### ISSUE TITLE
[MEMORY] TokensRegex SequencePattern.State memory optimization

### ISSUE THREAD

**Issue by lambdaupb** [stanfordnlp/CoreNLP#1000]
CoreNLP uses way too much memory to do what it does.

A HeapDump of an english model yields ~2mio instances of subclasses of SequencePattern.State.

Most instances have a `next` set of size 1 and a whole `LinkedHashSet` instance is allocated anyway (and wastes like 300byte each).

I'm not even sure if either iteration order or duplicate removal is strictly necessary for the states successor collection.

I propose doing something similar to the following:

```
Index: src/edu/stanford/nlp/ling/tokensregex/SequencePattern.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/edu/stanford/nlp/ling/tokensregex/SequencePattern.java	(revision 32d609a08ecb1cd905b09cf7712b8c58bfc13556)
+++ src/edu/stanford/nlp/ling/tokensregex/SequencePattern.java	(date 1582843145000)
@@ -1272,9 +1292,13 @@
      */
     protected void add(State nextState) {
       if (next == null) {
-        next = new LinkedHashSet<>();
-      }
-      next.add(nextState);
+        next = Collections.singleton(nextState);
+      } else if (next.getClass() != LinkedHashSet.class) {
+        next = new LinkedHashSet<>(next);
+        next.add(nextState);
+      } else {
+        next.add(nextState);
+      }
     }
 
     public <T> Object value(int bid, SequenceMatcher.MatchedStates<T> matchedStates) {

```

**Comment by lambdaupb** [comment]
<img width="821" alt="regexstate" src="https://user-images.githubusercontent.com/1890613/75498450-813f6180-59c7-11ea-8c8d-cf9f74ea6097.png">

**Comment by AngledLuffa** [comment]
Thanks, this looks like a great change.  I have integrated it.

**Comment by AngledLuffa** [comment]
Also, congrats!  You are our 1000th git issue.  You can claim your prize by PMing me your bank account info, personal address, pet names, and mother's maiden name.

**Comment by lambdaupb** [comment]
:P Heh, I'm glad it was useful.
