### ISSUE TITLE
[MEMORY] CoreMapNodePatternTrigger lowercaseStringTriggers values as List not HashSet

### ISSUE THREAD

**Issue by lambdaupb** [stanfordnlp/CoreNLP#1002]
The lowercaseStringTriggers
 in CoreMapNodePatternTrigger are in a 2d map, in which values are collected in some collection type. Default is HashMap.

Some instances have a very large secondary dim space of ~500k, Value count for a keypair (Class, String) are small (~1) however.

If Set semantics are not necessary (no pattern de-duplication needed), the TwoDimensionalCollectionValuedMap could be set to use ArrayLists for values, saving probably another offset of 500k HashSet/Map overheads.

```
Index: src/edu/stanford/nlp/ling/tokensregex/CoreMapNodePatternTrigger.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/edu/stanford/nlp/ling/tokensregex/CoreMapNodePatternTrigger.java	(revision 32d609a08ecb1cd905b09cf7712b8c58bfc13556)
+++ src/edu/stanford/nlp/ling/tokensregex/CoreMapNodePatternTrigger.java	(date 1582857025000)
@@ -18,7 +18,7 @@
   TwoDimensionalCollectionValuedMap<Class, Object, SequencePattern<CoreMap>> annotationTriggers =
           new TwoDimensionalCollectionValuedMap<>();
   TwoDimensionalCollectionValuedMap<Class, String, SequencePattern<CoreMap>> lowercaseStringTriggers =
-          new TwoDimensionalCollectionValuedMap<>();
+          new TwoDimensionalCollectionValuedMap<>(CollectionFactory.arrayListFactory(1));
 
   public CoreMapNodePatternTrigger(SequencePattern<CoreMap>... patterns) {
     this(Arrays.asList(patterns));
```

<img width="1090" alt="lowercaseStringTriggers" src="https://user-images.githubusercontent.com/1890613/75506845-8b6d5a00-59df-11ea-8d49-8bcdaa62ea3f.png">

**Comment by AngledLuffa** [comment]
Maybe some equivalent of singleton would work?  There's also an ArrayMap
option, but in cases where there actually are lots of keys that would blow
up runtime.  Sadly I think this is not as simple a fix as the other two.

What you're saying about Set semantics makes sense, but I don't know if
that's the case.

**Comment by lambdaupb** [comment]
Re-Reading my description makes me realize it was rather convoluted.

As I understand the `TwoDimensionalCollectionValuedMap<Class, String, SequencePattern<CoreMap>>`

maps from (Class) -> (String) -> Collection<SequencePattern<CoreMap>>.

the keyspace sizes are (as far as I can tell from one example) is:

{~1 Clas} -> {~500k Strings} -> {~1 SequencePattern},

so for one (Class, String) keypair, there is (in the order of) 1 Pattern.

The right-most collection of `lowercaseStringTriggers` seems to be only used in the same file
with
```java
    for (Class key:lowercaseStringTriggers.firstKeySet()) {
      Object value = in.get(key);
      if (value != null && value instanceof String) {
        Collection<SequencePattern<CoreMap>> triggered = lowercaseStringTriggers.get(key, ((String) value).toLowerCase());
        if (triggered != null) {
          triggeredPatterns.addAll(triggered);
        }
      }
    }
```

And the only collection semantic used here is iteration in addAll().

But this was a quick dive into the code, It is quite probable that I'm missing something.

**Comment by lambdaupb** [comment]
The reason I'm so keen on eliminating (Linked)HashMap/Sets is that they dominate the Heap.

<img width="1116" alt="maps" src="https://user-images.githubusercontent.com/1890613/75553357-8983b500-5a38-11ea-9a4d-7e5ffb6f894f.png">

Often they are read-only, wasting the pre-allocated array, usually of size 16.

**Comment by AngledLuffa** [comment]
Thanks for the clarification.

I grepped through the whole code and only found
CoreMapNodePatternTrigger.java as a place where lowercaseStringTriggers is
accessed.  Also, I only found the same file as a place where
TwoDimensional... is used in our publicly released code.  It might be
possible to change the underlying data structure to do the same trick with
singletons.

**Comment by AngledLuffa** [comment]
This *should* be improved with my latest change:

https://github.com/stanfordnlp/CoreNLP/commit/690697b9fe756b175a66a86a7ac46cba6c6d01a0

**Comment by AngledLuffa** [comment]
Also, I have no idea if the set semantics matter at all because I have close to 0 familiarity with tokensregex.  So I'm going to call it "good enough" now that things are significantly smaller
