### ISSUE TITLE
[MEMORY] Memory Tracking Issue

### ISSUE THREAD

**Issue by lambdaupb** [stanfordnlp/CoreNLP#1007]
#1000 
#1001 
#1002 
#1003 
#1004 

I have implemented some of those ideas on my fork:
https://github.com/lambdaupb/CoreNLP/tree/MEMORY

Those changes should *NOT* be merged, they are experiments.

I have ran experiments with the following result:

```
repo baseline: 			3785999536 3785MiB
With changes: 			3103041904 3103MiB (- 682MiB)
With float Classifier :		2204942344 2204MiB (-1581MiB)
With dedup on deserialize	2023875296 2023MiB (-1762MiB)
With SequencePatternExpr	2005381784 2005MiB (-1780MiB)
```

Tests were run with
```
JVM: OpenJDK 64-Bit Server VM (11.0.1+13, mixed mode)
Java: version 11.0.1, vendor Oracle Corporation
Java Home: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
JVM Flags: <none>
```

that is just loading the pipeline
```java
Properties props = new Properties();
props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,depparse,coref,quote");
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
Thread.sleep(10*1000*1000)
```

attaching VisualVM and forcing a few GCs and then looking at the used heap size.

**Comment by AngledLuffa** [comment]
I already did two of the changes you suggested.  They should be in the
public git repo...

https://github.com/stanfordnlp/CoreNLP/commit/f694e561a2dfd8592f09d5ef54c2fd39662b213e

https://github.com/stanfordnlp/CoreNLP/commit/772ca274c7b66afea9e11e1f4d115798919b5899


Would you test how much savings that gets you?

I'm also about to check in a change which makes CollectionValuedMap use a
singleton in the case of a single value in the underlying list or set.
Should get some more of the savings, hopefully.  I want to run our itest
suite first, though.

**Comment by lambdaupb** [comment]
772ca274c7b66afea9e11e1f4d115798919b5899 gives me 3325MiB Heap usage.

**Comment by lambdaupb** [comment]
String Dedup would be another 200MiB :D - And pretty easy and safely to do.

**Comment by lambdaupb** [comment]
So, there seem to be models that are serialized using java serialization.

For one, that makes it important to not break compatibility and also makes deduplication harder.

But with the change in https://github.com/stanfordnlp/CoreNLP/issues/1004#issuecomment-592810655 // https://github.com/lambdaupb/CoreNLP/commit/4ab64737eade49b42b4a6eb66ff2858d525b3cd6

The memory use dropped another 180MiB

**Comment by lambdaupb** [comment]
https://github.com/lambdaupb/CoreNLP/commit/a17283d7c767caba43e326de7de89ed9e71e575f
saves another ~20MiB.
Most SequencePattern$SequencePatternExpr have patterns.size = 1 and TokensRegexNERAnnotator knows the size beforehand anyway.

**Comment by AngledLuffa** [comment]
Doing some housekeeping - I think I'll close this issue and leave #1004 open as a reminder that there might be some way to reuse strings across NER models
