### ISSUE TITLE
pos-tagger cannot load models from stanford-corenlp-3.5.2-models.jar

### ISSUE THREAD

**Issue by konkol** [stanfordnlp/CoreNLP#101]
I use Stanford Core NLP in Java as a Maven dependency. I want to use the MaxentTagger with a model supplied in the stanford-corenlp-3.5.2-models package. The problem is that I cannot access this model through classpath. 

My code is 

	tagger = new MaxentTagger("/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger");

The file "/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" exists in the jar and should be loaded through classpath, but the following exception is thrown

	Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Unrecoverable error while loading a tagger model
		at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:770)
		at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:298)
		at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:263)
		at cz.zcu.kiv.nlp.semeval.cwi.features.POSFeature.<init>(POSFeature.java:24)
		at cz.zcu.kiv.nlp.semeval.cwi.CWIModel.train(CWIModel.java:60)
		at cz.zcu.kiv.nlp.semeval.cwi.TrainingCrossValidation.main(TrainingCrossValidation.java:51)
	Caused by: java.io.IOException: Unable to resolve "/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" as either class path, filename or URL
		at 	edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:481)
		at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:765)
		... 5 more

If I copy the model out of the jar and use e.g.

	tagger = new MaxentTagger("./english-left3words-distsim.tagger");

then everything works perfectly.

The problem is probably in the class IOUtils, method findStreamInClasspathOrFileSystem(String name).

In the line 

	InputStream is = IOUtils.class.getClassLoader().getResourceAsStream(name);

the returned classloader is probably the JarClassLoader which loaded the library (stanford-corenlp-3.5.2.jar) and it does not have access to other libraries.

This theory is supported by the following code

	InputStream stream = POSFeature.class.getResourceAsStream("/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger");
	System.out.println("Stream == null: " + (stream == null));
		
	tagger = new MaxentTagger("/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger");

which outputs

	Stream == null: false
	Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Unrecoverable error while loading a tagger model
	...
	Caused by: java.io.IOException: Unable to resolve "/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" as either class path, filename or URL

**Comment by J38** [comment]
You want "edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" instead of "/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" and it should work fine!

**Comment by konkol** [comment]
Thank you for the response. Your solution works.

I can see the problem now. The problem is not the code, but the documentation. The javadoc for MaxetnTagger(String) states that the argument can be classpath. I believe, that the standard definition for 'classpath' when loading resources is given by Resource.getResourceAsStream(). Check the following example:
		
	public static void main(String[] args) {
		try{
			MaxentTagger file = new MaxentTagger("./english-left3words-distsim.tagger");
			System.out.println("File OK");
		} catch(Exception e) {
			System.out.println("File ERROR");
		}
		
		try{
			InputStream stream = TestMain.class.getResourceAsStream("/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger");
			stream.read();
			stream.close();
			System.out.println("Stream with slash OK");
		} catch(Exception e) {
			System.out.println("Stream with slash ERROR");
		}
		
		try{
			InputStream stream = TestMain.class.getResourceAsStream("edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger");
			stream.read();
			stream.close();
			System.out.println("Stream without slash OK");
		} catch(Exception e) {
			System.out.println("Stream without slash ERROR");
		}
		
		try{
			MaxentTagger classpathWithSlash = new MaxentTagger("/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger");
			System.out.println("Classpath with slash OK");
		} catch(Exception e) {
			System.out.println("Classpath with slash ERROR");
		}
		
		try{
			MaxentTagger classpathWithoutSlash = new MaxentTagger("edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger");
			System.out.println("Classpath without slash OK");
		} catch(Exception e) {
			System.out.println("Classpath without slash ERROR");
		}
	}
	
The output is:
	
	File OK
	Stream with slash OK
	Stream without slash ERROR
	Classpath with slash ERROR
	Classpath without slash OK
	
You can see that your class does not follow this behavior. The documentation of IOUtils (which is hidden for the user of MaxentTagger) has an explicit note about this.

	Note that this method uses the ClassLoader methods, so that classpath 
	resources must be specified as absolute resource paths without a leading "/".

I believe, that this note should be repeated for all methods that use IOUtils and follow this (in my opinion) nonstandard behavior. The current documentation is confusing.

**Comment by konkol** [comment]
If I think about it, is there any good reason for this nonstandard behavior? It is possible to simply remove the leading '/' in IOUtils classpath check and all the methods would work as expected (at least for absolute classpaths) and if there is no leading '/', you can skip the classpath check.

**Comment by AngledLuffa** [comment]
We are opening the stream in IOUtils using

    InputStream is =
IOUtils.class.getClassLoader().getResourceAsStream(name);

We don't do anything to affect whether or not you can use a leading "/".

**Comment by konkol** [comment]
Check these methods from Java 8 source code for Class. 
	
     public InputStream getResourceAsStream(String name) {
        name = resolveName(name);
        ClassLoader cl = getClassLoader0();
        if (cl==null) {
            // A system class.
            return ClassLoader.getSystemResourceAsStream(name);
        }
        return cl.getResourceAsStream(name);
    }

    private String resolveName(String name) {
        if (name == null) {
            return name;
        }
        if (!name.startsWith("/")) {
            Class<?> c = this;
            while (c.isArray()) {
                c = c.getComponentType();
            }
            String baseName = c.getName();
            int index = baseName.lastIndexOf('.');
            if (index != -1) {
                name = baseName.substring(0, index).replace('.', '/')
                    +"/"+name;
            }
        } else {
            name = name.substring(1);
        }
        return name;
    }

You can see that there is a difference between Classloader.getResourceAsStream() and Class.getResourceAsStream(). My point is, that **you should specify in documentation**, what 'classpath' parameter in MaxentTagger really means. I was confused, because the Class version was used in 99% of cases in the code that I have seen so far. 

Both following methods work, but the name parameter is different. This is because ClassLoader supports only absolute paths while Class supports absolute and relative paths. (I understand that the relative paths in this case are nonsense.)
	
	InputStream is = IOUtils.class.getClassLoader().getResourceAsStream(name);
	InputStream is = IOUtils.class.getResourceAsStream(name);

**Comment by AngledLuffa** [comment]
The documentation for how to use the tagger is mostly in the class
documentation, which already has multiple examples of edu/stanford/nlp/...
without the leading slash.

http://www-nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/tagger/maxent/MaxentTagger.html

The classpath not being repeated in the constructor's documentation is
either an application of the DRY principle or an application of being lazy,
take your pick.

**Comment by 121eddie** [comment]
When I start the server, I encounter the same problem even through the slash is removed

**Comment by AngledLuffa** [comment]
You probably don't have the models jar in your classpath.

**Comment by 121eddie** [comment]
the 3 external files are all included in the sesnse that  i put them in the lib folder. 'english-left3words-distsim.tagger.props' is actually in the 'scripts' folder

**Comment by AngledLuffa** [comment]
Files like the models need to be included "in the sense" that they are in
the classpath.  Otherwise it doesn't work.

You haven't told us enough about your configuration or the error to fully
diagnose the problem, but I am 90% sure that either the model is not in the
classpath or you are not supplying the correct path to the model to the
program.

**Comment by 121eddie** [comment]
C:/CoreGit
    /models
          stanford-corenlp-models-current.jar
          stanford-english-corenlp-models-current.jar
          stanford-english-kbp-corenlp-models-current.jar
    /lib
   etc.


CLASSPATH: C:\CoreNLP;C:\CoreNLP\lib;C:\CoreNLP\liblocal;C:\CoreNLP\models;

**Comment by AngledLuffa** [comment]
Assuming CoreGit in your listing is a typo, you need to either do this

C:\CoreNLP\models\stanford-corenlp-models-current.jar;the next models file
goes here;etc etc

or

C:\CoreNLP\models\*

sometimes Windows dislikes the *

**Comment by 121eddie** [comment]
I corrected the path above.
Now , 
`echo %CLASSPATH%
>>>C:\CoreGit;C:\CoreGit\lib;C:\CoreGit\liblocal;C:\CoreGit\models\stanford-corenlp-models-current.jar;C:\CoreGit\models\stanford-english-corenlp-models-current.jar;C:\CoreGit\models\stanford-english-kbp-corenlp-models-current.jar;C:\CoreGit\models\;`

The error message is exactly the same

**Comment by AngledLuffa** [comment]
What is the output of

jar tvf C:\CoreGit\models\stanford-corenlp-models-current.jar | find
"lexparser"
jar tvf C:\CoreGit\models\stanford-english-corenlp-models-current.jar |
find "lexparser"

**Comment by 121eddie** [comment]
the files are there
`1883795 Wed May 22 18:46:30 CST 2019 edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz`

`64439692 Wed May 22 18:39:40 CST 2019 edu/stanford/nlp/models/lexparser/wsjRNN.ser.gz
6225813 Wed May 22 18:39:40 CST 2019 edu/stanford/nlp/models/lexparser/wsjFactored.ser.gz
6873217 Wed May 22 18:39:40 CST 2019 edu/stanford/nlp/models/lexparser/englishFactored.ser.gz
1769534 Wed May 22 18:39:40 CST 2019 edu/stanford/nlp/models/lexparser/englishPCFG.caseless.ser.gz
65000940 Wed May 22 18:39:40 CST 2019 edu/stanford/nlp/models/lexparser/englishRNN.ser.gz
1883795 Wed May 22 18:39:38 CST 2019 edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz
1630419 Wed May 22 18:39:40 CST 2019 edu/stanford/nlp/models/lexparser/wsjPCFG.ser.gz`

**Comment by AngledLuffa** [comment]
```
java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators parse -file input.txt

java -cp "*"

-cp "*"
```

Hol' up

**Comment by 121eddie** [comment]
1) Unable to open "edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz" as class path, filename or URL
2-3) are not valid commands

**Comment by AngledLuffa** [comment]
You are clobbering your system classpath with the `-cp "*"` flag

**Comment by 121eddie** [comment]
but if i remove the latter, it goes back to:
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP

**Comment by AngledLuffa** [comment]
Similar to my earlier suggestion of

C:\CoreNLP\models\*

you need to include the jars with Stanford's code and all jars in lib\* and liblocal\* in your classpath.  You will also need "." or wherever you put your own code.  I suggest using wildcards, but as I said, it sometimes takes some figuring out with Windows.  I leave it up to you.

**Comment by 121eddie** [comment]
Thank you very much for your help. It was all a matter of adding wildcards to the %CLASSPATH% and avoiding any overwrite with -cp
