### ISSUE TITLE
3.9.1version add KBP ner models for Chinese and Spanish？How to use kbp ner models？

### ISSUE THREAD

**Issue by tanzf** [stanfordnlp/CoreNLP#1018]
When I visit https://nlp.stanford.edu/software/CRF-NER.html，I found Stanford Named Entity Recognizer (NER) add KBP ner models for Chinese and Spanish In version 3.9.1.I want to know whether KBP ner model is a CRF model for training under KBP data set or improvement of the old CRF model？How to use kbp ner models？

**Comment by AngledLuffa** [comment]
KBP is trying to extract relation information from the text.  It makes use of the NER models rather than replace them.
