### ISSUE TITLE
pycorenlp sentiment annotation outputs a string instead of json

### ISSUE THREAD

**Issue by ugolbck** [stanfordnlp/CoreNLP#1023]
Hi, I'm trying to POS tag, lemmatize and do sentiment analysis on some text, but whenever I use the **sentiment** tool something goes wrong and instead of a json output I get a string. 
I get a similar error when trying the sentiment in a browser at http://localhost:9000/ where the output seems to be correct but in a red box and without the usual visuals.

I downloaded the latest version of CoreNLP on [the official website](https://stanfordnlp.github.io/CoreNLP/download.html), I am running the server with `java -mx6g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -timeout 10000` without any problem.

The code I am trying is 
`from pycorenlp import StanfordCoreNLP`
`nlp_wrapper = StanfordCoreNLP('http://localhost:9000')`
`doc = "I like this chocolate."`
`annot_doc = nlp_wrapper.annotate(doc,`
    `properties={`
       `'annotators': 'sentiment',`
       `'outputFormat': 'json',`
      ` 'timeout': 10000,`
    `})`

I run the code above on:
macOS 10.15.3
pycorenlp 0.3.0
python 3.6
java 8

Thank you for your help!

**Comment by AngledLuffa** [comment]
What's the error?

**Comment by ugolbck** [comment]
Actually there's no error per say, the output is just a `str` instead of `json disct`. When I query the server with **sentiment** only I get these answers:

> [pool-1-thread-1] INFO CoreNLP - [/0:0:0:0:0:0:0:1:53381] API call w/annotators tokenize,ssplit,pos,parse,sentiment
I like this chocolate. This chocolate is not good. The chocolate is delicious. Its a very tasty chocolate.
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator sentiment

**Comment by AngledLuffa** [comment]
Sorry for the late reply.  I was trying reproduce a similar effect in
stanza before I realized you were talking about pycorenlp.  I suggest
trying the pycorenlp help boards instead.

I don't know how the pycorenlp internals handle it, but in corenlp there is
no concept of using just the sentiment annotator.  It must be hiding all of
the rest of the output somehow.

**Comment by ugolbck** [comment]
Actually the problem seems to come from the parser, the error I get with `pycorenlp` comes from the `json` module which expects an ',' in the middle of the **sentimentDistribution** values of the output, so I believe it's just a collateral side effect.

When using the parser in a browser on http://localhost:9000/ something goes wrong with certain sentences when using "sentiment". For example, the sentences "i hate you" and "it is nice outside" result in a text output in a red box in a browser instead visual BRAT trees, and collaterally raises a json error. With the sentence "i hate you so much" it works perfectly fine though, tree representations in the browser and no json exception.

From the json error I can narrow the problem down to the values in the **sentimentDistribution**, but I don't really what to do from there...

**Comment by AngledLuffa** [comment]
I'm not encountering this issue with the release candidate for the next
version.  Perhaps whatever it was has been fixed...

**Comment by AngledLuffa** [comment]
Actually, I can't even reproduce it with the previous release.  I'm using Windows, though, in case that changes anything.

**Comment by danilvalov** [comment]
I have the same problem.
I get the following response:
![image](https://user-images.githubusercontent.com/2463767/86136799-26448500-baf5-11ea-986c-3371ce0de53c.png)

As you can see comma is used as a separator for the number and element of the array (thanks for the java language settings).
The number `0039390735794` is incorrect for json parser, so...

@ugolbck You just need to change DecimalFormatSymbols.

@AngledLuffa Can we set the decimal separator forcibly in the app?

**Comment by AngledLuffa** [comment]
This looks like a locale issue, which has hopefully been addressed in the
github version.  If you aren't up for recompiling, you can get around it by
setting the locale to US or using a format other than json.  Note to self:
this is another minor fix going out with the next minor version release.
