### ISSUE TITLE
A Web Server?

### ISSUE THREAD

**Issue by steve3p0** [stanfordnlp/CoreNLP#1028]
Is it absolutely necessary to have a web server running to use Stanford's CoreNLP parser?  Why?

**Comment by AngledLuffa** [comment]
What use case are you looking for?

**Comment by AngledLuffa** [comment]
Do you have a followup on this?  Are you asking why there's the ability to connect to corenlp using a browser when running the corenlp server, possibly as a security issue?  Are you asking why the published method for getting java results to python is via web server?  This question was kind of vague.
