### ISSUE TITLE
Use tokenRegex when ruleType is text

### ISSUE THREAD

**Issue by xcTorres** [stanfordnlp/CoreNLP#1029]
My question is that if I want to match a string pattern in a sentence, not a token sequence, can anyone help me to solve it?  

Example: 
If the input is rt. 42,  there are 2 tokens, so I can use (/rt[.]?/  /\d{1,4}/) to tag rt.  as RT_prefix, 42 as RT_number.  

But if the input is rt42, there is only one token, so how can I extract them as rt => RT_prefix, 42=>RT_number with Stanford NLP

**Comment by AngledLuffa** [comment]
It sounds like you need to split the tokens first before processing them
with tokensregex.  You can't assign two different labels to two different
parts of the same token.  (Actually, I don't know if it's possible to
assign lists of types using tokensregex, in which case you'd be able to
assign both RT_prefix and RT_number to rt42.  I suspect not)

**Comment by xcTorres** [comment]
Got it. So how to use regex for a string like java built-in regex, not for tokens in this library? 

is ruleType = text ?

**Comment by J38** [comment]
See this page for extensive write up on TokensRegex: https://stanfordnlp.github.io/CoreNLP/tokensregex.html

There is a section detailing how to do string matching called "Example 3: Extract Quotes"
