### ISSUE TITLE
Number of vertices in dependency graph not always (number of tokens + 1)

### ISSUE THREAD

**Issue by aschild** [stanfordnlp/CoreNLP#1030]
I am using Core NLP version 3.9.2 from the Maven repo. I ran the following Core NLP pipeline:

The sentence: "Then down thru Snowgrass Flats to Cispus Pass and on to Sheep Lake."

        String text = "Then down thru Snowgrass Flats to Cispus Pass and on to Sheep Lake.";
        Properties properties = new Properties();
        properties.setProperty("annotators", "tokenize,ssplit,pos,lemma,parse,depparse");

        StanfordCoreNLP pipeline = new StanfordCoreNLP(properties);
        CoreDocument doc = new CoreDocument(text);
        pipeline.annotate(doc);
        CoreSentence sentence = doc.sentences().get(0);
        assertEquals(sentence.tokens(), sentence.dependencyParse().vertexListSorted());

The assertion failed because token formats are not the same as vertex formats, but the sizes were also not the same. Specifically, there should be a token for each vertex. However, there was duplication. Instead, the output was as follows:

`org.opentest4j.AssertionFailedError: 

Expected :[Then-1, down-2, thru-3, Snowgrass-4, Flats-5, to-6, Cispus-7, Pass-8, and-9, on-10, to-11, Sheep-12, Lake-13, .-14]

Actual   :[Then/RB, Then/RB''''''''', Then/RB'''''''''', Then/RB''''''''''', Then/RB'''''''''''', down/IN, thru/IN, Snowgrass/NNP, Flats/NNP, to/TO, Cispus/NNP, Pass/NN, and/CC, on/IN, to/TO, Sheep/NNP, Lake/NNP, ./.]`

In particular, the word "Then" is repeated 4 times, with apostrophes added after the tag. I also tried doing the same using the Simple API (not the pipeline), and the output was normal (no bug).

**Comment by aschild** [comment]
Also, in case you are curious, I parsed about 2 million sentences and this bug happened on about 1% of the sentences.

**Comment by AngledLuffa** [comment]
Intentionally copied nodes, most likely.  The same word is connected to
several different words (each of the prepositions is my guess in this case
without looking at the actual result)

**Comment by aschild** [comment]
Thanks for your quick response! Why would the nodes by intentionally copied? If a word was connected to multiple words, shouldn't that just be captured by the edges in the graph? Why would there be more than one dependency graph node for a given token? Thanks for your help!

**Comment by AngledLuffa** [comment]
There's a bit of an explanation in here at the end of page 3:

https://nlp.stanford.edu/~sebschu/pubs/schuster-manning-lrec2016.pdf

dependencyParse() is shorthand for the enhanced deps:

  /** dependency parse **/
CoreSentence:
  public SemanticGraph dependencyParse() {
    return
sentenceCoreMap.get(SemanticGraphCoreAnnotations.EnhancedPlusPlusDependenciesAnnotation.class);
  }
