### ISSUE TITLE
training a custom NER :  java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by dineshggaonkar** [stanfordnlp/CoreNLP#1038]
facing out of memory issue even though the training corpus is very small (about 1 mb)
tried increasing memory allocation (mx7g) but this doesnt seem to be enough for training . please suggest some way to restrict this heap usage..below is the error log 

Invoked on Wed Apr 29 13:41:42 IST 2020 with arguments: -prop prop.txt
usePrevSequences=true
useClassFeature=true
useTypeSeqs2=true
useSequences=true
wordShape=chris2useLC
useTypeySequences=true
useDisjunctive=true
noMidNGrams=true
serializeTo=dummy-ner-model-arabic.ser.gz
maxNGramLeng=3
useNGrams=true
usePrev=true
useNext=true
maxLeft=1
trainFile=train_arabic.TSV
map=word=0,answer=1
useWord=true
useTypeSeqs=true
numFeatures = 648062
Time to convert docs to feature indices: 2.8 seconds
numClasses: 26 [0=O,1=B-MIS0,2=B-MIS1,3=B-MIS3,4=B-MIS2,5=I-MIS2,6=I-MIS0,7=B-PER,8=I-PER,9=B-MIS,10=I-MIS1,11=B-ORG,12=I-ORG,13=B-LOC,14=I-LOC,15=I-MIS3,16=IO,17=I--ORG,18=B-MISS1,19=OO,20=B-MIS-2,21=B-MIS-1,22=B-ENGLISH,23=I-MIS,24=B-SPANISH,25=B-MIS1`]
numDocuments: 1
numDatums: 116149
numFeatures: 648062
Time to convert docs to data/labels: 1.6 seconds
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at edu.stanford.nlp.ie.crf.CRFLogConditionalObjectiveFunction.empty2D(CRFLogConditionalObjectiveFunction.java:908)
        at edu.stanford.nlp.ie.crf.CRFLogConditionalObjectiveFunction.<init>(CRFLogConditionalObjectiveFunction.java:144)
        at edu.stanford.nlp.ie.crf.CRFLogConditionalObjectiveFunction.<init>(CRFLogConditionalObjectiveFunction.java:125)
        at edu.stanford.nlp.ie.crf.CRFClassifier.getObjectiveFunction(CRFClassifier.java:1821)
        at edu.stanford.nlp.ie.crf.CRFClassifier.trainWeights(CRFClassifier.java:1827)
        at edu.stanford.nlp.ie.crf.CRFClassifier.train(CRFClassifier.java:1742)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:770)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:758)
        at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3011)

**Comment by AngledLuffa** [comment]
Generally it uses a ton of memory, so you may need to supply more.  Another
thing I learned recently is the training code now automatically uses as
many threads as possible, and each thread uses another large chunk of
memory.  You may have some luck setting the number of threads to a smaller
number, possibly as low as 1, if you don't have more memory to throw at the
problem.

**Comment by dineshggaonkar** [comment]
hello @AngledLuffa
number of threads ...is that supposed to be defined in prop.txt?

**Comment by AngledLuffa** [comment]
I was kind of hoping I wouldn't have to look up the exact parameter name


try

`-multiThreadGrad` at the command line    or a   `multiThreadGrad` property

**Comment by dineshggaonkar** [comment]
> I was kind of hoping I wouldn't have to look up the exact parameter name try `-multiThreadGrad` at the command line or a `multiThreadGrad` property

facing memory issues even after multiThreadGrad inclusion

**Comment by AngledLuffa** [comment]
Oh, something else worth noting is that having 26 classes will greatly
increase the amount of memory used.  Reducing that will help as well.

Ultimately 7g for that many classes and that many data items is probably
not enough.

**Comment by dineshggaonkar** [comment]
thanks @AngledLuffa  ..reducing number of classes actually helped in reducing memory usage ..
i brought down number of classes to 8 from 26..
and do we have a control over number of iterations ? the model has not yet stopped training ..the eval_score is hovering around some value

**Comment by dineshggaonkar** [comment]
> thanks @AngledLuffa ..reducing number of classes actually helped in reducing memory usage ..
> i brought down number of classes to 8 from 26..
> and do we have a control over number of iterations ? the model has not yet stopped training ..the eval_score is hovering around some value

i think the model uses this ( | newest_val - previous_val | / |newestVal| < TOL) to converge

**Comment by AngledLuffa** [comment]
I can't tell if this most recent comment means you figured it out or not.
Just in case, the flag you want is

-tolerance   (default 0.0001)

It's not really documented anywhere.  Honestly it's probably better just to
wait for it to converge.
