### ISSUE TITLE
Stop StanfordCoreNLP from Connecting to StanfordCoreNLP server

### ISSUE THREAD

**Issue by ajesujoba** [stanfordnlp/CoreNLP#1039]
Whenever I create StanfordCoreNLP for a parsing task in Python, 
```
StanfordCoreNLP('stanford-corenlp-full-2020-04-20', lang='en')
```
I get this logging 
```
Initializing native server...
java -Xmx4g -cp "stanford-corenlp-full-2020-04-20/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9032
Server shell PID: 11991
The server is available.
```
1. Can StanfordCoreNLP work in python offline without connecting to the server?
2. Is there a command to stop the logging to screen in stanfordCoreNLP?
On applying

On applying the parser, `self.nlp_src.parse(sentence)`, I got another logging of the form below:

```{'properties': "{'annotators': 'pos,parse', 'outputFormat': 'json'}", 'pipelineLanguage': 'en'}```

3. Is there a way to stop the above logging too?

Lastly, I got this error in the process of using the parser in the stanford coreNLP as explained above. 

```requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9032): Max retries exceeded with url: /?properties=%7B%27annotators%27%3A+%27pos%2Cparse%27%2C+%27outputFormat%27%3A+%27json%27%7D&pipelineLanguage=en (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe04121d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))```

4. What is the cause of this error? What do I do to prevent this?

**Comment by AngledLuffa** [comment]
In terms of getting Java CoreNLP results to python, especially Stanza, the only method we currently support is via server.  This python client is included as part of the Stanza download:

https://github.com/stanfordnlp/stanza

That module has a be_quiet=True parameter you can set.  It looks like that might not be what you're using, though, in which case we aren't really able to help you.
