### ISSUE TITLE
QUESTION: How can I extract clauses and dependent (subordinate) clauses for Chinese

### ISSUE THREAD

**Issue by abhisheknovoic** [stanfordnlp/CoreNLP#1041]
Hello,

 I am working with extracting clauses for Chinese. I am using CoreNLP 4.0. I am also looking at this link 

> http://www.surdeanu.info/mihai/teaching/ista555-fall13/readings/PennTreebankConstituents.html

that lists the type of clauses. I used the terms S, SBAR, SBARQ, SINV, and SQ to check for all types of clauses in the constituency parse tree of English sentences.

However, where can I find the terminologies or the names of the nodes in a constituency parse tree for Chinese? 

I tried with a sample Chinese sentence and the constituency parse tree doesn't seem to have any of the above tags. However, I found one tag 

> IP

which means Independent clause? (Please correct me if I am wrong here).

I am looking for how to extract clauses and then specifically subordinate clauses for Chinese. Any help would be appreciated.

Thanks

**Comment by AngledLuffa** [comment]
https://repository.upenn.edu/cgi/viewcontent.cgi?article=1040&context=ircs_reports

**Comment by abhisheknovoic** [comment]
Wov @AngledLuffa , thanks a ton. That is super helpful!

Just curious, is there a place I could find this kind of document for all 6 languages supported by CoreNLP? Thanks!

**Comment by AngledLuffa** [comment]
I found that one via google search

**Comment by abhisheknovoic** [comment]
Thanks @AngledLuffa .
