### ISSUE TITLE
LEFT and RIGHT cases do the same thing

### ISSUE THREAD

**Issue by khatchad** [stanfordnlp/CoreNLP#1042]
https://github.com/stanfordnlp/CoreNLP/blob/e35d75d45b4b609aaadde43a12020285a1475139/src/edu/stanford/nlp/parser/shiftreduce/BinaryTransition.java#L211

The above case is redundant. Please see [this](https://github.com/stanfordnlp/CoreNLP/commit/7299f6ab5f6e2f25299ebed9361de7baf3aa63ee#r39266032) conversation. It could be written as:
```java
@Override
  public int hashCode() {
    switch(side) {
    case LEFT:
    case RIGHT:
      return 97197711 ^ label.hashCode();
```

**Comment by AngledLuffa** [comment]
Other options would be to just drop the switch altogether, or possibly to return different hash codes.  I'm not sure what the effects of that are, so it would take some investigation.

**Comment by AngledLuffa** [comment]
This was fixed in

https://github.com/stanfordnlp/CoreNLP/commit/e7e08c5f954573d8ee72782d69aa0ba7a3f800b0

Updated models will be enclosed in the next release.  Thanks for the note!
