### ISSUE TITLE
Sentiment Model training; Create Input data for BuildBinarizedDataset.java

### ISSUE THREAD

**Issue by ngigiwaithaka** [stanfordnlp/CoreNLP#1043]
I am curious to know whether there is any tool in CoreNLP, or otherwise, that can create from any input text, an input format that would be valid for BuildBinarizedDataset.java

If none, is there any documentation on how text data with the requisite sentiments tagged gets converted to a format acceptable to BuildBinarizedDataset.java to allow one to build their own?

**Comment by AngledLuffa** [comment]
You can take a text file, add labels, and then add blank lines after each labeled line.  Seems pretty straightforward to me.

**Comment by ngigiwaithaka** [comment]
> You can take a text file, add labels, and then add blank lines after each labeled line. Seems pretty straightforward to me.

Perhaps my question was not clear enough...

Looking at the code in BuildBinarizedDataset.java, you have an example of the following sentence...

`Today is not a good day`

Which gets turned into the following input which is what is passed onto BuildBinarizedDataset.java
```
1 Today is not a good day.<br>
3 good<br>
3 good day <br>
3 a good day <br>
<br>
```

My questions are:
1. What is the algorithm that translates the input sentence into the format shown above?
2. Is there a library in CoreNLP that given input sentences can generate such a format?
3. What do the values 1 & 3 stand for?

You have done some great work, from which we can build on, all we need is a few pointers here and there to figure out how everything plugs in together.

Thanks...

**Comment by AngledLuffa** [comment]
I added some more documentation to BuildBinarizedDataset which will
hopefully cover those questions.


https://github.com/stanfordnlp/CoreNLP/commit/5ac30445fc72b20e2815cda1b45e6646341ab6e5#diff-fda4d5fe07787a84d4d35d626f95418e

**Comment by ngigiwaithaka** [comment]
> I added some more documentation to BuildBinarizedDataset which will hopefully cover those questions. [5ac3044#diff-fda4d5fe07787a84d4d35d626f95418e](https://github.com/stanfordnlp/CoreNLP/commit/5ac30445fc72b20e2815cda1b45e6646341ab6e5#diff-fda4d5fe07787a84d4d35d626f95418e)

Excellent, having a look, a lot more detailed.

Thanks...
