### ISSUE TITLE
Tokenization in version 4.0.0 does different things with dashes.

### ISSUE THREAD

**Issue by davidtrobinson** [stanfordnlp/CoreNLP#1045]
After upgrading from version 3.9.2 of Stanford core nlp to version 4.0.0 we observed that the social security number in text got split differently. For example, 555-55-5555 instead of being one token became two, 555 and 55-555. 

This broke our SSN NER Rule that detects Social Security Numbers.

**Comment by J38** [comment]
We have changed the tokenization standard in Stanford CoreNLP 4.0.0 to UD 2.0, which for better or worse involves more splitting on hyphens.

That being said, we do have some patterns that don't split, and I would've thought that an SSN# type pattern would not get split, so we may need to fix this issue.

You can revert to older tokenization by setting `tokenize.options` to `ptb3Escaping=true`

**Comment by J38** [comment]
I think this is just a bug, and we should probably add the SSN numerical pattern as well. Note that phone numbers don't get split for example...

**Comment by davidtrobinson** [comment]
Thanks for looking at this. It does seem like a bug if it handles phone numbers.

**Comment by AngledLuffa** [comment]
https://github.com/stanfordnlp/CoreNLP/commit/cc976dcf6fd5ef092972236be66970075ed5d03b

**Comment by AngledLuffa** [comment]
You can rebuild with this source change to get the tokenization of SSNs that you want
