### ISSUE TITLE
Sentiment Analysis Result Categories

### ISSUE THREAD

**Issue by bconlon3** [stanfordnlp/CoreNLP#1047]
I was wondering how Core-NLP differentiates between its different sentiment result categories.   Specifically, what is the difference between "very negative" and just "negative"?  Is the method comparable to VADER's composite score?

**Comment by AngledLuffa** [comment]
The model is trained on data from movie reviews, with the rating being the
average rating given by a bunch of users.  Generally people tended to avoid
the extremes so it has to be really noticeable to achieve "very negative"
or "very positive"
