### ISSUE TITLE
Can't download CoreNLP

### ISSUE THREAD

**Issue by zhangyilun** [stanfordnlp/CoreNLP#1048]
Is the download server down? https://stanfordnlp.github.io/CoreNLP/download.html

**Comment by AngledLuffa** [comment]
No, it's working for me.  Are you able to access other github.io projects
or other files on nlp.stanford.edu?  We have occasionally heard from people
with difficulty reaching those sites

**Comment by zhangyilun** [comment]
i have no problem accessing github pages. I can also get to the page I posted above, but the download button doesn't start the download. I also can't open the maven page.

**Comment by AngledLuffa** [comment]
This is the direct link:

http://nlp.stanford.edu/software/stanford-corenlp-latest.zip

You are saying that does not work?  What happens?

**Comment by zhangyilun** [comment]
It's just sitting there (Chrome showing waiting for nlp.stanford.edu... at bottom left) and not starting the download. I also tried wget from terminal, and no speed.

**Comment by AngledLuffa** [comment]
There's probably some kind of firewall between you and the download, then.
Where are you located?

What if you go here?

https://nlp.stanford.edu/

**Comment by zhangyilun** [comment]
There was no problem reaching the website, only the file download didn't work (but used to work last week). I tried to restart my laptop and it's now working. Probably some setting wasn't correct before.
