### ISSUE TITLE
NER not recognizing URL's in 4.0.0 !!!?

### ISSUE THREAD

**Issue by J38** [stanfordnlp/CoreNLP#1049]
https://stackoverflow.com/questions/62058272/english-ner-annotator-for-stanford-corenlp-v-4-0-0-missing-some-entity-types-com

**Comment by J38** [comment]
I ran an example on a URL and failed to get it recognized.

**Comment by AngledLuffa** [comment]
Alright, as a first step the tokenizer is still treating the URL as a
single token, so probably it is further downstream from there

**Comment by AngledLuffa** [comment]
https://github.com/stanfordnlp/CoreNLP/commit/ab31288c5d91615bfb22a8845c90b648f5a93dcb

that was hard to find
