### ISSUE TITLE
Comparing CoreNLP and VADER 

### ISSUE THREAD

**Issue by bconlon3** [stanfordnlp/CoreNLP#1055]
Is there any way to compare CoreNLP sentiment categories (Very Negative, Negative, ect.) to VADER composite scores (-1 to 1)?  If you have any familiarity with VADER, which composite scores would correspond to the five CoreNLP sentiment categories?  Any help would be greatly appreciated.

**Comment by AngledLuffa** [comment]
As a belated response to this, these are two completely different analyses.  VADER is on a per-word basis, the model is predicting an entire sentence's score, and there's no guaranteed correspondence between the scales.
