### ISSUE TITLE
Request to Java server returning invalid json in a localized environment

### ISSUE THREAD

**Issue by AMArostegui** [stanfordnlp/CoreNLP#1056]
OS: Windows 10 Pro (x64)
Locale: es-ES
CoreNLP: 4.0.0
Java: 1.8.0_251, HotSpot 64-Bit

**Steps to reproduce:**

1) Open a CMD shell 
2) Run server with _java -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000_
3) Download Stanza CoreNLP client example: https://github.com/stanfordnlp/stanza/blob/master/demo/corenlp.py
4) Open another CMD shell and run the python source file above. I don't think it matters, but I'm using Python 3.7.1 (AMD64) and Stanza 1.0.1

**Result:**

_Line 77 (matches = client.tokensregex(text, pattern))_ throws exception _json.decoder.JSONDecodeError_ due to an invalid json being parsed.

The returned JSON contains a serialized floating point value, using a comma as a decimal separator.

```
  "entitymentions": [  {
		  "docTokenBegin": 0,
		  "docTokenEnd": 2,
		  "tokenBegin": 0,
		  "tokenEnd": 2,
		  "text": "Chris Manning",
		  "characterOffsetBegin": 0,
		  "characterOffsetEnd": 13,
		  "ner": "PERSON",
		  "nerConfidences": {
			  "PERSON": 0,
			99674529762772 
		}
```
		
**Workaround:**

If we run the server using the US localization like this: _java -Duser.language=en-US -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000_
we get no error.

Although not tried, the bug is likely to be reproduced on any machine, using this workaround, with spanish localization: es-ES.

**Comment by AngledLuffa** [comment]
Thank you for reporting this!  I believe it is fixed with this change: https://github.com/stanfordnlp/CoreNLP/commit/5e5a47a3c783d7cc4c56fc1406d638ad1cd5fa03
