### ISSUE TITLE
The sentiment output result from -stdin differs from the when input is read from a file

### ISSUE THREAD

**Issue by paris007** [stanfordnlp/CoreNLP#106]
I am not sure whether this issue is related to how the sentiment tool works or it is just a weird thing that stdin does. Regardless, I thought I should bring this up as a point of awareness for researchers analyzing the output results. 

Here is a toy snapshot of a comment from reddit analyzed via -stdin vs. being read from a .txt file. Please find the differences: 

<img width="1338" alt="screen shot 2015-11-19 at 12 49 22 pm" src="https://cloud.githubusercontent.com/assets/7051103/11283941/02125028-8ebc-11e5-9cc7-ac3bd9fa8fa5.png">

As you many notice, on the left side we have a sequence of  
[Negative, Neutral, Negative, Very negative, Negative, Neutral, Negative, Negative, Negative]
but on the right side we have the following sequence:
[Negative, Neutral, Neutral, Negative, Negative, Negative, Negative,  Negative, Negative, Neutral, Negative]

If you would like to try out yourself, here is the sample text: 
"States don't own.They just control.\n\n&gt;The Federal Reserve System (also known as the Federal Reserve  and informally as the Fed) is the central banking system of the United States. It was created on December 23  1913  with the enactment of the Federal Reserve Act  largely in response to a series of financial panics  particularly a severe panic in 1907.234567 Over time  the roles and responsibilities of the Federal Reserve System have expanded  and its structure has evolved.
38 Events such as the Great Depression in the 1930s were major factors leading to changes in the system.9The U.S. Congress established three key objectives for monetary policy in the Federal Reserve Act: Maximum employment  stable prices  and moderate long-term interest rates.
10 The first two objectives are sometimes referred to as the Federal Reserve's dual mandate.11 Its duties have expanded over the years  and today  according to official Federal Reserve documentation  include conducting the nation's monetary policy  suvising and regulating banking institutions  maintaining the stability of the financial system and providing financial services to depository institutions  the U.S. government  and foreign official institutions.12 The Fed also conducts research into the economy and releases numerous publications  such as the Beige Book.\n\nIt is a private bank  created by an act of the state  in order to achieve the states mandated goals. It is the state. At any moment congress decides  it can take money printing away from the fed  or eliminate the fed all together.The fact that the state CHOSE to use a private bank is mostly irrelevant. The federal reserve bank is a branch of the government that they have found a legal way to hide from public audit through private ownership."

**Comment by J38** [comment]
I think the issue here is just that with `-stdin` you have to enter one sentence per line whereas if you submit info via `.txt` file the text will be sentence split.
