### ISSUE TITLE
Keys are not being serialized: class edu.stanford.nlp.ling.CoreAnnotations$ArabicSegAnnotation

### ISSUE THREAD

**Issue by arghodayah** [stanfordnlp/CoreNLP#1060]
I'm trying to start CoreNLPClient with Arabic models, but when it tries to serialize the results it throws the following exception error (it works for English):

> Starting server with command: java -Xmx16G -cp /stanford-corenlp-4.0.0/* edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 30000 -threads 5 -maxCharLength 100000 -quiet True -serverProperties StanfordCoreNLP-arabic.properties -preload tokenize,ssplit,pos,lemma,ner,parse,coref

Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/stanza/server/client.py", line 398, in _request
    r.raise_for_status()
  File "/venv/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/?properties=%7B%27outputFormat%27%3A+%27serialized%27%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "corenlp_test.py", line 13, in <module>
    ann = client.annotate(output_format="serialized", text=text)
  File "/venv/lib/python3.6/site-packages/stanza/server/client.py", line 470, in annotate
    r = self._request(text.encode('utf-8'), request_properties, **kwargs)
  File "/venv/lib/python3.6/site-packages/stanza/server/client.py", line 404, in _request
    raise AnnotationException(r.text)
stanza.server.client.AnnotationException: edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer$LossySerializationException: Keys are not being serialized: class edu.stanford.nlp.ling.CoreAnnotations$ArabicSegAnnotation

Please note that it gives correct output when output_format="text", the error throws only when it's serialized

**Comment by AngledLuffa** [comment]
Thanks!  This will either be fixed in the next version, or you can use the
github codebase

**Comment by arghodayah** [comment]
So it's solved in github codebase?

**Comment by AngledLuffa** [comment]
Yes

**Comment by arghodayah** [comment]
Thanks.
But how how to build the entire repo?

**Comment by AngledLuffa** [comment]
ant or maven?

Maybe we should put out a small update soon anyway

**Comment by arghodayah** [comment]
Maven

**Comment by AngledLuffa** [comment]
There should be a `pom.xml` included in the distribution.  I personally haven't used this in a long time, but you should be able to

- unzip the file `stanford-corenlp-4.0.0-sources.jar`
- possibly move the `edu` directory to `src/edu`
- run maven using the provided `pom.xml`
- if that successfully rebuilds a `classes` directory, use `jar` to rebuild that into a new `stanford-corenlp-4.0.0.jar`  Everything should work as before (including the bug, of course)
- If those steps work, copy the files changed in this commit to overwrite the existing files in `src`, then rebuild again: https://github.com/stanfordnlp/CoreNLP/commit/61aad3e2f281de7ebe6182f6838427e5a498dea3

If this works out, it should no longer have this problem.  If you're not getting it to work, I'll see what we can do about releasing a maintenance release sooner than expected.  You're not the only one who has encountered this recently:

https://github.com/stanfordnlp/stanza/issues/362

**Comment by ahmedalbahnasawy** [comment]
@AngledLuffa Thank you for your help 
I built the project using maven. 
I set the variables environment and this is my configs
Maven home: /usr/local/apache-maven-3.6.3
Java version: 1.8.0_252, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
I downloaded Arabic jar model and added this part to pom.xml file
```
<dependency>
    <groupId>edu.stanford.nlp</groupId>
    <artifactId>stanford-corenlp</artifactId>
    <version>4.0.0</version>
    <classifier>models-arabic</classifier>
</dependency>
```
then mvn compile and it built successfully.  
java -mx3g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-arabic.properties -file arabic.txt -outputFormat text 
The output file contains everything such as pos and constituency parse **except** coreference resolution 
[arabic_output.txt](https://github.com/stanfordnlp/CoreNLP/files/4825211/arabic_output.txt)
Any suggestions !

**Comment by AngledLuffa** [comment]
I don't believe we have models for Arabic.  If you know of data sources for
Arabic coref, you could try training models using these instructions:

https://stanfordnlp.github.io/CoreNLP/coref.html

Alternatively, you can send us the information regarding the data sources,
and possibly we'll be able to integrate it in the future.

**Comment by ahmedalbahnasawy** [comment]
Thank you @AngledLuffa 
Unfortunately i have no Arabic dataset to train a model for coreference resolution. I know one but i think its not free
https://catalog.ldc.upenn.edu/LDC2013T19
