### ISSUE TITLE
Training a Shift-Reduce Parser

### ISSUE THREAD

**Issue by edemattos** [stanfordnlp/CoreNLP#1066]
I am trying to train a constituency parser for Portuguese (from the terminal).

> It is possible to train the Shift-Reduce Parser for languages other than English. An appropriate HeadFinder needs to be provided. This and other options are handled by specifying the -tlpp flag, which lets you choose the class for a TreebankLangParserParams.

I am not sure how to "provide the appropriate HeadFinder".

`Exception in thread "main" java.lang.IllegalArgumentException: No head rule defined for N' using class edu.stanford.nlp.trees.ModCollinsHeadFinder in (N' (N vinho) (A branco))`

`Exception in thread "main" java.lang.IllegalArgumentException: No head rule defined for NP using class edu.stanford.nlp.trees.international.spanish.SpanishHeadFinder in (NP (DEM Aquele) (N cliente))`

Obviously I need to define the rules, but how/where am I supposed to go about doing this? Must I create a `PortugueseTreeBankParserParams`, as well as `PortugueseHeadFinder`, `PortugueseLanguagePack`, and `PortugueseTreeReaderFactory`? Is it possible to use or slightly modify existing ones to get some baseline performance out of the box?

**Comment by J38** [comment]
Here is the command I ran for training a Spanish model:

```
java -Xmx100g edu.stanford.nlp.parser.shiftreduce.ShiftReduceParser -trainTreebank train -devTreebank dev -serializedPath  model.ser.gz -trainingThreads 4 -batchSize 12 -trainingIterations 100 -stalledIterationLimit 25 -tlpp edu.stanford.nlp.parser.lexparser.SpanishTreebankParserParams -trainingMethod BEAM -trainBeamSize 4 
```

I think your best bet would be copying the various Spanish files into Portuguese versions and modifying them until you don't get any crashes. It may suffice to just change the SpanishHeadFinder to have analogs in Portuguese, but I am not sure.

**Comment by J38** [comment]
I think the files you mentioned are a good place to start.

**Comment by edemattos** [comment]
@J38 Thank you. Java is not my main language so I'm struggling with incorporating these changes. Do I need to package them into their own jar, or include them in the original src directories? Would that entail cloning the GitHub release instead? Or would it suffice to introduce plain java files in the working directory?

**Comment by AngledLuffa** [comment]
Reasonable options would be to clone the github directory or to unpack the
src jar file and start compiling there.  You just need to make sure the
compiled code is in your classpath and the original classes jar isn't there
any more

**Comment by J38** [comment]
You should 1.) clone the Git repo, 2.) set CLASSPATH to point to `/path/to/CoreNLP/classes:/path/to/CoreNLP/lib/*:/path/to/CoreNLP/liblocal/*:/path/to/dir-w-models/*:` 3.) install ant (https://ant.apache.org/manual/install.html) which just involves downloading a file and setting some env variables as detailed in that link 4.) `cd /path/to/CoreNLP ; ant` (which will compile the code 5.) add new classes in same place as Spanish classes, and compile when you make changes

**Comment by J38** [comment]
Let me know if you have any questions with that workflow. But it really just involves setting some environment variables, so if you run into issues we can easily help you fix it.

**Comment by edemattos** [comment]
Thank you @J38 and @AngledLuffa. It turns out using the `LeftHeadFinder` was enough to get a decent baseline for now.

For reference, I used `-headFinder edu.stanford.nlp.trees.LeftHeadFinder` instead of `-tlpp [...]` and am observing pretty good parses.
