### ISSUE TITLE
Is whitespace tokenizer in 3.6.0 same as 4.0.0?

### ISSUE THREAD

**Issue by Guraadon** [stanfordnlp/CoreNLP#1067]
In 4.0.0, there is a comment saying that it recognizes whitespace characters the same as Java.lang.Character.isWhiteSpace. 

>  * This tokenizer treats as Whitespace almost exactly the same characters deemed Whitespace by the
>  * Java function {@link java.lang.Character#isWhitespace(int) isWhitespace}. That is, a whitespace
> * is a Unicode SPACE_SEPARATOR, LINE_SEPARATOR or PARAGRAPH_SEPARATOR, or one of the control characters
> * U+0009-U+000D or U+001C-U+001F <i>except</i> the non-breaking space characters. The one addition is
>  * to also allow U+0085 as a line ending character, for compatibility with certain IBM systems.
> * For including "spaces" in tokens, it is recommended that you represent them as the non-break space
> * character U+00A0.

But this comment is not in 3.6.0. Are they exactly the same? Does whitespace tokenizer recognizes whitespace characters the same as Java.lang.Character.isWhiteSpace, too?

**Comment by mimikyu-will** [comment]
Another question is does whitespace tokenizer in 4.0.0 treats whitespace characters the same as Java.lang.Character.isWhiteSpace? Because in the documentation, it said U+0085 is an addition. But isWhiteSpace doesn't treat U+0085 as whitespace.

**Comment by AngledLuffa** [comment]
No, they're not exactly the same.  There is a diff in WhitespaceLexer.flex:

https://github.com/stanfordnlp/CoreNLP/commit/3bea1fe7d7386bbe3b019c9e7d8bce70ce7bcb32#diff-e2d9c9b8d48bcb2fe51bf3fe2966e0020f3c1d7e916b0277a823d5fab5058f86

It's not too great that all of the changes were lumped together into one omnibus change without any explanation of any of the changes, but that's what happened.  

If you check out our repo, you can get a better look at these specific changes like this:

```
git show 3bea1fe7d7386bbe3b019c9e7d8bce70ce7bcb32 src/edu/stanford/nlp/process/WhitespaceLexer.flex
git show 3bea1fe7d7386bbe3b019c9e7d8bce70ce7bcb32 src/edu/stanford/nlp/process/WhitespaceTokenizer.java
```
