### ISSUE TITLE
How to make the sentence segment of document  in Coref is match to my sentences set?

### ISSUE THREAD

**Issue by nomadlx** [stanfordnlp/CoreNLP#1069]
I have document set that had split to sentences.
I want to get the context mention information for each sentence, so I run as follow:
```
java -Xmx5g -cp stanford-corenlp-4.0.0.jar:stanford-corenlp-4.0.0-models.jar:* edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,coref -coref.algorithm neural -outputFormat xml -file my_sentences.txt
```
the sentences in `my_sentences.txt` is split by `\n`

But the result not what I expected. It seem that the sentences have be merge to a document and split to sentence by bulit-in algorithm, so the number of sentences is not match to origin the number. This made I can't get the mention information for origin sentence. 

Is there a way to get mention information and keep origin sentences?

**Comment by AngledLuffa** [comment]
Look for the whitespace / newline options in this link:

https://stanfordnlp.github.io/CoreNLP/tokenize.html

**Comment by nomadlx** [comment]
Thank you! It runs as my expected.

> Look for the whitespace / newline options in this link: https://stanfordnlp.github.io/CoreNLP/tokenize.html
