### ISSUE TITLE
Sentiment results are different between stanford nlp python package and the live demo

### ISSUE THREAD

**Issue by ruoweiliu** [stanfordnlp/CoreNLP#1076]
I try sentiment analysis of tweet text by both stanford nlp python package and the live demo, but the results are different. The result of the python package is positive while the result of the live demo is negative.

- For python package, I download **stanford-corenlp-4.0.0** and install **py-corenlp**, basically follow the instruction in this answer: [Stanford nlp for python](https://stackoverflow.com/questions/32879532/stanford-nlp-for-python), the code is shown below:

```
import pycorenlp
from pycorenlp import StanfordCoreNLP

nlp = StanfordCoreNLP("http://localhost:9000")
text="noted former cocaine user carrie fisher says donald trump was absolutely on coke makes sense"
res = nlp.annotate(text,properties={'annotators': 'sentiment','outputFormat': 'json','timeout': 1000})
for s in res["sentences"]:
    print(s["sentimentValue"], s["sentiment"])
```
and the result is:
```
3 Positive
```

- For the live demo:
![Capture](https://user-images.githubusercontent.com/68687826/88470640-95c74d80-cec4-11ea-900d-176fb1a7a410.PNG)

**Comment by AngledLuffa** [comment]
Demo hasn't had its model updated in a while.  When things do get updated,
some results get better, others get worse...

**Comment by ruoweiliu** [comment]
> Demo hasn't had its model updated in a while. When things do get updated, some results get better, others get worse...

So you mean since the python package is the updated version 4.0.0, I just do not need to worry about the difference between them and use the python package to do the sentiment analysis, right?

**Comment by AngledLuffa** [comment]
Exactly

**Comment by ruoweiliu** [comment]
> Exactly

Thanks!
