### ISSUE TITLE
【error】There is already a relation named obl:agent!

### ISSUE THREAD

**Issue by unikcc** [stanfordnlp/CoreNLP#1077]
First I start a local server via StanfordNLP. Then I send a post resquest by python packages named requests  to parse sentence. It throwed an error when I sent a sentence. 
【sentence】
Technical problems will include user manipulation of agents through and agent editor , activation of agents in a shared context , presentation of agents , and creation of shared context through specification , construction , task representations , and interaction histories .
【code】
<pre>
import requests as rq
url = 'http://172.16.133.173:9000/?properties={"annotators":"tokenize, ssplit, pos, lemma, ner,     depparse","outputFormat":"json"}'
res = rq.post(url, data=sentence).text</pre>
【error】
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: There is already a relation named obl:agent!

**Comment by J38** [comment]
What version of CoreNLP are you using? I was able to run on that sentence and not get an error.

**Comment by AngledLuffa** [comment]
Fascinating.  First it should be pointed out that StanfordNLP is
deprecated.  Please use stanza instead:

github.com/stanfordnlp/stanza

The next thing I would ask is to explain what you are doing to get this
error.  As @j38 says, we are not able to reproduce this error.

**Comment by unikcc** [comment]
@J38 @AngledLuffa Thanks for your kind reply~
I just want to get the dependency parsing tree of each sentences. And I'm used to do this via StanfordCoreNLP. It's easy to use and works very well.
Here are some details: 
<pre>
【platform】: Ubuntu 18.04 LTS 
【Java vesion】: 1.8.0_192
【StanfordCoreNLP version】: 4.0.0
【Start server code】: nohup java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 8083 -timeout 15000 > 1.log 2>&1 &
</pre>
So I'll also go to learn how to use stanza~

**Comment by AngledLuffa** [comment]
What I meant is, how did you parse the text to trigger this error?

**Comment by unikcc** [comment]
> What I meant is, how did you parse the text to trigger this error?

All of the contexts are here:
<pre>
import requests as rq
url = 'http://172.16.133.173:9000/?properties={"annotators":"tokenize, ssplit, pos, lemma, ner,     depparse","outputFormat":"json"}'
sentence = "Technical problems will include user manipulation of agents through and agent editor , activation of agents in a shared context , presentation of agents , and creation of shared context through specification , construction , task representations , and interaction histories ."
res = rq.post(url, data=sentence).text
</pre>
Then it throws an error.

**Comment by AngledLuffa** [comment]
Sorry, but that still doesn't trigger it (when sent to my own local server).

What if you use the new 4.1.0 release?  Just in case something was fixed
without us realizing it.
http://nlp.stanford.edu/software/corenlp.shtml

**Comment by unikcc** [comment]
> Sorry, but that still doesn't trigger it (when sent to my own local server). What if you use the new 4.1.0 release? Just in case something was fixed without us realizing it. http://nlp.stanford.edu/software/corenlp.shtml

Magically. The new 4.1.0 release works perfectly. I'll use the lastest version🚀🚀🚀. Thank you!
