### ISSUE TITLE
document.sentence is a list of empty strings (document type is CoreNLP_pb2.Document)

### ISSUE THREAD

**Issue by Mohd-Misran** [stanfordnlp/CoreNLP#1080]
I am using the **Python CoreNLP interface**.
I annotated some text using the **CoreNLPClient** which gives me a document of type **CoreNLP_pb2.Document**.

Here's the code for annotating text:
`text = "Albert Einstein was a German-born theoretical physicist. He developed the theory of relativity."`
`document = client.annotate(text)`
`print(type(document))`

However, if I try to print the parse tree of the first sentence, the ouput is blank.

`first_sentence = document.sentence[0]`
`parse_tree = first_sentence.parseTree`
`print(parse_tree)`

So I checked for the text in **first_sentence**,
`print(first_sentence.text == '')` is `True`
which means that it's an empty string although `document.text` gives me the original string.

Need help with this! Why does the list contain empty strings? How do I make this right?

**Comment by AngledLuffa** [comment]
Which interface are you using?  The one in stanza or some other interface?

**Comment by Mohd-Misran** [comment]
StanfordNLP: Python CoreNLP Interface
I referred to this [notebbok](https://github.com/stanfordnlp/stanfordnlp/blob/master/demo/StanfordNLP_CoreNLP_Interface.ipynb)

**Comment by AngledLuffa** [comment]
There's a similar notebook available in stanza which is much more
up-to-date:

https://github.com/stanfordnlp/stanza/blob/master/demo/Stanza_CoreNLP_Interface.ipynb


There is a (hopefully temporary) caveat here which is that our downloads
are currently unavailable because of either a hardware or network issue.
Perhaps in an hour or two.

**Comment by Mohd-Misran** [comment]
@AngledLuffa same problem with stanza
`document.sentence[0]` is an empty string

**Comment by AngledLuffa** [comment]
Alright, looking into this a bit:
- are you including "parse" as one of your annotators?  If not, you won't get the parse tree.
- the sentence.text field is never set on the sending side.  I guess it wasn't considered essential since you can recover it using the offsets.

For example:

```
from stanza.server import CoreNLPClient

with CoreNLPClient(annotators=['tokenize','ssplit','pos','parse'], be_quiet=True) as client:
    text = "Albert Einstein was a German-born theoretical physicist. He developed the theory of relativity."
    document = client.annotate(text)
    print(type(document))

    first_sentence = document.sentence[0]
    parse_tree = first_sentence.parseTree
    print(parse_tree)

    for sentence in document.sentence:
        print("-----")
        print(sentence.tokenOffsetBegin)
        print(sentence.tokenOffsetEnd)
        print(sentence.characterOffsetBegin)
        print(sentence.characterOffsetEnd)
```
