### ISSUE TITLE
Updation of TIMEX3 standard url in SUTime page

### ISSUE THREAD

**Issue by kaushikacharya** [stanfordnlp/CoreNLP#1081]
URL for **TIMEX3 standard** mentioned in [SUTime webpage](https://nlp.stanford.edu/software/sutime.html#Usage) is not available.

It has been moved from 
http://www.timeml.org/site/publications/timeMLdocs/timeml_1.2.1.html#timex3 to
http://www.timeml.org/publications/timeMLdocs/timeml_1.2.1.html#timex3

Similarly, URL for **TimeML Annotation Guidelines Version 1.2.1** needs to be changed from http://www.timeml.org/site/publications/timeMLdocs/annguide_1.2.1.pdf  => http://www.timeml.org/publications/timeMLdocs/annguide_1.2.1.pdf

**Comment by AngledLuffa** [comment]
Someone didn't read the "Cool URIs don't change" style guide :)

Thanks for letting us know.
