### ISSUE TITLE
Upload 4.1.0 to Maven Central

### ISSUE THREAD

**Issue by kno10** [stanfordnlp/CoreNLP#1083]
https://mvnrepository.com/artifact/edu.stanford.nlp/stanford-corenlp

Maven currently only has 4.0.0

**Comment by J38** [comment]
Thanks for reminding me. Will work on this this week...

**Comment by toliwa** [comment]
A newer version of CoreNLP for the use with maven / gradle would be appreciated, thanks.

**Comment by simongray** [comment]
Sure would be great if 4.1 was on Maven instead of 4.0 :)

**Comment by AngledLuffa** [comment]
We have plans for 4.1.1, but minor things keep coming up and we keep
letting the deadline slip.  We'll try to redouble those efforts this week

**Comment by simongray** [comment]
@AngledLuffa Thank you so much! CoreNLP is a fantastic piece of software.

**Comment by J38** [comment]
version 4.2.0 is now up on Maven

**Comment by simongray** [comment]
Fantastic!
