### ISSUE TITLE
Stanford Parser failure when parsing this string: b.com/e(s)

### ISSUE THREAD

**Issue by ndvbd** [stanfordnlp/CoreNLP#1085]
Stanford Parser crashes when parsing this string: b.com/e(s)

You can easily reconstruct the problem by pasting it on the web console at: http://localhost:9001/

The reason for the failure is because the parser result is:

(ROOT
  (PRN
    (NP (NNS b.com/e(s))
    (-RRB- -RRB-)))

As you can see, there are 6 opening parentheses and only 5 closing parentheses.

I would appreciate a quick response on how to fix this.

**Comment by ndvbd** [comment]
The online crash happens when choosing Constituency Parse, of course.

**Comment by AngledLuffa** [comment]
> You can easily reconstruct the problem by pasting it on the web console at: http://localhost:9001/

ಠ_ಠ

**Comment by AngledLuffa** [comment]
I don't know how to recreate this.  If I run the server locally, it tokenizes the text as

b.com/e-LRB-s
-RRB-

The same thing happens if I go to corenlp.run  I certainly can't access the server you're running on your localhost.

If you can provide a more thorough explanation of how to recreate the issue, we can take a look.

**Comment by ndvbd** [comment]
Sure - this is my run configuration:

`java -Xmx4000m -cp "corenlp_3.9.1/stanford-corenlp-3.9.1.jar" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9001 -timeout 3000 -threads 12 -serverProperties /corenlp_3.9.1/stanford-english-corenlp-2018-02-27-models/caseless.properties
`
In the properties:

```
pos.model = /edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger
parse.model = /corenlp_3.9.1/stanford-english-corenlp-2018-02-27-models/edu/stanford/nlp/models/srparser/englishSR.ser.gz
depparse.model = /corenlp_3.9.1/stanford-english-corenlp-2018-02-27-models/edu/stanford/nlp/models/parser/nndep/english_UD.gz
```

So you can see that the CoreNLP version is 3.9.1, , I use POS model of english-left3words-distsim.tagger, parse model of englishSR.ser.gz and dep parse model of english_UD.gz,
When you run it, you can easily run http://localhost:9001/, and then paste the string:
`
b.com/e(s)`

Choose the constituency parser, run, and see the javascript crash, that happens because of the CoreNLP response.

What is the version you are running?

**Comment by AngledLuffa** [comment]
The current version is 4.1

This was a known issue that was fixed earlier this year.  The best advice I
can give is to upgrade.

**Comment by ndvbd** [comment]
I can confirm that when changing to 4.1.0 this problem is solved. Thank you so much for the assistance.
