### ISSUE TITLE
Upgrade from 3.9.1 to 4.1.0 - Can't find the english_UD.gz in the models of the 4.1.0

### ISSUE THREAD

**Issue by ndvbd** [stanfordnlp/CoreNLP#1088]
Upgrade from 3.9.1 to 4.1.0 - Can't find the `english_UD.gz` in the models of the 4.1.0

(So I cant find the DEP parser model there, only in the 3.9.1)

Am I missing something?

2. In addition, in 3.9.1 there is the non-caseless pos.model of `nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger`
while in 4.1.0 I only find the caseless model of: `models/pos-tagger/english-caseless-left3words-distsim.tagger`
Was the non-caseless (==caseful) model deprecated?

**Comment by AngledLuffa** [comment]
It should be in the main jar file, here:

edu/stanford/nlp/models/parser/nndep/english_UD.gz

**Comment by ndvbd** [comment]
@AngledLuffa, in the stanford-corenlp-4.1.0.jar, I don't have the subfolder edu/stanford/nlp/models. Am I missing something?

**Comment by AngledLuffa** [comment]
```
[john@localhost CoreNLP]$ jar tvf ../corenlp-releases/stanford-corenlp-4.1.0/stanford-corenlp-4.1.0-models.jar | grep nndep
     0 Mon Jul 27 00:04:40 PDT 2020 edu/stanford/nlp/models/parser/nndep/
13620770 Mon Jul 27 00:04:40 PDT 2020 edu/stanford/nlp/models/parser/nndep/english_SD.gz
13629875 Mon Jul 27 00:04:40 PDT 2020 edu/stanford/nlp/models/parser/nndep/english_UD.gz
```

**Comment by ndvbd** [comment]
@AngledLuffa I just downloaded http://nlp.stanford.edu/software/stanford-corenlp-4.1.0-models-english.jar again, and there is no folder edu/stanford/nlp/models/parser
What am I missing?

**Comment by AngledLuffa** [comment]
The jar titled "English" is more of an extra models jar.  You want the
basic models:

http://nlp.stanford.edu/software/stanford-corenlp-4.2.0-models.jar

**Comment by ndvbd** [comment]
@AngledLuffa I am sorry, but there is no file: https://nlp.stanford.edu/software/stanford-corenlp-4.1.0-models.jar

Note that I am using 4.1 version. My original question was: "Can't find the english_UD.gz in the models of the 4.1.0"

Again, am I missing something here?

**Comment by AngledLuffa** [comment]
Oops.  I would always recommend upgrading to the latest, and in this case I
don't think there are any breaking changes between 4.1 and 4.2, but I did
fix the link for you.

**Comment by ndvbd** [comment]
Thank you, now I am able to see the model file in the jar
