### ISSUE TITLE
Downsizing this library

### ISSUE THREAD

**Issue by nekonari** [stanfordnlp/CoreNLP#109]
This may not be the right place to add this, but any advice on downsizing this library? Trying to fit into Heroku's slug size limit (it's 300MB) and due to the size of this library, it's over 400MB (408MB to be precise).

**Comment by AngledLuffa** [comment]
It would help if you said which modules you do or don't need

**Comment by nekonari** [comment]
Guess that'd help. Here's all the import block in the code:
```
import edu.stanford.nlp.ie.crf.CRFClassifier;
import edu.stanford.nlp.ie.AbstractSequenceClassifier;

import edu.stanford.nlp.ling.CoreAnnotations;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.ling.IndexedWord;

import edu.stanford.nlp.parser.lexparser.LexicalizedParser;

import edu.stanford.nlp.pipeline.Annotation;
import edu.stanford.nlp.pipeline.StanfordCoreNLP;

import edu.stanford.nlp.process.CoreLabelTokenFactory;
import edu.stanford.nlp.process.PTBTokenizer;
import edu.stanford.nlp.process.Tokenizer;
import edu.stanford.nlp.process.TokenizerFactory;

import edu.stanford.nlp.sentiment.SentimentCoreAnnotations;

import edu.stanford.nlp.util.CoreMap;

import edu.stanford.nlp.semgraph.SemanticGraph;
import edu.stanford.nlp.semgraph.SemanticGraphCoreAnnotations;
import edu.stanford.nlp.semgraph.SemanticGraphEdge;

import edu.stanford.nlp.trees.*;
import edu.stanford.nlp.trees.Tree;
import edu.stanford.nlp.trees.tregex.TregexMatcher;
import edu.stanford.nlp.trees.tregex.TregexPattern;

import edu.stanford.nlp.util.CoreMap;
import edu.stanford.nlp.util.StringUtils;
```

I tried to remove duplicates...

**Comment by nekonari** [comment]
I didn't know what I was talking about (I'm working on this while the actual NLP guy is doing something else).

After posting above, I found where NLP is actually loading models. What would happen if I remove all other files besides those being loaded in the code explicitly?

**Comment by AngledLuffa** [comment]
What generally happens is it either works, or it completely fails, so you
can experiment on it yourself,

John

**Comment by manning** [comment]
It looks like you maybe also need to add a sentiment model, but overall, yes, it looks like you're only using parser, NER, and sentiment, and should be able to delete other unused models.
