### ISSUE TITLE
OpenIE doesn't work in Spanish

### ISSUE THREAD

**Issue by diego-bartra** [stanfordnlp/CoreNLP#1092]
I'm trying to use OpenIE for relation extraction in Spanish but it doesn't give any output.

It works well in English:
<img width="1267" alt="Screen Shot 2020-10-07 at 11 53 00" src="https://user-images.githubusercontent.com/44789253/95362792-37d7be80-0894-11eb-8c3a-f4f94f81e65a.png">

But not in Spanish:
<img width="1277" alt="Screen Shot 2020-10-07 at 11 53 21" src="https://user-images.githubusercontent.com/44789253/95362846-4faf4280-0894-11eb-833c-c4efcacdc2df.png">

What do you suggest?
Thanks

**Comment by AngledLuffa** [comment]
It's not really designed to be used in Spanish.  Sorry...
