### ISSUE TITLE
Scene graph in json form

### ISSUE THREAD

**Issue by onlyonewater** [stanfordnlp/CoreNLP#1093]
when I want print the scene graph in JSON form, I use the System.out.println(sg.toJSON()) command, but get an error:
error: method toJSON in class SceneGraph cannot be applied to given types;
        System.out.println(sg.toJSON());
                             ^
  required: int,String,String
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
what's wrong ???

**Comment by AngledLuffa** [comment]
Where is this class from?  I don't see SceneGraph in the corenlp release

**Comment by onlyonewater** [comment]
oh, thanks for your reply. I used the same code as in [https://nlp.stanford.edu/software/scenegraph-parser.shtml#Usage](url), I want to generate a scene graph from the text.

**Comment by AngledLuffa** [comment]
It appears the prototype for toJSON is actually

  public String toJSON(int imageID, String url, String phrase)

The values of imageID, url, and phrase are all only used once

    JSONObject obj = new JSONObject();
    obj.put("id", imageID);
    obj.put("url", url);
    obj.put("phrase", phrase);

so presumably if it isn't immediately obvious what values you need to fill
in, you can do

toJSON(0, "
https://www.dailyesports.gg/mtg-modern-banned-list-mox-opal-oko-thief-of-crowns-mycosynth-lattice-banned/",
"Unban mox opal")

and it should work fine

**Comment by onlyonewater** [comment]
oh, I used, but it get another error? 

Exception in thread "main" java.lang.NoClassDefFoundError: org/json/simple/JSONObject
	at edu.stanford.nlp.scenegraph.SceneGraph.toJSON(SceneGraph.java:122)
	at test.main(test.java:20)
Caused by: java.lang.ClassNotFoundException: org.json.simple.JSONObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more

**Comment by AngledLuffa** [comment]
Likely you don't have some json package installed or in your classpath

**Comment by onlyonewater** [comment]
Ok, I konw, I find I don't have the **json-simple-1.1.jar**, when I add this package to my classpath, it works, Thanks !!!

**Comment by snsd0805** [comment]
@onlyonewater
Excuse me. I have the same problem but I cannot understand how you solve it.
Should I new a JSONObject and transform the graph into this type via something function?

Can you give me some example or hint? Thanks a lot!
