### ISSUE TITLE
【CoreNLPServer】Unable to open "edu/stanford/nlp/models/segmenter/chinese/ctb.gz" as class path, filename or URL

### ISSUE THREAD

**Issue by LAveDrio-IIVA** [stanfordnlp/CoreNLP#1098]
# I'm trying to use CoreNLPServer with Chinese.

## Linux | ubuntu | Java1.8 | stanford-corenlp-4.1.0

First,I zipped the **stanford-corenlp-latest.zip**,then went into the directory **stanford-corenlp-4.1.0**.
I copied the **stanford-corenlp-4.1.0-models-chinese.jar** and **StanfordCoreNLP-chinese.properties** to this directory **stanford-corenlp-4.1.0**,like the pictue:
![文件结构](https://user-images.githubusercontent.com/25652450/96680910-f4f40b80-13a8-11eb-9612-aed31ea7caa2.png)

Then put all the jar into the CLASSPATH,by this command:
```
for file in `find . -name "*.jar"`; do export
CLASSPATH="$CLASSPATH:`realpath $file`"; done
```
Then,started the Server,by this command:
```
java -Xmx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties StanfordCoreNLP-chinese.properties -port 9000 -timeout 15000
```
So far,no problem,but when I sending a request to the Server,an Exception occurred:

**Unable to open "edu/stanford/nlp/models/segmenter/chinese/ctb.gz" as class path, filename or URL**
![image](https://user-images.githubusercontent.com/25652450/96680974-0f2de980-13a9-11eb-8e48-8443a1384767.png)

It seems that the program couldn't find the files in the models-chinese JAR.
But I don't know how to deal with it.
Plz help me,thx~

**Comment by AngledLuffa** [comment]
Would you echo the $CLASSPATH and make sure the jar file is there as you
expect?

Also please don't send screenshots when text would work

**Comment by LAveDrio-IIVA** [comment]
OK.I had executed the "echo $CLASSPATH".
It was the result:

.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib:/home/libo/CoreNLP/stanford-corenlp-4.1.0/*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::/home/libo/CoreNLP/stanford-corenlp-4.1.0/joda-time-2.10.5-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/jaxb-api-2.4.0-b180830.0359.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/ejml-simple-0.38-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/jaxb-impl-2.4.0-b180830.0438.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/protobuf.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/xom-1.3.2-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/ejml-ddense-0.38.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/jaxb-impl-2.4.0-b180830.0438-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/jaxb-core-2.3.0.1.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/joda-time.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/slf4j-api.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/stanford-corenlp-4.1.0-javadoc.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/javax.activation-api-1.2.0-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/ejml-ddense-0.38-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/jaxb-api-2.4.0-b180830.0359-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/javax.activation-api-1.2.0.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/stanford-corenlp-4.1.0-models.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/xom.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/ejml-simple-0.38.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/javax.json.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/javax.json-api-1.0-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/ejml-core-0.38-sources.jar:**/home/libo/CoreNLP/stanford-corenlp-4.1.0/stanford-corenlp-4.1.0-models-chinese.jar**:/home/libo/CoreNLP/stanford-corenlp-4.1.0/stanford-corenlp-4.1.0.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/ejml-core-0.38.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/jollyday-0.4.9-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/jollyday.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/stanford-corenlp-4.1.0-sources.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/slf4j-simple.jar:/home/libo/CoreNLP/stanford-corenlp-4.1.0/jaxb-core-2.3.0.1-sources.jar

**Actually,the "stanford-corenlp-4.1.0-models-chinese.jar" was in the result.**

**Comment by AngledLuffa** [comment]
I'm not sure this will fix it, but one thing is that the classpath can be
set up much easier.  Shouldn't need to loop over all the jars.  This is all
I need to do:

/home/john/extern_data/corenlp/*

Also please note that you are probably clobbering your classpath by giving
java the -cp parameter.  Try running without that parameter.

**Comment by LAveDrio-IIVA** [comment]
All right, I've done everything you said, but it's not working.
I want to make sure again that the correct operation is exactly what we said above？
If so,I'll try again...
Maybe I missed some other details...

**Comment by AngledLuffa** [comment]
You removed the

-cp "*"

from your command line?  What command line are you using now?

Can you run StanfordCoreNLP, either with an English pipeline or a
Chinese pipeline?

**Comment by LAveDrio-IIVA** [comment]
Now I use the command line:

**java -Xmx4g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties StanfordCoreNLP-chinese.properties -port 9000 -timeout 15000**

By CoreNLPServer ,English pipeline is OK,but Chinese pipeline crashed.
By setting maven pom in a java web project，everything is OK.
In a word,only CoreNLPServer can't find the file in the Chinese model jar.

**Comment by AngledLuffa** [comment]
I basically don't know anything about maven, so I can't help much.  Are you
able to run

java edu.stanford.nlp.pipeline.StanfordCoreNLP -props
StanfordCoreNLP-chinese.properties

**Comment by LAveDrio-IIVA** [comment]
All right,I have to copy the **StanfordCoreNLP-chinese.properties** to the **stanford-corenlp-4.1.0** directory before I run the command: 

**java edu.stanford.nlp.pipeline.StanfordCoreNLP -props
StanfordCoreNLP-chinese.properties**

If not,**Caused by: java.io.IOException: Unable to open "StanfordCoreNLP-chinese.properties" as class path, filename or URL** ... 
Also unable to find the file...

: (

**Comment by LAveDrio-IIVA** [comment]
Even if I copied the properties on manually,the **java edu.stanford.nlp.pipeline.StanfordCoreNLP -props
StanfordCoreNLP-chinese.properties** also worked,
but **Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/segmenter/chinese/ctb.gz" as class path, filename or URL** still occurred...

I'm basically sure its due to the CLASSPATH problem. Emmm... Thank you anyway~

**Comment by AngledLuffa** [comment]
Like I said above, I think the iteration over the jar files in your
corenlp download is unnecessary.  You should just be able to put
corenlp/path/* in your classpath and it will work.  Here is my entire
classpath, and it handles both a git checkout and the download
directory where I have the jars:

.:classes:data:lib/*:liblocal/*:/home/john/CoreNLP/classes:/home/john/CoreNLP/data:/home/john/CoreNLP/lib/*:/home/john/CoreNLP/liblocal/*:/home/john/extern_data/corenlp/*

Not being at your computer makes it hard to debug your classpath
issues, but it should absolutely be able to find ctb.gz in the jar
file.  Also, you shouldn't have needed to extract the Chinese
properties file, since it is in the Chinese models jar.  Clearly your
classpath is not correctly including the Chinese models jar.

**Comment by LAveDrio-IIVA** [comment]
All right,I made it...

The reason is that when I uploaded the Chinese-model.jar,maybe the network was bad.the Chinese-model.jar on the remote server machine was incomplete,so the  CLASSPATH was right,but unable to open.
I upload again,it's OK.

A silly mistake,it's my bad...
Thank you so much~

**Comment by AngledLuffa** [comment]
Oops!  Seems like we should make some kind of checksum available with the
downloads to avoid this kind of thing in the future.  Glad it worked out
