### ISSUE TITLE
How do I get `models-current.jar` from Maven Central?

### ISSUE THREAD

**Issue by cnowak7** [stanfordnlp/CoreNLP#1099]
Hi,

How would I be able to download the http://nlp.stanford.edu/software/stanford-english-corenlp-models-current.jar from maven central?

**Comment by cnowak7** [comment]
@AngledLuffa - I'm only finding the original JAR in maven central:

https://search.maven.org/artifact/edu.stanford.nlp/stanford-corenlp/4.0.0/jar

https://mvnrepository.com/artifact/edu.stanford.nlp/stanford-corenlp/4.0.0

Am I missing something or is http://nlp.stanford.edu/software/stanford-english-corenlp-models-current.jar not in Maven Central?

**Comment by AngledLuffa** [comment]
We are working on putting together a new build of CoreNLP, so at this point
I think the effort of getting the artifacts on maven will be focused on
4.1.1.  Hopefully soon

**Comment by cnowak7** [comment]
@AngledLuffa Thanks for the update - but I ended up resolving this thankfully - all I had to do was add the `models-english` dependency to my Gradle file - this has the SR parser - so now my Gradle contains the following:

```
compile(
     "edu.stanford.nlp:stanford-corenlp:4.0.0",
     "edu.stanford.nlp:stanford-corenlp:4.0.0:models",
     "edu.stanford.nlp:stanford-corenlp:4.0.0:models-english",
    ...
```
