### ISSUE TITLE
 edu.stanford.nlp.io.RuntimeIOException: Error while loading a tagger model (probably missing model file)

### ISSUE THREAD

**Issue by curtkohler** [stanfordnlp/CoreNLP#1101]
We have an Apache Spark program that leverages SCNLP 3.9.2 that we recently tried to upgrade to use the new SCNLP 4.x release. While the program ran well prior to the switch, we started getting the above error specifically for the model file: "edu/stanford/nlp/models/pos-tagger/english-left3words-distsim.tagger".  After confirming that we had the correct models jar as well as settings in the program we started digging down into the code. We were able to identify the changes in commit [b23221f012aeb9ab02479e0d5a03ddce22db777b](https://github.com/stanfordnlp/CoreNLP/commit/b23221f012aeb9ab02479e0d5a03ddce22db777b#diff-d250365debfb6d0aacce5da6bfdde12e7f99e0c7f7ad7aa915820b9bf6e71275) as the root cause of the problem. It basically switched to using the System ClassLoader to find the models instead of the Object's ClassLoader. By recompiling SCNLP after reverting the changes our migrated program successfully ran to completion.

When invoking Apache Spark you can specify a --jars option that copies the specified jars to the various worker machines and adds them to the classpath. My suspicion is that Spark introduces a ClassLoader (with access to the additional jar/classpath info) into the chain and by forcing the use of the System ClassLoader because of the change, you lose access to those additional jars.

I'm posting the issue here to make you aware of the breaking change as well as to leave a breadcrumb in case others encounter a similar issue (Most of the related web search results basically say just use the right model file).

**Comment by AngledLuffa** [comment]
Here's the original request to change it to the system classloader:

https://github.com/stanfordnlp/CoreNLP/pull/1051
This is not something I know much about.  Do you have any ideas on how both
you and the other user can have a functioning CoreNLP?

**Comment by AngledLuffa** [comment]
What do you think about this?  Hopefully it will cover both you and the other group

https://github.com/stanfordnlp/CoreNLP/commit/7be6ac36314b7fc3c972d870b0e58bfe3b37f50b

**Comment by curtkohler** [comment]
Looks ok to me and appears to have fixed the problem when I reran our Spark job with the changes. Can't speak for the person that requested the original change.

**Comment by AngledLuffa** [comment]
Good to hear.  I'll ping them, but hopefully it will work because of the
"if" blocks
