### ISSUE TITLE
Spanish tokenizer dies with an NPE on some input

### ISSUE THREAD

**Issue by vadali** [stanfordnlp/CoreNLP#111]
Hey,
I am using CoreNLP to tokenize crawled text, and I get the following error:

The current spanish tokenizer dies on the input "salos  ) ( 1 de", with the following stack trace:

    Unhandled java.lang.NullPointerException
    Matcher.java: 1283  java.util.regex.Matcher/getTextLength
    Matcher.java:  309  java.util.regex.Matcher/reset
    Matcher.java:  229  java.util.regex.Matcher/<init>
    Pattern.java: 1093  java.util.regex.Pattern/matcher

Tracing that in the code I get the following:
In DocumentPreProcessor.java, line 331 (```if ( ! (wsPattern.matcher(token.word()).matches() ||```), `token.word()` returns null. I added a debug log, here is what I got:

    token.word(): sal
    token.word(): os
    token.word(): null

By the way, if this was upper case (```SALOS  ) ( 1 DE```), it works just fine.

WDYT?

**Comment by vadali** [comment]
Well, adding ```if (token.word() != null)``` seems to solve that problem..

**Comment by manning** [comment]
Thanks for the bug report. Your suggestion probably sort of works, but it covers up the fact that there was a problem in the tokenizer whereby it was sometimes returning a token with a null String associated with it, as you worked out.  It seemed worth tracking that down the stack and fixing it properly. I've done that now.
