### ISSUE TITLE
Chinese Treebank version ?

### ISSUE THREAD

**Issue by datquocnguyen** [stanfordnlp/CoreNLP#1111]
Hi,
I am wondering which Chinese Treebank version was used for training the constituency parsing model for Chinese? 
Is it v9.0?
Thanks.

**Comment by AngledLuffa** [comment]
Most recent models are trained with CTB 7.  I think it is certainly
possible to have CTB 9 sometime in the next couple months, depending
on how much of a priority it is

**Comment by datquocnguyen** [comment]
Thanks for your information.
