### ISSUE TITLE
Possible to train classifier to a file?

### ISSUE THREAD

**Issue by kyygit** [stanfordnlp/CoreNLP#1112]
First, thanks for the great work. I feel lucky to have found the Softmax Classifier from this.

Here, i would like to ask, is there a choice to train the classifier 'To a File'? [Note, i am doing in code, not from CLI]

Currently, from understanding, here is my code:
`columnDataClassifier.trainClassifier(MY_TRAINING_FILE);`

After this line, the classifier is ready to be used. However, if i restart my program or android app, this line has to be called again, introducing additional overhead.

By any chance can this be saved to a file? So that it can be loaded subsequently without re-training?

Thanks in advance.

**Comment by AngledLuffa** [comment]
There's this method

  public void serializeClassifier(String serializeTo) throws IOException

and this method

  public static ColumnDataClassifier getClassifier(String path)

hopefully those will suffice

**Comment by yong2khoo88** [comment]
Great! I will come back after testing it. Thanks~

**Comment by yong2khoo88** [comment]
It works! Awesome!

Before I close this, i would like to ask, is the serialized classifier file 'human-readable' in some ways?

![image](https://user-images.githubusercontent.com/5007089/99769752-c8671700-2b41-11eb-8175-8be0a5255170.png)

As i thought, it is some formula with weight info. Maybe, it is interpret-able through the file with human eyes?

**Comment by kyygit** [comment]
Hi, It works! Thank you! 

Before i close this, i would like to know, if the serialized model file 'human-readable' in some way?

As i thought, it is a formula with weight info.

![image](https://user-images.githubusercontent.com/51041738/99770772-f6992680-2b42-11eb-8c9c-bb4c0df0c146.png)

P.S.: i logined with wrong account just now. have been amended.

**Comment by AngledLuffa** [comment]
It's a java serialization.  I would not expect to be able to read it, but
some strings may be encoded without compression depending on the way it is
encoded.

BTW you may be able to compress it by saving it to a file with a .gz
extension - most of our models allow for that.  In that case it would be a
surprise if you could read any of it

**Comment by kyygit** [comment]
No prob~
