### ISSUE TITLE
'Title' Named Entity Recognition not working 

### ISSUE THREAD

**Issue by HannahKirk** [stanfordnlp/CoreNLP#1117]
I downloaded the Stanford NER model using instructions from https://nlp.stanford.edu/software/CRF-NER.html and http://www.nltk.org/api/nltk.tag.html#module-nltk.tag.stanford. It recognises organizations, locations, persons but no job titles. However, the demo online http://corenlp.run/ does work with titles. How do I resolve this issue?

**Comment by AngledLuffa** [comment]
"Title" is an additional label added by the deterministic rules in CoreNLP,
not detected by the CRF models.  Unless NLTK integrates with the
deterministic rules provided by CoreNLP, it will not be able to detect
those labels.  I think that is on the NLTK side, not our side, although we
are happy to work with them to make it easier to do that integration.
