### ISSUE TITLE
I am trying to convert the tree structure dataset to .csv or json , i am using OutputSubtrees program but i am getting issue exception in main function which one need to use.

### ISSUE THREAD

**Issue by sruthi50** [stanfordnlp/CoreNLP#1122]

**Comment by AngledLuffa** [comment]
Please share the command line you used and the exception

**Comment by sruthi50** [comment]
I am new java, I am running code in intelliji idea . error: exception in thread  "main" java.lang arrayindexoutof exception craete break point:index 0 out of bounds for length 0 at edu.standard.nlp.trees.international.french ..main.
where we can find proper steps to execute, I want to convert train and test.txt files to .csv files

**Comment by sruthi50** [comment]
/standford/CoreNLP/src/edu/stanford/nlp/trees$ java edu.standford.nlp.trees.OutputSubtrees /home/sri/test.txt 
Error: Could not find or load main class edu.standford.nlp.trees.OutputSubtrees

**Comment by sruthi50** [comment]
/standford/CoreNLP/src/edu/stanford/nlp/trees$ java
edu.standford.nlp.trees.OutputSubtrees /home/sri/test.txt
Error: Could not find or load main class
edu.standford.nlp.trees.OutputSubtrees

**Comment by AngledLuffa** [comment]
You need the jar files in your classpath.  Look at step 4 in this link, for
example:

https://stanfordnlp.github.io/CoreNLP/download.html

**Comment by AngledLuffa** [comment]
... sorry, step 5

**Comment by sruthi50** [comment]
thanks for the response, I followed the step5 but still I am facing the
below issue

/standford/stanford-corenlp-4.2.0$ java -mx3g
edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat json -file input.txt
Error: Could not find or load main class
edu.stanford.nlp.pipeline.StanfordCoreNLP

**Comment by AngledLuffa** [comment]
What happens when you run

echo $CLASSPATH
I will say that for questions involving initial startup, you would have a
much faster turnaround time if you have a friend or coworker who can
interactively go through the first few steps.

If you're more comfortable with another language, it is also not too
difficult to rewrite the output mapping from tree to text.
