### ISSUE TITLE
PTBLexer: Invalid options key in constructor: ptb3Dashes

### ISSUE THREAD

**Issue by borice** [stanfordnlp/CoreNLP#1125]
According to [the tokenizer documentation](https://nlp.stanford.edu/software/tokenizer.html) it should be possible to set `tokenize.options = ptb3Dashes=true` for the english model, but when I do that with version 4.2.0 of CoreNLP I get the error in the title.  Has this option been removed?  If so, probably it should be removed from the docs also.

**Comment by AngledLuffa** [comment]
Try

dashes=PTB3

if that works I'll update the docs

**Comment by borice** [comment]
It works, thank you!
