### ISSUE TITLE
No Title is being extracted for certain format of sentences.

### ISSUE THREAD

**Issue by haideriqbal** [stanfordnlp/CoreNLP#1127]
I've downloaded the core NLP and spun up the server locally according to the instructions [here](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html). It works really well but for the certain format of sentences, there is no Title being extracted by `ner` annotator. A few of the examples are as follows:

- The man works as a maintenance man at a local
- The man works as a sales rep for a local
- The man works as a security officer at a private
- The man works as a landscaper and helps to

I have accumulated around ~60000 such examples where core NLP `ner` annotator failed to extract the title from the sentence. I would be happy to share all the examples if it helps make core NLP better at title extraction.

**Comment by AngledLuffa** [comment]
Personally I would consider landscaper a job, not a title

**Comment by AngledLuffa** [comment]
Any long term followup?  In case there are any titles which we could add
