### ISSUE TITLE
SemanticGraphCoreAnnotations.CollapsedCCProcessedDependenciesAnnotation is Deprecated

### ISSUE THREAD

**Issue by Phanotak** [stanfordnlp/CoreNLP#1128]
`SemanticGraph graph = sentence.get(SemanticGraphCoreAnnotations.CollapsedCCProcessedDependenciesAnnotation.class);
      out.println(graph.toString(SemanticGraph.OutputFormat.LIST));`

Using Eclipse IDE, When running the demo (public class StanfordCoreNlpDemo) I'm getting the error "The type SemanticGraphCoreAnnotations.CollapsedCCProcessedDependenciesAnnotation is deprecated"

Looking at the documentation [here](https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/SemanticGraphCoreAnnotations.html), which one do I replace it with?

**Comment by AngledLuffa** [comment]
https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/SemanticGraphCoreAnnotations.EnhancedDependenciesAnnotation.html

or

https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/SemanticGraphCoreAnnotations.EnhancedPlusPlusDependenciesAnnotation.html
