### ISSUE TITLE
can't download stanza for python3

### ISSUE THREAD

**Issue by nlp12** [stanfordnlp/CoreNLP#1131]
When I type in pip install stanza into the command line of python (im on Mac)  I keep getting a SyntaxError: invalid syntax error message. I am using python 3.8.2, so not sure why this is happening. I also have no experience with coding and just recently downloaded python 3 from pythons website. I was encouraged by your team (via email correspondence) to use java for my project, but that download failed several times, so here I am. I want to use stanza so I can first separate words (dealing with chinese) and then assign pos.

**Comment by AngledLuffa** [comment]
Wait, did you run pip from inside python?  You need to run it at the
command line / terminal

**Comment by nlp12** [comment]
the message I get when run it at terminal: -bash: pip: command not found

**Comment by AngledLuffa** [comment]
Is python in your path?  You might need to try pip3 instead

**Comment by nlp12** [comment]
that downloaded it. Thank you! Now my final question for now, how do I download the word segmenter for chinese so I can split words?

**Comment by AngledLuffa** [comment]
The python one can be downloaded with

stanza.download("zh")

assuming you're okay with simplified.  What is your goal?

**Comment by nlp12** [comment]
My main goal now, is, I have a .txt document with approximately 3 million chinese characters, which need to be segmented into words. I would like to utilize the POS Tagger and other tools, but right now the most pressing issue is getting the words separated. I just tried typing stanza.download ("zh") in python and in terminal and nothing happened.

**Comment by AngledLuffa** [comment]
Surely something happened...

**Comment by nlp12** [comment]
yeah it did but still nothing it is just downloading and downloading and downloading, but nothing downloading in my downloads folder. any advice?

**Comment by AngledLuffa** [comment]
First, as a general rule of advice for asking questions: that is not nothing

Is the download bar progressing?

The resulting download should go in ~/stanza_resources, not the Downloads
directory
