### ISSUE TITLE
StanfordScene GraphParser: Error: There is already a relation named det:qmod!

### ISSUE THREAD

**Issue by amulyahwr** [stanfordnlp/CoreNLP#1143]
Hello,

I have Java11. I downloaded:
1. CoreNLP4.2.0/4.1.0/3.9.2 + English models from https://stanfordnlp.github.io/CoreNLP/history.html
2. SceneGraphParser from https://nlp.stanford.edu/software/scenegraph-parser.shtml

In the directory which contains all jar files, I run command: java -mx2g -cp "*" edu.stanford.nlp.scenegraph.RuleBasedParser
Next, I input sentence:
A brown fox chases a white rabbit.

However, I receive the below output (providing the full trace so that it is easy to understand):

[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.5 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.1 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.6 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.6 sec].
[main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
[main] INFO edu.stanford.nlp.time.TimeExpressionExtractorImpl - Using following SUTime rules: edu/stanford/nlp/models/sutime/defs.sutime.txt,edu/stanford/nlp/models/sutime/english.sutime.txt,edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
[main] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 580704 unique entries out of 581863 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_caseless.tab, 0 TokensRegex patterns.
[main] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 4869 unique entries out of 4869 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_cased.tab, 0 TokensRegex patterns.
[main] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 585573 unique entries from 2 files
Exception in thread "main" java.lang.ExceptionInInitializerError
	at edu.stanford.nlp.scenegraph.RuleBasedParser.parse(RuleBasedParser.java:84)
	at edu.stanford.nlp.scenegraph.AbstractSceneGraphParser.parse(AbstractSceneGraphParser.java:20)
	at edu.stanford.nlp.scenegraph.AbstractSceneGraphParser.parse(AbstractSceneGraphParser.java:48)
	at edu.stanford.nlp.scenegraph.RuleBasedParser.main(RuleBasedParser.java:254)
Caused by: java.lang.IllegalArgumentException: There is already a relation named det:qmod!
	at edu.stanford.nlp.trees.GrammaticalRelation.<init>(GrammaticalRelation.java:322)
	at edu.stanford.nlp.trees.GrammaticalRelation.<init>(GrammaticalRelation.java:349)
	at edu.stanford.nlp.scenegraph.SemanticGraphEnhancer.<clinit>(SemanticGraphEnhancer.java:48)
	... 4 more

I tried it with CoreNLP4.2.0/4.1.0/3.9.2. Please suggest. Thank you in advance.

**Comment by AngledLuffa** [comment]
It seems to work with exactly 3.6.0.  I'll try to produce a new version
which works with the current version, although no promises

https://stanfordnlp.github.io/CoreNLP/history.html

**Comment by amulyahwr** [comment]
Ok. Thank you for the response.

**Comment by AngledLuffa** [comment]
The underlying issue is later versions of corenlp already have a QMOD relation, and there's an assertion which complains if the same relation is added twice.

https://github.com/stanfordnlp/CoreNLP-research/commit/3d4b7add7cd155702d89973261c457f673869e22 ... this may not be visible to people outside Stanford, which raises the question of whether something publicly released should be in our private repo or moved to the public

Hopefully the library still works the same.  I have nooooo idea
