### ISSUE TITLE
ssplit.tokenPatternsToDiscard causes AnnotationException

### ISSUE THREAD

**Issue by Fan-Luo** [stanfordnlp/CoreNLP#1145]
Hi,

To resolve coreference across sentences, I joint my sentence with separators.
Then I call CoreNLPClient while specifying ssplit.boundariesToDiscard, as
```
with CoreNLPClient(timeout=30000, memory='16G', endpoint='http://localhost:8000',
                   properties={'annotators': 'tokenize,ssplit,pos,lemma,coref',
                    'ssplit.boundariesToDiscard': '<title>,</title>,</sent>' 
                                       }
                   ) as client: 
    Text = '<title> ed wood film </title> ed wood is 1994 american biographical period comedydrama film directed and produced by tim burton and starring johnny depp as cult filmmaker ed wood </sent> film concerns period in woods life when he made his bestknown films as well as his relationship with actor bela lugosi played by martin landau </sent> sarah jessica parker patricia arquette jeffrey jones lisa marie and bill murray are among supporting cast </sent>'
    
    ann = client.annotate(Text)
```

It prints out the following errors:

> HTTPError                                 Traceback (most recent call last)
> /usr/local/lib/python3.7/dist-packages/stanza/server/client.py in _request(self, buf, properties, reset_default, **kwargs)
>     451                               timeout=(self.timeout*2)/1000, **kwargs)
> --> 452             r.raise_for_status()
>     453             return r
> 
> 3 frames
> HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8000/?properties=%7B%27outputFormat%27%3A+%27serialized%27%7D&resetDefault=false
> 
> During handling of the above exception, another exception occurred:
> 
> AnnotationException                       Traceback (most recent call last)
> /usr/local/lib/python3.7/dist-packages/stanza/server/client.py in _request(self, buf, properties, reset_default, **kwargs)
>     456                 raise TimeoutException(r.text)
>     457             else:
> --> 458                 raise AnnotationException(r.text)
>     459 
>     460     def annotate(self, text, annotators=None, output_format=None, properties=None, reset_default=None, **kwargs):
> 
> AnnotationException: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 68 out of bounds for length 68

Thank you

**Comment by AngledLuffa** [comment]
I think I've put a fix here:

https://github.com/stanfordnlp/CoreNLP/commit/a803bc357c32841beb3919f2e4dc22a1375dca4d

The problem was that "discarded" tokens still wind up in the overall token
list, so we need to look at the processed sentences instead.

Are you comfortable rebuilding this yourself, or do you need me to supply a
new jar file with the fix?

**Comment by AngledLuffa** [comment]
This is a package which includes some other fixes as well:

http://downloads.cs.stanford.edu/nlp/software/stanford-corenlp-4.2.1.zip

**Comment by Fan-Luo** [comment]
Thank you! I will try it out.
