### ISSUE TITLE
Blocked loading mixed active content “http://cdnjs.cloudflare.com/ajax/libs/dagre-d3/0.4.17/dagre-d3.min.js”

### ISSUE THREAD

**Issue by rpdeslandes** [stanfordnlp/CoreNLP#1146]
We're running CoreNLP using Docker. The issue we're having is that the constituency parse is not showing up. It seems that the `<script>` include for dagre-d3 requests the http not the https version and the browser blocks the mixed active content. I'm not sure if this is unique to our usage or not so filing this issue.

I mention the following in case it's relevant. We recently updated our version to 4.2.0 from the CoreNLP website to see if this had been fixed, but our instance says its on version 4.1.0 (not 4.2.0) on the landing page. Perhaps we've made a mistake in updating?

Regards

**Comment by AngledLuffa** [comment]
No, I'm just lame and forgot to update the version number.  Going forward
we incorporated automatically updating the built-in webpage with the new
version number when making a new distribution, so hopefully that won't
happen again.

I have not heard of this particular error before.  I see a line which may
be the offending line in the HTML.  Here is an updated jar file which is
exactly the same as 4.2.0, except it has that line updated to https.  If
this works for you, please let me know and we'll check it in to our
codebase.

https://nlp.stanford.edu/~horatio/stanford-corenlp-4.2.0.jar

**Comment by rpdeslandes** [comment]
Thanks for your help!

In our case we also needed to update the corenlp-brat.html file in stanford-corenlp-4.2.0-models.jar as it was being sourced first. But that was change we needed.

**Comment by AngledLuffa** [comment]
Probably shouldn't be in both places anyway.  Thanks for letting me know
