### ISSUE TITLE
Quote Annotation - AnnotationException StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by allenkim** [stanfordnlp/CoreNLP#1147]
Hello,

I had a situation with text that had this: `""=`

It seems to throw an error when I try running the pipeline with quote annotation on this small fragment. Just wanted to verify that it was an issue.

Thank you.

**Comment by AngledLuffa** [comment]
Would you try this?  It's not an official release, just a zip of all the
recent changes we've made.  Note that the current release of the
shift-reduce models won't work with this.  If you need those, I'll send you
a link for that as well.

http://downloads.cs.stanford.edu/nlp/software/stanford-corenlp-4.2.1.zip

**Comment by allenkim** [comment]
I tried running CoreNLP with the new files in the zip, but am still getting the same errors...

**Comment by AngledLuffa** [comment]
Alright, oops.  Would you send us a sample text / program which is causing
that crash?  I'll try to work it out and post another fix.

**Comment by allenkim** [comment]
Just running the pipeline on the given text `""=` seems to create errors for me when including the quote pipeline. Hopefully, I'm not running something incorrectly.

**Comment by AngledLuffa** [comment]
Alright, I see a bug and a potential fix using that example.  I posted a new release candidate at the same address.  Want to try again?

http://downloads.cs.stanford.edu/nlp/software/stanford-corenlp-4.2.1.zip

**Comment by allenkim** [comment]
Thanks. It seems to work for that example, but here is another example that seems to cause issues: `"?'" AAAAA BBBBB`

**Comment by AngledLuffa** [comment]
Try again?  I hopefully fixed that crash as well.

**Comment by allenkim** [comment]
I seem to still be getting the same error for the `"?'" AAAAA BBBBB` example. Was the same link updated?

**Comment by AngledLuffa** [comment]
No, it's not.  Sorry... fix it in a few minutes

**Comment by AngledLuffa** [comment]
Alright, I rebuilt it.  Try again?

**Comment by allenkim** [comment]
Seemed to fix that issue, but I found another (sorry to keep bombarding you like this). They all seem to be under this index out of bounds error.

This one is a larger piece of text, so I attached a text file.

[excerpt.txt](https://github.com/stanfordnlp/CoreNLP/files/6276025/excerpt.txt)

**Comment by AngledLuffa** [comment]
This one is not going to have as quick a turnaround, I'm afraid

**Comment by AngledLuffa** [comment]
Found it, I think.  Want to try again, same link?

**Comment by AngledLuffa** [comment]
PS we hope to make a new release in a week or two, with these changes being part of the updates, so please don't hesitate to send us any more errors you find

**Comment by allenkim** [comment]
Thanks! This seems to close out the issues I see so far, but I'll keep this open for a bit in case more errors pop up.

**Comment by allenkim** [comment]
Here's another error I'm getting; something with NullPointerException.

[passage.txt](https://github.com/stanfordnlp/CoreNLP/files/6301116/passage.txt)

**Comment by AngledLuffa** [comment]
This is a nice change of pace.  I see EXACTLY what the problem is and have
no idea how to fix it, which is somewhat different from the previous
iteration, where at first I had no idea wtf was happening but I could tell
it was an off-by-one error.

**Comment by AngledLuffa** [comment]
Alright, posted the update for that one

**Comment by allenkim** [comment]
Wow, that was fast! It's amazing how quickly you pick up on these things! Much appreciated. Seems good so far.

Again, will let you know if anything else is a problem.

**Comment by AngledLuffa** [comment]
Found one on my own (an bug in one of the previous bugfixes)

http://downloads.cs.stanford.edu/nlp/software/stanford-corenlp-4.2.1.zip

**Comment by allenkim** [comment]
Here's another passage with a bug:

[passage.txt](https://github.com/stanfordnlp/CoreNLP/files/6314335/passage.txt)

**Comment by AngledLuffa** [comment]
That should also be working now

**Comment by AngledLuffa** [comment]
I'm looking to put together a new release of 4.2.1, since there are some
updates to one of its features which can be used from our python package,
Stanza.  Since we're already looking to make the quote annotator more
robust, have you noticed any other crashes since the latest update?

Thanks!

**Comment by allenkim** [comment]
No crashes so far! Looks like the latest changes are working well!

**Comment by AngledLuffa** [comment]
Glad to hear it!

**Comment by allenkim** [comment]
Here's another snippet of text that raises an error I found.

[snippet.txt](https://github.com/stanfordnlp/CoreNLP/files/6393958/snippet.txt)

**Comment by AngledLuffa** [comment]
Thanks... you can find the fix in the usual place

**Comment by AngledLuffa** [comment]
Alright, I put together a more official release including all of the QuoteAnnotator fixes.  Please let us know if you find more & we'll start including them for the next version.  Otherwise, shall we consider this resolved?

**Comment by allenkim** [comment]
Yes. Sounds good. I'll let you know if more errors are found, but in the meantime, I appreciate the fixes and we can close this now.
