### ISSUE TITLE
Issue when using StanfordCorenlp for entity link

### ISSUE THREAD

**Issue by gaozhiguang** [stanfordnlp/CoreNLP#1149]
Hi, when i use Stanford Corenlp for entity link, the program is stuck, In other words, the program is running all the time without results. I use python's library stanfordcorenlp, here is my code:

import stanfordcorenlp
import json
from stanfordcorenlp import StanfordCoreNLP
nlp = StanfordCoreNLP(r'D:\stanford-corenlp-full-2018-10-05')#文件的位置
sentence = 'I want to go to beijing.'
output = nlp.annotate(sentence, properties={
    'annotators': 'tokenize,ssplit,pos,lemma,ner,entitylink',
    'outputFormat': 'json'
    })
data = json.loads(output)
print(data)

How does this happen? Thanks.

**Comment by AngledLuffa** [comment]
Please upgrade to stanza and try that instead.  If it still happens there,
we'll try to figure it out

https://github.com/stanfordnlp/stanza
https://stanfordnlp.github.io/stanza

**Comment by gaozhiguang** [comment]
Hi，thanks your reply . I follow your advice using the stanza, but another issue happens.
The program error is as follows:
stanza.server.client.AnnotationException: java.lang.RuntimeException: edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/models/kbp/english/wikidict.tab.gz" as class path, filename or URL

Does it mean i need to download the wikidict.tab.gz myself, and where can i find it? when i download the file, which step should i take to make it work correctly.

my code like this:
from stanza.server import CoreNLPClient
text = "Chris Manning is a nice person. Chris wrote a simple sentence. He also gives oranges to people."
with CoreNLPClient(
        annotators=['tokenize','ssplit','pos','lemma','ner', 'entitylink'],
        timeout=30000,
        memory='8G') as client:
    ann = client.annotate(text)
sentence = ann.sentence[0]
print(sentence)

thanks again.

**Comment by AngledLuffa** [comment]
This file is in the English(KBP) package available here:

https://stanfordnlp.github.io/CoreNLP/
