### ISSUE TITLE
CoreNLP not working for Chinese

### ISSUE THREAD

**Issue by nlp12** [stanfordnlp/CoreNLP#1152]
English and German both worked fine, but Chinese did not work, was given numbers instead of Chinese characters. Even the segmenter did not even work. Seems there is an issue with the pipeline for Chinese. 
Have tried several times and even on two different machines, still not working.

**Comment by AngledLuffa** [comment]
What do you mean by "numbers"?   Is this an encoding problem?

**Comment by nlp12** [comment]
numbers displayed in value instead of characters:

   child {
                value: "\351\202\243"
              }
              value: "DT"
            }
            child {
              child {
                child {
                  value: "\344\270\252"
                }
                value: "M"
              }
              value: "CLP"
            }
            value: "DP"
          }
          child {
            child {
              child {

**Comment by AngledLuffa** [comment]
This is absolutely an encoding problem.  I don't know what you're using to
produce this, though.  Are you using a library of some kind?  What system?
What version of CoreNLP?  We need some basic facts to be able to help at all

**Comment by nlp12** [comment]
what I did in python after downloading stanza, corenlp and java:

import stanza
from stanza.server import CoreNLPClient
text="""
XYZ chinese characters data
"""
with CoreNLPClient(
        annotators=['tokenize','ssplit','pos','lemma','ner', 'parse', 'depparse','coref'],
        timeout=30000,
        memory='8G',
        properties='zh') as client:
	ann=client.annotate(text)
	sentence=ann.sentence[0]
	parse=sentence.parseTree
	print(parse)

**Comment by AngledLuffa** [comment]
I don't remember ever seeing this before, and I'm actually kind of surprised this is the first time it's come up.  The issue here is that the protobuf __string__ method is escaping the text as it is printing it out.  The strings themselves are actually correct, though.  ​Consider the following example.  The cat is escaped when you print the entire token's protobuf object, but it's printed correctly if you print just the string.

```
import stanza
from stanza.server import CoreNLPClient

text = 'Unban mox opal 🐱.  This is a second sentence.'

with CoreNLPClient(annotators=["tokenize","ssplit"],
                   properties={'tokenize.codepoint': 'true'}) as client:
    ann = client.annotate(text)
    print(ann.text)
    print(ann.sentence[0].token[3])
    print(ann.sentence[0].token[3].word)
```

**Comment by AngledLuffa** [comment]
if you want to print the entire protobuf and see the unescaped strings, this might help:

https://googleapis.dev/python/protobuf/latest/google/protobuf/text_format.html
