### ISSUE TITLE
Using 'coref' annotator using corenlp from Stanza

### ISSUE THREAD

**Issue by joelawalsh01** [stanfordnlp/CoreNLP#1153]
Hello, 
     Not sure if this is the place for it, but I've been using 'coref' from the Stanza wrapper for corenlp. I was wondering which coref model is referenced from within 'annotators'. I noticed that you can use either 'coref' or 'dcoref', so I know it's not the deterministic model. So that leaves either the neural or statistical. If 'coref' is referring to the statistical model, is there any way to access the neural model from Stanza?

- Thanks!

**Comment by AngledLuffa** [comment]
Based on the debug output:

[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator
coref
[main] INFO edu.stanford.nlp.coref.statistical.SimpleLinearClassifier -
Loading coref model
edu/stanford/nlp/models/coref/statistical/ranking_model.ser.gz ... done
[0.7 sec].

To switch to the neural annotator, add the "parse" annotator and then use
the setting coref.algorithm=neural

**Comment by joelawalsh01** [comment]
Thank you!
