### ISSUE TITLE
Could not handle incoming annotation error

### ISSUE THREAD

**Issue by NielsRogge** [stanfordnlp/CoreNLP#1157]
When a string contains a % character, the pipeline is not able to annotate it with named entities. This is the same error as #206. With `quiet=False` and `logging_level=logging.DEBUG`, I get the following:

```
'Could not handle incoming annotation'
(<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 1 column 1 (char 0)',), <traceback object at 0x00000218D876A548>)
```

Looking at the server, this prints out the following when it receives a sentence containing a %:

```
[pool-1-thread-9] INFO CoreNLP - [/0:0:0:0:0:0:0:1:50544] API call w/annotators tokenize,ssplit,pos,lemma,ner
[pool-1-thread-9] WARN CoreNLP - java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " i"
  java.net.URLDecoder.decode(Unknown Source)
  edu.stanford.nlp.pipeline.StanfordCoreNLPServer.getDocument(StanfordCoreNLPServer.java:330)
  edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$600(StanfordCoreNLPServer.java:54)
  edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:898)
  com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
  sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
  com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
  sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
  com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
  sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
```

For reference, the sentence was "There was 60% inflation".

**Comment by AngledLuffa** [comment]
How are you triggering this?  The normal mechanisms for getting results
from the server (the demo page, the stanza client) all properly escape the
% so this is not an issue there.

**Comment by AngledLuffa** [comment]
I will put a disclaimer under that link recommending that you use stanza
instead of the older package.  In the meantime, you definitely should try
the same thing with stanza instead of stanfordcorenlp.

https://pypi.org/project/stanza/
https://stanfordnlp.github.io/stanza/

**Comment by AngledLuffa** [comment]
20fe1e996455b1c1434022d6e7f0b8524f41f253

This is integrated into CoreNLP 4.4.0 and might fix the issue for some external libraries.
