### ISSUE TITLE
NullPointerException when parser timeouts

### ISSUE THREAD

**Issue by leebird** [stanfordnlp/CoreNLP#116]
I tried to set a timeout parameter for the Stanford parser and followed the steps described at http://stackoverflow.com/questions/33297369/how-to-set-a-timeout-on-stanford-nlp-parsing

I replicated the errors described in the page. Has this bug been fixed yet? I am using the latest 3.6.0 release.

I assume parse.maxtime is in millisecond.

Thanks!

P.S., It looks [this line](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/SentenceAnnotator.java#L64) uses results returned by [this function](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/util/concurrent/InterruptibleMulticoreWrapper.java#L50), which may return null. I am not familiar with Java and the logic in the codes. Could someone fix this? Thanks!

**Comment by J38** [comment]
I pushed a fix to this.
