### ISSUE TITLE
Tokenization of cliticized tokens different for single-word tokens versus in a sentence

### ISSUE THREAD

**Issue by saxtell-cb** [stanfordnlp/CoreNLP#1161]
In English, when I tokenize text such as "that'll" with no other context, I get the following tokens:
* that
* '
* ll

However, when I tokenize text such as "that'll be all folks.", I get the following tokens (which is my expected result for "'ll"):
* that
* 'll
* be
* all
* folks
* .

I have the following set:
* tokenize.language = English
* tokenize.whitespace = false
* tokenize.keepeol = false
* tokenize.verbose = false
* tokenize.options = invertible=true,splitAssimilations=true,splitHyphenated=false,splitForwardSlash=true,untokenizable=firstDelete,strictTreebank3=true,normalizeSpace=false

Is there a way to make Stanford CoreNLP correctly tokenize a single contracted word with no other context? I don't see any other options here: [Tokenization](https://stanfordnlp.github.io/CoreNLP/tokenize.html).

The same thing happens with "wanna", "gonna", "shouldda", etc. They don't get tokenized when in isolation.

**Comment by saxtell-cb** [comment]
Thanks @AngledLuffa!! Very helpful to know! I can work around this for now, but if a solution is available it would be great to get that info.

**Comment by AngledLuffa** [comment]
I added a hack which I believe should compensate for this.  Hopefully in the future there is an EOF lookahead that lets us fix the problem in a more principled manner in the tokenizer.  You can get this from the dev branch... if rebuilding java distributions isn't your specialty, I can put together a fake release containing the fix.

**Comment by saxtell-cb** [comment]
@AngledLuffa I think it's better for me to wait for a release that has the changes. Thanks for looking into this.

**Comment by AngledLuffa** [comment]
Here, you can give this a try.  Not a real release, just a bugfix

https://nlp.stanford.edu/software/stanford-corenlp-4.2.2b.zip

**Comment by saxtell-cb** [comment]
@AngledLuffa That's exactly what I'll need. Any idea when it could get into a release?

**Comment by AngledLuffa** [comment]
Probably end of summer, unless we get something big done or some critical
bug shakes out between now and then.

**Comment by saxtell-cb** [comment]
Very cool. Thanks!
