### ISSUE TITLE
Publish 3.6.0 to maven central

### ISSUE THREAD

**Issue by craigryan** [stanfordnlp/CoreNLP#117]
Can you please indicate when 3.6.0 will be published to maven central? I'm relying on online documentation while having to use 3.5.2 (via pom.xml dep) which makes coding difficult. I can't use a private maven repo or manual downloads either.

**Comment by dispositional** [comment]
Open Information Extractor on Maven central would be awesome as well.

**Comment by J38** [comment]
We'll be releasing 3.6.0 on Maven in early January, the OpenIE stuff is included in the main release.


________________________________

**Comment by jakeabel** [comment]
Awesome greatly appreciated.
