### ISSUE TITLE
Broken Link in https://stanfordnlp.github.io/stanza/client_usage.html

### ISSUE THREAD

**Issue by shoebham** [stanfordnlp/CoreNLP#1170]
There is a broken link on the website on the page https://stanfordnlp.github.io/stanza/client_usage.html 
It points to https://github.com/stanfordnlp/stanza/blob/main/demo/StanfordNLP_CoreNLP_Interface.ipynb which doesn't exist and has been shifted to https://github.com/stanfordnlp/stanza/blob/main/demo/Stanza_CoreNLP_Interface.ipynb

**Comment by AngledLuffa** [comment]
Thanks, this is very helpful

**Comment by shoebham** [comment]
Thanks for fixing. 👍👍👍
