### ISSUE TITLE
Model jar files: 404 Not Found

### ISSUE THREAD

**Issue by mhillebrand** [stanfordnlp/CoreNLP#1172]
I can't download any of your models. These both yield **_404 Not Found_** errors:

https://downloads.cs.stanford.edu/nlp/software/stanford-corenlp-4.2.1-models-english.jar
https://downloads.cs.stanford.edu/nlp/software/stanford-corenlp-4.2.1-models-english-kbp.jar

<img width="734" alt="image" src="https://user-images.githubusercontent.com/286198/128385169-f20f9b8e-1451-42b5-8707-6546cb62b64e.png">

**Comment by AngledLuffa** [comment]
Sorry, this happens to us every once in a while.  Hopefully back in a
couple hours.

Somewhere on my list of tasks is to try to integrate with huggingface.
Every time this happens, I suppose the casus belli becomes stronger...

**Comment by mhillebrand** [comment]
Ahh, it's this entire subdomain. 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/286198/128395031-ae38fe93-ab6c-4d86-aa1c-c08f47889f87.png">

**Comment by wonjames** [comment]
Any updates on when this will be back up?

**Comment by mhillebrand** [comment]
It's back up!
