### ISSUE TITLE
cannot download the core NLP models

### ISSUE THREAD

**Issue by skwolvie** [stanfordnlp/CoreNLP#1173]
Hi,
THe download link on the home page does not work.
https://nlp.stanford.edu/software/stanford-corenlp-4.2.2.zip
Is there any other way of downloading the core NLP models?

I also cannot access the previous models. I'm trying wget on all the older versions here on this page (https://stanfordnlp.github.io/CoreNLP/history.html) none of the models are live.

Please provide a solution

Thanks,

**Comment by AngledLuffa** [comment]
Ah, it must be Tuesday and our cluster is broken

**Comment by AngledLuffa** [comment]
It should be back now
