### ISSUE TITLE
Question: Is there a way to customize sentence break rules?

### ISSUE THREAD

**Issue by saxtell-cb** [stanfordnlp/CoreNLP#1179]
I have successfully used `ssplit.boundaryTokenRegex` to add cases in which to break a sentence. However, for the following example, I cannot find an option that allows me to prevent sentence breaks in certain cases:
>My cel. # 34345

Currently, Stanford gives me "My cel." and "# 34345" (two separate sentences), but I would like to tell Stanford to _NOT_ break after abbreviations such as "cel." and "ph.", etc. Is there a way to do this?

**Comment by AngledLuffa** [comment]
As far as I see, there is no mechanism currently built in for keeping
arbitrary tokens together.  You might want to check my work, though:
src/edu/stanford/nlp/process/WordToSentenceProcessor.java
and src/edu/stanford/nlp/pipeline/WordsToSentencesAnnotator.java

The reason some things get split and others don't is from the tokenizer,
defined in src/edu/stanford/nlp/process/PTBLexer.flex

If you dig through it, you'll see rules for keeping a variety of
abbreviations together.  ABTITLE, ABBREV4, etc.  Oddly it seems "Ph." is
one of the abbreviations in that list, so I'm not sure why you would get
sentence splits there.  "cel." is not - in what context is that a useful
abbreviation?

At any rate, unfortunately it looks like it would need a code change to
make it possible to add your own abbreviations.

**Comment by saxtell-cb** [comment]
Thanks @AngledLuffa!! I deal with lots of crazy data; admittedly, "cel." is not common but possible in my data. I'll see about adding and recompiling with some custom changes. Thanks again!
