### ISSUE TITLE
Not getting Universal Dependencies in spanish through CoreNLP Server 4.2.2

### ISSUE THREAD

**Issue by franciclo** [stanfordnlp/CoreNLP#1186]
Im having the same problem as described here:
https://stackoverflow.com/questions/58754796/how-can-i-use-the-stanford-nlp-part-of-speech-tagging-in-spanish

As described in the official Stanford NLP FAQs for spanish, the POS tags should be like "vmg0000" and not "VERB" that is what im gettinng and is not even penn tree bank.
https://nlp.stanford.edu/software/spanish-faq.html#tagset

What im trying is to get the tense of the verb, is there another way?
Is there a parameter to enable those more detailed POS tags?

thank you

**Comment by AngledLuffa** [comment]
There may be some confusion - VERB etc ARE the upos tags.  That's all we
supply now for Spanish.

**Comment by franciclo** [comment]
Thanks for the quick reply, so those may be universal dependency tags i got that wrong. But isn't this [answer](https://nlp.stanford.edu/software/spanish-faq.html#tagset) implies that CoreNLP support the fine grainn tags as well? Or is it in a separated tool?
https://nlp.stanford.edu/software/spanish-faq.html#tagset

**Comment by AngledLuffa** [comment]
> Currently, the only Spanish tagger model available is the Universal
Dependencies model. This uses standard UPOS tags.

The alternate tagset was from before 4.0

**Comment by franciclo** [comment]
Oh i see. i will try downgrading then.
Thank you very much!
