### ISSUE TITLE
Question about coref in output file

### ISSUE THREAD

**Issue by mcriggs** [stanfordnlp/CoreNLP#1187]
I would like to use the coreference feature in CoreNLP, but I have had problems with the output file. 

I ran the following code:

./corenlp.sh -annotators tokenize,ssplit,pos,lemma,ner,parse,coref -file text.txt -outputFormat conll

The output file has seven columns, which correspond to what looks like a token id, word, lemma, pos, ner, some numerical value, and dependency parsing. There does not appear to be any information related to coreference annotation.

Could you please advise me as to how I can change the code in order that the coreference annotation information appears in the output file.

Thank you.

**Comment by AngledLuffa** [comment]
Correct.  There is no coref in the conll output format.

https://nlp.stanford.edu/nlp/javadoc/javanlp/

conllu has a misc column, but coref is not included in possible misc
values, so I would conclude there is currently no way in CoreNLP to output
coref as part of a conll style output.

**Comment by mcriggs** [comment]
Thank you.
