### ISSUE TITLE
NERClassifierCombiner cannot load models from URL

### ISSUE THREAD

**Issue by reckart** [stanfordnlp/CoreNLP#120]
Unlike many other annotators, the NERClassifierCombiner cannot load models from URLs. To fix this, `AbstractSequenceClassifier.loadStreamFromClasspath(String)` (and probably some other methods calling it) should use `IOUtils.getInputStreamFromURLOrClasspathOrFileSystem()`. There is even a related comment in `AbstractSequenceClassifier`:

    todo [cdm 2015]: Replace this method with use of the method in IOUtils.

**Comment by AngledLuffa** [comment]
Good idea.  In fact, the IOUtils version uses some buffering, so the load
time for the pipeline is reduced by a few seconds with this change.
