### ISSUE TITLE
Quote Annotator - Documentation Discrepancy?

### ISSUE THREAD

**Issue by jaded-1** [stanfordnlp/CoreNLP#1201]
The Description for quotes in the Annotator Descriptions table (https://stanfordnlp.github.io/CoreNLP/annotators.html) states that quote: 
Does not depend on any other annotators.

But the Annotator Dependencies for quotes list these annotators as requirements: tokenize, ssplit, pos, lemma, ner, depparse, coref

I was able to run quote extraction simply using the quote annotator and it produced the same results as using the annotators above. So do we need to specify the annotators for quote?

with CoreNLPClient(annotators=['quote'], be_quiet=False, properties={'tokenize.codepoint': 'true'}) as client:

**Comment by AngledLuffa** [comment]
The initialization makes an attempt to pick the right annotators when it
starts.  It absolutely needs the other listed annotators to work correctly,
though.
