### ISSUE TITLE
Wrong tokenization for equation "Z = 408R1.20"

### ISSUE THREAD

**Issue by frankang** [stanfordnlp/CoreNLP#1219]
Hi, this sentence `The Z-R relationship was Z = 408R9.20  for the convective precipitation.` is tokenized into `The Z-R relationships were Z = 408R9 .20 for the convective precipitation .` . I tried many tokenizer options but were unable to resolve this issue. 
Any suggestion would be appreciated.

**Comment by AngledLuffa** [comment]
Currently there is no option I know of which will keep that as a token but
still split the sentence final punct.  I will look into how feasible it is

**Comment by frankang** [comment]
Thanks! This pattern also happens when software name with version number is presented with out spacing, like SPSS28.0.

**Comment by manning** [comment]
Thanks for this! We can see if we can further tweak things, but in general the tokenizers is only user-configurable in very limited ways because it's a big pre-compiled finite automaton.

Hopefully you also noticed that there were a lot of places where the new tokenizer is much better, since I spent a number of hours over the summer improving its tokenization performance on wikipedia. 😛

**Comment by AngledLuffa** [comment]
"version numbers" indeed

```
NLP> I was recently infected with Omicron BA2.12.1

Sentence #1 (8 tokens):
I was recently infected with Omicron BA2.12.1

Tokens:
[Text=I CharacterOffsetBegin=0 CharacterOffsetEnd=1]
[Text=was CharacterOffsetBegin=2 CharacterOffsetEnd=5]
[Text=recently CharacterOffsetBegin=6 CharacterOffsetEnd=14]
[Text=infected CharacterOffsetBegin=15 CharacterOffsetEnd=23]
[Text=with CharacterOffsetBegin=24 CharacterOffsetEnd=28]
[Text=Omicron CharacterOffsetBegin=29 CharacterOffsetEnd=36]
[Text=BA2 CharacterOffsetBegin=37 CharacterOffsetEnd=40]
[Text=.12.1 CharacterOffsetBegin=40 CharacterOffsetEnd=45]
```

**Comment by AngledLuffa** [comment]
It's updated on the dev branch to tokenize as

```
[Text=Z CharacterOffsetBegin=25 CharacterOffsetEnd=26]
[Text== CharacterOffsetBegin=27 CharacterOffsetEnd=28]
[Text=408R CharacterOffsetBegin=29 CharacterOffsetEnd=33]
[Text=9.20 CharacterOffsetBegin=33 CharacterOffsetEnd=37]
```
