### ISSUE TITLE
Unreleased Resource: Files

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [stanfordnlp/CoreNLP#1223]
https://github.com/stanfordnlp/CoreNLP/blob/d147ba597bb13efeab5c567d677854bfc69104e6/src/edu/stanford/nlp/ui/JarFileChooser.java#L129

The program can potentially fail to release a file handle.

**Comment by AngledLuffa** [comment]
Thanks.  There are probably a lot of cases like this in the codebase, but we can clean them up as we find them.

https://github.com/stanfordnlp/CoreNLP/commit/85e305bf63b3954e6266801175579a8b81769709

**Comment by AngledLuffa** [comment]
https://github.com/stanfordnlp/CoreNLP/commit/b606e0dbacc1ed6724949d24ff822ff8ad711920

actually, that covers the only other ZipFile in the codebase.  There's probably a ton of file streams & readers though
