### ISSUE TITLE
Java unknown class exception while running in eclipse

### ISSUE THREAD

**Issue by bubunia2000** [stanfordnlp/CoreNLP#1236]
Hi all,

I am trying to use stanford coreNLP libraries for sentimental analysis. I use it using eclipse and jdk 1.8.
I have downloaded the coreNLP libraries from https://stanfordnlp.github.io/CoreNLP/---->Download CoreNLP.zip file and stored in a local folder, I created a Java project in eclipse IDE using jdk1.8.301(Winows->Preferences-> Install JRE) and added the jars to class path and module path by Right Click on Project --->Configure Build Path -> Libraries(Add all the jars to the classpath)

1. When I tried to run it it gives an error:
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	String cannot be resolved to a type
	Properties cannot be resolved to a type
	Properties cannot be resolved to a type
	at stanfordcoreNLP.testNLP.main(testNLP.java:12)

Can anyone help me out how to successfully run Stanford CoreNLP libraries(4.3.2) using eclipse. Iam struggling and tried to find a answer from 2 days but could not succeed. I need some urgent help. Can someone help what is the step-by-step instructions to run stanford coreNLP libraries(4.3.2) in eclipse ?

2. I have a Amazon Data set and when I pass to using the command mentioned below it only results values like 0(negative or neutral) or 1(positive, very positive). I want to modify the existing code for sentiment to return multiple values for example ( 0= negative, 1= neutral, 2= positive,3=very positive) and calculate the maximum of positive I received, maximum of very positive I received and decide whether the sentiment is positive or negative or very positive. Could you please help urgently how can I achieve doing this? Most of the files are in jar format and I am not sure how can i make the code change for the above requirement to achieve the result? 

Regards
Pradeep

**Comment by bubunia2000** [comment]
I fixed the first problem partially I guess. Loading of libraries was not done properly in eclipse.
https://programmerall.com/article/2970765764/

**Actual Output is:**
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words-distsim.tagger ... done [4.3 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [7.5 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [5.0 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [3.8 sec].
ner.fine.regexner: Read 580705 unique entries out of 581864 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_caseless.tab, 0 TokensRegex patterns.
ner.fine.regexner: Read 4867 unique entries out of 4867 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_cased.tab, 0 TokensRegex patterns.
ner.fine.regexner: Read 585572 unique entries from 2 files

**Expected Output is** (See https://programmerall.com/article/2970765764/)
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words-distsim.tagger ... done [4.3 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [7.5 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [5.0 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [3.8 sec].
ner.fine.regexner: Read 580705 unique entries out of 581864 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_caseless.tab, 0 TokensRegex patterns.
ner.fine.regexner: Read 4867 unique entries out of 4867 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_cased.tab, 0 TokensRegex patterns.
ner.fine.regexner: Read 585572 unique entries from 2 files

**Adding annotator parser**
** Adding annotator dcoref**

Any idea how can I fix this.

I need some guidance on second question. Can someone throw some light how can I achieve this?

**Comment by AngledLuffa** [comment]
I think it is very likely you didn't include "parse" in your list of annotators, but without seeing the code, no one will be able to answer that for you.

**Comment by bubunia2000** [comment]
Issue is not because I have not included the parse annotators. It hanged
for a long time and then failed with "Out of Memory Exception" in
TokenParser module.
Below is the test code.

package Test;


import java.util.List;
import java.util.Map;
import java.util.Properties;

import edu.stanford.nlp.dcoref.CorefChain;
import edu.stanford.nlp.dcoref.CorefCoreAnnotations.CorefChainAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.LemmaAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.NamedEntityTagAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.PartOfSpeechAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.SentencesAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.TextAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.TokensAnnotation;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.pipeline.Annotation;
import edu.stanford.nlp.pipeline.StanfordCoreNLP;
import edu.stanford.nlp.semgraph.SemanticGraph;
import
edu.stanford.nlp.semgraph.SemanticGraphCoreAnnotations.CollapsedCCProcessedDependenciesAnnotation;
import edu.stanford.nlp.sentiment.SentimentCoreAnnotations;
import edu.stanford.nlp.trees.Tree;
import edu.stanford.nlp.trees.TreeCoreAnnotations.TreeAnnotation;
import edu.stanford.nlp.util.CoreMap;

public class CoreNLP {
    public static void main(String[] args) {
   // creates a StanfordCoreNLP object, with POS tagging, lemmatization,
NER, parsing, and coreference resolution
           Properties props = new Properties();
           props.put("annotators", "tokenize, ssplit, pos, lemma, ner,
parse, dcoref");
           StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
           // read some text in the text variable
           String text = "Add your text here:Beijing sings Lenovo";
           // create an empty Annotation just with the given text
           Annotation document = new Annotation(text);
           // run all Annotators on this text
           pipeline.annotate(document);
           // these are all the sentences in this document
           // a CoreMap is essentially a Map that uses class objects as
keys and has values with custom types
           List<CoreMap> sentences =
document.get(SentencesAnnotation.class);
           System.out.println("word\tpos\tlemma\tner");
           for(CoreMap sentence: sentences) {
                // traversing the words in the current sentence
               // a CoreLabel is a CoreMap with additional token-specific
methods
             for (CoreLabel token: sentence.get(TokensAnnotation.class)) {
                   // this is the text of the token
                String word = token.get(TextAnnotation.class);
                  // this is the POS tag of the token
                String pos = token.get(PartOfSpeechAnnotation.class);
                  // this is the NER label of the token
                String ne = token.get(NamedEntityTagAnnotation.class);
                String lemma = token.get(LemmaAnnotation.class);

                System.out.println(word+"\t"+pos+"\t"+lemma+"\t"+ne);
             }
              // this is the parse tree of the current sentence
              Tree tree = sentence.get(TreeAnnotation.class);
              // this is the Stanford dependency graph of the current
sentence
              SemanticGraph dependencies =
sentence.get(CollapsedCCProcessedDependenciesAnnotation.class);
          }
           // This is the coreference link graph
           // Each chain stores a set of mentions that link to each other,
           // along with a method for getting the most representative
mention
           // Both sentence and token offsets start at 1!
           Map<Integer, CorefChain> graph =
document.get(CorefChainAnnotation.class);
     }
  }

**Comment by bubunia2000** [comment]
Below is the exception and its backtrace.

Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Loading POS tagger from
edu/stanford/nlp/models/pos-tagger/english-left3words-distsim.tagger ...
done [4.3 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from
edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done
[7.5 sec].
Loading classifier from
edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done
[5.0 sec].
Loading classifier from
edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ...
done [3.8 sec].
ner.fine.regexner: Read 580705 unique entries out of 581864 from
edu/stanford/nlp/models/kbp/english/gazetteers/regexner_caseless.tab, 0
TokensRegex patterns.
ner.fine.regexner: Read 4867 unique entries out of 4867 from
edu/stanford/nlp/models/kbp/english/gazetteers/regexner_cased.tab, 0
TokensRegex patterns.
ner.fine.regexner: Read 585572 unique entries from 2 files
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
at
edu.stanford.nlp.ling.tokensregex.parser.TokenSequenceParser.<init>(TokenSequenceParser.java:3895)
at
edu.stanford.nlp.ling.tokensregex.TokenSequencePattern.getNewEnv(TokenSequencePattern.java:158)
at
edu.stanford.nlp.pipeline.TokensRegexNERAnnotator.createPatternMatcher(TokensRegexNERAnnotator.java:367)
at
edu.stanford.nlp.pipeline.TokensRegexNERAnnotator.<init>(TokensRegexNERAnnotator.java:319)
at
edu.stanford.nlp.pipeline.NERCombinerAnnotator.setUpFineGrainedNER(NERCombinerAnnotator.java:254)
at
edu.stanford.nlp.pipeline.NERCombinerAnnotator.<init>(NERCombinerAnnotator.java:170)
at
edu.stanford.nlp.pipeline.AnnotatorImplementations.ner(AnnotatorImplementations.java:90)
at
edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$8(StanfordCoreNLP.java:543)
at
edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$17/1469821799.apply(Unknown
Source)
at
edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$null$33(StanfordCoreNLP.java:622)
at
edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$39/1830908236.get(Unknown
Source)
at edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:126)
at edu.stanford.nlp.util.Lazy.get(Lazy.java:31)
at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:149)
at
edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:253)
at
edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:194)
at
edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:190)
at Test.CoreNLP.main(CoreNLP.java:31)

**Comment by AngledLuffa** [comment]
> Issue is not because I have not included the parse annotators. It hanged for a long time and then failed with "Out of Memory Exception" in TokenParser module.

How is anyone supposed to understand that based on the context you gave us???

Add more memory.

**Comment by bubunia2000** [comment]
Thanks John for quick response.
I can try that what is min jvm size required? I saw 2gb is enough. I have
4gb ram and I think it should be fine. But will check jvm settings once.

https://www.google.com/url?sa=t&source=web&rct=j&url=https://nlp.stanford.edu/software/corenlp-faq.html%23:~:text%3DRunning%2520the%2520full%2520CoreNLP%2520pipeline,operates%2520over%2520an%2520entire%2520document.&ved=2ahUKEwiO4Oz_1Pb0AhV3wjgGHf91AkQQFnoECAQQBQ&usg=AOvVaw3S-trkcHufeDMgz4qvifig
