### ISSUE TITLE
Is there a part of speech summary document? I can't find it on the official website

### ISSUE THREAD

**Issue by Jzow** [stanfordnlp/CoreNLP#1243]
such as:

How many parts of speech are there? Where do I look, or where do I look at the source code

```markdown
ROOT：要处理文本的语句
IP：简单从句
NP：名词短语
VP：动词短语
PU：断句符，通常是句号、问号、感叹号等标点符号
LCP：方位词短语
PP：介词短语
CP：由‘的’构成的表示修饰性关系的短语
DNP：由‘的’构成的表示所属关系的短语
ADVP：副词短语
ADJP：形容词短语
DP：限定词短语
QP：量词短语
NN：常用名词
NR：固有名词
NT：时间名词
PN：代词
VV：动词
VC：是
CC：表示连词
VE：有
VA：表语形容词
AS：内容标记（如：了）
VRD：动补复合词
CD: 表示基数词
DT: determiner 表示限定词
EX: existential there 存在句
FW: foreign word 外来词
IN: preposition or conjunction, subordinating 介词或从属连词
JJ: adjective or numeral, ordinal 形容词或序数词
JJR: adjective, comparative 形容词比较级
```

**Comment by AngledLuffa** [comment]
POS should be here:

https://hanlp.hankcs.com/docs/annotations/pos/ctb.html

but you've listed some category tags, so look here:

https://www.cs.brandeis.edu/~clp/ctb/

there's some more info on bracketing there

**Comment by Jzow** [comment]
thanks @AngledLuffa

**Comment by Jzow** [comment]
@AngledLuffa  hi , I'm sorry to bother you. I want to know which address is the part of speech in English, not in Chinese

**Comment by AngledLuffa** [comment]
Not to be too much of a jerk but you can just search for this  ... [ptb pos
tags] or something like that

https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html

**Comment by Jzow** [comment]
thanks
