### ISSUE TITLE
where are the files????

### ISSUE THREAD

**Issue by mintaka5** [stanfordnlp/CoreNLP#1254]
i can't access needed models, parsers, taggers, etc... 

it seems they have all been isolated to each contributing institution's repositories, and some of them are firewalled/broken to repos/versioning instances.

great library but practically unusable. Your library is lacking structural organization. please, resolve or FLAG the maven and gradle instances as broken! spent hours hunting down these files, just to discover the ones i need are blocked somehow.

![image](https://user-images.githubusercontent.com/87902810/155416651-95eeb35f-2c6f-45e3-9d59-e51f8a28f183.png)
![image](https://user-images.githubusercontent.com/87902810/155417642-19df61e2-c823-48a9-8cfb-52cfd504c234.png)
![image](https://user-images.githubusercontent.com/87902810/155417727-ca51c415-c7b8-48d8-b1e8-9daa5e49418f.png)

**Comment by AngledLuffa** [comment]
For a direct download, scroll down to quickstart:

https://stanfordnlp.github.io/CoreNLP/

The models are on maven and are not gated by anything:

https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/4.4.0/

If you need help making a maven pom which depends on the models, you can look here:

https://github.com/stanfordnlp/CoreNLP/blob/main/examples/sample-maven-project/pom.xml

or here

https://stackoverflow.com/questions/18492608/maven-fails-to-download-corenlp-models
