### ISSUE TITLE
JSONDecodeError when calling Chinese jar in Python

### ISSUE THREAD

**Issue by 4daJKong** [stanfordnlp/CoreNLP#1255]
I have download stanfordcorenlp 3.9.1.1 and the newest zip file stanford-corenlp-latest, still download Chinese model jar in this folder, when I run the code,
```
from stanfordcorenlp import StanfordCoreNLP
sentence = "香港理工大学校长滕锦光表示，任何情况下暴力都不是解决问题的方法。"
nlp_ch = StanfordCoreNLP(r'C:\stanford-corenlp-full-2018-02-27', lang='zh')
print('named entities:',nlp_ch.ner(sentence))
```
It shows error,
```
Exception has occurred: JSONDecodeError
Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

  File "[C:\...\stanford_filter.py]()", line 22, in <module>
    print('named entities:',nlp_ch.ner(sentence))

```
I have tried to download stanza, correct Json file but still didn't word, any idea?

**Comment by 4daJKong** [comment]
P.S python version is 3.7.0

**Comment by AngledLuffa** [comment]
If you can tell us what's going on with stanza, we can investigate that,
but we're not responsible for the stanfordcorenlp package

**Comment by 4daJKong** [comment]
```
import stanza
sentence = "香港理工大学校长滕锦光表示，任何情况下暴力都不是解决问题的方法。"
stanza.download('zh')
nlp_ch = stanza.Pipeline('zh')
doc = nlp_ch(sentence)
print(doc)
print(doc.entities)

```
```
Exception has occurred: SSLError
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /stanfordnlp/stanza-resources/main/resources_1.3.0.json (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:
```

**Comment by AngledLuffa** [comment]
I mean, removing the traceback defeats the purpose of sending us the
error.  However, the only line here which can cause that is the download,
so whatever.

Are you able to see these pages?

https://github.com/stanfordnlp/stanza-resources
https://github.com/stanfordnlp/stanza-resources/blob/main/resources_1.3.0.json
