### ISSUE TITLE
Timer logs normal messages to System.err

### ISSUE THREAD

**Issue by tlaukkan** [stanfordnlp/CoreNLP#126]
Thank you for this very useful library. Here is something minor I noticed:

Timer logs normal messages to System.err which results in mixed Logger and System.err lines in normal startup log.

Would be nice to log timing messages with debug level to Logger.

08:45:56 190  INFO   Adding annotator tokenize
08:45:56 193  INFO   TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
08:45:56 200  INFO   Adding annotator ssplit
08:45:56 201  INFO   Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... 08:45:57 210  INFO   Adding annotator lemma
done [1.0 sec].
08:45:57 210  INFO   Adding annotator parse
08:45:57 215  INFO   Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... 
done [0.3 sec].

```
  /** Print the start of timing message to stderr and start the timer. */
  public void doing(String str) {
    System.err.print(str);
    System.err.print(" ... ");
    System.err.flush();
    start();
  }

  /** Finish the line from startDoing with the end of the timing done message
   *  and elapsed time in x.y seconds.
   */
  public void done() {
    System.err.println("done [" + toSecondsString() + " sec].");
  }
```

**Comment by manning** [comment]
Hi @tlaukkan - yes, we realize that this is pretty much a mess at the moment.  But we've at least started to try to use logging, and hopefully it'll be cleaned up by version 3.6.1. (Among other things, the historical strategy of writing the beginning and then end of a line with doing(String) and done() illustrated above doesn't work with logging....

**Comment by dinoboy197** [comment]
> (Among other things, the historical strategy of writing the beginning and then end of a line with doing(String) and done() illustrated above doesn't work with logging....

When I started working on slf4j log conversion, I hesitated to do any changes to logging where there were log lines generated by multiple statements (in loops or with progress bars, etc). How would you like me to proceed with logging changes for instances like that?

**Comment by tlaukkan** [comment]
Hi @manning, @dinoboy197, one could consider implementing custom output stream which would redirect complete lines to slf4j and could replace System.out in the code base. Here is some related discussion:

http://stackoverflow.com/questions/11187461/redirect-system-out-and-system-err-to-slf4j
