### ISSUE TITLE
Array length and sentiment value

### ISSUE THREAD

**Issue by farbodsafaei** [stanfordnlp/CoreNLP#1260]
I'm new tho all of this, was looking at [RNNOptions.java](https://github.com/stanfordnlp/CoreNLP/blob/main/src/edu/stanford/nlp/sentiment/RNNOptions.java#L73) there are 5 class names:

```java
  public static final String[] DEFAULT_CLASS_NAMES = { "Very negative", "Negative", "Neutral", "Positive", "Very positive" };
````
and
```java
  public String[] classNames = DEFAULT_CLASS_NAMES;
```

and in [SentimentUtils.java](https://github.com/stanfordnlp/CoreNLP/blob/main/src/edu/stanford/nlp/sentiment/SentimentUtils.java#L84) there is this code:
```java
  public static String sentimentString(SentimentModel model, int sentiment) {
    String[] classNames = model.op.classNames;
    if (sentiment < 0 || sentiment > classNames.length) {
      return "Unknown sentiment label " + sentiment;
    }
    return classNames[sentiment];
  }
```

Can `sentiment` value ever be equal to `5`?

**Comment by AngledLuffa** [comment]
java arrays start at 0

**Comment by farbodsafaei** [comment]
Thanks @AngledLuffa , I am aware of that, the reason I asked, when trying to get a sentiment score of a sentence (which turns out to be very positive, from 
`RNNCoreAnnotations.getPredictedClass(tree)` the maximum value I get is a `4` and calling
`sentence.get(classOf[SentimentCoreAnnotations.SentimentClass])` gives me `Ver Positive` (sentence type is CoreMap)
looking at that array, I am trying to figure out the range of sentiment `int` and mapped String values

**Comment by AngledLuffa** [comment]
0 through 4

Although now that I look at that conditional, it looks like it should be >=
rather than >
