### ISSUE TITLE
BUG : java.util.logging.Logger shows multiple times after loop

### ISSUE THREAD

**Issue by Megnatis** [stanfordnlp/CoreNLP#1267]
I post a problem found in corenlp and java logger , when use logger in stanford nlp it can be happen for ssplit sentence too be multiple calls logger that I don't know what it is or what happen inside it but put my problem here
[stackoverflow.com:java-util-logging-logger-shows-multiple-times-after-loop](https://stackoverflow.com/questions/72115443/java-util-logging-logger-shows-multiple-times-after-loop)

**Comment by AngledLuffa** [comment]
It looks like this line is being called once per sentence:

```
for (String sentense : sentenses) {
   ....
                      Logger logger = Application.setupLog(BasicLocation.getBaseFileDir()+"logs");
}
```

You've made 7 (or N) loggers here, so any time you log something it will be logged 7 times if that's how that particular logging system works.  Most logging systems follow a pattern where you set it up *once*, at the very start of the program, and then *get* the existing logger when you need to use it.

Anyway, I don't see how this has anything to do with CoreNLP

**Comment by Megnatis** [comment]
the rest of program works fine and if i don't use the logger (like print) its normal . check all comment and codes .
because happened in this library.

**Comment by AngledLuffa** [comment]
No, it didn't happen in this library, it happened in the code you wrote
