### ISSUE TITLE
Parse sentence to tree structure like Stanford Sentiment Treebank

### ISSUE THREAD

**Issue by Garlandal** [stanfordnlp/CoreNLP#127]
As shown in the Stanford Sentiment Treebank demo on [Sentiment Analysis](http://nlp.stanford.edu/sentiment/treebank.html), it shows that the structure of the tree is definitely the binary tree,i learned that The Stanford Parser was used to parse all data sentences, and i tried it.

However, for English,The Stanford Parser has the following 4 model to parse english
 - englishFactored.ser.gz 
 - englishPCFG.caseless.ser.gz
 - englishPCFG.ser.gz 
 - englishRNN.ser.gz 

none of  them generates the same tree structure when i use the same dataset, i got three or four children on one node. I wonder which model should i choose to generate the binary structure tree like Stanford Sentiment Treebank or how can i generate such structure?

**Comment by AngledLuffa** [comment]
The option for binarized trees doesn't exist, but you could look at
edu.stanford.nlp.parser.tools.ParseAndSetLabels which can parse a list of
sentences and return binarized trees.  It doesn't gracefully handle the
case of what happens if you don't have labels, but you can just feed it an
empty file I guess

John

**Comment by Garlandal** [comment]
@AngledLuffa i'm sorry i did not found ParseAndSetLabels in edu.stanford.nlp.parser.tools, is it in this this repository?

**Comment by AngledLuffa** [comment]
https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/parser/tools/ParseAndSetLabels.java

**Comment by Garlandal** [comment]
it's my fault, Thank you very much.

**Comment by MingleiLI** [comment]
Hi, @Garlandal, have you completed the binary tree function?

**Comment by kittsville** [comment]
I was also wondering if any progress had been made by either @MingleiLI or @Garlandal.

There seem to be two files that could be relevant but I have had no luck with either:
- [TreeBinarizer.java](../blob/master/src/edu/stanford/nlp/parser/lexparser/TreeBinarizer.java)  
- [BuildBinarizedDataset.java](../blob/master/src/edu/stanford/nlp/sentiment/BuildBinarizedDataset.java)
