### ISSUE TITLE
Possible offset bug in edu/stanford/nlp/pipeline/JSONOutputter.java in CoreNLP 4.4.0

### ISSUE THREAD

**Issue by slbayer** [stanfordnlp/CoreNLP#1272]
At line 189:
```
              if (token.containsKey(CoreAnnotations.CodepointOffsetBeginAnnotation.class) &&
                  token.containsKey(CoreAnnotations.CodepointOffsetEndAnnotation.class)) {
                l3.set("codepointOffsetBegin", token.beginPosition());
                l3.set("codepointOffsetEnd", token.endPosition());
              }
```

Is this correct? It seems that in other places you report `token.get(CoreAnnotations.CodepointOffsetBeginAnnotation.class)`.

Also, at line 217, in the case where there are no sentences, the same enhancement should probably be added, I'm guessing.

**Comment by AngledLuffa** [comment]
Thanks, a fix is here on dev:

https://github.com/stanfordnlp/CoreNLP/commit/e0f6185adddabb615c17cf652818a18f270e70f0
