### ISSUE TITLE
XML External Entity (XXE) Injection

### ISSUE THREAD

**Issue by matanPyramid** [stanfordnlp/CoreNLP#1276]
according to snyk report the current latest release 
is vulnerable to XML External Entity (XXE) Injection
with no remediation since A fix was pushed into the master branch but not yet published.
please supply a date for the next release

**Comment by AngledLuffa** [comment]
Would you link the fix in the master branch?

**Comment by matanPyramid** [comment]
this is what appears in the snyk report https://github.com/stanfordnlp/CoreNLP/pull/1241/commits/916fc0c5c291fb03b9661eab4b9875d863aee775

https://security.snyk.io/vuln/SNYK-JAVA-EDUSTANFORDNLP-2339881

**Comment by AngledLuffa** [comment]
This is part of 4.4.0, released on Jan 20th

**Comment by matanPyramid** [comment]
they are still complaining about the 4.4.0 release 
introduced through: ... › edu.stanford.nlp:stanford-corenlp@4.4.0
we are using edu.stanford.nlp:stanford-corenlp@4.4.0 and according to the snyk report we are running 
the violation still exist

**Comment by AngledLuffa** [comment]
That patch was released.  You can verify this by unjarring the source and inspecting it yourself, if you like.  If there is another patch which is needed, we can implement that as well.

```
jar xvf stanford-corenlp-4.4.0-sources.jar > /dev/null

grep "TransformXML()" edu/stanford/nlp/process/TransformXML.java -A 9
  public TransformXML() {
    try {
      SAXParserFactory spf = SAXParserFactory.newInstance();
      spf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
      saxParser = spf.newSAXParser();
    } catch (Exception e) {
      log.info("Error configuring XML parser: " + e);
      throw new RuntimeException(e);
    }
  }
```

**Comment by matanPyramid** [comment]
snyk have fixed their vulnerability database.
