### ISSUE TITLE
hybrid coref missing model issue

### ISSUE THREAD

**Issue by eliujl** [stanfordnlp/CoreNLP#128]
Not sure if the following code is working for random forest for 'hybrid' coref:

 public static String getPathModel(Properties props, String sievename) {
    return props.getProperty(PATH_SERIALIZED_PROP) + File.separator +
        props.getProperty(PATH_MODEL_PROP.replace("SIEVENAME", sievename), "MISSING_MODEL_FOR_"+sievename);
  }
in src\edu\stanford\nlp\hcoref\CorefProperties.java

**Comment by J38** [comment]
Hybrid coref is not supported for English, so I think if you try to run it on English you could run into some missing model issues.  It is possible the English models jar has all the jars you need but at the moment no effort has gone into checking that hybrid coref works for English.  dcoref and statistical work for English, hybrid is used for Chinese.  At the moment we are only supporting what is described on this page: http://stanfordnlp.github.io/CoreNLP/coref.html

**Comment by eliujl** [comment]
Many thanks. I indeed saw the implementation of random forest sieves but was wondering if they can be used. Are they used anywhere in the package? If yes, then I may be able to use them as examples to figure out.

For Chinese hybrid coref, my impression is that it still just uses rule-based, deterministic sieves (ExactStringMatch, etc.). Is there anything hybrid with it? BTW is word embedding implemented?
