### ISSUE TITLE
Downloading CoreNLP zip Not Responding

### ISSUE THREAD

**Issue by kyleyost** [stanfordnlp/CoreNLP#1280]
Hello, I am using the stanza python library which is timing out when it attempts to download CoreNLP zip file from this location 
downloads.cs.stanford.edu/nlp/software/stanford-corenlp-latest.zip

I tried hitting the download button on this link and it does not respond either
https://stanfordnlp.github.io/CoreNLP/

I am also unable to download from this backup link 
https://nlp.stanford.edu/software/corenlp-backup-download.html

**Comment by AngledLuffa** [comment]
Yeah...

https://uit.stanford.edu/service-alerts/power-outage-and-it-services-updates

It is possible to download from HuggingFace, actually:

https://huggingface.co/stanfordnlp/CoreNLP/tree/main

**Comment by AngledLuffa** [comment]
Which version of Stanza are you using?  v1.4.0 is already set to download
from HF and not from the Stanford website.
