### ISSUE TITLE
Having Bundle-SymbolicName header missing, cannot install bundle

### ISSUE THREAD

**Issue by gcalandria** [stanfordnlp/CoreNLP#1292]
Hello everyone, I'm trying to use this dependency from my AEM project (maven based) but the dependency is not being installed because I have the following error:

`Bundle-SymbolicName header missing, cannot install bundle`

Can some one help me on this?

**Comment by AngledLuffa** [comment]
Probably your `pom.xml` or whatever you used to build the maven project is screwed up, but it's not like we'd know, considering you gave us zero information to help you with

**Comment by gcalandria-populicom** [comment]
I don't have access right now to the `pom.xml` but I know is not screwed up since it works without that dependency. AFAIK this dependency is not an OSGi dependency and that's what's giving me problems. Is this an OSGi bundle?

**Comment by J38** [comment]
This sample app should work: https://github.com/stanfordnlp/CoreNLP/tree/main/examples/sample-maven-project

**Comment by J38** [comment]
I don't believe it is OSGi ready.

Maybe this thread could help ? 

https://stackoverflow.com/questions/34087943/make-maven-dependency-osgi-ready

**Comment by AngledLuffa** [comment]
Yeah, I don't foresee us doing any work to incorporate OSGi
