### ISSUE TITLE
Training materials for Chinese models

### ISSUE THREAD

**Issue by echointherain** [stanfordnlp/CoreNLP#1293]
What are the training materials for your Chinese model? Are they newspaper news or are they social media texts? Or maybe there are other sources.

**Comment by AngledLuffa** [comment]
Which model?  In general it'll be some version of CTB for the segmenter,
POS, and conparse, UD for the depparse, and OntoNotes for NER and coref

**Comment by AngledLuffa** [comment]
Was that a sufficient answer?
