### ISSUE TITLE
 Error while loading a tagger model (probably missing model file) AEM

### ISSUE THREAD

**Issue by meguia25** [stanfordnlp/CoreNLP#1294]
We have an AEM project on version 6.5.13. We are trying to integrate Stanford CoreNLP without success.
First we had to transform the jar into an OSGi bundle, and with that mad work the dependencies. But now er are facing that the models are not being found. 
Tried to do the same, and installed it as a OSGi bundle. 
this is the pom.xml
```
            <dependency>
                <groupId>edu.stanford.nlp</groupId>
                <artifactId>stanford-corenlp</artifactId>
                <version>4.4.0</version>
            </dependency>
            <dependency>
                <groupId>edu.stanford.nlp</groupId>
                <artifactId>stanford-corenlp</artifactId>
                <version>4.4.0</version>
                <classifier>models</classifier>
            </dependency>
```
![image](https://user-images.githubusercontent.com/17273356/184004335-76c534ba-c931-402e-a7ff-12b4dfd7dc8d.png)

this is the error
![image](https://user-images.githubusercontent.com/17273356/184003714-adc92485-a24e-4b0b-9fd3-b31ca839abf3.png)

i don't have acces to the classpath to the project
Can someone help on this?

Thanks

**Comment by AngledLuffa** [comment]
None of us know anything about OSGi or have any inclination to learn.  My best suggestion would be to make sure you can integrate corenlp with the rest of your maven project before trying to convert it to OSGi.

**Comment by gcalandria** [comment]
Nice helping dude

**Comment by AngledLuffa** [comment]
Would you rather hear that we don't know how to fix problems with OSGi, or would you rather never hear back from us at all?

**Comment by AngledLuffa** [comment]
I actually found a friend who used OSGi over ten years ago.  Apparently there are libraries which can help, such as

https://maven.apache.org/shared/maven-osgi/apidocs/org/apache/maven/shared/osgi/Maven2OsgiConverter.html

also Eclipse can convert a maven project to an osgi bundle, but that takes a manual step for each release

There are three of us in the group who still work with Java in some capacity, and none of us have the capacity to learn a new toolset with such a limited application, so I encourage you to take these suggestions and do the best you can with them.  Or just use a different package management tool

**Comment by meguia25** [comment]
Hi, yes, we tried that, and solved the dependencies issues.
We have issues with the models, what we have done is modify the paths on defaultPaths.class to a location that we have access.
But have this issue now: 
![image](https://user-images.githubusercontent.com/17273356/184224140-81ce0086-7884-4309-a514-0263a63032d7.png)
where the header of the file is invalid.

The file is the one on https://github.com/stanfordnlp/CoreNLP/blob/main/scripts/pos-tagger/english-left3words-distsim.tagger.props, we tried removing the comment and got the same issue.

Have any idea why this can happen? 

Thanks in advance

**Comment by AngledLuffa** [comment]
I believe it is saying the header of the Java stream is corrupted, not the file itself.

The default mechanism for loading the models is to read them from jar files in the classpath.  I don't know exactly what you mean by "modify the paths on DefaultPaths.class", but if I had to guess, you extracted the files from that jar file somewhere and rebuild the CoreNLP jar itself with a new `edu/stanford/nlp/pipeline/DefaultPaths`

I do not think that should be necessary, but again, I know nothing about AEM or OSGi.  I think instead what you can do is wrap the models jar the same way as you wrapped the CoreNLP jar without having changed DefaultPaths.  If the jar file is in your classpath, then it should be able to open a stream to that jar file and read in the models.

BTW, if you come up with an easy to incorporate change that will make OSGi more accessible for future releases, feel free to send us a PR.  A couple bugs have turned up since releasing 4.5.0, so making a bugfix release in the near future is a possibility.

**Comment by GonzaloCalandria** [comment]
@AngledLuffa which are the models files we need to work on? the base ones? it is just `stanford-corenlp-4.5.0-models.jar` or we need to also work with `stanford-corenlp-4.5.0-models-english.jar` and `stanford-corenlp-4.5.0-models-english-kbp.jar`?

**Comment by AngledLuffa** [comment]
​If you're just doing basic CoreNLP, you only need ` stanford-corenlp-4.5.0-models.jar`

**Comment by AngledLuffa** [comment]
The KBP models are pretty niche usage.  The `english` models include the shift-reduce parser models, which is more accurate than the PCFG parser for constituency parsing

**Comment by GonzaloCalandria** [comment]
I've added both `stanford-corenlp-4.5.0.jar` and `stanford-corenlp-4.5.0-models.jar` to my classpath but I keep having the error `Error while loading a tagger model (probably missing model file)`.
Am I missing something?

**Comment by AngledLuffa** [comment]
Is the problem still the same, and it is saying the stream is corrupted?  You can try some various things in terms of debugging, such as seeing if you can load other files which we know to be in the jar file from within your USGi application.  For example, just open the file `edu/stanford/nlp/models/pos-tagger/english-left3words-distsim.tagger.props` which it says is corrupted, or open some other txt file such as  `edu/stanford/nlp/models/ud/feature_map.txt`  You can get a URL which describes the file with something like

```
ClassLoader classLoader = getClass().getClassLoader();
URL resource = classLoader.getResource(fileName);
```

Ultimately I just don't know anything about USGi, and all I can do is make general suggestions for figuring out where it's going wrong.  One thing we could try is that if you send instructions on how to build the USGi version and some simple instructions on how to run it, I can give that a try and see if there's something obvious going wrong.

**Comment by GonzaloCalandria** [comment]
@AngledLuffa does this means the file is being read?
<img width="824" alt="image" src="https://user-images.githubusercontent.com/2286280/184457710-7e1c93d0-4bfa-4a96-9b6b-d6267dd23f94.png">

**Comment by AngledLuffa** [comment]
Are you able to output the contents of the file?  I suggested text files so you could see if the contents are the same as in the original file.  If you are or aren't able to output the contents of the .props file, that might tell us something about where the problem is

**Comment by AngledLuffa** [comment]
I'm going to put together a bugfix release early this week, possibly tomorrow.  Is there an update of some kind which will make it easier for you to convert a maven project to OSGi?  Again, I don't know much about this, but my understanding is there's something we can do to the manifest which will make it more compatible.

**Comment by meguia25** [comment]
Hey, we decide to take another path. Putting the corenlp code on an spring bott application, and using it as rest api
Thanks for the help

**Comment by AngledLuffa** [comment]
Glad to hear it's working!
