### ISSUE TITLE
NullPointerException frrom shift-reduce parser or udfeats model

### ISSUE THREAD

**Issue by mo3ath** [stanfordnlp/CoreNLP#1303]
I got the following error

> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
> [main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words-distsim.tagger ... done [0.5 sec].
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
> [main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/srparser/englishSR.ser.gz ... done [9.4 sec].
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator udfeats
> 
> Processing file /home/...../test ... writing to /home/moath/dec_exp/data/test.conllu
> Exception in thread "main" java.lang.NullPointerException
>         at edu.stanford.nlp.trees.ud.UniversalDependenciesFeatureAnnotator.getPOSFeatures(UniversalDependenciesFeatureAnnotator.java:86)
>         at edu.stanford.nlp.trees.ud.UniversalDependenciesFeatureAnnotator.addFeatures(UniversalDependenciesFeatureAnnotator.java:395)
>         at edu.stanford.nlp.pipeline.UDFeatureAnnotator.doOneSentence(UDFeatureAnnotator.java:48)
>         at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:102)
>         at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
>         at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:653)
>         at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:663)
>         at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1261)
>         at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1095)
>         at edu.stanford.nlp.pipeline.StanfordCoreNLP.run(StanfordCoreNLP.java:1361)
>         at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1430)
> 

while running the following configuration  `java -Xmx30g -cp "../../stanford-corenlp-4.2.0/*" edu.stanford.nlp.pipeline.StanfordCoreNLP -file test -annotators tokenize,ssplit,pos,parse,udfeats -outputFormat conllu -parse.model edu/stanford/nlp/models/srparser/englishSR.ser.gz`  

The error disappears when I use the default PCFG parser.

I am using a dataset of tweets. so I tried minimizing the text to the minimum part that can reproduce the problem and reached the following 12 line text (also attached)

> RT @BTS_zone7: @FIFAWorldCup ▒█▀▀█ ▀▀█▀▀ ▒█▀▀▀█
> ▒█▀▀▄ ░▒█░░ ░▀▀▀▄▄
> ▒█▄▄█ ░▒█░░ ▒█▄▄▄█
> 
> Fake Love by @BTS_twt
> #BTSxFifaWorldCup
> 
> <endoftweet>
> 
> 
> 
> RT @Cerridwensheart: When all else fails turn up the music. 🎶 https://t.co/YT28PG41Oj

I am using CoreNLP 4.2.0 on Ubuntu 18.04.4 system

The error appeared on many files I am processing, but I only tracked one of them.
Anyway to avoid it?

Thanks,
[test.txt](https://github.com/stanfordnlp/CoreNLP/files/9568709/test.txt)

**Comment by AngledLuffa** [comment]
> I am using CoreNLP 4.2.0 on Ubuntu 18.04.4 system

https://www.youtube.com/watch?v=uSvJaYxRoB4

**Comment by mo3ath** [comment]
> > I am using CoreNLP 4.2.0 on Ubuntu 18.04.4 system
> 
> https://www.youtube.com/watch?v=uSvJaYxRoB4

I just checked, and this seems to work fine in 4.5, sorry about that.
