### ISSUE TITLE
No head rule defined

### ISSUE THREAD

**Issue by GeorgeS2019** [stanfordnlp/CoreNLP#1306]
Stanford.NLP.Parser: 4.2.0.2(https://www.nuget.org/packages/Stanford.NLP.Parser/4.2.0.2)

Problem: happens when using German using the 4.5.1 model 
Relevant [issue](https://github.com/sergey-tihon/Stanford.NLP.NET/issues/126)
```cs
//using c# wrapper 4.2.0.2
var gs = gsf.newGrammaticalStructure(parse);
```
```
java.lang.IllegalArgumentException: 'No head rule defined for NUR using class edu.stanford.nlp.trees.UniversalSemanticHeadFinder in (NUR
  (S (PROPN Christian) (AUX ist)
    (NP (PRON mein) (NOUN Freund)))
  (PUNCT .))
```

**Comment by GeorgeS2019** [comment]
- [german depparser is not working correctly](https://github.com/stanfordnlp/CoreNLP/issues/1227)
- [German parsing without dependency relations](https://github.com/stanfordnlp/CoreNLP/issues/670)

**Comment by AngledLuffa** [comment]
I'm sorry, but it's completely impossible to diagnose the problem with this little information.  Why are you linking random other issues just because they have the word "German" in them?

**Comment by GeorgeS2019** [comment]
I have tested more, there are more issues than this
