### ISSUE TITLE
Why Naive Bayes Classifier is not available in the latest (3.6.0) jar ?

### ISSUE THREAD

**Issue by unoexperto** [stanfordnlp/CoreNLP#131]
Why Naive Bayes Classifier is not available in the latest (3.6.0) jar ? What should I use ?

Thanks!

**Comment by J38** [comment]
When was the last time it was included in the Stanford CoreNLP jar?  It seems like it has been gone a long time.  I think it's included with the classifier distribution: 

http://nlp.stanford.edu/software/classifier.html

**Comment by cppexpert** [comment]
I don't think it ever was but it seems strange that it's the only method that is excluded from `classify` package. Others such as `ColumnDataClassifier` or `SVMLightClassifier` are in place. 

Is there particular reason it is excluded ?

The reason I noticed it is because your NLP course on cursera.org has section dedicated to Naive Bayes (https://class.coursera.org/nlp/).

**Comment by J38** [comment]
Well if you get the classifier distribution and add stanford-classifier-3.6.0.jar to your CLASSPATH you will be able to use the Naive Bayes.

**Comment by cppexpert** [comment]
I see. But if I get `"edu.stanford.nlp" % "stanford-corenlp" % "3.6.0"` from maven and add manually `stanford-classifier-3.6.0.jar` wouldn't it result in duplicate classes in my classpath ? How would you suggest to avoid that ?

**Comment by J38** [comment]
Both distributions are built from the same src , so while there will be duplicates they will be identical.

**Comment by cppexpert** [comment]
All right. But just curious what's the reason for excluding Naive Bayes from `stanford-corenlp` ?

**Comment by cppexpert** [comment]
Also there is previous version of classifier at http://nlp.stanford.edu/software/classifier.html. Is there 3.6.0 ?

**Comment by J38** [comment]
We recently changed the website, let me update it to have the download link for classifier 3.6.0

**Comment by J38** [comment]
Ok I updated the site to have the link to 3.6.0

**Comment by J38** [comment]
I am not sure why Naive Bayes has historically not been included, I suppose in future versions we can add it.

**Comment by cppexpert** [comment]
Thanks!

Yes, please add it. It would be great. Having manual dependency is not too bad but from perfectionist's point of view is undesirable :)
