### ISSUE TITLE
'email' tokenizing as 'em, ail, and '

### ISSUE THREAD

**Issue by saxtell-cb** [stanfordnlp/CoreNLP#1316]
In the following sentence (from Twitter), `'email'` is being tokenized as `'em`, `ail`, and `'`. This is obviously incorrect. What can be done to stop this split?

* It's official (according to the AP) it's 'email' not 'e-mail' and 'website' not 'web-site'!

I have the following parameters set:
`tokenize.language`: English
`tokenize.whitespace`: false (because we want tokens like `it's` to separate into `it` and `'s`)
`tokenize.keepeol`: false
`tokenize.verbose`: false
`tokenize.options`: invertible=true,splitAssimilations=false,splitHyphenated=false,splitForwardSlash=true,untokenizable=allKeep,strictTreebank3=true,normalizeSpace=false,ellipses=original

**Comment by AngledLuffa** [comment]
I gotta run this by my PI, who knows the tokenizer much better than I do, but I think this PR should address the situation

**Comment by AngledLuffa** [comment]
@manning

**Comment by manning** [comment]
LGTM. Fine to merge.

(I added to your PR a documentation fix to the previous line cleaning up the "C'mon" tokenization change.)

**Comment by AngledLuffa** [comment]
This is now released in 4.5.2
