### ISSUE TITLE
do i can work in Persian language?

### ISSUE THREAD

**Issue by vahidalvandi** [stanfordnlp/CoreNLP#1320]

**Comment by AngledLuffa** [comment]
Nothing's stopping you from trying, but we have zero support for it in CoreNLP

You would have better luck using Stanza, which is trained on UD and has an NER model as well

https://stanfordnlp.github.io/stanza/

If you happen to find a Persian constituency treebank, we'll be happy to incorporate that as well

**Comment by vahidalvandi** [comment]
constituency treebank in persian for core nlp ?

**Comment by AngledLuffa** [comment]
Sure, if you have one, we'll use one.  Either CoreNLP or Stanza (which also has a conparser)

**Comment by vahidalvandi** [comment]
please show me how i can deply it in a sample like arabic , from scatch

**Comment by AngledLuffa** [comment]
Both CoreNLP and Stanza need trees in a format such as

```
(ROOT (S (NP (DT This)) (VP (VBZ is) (NP (DT a) (NN test)))))
```

Having said that, there's already a dependency parser and NER model in Stanza for Farsi.  What is it you actually need?

**Comment by vahidalvandi** [comment]
i found persian treebank in persian , what is diff CoreNLP or Stanza  , do CoreNLP better than Stanza ??
https://github.com/UniversalDependencies/UD_Persian-Seraji

**Comment by AngledLuffa** [comment]
Yes, that's a dependency treebank.  Stanza has a stronger model in general, and already has a model built for the Persian datasets.  We used this one as a default, but you can switch to a different model if you like:

https://github.com/UniversalDependencies/UD_Persian-PerDT

If you're looking for something already made, and can use either Java or Python for your work, I highly recommend just switching to Python and using Stanza

**Comment by vahidalvandi** [comment]
very cool .

**Comment by vahidalvandi** [comment]
http://stanza.run/

not work in persian ,,,not show any proccess

**Comment by AngledLuffa** [comment]
hmm, it's working for me, but what you could do instead is just install stanza via pip or by cloning our git repo, and then run it and see how the results go
