### ISSUE TITLE
How to format pos and parse result into conll format?

### ISSUE THREAD

**Issue by Hins** [stanfordnlp/CoreNLP#1321]
Thanks in advance.

**Comment by AngledLuffa** [comment]
https://stanfordnlp.github.io/CoreNLP/cmdline.html#output

When you say "parse", you mean the constituency parse?  What would that look like in conll format?  There are a couple ways of doing that, such as [suggested here](https://mailman.uib.no/public/corpora/2019-July/030495.html), but I don't believe we've implemented any.

So for example, if you do 

```
java edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat conll -annotators "tokenize,pos,parse"
```

you'll get tokens, POS, and (perhaps surprisingly) a dependency conversion of the parse tree, but no constituency parse tree:

```
NLP> Jennifer has lovely antennae
1       Jennifer        _       NNP     _       2       nsubj
2       has     _       VBZ     _       0       ROOT
3       lovely  _       JJ      _       4       amod
4       antennae        _       NN      _       2       obj
```

**Comment by Hins** [comment]
> 

Thanks a lot, I found CoNLLOutputter instead.
