### ISSUE TITLE
Verb tagged as NNP in parse

### ISSUE THREAD

**Issue by charlieegan3** [stanfordnlp/CoreNLP#133]
> Jack accompanied Gill.

Results in the following parse:
```
(ROOT\n  (NP (NNP Jack) (NNP accompanied) (NNP Jill.)))
```

_accompanied_ is incorrectly tagged as a proper noun.

However in the dependancy parse it is correctly annotated:
<img width="213" alt="screen shot 2016-01-31 at 12 06 40" src="https://cloud.githubusercontent.com/assets/1774239/12702037/aabfb342-c813-11e5-8951-0ed9853296f6.png">

**Comment by charlieegan3** [comment]
I removed `"tokenize.whitespace": "true"` from the request params, this seems to have fixed the issue.

**Comment by sebschu** [comment]
Yes, this is not surprising. Without the sentence-final period (which won't be its own token if you set `tokenize.whitespace` to `true`) the parser is less likely to interpret a phrase as an entire sentence and therefore also parses without a verb will get assigned a high probability.
