### ISSUE TITLE
How to get “basic dependencies” or "enhancedDependencies" with the option “-outputFormat text”

### ISSUE THREAD

**Issue by JasmineChen123** [stanfordnlp/CoreNLP#1339]
I am using this command to get the dependency parsing result of sentence.
```sh
java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,parse  \
-tokenize.whitespace true  -tokenize.keepeol true  -tokenize.language English -ssplit.eolonly  true \
-outputFormat text  < test.en > test.en.out
```
When I set the "-outputFormat text ", I only get enhanced plus plus dependencies result, like:
root(ROOT-0, ask-5)
advmod(ask-5, However-1)
punct(ask-5, ,-2)
nsubj(ask-5, I-3)
nsubj(ask-5', I-3)
nsubj(ask-5'', I-3)
nsubj(ask-5''', I-3)
nsubj(ask-5'''', I-3)
nsubj(ask-5''''', I-3)
nsubj(ask-5'''''', I-3)
aux(ask-5, would-4)
conj:or(ask-5, ask-5')
conj:or(ask-5, ask-5'')
conj:or(ask-5, ask-5''')
conj:and(ask-5, ask-5'''')
conj:and(ask-5, ask-5''''')
conj:and(ask-5, ask-5'''''')

But I need basic dependencies or enhancedDependencies result.
How can I get “basic dependencies” or "enhancedDependencies" with the option “-outputFormat text”?

**Comment by AngledLuffa** [comment]
Great question.  Actually, that feature currently doesn't exist in the text format.  Bad news is that apparently I was the one who wrote it, so I'm on the hook for adding such a feature

**Comment by AngledLuffa** [comment]
As of the next release (which we expect in a couple weeks), this will work:

```java edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat text -annotators "tokenize,pos,lemma,ner,depparse" -output.dependencyType basic```

if you want it sooner than that, you can download & compile our dev branch

**Comment by JasmineChen123** [comment]
> As of the next release (which we expect in a couple weeks), this will work:
> 
> `java edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat text -annotators "tokenize,pos,lemma,ner,depparse" -output.dependencyType basic`
> 
> if you want it sooner than that, you can download & compile our dev branch

Sorry my English is poor.  Does it mean that I can use this command after I compile the dev branch now rather than waiting util a couple of weeks later?

**Comment by AngledLuffa** [comment]
> Does it mean that I can use this command after I compile the dev branch now rather than waiting util a couple of weeks later?

Yes, that's the intent.

**Comment by JasmineChen123** [comment]
> As of the next release (which we expect in a couple weeks), this will work:
> 
> `java edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat text -annotators "tokenize,pos,lemma,ner,depparse" -output.dependencyType basic`
> 
> if you want it sooner than that, you can download & compile our dev branch

Thanks a lot. After compiling with command 'ant', it works.
