### ISSUE TITLE
Cycles in constituent to dependency conversion for English when-clauses

### ISSUE THREAD

**Issue by amir-zeldes** [stanfordnlp/CoreNLP#134]
Hi, I'm using the constituent to dependency conversion using original, non-collapsed dependencies like this:

```
java -mx2056m -cp "*;" edu.stanford.nlp.trees.EnglishGrammaticalStructure -treeFile FILE -originalDependencies -nonCollapsed -conllx
```

and I'm consistently seeing cycles in the output when a construction with tmod+when clause occurs. It looks like for some reason the object of a preposition before 'when' gets misinterpreted and a relative clause is produced instead of advcl. Here's an example from WSJ data - note how 14 has the head 17 and vice versa:

```
1	Last	_	ADJ	JJ	_	2	amod	_	_
2	summer	_	NOUN	NN	_	6	tmod	_	_
3	,	_	PUNCT	,	_	6	punct	_	_
4	Mr.	_	PROPN	NNP	_	5	nn	_	_
5	Bush	_	PROPN	NNP	_	6	nsubj	_	_
6	moved	_	VERB	VBD	_	0	root	_	_
7	the	_	DET	DT	_	8	det	_	_
8	administration	_	NOUN	NN	_	6	dobj	_	_
9	in	_	ADP	IN	_	6	prep	_	_
10	the	_	DET	DT	_	11	det	_	_
11	direction	_	NOUN	NN	_	9	pobj	_	_
12	of	_	ADP	IN	_	11	prep	_	_
13	gradual	_	ADJ	JJ	_	14	amod	_	_
14	liberalization	_	NOUN	NN	_	17	tmod	_	_
15	when	_	ADV	WRB	_	17	advmod	_	_
16	he	_	PRON	PRP	_	17	nsubj	_	_
17	told	_	VERB	VBD	_	14	rcmod	_	_
18	a	_	DET	DT	_	22	det	_	_
19	North	_	PROPN	NNP	_	22	nn	_	_
20	Atlantic	_	PROPN	NNP	_	22	nn	_	_
21	Treaty	_	PROPN	NNP	_	22	nn	_	_
22	Organization	_	PROPN	NNP	_	23	nsubj	_	_
23	meeting	_	NOUN	NN	_	17	xcomp	_	_
24	that	_	SCONJ	IN	_	27	mark	_	_
25	he	_	PRON	PRP	_	27	nsubj	_	_
26	would	_	AUX	MD	_	27	aux	_	_
27	allow	_	VERB	VB	_	17	ccomp	_	_
28	some	_	DET	DT	_	29	det	_	_
29	exceptions	_	NOUN	NNS	_	27	dobj	_	_
30	to	_	ADP	TO	_	6	prep	_	_
31	the	_	DET	DT	_	33	det	_	_
32	Cocom	_	PROPN	NNP	_	33	nn	_	_
33	embargo	_	NOUN	NN	_	30	pobj	_	_
34	of	_	ADP	IN	_	33	prep	_	_
35	strategic	_	ADJ	JJ	_	36	amod	_	_
36	goods	_	NOUN	NNS	_	34	pobj	_	_
37	.	_	PUNCT	.	_	6	punct	_	_
```

Thanks for your help!
Amir

**Comment by sebschu** [comment]
Which version of CoreNLP are you using? I wasn't able to reproduce the bug with the current codebase and it might be that this was fixed by a change that I pushed sometime last year.

**Comment by amir-zeldes** [comment]
I downloaded the parser as a standalone, v3.6.0 - 2015-12-09. Sorry if this is the wrong place to post specifically about the parser release! I can post the constituent tree I got too if you need it.

**Comment by sebschu** [comment]
I tried it again with the latest version of the parser and I get the following result which doesn't contain any cycles:

```
1	Last	_	ADJ	JJ	_	2	amod	_	_
2	summer	_	NOUN	NN	_	6	tmod	_	_
3	,	_	PUNCT	,	_	6	punct	_	_
4	Mr.	_	PROPN	NNP	_	5	nn	_	_
5	Bush	_	PROPN	NNP	_	6	nsubj	_	_
6	moved	_	VERB	VBD	_	0	root	_	_
7	the	_	DET	DT	_	8	det	_	_
8	administration	_	NOUN	NN	_	6	dobj	_	_
9	in	_	ADP	IN	_	6	prep	_	_
10	the	_	DET	DT	_	11	det	_	_
11	direction	_	NOUN	NN	_	9	pobj	_	_
12	of	_	ADP	IN	_	11	prep	_	_
13	gradual	_	ADJ	JJ	_	14	amod	_	_
14	liberalization	_	NOUN	NN	_	12	pobj	_	_
15	when	_	ADV	WRB	_	17	advmod	_	_
16	he	_	PRON	PRP	_	17	nsubj	_	_
17	told	_	VERB	VBD	_	6	advcl	_	_
18	a	_	DET	DT	_	23	det	_	_
19	North	_	PROPN	NNP	_	23	nn	_	_
20	Atlantic	_	PROPN	NNP	_	23	nn	_	_
21	Treaty	_	PROPN	NNP	_	23	nn	_	_
22	Organization	_	PROPN	NNP	_	23	nn	_	_
23	meeting	_	NOUN	NN	_	17	dobj	_	_
24	that	_	SCONJ	IN	_	27	mark	_	_
25	he	_	PRON	PRP	_	27	nsubj	_	_
26	would	_	AUX	MD	_	27	aux	_	_
27	allow	_	VERB	VB	_	17	ccomp	_	_
28	some	_	DET	DT	_	29	det	_	_
29	exceptions	_	NOUN	NNS	_	27	dobj	_	_
30	to	_	ADP	TO	_	29	prep	_	_
31	the	_	DET	DT	_	33	det	_	_
32	Cocom	_	PROPN	NNP	_	33	nn	_	_
33	embargo	_	NOUN	NN	_	30	pobj	_	_
34	of	_	ADP	IN	_	33	prep	_	_
35	strategic	_	ADJ	JJ	_	36	amod	_	_
36	goods	_	NOUN	NNS	_	34	pobj	_	_
37	.	_	PUNCT	.	_	6	punct	_	_
```

Did you preprocess the tree from the PTB in any way? And can you make sure that no old versions of the parser or CoreNLP are in your classpath?

**Comment by amir-zeldes** [comment]
Sorry for not being more specific: I actually parsed this from plain text with the Stanford Parser for an experiment, so it's not the exact PTB tree with traces etc. Here is the underlying bracket tree that got me this output:

```
(ROOT
  (S
    (NP (JJ Last) (NN summer))
    (, ,)
    (NP (NNP Mr.) (NNP Bush))
    (VP (VBD moved)
      (NP (DT the) (NN administration))
      (PP (IN in)
        (NP
          (NP (DT the) (NN direction))
          (PP (IN of)
            (NP
              (NP (JJ gradual) (NN liberalization))
              (SBAR
                (WHADVP (WRB when))
                (S
                  (NP (PRP he))
                  (VP (VBD told)
                    (S
                      (NP (DT a) (NNP North) (NNP Atlantic) (NNP Treaty) (NNP Organization))
                      (ADJP (NN meeting)))
                    (SBAR (IN that)
                      (S
                        (NP (PRP he))
                        (VP (MD would)
                          (VP (VB allow)
                            (NP (DT some) (NNS exceptions)))))))))))))
      (PP (TO to)
        (NP
          (NP (DT the) (NNP Cocom) (NN embargo))
          (PP (IN of)
            (NP (JJ strategic) (NNS goods))))))
    (. .)))
```

**Comment by sebschu** [comment]
Oh, I see. The issue here is that you used the `-nonCollapsed` option in combination with the CoNLL-X output. The `-nonCollapsed` option adds additional relations and introduces cycles when you have a relative clause but the CoNLL-X format requires that every token has exactly one head and therefore only one of the two relations is being printed.

In your example, the token _liberalization_ ends up with two heads, namely _of-12_ and _told-17_, but only one of them is shown in the output.

You probably want to use the `-basic` option instead of the `-nonCollapsed` option which always returns a surface syntax tree in which every token has exactly one head. You can find more information on the different representations in the [Stanford Dependencies manual](http://nlp.stanford.edu/software/dependencies_manual.pdf).

**Comment by amir-zeldes** [comment]
OK, I see the acyclic property in the manual, that's clear now - thanks and sorry for the confusion!
