### ISSUE TITLE
Is there any method to speed up dependency parsing process?

### ISSUE THREAD

**Issue by JasmineChen123** [stanfordnlp/CoreNLP#1341]
I compiled the latest dev branch and tried to get the dependency parsing result.
However, this process seems to be very slow. Is there any configuration to speed it up ? 
##dependency parse
```bash
java -Xmx96g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,parse  \
           -tokenize.whitespace true  -tokenize.keepeol true  -tokenize.language English -ssplit.eolonly  true \
           -outputFormat text   -output.dependencyType basic < test >test.out
```

**Comment by AngledLuffa** [comment]
You could use the srparser or the direct to dependencies `depparse` annotator instead of `parse`

**Comment by JasmineChen123** [comment]
> You could use the srparser or the direct to dependencies `depparse` annotator instead of `parse`

Thank you!! It runs much faster!!

**Comment by JasmineChen123** [comment]
After using the option 'depparse' rather than 'parse', the parsing process speeds up a lot. But I also found that parsing German text was much slower than English. Is there any way to speed up the German text parsing process?
my command for dependency parse German text is below:
```bash
java -Xmx96g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,depparse  \
           -tokenize.whitespace true  -tokenize.keepeol true  -tokenize.language German -ssplit.eolonly  true \
           -outputFormat text   -output.dependencyType basic < test.de  >test.de.out
```
And the terminal log is below:
```bash
Adding annotator tokenize
Adding annotator pos
Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words-distsim.tagger ... done [0.8 sec].
Adding annotator depparse
Loading depparse model: edu/stanford/nlp/models/parser/nndep/english_UD.gz ... Time elapsed: 1.7 sec
PreComputed 20000 vectors, elapsed Time: 1.911 sec
Initializing dependency parser ... done [3.6 sec].
```
Is this normal?

**Comment by JasmineChen123** [comment]
If I use srparser, will it work? But I dont know where to download the srparser of German and its running command.

**Comment by AngledLuffa** [comment]
Problem with that approach is there is no German constituency -> dependency converter in CoreNLP.

The loading is a bit slower, but is the processing much slower for German?  Obviously you want to run a whole bunch of text through at once

There's also Stanza if you just want basic dependencies and don't need the other annotators, especially for non-English languages

**Comment by JasmineChen123** [comment]
> The loading is a bit slower, but is the processing much slower for German? Obviously you want to run a whole bunch of text through at once
yes，I processed millons of Germany sentences. And it is about 5 times slower than English.

if I run this command, will I get the correct German parsing result? Or the depparse is only designed for English?
```bash
java -Xmx96g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,depparse  \
           -tokenize.whitespace true  -tokenize.keepeol true  -tokenize.language German -ssplit.eolonly  true \
           -outputFormat text   -output.dependencyType basic < test.de  >test.de.out
```

**Comment by JasmineChen123** [comment]
> Problem with that approach is there is no German constituency -> dependency converter in CoreNLP.

Does it mean that we can get the correct German consituency result but can't get correct dependency parsing result?

**Comment by JasmineChen123** [comment]
> Problem with that approach is there is no German constituency -> dependency converter in CoreNLP.
> 
> The loading is a bit slower, but is the processing much slower for German? Obviously you want to run a whole bunch of text through at once
> 
> There's also Stanza if you just want basic dependencies and don't need the other annotators, especially for non-English languages

Thanks for your advice. I tried the tool of Stanza. And I got the right German parsing result.

**Comment by AngledLuffa** [comment]
> Does it mean that we can get the correct German constituency result but can't get correct dependency parsing result?

The reason the constituency parser in English for CoreNLP also produces dependencies is that there's a deterministic converter which turns the constituency trees into dependency graphs.  We only wrote that for English and Mandarin, so there's no such equivalent in German.

Someone could of course run a project where they write a German specific converter or a generalized converter, but that's not high on our TODO list
