### ISSUE TITLE
How to use StanfordCoreNLPServer to load scenegraph library

### ISSUE THREAD

**Issue by chaojiewang94** [stanfordnlp/CoreNLP#1346]
I wanna to construct a StanfordCoreNLPServer, which has preloaded scenegraph, how to achice this?

I have tried the command "
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer \
-preload scenegraph \
-status_port 9000 -port 9000 -timeout 15000 & 
"
but it seems to be failed

**Comment by AngledLuffa** [comment]
It's the same problem as on the stanza side.  The code to run scenegraph in a server simply doesn't exist.

I'm sure you've found this already, but there are instructions on how to run it here:

https://nlp.stanford.edu/software/scenegraph-parser.shtml

That's the only thing that exists currently.  We could theoretically include it in a server, but until you came along, there was never any request for that.  What are you looking for that the CLI and the API don't provide?

**Comment by chaojiewang94** [comment]
I wonder if you can include the following two APIs in NLPserver
``
import edu.stanford.nlp.scenegraph.RuleBasedParser;
import edu.stanford.nlp.scenegraph.SceneGraph;
''
so that I can preload them as the same as other APIs like ``tokenize,ssplit,pos,lemma,ner'' in https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK

then I use the transfer a sentence into scene graph in Python, just like this

``
from nltk.parse import CoreNLPParser

sentence = "A brown fox chases a white rabbit."

parser = CoreNLPParser(url='http://localhost:9000')
sg = parser.scenegraph_parse(sentence)

print(sg.toReadableString())
''


It will be helpful for us to cite your work in https://nlp.stanford.edu/software/scenegraph-parser.shtml
thanks

**Comment by AngledLuffa** [comment]
can do, but it will be at least a week until we make that available

**Comment by chaojiewang94** [comment]
thanks for your help, looking forward to your reply

**Comment by AngledLuffa** [comment]
Sorry for the long delay.  Spring quarter was quite busy (we did submit a couple drafts out of work we had done, so that was good).  I have time to pick this up again, and after looking over scenegraph, I think I can put something together.
There's a text output format and a json output format which would both be easy to make available in python.  There are a couple different ways of doing it:

- standalone java program with a corresponding python interface. easier to run, but can only be run locally
- add it to server itself.  a little more complicated, allows you to run the server in a separate process or on a separate machine

Which of these would be more useful, assuming you even still need this upgrade?

**Comment by chaojiewang94** [comment]
Thanks for your reply, I wonder if you can include the scene graph parser into [stanza](https://github.com/stanfordnlp/stanza)? so that I can directly use it after intalling stanza?

**Comment by AngledLuffa** [comment]
One way or another, it'll require having the Java implementation of SceneGraph, as there really isn't any impetus to update the project for python & deep learning in the group

**Comment by chaojiewang94** [comment]
> I wonder if you can include the following two APIs in NLPserver `` import edu.stanford.nlp.scenegraph.RuleBasedParser; import edu.stanford.nlp.scenegraph.SceneGraph; '' so that I can preload them as the same as other APIs like tokenize,ssplit,pos,lemma,ner in https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK
> 
> then I use the serve to transfer a sentence into scene graph in Python, just like this
> 
> `` from nltk.parse import CoreNLPParser
> 
> sentence = "A brown fox chases a white rabbit."
> 
> parser = CoreNLPParser(url='http://localhost:9000') sg = parser.scenegraph_parse(sentence)
> 
> print(sg.toReadableString()) ''
> 
> It will be helpful for us to cite your work in https://nlp.stanford.edu/software/scenegraph-parser.shtml thanks
> 
> @AngledLuffa

can u implement like this, maybe the second way?

**Comment by AngledLuffa** [comment]
You can see what I did in the two changes listed above.  If you have a CoreNLP server created, or if you create one using the Stanza API, you can then call `client.scenegraph(text)` and it will get a result.

It occurs to me that I don't actually know if the SceneGraph parser is threadsafe.  🤷

**Comment by AngledLuffa** [comment]
It might be a little time before the next official release, but I can make some sort of temporary package available if you'd use it in the short term

**Comment by chaojiewang94** [comment]
Thanks, I will have a try in the following week

**Comment by chaojiewang94** [comment]
> You can see what I did in the two changes listed above. If you have a CoreNLP server created, or if you create one using the Stanza API, you can then call `client.scenegraph(text)` and it will get a result.
> 
> It occurs to me that I don't actually know if the SceneGraph parser is threadsafe. 🤷

sorry, I still have trouble in building client with  Stanza API


# set up the client
with CoreNLPClient(annotators=['tokenize','ssplit','pos','lemma','ner','parse','depparse','coref'], timeout=60000, memory='16G') as client:
    # submit the request to the server
    client.scenegraph(text)

did I miss something?

**Comment by chaojiewang94** [comment]
from stanza.server import CoreNLPClient

# example text
print('---')
print('input text')
print('')

text = "Chris Manning is a nice person. Chris wrote a simple sentence. He also gives oranges to people."

print(text)

# set up the client
print('---')
print('starting up Java Stanford CoreNLP Server...')

# set up the client
with CoreNLPClient(timeout=60000, memory='16G') as client:
    # submit the request to the server
    client.scenegraph(text)

**Comment by chaojiewang94** [comment]
bug here:

---
input text
Chris Manning is a nice person. Chris wrote a simple sentence. He also gives oranges to people.
---
starting up Java Stanford CoreNLP Server...
2023-09-11 14:58:40 INFO: Writing properties to tmp file: corenlp_server-6f8436e1da2e4dc6.props
2023-09-11 14:58:40 INFO: Starting server with command: java -Xmx16G -cp /home/chaojiewang/stanza_corenlp/* edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 60000 -threads 5 -maxCharLength 100000 -quiet False -serverProperties corenlp_server-6f8436e1da2e4dc6.props -preload -outputFormat serialized
Traceback (most recent call last):
  File "/home/chaojiewang/anaconda3/envs/diffusion/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/chaojiewang/anaconda3/envs/diffusion/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/chaojiewang/anaconda3/envs/diffusion/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:

**Comment by chaojiewang94** [comment]
@AngledLuffa can u provide your demo code to use client.secengraph, thanks

**Comment by AngledLuffa** [comment]
what failure are you getting?

this works for me with the latest CoreNLP (4.5.5) and the latest stanza (1.5.1)

https://github.com/stanfordnlp/stanza/commit/b63fdfe97dda1a383fcf1c8d95f0101481a6a709

**Comment by AngledLuffa** [comment]
getting a connection error makes me wonder if there's a permissions problem binding that port

**Comment by chaojiewang94** [comment]
> getting a connection error makes me wonder if there's a permissions problem binding that port

but the demo for CoreNLP works for me 

from stanza.server import CoreNLPClient

# example text
print('---')
print('input text')
print('')

text = "Chris Manning is a nice person. Chris wrote a simple sentence. He also gives oranges to people."

print(text)


print('---')
print('starting up Java Stanford CoreNLP Server...')

with CoreNLPClient(annotators=['tokenize','ssplit','pos','lemma','ner','parse','depparse','coref'], timeout=60000, memory='16G') as client:
    # submit the request to the server
    ann = client.annotate(text)

**Comment by AngledLuffa** [comment]
I have found that it is behaving a bit different between having the server already started and starting the server inside a script.  Let me track that down

**Comment by chaojiewang94** [comment]
this works for me, but I donot know why

from stanza.server import CoreNLPClient

text = "Chris Manning is a nice person. Chris wrote a simple sentence. He also gives oranges to people."

with CoreNLPClient(annotators=['tokenize'], timeout=60000, memory='16G') as client:

    ann = client.annotate(text)

    result = client.scenegraph("Jennifer's antennae are on her head.")
    print(result)

**Comment by chaojiewang94** [comment]
seems there  are some procedures to intial the client in client.annotate()

**Comment by AngledLuffa** [comment]
ok, figured it out, there needs to be a

```
    client.ensure_alive()
```

It was supposed to be in the client itself, so that's on me.  I'll fix it on the dev branch.  For now you can just add this line, so the code to start & then run it looks like this

```
with CoreNLPClient(preload=False) as client:
    client.ensure_alive()
    result = client.scenegraph("Jennifer's antennae are on her head.")
    print(result)
```

**Comment by chaojiewang94** [comment]
@AngledLuffa  great! works for me now, thanks for your help!

**Comment by AngledLuffa** [comment]
👍 

i will add that to the client so you won't need to do it for future versions

**Comment by chaojiewang94** [comment]
got it!
