### ISSUE TITLE
IndexedWord index not 0-based

### ISSUE THREAD

**Issue by Tyler-Yates** [stanfordnlp/CoreNLP#135]
The `index()` method for `IndexedWord` is not 0-based (i.e. the first word in a sentence has index 1, not 0). While this is not really a bug, it makes it very error-prone to work with since accessing words from a `List` will require decrementing the index by one each time.

**Comment by AngledLuffa** [comment]
Will not fix.  Typically the IndexedWord is used as a component in the
SemanticGraph, where 0 represents a "root" state not part of the original
sentence.

**Comment by Tyler-Yates** [comment]
I see. Thank you for clarifying this. I figured there was some reason for this behavior but could not see it.
