### ISSUE TITLE
Online demos are not working

### ISSUE THREAD

**Issue by alishiba14** [stanfordnlp/CoreNLP#1350]
Online demos for example of SUTime (http://nlp.stanford.edu:8080/sutime/) are down. Could you please let me know if the online demos will be up soon?

**Comment by AngledLuffa** [comment]
Okay, it's back

**Comment by alishiba14** [comment]
Thank you :)

**Comment by winghigh** [comment]
来信已收到，谢谢！
                     王华

**Comment by alishiba14** [comment]
The demos stopped again. Is there a way to know when will they be up again?

**Comment by AngledLuffa** [comment]
I restarted it, but ultimately they should not be relied on for anything.
They're just there for fun.

**Comment by winghigh** [comment]
来信已收到，谢谢！
                     王华
