### ISSUE TITLE
无法提取中文的三元组，提取英文时是正常的。

### ISSUE THREAD

**Issue by salah0811** [stanfordnlp/CoreNLP#1357]
用来提取中文的三元组时结果一直是空的，提取英文的是可以的，用的java代码。并且已经引入了中文的依赖。请问该怎么提取中文的三元组
![image](https://github.com/stanfordnlp/CoreNLP/assets/102853999/09619586-494e-4304-8196-a963d914cc7a)

![image](https://github.com/stanfordnlp/CoreNLP/assets/102853999/20e9a1b4-0fb5-47c6-87cb-6c11ad1b9bb8)

**Comment by AngledLuffa** [comment]
Sorry for the late response.

Unfortunately, as you can see here, there is no OpenIE for ZH.

https://stanfordnlp.github.io/CoreNLP/human-languages.html

对不起很久没回答。剋下CoreNLP没有中文的OpenIE
