### ISSUE TITLE
Replicating conll2011 - coreference

### ISSUE THREAD

**Issue by annefried** [stanfordnlp/CoreNLP#136]
Hi all,
I am trying to replicate the Conll 2011 shared task results for the DEV set.
I am using the most recent version of the conll scorer (8.01).
The scores I get for MUC and CEAF approximately match the ones on the web site and in the paper, but the scores for BCUBED and BLANC are well below the numbers on the web site. (BCUBED = 52.1, BLANC=53.1). The official Conll shared task web site says that the implementation of these scores has been updated since, and you state on the Stanford CoreNLP web site that you used version 4.
Using the new scorer, are my replicated numbers correct?
Any help appreciated!
Many thanks -- Annemarie

**Comment by manning** [comment]
Hi Annemarie, it looks like you are running the replication correctly. I've just put scores for v8.01 up on [the webpage](http://nlp.stanford.edu/software/dcoref.shtml). Yes, as you can also see from the spreadsheet on [the CoNLL 2011 software page](http://conll.cemantix.org/2011/software.html), the numbers are markedly lower with the current scorer. *But* one minor point: I've never actually bothered understanding BLANC myself, however, the BLANC numbers people report are the ones that come from the second line of output that starts "BLANC", not the line starting "METRIC:blanc", and so our number on BLANC is now 50.1
