### ISSUE TITLE
Constituency Parse Tree output

### ISSUE THREAD

**Issue by mercurial-moon** [stanfordnlp/CoreNLP#1362]
I see that the output for constituency parse output in the text, xml or json files is given as a long string like so
```
Constituency parse: 
(ROOT
  (S
    (NP (NNP Stanford) (NNP University))
    (VP (VBZ is)
      (VP (VBN located)
        (PP (IN in)
          (NP (NNP California)))))
    (. .)))
```

This would be needed to be parsed to get it into a structured tree.
Is there a parser available for this by default in CoreNLP, or is there a more direct output (in tree format) available by querying the api ?

**Comment by AngledLuffa** [comment]
Please explain what you mean by "structured tree".  Do you want a list of
Tree objects in Java?  You can get that using the DiskTreebank class

https://nlp.stanford.edu/nlp/javadoc/javanlp-4.5.1/index.html?edu/stanford/nlp/trees/DiskTreebank.html

**Comment by mercurial-moon** [comment]
Hi,
Yes I was looking to getting the constituency parse data as a tree of java objects.
I found some api samples here [](https://stanfordnlp.github.io/CoreNLP/api.html)

`Tree constituencyParse = sentence.constituencyParse();`

Is this ok instead of the `DiskTreebank`

**Comment by AngledLuffa** [comment]
Yes, I had thought your trees were already in a file and you needed them
back, but there are several ways to access them as part of the API
