### ISSUE TITLE
CA certificate has expired 

### ISSUE THREAD

**Issue by ppagare** [stanfordnlp/CoreNLP#1365]
Hi, 

I have a docker container image that gets setup with CoreNLP 4.5.2 using the wget command as below - 
wget https://nlp.stanford.edu/software/stanford-corenlp-4.5.2.zip

Today, I got the certificate expired issue with the following line -
ERROR: cannot verify downloads.cs.stanford.edu's certificate issued by 'CN=InCommon RSA Server CA,.....'
Issued certificate expired

Although I could switch to insecure mode, it will impact all my packages that contain this dockerfile. 

Can this issue be resolved on the server end? Please treat this as urgent as our deployments are failing.

Thanks,
Paras

**Comment by AngledLuffa** [comment]
It works for me now.  Would you try again?

**Comment by ppagare** [comment]
Its working now. Thanks
