### ISSUE TITLE
Unable to download packages

### ISSUE THREAD

**Issue by anjultripathi** [stanfordnlp/CoreNLP#1367]
Hi Team, @AngledLuffa , @manning , @gangeli , @sebschu 

We are facing issue while downloading packages from wget.
![image](https://github.com/stanfordnlp/CoreNLP/assets/30743340/ecede474-0011-453d-9292-ec8217d3b93b)

Attaching image for reference.

Error:-
wget http://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip
--2023-06-25 07:28:57--  http://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... failed: Connection timed out.
Retrying.

--2023-06-25 07:31:08--  (try: 2)  http://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... failed: Connection timed out.
Retrying.

Please look into this on priority as our all deployment is getting failed.

Thanks in advance.

**Comment by AngledLuffa** [comment]
Unfortunately, our cluster is down for maintenance for the following two
weeks.  To add to the difficulty, I do not have a copy of 4.1.0 anywhere
with which to help you.  If you can send us an original copy of 4.1.0, I
will put it on HuggingFace, and hopefully you can use that URL instead.

Half the people you tagged have graduated, btw

**Comment by AngledLuffa** [comment]
If you are able to upgrade to 4.2.2 or later, this will be much easier to
fix

**Comment by anjultripathi** [comment]
hi @AngledLuffa ,
Thanks for quick response.

I am unable to download 4.5.2.zip as well.

I have both of these zip files with me, let me know how to share these zip packages with you?

upgrading to 4.2.2 will not be easy to us without testing.

**Comment by anjultripathi** [comment]
@AngledLuffa 

![image](https://github.com/stanfordnlp/CoreNLP/assets/30743340/736199b0-c1b2-40fd-a165-441ae3856cee)

For your ref

**Comment by AngledLuffa** [comment]
I wouldn't expect you to be able to download those versions from the
Stanford cluster, but there is already version 4.2.2 on HuggingFace:

https://huggingface.co/stanfordnlp/CoreNLP/resolve/v4.2.2/stanford-corenlp-latest.zip

The differences might not be so big that it gets in your way, although it
looks like the constituency parser models for English are updated:

https://stanfordnlp.github.io/CoreNLP/history.html

**Comment by anjultripathi** [comment]
@AngledLuffa , I can share original copy of version 4.1.0 , Could you please put it on hugging face?
to use 4.2, we need to modify many releases and their docker files.

**Comment by AngledLuffa** [comment]
Sure, I can do that later today (US) if you make it available for
download.  Sorry for the hassle, but all of our normal resources are
unavailable

**Comment by AngledLuffa** [comment]
If you find yourself in need of 4.1.0 again, I have a spare copy on my desktop now.  I'll make it available if this situation happens again and you haven't updated by then
