### ISSUE TITLE
corenlp.run is down

### ISSUE THREAD

**Issue by BryanHY** [stanfordnlp/CoreNLP#1368]
The website of live demo (https://corenlp.run) is down.
<img width="897" alt="image" src="https://github.com/stanfordnlp/CoreNLP/assets/53143180/18086f06-6a70-47c0-8ada-6895e7d717e4">

**Comment by AngledLuffa** [comment]
The cluster is down for maintenance, and the demo will not be available for
about 2 weeks

**Comment by BryanHY** [comment]
I see. Thank you for the prompt reply, John.
