### ISSUE TITLE
corenlp.run is down.

### ISSUE THREAD

**Issue by ayan-iiitd** [stanfordnlp/CoreNLP#1369]
Browser errors out with message
> Connection timed out Error code 522

**Comment by AngledLuffa** [comment]
The cluster is down for maintenance, and the demo will not be available for
about 2 weeks

**Comment by Dragoz99** [comment]
the service is still down

**Comment by dingusagar** [comment]
any update on this? this was a useful service. any other alternative websites which uses coreNLP?
currently I am using spacy https://demos.explosion.ai/displacy

**Comment by AngledLuffa** [comment]
It's meant to be a demo, not a service.  If you need lots of results, or if you want the results soon, please run the server locally.

**Comment by manning** [comment]
The corenlp.run server is now back up (and has been for about a week). Thanks for your patience.
