### ISSUE TITLE
Lemmatization in spanish

### ISSUE THREAD

**Issue by sebastiandev** [stanfordnlp/CoreNLP#137]
I'm trying to get the lemmas of each word from the provided text, but I couldn't find any docs about it. I'm wondering if there are any particular parameters like with the other annotators, since I'm defining the language for the tokenizer and spanish models for the pos,parse and ner. 

What I'm getting now looks like it didn't find anything and is returning the same word. 

> "caminando" => "caminando" (should be "camina")
> "arboles" => "arboles" (should be "arbol")
> "corriendo" => "corriendo" (should be "corre")

**Comment by manning** [comment]
Sorry, but we don't currently have a  Spanish lemmatizer.
http://stanfordnlp.github.io/CoreNLP/index.html#human-languages-supported

**Comment by pommedeterresautee** [comment]
@manning is there a way to override the english lemma dictrionary with a custom one? I can't find where I should override in the java code.

**Comment by manning** [comment]
Currently I think it is hardwired. It would be sensible to make that something that could be overwritten, but it's not just a dictionary. It's a compiled piece of code. (Essentially, a bit finite automaton.)
