### ISSUE TITLE
Tregex: infinite loop for `?<...`

### ISSUE THREAD

**Issue by tanloong** [stanfordnlp/CoreNLP#1375]
Specifying the MULTI_RELATION as optional seems to cause an infinite loop of printing matches. I am using Tregex 4.2.0 downloaded from [https://nlp.stanford.edu/software/tregex.shtml#Download](https://nlp.stanford.edu/software/tregex.shtml#Download) and here is the command I used:

```sh
echo "(A (B 1) (C 2))" | tregex.sh "A ?<... { B ; C }" -filter
```
![tregex_optional-multi-relation](https://github.com/stanfordnlp/CoreNLP/assets/71320000/584708de-d79a-4015-a3a3-ecb7038d7b8f)

P.S.

I noticed that the [testSubtreePattern](https://github.com/stanfordnlp/CoreNLP/blob/efc66a9cf49fecba219dfaa4025315ad966285cc/test/src/edu/stanford/nlp/trees/tregex/TregexTest.java#L1474) of TregexTest.java includes the `<...` and `!<...` but does not cover `?<...` . So I gave it a try and encountered this issue.

**Comment by AngledLuffa** [comment]
Thanks, love it.  A bug in an obscure syntax I added because I was tired of writing out the individual pieces by hand, using a variant of the feature probably no one will ever use.  I'll try to figure out what's going on.

Interesting to note btw is that when the pattern is turned back into a tregex, it does not use the `<...` syntax.  Basically, the `<...` gets expanded into the component pieces it represents.

I suspect the optional syntax in general is wrong somehow... there shouldn't be anything specific to the `<...`, considering your expression gets turned into a nested `CoordinationPattern` with two `<` and one `!<`

**Comment by AngledLuffa** [comment]
Haven't fully generalized this yet, but this also goes infinite:

```
echo "(A (B 1) (C 2))" | java edu.stanford.nlp.trees.tregex.TregexPattern "A ?(< B < C)" -filter
```

This does not:

```
echo "(zzz (A (B 1) (C 2)))" | java edu.stanford.nlp.trees.tregex.TregexPattern "A ?(< B)" -filter
```

So basically any optional `CoordinationPattern` is buggy?

**Comment by AngledLuffa** [comment]
... for reference, `CoordinationPattern` is how Tregex implements an `and` or an `or` internally

further bugginess in it is that the pattern

`A ?(< B < C)`

gets output without the optional:

`(A < B < C )`

this is probably easier to fix

**Comment by AngledLuffa** [comment]
well, this fixed the output of the `CoordinationPattern`, at least

https://github.com/stanfordnlp/CoreNLP/commit/a9965b2bbca615c8838cc2b24ca1403ec545c98c

**Comment by AngledLuffa** [comment]
Alright, figured out what's going on - basically, the `CoordinationPattern` in question wasn't checking if it had already returned once for an optional pattern, instead just always returned `true` for an optional.  The result was it would just always accept new empty matches every time it checked if the tree had another match...

under the hood, in case it wasn't clear from the previous comments, `<...` is just a macro for match the named nodes, then check that there isn't a subsequent node at the end of the list, and do all of that in a conjunction `CoordinationPattern`

**Comment by tanloong** [comment]
Yes. The `A ?<... { B ; C }` gets expanded to `A <1 B <2 C !<3 __`. 

Thanks for all the efforts and the patient explanation!
