### ISSUE TITLE
CoreNLPParser not working on Chinese text

### ISSUE THREAD

**Issue by ehsong** [stanfordnlp/CoreNLP#1378]
Hello, I've been trying since yesterday to use CoreNLPParser on Chinese text in Python 3 / Jupyter Notebook, but I realized that it is not working for Chinese text. Example

```
from nltk.parse.corenlp import CoreNLPServer, CoreNLPParser

parser = CoreNLPParser('http://localhost:9000')

sent = u'这是斯坦福中文分词器测试'

tokenized = list(parser.tokenize(sent))

print(tokenized)

['这是斯坦福中文分词器测试']

from nltk.parse.corenlp import CoreNLPServer, CoreNLPParser

parser = CoreNLPParser('http://localhost:9000')

sent = u'the quick brown fox jumped over the fence'

tokenized = list(parser.tokenize(sent))

print(tokenized)

['the', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'fence']
```

Is there something I didn't execute particularly for Chinese text? I do have the file 'stanford-corenlp-4.4.0-models-chinese.jar' within stanford-corenlp-4.5.1 folder, and I am ruing the script inside stanford-corenlp-4.5.1 folder.

**Comment by AngledLuffa** [comment]
Did you start the server with the Chinese properties, as described here?

https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK

I can also point out that we have a substantially more accurate parser
already in Python as part of Stanza, although it does need a GPU to be
competitively fast

https://stanfordnlp.github.io/stanza/
