### ISSUE TITLE
an info shows "INFO CoreNLP - CoreNLP Server is shutting down."

### ISSUE THREAD

**Issue by jacluxx** [stanfordnlp/CoreNLP#1380]
I was using python to run corenlp's openie for extracting triples, but it couldn't run for nearly 3 weeks.
when from pycorenlp import StanfordCoreNLP, it shows"INFO CoreNLP - CoreNLP Server is shutting down."

**Comment by AngledLuffa** [comment]
Are you running the server locally?

**Comment by jacluxx** [comment]
yes,I've downloaded the latest package stanford-corenlp-4.5.4

**Comment by AngledLuffa** [comment]
Great, sounds like you should be able to run `StanfordCoreNLPServer` on your own machine then

**Comment by jacluxx** [comment]
> 

Thank you for your response. I think I have identified where my problem lies, it's an issue with the local deployment. Thanks a lot！
