### ISSUE TITLE
for ner type - DATE, normalizedNER is not coming in appropriate format. 

### ISSUE THREAD

**Issue by ndoshi19** [stanfordnlp/CoreNLP#1382]
for ner type - DATE, normalizedNER is not coming in appropriate format. 
Data is coming in below format (without any dashes in normalized text)
                                        {
                                            "nerType": "DATE",
                                            "normalizedText": "20220701",
                                            "text": "July 1, 2022"
                                         }
                                         
whereas, it should appear like this
                                         {
                                            "nerType": "DATE",
                                            "normalizedText": "2022-07-01",
                                            "text": "July 1, 2022"
                                         }
                                         
Stanford version : stanford-corenlp-4.5.2
stanfordcorenlp==3.9.1.1 (python package version)

Please help on this as soon as possible, because we are facing lots of issue because of this.
Also let me know if any further details required from my side

**Comment by AngledLuffa** [comment]
We don't support this package:

stanfordcorenlp==3.9.1.1 (python package version)

You could use Stanza if you need NER annotations from CoreNLP in Python (or
just use it to produce NER annotations directly)
