### ISSUE TITLE
SUTime demo code needs updating

### ISSUE THREAD

**Issue by garfieldnate** [stanfordnlp/CoreNLP#139]
Not sure if this is the right place to report this, but the demo code for using SUTime on the [website](http://nlp.stanford.edu/software/sutime.html) does not compile (`Type mismatch: cannot convert from element type Object to CoreMap`, etc.), but the problems are quickly fixable using generics. Lines 31-33 should be as below:

      List<CoreMap> timexAnnsAll = annotation.get(TimeAnnotations.TimexAnnotations.class);
      for (CoreMap cm : timexAnnsAll) {
        List<CoreLabel> tokens = cm.get(CoreAnnotations.TokensAnnotation.class);

**Comment by manning** [comment]
Thanks, yes!  Really it was the bug of the generics not being escaped and so they disappeared in HTML rendering. Fixed.
