### ISSUE TITLE
corenlp.run seems to be down

### ISSUE THREAD

**Issue by SKefalidis** [stanfordnlp/CoreNLP#1390]
Hi,

I've been trying to access https://corenlp.run/, but it seems to be down.  Is it just me?

Thank you very much for your time and your amazing tool!

**Comment by frankenmatthias** [comment]
Having trouble with downloading using wget:
`wget http://nlp.stanford.edu/software/stanford-corenlp-latest.zip`
It seems to be down?

**Comment by AngledLuffa** [comment]
corenlp.run should be back up.

I can confirm that the download link is not working as expected.  I will
contact our sysdev team about that as well.  In the meantime, there should
be a huggingface link that works as backup, something like

https://huggingface.co/stanfordnlp/CoreNLP/resolve/main/stanford-corenlp-latest.zip

**Comment by AngledLuffa** [comment]
downloads should be back now as well
