### ISSUE TITLE
German Morphology

### ISSUE THREAD

**Issue by GeorgeS2019** [stanfordnlp/CoreNLP#1392]
Where I can find German morphology information. Has it been implemented? I most probably miss it.

Information like plurality, nominative/genitive, neutral/feminine,   etc

**Comment by AngledLuffa** [comment]
That is not supported in CoreNLP for German.  You can use Stanza, though,
which has that component as part of the POS tagger.

**Comment by GeorgeS2019** [comment]
I tried Stanza online, I fail to see any morphology information.

Without the morphology, it is challenging to program some levels of German Grammar matchers


![IMG_20231031_174513](https://github.com/stanfordnlp/CoreNLP/assets/49812372/e94c3d3a-c7f1-4bbc-8d3f-54f399e1d080)

**Comment by AngledLuffa** [comment]
It's not shown on the demo page, but it's definitely part of the API

**Comment by GeorgeS2019** [comment]
I found the morphology features..seem similar to those I found in Spacy.

Are morphology features come from independent sources than Spacy.

Curious of the source, especially for German

**Comment by AngledLuffa** [comment]
From what I read, spacy trained with the Tiger corpus.  We used the UD
dataset GSD.  I can't say much about the differences.

If accuracy is important to you, our latest release has a transformer based
version of the tagger.

**Comment by GeorgeS2019** [comment]
@AngledLuffa 

It seems [this support only](https://github.com/stanfordnlp/CoreNLP/blob/3499d27e615c35702f23948e886a7389b5695c33/src/edu/stanford/nlp/international/morph/AddMorphoAnnotations.java#L26) the Arabic language. 

Will it make sense to support German too?

**Comment by AngledLuffa** [comment]
There is roughly 0% chance of that happening from someone here.  It would require someone who knows German, who knows Java, who isn't satisfied with the python Stanza toolkit.  If someone outside Stanford produced such a project and sent us a PR, we would be happy to integrate it.

**Comment by GeorgeS2019** [comment]
##### isMorphTreeFile
ArabicTreeReaderFactory
> Morph file is gold tree file with morph analyses in the pre-terminals.

@AngledLuffa 

- Could you please suggest where I could read more how to create this Morph File
- Do I need GermanTreeReaderFactory? Is it already included in CoreNLP?

**Comment by AngledLuffa** [comment]
I think (although I can't swear to it, having not done anything with the Arabic normalization) that this is pursuing the wrong angle.  The Arabic datasets have morphology added as extra pieces to the words in question.  The German datasets such as the UD dataset you linked have it as an entirely separate column in the training data.  The preprocessing code wouldn't be a one-to-one language swap, but rather something entirely different.

It really is a project that literally no one at Stanford is going to take on or even provide help in any but the most cursory manner.  If it's this important that it be in Java, such that repeated suggestions of "just use Stanza" aren't sufficient, you can try contacting @manning to see if there's an arrangement that can be made to sponsor one of the group's (very few) Java programmers to figure out how to make the morphological analyzer you need in Java.

Stanza is available here:

https://github.com/stanfordnlp/stanza

the morphological analyzer is part of the POS tagger, which is documented here (look for `feats`):

https://stanfordnlp.github.io/stanza/pos.html

the version that uses the transformer is the `default_accurate` package, so, something like

```
pipe = stanza.Pipeline("de", package="default_accurate")
```
