### ISSUE TITLE
cryptic NullPointerException with SUTime

### ISSUE THREAD

**Issue by garfieldnate** [stanfordnlp/CoreNLP#140]
I'm using the demo code from the website (edited as in #139). When you comment out the line adding `WordsToSentencesAnnotator` and `POSTaggerAnnotator`, time annotation works fine. But then when you comment out the line setting the current date, it fails with the following trace:

	No document date specified
	Exception in thread "main" java.lang.NullPointerException
		at edu.stanford.nlp.time.TimeAnnotator.annotateSingleSentence(TimeAnnotator.java:241)
		at edu.stanford.nlp.time.TimeAnnotator.annotate(TimeAnnotator.java:230)
		at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:71)
		at SUTimeDemo.main(SUTimeDemo.java:32)

Only commenting out the line adding `POSTaggerAnnotator` does not cause the crash. The string I am testing with is "Tuesday".

The crash may be caused for some good (unknown) reason, but the error message is misleading, since it makes the user think that SUTime cannot function without the date being set.

**Comment by garfieldnate** [comment]
Silly me, the "No document date specified" string is not the error, though it is printed to STDERR.

I think I will edit the issue... it would be nice if SUTime said something like "XYZ annotation is required to perform time expression annotation", instead of just dying with a `NullPointerException`.

**Comment by manning** [comment]
This was a dumb bug in the code, and I'm fixing it. But you should know that the usual, full-functionality case is for SUTime to run on an input that does have part-of-speech tags and which is already split into sentences. Omitting that information was putting you on an under-used code path.
