### ISSUE TITLE
IntervalTree#remove null pointer exception

### ISSUE THREAD

**Issue by Sirius902** [stanfordnlp/CoreNLP#1405]
The following program causes a null pointer exception to be thrown. I would expect it to complete successfully and output `false`.

```java
import edu.stanford.nlp.util.Interval;
import edu.stanford.nlp.util.IntervalTree;

public class Main {
    public static void main(String[] args) {
        var tree = new IntervalTree<Integer, Interval<Integer>>();
        tree.add(Interval.toInterval(0, 1));
        tree.add(Interval.toInterval(2, 5));

        tree.remove(Interval.toInterval(2, 5));

        System.out.println(tree.overlaps(Interval.toInterval(2, 3)));
    }
}


```

```
Exception in thread "main" java.lang.NullPointerException: Cannot read field "value" because "anotherInteger" is null
	at java.base/java.lang.Integer.compareTo(Integer.java:1466)
	at java.base/java.lang.Integer.compareTo(Integer.java:72)
	at edu.stanford.nlp.util.Interval.max(Interval.java:424)
	at edu.stanford.nlp.util.IntervalTree.remove(IntervalTree.java:284)
	at edu.stanford.nlp.util.IntervalTree.remove(IntervalTree.java:214)
	at test.Main.main(Main.java:13)
```

**Comment by AngledLuffa** [comment]
Gah, this class is terrible.  Zero documentation and apparently even the most basic functionality isn't tested.  Thanks *so much* for uncovering it

**Comment by AngledLuffa** [comment]
Testing on other trees of size two, it also crashes if you insert things in such an order that the left child of the balanced tree is being deleted or if the root of the balanced tree is deleted.  You would think such a thing would be found before the other 500 lines of code got written.

What's debugging got to do with it, anyway?  
What's debugging but a sweet old fashioned notion?  
Who needs a unit test when a test can be broken?

**Comment by Sirius902** [comment]
@AngledLuffa Thanks for the quick reply! I found the issue using a larger set of test data but cf11603a33c965c8e1c6118521ffd106e813c269 seems to have addressed the issue there as well.

**Comment by AngledLuffa** [comment]
Now released in 4,.5.6
