### ISSUE TITLE
i am getting a lock screen bug 

### ISSUE THREAD

**Issue by 162September1996** [stanfordnlp/CoreNLP#1406]
import java.io.*;
import java.nio.channels.*;

public class foo {
  public static void main(String[] args) throws IOException {
    RandomAccessFile fout = new RandomAccessFile( "foo", "rw" );
    FileChannel channel = fout.getChannel();

    // this doesn't work
    FileLock lock = channel.lock(1, 10, true);

    // this works
    //FileLock lock = channel.lock();

    // Write the new value to the file
    byte[] bytes = "Hello World\n".getBytes();
    fout.write( bytes );
    fout.close();
  }
}
![Screenshot 2024-01-14 133604](https://github.com/stanfordnlp/CoreNLP/assets/155871058/92f380ae-ca05-4e64-bcf6-9e7afa376278)

**Comment by AngledLuffa** [comment]
Respectfully, is this in any way related to CoreNLP?

**Comment by 162September1996** [comment]
No

**Comment by 162September1996** [comment]
This is related to katalon studio,
