### ISSUE TITLE
Leap Year issue in calculating relative weeks

### ISSUE THREAD

**Issue by jeradf** [stanfordnlp/CoreNLP#141]
The expression "next week" with today ("2016-02-10") as a reference date, SUtime returns a date range for last year, and not even the correct week. 

I get 
```
<TIMEX3 range="(2015-02-09,2015-02-15,P1W)" tid="t2" type="DATE" value="2016-W07">next week</TIMEX3>
```
when using either the sutime online demo or the latest corenlp. 

Perhaps this issue is due to the fact that there is an extra week in February this year?

**Comment by jhauswald** [comment]
For those curious, It looks like this was fixed by @angelxuanchang in 1d5f7a9dac8cca457e86703ac44be065f9b1cee4. Thanks for the fix!
