### ISSUE TITLE
negation modifier

### ISSUE THREAD

**Issue by Shasetty** [stanfordnlp/CoreNLP#1410]
Hi sir,

Can i get the complete list of words, which are considered in negation modifier.

**List**
advmod : never , n’t , not
det :	no		

Thanks in advance.

Regards
Shankar

**Comment by AngledLuffa** [comment]
In what context, dependencies?

The NOT pattern is:

EnglishPatterns.java line 104

  // match "not", "n't", "nt" (for informal writing), or "never" as
_complete_ string

  public static final String NOT_PAT_WORD = "^(?i:n[o'’]?t|never)$";

**Comment by Shasetty** [comment]
Under basic dependencies of  Stanford typed dependencies, 
I need all the list  of words,  which are considered as negation modifiers.

**example text** 
Bill is not a scientist.  neg(scientist-5, not-3)

Bill is no scientist.      neg(scientist-4, no-3)

Bill does n't drive.      neg(drive-4, n't-3)

thanks in advance.

**Comment by AngledLuffa** [comment]
What I just sent is the regex used by the dependencies

https://github.com/stanfordnlp/CoreNLP/blob/f8838d2639589f684cbaa58964cb29db5f23df7f/src/edu/stanford/nlp/trees/EnglishPatterns.java#L104

**Comment by Shasetty** [comment]
Thank You Sir.
