### ISSUE TITLE
english.all.3class.distsim.crf.ser.gz  ????

### ISSUE THREAD

**Issue by NeilWP** [stanfordnlp/CoreNLP#1413]
### Discussed in https://github.com/stanfordnlp/CoreNLP/discussions/1412

<div type='discussions-op-text'>

<sup>Originally posted by **NeilWP** January 30, 2024</sup>
The docs and advice I have for  Entity search in a C# class  suggest I install  Stanford.NLP.Core.NLP  and then execute against the 
`
var jarRoot = @"J:\STANDFORD.NLP\stanford-corenlp-4.5.5";
var classifiersDirec = jarRoot + @"\classifiers";
var classifier = CRFClassifier.getClassifierNoExceptions(classifiersDirec + @"\english.all.3class.distsim.crf.ser.gz");
return classifier.classifyToString(text);
`
However in the download neither the .gz file nor the folder  classifiers exist . Help text here is  not very clear
Assistance gratefully received, I cannot be the only person trying to execute an entity look up   in a C# console app.
</div>

**Comment by AngledLuffa** [comment]
I really don't know anything about C# or using CoreNLP from C#.  The model in question exists in the jar files downloaded with CoreNLP.  One thing I can note is that you wrote `STANDFORD` whereas it's spelled `STANFORD`... not sure there's any correlation between that and it not finding the right path
