### ISSUE TITLE
Training Shift Reduce Parser

### ISSUE THREAD

**Issue by alvaro-rio** [stanfordnlp/CoreNLP#1428]
Hello, I'm trying to train a shift-reduce parser using this technology but I need some help since I'm having trouble doing it. I'm trying to execute the command:

java -mx10g edu.stanford.nlp.parser.shiftreduce.ShiftReduceParser -trainTreebank <trainpath> -devTreebank <devpath> -serializedPath model.ser.gz

but I have several doubts. First, where does edu.stanford.nlp.parser.shiftreduce.ShiftReduceParser come from? 
And second, where can I get a treebank to train the model?

If someone could help me, it would be greatly appreciated.

**Comment by AngledLuffa** [comment]
> First, where does edu.stanford.nlp.parser.shiftreduce.ShiftReduceParser come from?

It's all included in the CoreNLP distribution, so you can get that however works best for you: download from [github.io/CoreNLP](https://stanfordnlp.github.io/CoreNLP/), maven, whatever

> And second, where can I get a treebank to train the model?

It's definitely more of a B-Y-O-Trees.  Is there a particular language you're looking for?

Also, in general you'll almost definitely have better results with Stanza's constituency parser, which uses pretrained word vectors and/or HF transformers and is much more accurate.

https://stanfordnlp.github.io/stanza/new_language_constituency.html
