### ISSUE TITLE
Publish model artifacts under own artifactId instead of using classifier

### ISSUE THREAD

**Issue by reckart** [stanfordnlp/CoreNLP#143]
Having multiple dependencies with the same groupId/artifactId but different classifiers appears to be a problem for some build systems, e.g. Sbt does not resolve dependencies with classifiers, e.g. Ivy-based ones (e.g. https://github.com/sbt/sbt/issues/285, but also hitting that problem with the Ivy used by Groovy Grapes now.)

It would be great if the model JARs for CoreNLP could be published under separate artifactIDs instead of using the classifier coordinate. That would also facilitate giving them their own version cycles, as many models do not change between CoreNLP releases.

**Comment by dinoboy197** [comment]
I was able to include multiple CoreNLP dependencies with the same groupId / artifactId with different classifiers in SBT.

Example:
```
   "edu.stanford.nlp" % "stanford-corenlp" % "[3.4.1,3.5.0)",
   "edu.stanford.nlp" % "stanford-corenlp" % "[3.4.1,3.5.0)" classifier "models",
   "edu.stanford.nlp" % "stanford-corenlp" % "[3.4.1,3.5.0)" classifier "srparser-models",
```

However, I agree that it would be more straightforward if they had different artifact ids.
