### ISSUE TITLE
Is https://corenlp.run down?

### ISSUE THREAD

**Issue by evan-qianjh** [stanfordnlp/CoreNLP#1446]
**A timeout occurred Error code 524**
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_524&utm_campaign=corenlp.run) for more information.
2024-05-15 16:19:40 UTC
Cloudflare Ray ID: 884470ffcc3976b0

**Comment by AngledLuffa** [comment]
i don't know why it keeps crashing.  our logging doesn't explain the situation.  i'll add more logging the next time i have to restart it.  still trying to work out issues caused by a file server melting down
