### ISSUE TITLE
Unable to install CoreNLP software

### ISSUE THREAD

**Issue by Lucia062026** [stanfordnlp/CoreNLP#1450]
Hi everyone,
I am absolutely new to python, javars, and CoreNLP but my project now needs to measure investor sentiment by CoreNLP software. The problem is I downloaded this software from Github website to my laptop but I did not know how to install it. I unzipped the file and in includes so many things that I do not know. I also followed instructions to download Ant and Maven, but I did not know how to install these too. Please guide me to install CoreNLP. I really appreciate.
Thank you
Lucia

**Comment by AngledLuffa** [comment]
There's a sentiment model for English in Stanza as well.  Your accuracy
will be higher if you just use that.

**Comment by Lucia062026** [comment]
Hi John,
Thank you very much for your reply. But do I need to install any software
to run it? I do not know how to use Stanza. In the page to download, it
shows me some codes, where to put the codes?
*Thuy Duong (Lucia)*
*Email: ***@***.*** ***@***.***>*
*Phone: +61(0)413213685*

**Comment by AngledLuffa** [comment]
- install python
- install pytorch
- pip install stanza

follow the tutorials on how to get started with labeling text with stanza

**Comment by Lucia062026** [comment]
Thank you very much. I will follow it

Vào 08:37, T.7, 8 Th6, 2024 John Bauer ***@***.***> đã viết:

**Comment by Lucia062026** [comment]
Hi John,
I installed all the packages. The problem is I dont know how to build the
sentiment index there. Could you please spend time on giving me an online
tutorial for that, I am happy to pay the learning fee. Because I am
preparing the confirmation of my PHD candidature, I need to have this data
as soon as possible. Please help me.
Thank you very much.
*Thuy Duong (Lucia)*
*Email: ***@***.*** ***@***.***>*
*Phone: +61(0)413213685*

**Comment by AngledLuffa** [comment]
There's a simple code sample here:

https://stanfordnlp.github.io/stanza/sentiment.html#simple-code-example

**Comment by Lucia062026** [comment]
Thanks, I'll check it out.

Vào 10:23, T.3, 11 Th6, 2024 John Bauer ***@***.***> đã viết:
