### ISSUE TITLE
edu.stanford.nlp.pipeline.StanfordCoreNLP

### ISSUE THREAD

**Issue by gguangy** [stanfordnlp/CoreNLP#1452]
Hi everyone!

I'm encountering issues while trying to run the following commands:

(1）
 java -cp "*" -mx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat json -file input.txt
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP

（2） 
 java -mx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat json -file input.txt
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP

Could someone please assist me with resolving this issue?

Thank you!

**Comment by AngledLuffa** [comment]
https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean
