### ISSUE TITLE
downloadCoreNLP() timeout

### ISSUE THREAD

**Issue by DeepankarVyas** [stanfordnlp/CoreNLP#1456]
I am trying to run downloadCoreNLP() in R, but getting the error below:-

![image](https://github.com/user-attachments/assets/6994678c-2218-438d-869b-c899feb8642c)

Any help is greatly appreciated.

Thanks

**Comment by AngledLuffa** [comment]
I don't know how the timeout is being set, but it's a large file.  Perhaps
you need to increase the time allowed for downloading?

**Comment by DeepankarVyas** [comment]
Hi @AngledLuffa ,

Thank you for the response. But I checked and can't seem to find how to increase the timeout.

Regards
