### ISSUE TITLE
SUTime.RelativeTime API does not give access to base, tempOp or tempArg

### ISSUE THREAD

**Issue by garfieldnate** [stanfordnlp/CoreNLP#146]
I am unable to find any programmatic way to access the individual parts of an SUTime.RelativeTime object. Currently I am parsing the contents of `getTimexAttributes().get("alt_value")` to get this information.

**Comment by manning** [comment]
This class seems to have a few cautions and todo's in the code, and I'm not going to try to sort it all out now. But there seems no reason not to add some field accessors, so I will do that.

**Comment by garfieldnate** [comment]
Thanks! This will make it much easier to use.

**Comment by garfieldnate** [comment]
Sorry to come back to this, but I think that "base" needs to be accessible in the other nested classes as well. Right now I'm trying to get the results of a rule that matches "Saturday the 24th", etc.; when I print the temporal I get "XXXX-XX-24-WXX-6", but when I get the timex attributes it only provides `{tid=t1, value=XXXX-WXX-6, type=DATE}`, so I lose the 24th part. This particular one is an SUTime.PartialTime, with `[dayOfMonth=24, dayOfWeek=6]` stored in the base variable.
