### ISSUE TITLE
自定义词典

### ISSUE THREAD

**Issue by dashu101** [stanfordnlp/CoreNLP#1462]
What is the txt file format for custom dictionaries?

**Comment by AngledLuffa** [comment]
one word per line


https://github.com/stanfordnlp/CoreNLP/blob/375f24338c09b22d1596440864bc074f32c0feb9/src/edu/stanford/nlp/wordseg/ChineseDictionary.java#L158

**Comment by dashu101** [comment]
Thanks I have solved it. Looking at the source code, I found that the custom words cannot exceed 6 words.



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: John Bauer ***@***.***&gt;
发送时间: 2024年8月27日 23:01
收件人: stanfordnlp/CoreNLP ***@***.***&gt;
抄送: dashu101 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [stanfordnlp/CoreNLP] 自定义词典 (Issue #1462)





 one word per line
 
 
 https://github.com/stanfordnlp/CoreNLP/blob/375f24338c09b22d1596440864bc074f32c0feb9/src/edu/stanford/nlp/wordseg/ChineseDictionary.java#L158
