### ISSUE TITLE
Percent decoding %2B results in blank, not +

### ISSUE THREAD

**Issue by BartJongejan** [stanfordnlp/CoreNLP#1470]
It seems there is a problem with percent decoding %2B, which ends being interpreted as a blank, not a +, which it should. I think percent decoding somehow happens twice.

The error appeared when trying to use the web API on localhost for an Arabic text. The segment.model in StanfordCoreNLP-arabic.properties has a value containing +'es:

    segment.model = edu/stanford/nlp/models/segmenter/arabic/arabic-segmenter-atb+bn+arztrain.ser.gz 

There is a work-around (a hack, in other words) that works for us: 
When percent encoding the properties attribute (which is a string of JSON data), + must be encoded as %252B, that is, percent encode both the percent symbol and the + symbol.

Settings;
java -version returns

    openjdk version "21.0.5" 2024-10-15 
    OpenJDK Runtime Environment (build 21.0.5+11-Ubuntu-1ubuntu124.04)
    OpenJDK 64-Bit Server VM (build 21.0.5+11-Ubuntu-1ubuntu124.04, mixed mode, sharing)

The version of CoreNLP is 4.5.7

**Comment by AngledLuffa** [comment]
That's not ideal, but hopefully fixable.  Would you let me know what you're
doing to trigger this error?

**Comment by BartJongejan** [comment]
Downloaded https://nlp.stanford.edu/software/stanford-corenlp-4.5.7-models-arabic.jar
Copied to /opt/stanford-corenlp-4.5.7/
Extracted StanfordCoreNLP-arabic.properties using

    unzip -p /opt/stanford-corenlp-4.5.7/stanford-corenlp-4.5.7-models-arabic.jar StanfordCoreNLP-arabic.properties

Contents of StanfordCoreNLP-arabic.properties (notice the four + symbols):

    # Pipeline options
    annotators = tokenize, ssplit, pos, parse
    
    # segment
    #customAnnotatorClass.segment = edu.stanford.nlp.pipeline.ArabicSegmenterAnnotator
    tokenize.language = ar
    segment.model = edu/stanford/nlp/models/segmenter/arabic/arabic-segmenter-atb+bn+arztrain.ser.gz
    
    # sentence split
    ssplit.boundaryTokenRegex = [.]|[!?]+|[!\u061F]+
    
    # pos
    pos.model = edu/stanford/nlp/models/pos-tagger/arabic.tagger
    
    # parse
    parse.model = edu/stanford/nlp/models/lexparser/arabicFactored.ser.gz
    
Prepared the 'properties' parameter (JSON) for a call to http://localhost:9000/, using info found in StanfordCoreNLP-arabic.properties

    {"annotators":"tokenize,ssplit","outputFormat":"json","segment.model":"edu/stanford/nlp/models/segmenter/arabic/arabic-segmenter-atb+bn+arztrain.ser.gz","ssplit.boundaryTokenRegex":"[.]|[!?]+|[!\\u061F]+","timeout":"500000","tokenize.language":"ar"}

Creating the wget call, percent encoding + as %2B in the JSON string:

    wget --post-file testinput.txt 'http://localhost:9000/?properties=%7B%22annotators%22%3A%22tokenize%2Cssplit%22%2C%22outputFormat%22%3A%22json%22%2C%22segment.model%22%3A%22edu%2Fstanford%2Fnlp%2Fmodels%2Fsegmenter%2Farabic%2Farabic-segmenter-atb%2Bbn%2Barztrain.ser.gz%22%2C%22ssplit.boundaryTokenRegex%22%3A%22%5B.%5D%7C%5B%21%3F%5D%2B%7C%5B%21%5C%5Cu%30%36%31F%5D%2B%22%2C%22timeout%22%3A%22%35%30%30%30%30%30%22%2C%22tokenize.language%22%3A%22ar%22%7D' -O /tmp/corenlp-tmp28puKVo --

Look in the stderr output (Notice that the file name arabic-segmenter-atb+bn+arztrain.ser.gz now contains spaces where there should have been +'es):

    [pool-1-thread-10] WARN CoreNLP - edu.stanford.nlp.io.RuntimeIOException: Failed to load segmenter edu/stanford/nlp/models/segmenter/arabic/arabic-segmenter-atb bn arztrain.ser.gz

Create a new wget call, this time percent encoding + as %252B in the JSON string:

    wget --post-file testinput.txt 'http://localhost:9000/?properties=%7B%22annotators%22%3A%22tokenize%2Cssplit%22%2C%22outputFormat%22%3A%22json%22%2C%22segment.model%22%3A%22edu%2Fstanford%2Fnlp%2Fmodels%2Fsegmenter%2Farabic%2Farabic-segmenter-atb%252Bbn%252Barztrain.ser.gz%22%2C%22ssplit.boundaryTokenRegex%22%3A%22%5B.%5D%7C%5B%21%3F%5D%252B%7C%5B%21%5C%5Cu%30%36%31F%5D%252B%22%2C%22timeout%22%3A%22%35%30%30%30%30%30%22%2C%22tokenize.language%22%3A%22ar%22%7D' -O /tmp/corenlp-tmp28puKVo --

This works.

**Comment by BartJongejan** [comment]
True, but only one round is percent decoding. The second round is backslash unescaping, in the case of JSON data and many other data formats. So

    "\""

should simply be percent encoded as

    %22%5C%22%22

**Comment by AngledLuffa** [comment]
In principle I agree with you, this mechanism for double escaping / unescaping is weird and possibly even incorrect.  However, it's already what exists, and we have no way of knowing if anyone else out there already relies on it and just didn't post an issue about it.  If we could start over, we'd specifically escape and unescape the parameters map differently, but I hesitate to potentially break anyone else's workflow.

One thing to point out which may help in your particular case, though, is that everything aside from `properties` or `props` is treated as a separate property on its own, and those are only decoded one time.  For example, if you include `segment.model` directly in your query instead of putting it in a separate properties map, you should only have to escape it once ... at least, I believe that to be true, feel free to double check that

**Comment by AngledLuffa** [comment]
> A good place would be https://stanfordnlp.github.io/CoreNLP/corenlp-server.html#quirks-and-subtleties

Yes, that makes sense.  I have added a section there.  Feel free to suggest edits

> I tried to query localhost:9000 with separated-out parameters, but found that the only way is to put everything in a properties map

I did this, and it worked as I expected to tokenize in Chinese:

```
wget --post-file foo.txt "http://localhost:8880?annotators=tokenize&tokenize.language=zh&segment.model=edu/stanford/nlp/models/segmenter/chinese/ctb.gz&segment.serDictionary=edu/stanford/nlp/models/segmenter/chinese/dict-chris6.ser.gz&segment.sighanCorporaDict=edu/stanford/nlp/models/segmenter/chinese"
```

**Comment by BartJongejan** [comment]
Thank you for adding that section. The problem is indeed with passing JSON data. If I use a command that is a chinese->arabic modification of the JSON-less wget command:

    wget --post-file foo.txt "http://localhost:9000?annotators=tokenize,ssplit&tokenize.language=ar&segment.model=edu/stanford/nlp/models/segmenter/arabic/arabic-segmenter-atb+bn+arztrain.ser.gz&ssplit.boundaryTokenRegex=[.]|[!?]+|[!\\u061F]+"

I get this error:

    [pool-1-thread-1] WARN CoreNLP - edu.stanford.nlp.io.RuntimeIOException: Failed to load segmenter edu/stanford/nlp/models/segmenter/arabic/arabic-segmenter-atb bn arztrain.ser.gz

You see that each + ends as a blank in the error message. But this time, the problem is solved by replacing each + by its percent encoded equivalent:

    wget --post-file foo.txt "http://localhost:9000?annotators=tokenize,ssplit&tokenize.language=ar&segment.model=edu/stanford/nlp/models/segmenter/arabic/arabic-segmenter-atb%2Bbn%2Barztrain.ser.gz&ssplit.boundaryTokenRegex=[.]|[!?]%2B|[!\\u061F]%2B"

No need for a double escape here.

**Comment by AngledLuffa** [comment]
Thank you for the additional clarification.  I will add that to the webpage, using your example command line if you don't mind

**Comment by BartJongejan** [comment]
That is absolutely fine!

Den ons. 27. nov. 2024 kl. 23.54 skrev John Bauer ***@***.***
