### ISSUE TITLE
Model jar encoding error

### ISSUE THREAD

**Issue by yc21icacuk** [stanfordnlp/CoreNLP#1471]
When I am using the CoreNLP model, it always works well. However, when I move the Chinese model into the category and load the model, only word_tokenize function works and the others return the following error: ChunkedEncodingError(Connection broken: IncompleteRead(0 bytes read, 124 more expected)) urllib3.exceptions.IncompleteRead(0 bytes read, 124 more expected).
I am running the code on SUSE Linux 15 sp3 server with java version 1.8.0_431. The code is simple:
```python
from stanfordcorenlp import StanfordCoreNLP
nlp = StanfordCoreNLP(r'/users/python/stanford-corenlp-4.5.7',lang='zh') 
text = "斯坦福大学位于加州，是一所综合型大学。"
print(nlp.word_tokenize(text))
print(nlp.pos_tag(text))
print(nlp.ner(text))
``` 

I have tried different conda environment with java 17 and other versions of Chinese model but still got the error.

**Comment by AngledLuffa** [comment]
We are not responsible for the `stanfordcorenlp` module.

**Comment by AngledLuffa** [comment]
If you want a working python client maintained by Stanford NLP, I suggest using [Stanza](https://github.com/stanfordnlp/stanza) instead
