### ISSUE TITLE
edu.stanford.nlp.naturalli.Util.cleanTree(...) function cuts off large chunk of sentence due to self-edge issue

### ISSUE THREAD

**Issue by todpole3** [stanfordnlp/CoreNLP#148]
I encounter this abnormal behavior when trying to perform OpenIE relation extraction on the following sentence:

> Julian served on the Carson City Council and in the California State Assembly before running for Congress in December 1995 in a special election to replace Walter Tucker III (D).

After the Util.cleanTree() method is applied onto the collapsed parse tree, only the following proportion of the sentence is retained:

> Julian served on the Carson City Council and

I realized that this error comes from the fact that the collapsed parse tree introduced a self-edge
> served -[conj:and]-> served'

After this edge is deleted, the copy node "served'" and the rest of the dependency structure attached to it got deleted. 

I printed out the sequence of nodes and edges deleted and found out that:
Since "served" is the root of the sentence, once the self-edge is removed, the copy node "served'" becomes a dangling node. Once "served'" is deleted, its dependencies become dangling node, so on and so forth, which causes a large chunk of words got deleted. 

I'm not sure if this is a known bug and you have decided to sacrifice some of these (I didn't check how often this happens) cases to get clean trees. A hacky solution is given below: when the self-edge deletion happens, add the copy node to the set of roots as well, but I'm not sure if that damages other things..

```
    // Clean edges
    Iterator<SemanticGraphEdge> iter = tree.edgeIterable().iterator();
    while (iter.hasNext()) {
      SemanticGraphEdge edge = iter.next();
      if (edge.getDependent().index() == edge.getGovernor().index()) {
    	if (tree.getRoots().contains(edge.getGovernor())) {
    		tree.addRoot(edge.getDependent());
    	}
        // Clean self-edges
        iter.remove();
```

**Comment by manning** [comment]
This looks buggy to me -- the copy nodes do add some additional trickiness, and it sure likes this code doesn't handle them correctly....

**Comment by gangeli** [comment]
<rant>This function is responsible for probably >25% of my debugging time in the OpenIE system. So many weird things happen in SemanticGraphs, and if I pass a non-tree graph into OpenIE it runs the risk of hanging. At one point I recall reporting the existence of copy nodes as a bug in CoreNLP, before being told "no, this is a feature not a bug."</rant>

In any event, I think I've fixed it; the commit should propagate to GitHub soon.

**Comment by manning** [comment]
I guess we should talk about this sometime! I agree that they add complexity and often confuse people, but there are a lot of linguistic issues that people are trying to model, and we don't know a better solution....  The better representation of conjunction that results should actually give better OpenIE output than not having copy nodes.
