### ISSUE TITLE
Issue when tokenizing tweets

### ISSUE THREAD

**Issue by jplu** [stanfordnlp/CoreNLP#150]
Hello,

I'm currently using the tokenizer provided by Stanford CoreNLP to tokenize tweets. And there is a strange behavior with hashtags that mix numbers and letters. For example:

```
#Trump #Trump2016 Muhammad Ali Criticises Donald Trump's Call to Ban Muslims From Entering  @FollowNewsNow
```

If you use the online version you can see that the hashtag ```#Trump2016``` is divided in two tokens ```#Trump``` and ```2016```.

Is it a bug or a wanted behavior for the tokenizer?

Thanks.

**Comment by manning** [comment]
This is a deficiency. While the tokenizer tries to do its best over a broader range of text types, this just seems a bad limitation.  I've adding some more generous matching of tweet mentions and hashtags -- though the patterns matched are deliberately still somewhat more restrictive than Twitter's own.

**Comment by manning** [comment]
To get better behaviour soon, you'd need to use at least the improved PTBTokenizer and PTBLexer classes from github.

**Comment by jplu** [comment]
That's perfect, thanks a lot!
