### ISSUE TITLE
Tokenization inconsistency

### ISSUE THREAD

**Issue by octavian-ganea** [stanfordnlp/CoreNLP#152]
There is an inconsistency in processing dots in the tokenizer:
The following code
```
    val ptbt = new PTBTokenizer(
      new StringReader("Tokenization is performed.Parameters can be specified."),
      new CoreLabelTokenFactory(), "")
    while (ptbt.hasNext()) {
      val label = ptbt.next()
      val w = label.originalText()
      println(w)
    }
```
gives "performed.Parameters" as an word. If I put a space after 'performed' it will work, but still, natural text can be messy and omitting spaces after punctuation is very common.

**Comment by manning** [comment]
This isn't an inconsistency, but a consistency (!). The current CoreNLP tokenizer does not split on periods surrounded by letters.

This is a difficult issue. It actually used to split cases like this, reasoning that sometimes the space is missing and this would be useful, as you note. But there are also a fair number of cases where periods occur in a word that should not be split including an ever-expanding range of domain names (California.Travel), filenames, various stock ticker symbols, usernames, etc.

Even though PTBTokenizer has a lot of heuristics that result in it really working rather well on edited text - better than pretty much everything else out there - at the end of the day it is just a big finite state machine, and differentiating the good and bad splits here becomes almost impossible, and so we opted for the principle of least surprise and to always not split. If someone wants to, you can insert a second TokenizerFixup annotator after the tokenizer to further split tokens as you think best.

At some point, it probably would be useful to have a machine learned/language model tokenizer more suitable for social media text, where spaces are often missing - not only after periods - but at present there is no work underway by us to provide one.
