### ISSUE TITLE
dcoref always returns null

### ISSUE THREAD

**Issue by xuanchien** [stanfordnlp/CoreNLP#154]
With `dcoref` annotator, I can not get the CorefChain in the document. I even try running the sample code `StanfordCoreNlpDemo.java` provided in the `stanford-corenlp-full-2015-12-09` but it also does not work. When checking further, I see that the `Annotation` indeed contains the coreference result but with the hash key: `hcoref.CorefCoreAnnotations.CorefChainAnnotation`, not `dcoref.CorefCoreAnnotations.CorefChainAnnotation`. Therefore, the following `corefChains` variable will always return null

```
Map<Integer, CorefChain> corefChains =
                    annotation.get(CorefCoreAnnotations.CorefChainAnnotation.class);
```

Please check and fix this issue.

**Comment by xuanchien** [comment]
I've looked further into the source code and realized that the following line has been commented out (in `src/edu/stanford/nlp/pipeline/DeterministicCorefAnnotator.java`):

```
Map<Integer, CorefChain> result = corefSystem.coref(document);
      annotation.set(CorefCoreAnnotations.CorefChainAnnotation.class, result);
```

and replaced with the following:
```
Map<Integer, edu.stanford.nlp.hcoref.data.CorefChain> result = corefSystem.corefReturnHybridOutput(document);
      annotation.set(edu.stanford.nlp.hcoref.CorefCoreAnnotations.CorefChainAnnotation.class, result);
```

My temporary fix is to use full package name `edu.stanford.nlp.hcoref` to get the CorefChains correctly. Still not sure why it is done like this in the code. Perhaps more explanation or comment is necessary

**Comment by J38** [comment]
Thank you for pointing this out, I have updated the demo to reflect this change.

**Comment by Millymanz** [comment]
Hi, I am very interested in getting this example to work. I tried this example in Standford.NLP.NET and I keep getting null, for Map<Integer, CorefChain> coref = document.get(CorefChainAnnotation.class). 

This is what I am trying to recreate in C#.

JAVA
Map<Integer, CorefChain> coref = document.get(CorefChainAnnotation.class);

for(Map.Entry<Integer, CorefChain> entry : coref.entrySet()) {
    CorefChain c = entry.getValue();

    //this is because it prints out a lot of self references which aren't that useful
    if(c.getCorefMentions().size() <= 1)
        continue;

    CorefMention cm = c.getRepresentativeMention();
    String clust = "";
    List<CoreLabel> tks = document.get(SentencesAnnotation.class).get(cm.sentNum-1).get(TokensAnnotation.class);
    for(int i = cm.startIndex-1; i < cm.endIndex-1; i++)
        clust += tks.get(i).get(TextAnnotation.class) + " ";
    clust = clust.trim();
    System.out.println("representative mention: \"" + clust + "\" is mentioned by:");

    for(CorefMention m : c.getCorefMentions()){
        String clust2 = "";
        tks = document.get(SentencesAnnotation.class).get(m.sentNum-1).get(TokensAnnotation.class);
        for(int i = m.startIndex-1; i < m.endIndex-1; i++)
            clust2 += tks.get(i).get(TextAnnotation.class) + " ";
        clust2 = clust2.trim();
        //don't need the self mention
        if(clust.equals(clust2))
            continue;

        System.out.println("\t" + clust2);
    }
}

Can you help?
