### ISSUE TITLE
The examples files missed in demo

### ISSUE THREAD

**Issue by cnwarden** [stanfordnlp/CoreNLP#155]
Hi, In `edu.stanford.nlp.classify.demo.ClassifierDemo.java`, it uses "examples/cheese2007.prop", but I can't find files in whole project.

the same with other examples, can't find necessary files.

**Comment by manning** [comment]
Sorry, there is some history here and some things to fix up, since we originally only had separate release packages before corenlp.

For the moment, if you want the example files, you need to get them from the Stanford Classifier download:

    http://nlp.stanford.edu/software/classifier.html

**Comment by cnwarden** [comment]
Great Thanks. :+1:
