### ISSUE TITLE
Store language in NN dependency parser model

### ISSUE THREAD

**Issue by sebschu** [stanfordnlp/CoreNLP#156]
The NN dependency parser models currently don't store the language and therefore unless a user specifies the `depparse.language` property it always assumes that the language is `UniversalEnglish`, which in return causes problems in the generation of _collapsed_ and _CCprocessed_ Stanford Dependencies.

**Comment by J38** [comment]
I'm going to modify this to write the language as the last line of the serialized model.  Older models will still work, the loading code will be able to handle the absence of a specified language.

**Comment by J38** [comment]
Ok future models will start with:

```
language=spanish
tlp=edu.stanford.nlp.trees.PennTreebankLanguagePack
```

I've set the code up to check if the saved model is the old format or new format, so old models should work as before.
