### ISSUE TITLE
Sentiment prediction demo isn't working

### ISSUE THREAD

**Issue by davidaparicio** [stanfordnlp/CoreNLP#157]
The demo on http://nlp.stanford.edu:8080/sentiment/rntnDemo.html isn't working due to a permission error:

java.io.IOException: Permission denied
	java.io.UnixFileSystem.createFileExclusively(Native Method)
	java.io.File.createTempFile(File.java:2024)
	com.cs224u.rt.web.batchController.handleRequestInternal(batchController.java:114)

Moreover, there is a code example to find the same sentiment like the Sentiment Treebank?
Because, the sentiment analysis found for CoreNLP was only based on the longest sentence..
Thank

Best regards,
David

**Comment by davidaparicio** [comment]
Is it possible to have the code used to recreate the Sentiment Treebank?

**Comment by J38** [comment]
We have fixed the online sentiment demo.
