### ISSUE TITLE
regexner annotator does not work properly with ner annotator

### ISSUE THREAD

**Issue by masumsoft** [stanfordnlp/CoreNLP#161]
I'm trying to use `regexner` annotator so that it overwrites some of the entities recognised as `O` or `MISC` from the `ner` annotator. I'm trying to query the corenlp server like the following:

```
/?properties={"annotators": "tokenize, ssplit, pos, lemma, ner, regexner", "outputFormat": "json"}
```

But it does not work as expected. If I only use the `regexner` then it works, but when I wanted to use it along with the `ner` annotator, so that the `regexner` overwrites the recognised entities, it only shows the entities recognised from `ner` as if the `regexner` did nothing. Looking at the corenlp server logs, I found that the annotators are actually reordered while executing like the following: 

```
API call w/annotators tokenize,ssplit,regexner,pos,lemma,ner
```

So I guess the `regexner` is being called before the `ner` violating the order of annotators mentioned by me. Could you guys have a look into this?

**Comment by manning** [comment]
I agree. I'm not sure why annotators are being reordered when using the corenlp server, but it is clearly dysfunctional between ner and regexner for the reason you give.

**Comment by gangeli** [comment]
This is indeed a bug. The server actually tries to guess prerequisite annotators if you supply an incomplete annotation list (e.g., just `depparse`). But, in doing so, it was re-ordering annotators that didn't have any stated dependencies between them -- such as `ner` and `regexner`. I've committed a fix for this.
