### ISSUE TITLE
Simple coreference not recognized

### ISSUE THREAD

**Issue by jplu** [stanfordnlp/CoreNLP#163]
Hello,

I'm currently testing the coref annotator with few different sentences (some are easy others are pretty tricky) to see its limitations. Although, I'm impressed of its general accuracy, I'm also surprised that some very easy sentences are not handled. As example, for the sentence: ```Barack Obama is an american politician. He was Born in Hawaï.```, no coreference are recognized. I used the default behavior of the ```coref``` annotator and also with the following options: ```coref.md.type=rule coref.mode=statistical coref.doClustering=true```.

Is it a bug coming from the annotator, or there is a property I have missed or not well set?

Thanks!

**Comment by J38** [comment]
I am seeing "Barack Obama" matched with "He" when I use your example.  I used this command:

    java -Xmx5g -cp "stanford-corenlp-full-2015-12-09/*" edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,mention,coref -file stack-overflow-coref-example.txt -outputFormat text

**Comment by jplu** [comment]
Oops really sorry for this very late reply :-( I certainly missed the Github email... :-(

I'm indeed using the 3.6 version and with command line it works like a charm. I remember that I had tested also this sentence against the online version http://corenlp.run/ (which at this moment is down) and no coref annotations as well between "He" and "Barack Obama".

Also, might be also something wrong coming from the way I use it in my code:

```
Properties props = new Properties();

props.put("annotators", "tokenize, ssplit, pos, lemma, ner, parse, mention, coref");
props.put("coref.md.type", "rule");
props.put("coref.mode", "statistical");
props.put("coref.doClustering", "true");
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
Annotation document = new Annotation("Barack Obama is an american politician. He was Born in Hawaï.");
pipeline.annotate(StanfordCoreNLPTool.document);

if (document.get(CorefCoreAnnotations.CorefChainAnnotation.class) != null) {
    for (CorefChain cc : document.get(CorefCoreAnnotations.CorefChainAnnotation.class).values()) {
        for (CorefChain.CorefMention mention : cc.getMentionsInTextualOrder()) {
            System.out.println(mention.mentionSpan + " -> " + cc.getRepresentativeMention().mentionSpan);
        }
    }
} else {
    System.out.println("No coref found");
}
```

With this sentence, this piece of code outcome "No coref found". Did I do something wrong?

**Comment by jplu** [comment]
Ok it has been fixed in the master branch. Thanks!
