### ISSUE TITLE
Logging control

### ISSUE THREAD

**Issue by silentsnooc** [stanfordnlp/CoreNLP#168]
It appears that the only way to remove the debug output from CoreNLP is possible by replacing the error output stream:

```scala
val err = System.err;

System.setErr(new PrintStream( new OutputStream() {
  override def write(b: Int): Unit = {}
}))

// Do stuff ..

System.setErr(err)
```

It would be awesome if we had more control about that e.g. with log4j

**Comment by gangeli** [comment]
If you have slf4j in your classpath, logging statements should automatically be routed through it, and from there you can do all the normal things to hide debug statements. You should also be able to get CoreNLP to shut up with the statement `RedwoodConfiguration.empty().apply()`. This will simply drop all logging messages into the void.

**Comment by silentsnooc** [comment]
Oh, thanks for that information I didn't realize that!

**Comment by manning** [comment]
Note that some of what @gangeli writes, especially the Redwood part, is only true if you're using the current version from github....  But it will be generally true in the future.
