### ISSUE TITLE
Maven dependencies don't include protobuf-java

### ISSUE THREAD

**Issue by camullen** [stanfordnlp/CoreNLP#171]
The current pom.xml file appearing on Maven Central does not have a dependency to the protobuf-java artifact. As a result, if you want to use a maven dependency, you have to install it yourself.

**Comment by J38** [comment]
Thanks for the observation.  We will work on resolving this issue next week.

**Comment by camullen** [comment]
No problem! Go Card!

**Comment by heni** [comment]
Is this true, that this problem didn't resolved yet?

**Comment by J38** [comment]
I am not sure the plan to resolve this yet.  

The pom.xml on GitHub is fixed: https://github.com/stanfordnlp/CoreNLP/blob/master/doc/corenlp/pom-full.xml if you just want to go into your ~/.m2/repository and update it.

I'll update this issue when we know what we're going to do.

**Comment by J38** [comment]
This issue will be fixed with the upcoming Stanford CoreNLP 3.7.0 release.
