### ISSUE TITLE
tokenize.options are ignored in pipeline.StanfordCoreNLP?

### ISSUE THREAD

**Issue by vspinu** [stanfordnlp/CoreNLP#172]
I cannot make `ptb3Escaping` working as described in the [API](http://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/process/PTBTokenizer.html).

```

java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP \
     -annotators tokenize,ssplit,pos,parse,sentiment \
     -outputFormat json \
     -tokenize.options ptb3Escaping=true,normalizeFractions=true 
```

Then paste "None-sense with 1/2 colour.". I expect 1/2 and colour to be substituted. Instead I am getting:

```
     "tokens": [
        {
          "index": 1,
          "word": "None-sense",
          "originalText": "None-sense",
          "characterOffsetBegin": 0,
          "characterOffsetEnd": 10,
          "pos": "JJ"
        },
        {
          "index": 2,
          "word": "with",
          "originalText": "with",
          "characterOffsetBegin": 11,
          "characterOffsetEnd": 15,
          "pos": "IN"
        },
        {
          "index": 3,
          "word": "1/2",
          "originalText": "1/2",
          "characterOffsetBegin": 16,
          "characterOffsetEnd": 19,
          "pos": "CD"
        },
        {
          "index": 4,
          "word": "colour",
          "originalText": "colour",
          "characterOffsetBegin": 20,
          "characterOffsetEnd": 26,
          "pos": "NN"
        },
        {
          "index": 5,
          "word": ".",
          "originalText": ".",
          "characterOffsetBegin": 26,
          "characterOffsetEnd": 27,
          "pos": "."
        }
      ]
```

I guess I am doing something wrong or misinterpreting the API page. 

Thanks.

**Comment by vspinu** [comment]
This is stanford-corenlp-full-2015-12-09.

**Comment by J38** [comment]
I see this command working fine on your example:

    java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,parse,sentiment -outputFormat text -tokenize.options "americanize=true,normalizeFractions=true" -file ../tokenize-options-example.txt

normalizeFractions=true by default

The input text I used was:

    None-sense with ½ colour.

**Comment by vspinu** [comment]
Thanks. That's what normalize fractions means. I thought it will be substituted by words, like "one half". 

Ok. But how about `americanise=true` which is also by default as per `ptb3Escaping=true`; `colour` is not substituted by `color`.

**Comment by J38** [comment]
Are you using "americanize=true" with a "z"?  I am seeing it do the correct substitution on your example.  My sample command above should work.

**Comment by vspinu** [comment]
Actually I was not explicitly setting it. PTBTokenizer [javadoc](http://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/process/PTBTokenizer.html) says that it should be by default true. 

In any case, adding `americanize=true` did it. Thanks!
