### ISSUE TITLE
StanfordCoreNLPServer's documentation doesn't mention the timeout parameter 

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [stanfordnlp/CoreNLP#174]
The [StanfordCoreNLPServer's documentation](http://stanfordnlp.github.io/CoreNLP/corenlp-server.html) doesn't mention the `timeout` parameter.

It should be:

    java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer [port] [timeout]

**Comment by gangeli** [comment]
Fair enough, though it'll be outdated soon anyways with the next release, where we'll have proper flags (and more of them!) for: `-port [port]`  `-timeout [timeout]`  `-quiet` and `-strict`.
