### ISSUE TITLE
German CoreNLP NNDEP parser model is actually a French model

### ISSUE THREAD

**Issue by reckart** [stanfordnlp/CoreNLP#183]
Looks like the German dependency parser model was mis-packaged.

The following two files...

```
  http://nlp.stanford.edu/software/stanford-french-corenlp-2016-01-14-models.jar
  http://nlp.stanford.edu/software/stanford-german-2016-01-19-models.jar
```

contain the model files

```
  edu/stanford/nlp/models/parser/nndep/UD_French.gz
  edu/stanford/nlp/models/parser/nndep/UD_German.gz
```

which appear to both have the same size and CRC:

```
  UD_German.gz  19.01.2016 04:29:02  24.636.092 bytes  CRC 25830829
  UD_French.gz  14.01.2016 13:36:58  24.636.092 bytes  CRC 25830829
```

... and the same MD5 checksum: c2cd7c55750e2d4dcdd8a16963430c40

Looks like the UD_German.gz model is actually the French model as it contains words such as "phénomène".

**Comment by J38** [comment]
Thank you for pointing this out, I will investigate further.  It does appear when I diff the two files they are the same!

**Comment by J38** [comment]
This issue has been resolved in the current code base.  In the upcoming 3.7.0 release the next models will be fixed.
