### ISSUE TITLE
Unicode General Punctation U+2022 (•) not recognized as punctuation by POS tagger

### ISSUE THREAD

**Issue by cnantoninor** [stanfordnlp/CoreNLP#185]
Hello Stanford CoreNLP team,

given sentences containing Unicode General Punctation chars U+2022 (•), those char sequences are  tagged wrongly. 

Examples: 

> • I couldn't be more proud and excited to team up with an amazing group of people to give the world something really special.

The POS-tagger marked the initial bullet as NN

> I couldn't be more proud and excited to team up with an amazing group of people to give the world something really special. • • •

The POS-tagger marked the sequence • • • as NN CD NN

Best,
Antonino

**Comment by J38** [comment]
Thanks for bringing up this issue.  I will look into how to correct this for future releases!

**Comment by manning** [comment]
A lot of the original treebank data we use was originally ASCII-fied or pre-Unicode, unfortunately.

I've added a couple of examples, so when in the future we train parsers and taggers, it should become SYM. But this won't make it into the next release....
