### ISSUE TITLE
StanfordCoreNLPServer ignores parse.maxlen and pos.maxlen properties

### ISSUE THREAD

**Issue by klopyrev** [stanfordnlp/CoreNLP#186]
It seems like there's an extra negation in the following lines: https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/StanfordCoreNLPServer.java#L572

It should be "-1".equals(props.getProperty("parse.maxlen", "60")), not !"-1".equals(props.getProperty("parse.maxlen", "60"))

@gangeli @muzny

**Comment by gangeli** [comment]
So, if I recall this was put in after the Great Hacker News [Unintentional] DDOS Of 2016, where we got a bunch of concurrent requests to the service on our little 4-core machine, and I was trying to keep users from putting in sentences that would cause the parser to take forever. Now that we have timeouts implemented a bit more carefully, this should actually be unnecessary altogether. I've removed it.
