### ISSUE TITLE
percentageOfTrain parameter in edu.stanford.nlp.ie.machinereading.MachineReading is never used

### ISSUE THREAD

**Issue by git-rbanerjee** [stanfordnlp/CoreNLP#189]
Hi ,

   We wanted to fed the training set incrementally , to see the learning graph . But the parameter for that percentageOfTrain  is hashed .

// partitionTrain = keepPercentage(partitionTrain, percentageOfTrain);  

Is there any reason to hash it out ?

**Comment by J38** [comment]
I am not sure why that was commented out.  Have you tried un-commenting it out and running it?

**Comment by git-rbanerjee** [comment]
I am not compiling it from source , using maven to fetch the jar .
<dependency>
			<groupId>edu.stanford.nlp</groupId>
			<artifactId>stanford-corenlp</artifactId>
			<version>3.6.0</version>
			<classifier>models</classifier>
</dependency>

But , I checked the code , it should work if uncomment it . 

Kindly create a minor version and add this fix.

**Comment by git-rbanerjee** [comment]
I tried it un-commenting it, and it is working ,

```
// for learning curve experiments
         // partitionTrain = keepPercentage(partitionTrain, percentageOfTrain);
         partitionTrain = keepPercentage(partitionTrain, MachineReadingProperties.percentageOfTrain);        
    
```    

It is working fine.

**Comment by git-rbanerjee** [comment]
Same has been marged :+1: 
Thanks.
https://github.com/stanfordnlp/CoreNLP/pull/192#event-668126515
