### ISSUE TITLE
please, stop write log messages to sterr

### ISSUE THREAD

**Issue by antonkulaga** [stanfordnlp/CoreNLP#194]
You write log messages to stderr, that is why in all libs that use standford NLP people are confused by a lot of ERROR-looking messages, like 

``` bash
root[ERROR] Adding annotator tokenize
root[ERROR] Adding annotator ssplit
root[ERROR] Adding annotator pos
root[ERROR] Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1,2 sec].
root[ERROR] Adding annotator lemma
```

and then they spend time on searching what is wrong while everything is ok =(

**Comment by gangeli** [comment]
If you have SLF4J in your classpath, messages should be logged onto there automatically with the appropriate log levels. If not, between stdout and stderr, clearly log messages should go to stderr (since useful output occasionally goes to stdout).

**Comment by manning** [comment]
Closing this since I think new version does a pretty good job of logging via slf4j if available, and to stderr otherwise.  If anyone finds stray stderr prints please raise as separate issues.
