### ISSUE TITLE
Round brackets are not working in regexner?

### ISSUE THREAD

**Issue by rajsinghudr** [stanfordnlp/CoreNLP#196]
I have a text like "ABC (XYZ WR) is a the best product launched by ABC company."

I have added the "products.txt" file as a regex NER file and marked "ABC (XYZ WR)" as a PRODUCT as below:

ABC (XYZ WR)         PRODUCT

In the output it is not extracting the ABC (XYZ WR) as a PRODUCT.

I tried to escape the "(" by using "\" escape character, but did not get any success.
ABC \(XYZ WR\)         PRODUCT          (not working)

**Comment by gangeli** [comment]
Try replacing "(" with "-LRB-" and ")" with "-RRB-".

**Comment by rajsinghudr** [comment]
No, i tried this, but its not working.

**Comment by J38** [comment]
You need to add a space between the "-LRB-" and XYZ and a space between "WR" and "-RRB-".  The RegexNER runs over tokens, and you separate each token in the pattern by a space.  When the tokenizer runs on text it transforms "(" into "-LRB-" and ")" into "-RRB-", and it also treats each as it's own token.  So "(XYZ WR)" becomes the token stream: 0:"-LRB-", 1:"XYZ", 2:"WR", 3:"-RRB-".

So if you have the rule:
Apple -LRB- IPhone 10 -RRB-(tab)PRODUCT

The string "I just bought the new Apple (IPhone 10)" will have all the tokens Apple (IPhone 10) tagged as PRODUCT.  But note that it will treat "(" and "IPhone" as separate tokens.

**Comment by rajsinghudr** [comment]
Thanks a lot J3B and gangeli, It worked like a charm. I just forgot to add space in the LRB AND RRB.
Thanks again guys for quick help.
