### ISSUE TITLE
Tokenization bug on censored profanities

### ISSUE THREAD

**Issue by gangeli** [stanfordnlp/CoreNLP#197]
I don't trust myself to poke around the tokenizer, so I'm filing a bug report instead :)

Tokenization fails on censored profanities (e.g., those matching the regexps /f\*+c?k?/ and /sh?\*+i?t?/), tokenizing instead as, e.g., `f *** k` (3 tokens).

**Comment by AngledLuffa** [comment]
You mean literally that

f***k -> f *** k
s*****t -> s ***** t

not that it is somehow tokenizing swear words into smaller components,
right?

**Comment by gangeli** [comment]
Yes, the literal string "f***k" tokenizes as "f   ***   k".

**Comment by manning** [comment]
I actually added a couple of these to the tokenizer a while back -- looks like 2015/07/05 (!). So `f**k` already works for me, and so I dispute the most recent message from @gangeli. However, what was added was just `f\*[c*]k(in[g']|e[dr])?|sh\*t(ty)?`, so you could certainly imagine more extensive handling. If you had a list, I could add some more. I'm not sure that `f***k` appears much does it? Certainly, if I search for that on Google, all the answers I seem to be getting are just `f**k`. It seems like there's much more need to support `f--k`.

**Comment by gangeli** [comment]
You're right -- "f**k" is indeed tokenized correctly. Looking back, the example that broke the tokenizer for me was "what the f***", and I'd assumed this meant that all of the censored profanities were broken. If there's already a place in the flex file where these are defined, I could take a look and tweak the regex myself.

**Comment by manning** [comment]
The ones matched are stuffed at the end of TBSPEC. It doesn't match a trailing \* and I wouldn't be in favor of adding that. I think that would tend to overmatch when you don't want it to.
