### ISSUE TITLE
Can numbers be annotated?

### ISSUE THREAD

**Issue by garfieldnate** [stanfordnlp/CoreNLP#199]
I found in the online documentation the mention of a NumberAnnotator in the pipeline package. I found the source on here on GitHub, and see that the class has been in the code base since September 2014. However, the 3.6.0 code released in January of this year doesn't seem to contain it. Is there currently any way to do number annotation (I'm trying to extract numeric values from spelled words), or is alpha/unreleased?

**Comment by J38** [comment]
The default NER will tag a number with NUMBER.  So for instance, in the sentence "There have been forty three presidents", forty and three will be tagged as "NUMBER" and each will have the value "43.0"

**Comment by J38** [comment]
import java.util.*;
import edu.stanford.nlp.ling.*;
import edu.stanford.nlp.pipeline.*;
import edu.stanford.nlp.util.*;


public class NumberIdentificationExample {

    public static void main(String[] args) {
        Properties props = new Properties();
        props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner");
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
        String text = "There have been forty three presidents.";
        Annotation annotation = new Annotation(text);
        pipeline.annotate(annotation);
        for (CoreMap sentence : annotation.get(CoreAnnotations.SentencesAnnotation.class)) {
            List<CoreMap> numbers = sentence.get(CoreAnnotations.NumerizedTokensAnnotation.class);
            for (CoreMap number : numbers) {
                if(!number.containsKey(CoreAnnotations.NumericCompositeValueAnnotation.class)){
                    continue;
                }
                System.out.println("start: "+number.get(CoreAnnotations.TokenBeginAnnotation.class));
                System.out.println("end: "+number.get(CoreAnnotations.TokenEndAnnotation.class));
            }
        }
    }
}

**Comment by garfieldnate** [comment]
Thanks for the info and example.
I'd like to do just number annotation, though. For my application I need this to be as fast as possible and I don't want to run more annotators than are required, and definitely not anything that requires loading models. Is this possible?

**Comment by garfieldnate** [comment]
I think I mostly have it figured out. The code below is supposed to create the pipeline programmatically and mark numbers, but it doesn't work:

	import java.io.IOException;
	import java.util.Properties;
	import edu.stanford.nlp.pipeline.Annotation;
	import edu.stanford.nlp.pipeline.AnnotationPipeline;
	import edu.stanford.nlp.pipeline.AnnotatorImplementations;
	import edu.stanford.nlp.pipeline.POSTaggerAnnotator;
	import edu.stanford.nlp.pipeline.TokenizerAnnotator;
	import edu.stanford.nlp.pipeline.WordsToSentencesAnnotator;
	public class NumberTest {
		public static void main(String[] args) throws IOException {
			Properties props = new Properties();
			props.setProperty("ner.model", "");
			props.setProperty("ner.applyNumericClassifiers", "true");
			props.setProperty("ner.useSUTime", "false");
			AnnotationPipeline pipeline = new AnnotationPipeline();
			pipeline.addAnnotator(new TokenizerAnnotator(false,"en"));
			pipeline.addAnnotator(new WordsToSentencesAnnotator(false));
			pipeline.addAnnotator(new POSTaggerAnnotator(false));
			pipeline.addAnnotator(new AnnotatorImplementations().ner(props));

			Annotation document = new Annotation("100 apples");
			pipeline.annotate(document);
		        System.out.println(document.keySet());
		}
	}

I'm not sure if this is a bug or just me not creating the number annotator correctly.

When I step through the execution, I first come to `NERCombinerAnnotato`r line 142, where I see that 100 has been marked as `NUMBER` with value `100.0` (values of `neTag` and `normNeTag`). I then step into `NumberSequenceClassifier.transferAnnotations`, which it would seem is supposed to copy the number annotations from `src` into `dst`. `src` contains the following keys and values:

   	 keys: [edu.stanford.nlp.ling.CoreAnnotations$ValueAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$TextAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$OriginalTextAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$CharacterOffsetBeginAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$CharacterOffsetEndAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$BeforeAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$AfterAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$IndexAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$SentenceIndexAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$PartOfSpeechAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$PositionAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$AnswerAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$NamedEntityTagAnnotation,
	 	edu.stanford.nlp.ling.CoreAnnotations$NormalizedNamedEntityTagAnnotation]
    values: [100, 100, 100, 0, 3, ,  , 1, 0, CD, 0, NUMBER, NUMBER, 100.0]

So I guess the the number annotation is stored as a NormalizedNamedEntityTagAnnotation. The method then checks for three types of annotations to copy: `CoreAnnotations.NumericCompositeValueAnnotation`, `CoreAnnotations.NumericCompositeTypeAnnotation`, and `TimeAnnotations.TimexAnnotation`. None of these match the actual number annotation, so none are copied. The annotation is then returned, without the detected number sequence having been placed in the annotation.

I am unsure if I instantiated the annotator correctly or if this is incorrect behavior.

**Comment by garfieldnate** [comment]
@J38 Would my last comment be better placed in a new issue?

**Comment by J38** [comment]
I'll re-open this issue and look into it more soon!

**Comment by garfieldnate** [comment]
Thanks!

**Comment by J38** [comment]
This command shows how to run a pipeline just for tagging NUMBER.

`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner -ner.model "" -ner.applyNumericClassifiers -file example.txt -outputFormat text`

You can adapt these settings for use with the Java API.  More info about the Java API here:

https://stanfordnlp.github.io/CoreNLP/api.html

**Comment by LockedInTheSkage** [comment]
> import java.util.*;
> import edu.stanford.nlp.ling.*;
> import edu.stanford.nlp.pipeline.*;
> import edu.stanford.nlp.util.*;
> 
> 
> public class NumberIdentificationExample {
> 
>     public static void main(String[] args) {
>         Properties props = new Properties();
>         props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner");
>         StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
>         String text = "There have been forty three presidents.";
>         Annotation annotation = new Annotation(text);
>         pipeline.annotate(annotation);
>         for (CoreMap sentence : annotation.get(CoreAnnotations.SentencesAnnotation.class)) {
>             List<CoreMap> numbers = sentence.get(CoreAnnotations.NumerizedTokensAnnotation.class);
>             for (CoreMap number : numbers) {
>                 if(!number.containsKey(CoreAnnotations.NumericCompositeValueAnnotation.class)){
>                     continue;
>                 }
>                 System.out.println("numeric value: "+number.get(CoreAnnotations.NumericCompositeValueAnnotation.class));
>                 System.out.println("start: "+number.get(CoreAnnotations.TokenBeginAnnotation.class));
>                 System.out.println("end: "+number.get(CoreAnnotations.TokenEndAnnotation.class));
>             }
>         }
>     }
> }

Hey there! I am trying to do something akin to what this script is an example of, but this code doesn't seem to work anymore. You wouldn't happen to have any more recent examples of code like this?

**Comment by AngledLuffa** [comment]
I see, that code is from 8 years ago in this git issue.  It seems the interface has changed some in the years since then.  Here is what seems to work for me:

```
  public static void main(String[] args) {
    Properties props = new Properties();
    props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner");
    StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
    String text = "There have been forty three presidents.";
    Annotation annotation = new Annotation(text);
    pipeline.annotate(annotation);
    for (CoreMap sentence : annotation.get(CoreAnnotations.SentencesAnnotation.class)) {
      List<CoreLabel> tokens = sentence.get(CoreAnnotations.TokensAnnotation.class);
      for (CoreLabel token : tokens) {
        System.out.println(token);
        System.out.println(token.get(CoreAnnotations.NormalizedNamedEntityTagAnnotation.class));
      }
  }
}
```

```
There-1
null
have-2
null
been-3
null
forty-4
43.0
three-5
43.0
presidents-6
null
.-7
null
```

**Comment by LockedInTheSkage** [comment]
Thank you very much! This seemed to work for me!
