### ISSUE TITLE
SUTime gives wrong result (2015 rather than 2016)

### ISSUE THREAD

**Issue by yunshengb** [stanfordnlp/CoreNLP#201]
When I type "What is on my calendar next week?" and check "Include range," on the demo web page http://nlp.stanford.edu:8080/sutime/process , the result is "next week	2016-W23	<TIMEX3 range="(2015-06-01,2015-06-07,P1W)" tid="t1" type="DATE" value="2016-W23">next week</TIMEX3>" which is incorrect. 

It should be 2016, not 2015. The same issue for "previous week."

It works for "What is on my calendar next 2 weeks," so maybe I miss something. Thank you very much!

![screenshot from 2016-06-04 16 42 18](https://cloud.githubusercontent.com/assets/8391016/15801975/52d7616c-2a73-11e6-88dd-cbd575616228.png)

**Comment by pbhadauria** [comment]
My guess is that the web app is not using the base date for DocDateAnnotation. You can try following code to get the right range. With base date as '2016-06-06', I get range as '(2015-06-08,2015-06-14,P1W)'.

Annotation annotation = new Annotation("What is on my calendar next week?");
annotation.set(CoreAnnotations.DocDateAnnotation.class, "2016-06-06");
StanfordNLP.getInstance().getNlpPipeline().annotate(annotation);
List<CoreMap> timePatterns = annotation.get(TimeAnnotations.TimexAnnotations.class);
for (CoreMap timePattern : timePatterns) {
    SUTime.Temporal temporal = timePattern.get(TimeExpression.Annotation.class).getTemporal();
    System.out.println(temporal.getRange());
}

**Comment by mirosval** [comment]
#235

**Comment by J38** [comment]
This issue has been fixed.  There have been some improvements to handling of phrases with word "week" in them.
