### ISSUE TITLE
Strange behavior of NER options

### ISSUE THREAD

**Issue by rationalism** [stanfordnlp/CoreNLP#205]
I'm running CoreNLP 3.6.0, and getting some strange behavior when I try to configure NER. These CoreNLP options:

Properties props = new Properties();
props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, entitymentions");
props.setProperty("ner.applyNumericClassifiers", "false")
props.setProperty("ner.useSUTime", "false")
props.setProperty("ner.markTimeRanges", "false")
props.setProperty("ner.includeRange", "false")
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

run on this sentence:

"I will be in San Francisco from 6 PM to 9 PM."

tag "San Francisco" as a LOCATION, and that's the only tag, as expected. However, when these options are run on this sentence:

"I will be in San Francisco from January 22nd to January 27th."

they tag "San Francisco" as a LOCATION and January 22nd/January 27th as DATE, even though SUTime is supposed to be switched off. With this set of options:

Properties props = new Properties();
props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, entitymentions");
props.setProperty("ner.applyNumericClassifiers", "true")
props.setProperty("ner.useSUTime", "true")
props.setProperty("ner.markTimeRanges", "true")
props.setProperty("ner.includeRange", "true")
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

the sentence "I will be in San Francisco from 6 PM to 9 PM." now includes the times, but it and the sentence "I will be in San Francisco from January 22nd to January 27th." have two DATE tags instead of one DURATION tag, even though "markTimeRanges" is set to true. "markTimeRanges" is supposed to be an SUTime option, but when I tried this set of options:

Properties props = new Properties();
props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, entitymentions");
props.setProperty("ner.applyNumericClassifiers", "true")
props.setProperty("ner.useSUTime", "true")
props.setProperty("sutime.markTimeRanges", "true")
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

I got this error:

sutime.markTimeRanges=true
Unknown property: |sutime.markTimeRanges|

while the pipeline was being loaded (before any text had been parsed).

**Comment by J38** [comment]
Here is some sample code that will get the duration:

```
import java.io.*;
import java.util.*;
import edu.stanford.nlp.io.*;
import edu.stanford.nlp.ling.*;
import edu.stanford.nlp.pipeline.*;
import edu.stanford.nlp.time.*;
import edu.stanford.nlp.trees.*;
import edu.stanford.nlp.trees.TreeCoreAnnotations.*;
import edu.stanford.nlp.semgraph.*;
import edu.stanford.nlp.ling.CoreAnnotations.*;
import edu.stanford.nlp.util.*;

public class SUTimeExample {

    public static void main(String[] args) {
        Properties props = new Properties();
        props.setProperty("customAnnotatorClass.sutime", "edu.stanford.nlp.time.TimeAnnotator");
        props.setProperty("sutime.markTimeRanges", "true");
        props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, sutime");
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
        Annotation ann = new Annotation("I will be in San Francisco from January 22nd to January 27th.");
        pipeline.annotate(ann);
        for (CoreMap timeAnnotation : ann.get(TimeAnnotations.TimexAnnotations.class)) {
            System.out.println(timeAnnotation.get(CoreAnnotations.TextAnnotation.class));
        }
        for (CoreLabel token : ann.get(CoreAnnotations.TokensAnnotation.class)) {
            System.out.println(token+" "+token.get(CoreAnnotations.NamedEntityTagAnnotation.class));
        }
    }
}
```
