### ISSUE TITLE
Percentage unparsable

### ISSUE THREAD

**Issue by Tooa** [stanfordnlp/CoreNLP#206]
Hi,

the following sentence `Waiter earned his standard 15%.` yields

> {"sentences":[{"index":0,"line":1,"parse":"SENTENCE_SKIPPED_OR_UNPARSABLE" [...]

for the web-interface [1] and also for the latest git version (tested commit hash e25f46f76af78cdcc06fdf20b6df3f57c4f1b032). 

Command:
> wget --tries=2  --post-data  "Waiter earned his standard 15%." 'localhost:1337/?properties={"ssplit.eolonly": "true", "annotators": "tokenize,ssplit,pos,lemma,ner,depparse","outputFormat": "json",'timeout': 9000000}' -O res.json

Best Uli

[1] http://corenlp.run/

**Comment by gangeli** [comment]
You don't have the `parse` annotator in your annotators list. The sentence is not unparsable, but rather just skipped.

**Comment by Tooa** [comment]
Have you tried to process the sentence in the web interface? It says `Could not handle incoming annotation`. I still think there is something broken.

**Comment by gangeli** [comment]
You're right. Let me look into it...

**Comment by sebschu** [comment]
@gangeli It looks like jQuery does not URI encode POST data if you pass it as a string. 

> By default, data passed in to the data option as an object (technically, anything other than a string) will be processed and transformed into a query string, fitting to the default content-type "application/x-www-form-urlencoded".
-- http://api.jquery.com/jquery.ajax/

I committed a fix that manually encodes the sentence but I don't know how to deploy a new version to the server, so that's still left to do.
