### ISSUE TITLE
How to deal with Chinese words with Stanford NLP

### ISSUE THREAD

**Issue by befeng** [stanfordnlp/CoreNLP#207]
how to deal with Chinese words with Stanford NLP that like English pipeline ?

**Comment by J38** [comment]
Here's an example command:

    java -Xmx6g edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-chinese.properties -file chinese-example-2.txt -outputFormat text

The key is to load the properties in the file StanfordCoreNLP-chinese.properties which configures the pipeline to handle Chinese text.
