### ISSUE TITLE
CoreNLP 3.6.0 not compatible with recent versions of Jollyday

### ISSUE THREAD

**Issue by rationalism** [stanfordnlp/CoreNLP#208]
When I downloaded Jollyday off Maven, I got this error and stack trace from CoreNLP:

https://gist.github.com/rationalism/300d00802906a6332c41a1006c756c3d

The exception seems to be caused by having downloaded the latest version (0.5.1). Downgrading to 0.4.7 fixed the problem, but 0.4.7 is four years old now.

**Comment by edesdan** [comment]
+1

**Comment by edesdan** [comment]
Hi I've got the same issue. It seems that the current version used in the project is 0.4.9, I tried with that, same problem. It works only with 0.4.7.

**Comment by gangeli** [comment]
The GitHub HEAD should be compatible with 0.4.9. Is it not? The 3.6.0 release is now fairly old and likely still requires 0.4.7; we should have a new release soon.

**Comment by edesdan** [comment]
Hi, I have tried the 3.6.0 with 0.4.9 and wasn't working. 3.6.0 with 0.4.7 is fine. Hope to see a new release to address this problem.

**Comment by J38** [comment]
There is a new release coming soon I will address this issue in the release!

________________________________

**Comment by J38** [comment]
The current version works with 0.4.9.
