### ISSUE TITLE
StanfordCoreNLP initialize takes really a long time

### ISSUE THREAD

**Issue by xsank** [stanfordnlp/CoreNLP#212]
`nlp = new StanfordCoreNLP(StanfordCoreNLP-chinese.properties);`
i use the StanfordCoreNLP to write a simple [chatbot](https://github.com/xsank/Shour), but it takes really a long time to new CoreNLP, always nearly 90 seconds.
will you consider about this? thank you.

**Comment by AngledLuffa** [comment]
Initialize CoreNLP and keep it running.

**Comment by xsank** [comment]
i have thought of this stuff, but don't you think it is a dirty way? If you think that the coreNLP is a demo just for study, ok whatever. But there is no one participle library running as slow as the coreNLP.

**Comment by sebschu** [comment]
The individual components in CoreNLP (segmenter, tagger, parser, NER, etc.) require learned models that have in total a size of a few hundred MB (or even more than one GB, depending on which parser you use). Whenever you start a new pipeline, these models have to be loaded and that takes time. As John suggested, you can initialize CoreNLP once and then keep it running -- then you don't have to load the models over and over again.
