### ISSUE TITLE
NER consistently tags the word "score" as 20.0

### ISSUE THREAD

**Issue by ppasupat** [stanfordnlp/CoreNLP#215]
To reproduce, run Stanford CoreNLP from the command line on the following input:

```
The student got a pretty good score.
The current score is 2 to 1.
an IQ score of 161
```

When the following command is run:

```
java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner -file input.txt
```

All occurrences of "score" are tagged as NUMBER with value 20.0.

**Comment by J38** [comment]
A `score` is 20 years.  But there is clearly a problem with not differentiating between:

`Four score and seven years ago` and `The student got a pretty good score.`

**Comment by manning** [comment]
I've done this for my weekend project....
