### ISSUE TITLE
-tlp properties ignored in DependencyParser constructor

### ISSUE THREAD

**Issue by tommy9114** [stanfordnlp/CoreNLP#216]
I was trying to train a dependency parser for Spanish with universal dependencies.
Following instruction in this page http://nlp.stanford.edu/software/nndep.shtml i just implemented a new language pack and passed its path as tlp parameters.
I'm using java api, so I build a Properties object with " tlp" keys and the full qualified path of my language pack.
At the end of the training (even if it seams to perform well on dev set) it perform very bad on the test set, so i started to debug and I found a couple of strange things in DependencyParser.java and Config.java file:
1)      this.language = config.language; (DependencyParser.java:line 123) 
here a language is assigned from the configuration (which decide to return the default one if no other one have been set). This is not a big issue but would be better if you give a mention of this parameter in the instruction page. 
2)language = props.containsKey("language")? getLanguage(props.getProperty("language")) : language;
    tlp = language.params.treebankLanguagePack(); (Config.java: 237-240)
Here the tlp object is assigned from the set language. This rise 2 problems:
**first**: given that no mention of the language parameter was given in the instructions then the standard language is chose and so also the associated language pack is returned in the last line.
**second**: the parameter "tlp" set in the properties object is never used, so is totally useless pass the class path as value of the key "tlp". This mean that you can only choose an already implemented LanguagePack (the ones listed in Language.java in which a TregexPoweredTreebankParserParams object is assigned to each supported language). 

Please let me know if i'm getting something wrong or if i missed somthing! 

Thanks a lot

Tommaso

**Comment by J38** [comment]
I have changed this in `Config.java` to attempt to overwrite the tlp set by the language with the user specified tlp.  Also future models will actually store the language and tlp used at training time and expect those same to be used.

I have recently trained a brand new Spanish dependency parser model for Stanford CoreNLP 3.9.0.  Switching between `edu.stanford.nlp.trees.international.spanish.SpanishTreebankLanguagePack` and `edu.stanford.nlp.trees.PennTreebankLanguagePack` doesn't seem to be affecting performance.

If you are interested, this is the command I used to train the new model:

`java -Xmx20g edu.stanford.nlp.parser.nndep.DependencyParser -trainFile /u/nlp/data/dependency_treebanks/UD/1.3/UD_Spanish-AnCora/es_ancora-ud-train.conllu -devFile /u/nlp/data/dependency_treebanks/UD/1.3/UD_Spanish-AnCora/es_ancora-ud-dev.conllu -model /path/to/new-model.ser.gz -embedFile /u/nlp/data/spanish/embeddings/SBW-vectors-300-min5.txt -embeddingSize 300`

I included new embeddings from http://crscardellino.me/SBWCE/

**Comment by J38** [comment]
These are the numbers I got for this new model I trained:

```
[main] INFO edu.stanford.nlp.parser.nndep.DependencyParser - Test File: /u/nlp/data/dependency_treebanks/UD/1.3/UD_Spanish-AnCora/es_ancora-ud-test.conllu
OOV Words: 2849 / 53594 = 5.32%
UAS = 85.7447
LAS = 83.1007
```
