### ISSUE TITLE
Outdated LICENSE.txt file?

### ISSUE THREAD

**Issue by reckart** [stanfordnlp/CoreNLP#220]
The README.md file in this repo states that

> The Stanford CoreNLP code is written in Java and licensed under the GNU General Public License (v3 or later).

However, the LICENSE.txt file still contains the GPL v2 license text.

It is unclear to the user which statement is correct.

**Comment by J38** [comment]
I have added a folder which has both versions, because our standalone distributions are version 2 and the main corenlp distribution is version 3.  To avoid confusion I will keep a copy of that LICENSE.txt file in the same location and update it to version 3.0 as well.
