### ISSUE TITLE
Lemmatization of 'dunno'

### ISSUE THREAD

**Issue by gangeli** [stanfordnlp/CoreNLP#224]
It seems that the Stanford Tokenizer now lemmatizes 'dunno' as 'du nno', but it would be nice if the lemmatizer also did something reasonable with this. Perhaps tokenizing as 'du n no' and lemmatizing as 'do not know'? Or 'du nno' as 'not know'? Are these sorts of contextual lemmatizations possible in our Morpha class?

Happy to poke around the Morpha file if anyone knows of a similar case I can use as reference.

**Comment by manning** [comment]
Iff the POS tags are assigned properly (as VBP RB VB) then the lemmatizer will now work. That's a big "iff" – it appears that the POS tagger at present normally doesn't get this right, but that's a different component to file a bug against. :)
