### ISSUE TITLE
JJR and JJS tokens are not lemmatized properly

### ISSUE THREAD

**Issue by DavidNemeskey** [stanfordnlp/CoreNLP#226]
When using the `tokenize,ssplit,pos,lemma` annotators, all tokens are lemmatized (e.g. `likes` becomes `like VBZ`), but comparative and superlative adjectives are not: e.g. `heavier` becomes `heavier JJR` and `best` is analyzed as `best JJS` (instead of `heavy JJR` and `good JJS`, respectively).

I was using the caseless POS model as my input was in lower case, but did not specify any other options.

**Comment by DavidNemeskey** [comment]
Any news on this?

**Comment by jeffrschneider** [comment]
A couple years has passed, and this remains broken. Again, lemmas do not work for adjectives in their comparative or superlative form.
