### ISSUE TITLE
the parser online demo issue

### ISSUE THREAD

**Issue by aalzehla** [stanfordnlp/CoreNLP#228]
the online demo is not working, please fix it. 
I want try something urgently.

**Comment by AngledLuffa** [comment]
It should be pretty easy to use at the command line if you download the
software and have Java installed.

**Comment by gangeli** [comment]
The demo (corenlp.run, I assume?) is back online. But, you should not rely on this demo being online at critical times -- remember that the demo is being maintained by an academic research group on a volunteer basis, and most of us aren't even awake at 6am.
