### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by linkerlin** [stanfordnlp/CoreNLP#23]
Add a maven building support would be nice.

**Comment by burtonator** [comment]
Was the pom.xml removed?  Looks like it's missing now. I'm trying to recreate it with dependencies for a consistent build plus so we can upload to our own maven repo.

**Comment by manning** [comment]
I believe all is good for maven building with the pom.xml now in the root directory with 3.7 / HEAD, so closing this unless there are problems to be reported....
