### ISSUE TITLE
Website doesn't work over HTTPS

### ISSUE THREAD

**Issue by mirosval** [stanfordnlp/CoreNLP#232]
Using duckduckgo.com takes me to the https version of https://stanfordnlp.github.io/CoreNLP/ and this does not load stylesheets and such because they have hardcoded addresses beginning with http:// 

You should replace 
`http://stanfordnlp.github.io/CoreNLP/css/syntax.css`
With:
`//stanfordnlp.github.io/CoreNLP/css/syntax.css`

this way the browser will use the appropriate protocol and load the files.

I would write a PR but I couldn't find the website on GitHub

**Comment by J38** [comment]
Thanks for pointing this out!  I will change it soon.

**Comment by willmoy** [comment]
Protocol relative URLs are deprecated.* Better to hard code https, as already done with some of the assets.

* e.g. http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by manning** [comment]
This has been fixed!
