### ISSUE TITLE
Some enhanced++ UD edges missing in online demo

### ISSUE THREAD

**Issue by nschneid** [stanfordnlp/CoreNLP#236]
I've been noticing that the [online demo](http://corenlp.run/) isn't finding some of the enhanced++ dependencies described in the [LREC 2016](http://www.lrec-conf.org/proceedings/lrec2016/pdf/779_Paper.pdf) paper, such as `nsubj:xsubj` in "Sue wants to buy a hat", the `nsubj` in "the boy who lived", the second `amod` in "the long and wide river", and the copy node/edges in "She flew to Bali or to Turkey". Is this just a problem with the rendering on the demo page, or are these not being produced?

**Comment by sebschu** [comment]
This seems to be a problem with the rendering on the demo page. When I run CoreNLP locally, I get all the expected edges. We'll look into it.

**Comment by sebschu** [comment]
Seems to be working now.

**Comment by nschneid** [comment]
I'm still getting the old behavior.

**Comment by sebschu** [comment]
Oh, it seems to have something to do with OpenIE. If you remove the OpenIE annotator, then it seems to work (which is obviously a bug).

**Comment by sebschu** [comment]
Now it seems to be working again for real but let me know if some edges are still missing.

**Comment by nschneid** [comment]
It's still not showing a copy node in "She flew to Bali or to Turkey". The other examples look good.

**Comment by sebschu** [comment]
Sorry for the late reply, but yes, the demo does not show  copy nodes explicitly. However, the self-loops always indicate that there is a copy node! This has always been the case and I don't think that we are going to change that as brat doesn't allow us to visualize copy nodes in a good way and we are not planning on developing our own visualization tools.
