### ISSUE TITLE
[Sentiment] - sentiment.model property not used

### ISSUE THREAD

**Issue by davidaparicio** [stanfordnlp/CoreNLP#239]
Hi!

I followed the documentation to retrain the sentiment model with a numHid=25

`java -mx8g edu.stanford.nlp.sentiment.SentimentTraining -numHid 25 -trainPath train.txt -devPath dev.txt -train -model model.ser.gz`

After 16 hours of training, I exported my model to my project, and I imported with this line:

`props.put("sentiment.model", "src/main/resources/model.ser.gz");`
or 
`props.setProperty("sentiment.model", "model.ser.gz");`

But the custom model is never used:

> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
> [main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
> [main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... 
> done [1.4 sec].
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator sentiment
> This movie doesn't care about cleverness, wit or any other kind of intelligent humor.
> Negative
> 1
> Those who find ugly meanings in beautiful things are corrupt without being charming.
> Negative
> 1
> There are slow and repetitive parts, but it has just enough spice to keep it interesting.
> Positive
> 3

I tried with `props.setProperty("sentiment.model", "test39randomName.ser.gz");`
And no error during the run.

My code is:
```
String paragraph = The quick brown fox jumps over the lazy dog;
Annotation document = new Annotation(paragraph);
Properties props = new Properties();
props.setProperty("annotators", "tokenize, ssplit, parse, sentiment");
props.setProperty("sentiment.model", "src/main/resources/model.ser.gz");
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
pipeline.annotate(document);
for (CoreMap sentence : document.get(CoreAnnotations.SentencesAnnotation.class)) {
            System.out.println("---");
            System.out.println(sentence);
            //System.out.println(sentence.get(SentimentCoreAnnotations.SentimentAnnotatedTree.class));
            Tree tree = sentence.get(SentimentCoreAnnotations.SentimentAnnotatedTree.class);
            int sentiment = RNNCoreAnnotations.getPredictedClass(tree);
            System.out.println(sentence.get(SentimentCoreAnnotations.SentimentClass.class));
            System.out.println(sentiment);
}

**Comment by sebschu** [comment]
I just tried running your code and when I change the path to the model to a non-existent path, I get an exception as expected. Which version are you using?

**Comment by J38** [comment]
When I run it looks for the specified path with the latest code.  Please let me know if there are still issues with this.
