### ISSUE TITLE
Lack of documentation on how to use CoreNLP server options

### ISSUE THREAD

**Issue by raphael0202** [stanfordnlp/CoreNLP#240]
On the documentation page (http://stanfordnlp.github.io/CoreNLP/corenlp-server.html), it's not clear how to specify the timeout and the port number of the CoreNLP server.
I've tried:
`timeout 30000`, `timeout=30000`, `--timeout 30000`, `--timeout=30000` before finding it's `-timeout 30000`. I think the way options should be specified must be present in the documentation.

**Comment by gangeli** [comment]
This is due to a difference between the last release (3.6.0) and the current HEAD of the GitHub repo. We'll update the documentation with the next release, but for now unfortunately it's confusing for one group or another either way...

**Comment by raphael0202** [comment]
Thank you for your response. I use the 3.6.0 release, and the documentation is inconsistent with the 3.6.0 argument syntax. So you won't have to update the documentation if it describes the syntax on the HEAD of the repo, right ?
