### ISSUE TITLE
Incorrect addition of unquoted null characters in JSON response from CoreNLP server

### ISSUE THREAD

**Issue by raphael0202** [stanfordnlp/CoreNLP#241]
I've used CoreNLP server for annotation tasks (tokenization, ssplit and pos).
However, sometimes the JSON response from the server is invalid as it contains unquoted null characters, even when there are no \x00 in the original text.
Here is the Python script that reproduces the error:

`    # coding: utf-8
    
    import json
    from urllib.parse import urljoin, quote
    import requests
    
    text = """I am overweight as well but wonder why it is just my left ankle and not my left.  Could it be thyroid issues as I have many symptoms of that as well???"""

    def annotate_corenlp(text, annotators="tokenize,ssplit,pos", output_format='json', url="http://localhost:9000"):
        payload_str = json.dumps({"annotators": annotators, "outputFormat": output_format})

        full_url = urljoin(url, quote(payload_str))
        r = requests.post(full_url, data=text.encode('utf-8'))

        content = r.content.decode('utf-8')
        return json.loads(content)
    
    annotate_corenlp(text)`

The JSON parser fails, because the \x00 are unquoted in the JSON response :
{"index":15,"word":"???","originalText":"???","lemma":"???","characterOffsetBegin":148,"characterOffsetEnd":151,"pos":"IN","ner":"O","speaker":"PER0","before":"","after":"\x00\x00"}

I've checked the request body, and the text is formatted properly, without \x00\x00 at its end.
Surprisingly, the error disappears when removing no-break spaces (\xa0) in the text.

**Comment by gangeli** [comment]
Is this using the HEAD of the GitHub repo, or the 3.6.0 release?

**Comment by raphael0202** [comment]
This is using the 3.6.0 release.

**Comment by gangeli** [comment]
OK, then this is a known bug, since fixed. The GitHub version of the code should work.

**Comment by raphael0202** [comment]
I'm now using the latest version of CoreNLP (on the HEAD branch), and I'm getting a JSON decoding error. If you try "It will cover %100", in 'tokens', there is indeed an unescaped '\x10':

{"index":3,"word":"cover","originalText":"cover","lemma":"cover","characterOffsetBegin":8,"characterOffsetEnd":13,"pos":"VB","ner":"O","speaker":"PER0","before":" ","after":" \x10"},{"index":4,"word":"0","originalText":"0","lemma":"0","characterOffsetBegin":15,"characterOffsetEnd":16,"pos":"CD","ner":"NUMBER","normalizedNER":"0.0","speaker":"PER0","before":" \x10","after":""}
