### ISSUE TITLE
Arabic dialect profiles

### ISSUE THREAD

**Issue by odaymard** [stanfordnlp/CoreNLP#242]
Hi ,
I have created profiles for arabic dialects
included
1-syrian
2-egyprian
i have tested it and it work correctly 
is it usefull for you?

**Comment by futurulus** [comment]
Hi @odaymard, could you clarify what you mean by "profiles"? Or can you upload what you have created to a GitHub project of your own so we can look at it? Support for Syrian dialect would indeed be useful for our Arabic tools.
