### ISSUE TITLE
How you can define your feature extraction patterns in NERFeatureFactory.java?

### ISSUE THREAD

**Issue by paktiger** [stanfordnlp/CoreNLP#243]

**Comment by paktiger** [comment]
I am using standfordNER to identify actor, movie. director etc from movie reviews. I have tokenized and tagged my review text. But i am fail to understand the working principle of properties define in prop file. Please anyone can tell me how can I understand these properties and define my own features ?

**Comment by J38** [comment]
There is an FAQ here for training your own models: http://nlp.stanford.edu/software/crf-faq.html

Also if you want to just build a dictionary with known actors, directors and movie titles you could try using RegexNER: http://nlp.stanford.edu/software/regexner.html
