### ISSUE TITLE
How to run StanfordCoreNLPServer with a different language?

### ISSUE THREAD

**Issue by bluepuma77** [stanfordnlp/CoreNLP#245]
I can run the regular command line version of CoreNLP successful with a different language set:

```
java -mx4g -cp "stanford-corenlp-full-2015-12-09/*:stanford-german-2016-01-19-models.jar" \
edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,parse \
-props StanfordCoreNLP-german.properties -file german.txt -outputFormat text
```
Then I tried StanfordCoreNLPServer with the same jar, but it only processes English language:

```
java -mx6g -cp "stanford-corenlp-full-2015-12-09/*:stanford-german-2016-01-19-models.jar" \
edu.stanford.nlp.pipeline.StanfordCoreNLPServer -props StanfordCoreNLP-german.properties
```

How do I use StanfordCoreNLPServer with a different language set?

**Comment by J38** [comment]
In the current version of the code there is more support for using the server on foreign languages.  The main page describes how to build a jar from the current code.

If you issue a command to the server like this:

`wget --post-data '<insert german text here' 'localhost:9000/?properties={"pipelineLanguage":"de", "outputFormat":"json"}' -O -`

The server should load the proper German resources...
