### ISSUE TITLE
How do I get the score distribution value for CoreNLP Sentiment?

### ISSUE THREAD

**Issue by hassanz** [stanfordnlp/CoreNLP#246]
I have setup CoreNLP server on my ubuntu instance and it works ok. I more interested in Sentiment module and currently I get is

```
{
sentimentValue: "2",
sentiment: "Neutral"
}
```

What I need is score distribution value, as you see here: http://nlp.stanford.edu:8080/sentiment/rntnDemo.html

`"scoreDistr": [0.1685, 0.7187, 0.0903, 0.0157, 0.0068]`

What am I missing or How do I get such data ?

Thanks

**Comment by hassanz** [comment]
@gangeli Since you helped me earlier about similar issue maybe you can provide some info on this one as well. Thanks :)

**Comment by pcrutchl** [comment]
@hassanz Were you able to figure this out? I'm trying to do the same thing myself.

**Comment by hassanz** [comment]
Nope, no luck. I kinda parked this project for now. I'll update this thread
if I figure it out. Please do the same as well :)

Cheers,

**Comment by J38** [comment]
I'll try to add some code to allow for this soon.  Basically I need to make a few small changes to:

edu.stanford.nlp.pipeline.JSONOutputter
edu.stanford.nlp.neural.rnn.RNNCoreAnnotations

and we should be able to have the JSON include the full range of labels.

**Comment by pcrutchl** [comment]
@J38 Thanks, sounds great!

**Comment by dandelionred** [comment]
Any progress on the issue? I'm trying to use the CoreNLP server in my project and I heavily miss the ability to get the class distribution values in sentiments.

**Comment by bwang12** [comment]
Same here, @J38 any help is greatly appreciated here!

**Comment by J38** [comment]
I will try to look into this more soon, but you should try looking at the `getPredictions()` method in `edu.stanford.nlp.neural.rnn.RNNCoreAnnotations` and looking over the code in `edu.stanford.nlp.sentiment.SentimentPipeline` , particularly `setSentimentLabels`.

It's possible if you apply that method to the tree stored for the sentence with the SentimentCoreAnnotations.SentimentAnnotatedTree.class you can get back the predictions.

**Comment by loretoparisi** [comment]
+1

**Comment by loretoparisi** [comment]
@J38 any progress using the `RNNCoreAnnotations` and the `JSONOutputter` to get the score distribution?

**Comment by J38** [comment]
Ok I added this to the JSON output under the "sentimentDistribution" key.

**Comment by duichwer** [comment]
Hi, 
I'm not sure if this is the right place for adding my issue, but I think it is directly related.

I receive the a json ouput with wrong parsed double values.
```
      "sentimentValue": "3",
      "sentiment": "Positive",
      "sentimentDistribution": [
        0,01239421277441,
        0,05552580544032,
        0,42735414341245,
        0,45560394094911,
        0,04912189742371
      ],
```
Shouln't there be adecimal point? 
0,01**.**239421277441

**Comment by AngledLuffa** [comment]
For whatever reason it's giving you a European locale

**Comment by loretoparisi** [comment]
@AngledLuffa this is due to the locale settings when you startup Java not to CoreNLP. To solve it it is easier as doing "-Duser.language=en -Duser.country=US Default"

**Comment by duichwer** [comment]
@loretoparisi thanks a lot. With those parameters added to my start script. The CoreNLP works perfect and give the correct results.

**Comment by lingxiangwu** [comment]
Hi I set up a CoreNLP server following Stanza. 
```
with CoreNLPClient(annotators=['tokenize','ssplit','sentiment'], outputFormat = "json", timeout=30000, memory='16G', endpoint="http://localhost:6002") as client:
    # submit the request to the server
    ann = client.annotate(text)
```
However, I can only get `sentiment` but no `sentimentDistribution `. Is there anything can help? THX

**Comment by AngledLuffa** [comment]
output_format not outputFormat
