### ISSUE TITLE
Stanford CoreNLP server seems to ignore port option

### ISSUE THREAD

**Issue by kelvinguu** [stanfordnlp/CoreNLP#247]
As of commit `e3cf455f`, this is what happens when I try to specify a port:

```
$ java -mx10g -cp "*:lib/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer 9005
[main] INFO CoreNLP - Starting server...
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9000
```

**Comment by gangeli** [comment]
Ah, the documentation is out of sync with the GitHub code (it's still tracking 3.6.0). The port option is specified with the command-line flag `-port 9005`.
