### ISSUE TITLE
Make TokenRegex and Semgrex usable with externally annotated data?

### ISSUE THREAD

**Issue by raphael0202** [stanfordnlp/CoreNLP#251]
I've been using CoreNLP extensively lately, and there is a feature I really miss.
I usually use multiple NLP tools for tokenization and annotation, I notably use a custom entity tagger.
However, it is difficult to use TokenRegex and Semgrex on data which were not annotated with CoreNLP, due to the strong dependencies of TokenRegex and Semgrex on CoreNLP internal classes.
Would it be possible to use these 2 tools with externally annotated data? Or more broadly, to import externally annotated data and convert them into CoreNLP internal classes?
A JSON import would be great for instance.

**Comment by AngledLuffa** [comment]
There's now a protobuf interface which lets you pass in outside annotated data, along with a python interface in stanza which makes use of that protobuf interface.

https://stanfordnlp.github.io/stanza/client_regex.html
