### ISSUE TITLE
Address parsing 

### ISSUE THREAD

**Issue by moinsy** [stanfordnlp/CoreNLP#252]
Hello,
   I need to classify the address text into two classes, one class is LOCALITY which categorises locality, area, neighbourhood into it and another class which contains the rest of the address. I have the data of locality , but need to know how to go about it,how to train the model to categorise LOCALITY, which software to use, either use NER and train location label or use regexNER?   

Thank you!

**Comment by J38** [comment]
I would suggest using RegexNER for this task.
