### ISSUE TITLE
Failed to start corenlp.service: Unit corenlp.service not found.

### ISSUE THREAD

**Issue by DeliciousHair** [stanfordnlp/CoreNLP#258]
I'm probably missing something stupid easy, but I tried creating a dedicated core nlp server as instructed [here](http://stanfordnlp.github.io/CoreNLP/corenlp-server.html#dedicated-server). When I try to start it get:

```
$ sudo service corenlp start
Failed to start corenlp.service: Unit corenlp.service not found.
```

Any ideas what I may have missed?

**Comment by DeliciousHair** [comment]
Nevermind, put the file in the wrong place. Oops. :-)

**Comment by erindb** [comment]
Which file was in the wrong place? And where was it supposed to go?

**Comment by DeliciousHair** [comment]
Supposed to go is relative I think, but in my case I had everything stuck into one folder under `/opt`, which was causing problems with the way in which the sentiment and POS tagger libraries were being loaded.  What I have now is:

    /opt/CoreNLP
    /opt/stanford-postagger

which allows me to get the server up and running via:

    java -mx8g -cp "/opt/CoreNLP/javanlp-core.jar:/opt/CoreNLP/models/*:/opt/CoreNLP/lib/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer

Owing to my usage requirements, this was a better solution than creating a service, but the extra step is trivial.
