### ISSUE TITLE
Augment Spanish NER data with CoNLL

### ISSUE THREAD

**Issue by hans** [stanfordnlp/CoreNLP#261]
Rebuild NER models with [CoNLL data](http://www.cnts.ua.ac.be/conll2003/ner/).
(would assign this to myself if I could!)

**Comment by manning** [comment]
Evidence that our lack of NER training data does cause issues: http://stackoverflow.com/questions/42162825/how-can-i-expand-stanford-corenlp-spanish-model-dictionary

**Comment by J38** [comment]
I'm assuming this is resolved since we built so many new Spanish models over the summer.
