### ISSUE TITLE
ChineseSegmenterAnnotator / ChineseStringUtils NullPointerException in multi-threaded use

### ISSUE THREAD

**Issue by pauldoo** [stanfordnlp/CoreNLP#263]
When using `ChineseSegmenterAnnotator` in a multi-threaded environment a NullPointerException can sometimes occur.  The root cause seems to be that `ChineseStringUtils.processColons()` is not thread safe due to lazy initialisation of static members.

Current master revision can throw an NPE on line 300:
https://github.com/stanfordnlp/CoreNLP/blob/6ea6a2e9e9b58b41827ebbf581ca2239aeebb52f/src/edu/stanford/nlp/wordseg/ChineseStringUtils.java#L300

The issue is the (thread-)unsafe initialisation of `colonsPat` a few lines earlier.  The same issue appears to be present for `colonsWhitePat`.

**Comment by manning** [comment]
Closing assuming fixed!
