### ISSUE TITLE
Preload models on server start?

### ISSUE THREAD

**Issue by giorgio79** [stanfordnlp/CoreNLP#264]
Would you add an option to preload models on server start with properties perhaps?

I would like to avoid loading hte models on first use.

Ref:
"The first use will be slow to respond while models are loaded – it might take 30 seconds or so, but after that the server should run quite quickly.)" http://stanfordnlp.github.io/CoreNLP/corenlp-server.html

**Comment by gangeli** [comment]
This does actually already exist in the GitHub version of the code. Simply specify `-lazy false` when starting the server, and it should (in theory) pre-load the common models.

**Comment by edesdan** [comment]
Hi, is it already included in the 3.6.0 released version?

**Comment by J38** [comment]
No this functionality is not in the 3.6.0 release.  It is available in the current version on the GitHub.  There are instructions on the main page for creating a jar from the current code.
