### ISSUE TITLE
German corenlp server defaulting to english models

### ISSUE THREAD

**Issue by aliabbasjp** [stanfordnlp/CoreNLP#269]
I use the following command to serve a  corenlp server for German language models which are downloaded as jar in the classpath , but it does not output german tags or parse but loads only english models:

`     java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer   -props ./german.prop
`
german.prop contents:

  ```
  annotators = tokenize, ssplit, pos, depparse, parse
    
    tokenize.language = de
    
    pos.model = edu/stanford/nlp/models/pos-tagger/german/german-hgc.tagger
    
    ner.model = edu/stanford/nlp/models/ner/german.hgc_175m_600.crf.ser.gz
    ner.applyNumericClassifiers = false
    ner.useSUTime = false
    
    parse.model = edu/stanford/nlp/models/lexparser/germanFactored.ser.gz
    depparse.model = edu/stanford/nlp/models/parser/nndep/UD_German.gz

```

client command:
```

    wget --post-data ' Meine Mutter ist aus Wuppertal' 'localhost:9000/?properties"="{"tokenize.whitespace":"true","annotators":"tokenize, ssplit, pos, depparse, parse","outputFormat":"text","tokenize.language" :"de" ,
     "pos.model":" edu/stanford/nlp/models/pos-tagger/german/german-hgc.tagger",
    "depparse.model" : "edu/stanford/nlp/models/parser/nndep/UD_German.gz",
    "parse.model" : "edu/stanford/nlp/models/lexparser/germanFactored.ser.gz"
    
     }' -O -

```
I get following incorrect output:
  `

     {"dep":"dep","governor":4,"governorGloss":"aus","dependent":5,"dependentGloss":"Wuppertal"}],"openie":[{"subject":"Wuppertal","subjectSpan":[4,5],"relation":"is ist aus of","relationSpan":[2,4],"object":"Meine Mutter","objectSpan":[0,2]}],"tokens":[{"index":1,"word":"Meine","originalText":"Meine","lemma":"Meine","characterOffsetBegin":1,"characterOffsetEnd":6,"pos":"NNP","ner":"PERSON","speaker":"PER0","before":" ","after":" "},{"index":2,"word":"Mutter","originalText":"Mutter","lemma":"Mutter","characterOffsetBegin":7,"characterOffsetEnd":13,"pos":"NNP","ner":"PERSON","speaker":"PER0","before":" ","after":" "},{"index":3,"word":"ist","originalText":"ist","lemma":"ist","characterOffsetBegin":14,"characterOffsetEnd":17,"pos":"NN","ner":"O","speaker":"PER0","before":" ","after":" "},{"index":4,"word":"aus","originalText":"aus","lemma":"aus","characterOffsetBegin":18,"characterOffsetEnd":21,"pos":"NN","ner":"O","speaker":"PER0","before":" ","after":" "},{"index":5,"word":"Wuppertal","originalText":"Wuppertal","lemma":"Wuppertal","characterOffsetBegin":22,"characterOffsetEnd":31,"pos":"NNP","ner":"LOCATI100%[==========================================================================>] 2,
`

in the server log I see it loads english models eventhough it lists german models on startup:
```

    pos.model=edu/stanford/nlp/models/pos-tagger/ge...
    parse.model=edu/stanford/nlp/models/lexparser/ger...
    tokenize.language=de
    depparse.model=edu/stanford/nlp/models/parser/nndep/...
    annotators=tokenize, ssplit, pos, depparse, parse
    Starting server on port 9000 with timeout of 5000 milliseconds.
    StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9000
    [/203.:61563] API call w/annotators tokenize,ssplit,pos,depparse
    Die Katze liegt auf der Matte.
    [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
    [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
    [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
    [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
    Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.5 sec].
    [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator depparse
    Loading depparse model file: edu/stanford/nlp/models/parser/nndep/english_UD.gz ...
    PreComputed 100000, Elapsed Time: 1.396 (s)

```
The following question for same error in french models also points to the same problem but even after following , it does not resolve the problem for the server case, I am able to get the correct output without using the server and just using the `edu.stanford.nlp.pipeline.StanfordCoreNLP command` , it is the server command `edu.stanford.nlp.pipeline.StanfordCoreNLPServer` which defaults to english:
http://stackoverflow.com/questions/36223002/french-dependency-parsing-using-corenlp#

**Comment by J38** [comment]
This issue has been resolved in the soon to be released Stanford CoreNLP 3.7.0.  If you use
"pipelineLanguage": "de" in the properties of the wget request it will automatically use default German properties and load the correct models.
