### ISSUE TITLE
DEFAULT_SENTENCE_DELIMS

### ISSUE THREAD

**Issue by EasonSun** [stanfordnlp/CoreNLP#272]
Hi Group,

Thank you first for this open source contribution. It makes make my life much better.

The problem I have right now is that it seems not possible to split sentences with no punctuation in between, like two sentences glued together with the first having no period. Can the DocumentParser smartly spot where to break the sentences? 

I saw[ this line](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/process/DocumentPreprocessor.java#L63) so I doubt if it is possible.

Thank you.

**Comment by manning** [comment]
We don't have anything for this at present. It's a possible research project but not an easy thing to do since it needs to be content based. But no current plans on doing this.

**Comment by EasonSun** [comment]
Thank you!
