### ISSUE TITLE
How to pick a specific in memory loaded NER model?

### ISSUE THREAD

**Issue by jplu** [stanfordnlp/CoreNLP#275]
Hello,

I wanted to know if it was possible to select which NER model we would like to use even when the pipeline is already loaded in memory. For example, let's assume I create a pipeline by using the NERCombiner and loading the 3 provided models:

```
edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz
edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz
edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz
```

With the following piece of code:

```
Properties props = new Properties();
props.put("annotators", "tokenize, ssplit, pos, lemma, ner, parse, mention, coref");
props.put("coref.md.type", "rule");
props.put("coref.mode", "statistical");
props.put("coref.doClustering", "true");
props.put("ner.model", "edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz,edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz,edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz");
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
```

Now every time I want to annotate a text, the 3 models will be applied. Now what I would like to do is to use only the ```3class``` model but without recreating the pipeline and reloading everything in memory. As in my case I use the statistical coref, it takes a moment all the time to load all its stuff in memory, and I would like to avoid this all the time. Is there any way to do that?

Thanks in advance for any help!

**Comment by J38** [comment]
I built the pipeline with your full settings in 34 seconds.  Then I changed props for "ner.model" to just use the one model and I rebuilt the pipeline and it only took 1 second and it only reloaded the ner related elements.

**Comment by jplu** [comment]
Ok then changing only the "ner.model" seems to be enough. Thanks a lot :)
