### ISSUE TITLE
Refactor build system towards Maven

### ISSUE THREAD

**Issue by burtonator** [stanfordnlp/CoreNLP#288]
As an outsider I'm somewhat confused as to the build system.

Admittedly I'm not a big proponent of Gradle as all the larger project I work on use Maven.

That said, I think moving to EITHER Gradle or Maven, with included depenencies, would be better than what we have now.

Storing .jars inline in the repo is generally not a good idea.    It also has the problem of not being able to compute full transitive dependencies which both gradle and maven can do just fine. 

I think the current strategy is to have a README in the lib directory with all the depenencies

Couldn't this be replaced with a full maven/gradle build with the dependencies included?

This almost works with pom-full.xml but needs to be improved a bit to add the remaining dependencies.  

Sees straight forward.

I think the problem now, from an outsiders perspective, is that to get a custom CoreNLP build (we will need to run a fork for a while until you accept our PRs) is difficult without maven.

Anyway. I think having this as a SIDE build system, along with the current one, shouldn't be too hard.  

Thoughts?

Thanks!

**Comment by J38** [comment]
Ok this sounds great thanks for the work!  I would like to review this situation some more since I don't have a deep knowledge of Ant, Maven, etc...but I think your proposal sounds good.  I will probably add in your changes this week or next.

**Comment by J38** [comment]
Ok the pom.xml currently seems to work.  To get "mvn test" to work, you need to download and install the latest version of the Spanish models jar.  There are instructions for this on the main GitHub page.
