### ISSUE TITLE
Server doesn't start because of missing .js file (CoreNLP 3.7.0 (beta))

### ISSUE THREAD

**Issue by EmilStenstrom** [stanfordnlp/CoreNLP#290]
```
~/Projects/corenlp $ java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - using SR parser: edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP -     Threads: 8
[main] INFO CoreNLP - Starting server...
java.io.IOException: Unable to open "edu/stanford/nlp/pipeline/demo/corenlp-parseviewer.js" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:478)
	at edu.stanford.nlp.io.IOUtils.readerFromString(IOUtils.java:615)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$FileHandler.<init>(StanfordCoreNLPServer.java:448)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.run(StanfordCoreNLPServer.java:1198)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1274)
[Thread-0] INFO CoreNLP - CoreNLP Server is shutting down.
```

I'm using macOS 10.12 and have just downloaded and unzipped the files from your website.

**Comment by EmilStenstrom** [comment]
Version 3.6 works fine:

```
~/Projects/corenlp $ java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer
-- listing properties --
Starting server on port 9000 with timeout of 5000 milliseconds.
StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9000
```

**Comment by gangeli** [comment]
I've pushed a fix for this, but we'll need to rebuild the *.jar file before it takes effect.

**Comment by EmilStenstrom** [comment]
@gangeli Thanks! Can I suggest also adding a test for this. Seems like something that should be considered a "public API".

**Comment by EmilStenstrom** [comment]
Are you sure 8ad088f was the right commit? I don't see any mention of any js file there?

**Comment by gangeli** [comment]
Right, sorry -- we don't release the scripts to make the releases. Which makes this commit (and the subsequent merge) look like a big confusing NOOP. The fix involved adding the js file "entry-points" to the script that goes through the source files to jar up the ones which are relevant for the release. @J38 are we updating the beta as bug reports come in?

**Comment by J38** [comment]
Sure the idea is to have a 30-day period after the beta release to make bug fixes which would be applied to the final Maven release.

**Comment by manning** [comment]
@EmilStenstrom: If you want a quick fix for this so it works for you, you could just grab the file from:

    https://github.com/stanfordnlp/CoreNLP/tree/master/src/edu/stanford/nlp/pipeline/demo

and insert it into the CoreNLP models jar....
