### ISSUE TITLE
CoreNLP 3.7-beta kpb models

### ISSUE THREAD

**Issue by sergey-tihon** [stanfordnlp/CoreNLP#293]
New kpb models uses `:` (colon)  in files names that is not supported by Win file system
![image](https://cloud.githubusercontent.com/assets/1197905/19885140/25503c9c-a02e-11e6-9e74-1a9e723488c0.png)
Is possible to rename those files?

It slightly affects [Stanford.NLP.NET](https://github.com/sergey-tihon/Stanford.NLP.NET)
`stanford-corenlp-3.7.0-models.jar` cannot be unzipped using standard .NET API
![image](https://cloud.githubusercontent.com/assets/1197905/19885263/b5f4b57a-a02e-11e6-9510-4cce773c1942.png)
https://ci.appveyor.com/project/sergey-tihon/stanford-nlp-net/build/0.0.1.56#L65

`7zip` for example automatically rename all files (that also may lead to confusion)
![image](https://cloud.githubusercontent.com/assets/1197905/19885293/dfb00504-a02e-11e6-91e2-887005dbed79.png)

**Comment by J38** [comment]
Sure we'll rename them, thanks for pointing this out.  I generally just test things on Unix!

**Comment by J38** [comment]
We are still aware of this issue but there are some complications with changing the names.  Some things are hard coded to use that naming convention with the ":" and some resources have to be rebuilt to use a new naming convention.  We will fix this at some point soon though!

**Comment by sergey-tihon** [comment]
I see that you releases `3.7.0`, is this issue fixed in release?

**Comment by J38** [comment]
Hi this issue is finally fixed.  We will probably release Stanford CoreNLP 3.9.2 fairly soon as an update to include this!
