### ISSUE TITLE
How to create Chinese Sentiment Annotator?

### ISSUE THREAD

**Issue by ryh95** [stanfordnlp/CoreNLP#297]
Stanford Core NLP software has an annotator of sentiment , but it only supports for English , I want to create an sentiment annotator for Chinese . What should I do ? Can someone give me some advice on it , thank you very much!

**Comment by gangeli** [comment]
Unfortunately, we do not have any trained model for Chinese sentiment analysis. To train a Chinese model, you'd need to construct a sentiment treebank similar to the Stanford Sentiment Treebank (http://nlp.stanford.edu/sentiment/treebank.html) and then retrain the sentiment model, but this is not a small task.

**Comment by loretoparisi** [comment]
@gangeli it's not clear to me how to write brand new `STree.txt` and `SOStr.txt` files starting from a new annotated dataset of sentences. Thanks!
