### ISSUE TITLE
what is TokensRegexNERAnnotator Annotation name?

### ISSUE THREAD

**Issue by flystarhe** [stanfordnlp/CoreNLP#298]
hi, TokensRegexNERAnnotator ? Annotation name
thanks

**Comment by J38** [comment]
The name is "regexner".

**Comment by flystarhe** [comment]
sorry, who is " RegexNERAnnotator"? if "regexner" is "TokensRegexNERAnnotator".
i know "regexner" is name of "RegexNERAnnotator"

**Comment by flystarhe** [comment]
or where find it @J38

**Comment by flystarhe** [comment]
Can you give me a check list, AnnotatorClass mapping
thanks
