### ISSUE TITLE
3.4 Release missing classes for SR Parser

### ISSUE THREAD

**Issue by Necrolis** [stanfordnlp/CoreNLP#30]
When setting `parse.model=edu/stanford/nlp/models/srparser/englishSR.ser.gz` and using the SR models from the site, there is a `java.lang.ClassNotFoundException` being thrown for `edu.stanford.nlp.parser.shiftreduce.BasicFeatureFactory`. 

Upon inspection it looks like the class files for `BasicFeatureFactory` & `DistsimFeatureFactory` were not included in the build/jar; this renders the SR parser unusable from 3.4 (which is a bit of a pain as we use the .Net bindings).

**Comment by hamedkhanpour** [comment]
I have downloaded recent version of the Stanford_corenlp to run Constituacy parser. I found that "srparser/englishSR.ser.gz" is not included in the models. would you please tell me what would be the solution?

**Comment by hans** [comment]
You need to have the shift-reduce parser models JAR on your classpath. Direct link to the 3.5.1-compatible version is here: http://nlp.stanford.edu/software/stanford-srparser-2014-10-23-models.jar

You can find the latest model downloads on the [CoreNLP homepage](http://nlp.stanford.edu/software/corenlp.shtml#History).
