### ISSUE TITLE
Build Failure while executing tests cases

### ISSUE THREAD

**Issue by samruddh-singhal** [stanfordnlp/CoreNLP#300]
I have installed java & ant and performed following steps to compile CoreNLP from github repo-  
#java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

#ant -version
Apache Ant(TM) version 1.9.6 compiled on July 8 2015

#git clone https://github.com/stanfordnlp/CoreNLP.git
#cd CoreNLP
#ant clean
BUILD SUCCESSFUL

#ant compile
BUILD SUCCESSFUL

#ant test

[junit] Testsuite: edu.stanford.nlp.international.spanish.SpanishUnknownWordSignaturesTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec
    [junit]
    [junit] Testsuite: edu.stanford.nlp.international.spanish.process.SpanishTokenizerTest
    [junit] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.051 sec
    [junit]
    [junit] Testcase: testIr(edu.stanford.nlp.international.spanish.process.SpanishTokenizerTest):      FAILED
    [junit] Number of tokens doesn't match reference 'tengo que irme ahora' expected:<5> but was:<4>
    [junit] junit.framework.AssertionFailedError: Number of tokens doesn't match reference 'tengo que irme ahora' expected:<5> but was:<4>
    [junit]     at edu.stanford.nlp.international.spanish.process.SpanishTokenizerTest.testOffset(SpanishTokenizerTest.java:26)
    [junit]     at edu.stanford.nlp.international.spanish.process.SpanishTokenizerTest.testIr(SpanishTokenizerTest.java:42)
    [junit]
    [junit]

BUILD FAILED
/CoreNLP/build.xml:146: Tests failed

Any suggestions how to fix this ?

**Comment by J38** [comment]
Are you using the latest models jars?  You can see download links for all of them on the main GitHub page.

**Comment by J38** [comment]
You need to have the current Spanish models jar in your CLASSPATH to avoid this issue.  The download link for that jar is on the main GitHub page.

**Comment by samruddh-singhal** [comment]
Thanks for your response, I will try as per your suggestion.
