### ISSUE TITLE
Fails to identify compound nouns

### ISSUE THREAD

**Issue by riyadparvez** [stanfordnlp/CoreNLP#302]
corenlp fails to identify common compound nouns like "hot dogs". For example, "I like hot dogs." - in this sentence corenlp identifies relationship between hot dogs as "amod(dogs, hot)", whereas it should be "compound(dogs, hot)"

**Comment by J38** [comment]
Thanks for pointing out this issue.  Unfortunately the models don't always do the correct thing, but we will look into improving the performance on cases like this!
