### ISSUE TITLE
How to correctly import in Intellij?

### ISSUE THREAD

**Issue by soundlicious** [stanfordnlp/CoreNLP#303]
Hello,

I import the jar file via dependencies windows of Intellij. 
I import them (stanford-english-corenlp-models-current & stanford-corenlp-models-current) as classes.
Problem, the package Pipeline only contain .demo...

import edu.stanford.nlp.pipeline.demo.*;

I would like to have the Annotation import.
Also nlp doesn't contain .ling or .util.

What do i have to do to get all the import needed by this example : http://stackoverflow.com/a/19909327 ?

**Comment by J38** [comment]
You need to import stanford-corenlp-3.7.0.jar as well.

Download available here: http://stanfordnlp.github.io/CoreNLP/

**Comment by soundlicious** [comment]
Thanks, work perfectly indeed...My bad.
