### ISSUE TITLE
Use Sentiment analysis system to test a lot of sentences will spend long time

### ISSUE THREAD

**Issue by liuyunfang** [stanfordnlp/CoreNLP#306]
I think sentiment analysis system of stanfordCoreNlp with high accuracy, But I found if I test a lot of sentences, long time would be spent. I have not  find solution for this problem, I hope someone will help me! Thank you very much!

**Comment by J38** [comment]
Ok I will look into modifying the sentiment annotator to run in multi-threaded mode.

**Comment by AngledLuffa** [comment]
It will now run in multi-threaded mode for the next release.

It should be pointed out that the time spent parsing to get the tree in the first place is significantly higher than the time spent in the sentiment annotator, though.
