### ISSUE TITLE
Unable to open "edu/stanford/nlp/models/kbp/wikidict.tab.gz"

### ISSUE THREAD

**Issue by neilnelson** [stanfordnlp/CoreNLP#308]
On Firefox, URL http://localhost:9000/, click on the white area in the annotators box to a get a drop down. 'Select wikipedia entities'. The following error is obtained.

java.lang.RuntimeException: edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/models/kbp/wikidict.tab.gz" as class path, filename or URL

All the other options appear to work. There is no '\*wikidict\*' file in the distribution.

**Comment by gangeli** [comment]
The wikidict models are in the (larger) English models jar. You can download the latest models [here](http://nlp.stanford.edu/software/stanford-english-corenlp-models-current.jar) (warning: ~1GB download).

**Comment by neilnelson** [comment]
Found it. Thank you for the solution.
