### ISSUE TITLE
StanfordCoreNLPClient does not terminate when run as a command line client

### ISSUE THREAD

**Issue by ivan-zapreev** [stanfordnlp/CoreNLP#309]
Running CoreNLP 3.6.0 on Max OS X EI Capitan v 10.11.6
The same behavior is observed with CoreNLP 3.7.0 (beta)
```
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

Starting server as:
```
$java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9010
-- listing properties --
port=9010
Starting server on port 9010 with timeout of 5000 milliseconds.
StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9010

```

Starting client as:
```
$java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLPClient -props StanfordCoreNLP-chinese.properties -annotators tokenize,ssplit -file ~/Tmp/input_chinese.txt -outputDirectory ~/Tmp/ -outputFormat text
Processing file /Users/zapreevis/Tmp/input_chinese.txt ... writing to /Users/zapreevis/Tmp/input_chinese.txt.out
Annotating file /Users/zapreevis/Tmp/input_chinese.txt
done.
```

After  **done.** is printed, the processed text is indeed written into */Users/zapreevis/Tmp/input_chinese.txt.out*, yet the client does not quite but keeps running blocking the console.

**Comment by ivan-zapreev** [comment]
Is it just me or this is not a bug? 🎱

**Comment by manning** [comment]
You are right. This is a bug. Not sure how to fix it. Will ask around, suggestions welcome.

**Comment by gangeli** [comment]
I believe I've fixed this. As an unrelated comment: to make calls against your own server, you should additionally specify the property (or command-line flag) `-backends localhost:9010`. This is a comma-separated list of "protocol://hostname:port" strings (defaulting to http:// and port 80); annotations will cycle through annotating on these backends. This now defaults to localhost:9000.
