### ISSUE TITLE
Unable to instantiate TokensRegexAnnotator under windows

### ISSUE THREAD

**Issue by chesterm8** [stanfordnlp/CoreNLP#311]
The constructor of `TokensRegexAnnotator` relies on `PropertiesUtils.getStringArray` to extract the rules property. This in turn uses `MetaClass.cast` to cast the property string to an array. This then delegates to `StringUtils.decodeArray`, which turns the string `C:\Users\BELLCH~1\AppData\Local\Temp\bill-ie5804201486895318826regex_rules.txt` (a valid windows filepath) into `["C:UsersBELLCH~1AppDataLocalTempbill-ie5804201486895318826regex_rules.txt"]` as it skips over the backslash characters (`chars[i] == '\\'`).

**Comment by manning** [comment]
Actually, I don't think this is a bug. Isn't this just that you need to escape backslash characters by writing them as a double backslash, just like everywhere else in Java? That is, you have to start with:

C:\\Users\\BELLCH~1\\AppData\\Local\\Temp\\bill-ie5804201486895318826regex_rules.txt

**Comment by chesterm8** [comment]
I assume that you have double `\\` characters in there and github formatting is hiding them from me? 

Regardless, I do think that it is a bug. I can initialise `TimeAnnotator` by passing `sutime.rules` with the string returned by the native java `File.getAbsolutePath()`, I would expect to be able to initialise any other `.rules` annotators the same way - having to add backslashes into a file path in such a situation is unintuitive.

It looked to me like the issue is the handling of String -> Array of String conversion, for example the `TimeAnnotator` ends up delegating down to `GenericTimeExpressionPatterns.createExtractor()` which uses the following: `StringUtils.split(options.grammarFilename, "\\s*[,;]\\s*")` to split a string into an array of strings.

**Comment by chesterm8** [comment]
Apologies for the multitude of pull requests - https://github.com/stanfordnlp/CoreNLP/pull/331 is a correct and complete one which fixes the behaviour and shows what was broken in the first place through unit tests.

**Comment by manning** [comment]
The code here is certainly a mess: it's not clear why you have to go through Metaclass.cast in the first place, since you know you have a String and the hand-written parser in StringUtils.decodeArray looks like it has weird holes in it to me....

**Comment by manning** [comment]
I added in some more tests with your original Windows file example. Effectively now you are getting \ treated as an escape character in a bare String but not inside a quoted portion. I hope that seems right? At any rate, going with this for now....
