### ISSUE TITLE
Stanford Core NLP gets tokens lost with: '-annotators tokenize,ssplit'

### ISSUE THREAD

**Issue by ivan-zapreev** [stanfordnlp/CoreNLP#314]
When running version 3.6.0 for Chinese, I see that when doing tokenization and sentence splitting some characters get disappeared! 

Server:
`$java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9010`

Client:
`$java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLPClient -props StanfordCoreNLP-chinese.properties -annotators tokenize,ssplit -file ~/Tmp/input_chinese.txt -outputDirectory ~/Tmp/ -outputFormat text -port 9010`

Content of the Chinese inptut text file:
`$cat ~/Tmp/input_chinese.txt`
`巴拉特 说 ： 「 我们 未 再 获得 任何 结果 。 」`
`《金融时报》周三`
`$`

The result is:
 `$cat ~/Tmp/input_chinese.txt`
`Sentence #1 (10 tokens):`
`巴拉特 说 ： 「 我们 未 再 获得 任何 结果 。`
`[Text=巴拉特 CharacterOffsetBegin=0 CharacterOffsetEnd=3]`
`[Text=说 CharacterOffsetBegin=4 CharacterOffsetEnd=5]`
`[Text=： CharacterOffsetBegin=6 CharacterOffsetEnd=7]`
`[Text=我们 CharacterOffsetBegin=10 CharacterOffsetEnd=12]`
`[Text=未 CharacterOffsetBegin=13 CharacterOffsetEnd=14]`
`[Text=再 CharacterOffsetBegin=15 CharacterOffsetEnd=16]`
`[Text=获得 CharacterOffsetBegin=17 CharacterOffsetEnd=19]`
`[Text=任何 CharacterOffsetBegin=20 CharacterOffsetEnd=22]`
`[Text=结果 CharacterOffsetBegin=23 CharacterOffsetEnd=25]`
`[Text=。 CharacterOffsetBegin=26 CharacterOffsetEnd=27]`
`Sentence #2 (2 tokens):`
`金融时报》周三`
`[Text=金融时报 CharacterOffsetBegin=31 CharacterOffsetEnd=35]`
`[Text=周三 CharacterOffsetBegin=36 CharacterOffsetEnd=38]`

Here there are two issues:

1. Characters 」and  are《 skipped completely, even from the complete sentences
2. The characters  《, 》, 「 and 」are not present as tokens.

**Comment by manning** [comment]
Thanks for the report. I think this is mainly fixed in v 3.7.0.  (The beta is out now on the website, final version to follow and be on Maven Central soon.) The current result is:

```
Sentence #1 (11 tokens):
巴拉特 说 ： 「 我们 未 再 获得 任何 结果 。
[Text=巴拉特 CharacterOffsetBegin=0 CharacterOffsetEnd=3]
[Text=说 CharacterOffsetBegin=4 CharacterOffsetEnd=5]
[Text=： CharacterOffsetBegin=6 CharacterOffsetEnd=7]
[Text=「 CharacterOffsetBegin=8 CharacterOffsetEnd=9]
[Text=我们 CharacterOffsetBegin=10 CharacterOffsetEnd=12]
[Text=未 CharacterOffsetBegin=13 CharacterOffsetEnd=14]
[Text=再 CharacterOffsetBegin=15 CharacterOffsetEnd=16]
[Text=获得 CharacterOffsetBegin=17 CharacterOffsetEnd=19]
[Text=任何 CharacterOffsetBegin=20 CharacterOffsetEnd=22]
[Text=结果 CharacterOffsetBegin=23 CharacterOffsetEnd=25]
[Text=。 CharacterOffsetBegin=26 CharacterOffsetEnd=27]
Sentence #2 (6 tokens):
」
《金融时报》周三
[Text=」 CharacterOffsetBegin=28 CharacterOffsetEnd=29]
[Text=《 CharacterOffsetBegin=30 CharacterOffsetEnd=31]
[Text=金融 CharacterOffsetBegin=31 CharacterOffsetEnd=33]
[Text=时报 CharacterOffsetBegin=33 CharacterOffsetEnd=35]
[Text=》 CharacterOffsetBegin=35 CharacterOffsetEnd=36]
[Text=周三 CharacterOffsetBegin=36 CharacterOffsetEnd=38]
```

The thing that is still wrong is not keeping 」with the preceding sentence. We may be able to fix that. We do handle similar stuff in English.

**Comment by ivan-zapreev** [comment]
Hallo, awesome! Thanks you for the reply! As far as I can see the only thing that is to be fixed is indeed keeping  」with the preceding sentence. Fingers crossed, hopefully it will make it into the 3.7.0 👍  Is there any indication of the release date?

**Comment by manning** [comment]
Plan is to release it next week.
