### ISSUE TITLE
TokenizerAnnotator: unknown tokenize.language property zh version 3.6.0

### ISSUE THREAD

**Issue by maregeo** [stanfordnlp/CoreNLP#315]
I read source code and it looks like 
` public enum TokenizerType {
    Unspecified(null, null, "invertible,ptb3Escaping=true"),
    Spanish    ("es", "SpanishTokenizer", "invertible,ptb3Escaping=true,splitAll=true"),
    English    ("en", "PTBTokenizer", "invertible,ptb3Escaping=true"),
    German     ("de", null, "invertible,ptb3Escaping=true"),
    French     ("fr", "FrenchTokenizer", ""),
    Whitespace (null, "WhitespaceTokenizer", "");

    private final String abbreviation;
    private final String className;
    private final String defaultOptions;

    TokenizerType(String abbreviation, String className, String defaultOptions) {
      this.abbreviation = abbreviation;
      this.className = className;
      this.defaultOptions = defaultOptions;
    }`

i can't find zh in TokenizerType

**Comment by J38** [comment]
In version 3.7.0 we did some refactoring so that all languages, including Chinese and Arabic use the TokenizerAnnotator.  So you need to upgrade to 3.7.0 to use tokenize.language zh and not get an error.
