### ISSUE TITLE
Timing information does not wait for last thread to finish

### ISSUE THREAD

**Issue by peteruhrig** [stanfordnlp/CoreNLP#319]
The timing information given by CoreNLP at the end does not wait for last thread to finish and is thus wrong (even though the information on when all threads were running in parallel may be interesting, too).

Simple test: Use 4 threads and parse 1 file only:

    Annotation pipeline timing information:
    TokenizerAnnotator: 0.0 sec.
    CleanXmlAnnotator: 0.0 sec.
    WordsToSentencesAnnotator: 0.0 sec.
    POSTaggerAnnotator: 0.0 sec.
    TrueCaseAnnotator: 0.0 sec.
    MorphaAnnotator: 0.0 sec.
    NERCombinerAnnotator: 0.0 sec.
    ParserAnnotator: 0.0 sec.
    DependencyParseAnnotator: 0.0 sec.
    DeterministicCorefAnnotator: 0.0 sec.
    RelationExtractorAnnotator: 0.0 sec.
    NaturalLogicAnnotator: 0.0 sec.
    QuoteAnnotator: 0.0 sec.
    SentimentAnnotator: 0.0 sec.
    TOTAL: 0.0 sec. for 0 tokens at NaN tokens/sec.
    Pipeline setup: 45.5 sec.
    Total time for StanfordCoreNLP pipeline: 45.5 sec.
    Annotating file /home/pruhrig/stanford-corenlp-full-2016-10-31/test_normal.txt ... done [0.7 sec].

**Comment by J38** [comment]
Ok I've pushed a fix for this.  Basically the timing print out was happening as soon as the last document was handed off to be processed.  Now the timing info it tied to the completion of the last file.
