### ISSUE TITLE
Train sentiment analyzer for a specific domain

### ISSUE THREAD

**Issue by anupamme** [stanfordnlp/CoreNLP#32]
Hello, 

I am not sure if this is relevant to this forum but I want to train the sentiment analyzer model for specific domains, right now it is pretty generic. e.g. following sentences

The room was spacious  or The restaurants were short walk from the hotel

get a sentiment of 1/5 whereas they talk positively. 

Any instructions how I can achieve this extension will be appreciated.

**Comment by anupamme** [comment]
I downloaded the training data from http://nlp.stanford.edu/sentiment/code.html

Training data (train.txt file) had 8544 lines and is of size 2.1M. I generated the new model using SentimentTraining.java. The size of the new model (new_model.ser.gz) is 248K whereas the size of edu/stanford/nlp/models/sentiment/sentiment.ser.gz is 3.6K

I suspect this is because sentiment.ser.gz is trained on larget set of training data than the training data available to download. Is that correct?

If yes, is there a way to enhance the model for new domains (rather than training from scratch)?

**Comment by anupamme** [comment]
I guess I was not super clear.

Is the complete training data available for re-training purposes? Or is it something proprietary to stanford and is not publicly available?

**Comment by davidaparicio** [comment]
@anupamme I have the same question.. 👍

**Comment by gangeli** [comment]
We certainly don't have any proprietary training data, though I'm not the right person to answer why the model sizes are different (also, I assume 3.6K = 3.6M?)

**Comment by cfuxiang** [comment]
Supposedly we have already a trained model via this command:
`java -mx8g edu.stanford.nlp.sentiment.SentimentTraining -numHid 25 -trainPath train.txt -devPath dev.txt -train -model model.ser.gz`
How to use this model `model.ser.gz` for prediction? As in, what is the command to pass in this model via jar?

**Comment by jageshmaharjan** [comment]
My question is same as @cfuxiang

**Comment by J38** [comment]
`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,parse,sentiment -parse.binaryTrees -sentiment.model /path/to/your-custom-sentiment-model -file example-sentence.txt -outputFormat text`

**Comment by jageshmaharjan** [comment]
Thank you, @J38

**Comment by jageshmaharjan** [comment]
One more question, can i use both model [Stanford sentiment model and my domain model ] to predict the sentiment. Does the result conflicts.

**Comment by J38** [comment]
No you can only use one model at a time.

**Comment by jageshmaharjan** [comment]
谢谢

**Comment by jageshmaharjan** [comment]
Thank you :)

**Comment by jageshmaharjan** [comment]
While i train the training dataset, using Stanford sentiment tool [RNTN], several models were generated, which i assume with score. Which model should we use.

**Comment by saisubramaniam** [comment]
Has someone already created custom models for specific domains? If yes, will it be possible to share? Thanks.
