### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: edu.stanford.nlp.process.WordToSentenceProcessor.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/Set;Ljava/util/Set;Ledu/stanford/nlp/process/WordToSentenceProcessor$NewlineIsSentenceBreak;Ledu/stanford/nlp/ling/tokensregex/SequencePattern;Ljava/util/Set;)V

### ISSUE THREAD

**Issue by maregeo** [stanfordnlp/CoreNLP#321]
exception stack ：
Exception in thread "main" java.lang.NoSuchMethodError: edu.stanford.nlp.process.WordToSentenceProcessor.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/Set;Ljava/util/Set;Ledu/stanford/nlp/process/WordToSentenceProcessor$NewlineIsSentenceBreak;Ledu/stanford/nlp/ling/tokensregex/SequencePattern;Ljava/util/Set;)V
	at edu.stanford.nlp.pipeline.WordsToSentencesAnnotator.<init>(WordsToSentencesAnnotator.java:53)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.wordToSentences(AnnotatorImplementations.java:54)
	at edu.stanford.nlp.pipeline.AnnotatorFactories$3.create(AnnotatorFactories.java:213)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:152)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:150)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:137)

————————————————here is my code like that：——————————
`
Properties props = 
		PropertiesUtils.asProperties("annotators", " tokenize, ssplit, pos, lemma, ner, parse, mention, coref",
				"tokenize.language" ,"zh",
				"segment.model" ,"edu/stanford/nlp/models/segmenter/chinese/ctb.gz",
				"segment.sighanCorporaDict", "edu/stanford/nlp/models/segmenter/chinese",
				"segment.serDictionary" , "edu/stanford/nlp/models/segmenter/chinese/dict-chris6.ser.gz",
				"segment.sighanPostProcessing" , "true",
				"ssplit.boundaryTokenRegex" , "[.。]|[!?！？]+",
				"pos.model" , "edu/stanford/nlp/models/pos-tagger/chinese-distsim/chinese-distsim.tagger",
				"ner.language" , "chinese",
				"ner.model", "edu/stanford/nlp/models/ner/chinese.misc.distsim.crf.ser.gz",
				"ner.applyNumericClassifiers" ,"true",
				"ner.useSUTime", "false",
				"regexner.mapping","edu/stanford/nlp/models/kbp/cn_regexner_mapping.tab",
				"regexner.validpospattern" , "^(NR|NN|JJ).*",
				"regexner.ignorecase" , "true",
				"regexner.noDefaultOverwriteLabels" , "CITY",
				"parse.model" , "edu/stanford/nlp/models/srparser/chineseSR.ser.gz",
				"depparse.model","edu/stanford/nlp/models/parser/nndep/UD_Chinese.gz",
				"depparse.language", "chinese",
				"coref.sieves" ,"ChineseHeadMatch, ExactStringMatch, PreciseConstructs, StrictHeadMatch1, StrictHeadMatch2, StrictHeadMatch3, StrictHeadMatch4, PronounMatch",
				"coref.input.type" ,"raw",
				"coref.postprocessing" ,"true",
				"coref.calculateFeatureImportance" , "false",
				"coref.useConstituencyTree" , "true",
				"coref.useSemantics" , "false",
				"coref.algorithm" ,"hybrid",
				"coref.path.word2vec" ,"",
				"coref.language" , "zh",
				"coref.defaultPronounAgreement" , "true",
				"coref.zh.dict" , "edu/stanford/nlp/models/dcoref/zh-attributes.txt.gz",
				"coref.print.md.log" , "false",
				"coref.md.type" , "RULE",
				"coref.md.liberalChineseMD" ,"false"
				);
		StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

		// read some text in the text variable
		String text = "这里是中国";
		// create an empty Annotation just with the given text
		Annotation document = new Annotation(text);
		// run all Annotators on this text
		pipeline.annotate(document);

`

**Comment by manning** [comment]
Your code above runs fine for me using code from HEAD.

This error is being caused by you having classes or jar files from two different versions/dates on your classpath, which are incompatible.

Even though the exact case is different, see the long description of the general problem at:

http://nlp.stanford.edu/software/pos-tagger-faq.shtml#nosuchmethoderror

In this case, I think it is because post-version 3.6, we made some changes to the internal methods of WordToSentenceProcessor to better support Chinese.
