### ISSUE TITLE
NER cannot work correctly with Cyprus and cyprus 

### ISSUE THREAD

**Issue by xtao** [stanfordnlp/CoreNLP#332]
Step:
1. search Cyprus: "ner":"POSITION"
2. search cyprus: "ner":"O"
3. search Cyprus: "ner":"O"

After those three steps, we cannot get correct ner with 'Cyprus'.

In 3.6.0

**Comment by J38** [comment]
The `ner` annotator is designed to work on a sentence, such as `I traveled to cyprus last summer.`  We supply models that work on caseless text.  They can be found in the English models jar available [here](http://stanfordnlp.github.io/CoreNLP/download.htmll)

This is a sample command showing use of the caseless models (make sure to have the English models jar in your CLASSPATH):

`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner -ner.model edu/stanford/nlp/models/ner/english.all.3class.caseless.distsim.crf.ser.gz,edu/stanford/nlp/models/ner/english.muc.7class.caseless.distsim.crf.ser.gz,edu/stanford/nlp/models/ner/english.conll.4class.caseless.distsim.crf.ser.gz -file sample-sentence.txt -outputFormat text`

It correctly tags `cyprus` as LOCATION when run on the above example sentence.

Also be sure to download Stanford CoreNLP 3.7.0 for the best results!
