### ISSUE TITLE
customAnnotatorClass static object ?

### ISSUE THREAD

**Issue by toliwa** [stanfordnlp/CoreNLP#333]
I can create a customAnnotator with some parameters in a properties object and then create a brand new pipeline with 

    StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

My customAnnotator works fine. Now when I create another pipeline object with the customAnnotator and some other parameters defined in a new properties file, the customAnnotator class gets not instantiated a second time. Instead, the second pipeline seems to be using the created class of the customAnnotator from the first pipeline.

It looks to me that customAnnotators in CoreNLP live somehow in static objects, and it is not intended to create a second pipeline with the same annotator and different parameters in a single JVM, but maybe I am missing something.

Clearing the pool does not help, as this only sets the pool to null.

    pipeline.clearAnnotatorPool();

Is this intended behavior or a bug? (CoreNLP 3.7.0)

How can I instantiate a new object of class StanfordCoreNLP, so that a customAnnotators constructor is also called every time and its object created every time anew?

**Comment by J38** [comment]
I am not seeing this behavior at all.

I created two separate properties objects with different versions of a DummyCustomAnnotator.

```
annotators = tokenize,ssplit,pos,custom-one
customAnnotatorClass.custom-one = edu.stanford.nlp.examples.SimpleCustomAnnotator
custom-one.customAttribute = CUSTOM-ONE
```

```
annotators = tokenize,ssplit,pos,custom-two
customAnnotatorClass.custom-two = edu.stanford.nlp.examples.SimpleCustomAnnotator
custom-two.customAttribute = CUSTOM-TWO
```

I built two pipelines, each with the different properties.  I then ran each one in succession, and I saw that each pipeline had a distinct custom annotator.

```
package edu.stanford.nlp.examples;

import edu.stanford.nlp.pipeline.*;
import edu.stanford.nlp.util.*;

import java.util.*;


public class TwoVersionsOfCustomAnnotator {

  public static void main(String[] args) {
    // set up two props files
    Properties customPropsOne = StringUtils.argsToProperties("-props", "custom-one.props");
    Properties customPropsTwo = StringUtils.argsToProperties("-props", "custom-two.props");
    // set up two pipelines
    StanfordCoreNLP pipelineOne = new StanfordCoreNLP(customPropsOne);
    StanfordCoreNLP pipelineTwo = new StanfordCoreNLP(customPropsTwo);
    // text
    Annotation exampleText = new Annotation("...");
    Annotation anotherText = new Annotation("...");
    // annotate
    pipelineOne.annotate(exampleText);
    pipelineTwo.annotate(exampleText);
    // annotate again
    pipelineOne.annotate(anotherText);
    pipelineTwo.annotate(anotherText);

  }
}
```

**Comment by J38** [comment]
This was done with the current code on GitHub.  Please let me know if you are still seeing any issues.

**Comment by J38** [comment]
One piece of advice, if you are creating two versions of the same pipeline you should give them different names as in my example: `custom-one` and `custom-two`.  If you weren't doing that that could possibly cause an issue.
