### ISSUE TITLE
Wrong slf4j.jar version?

### ISSUE THREAD

**Issue by fievelk** [stanfordnlp/CoreNLP#334]
I have the feeling that the current `slf4j` version shipped within Stanford CoreNLP is different from the one that is actually required by it. This command will fail:

```bash
/usr/bin/java -mx1000m -cp my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/stanford-postagger-3.7.0.jar:my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/stanford-postagger.jar:my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/stanford-postagger-3.7.0-sources.jar:my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/stanford-postagger-3.7.0-javadoc.jar:my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/lib/slf4j-simple.jar:my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/lib/slf4j-api.jar edu.stanford.nlp.tagger.maxent.MaxentTagger -model my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/models/english-bidirectional-distsim.tagger -textFile /tmp/tmp1ap3auf6 -tokenize false -outputFormatOptions keepEmptySentences -encoding utf8
```
The error is the following:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<clinit>(MaxentTagger.java:224)
Caused by: java.lang.IllegalStateException: Could not find SLF4J in your classpath
	at edu.stanford.nlp.util.logging.RedwoodConfiguration$Handlers.lambda$static$530(RedwoodConfiguration.java:190)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration$Handlers$7.buildChain(RedwoodConfiguration.java:309)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration$Handlers$7.apply(RedwoodConfiguration.java:318)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration.lambda$handlers$535(RedwoodConfiguration.java:363)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration.apply(RedwoodConfiguration.java:41)
	at edu.stanford.nlp.util.logging.Redwood.<clinit>(Redwood.java:609)
	... 1 more
Caused by: edu.stanford.nlp.util.MetaClass$ClassCreationException: java.lang.ClassNotFoundException: edu.stanford.nlp.util.logging.SLF4JHandler
	at edu.stanford.nlp.util.MetaClass.createFactory(MetaClass.java:364)
	at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:381)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration$Handlers.lambda$static$530(RedwoodConfiguration.java:186)
	... 6 more
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.util.logging.SLF4JHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.construct(MetaClass.java:135)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.<init>(MetaClass.java:202)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.<init>(MetaClass.java:69)
	at edu.stanford.nlp.util.MetaClass.createFactory(MetaClass.java:360)
```

The manifest file of `lib/slf4j-api.jar` that you are currently shipping states:
```
Bundle-Description: The slf4j API
Bundle-Version: 1.7.2
Implementation-Version: 1.7.2
```

Conversely, in your [`core-nlp/pom-full.xml`][1] you state that version `1.7.12` is required:
```xml
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-api</artifactId>
  <version>1.7.12</version>
</dependency>
```

If I substitute your `lib/slf4j-api.jar` with the `1.7.12` version, I can correctly run the above command and get the result:
```bash
Loading default properties from tagger my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/models/english-bidirectional-distsim.tagger
Loading POS tagger from my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/models/english-bidirectional-distsim.tagger ... done [2.3 sec].
What_WP is_VBZ the_DT airspeed_NN of_IN an_DT unladen_JJ swallow_VB ?_.
Tagged 9 words at 65.22 words per second.
```

[1]: https://github.com/stanfordnlp/CoreNLP/blob/3eeaff39eee27287925ed4c625e7ac167bccfba1/doc/corenlp/pom-full.xml#L114

**Comment by fievelk** [comment]
Update: I noticed that if I remove this entry from the classpath everything goes smoothly:
`my_path/stanford_core_nlp/stanford-postagger-full-2016-10-31/lib/slf4j-api.jar`.

However, the `README` examples use `-classpath stanford-postagger.jar:lib/*`, and it seems that the `lib/*` part is what is causing the problem.

**Comment by manning** [comment]
Yes, there's obviously something to figure out here and something to update in the tagger distribution, but the aim is that with 3.7, you'll only need the tagger jar and it will run, and so deleting mentions of slf4j should be the right move.

In general, you don't need all those things on your classpath! The sources jar file and documentation (javadoc) jar aren't needed, and the jar file with and without the version number in it are identical. So, under v3.7 (or v3.5 or earlier) it should all work with just one of those on the classpath, and nothing else! (In v3.6 you had to have the slf4j logging jars, but we decided that was a big mistake.)

**Comment by fievelk** [comment]
@manning Thank you for your answer. 
I think that fixing the `slf4j.jar` version in the tagger distribution would help solving compatibility problems for libraries that use it as third-party software. For example, NLTK interfaces are currently including the logger jar in the CLASSPATH. I suppose that this would work with both `v3.6` and `v3.7` if the shipped version of `slf4j.jar` was the same required in `pom-full.xml`.

**Comment by manning** [comment]
Thanks for raising the issue and your comments. We do definitely have some work to do getting the documentation updated and consistent, etc. Including the logger jar in the classpath should work fine, but the fundamental difference is that the v3.6 tagger won't run _without_ slf4j, whereas the v3.7 tagger runs fine without slf4j. We're deleting – indeed @J38 has already deleted – slf4j from the tagger zip file. Just need to update documentation now ….

**Comment by highpost** [comment]
I seem to have a related problem. I'm new to the Stanford NLP software and I'm using it from NLTK. Right now, I'm seeing three versions of slf4j-api.jar:

slf4j:
-rw-r--r-- 1 dan dan 41077 Dec 13 18:07 slf4j-api-1.7.22.jar
corenlp:
-rw-rw-r-- 1 dan dan 26083 Jan  7 03:44 slf4j-api.jar
parser:
-rw-rw-r-- 1 dan dan 32127 Jan  9 05:18 slf4j-api.jar

I'm not sure which jars to add to my CLASSPATH, so of course I'm adding them all. And now I'm getting a "java.lang.IllegalStateException: Could not find SLF4J in your classpath", which is interesting because I have several copies available.

**Comment by J38** [comment]
You want to use `slf4j-api-1.7.12`

**Comment by harshita-gupta** [comment]
Just to clarify: should I be renaming the jars at all, and which should I direct to in the classpath, with what name?

**Comment by J38** [comment]
Hi here is my advice for accessing Stanford CoreNLP from Python:

1. Download the latest Stanford CoreNLP 3.7.0 distribution from here:

http://stanfordnlp.github.io/CoreNLP/download.html

You should unzip it and get a folder called stanford-corenlp-full-2016-10-31.

2. Run this command to start the Stanford CoreNLP server:

`cd /path/to/stanford-corenlp-full-2016-10-31 ; java -Xmx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000 -annotators tokenize,ssplit,pos,lemma,ner,parse`

This will start up a Stanford CoreNLP server on your local machine.  This command will cause these annotators to be loaded: `tokenize,ssplit,pos,lemma,ner,parse`

Note also you could run this command in Python with subprocess, etc...

3. Here is some sample Python code to issue a request to the Stanford CoreNLP server:

```
import requests

url = 'http://localhost:9000/?'
request_params = {'outputFormat': 'json'}
text = "This is a test sentence."
r = requests.post(url,data=text,params=request_params)
print r.json()
```

This should return a JSON string with the various linguistic annotations including the parse.

4. When you're done remember to close the server.

If you have any more issues please let me know!

**Comment by J38** [comment]
Also I'd like to advertise the Python code the group has written to access the Stanford CoreNLP server.  If you install `stanza` there are some Python interfaces for calling the server.  The full details are available at this link:

https://github.com/stanfordnlp/stanza

**Comment by qingchen36** [comment]
rename  "stanford-parser-full-2016-10-31/slf4j-api-1.7.12-sources.jar"  to be "slf4j-api.jar";  the add "slf4j-api.jar" to CLASSPATH.
I tested it ,and it is work

**Comment by yjr930** [comment]
It seems that you should use "slf4j-api-1.7.12-sources.jar" instead of "slf4j-api-1.7.12.jar"
