### ISSUE TITLE
Handling unclosed quotations

### ISSUE THREAD

**Issue by pburrows** [stanfordnlp/CoreNLP#338]
Currently in the quotations analyzer, it writes a warning to the console that unclosed quotations were found, but there is no way to get those notifications programatically. 

Is there a way to make those notifications visible to users as an interim to implementing the "closeUnclosedQuotes" feature (which is currently marked with  todo)

https://github.com/stanfordnlp/CoreNLP/search?utf8=%E2%9C%93&q=closeUnclosedQuotes

Here's the relevant code from QuoteAnnotator.java:

```
//    // TODO: determine if we want to be more strict w/ single quotes than double
//    // answer: we do want to.
//    // if we reached then end and we have an open quote, close it
//    if (closeUnclosedQuotes && start >= 0 && start < text.length() - 2) {
//      if (!quotesMap.containsKey(quote)) {
//        quotesMap.put(quote, new ArrayList<>());
//      }
//      quotesMap.get(quote).add(new Pair(start, text.length()));
//    } else
    if (start >= 0 && start < text.length() - 3) {
      String warning = text;
      if (text.length() > 150) {
        warning = text.substring(0, 150) + "...";
      }
      log.info("WARNING: unmatched quote of type " +
          quote + " found at index " + start + " in text segment: " + warning);
    }
```

**Comment by muznyg** [comment]
Let me first shed some light into why that feature was ultimately commented out: we decided that it would be better to have a higher precision extractor that sometimes missed quotes than to extract bad quotes.

Second, one solution (though not ideal) to your problem could be to read the log file as it's being written to detect the types of errors that you are looking for 
http://stackoverflow.com/questions/2210975/how-do-you-continuously-read-a-file-in-java 

What would your preferred behaviour be for when an unclosed quote is found?

**Comment by pburrows** [comment]
My use-case is that I want to warn people (show them visually) where they missed a quote. I am already splitting the document so that only a paragraph at a time is being passed through the quotations analyzer. 

From a design standpoint, I would think, there are two possibilities: use a dedicated type, or add special cases for the existing type. 

The dedicated type would be a new type of CoreAnnotation, say an UnclosedQuotationAnnotation that returns a List<CoreMap> of unclosed quotes.  I'd think it would have TextAnnotation and CharacterOffsetBeginAnnotation types (but not CharacterOffsetEndAnnotations, obviously).

Adding a special case to the existing QuotationsAnnotation /MIGHT/ be as simple as just not returning the various *EndAnnotations (CharacterOffset, Token, Sentence). But I think just leaving the feature there would be confusing behavior. Instead a way to signify that this QuotationAnnotation is an UnclosedQuotation would be needed. Perhaps an UnclosedQuotationAnnotation could be added. 

From a usability point of view, I like the first idea (a new type of UnclosedQuotationAnnotation). This way only people who care can specifically get them. Everyone else can continue using it as-is. Plus it wouldn't break any existing applications.

My suspicion is this might be a more complicated way of doing it, though.

**Comment by muznyg** [comment]
I think that the easiest/most practical solution would be to add an UnclosedQuotationsAnnotation, that would be exactly the same as the QuotationsAnnotation, except that the List<CoreMap> returned would be unclosed quotations. A thing to note about such an annotation: 1) all the *EndAnnotations should be kept - they simply indicate how far the span goes.

Further, the lines of code that are actually more relevant to this issue are 517 - 525 -- there is another question of what to do if an unclosed quote is found: currently the behaviour is to warn the user, then the annotator searches for quotes from position i + 1, which means that if there is a later, better formatted quotation, it has a chance of getting it. I think that adding an UnclosedQuotationsAnnotation that doesn't result in lots of special cases would want to treat this case as follows: if you found an unclosed quotation, add it to the list of unclosed quotations, then proceed as normal searching from position i + 1. If another, later quotation was also unclosed, it would also be added to the list, which means that you could end up with "cascading" unclosed quotes.

**Comment by muznyg** [comment]
Okay, changes are in so that setting extractUnclosedQuotes to "true" should give you an UnclosedQuotationsAnnotation at your top level. They have not yet been rigorously tested so if you have some use cases, either post them here or add them to QuoteAnnotatorTest. For the tests you'll need to add another custom annotator with extractUnclosedQuotes set to true.

https://github.com/stanfordnlp/CoreNLP/commit/87f755fe3f2e6c404c475a2add86a34d461cf73c

**Comment by pburrows** [comment]
Wow! That was amazingly fast! 
I will pull the source / nightly build / and try it out locally. 

Than you so much!

**Comment by pburrows** [comment]
Here is a simple test that doesn't appear to be working for me. Can you try it and see if it works? (UnclosedQuotationsAnnotation is null)

> "It is sad, Sola, that you were not born a million years ago," snapped Sarkoja, "when all the hollows of the land were filled with water

I would expect this to return one QuoteAnnotation and one UnclosedQuotationsAnnotation.

**Comment by pburrows** [comment]
Here is a failing unit test. I modified the existing testUnclosedLastDoubleQuotes test to look like this:

```
public void testUnclosedLastDoubleQuotes() {
    String text = "\"Hello,\" he said, \"how are you doing?";
    List<CoreMap> quotes = runQuotes(text, 1);
    List<CoreMap> unclosedQuotes = runUnclosedQuotes(text, 1, pipelineUnclosedQuotes);
    assertEquals("\"Hello,\"", quotes.get(0).get(CoreAnnotations.TextAnnotation.class));
    assertEquals("\"how are you doing?", unclosedQuotes.get(0).get(CoreAnnotations.TextAnnotation.class));
  }
```

And added this to the setup:

```
if(pipelineUnclosedQuotes == null){
        Properties props = new Properties();
        props.setProperty("annotators", "tokenize, ssplit, quote6");
        props.setProperty("customAnnotatorClass.quote6", "edu.stanford.nlp.pipeline.QuoteAnnotator");
        props.setProperty("extractUnclosedQuotes", "true");
        pipelineUnclosedQuotes = new StanfordCoreNLP(props);
      }
```

and created the runUnclosedQuotes method like this:

```
  public List<CoreMap> runUnclosedQuotes(String text, int numQuotes, StanfordCoreNLP pipeline) {
    Annotation doc = new Annotation(text);
    pipeline.annotate(doc);

    // now check what's up...
    List<CoreMap> quotes = doc.get(CoreAnnotations.UnclosedQuotationsAnnotation.class);

    Assert.assertNotNull(quotes);
    Assert.assertEquals(numQuotes, quotes.size());
    return quotes;
  }
```

I've attached the failing test as a patch. I'll see if I can dig through the code more and figure out what is going on. 

Or, perhaps, I am just doing something wrong in the setup (that seems more likely :)  )

[failingtest.zip](https://github.com/stanfordnlp/CoreNLP/files/704590/failingtest.zip)

**Comment by muznyg** [comment]
Great! I'll take a look at it more after the weekend.

**Comment by muznyg** [comment]
Should be handled now (it was an error with being able to deal with both closed & unclosed quotes). As before, *warning*, I have not extremely thoroughly tested this so if you encounter any bugs/failing cases please do send them along/create a pull request etc!

https://github.com/stanfordnlp/CoreNLP/commit/bc3a99e5faebbb528c4ddea745554e5cec1a6423

**Comment by pburrows** [comment]
Thanks! I was able to make the test pass locally. I'll let you know if I come across other test cases.
