### ISSUE TITLE
Chinese Word Segmentation result difference due to the period mark 

### ISSUE THREAD

**Issue by zhuangh** [stanfordnlp/CoreNLP#339]
I tried to use CoreNLP Chinese word segmenter to do the segmentation of the following two sentences， "没有见过你听摇滚乐。" and "没有见过你听摇滚乐" . The only difference is that the first one sentence has period.

The results are 
1. 没有见过你听摇滚乐。 => 没有 见 过 你 听摇滚乐 。 
2. 没有见过你听摇滚乐=> 没有 见 过 你 听 摇滚乐

The command options are used as following, when CoreNLP as service 
properties={"tokenize.whitespace": "true", "annotators": "segment,ssplit,pos", "outputFormat": "json", "customAnnotatorClass.segment": "edu.stanford.nlp.pipeline.ChineseSegmenterAnnotator", "segment.model": "edu/stanford/nlp/models/segmenter/chinese/ctb.gz", "segment.sighanCorporaDict": "edu/stanford/nlp/models/segmenter/chinese", "segment.serDictionary": "edu/stanford/nlp/models/segmenter/chinese/dict-chris6.ser.gz", "segment.sighanPostProcessing": "true", "pos.model": "edu/stanford/nlp/models/pos-tagger/chinese-distsim/chinese-distsim.tagger"}

I think 听摇滚乐 should be divided to 听（listen to) 摇滚乐(rock music), which means the second sentence is "correct". But why does the difference depend on the period mark?

Any thought? Thanks.

**Comment by J38** [comment]
The Chinese word segmenter is a CRF trained on Chinese segmentation training data.  There is more info here: http://www.aclweb.org/anthology/I05-3027 and here: https://nlp.stanford.edu/software/segmenter.html

Statistical models such as this can have their behavior change by small variations in the input sequence.  Also such systems are not guaranteed to always behave correctly.
