### ISSUE TITLE
Unable to open "edu/stanford/nlp/pipeline/demo/corenlp-brat.html" as class path, filename or URL

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#340]
I have cloned latest CoreNLP repo, built with `mvn package` and put the latest models root in the `CLASSPATH`:

```
CoreNLPDataset loretoparisi$ ls -l
total 3662400
-rw-r--r--@ 1 loretoparisi  staff   362133856 12 Gen 17:03 stanford-corenlp-models-current.jar
-rw-r--r--@ 1 loretoparisi  staff  1039006700 12 Gen 17:07 stanford-english-corenlp-models-current.jar
-rw-r--r--@ 1 loretoparisi  staff   474001837 12 Gen 17:03 stanford-english-kbp-corenlp-models-current.jar
```

When I try to startup the CoreNLP server like `java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer`

 I get

```
$ java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer
--- StanfordCoreNLPServer#main() called ---
setting default constituency parser
warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
to use shift reduce parser download English models jar from:
http://stanfordnlp.github.io/CoreNLP/download.html
    Threads: 8
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/pipeline/demo/corenlp-brat.html" as class path, filename or URL
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1263)
Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/pipeline/demo/corenlp-brat.html" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.io.IOUtils.readerFromString(IOUtils.java:637)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$FileHandler.<init>(StanfordCoreNLPServer.java:460)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$FileHandler.<init>(StanfordCoreNLPServer.java:457)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1261)
CoreNLP Server is shutting down.
```

It seems it cannot found the resource of the html server index page in https://github.com/stanfordnlp/CoreNLP/blob/2e4c4dc48ab8a34f6696757a5351a48412f66d61/src/edu/stanford/nlp/pipeline/StanfordCoreNLPServer.java#L1261

So my guess was a `mvn` problem, trying with `ant` at the end it seems resources have been copied:

```
     [copy] Copying 5 files to /Users/loretoparisi/Documents/Projects/CoreNLP/classes/edu/stanford/nlp/pipeline/demo
     [copy] Copying 13 files to /Users/loretoparisi/Documents/Projects/CoreNLP/classes/edu/stanford/nlp/pipeline

```

but I get the same error starting up the server.

**Comment by gangeli** [comment]
I suspect the maven build is not copying the appropriate files over. I'll update the build file once I get a chance, but in the meantime building the jar with `ant jar` should fix the bug.

**Comment by J38** [comment]
Currently the pom.xml is not designed to package the models jars.  You need to include the models jars in a folder if you want to run the server.  `mvn package` is just going to create a jar with the code.

**Comment by loretoparisi** [comment]
@J38 yes I confirm, infact @gangeli the `mvn` will not bundle the demo files, I did `ant` build and then (forgot this step before) in `classes` compiled the files: `jar -cf ../stanford-corenlp.jar edu`. The resulting `jar` will work this time with all resources bundled.

So the recap instead of `mvn package` you do

```
cd CoreNLP/
ant
cd classes/
jar -cf ../target/stanford-corenlp.jar edu
cd target/
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer
```

By the way there is still something missing since I get

```
--- StanfordCoreNLPServer#main() called ---
setting default constituency parser
warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
to use shift reduce parser download English models jar from:
http://stanfordnlp.github.io/CoreNLP/download.html
```

even if I have defined the CLASSPATH with this folder:

```
CoreNLPDataset loretoparisi$ ls -l
total 3662400
-rw-r--r--@ 1 loretoparisi  staff   362133856 12 Gen 17:03 stanford-corenlp-models-current.jar
-rw-r--r--@ 1 loretoparisi  staff  1039006700 12 Gen 17:07 stanford-english-corenlp-models-current.jar
-rw-r--r--@ 1 loretoparisi  staff   474001837 12 Gen 17:03 stanford-english-kbp-corenlp-models-current.jar
```

**Comment by J38** [comment]
If you use `-cp "*"` in your command the CLASSPATH will be whatever folder you are running the command from.

If you exclude the `-cp "*"` it will use whatever you set the environment variable CLASSPATH to be.

When I run the current code with the English jars in my CLASSPATH it properly finds `edu/stanford/nlp/models/srparser/englishSR.ser.gz`

**Comment by loretoparisi** [comment]
@J38 my env looks like

`:/Users/loretoparisi/Documents/CoreNLPDataset:/Users/loretoparisi/Documents/Projects/CoreNLP/lib:/Users/loretoparisi/Documents/Projects/CoreNLP/liblocal
`

Do I have to link each jar instead?

**Comment by J38** [comment]
If you want to use the CLASSPATH variable make sure not to use `-cp "*"` in your command.

Also, every directory requires a `*`.  So for instance `/path/to/jars/*` will include all the jars in the directory `/path/to/jars`
