### ISSUE TITLE
JSONOutputter Public Classes

### ISSUE THREAD

**Issue by jd-carroll** [stanfordnlp/CoreNLP#341]
**[Objective:]**
Implement Stanford CoreNLP in Spring Boot container to support a custom authentication mechanism as well as some other goodies.

**[Method:]**
Re-implement/factor `StanfordCoreNLPServer` by breaking apart the core logic from the http server and resource handlers.  (i.e. implementing a Spring `@Service ` for the `StanfordCoreNLPServer`)

**[Issue:]**
The `StanfordCoreNLPServer` uses `JSONOutputter` which has subclasses [`JSONWriter`](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/JSONOutputter.java#L323) and [`Writer`](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/JSONOutputter.java#L527), both of these classes are not public.

Is there any reason why these classes are not `public static` instead of `protected static`?  It seems silly to make a copy of JSONWritter just to get access to those classes.

**Comment by gangeli** [comment]
There's no principled reason these are protected rather than public, other than the fact that we don't really use them elsewhere. I'll change them to public soon.

**Comment by jd-carroll** [comment]
Thanks!

**Comment by jd-carroll** [comment]
I'll also throw in [`createOutputter`](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/StanfordCoreNLP.java#L957) and [`OutputFormat`](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/StanfordCoreNLP.java#L89) from StanfordCoreNLP, but those are a little easier to manage.

**Comment by J38** [comment]
I made the requested changes.
