### ISSUE TITLE
MaxSizeConcurrentHashSet.java is not threadsafe

### ISSUE THREAD

**Issue by KellenSunderland** [stanfordnlp/CoreNLP#342]
From the naming I would expect this class to be threadsafe, but when checking for maximum size here:

https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/util/MaxSizeConcurrentHashSet.java#L104 

and here:

https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/util/MaxSizeConcurrentHashSet.java#L74

we see this is not the case.

**Comment by manning** [comment]
Hi Kellen, what is the problem with line 104? I don't see it.

For 74, you'd be happy if there were a synchronized block so the size can't change between the size test and the adding?

**Comment by KellenSunderland** [comment]
My mistake, I missed that addAll is intentionally not checking maxSize.  For line 74, yes I think a lock block would work well there.
