### ISSUE TITLE
Unique shutdown key file names

### ISSUE THREAD

**Issue by DavidNemeskey** [stanfordnlp/CoreNLP#345]
When the Stanford CoreNLP server is started, it creates the file `/tmp/corenlp.shutdown` file, which contains the shutdown key. The problem is, if two servers are started on two different ports (e.g. to speed up analysis on a multicore system), then both instances will write their keys to this file. This, of course, makes it impossible to stop one of them via the shutdown URL.

The solution to this situation is making sure the files have unique names. The easiest way would be to append the port to the name of the file, e.g. `/tmp/corenlp.shutdown.9000`.

**Comment by J38** [comment]
Ok I pushed a change to address this.

**Comment by DavidNemeskey** [comment]
Thanks, I was just going to add it. :)

**Comment by J38** [comment]
Hmm but my change doesn't work due to some issues!

**Comment by DavidNemeskey** [comment]
Ah yes, indeed: it's always `.9000`, irrespective of what I specify as `--port`.

**Comment by J38** [comment]
Ok I've added a new `-server_id` option, so if you use `-server_id server0` the shutdown file will be "/tmp/corenlp.shutdown.server0`
