### ISSUE TITLE
PTBEscapingProcessor leaves unescaped parentheses in output

### ISSUE THREAD

**Issue by smithtim** [stanfordnlp/CoreNLP#346]
PTBEscapingProcessor properly escapes parentheses to -LRB- and -RRB-, but seems to unescape them in the output, interfering with the tree format.  For example,

`They live in London ( Ontario ) .`

becomes

`(ROOT (S (NP (PRP They)) (VP (VBP live) (PP (IN in) (NP (NP (NNP London)) (PRN (-LRB- () (NP (NNP Ontario)) (-RRB- )))))) (. .)))
`

Notice that the NP containing `Ontario` has erroneously been made a child of the -LRB-, due to the unescaped left parenthesis.  The expected output is:

`(ROOT (S (NP (PRP They)) (VP (VBP live) (PP (IN in) (NP (NP (NNP London)) (PRN (-LRB- -LRB-) (NP (NNP Ontario)) (-RRB- -RRB-))))) (. .)))`

**Comment by J38** [comment]
When I run this command with Stanford CoreNLP 3.7.0:

`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,parse -file sample-text-2.txt -outputFormat text`

I get this output:

`Sentence #1 (8 tokens):
They live in London ( Ontario ) .
[Text=They CharacterOffsetBegin=0 CharacterOffsetEnd=4 PartOfSpeech=PRP Lemma=they]
[Text=live CharacterOffsetBegin=5 CharacterOffsetEnd=9 PartOfSpeech=VBP Lemma=live]
[Text=in CharacterOffsetBegin=10 CharacterOffsetEnd=12 PartOfSpeech=IN Lemma=in]
[Text=London CharacterOffsetBegin=13 CharacterOffsetEnd=19 PartOfSpeech=NNP Lemma=London]
[Text=-LRB- CharacterOffsetBegin=20 CharacterOffsetEnd=21 PartOfSpeech=-LRB- Lemma=-lrb-]
[Text=Ontario CharacterOffsetBegin=22 CharacterOffsetEnd=29 PartOfSpeech=NNP Lemma=Ontario]
[Text=-RRB- CharacterOffsetBegin=30 CharacterOffsetEnd=31 PartOfSpeech=-RRB- Lemma=-rrb-]
[Text=. CharacterOffsetBegin=32 CharacterOffsetEnd=33 PartOfSpeech=. Lemma=.]
(ROOT
  (S
    (NP (PRP They))
    (VP (VBP live)
      (PP (IN in)
        (NP
          (NP (NNP London))
          (PRN (-LRB- -LRB-)
            (NP (NNP Ontario))
            (-RRB- -RRB-)))))
    (. .)))

root(ROOT-0, live-2)
nsubj(live-2, They-1)
case(London-4, in-3)
nmod:in(live-2, London-4)
punct(Ontario-6, -LRB--5)
appos(London-4, Ontario-6)
punct(Ontario-6, -RRB--7)
punct(live-2, .-8)`

Isn't that the correct output ?

**Comment by smithtim** [comment]
That's the correct output, but this issue is about the `-escaper` option (combined with certain tokenize options).  Sorry for not being clear the first time; see below.

According to the Stanford Parser FAQ (questions 10 and 11), to give the parser POS tagged input, e.g.

`It is red/NN ( apparently ) .`

and force the parser to use those tags, you would include the options

`-tokenized -tagSeparator / -tokenizerFactory edu.stanford.nlp.process.WhitespaceTokenizer -tokenizerMethod newCoreLabelTokenizerFactory`

and provide correctly tokenized input by adding the flag

`-escaper edu.stanford.nlp.process.PTBEscapingProcessor`

Combining these, we have something like

java -mx1g -cp "*" edu.stanford.nlp.parser.lexparser.LexicalizedParser -sentences newline -tokenized -tagSeparator / -tokenizerFactory edu.stanford.nlp.process.WhitespaceTokenizer -tokenizerMethod newCoreLabelTokenizerFactory -escaper edu.stanford.nlp.process.PTBEscapingProcessor edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz example-sentence.txt

But the output is

`(ROOT
  (S
    (NP (PRP It))
    (VP (VBZ is)
      (NP (NN red))
      (PRN (-LRB- ()
        (ADVP (RB apparently))
        (-RRB- ))))
    (. .)))`

which exhibits the behavior I described above, indicating that the parentheses were not handled properly.

**Comment by J38** [comment]
Okay the issue is if you use the whitespace only for tokenization option it is not performing the escaping.

**Comment by AngledLuffa** [comment]
This has been fixed for version 4.0.0
