### ISSUE TITLE
Failed to load cusom stopword annotator

### ISSUE THREAD

**Issue by medvednic** [stanfordnlp/CoreNLP#348]
Hello,
I'm maintaining an old project which used CoreNLP 3.2.0, I've updated the dependency to 3.7.0. 
I'm trying to add a [custom annotator](https://github.com/jconwell/coreNlp/blob/master/src/main/java/intoxicant/analytics/coreNlp/StopwordAnnotator.java) that functioned with 3.2.0. Required class was still used back than to set and check for annotators requirement satisfaction.
I get an exception because Annotator$Requiered class is not found. Is there  a way to add this old style annotator? because there is no newer version of if.

**Comment by J38** [comment]
It shouldn't be hard to update your custom annotator to work with the new setup.  You just need to change requires() and requirementsSatisfied() to return the annotations that are required and produced.  Here is an example annotator with the new requirements set up: https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/DependencyParseAnnotator.java

**Comment by medvednic** [comment]
Thanks for the answer,
Here in the code of the two methods:
`@Override
    public Set<Requirement> requirementsSatisfied() {
        return Collections.singleton(STOPWORD_REQUIREMENT);
    }

    @Override
    public Set<Requirement> requires() {
        if (checkLemma) {
            return TOKENIZE_SSPLIT_POS_LEMMA;
        }
        else {
            return TOKENIZE_AND_SSPLIT;
        }
}`

I tried converting it by myself just for testing (with `required()` and `requirementsSatisfied()` set to return an empty list) but `annotate` method also gave me some trouble - `token.set()` to be precise.

`    @Override
    public void annotate(Annotation annotation) {
        if (stopwords != null && stopwords.size() > 0 && annotation.containsKey(TokensAnnotation.class)) {
            List<CoreLabel> tokens = annotation.get(TokensAnnotation.class);
            for (CoreLabel token : tokens) {
                boolean isWordStopword = stopwords.contains(token.word().toLowerCase());
                boolean isLemmaStopword = checkLemma ? stopwords.contains(token.word().toLowerCase()) : false;
                Pair<Boolean, Boolean> pair = Pair.makePair(isWordStopword, isLemmaStopword);
                token.set(StopwordAnnotator.class, pair);
            }
        }
}`



Regards,

**Comment by toliwa** [comment]
I recently updated my custom annotator to be compatible with 3.7.0, and had to change the requires() and requirementsSatisfied() methods for this, see here: [https://github.com/toliwa/CoreNLP-jMWE/blob/master/src/edu/stanford/nlp/pipeline/JMWEAnnotator.java](https://github.com/toliwa/CoreNLP-jMWE/blob/master/src/edu/stanford/nlp/pipeline/JMWEAnnotator.java)

Hope it helps.

**Comment by medvednic** [comment]
Thanks @toliwa I will look into it.
