### ISSUE TITLE
Euro symbol(€) converting to Dollar symbol($) 

### ISSUE THREAD

**Issue by MadhuKush** [stanfordnlp/CoreNLP#349]
Hi,

We were trying to extract the euro value from the file. The **stanford** is recognizing the money however its **converting** **€1000** to **$1000**. 
Could you please guide us on how to overcome this issue.

Thankyou

**Comment by J38** [comment]
If you turn off `normalizeCurrency` this problem will go away.

Sample command:

```java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit -file sample-sentence.txt -outputFormat text -tokenize.options "normalizeCurrency=false"```
