### ISSUE TITLE
SUTime Language Support

### ISSUE THREAD

**Issue by akeskiner** [stanfordnlp/CoreNLP#350]
Hi,

I want to use another language with SUTime (Turkish). While initializing TimeAnnotator, I set new property for sutime.rules. When I change months, days etc. it works perfectly. However, when I want to annotate Ninth April 2017 in Turkish (which is "Dokuzuncu Nisan 2017"), the phrase can not be captured. It's probably because numbers and ordinals are annotated differently and they are inside the source code. Is it possible to use my definitions of numbers and ordinals without changing the source code?

Thanks.

**Comment by J38** [comment]
Have you tried creating a comparable version of `english.sutime.txt`  and using that ?  I see a `BASIC_ORDINAL_MAP` which has mapping from `ninth ==> 9` ?  That rule file can be found in `edu/stanford/nlp/time/rules/english.sutime.txt` .
