### ISSUE TITLE
Sentiment depends on the name of an actor

### ISSUE THREAD

**Issue by sam-s** [stanfordnlp/CoreNLP#351]
I use [`stanford-corenlp-full-2016-10-31`](http://nlp.stanford.edu/software/stanford-corenlp-full-2016-10-31.zip) with Python (as described [here](http://stackoverflow.com/a/40496870/850781)), and I get surprising results:

**the sentiment of a sentence depends on which word is the subject**.

Specifically, I tested the following sentences: `X loves playing footballY` where `X` is a  name from this list:
```
names = ["John","Jane","Bill","Billy","Jenny","Foo","Bar","Baz","Quux","Mike",
         "Davie","Dave","David","Sandy","House","Bob","Robert","Sam"]
```
and `Y` is period, exclamation point, or empty.
Names were also supplied capitalized and lower-case.

The result is: all sentences were assigned `Positive` sentiment with the following exceptions:
```
Billy [Billy]: Neutral [Billy.]: Neutral
Bar [Bar]: Neutral [Bar.]: Neutral
Dave [Dave!]: Verypositive
David [David]: Neutral [David.]: Neutral
House [House]: Neutral [House.]: Neutral
```

It is expected that period and blank are less positive than `!`.

**However why is `Dave` so much more positive than `David`?**

See also [Stanford NLP sentiment ambiguous result](http://stackoverflow.com/q/42027119/850781).

**Comment by AngledLuffa** [comment]
Names can have sentiment attached to them as well.

There aren't very many training examples for any particular name, so any
one given name can some positive or negative associations based on random
chance.

**Comment by sam-s** [comment]
I would understand if all diminutives (`Dave`, `Billy` &c) had the same effect and full names, like `David` and `Bill` had also the same effect.
This is not what I observe: `David` is more negative than `John` and `Dave` is more positive than `Johnny`.

**Comment by AngledLuffa** [comment]
Everyone knows Johnny is a crappy version of a perfectly good name.  Sounds
like the system is working

**Comment by rakshitcr7** [comment]
I am getting the same problem sam-s. See the following results:
`Sentence: Tendulkar is a great batsman
Sentiment: 3
Sentence: David is a great batsman
Sentiment: 3
Sentence: Tendulkar is not a great batsman
Sentiment: 1
Sentence: David is not a great batsman
Sentiment: 2
Sentence: Shyam is not a great batsman
Sentiment: 1
Sentence: Dhoni loves playing football
Sentiment: 3
Sentence: John, Julia loves playing football
Sentiment: 3
Sentence: Drake loves playing football
Sentiment: 3
Sentence: David loves playing football
Sentiment: 2
Sentence: Virat is a good boy
Sentiment: 2
Sentence: David is a good boy
Sentiment: 2
Sentence: Virat is not a good boy
Sentiment: 1
Sentence: David is not a good boy
Sentiment: 2
Sentence: I love every moment of life
Sentiment: 3
Sentence: I hate every moment of life
Sentiment: 2
Sentence: I like dancing and listening to music
Sentiment: 3
Sentence: Messi does not like to play cricket
Sentiment: 1
Sentence: This was the worst movie I have ever seen
Sentiment: 0
Sentence: I really appreciated the movie
Sentiment: 1
Sentence: I really appreciate the movie
Sentiment: 3` 

Have you found a solution to this? I am considering training my own dataset.

**Comment by sam-s** [comment]
Maybe you need to exclude names from training, replacing them with the indicator that it's a name, possibly in a diminutive form?
E.g., `David`, `Bob` and `John` would be treated as the same attribute `Name-full`, while `Dave`, `Bobby` and `Johnny` would be replaced by `Name-diminutive`?
This would make the results more reasonable, while overcoming the low training set size, mentioned by [AngledLuffa](https://github.com/stanfordnlp/CoreNLP/issues/351#issuecomment-277377072).

**Comment by sam-s** [comment]
The same weird results with 3.8.0 (2017-06-09).

**Comment by AngledLuffa** [comment]
Unless the model changes, the results won't change.  I really don't see the
problem, though.  If a sentence has a positive or negative sentiment, the
names involved will get some effect from that rating, even if they are
labeled neutral in the training data.  The training data isn't extensive
enough for names which are actually neutral in everyday life to get a
completely neutral effect.  You can also imagine that even if names
themselves should be neutral, they have some effect on the overall
sentence.  Compare:

"I'm naming him Winston, after our country's greatest leader"
"I'm naming him Adolf, after our country's greatest leader"

**Comment by sam-s** [comment]
@AngledLuffa - yes, I see and appreciate your point. However, I respectfully disagree.
I urge You to consider the approach I outlined in [my 2017-05-04 comment](https://github.com/stanfordnlp/CoreNLP/issues/351#issuecomment-299211106) (`Name-full` vs `Name-diminutive`).

Thank you!

PS. The model is `stanford-corenlp-full-2017-06-09/stanford-corenlp-3.8.0-models.jar` and is, presumably, different from the previous one (`stanford-corenlp-full-2016-10-31/stanford-corenlp-3.7.0-models.jar`).

**Comment by AngledLuffa** [comment]
The model jar changing just indicates that something changed, not
necessarily the sentiment model.

The biggest problem with the approach of clustering all the names is that
probably no one at Stanford is going to put in that time, since the people
who worked on the sentiment model have all moved on.

**Comment by sam-s** [comment]
The model was not changed in 3.9.0 (2018-01-31) either. ;-(
@AngledLuffa: given that no one is working on sentiment at Stanford, maybe people outside might volunteer if you provide instructions on how to rebuild the model?
Thanks.

**Comment by J38** [comment]
I could see some potential in the approach being suggested here.  I am working on putting 3.9.0 up on to Maven, but after that I can try to give you some help.

**Comment by sam-s** [comment]
Note that parsing seems to be able to affect sentiment:
`"He is dumb and mean!"` is 
* `Negative` with `stanford-english-corenlp-2018-02-27-models.jar` which uses `edu/stanford/nlp/models/srparser/englishSR.ser.gz`
* `Verynegative` without it which uses `edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz` instead
It does not affect the outcome of _this_ issue though.
