### ISSUE TITLE
Enhanced++ Dependencies arc name descriptions

### ISSUE THREAD

**Issue by neilnelson** [stanfordnlp/CoreNLP#353]
The http://localhost:9000/ web-page that communicates with the edu.stanford.nlp.pipeline.StanfordCoreNLPServer provides a nice chart under Enhanced++ Dependencies with somewhat cryptic arc names.

Is there a table of arc names vs. descriptions?

**Comment by sebschu** [comment]
Yes, take a look at http://universaldependencies.org/en/dep/index.html and http://nlp.stanford.edu/~sebschu/pubs/schuster-manning-lrec2016.pdf for a description of the different relation types.
