### ISSUE TITLE
TokenRegex Combining Words

### ISSUE THREAD

**Issue by akeskiner** [stanfordnlp/CoreNLP#354]
Hello,
I want to match a phrase combining two words like "twentytwo" (without the space). Lets say that both "twenty" and "two" are annotated as NUMBER ner. Is there a way to achieve that? Thanks

**Comment by J38** [comment]
If you want to match the token twentytwo it will not be marked as NUMBER.  You can create a dictionary to cover cases like this using regexner: http://nlp.stanford.edu/software/regexner.html
