### ISSUE TITLE
Where is chinese.misc.distsim.crf.ser.gz ?

### ISSUE THREAD

**Issue by eromoe** [stanfordnlp/CoreNLP#358]
Hi, I am looking a tutorial about using stanfordnlp to cope Chinese.

In that tutorial, they use 2015-12-08 version，and mention need copy `chinese.misc.distsim.crf.ser.gz` and `chinese.misc.distsim.prop`  to `stanford-ner-2015-12-09/classifiers`.

Current corenlp version is 2016-10-31, and I only find `stanford-chinese-corenlp-2016-10-31-models.jar` without `chinese.misc.distsim.crf.ser.gz` and `chinese.misc.distsim.prop` on http://nlp.stanford.edu/software/CRF-NER.shtml

Does `stanford-chinese-corenlp-2016-10-31-models.jar` already contain that? Or I have to download from other place?

**Comment by J38** [comment]
Yes that model file is present in `stanford-chinese-corenlp-2016-10-31-models.jar`
