### ISSUE TITLE
Issue with NER and adjacent names and same type.

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#360]
Supposed to have in my input text a NER output like the following

<img width="1174" alt="schermata 2017-02-22 alle 15 53 29" src="https://cloud.githubusercontent.com/assets/163333/23216676/176d9c36-f917-11e6-9c01-d73a79bbf834.png">

We can see how it is wrong with the consecutive keywords `Quavo Ratatouille Run` that are recognized as `TYPE=PERSON`, while that classification is for `Quavo Ratatouille` of course.

What happens is the two or more words, that are consecutive and having the same type will be grouped by that type.

 In this specific case we have a line break separator in the text, so the NER module should consider `Run` as not consecutive. 

Is there a way to achieve that?

**Comment by J38** [comment]
You can treat each line of the lyrics as a separate sentence so the NER will not find entities that are on multiple lines.  It seems plausible most entities will be contained on a single line.  You will need to apply sentence splitting to your input text, but you can just use newlines to create sentences.

**Comment by loretoparisi** [comment]
@J38 In My case I have a structure like a song so I have `\n` as sentence separator and `\n\n` and lyrics separator like:

```
I used to rule the world
Seas would rise when I gave the word
Now in the morning I sleep aloneSweep the streets I used to own

I used to roll the dice
Feel the fear in my enemy's eyes
Listen as the crowd would sing
"Now the old king is dead! Long live the king!"
```

So what I have tried is

```
"ssplit.newlineIsSentenceBreak": "always" 
```

and I get when collecting the sentences for brat

```
I used to rule the world
Seas would rise when I gave the word
Now in the morning I sleep aloneSweep the streets I used to own
I used to roll the dice
Feel the fear in my enemy 's eyes
Listen as the crowd would sing
" Now the old king is dead !
Long live the king ! "
```

So it is better that before using `ssplit.newlineIsSentenceBreak": "always"`, but I would like to have 
this strophe


I used to rule the world`\n`
Seas would rise when I gave the word`\n`
Now in the morning I sleep aloneSweep the streets I used to own`\n\n`

as a single sentence, so that `data.sentences` would be 2 in this case.

I'm using a customized function of the CoreNLP brat utils:

```
function createAnnotations(data,sentencesSeparator) {
                currentSentences = data.sentences;  // GLOBAL
                data.sentences.forEach(function(sentence) {
                    for (var i = 0; i < sentence.tokens.length; ++i) {
                    var token = sentence.tokens[i];
                    var word = token.word;
                    if (!(typeof tokensMap[word] === "undefined")) {
                        word = tokensMap[word];
                    }
                    if (i > 0) { currentText.push(' '); }
                    token.characterOffsetBegin = currentText.length;
                    for (var j = 0; j < word.length; ++j) {
                        currentText.push(word[j]);
                    }
                    token.characterOffsetEnd = currentText.length;
                    }
                    currentText.push(sentencesSeparator);
                });
                currentText = currentText.join('');
            }//createAnnotations
```

with a `\n` sentence separator

**Comment by J38** [comment]
Did you try `"ssplit.newlineIsSentenceBreak": "two"`

Documentation on sentence splitter: http://stanfordnlp.github.io/CoreNLP/ssplit.html

**Comment by loretoparisi** [comment]
@J38 Hello,
so the option `"ssplit.newlineIsSentenceBreak": "two"` 
was my first option, but it didn't work well since the input text like

***
I used to rule the world`\n`
Seas would rise when I gave the word`\n`
Now in the morning I sleep aloneSweep the streets I used to own`\n\n`
***

resulted as

***
I used to rule the world Seas would rise when I gave the word Now in the morning I sleep aloneSweep the streets I used to own`\n`
***

So my last option was `"ssplit.newlineIsSentenceBreak": "always" `
