### ISSUE TITLE
Property ner.language not recognized: ENGLISH

### ISSUE THREAD

**Issue by marty30** [stanfordnlp/CoreNLP#361]
Hi all,

I am trying to use the NERCombinedClassifier to classify a text. When I used the default classifier bundled with the stanford-ner.jar I get the following error: Property ner.language not recognized: ENGLISH. Looking into this I find that it seems like a merge error since this error message has nothing to do with the actual if statement surrounding it:
`this.nerLanguage = NER_LANGUAGE_DEFAULT;
    // build the nsc, note that initProps should be set by ClassifierCombiner
    this.nsc = new NumberSequenceClassifier(new Properties(), useSUTime, props);
    if (PropertiesUtils.getBool(props, NERClassifierCombiner.APPLY_GAZETTE_PROPERTY, NERClassifierCombiner.APPLY_GAZETTE_DEFAULT) ) {
      this.gazetteMapping = readRegexnerGazette(DefaultPaths.DEFAULT_NER_GAZETTE_MAPPING);
    } else {
      this.gazetteMapping = Collections.emptyMap();
      log.fatal("Property ner.language not recognized: " + nerLanguage);
    }`

I am getting this error by instantiating the classifier:
`Properties props = new Properties();
                props.load(new FileInputStream(classifierLocation +serializedClassifier.replace(".ncc.ser.gz",".prop")));
                classifier = NERClassifierCombiner.getClassifier(classifierLocation + serializedClassifier, props);`

I have not used this repo to get the jar, but did find the same code in the repo. Original download: http://nlp.stanford.edu/software/CRF-NER.shtml#Download

**Comment by J38** [comment]
Ok I will remove that error statement, I do not know why it's there.  In general did everything else work ok for you though?
