### ISSUE TITLE
NER: Timeout in loading fonts

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#362]
Some fonts requested by brat visualizer (Visualizer.js) are not available in the cloud storage that is used by CoreNLP like

```
https://storage.googleapis.com/corenlp/static/fonts/Liberation_Sans-Regular.ttf
```

This refers to `visualizer.js` (line 3073) that tries to load default fonts:

```javascript
var webFontConfig = {
          custom: {
            families: [
              'Astloch',
              'PT Sans Caption',
              //        'Ubuntu',
              'Liberation Sans'
            ],
            /* For some cases, in particular for embedding, we need to
              allow for fonts being hosted elsewhere */
            urls: webFontURLs !== undefined ? webFontURLs : [
              'static/fonts/Astloch-Bold.ttf',
              'static/fonts/PT_Sans-Caption-Web-Regular.ttf',
              //
              'static/fonts/Liberation_Sans-Regular.ttf'
            ],
          },
          active: proceedWithFonts,
          inactive: proceedWithFonts,
          fontactive: function(fontFamily, fontDescription) {
            // Note: Enable for font debugging
            //console.log("font active: ", fontFamily, fontDescription);
          },
          fontloading: function(fontFamily, fontDescription) {
            // Note: Enable for font debugging
            //console.log("font loading:", fontFamily, fontDescription);
          },
        };
        WebFont.load(webFontConfig);
```

This will result in a 404 error and a `Timeout in loading fonts` error.
Would it be possibile to add those fonts to the cloud storage to avoid it?

The fonts that are requested by brat embed as described here (http://brat.nlplab.org/embed.html) are

```javascript
var webFontURLs = [
    bratLocation + '/static/fonts/Astloch-Bold.ttf',
    bratLocation + '/static/fonts/PT_Sans-Caption-Web-Regular.ttf',
    bratLocation + '/static/fonts/Liberation_Sans-Regular.ttf'
];
```
Thank you.

**Comment by loretoparisi** [comment]
closing this since I have solved with custom javascript.

**Comment by szitnik** [comment]
Hey,

Have you solved the font loading to load them correctly or have you just decreased the timeout? 

I set the timeout to 1s in line 5 of visualizer.js. If I set less, an additional error may happen as the text might not be loaded yet and brat's sentence splitter cannot get the text length.

Slavko

**Comment by szitnik** [comment]
Maybe a bit better solution: remove timeout for font loading and just call function proceedWIthFonts() - lines around 3104 in visualizer.js?

**Comment by loretoparisi** [comment]
@szitnik Yes I did in that way thank you!
