### ISSUE TITLE
coref or dcoref gives no result 

### ISSUE THREAD

**Issue by andrewufrank** [stanfordnlp/CoreNLP#366]
i have a problem that for specific input no coref tags are produced (for other inputs with the same server and command, the corefs are properly output), just this strange input is not handled

````
.
000.
THROUGH THE LOOKING-GLASS .

````

with the command 
    wget --post-file=/home/frank/Scratch/converts/in.text 'localhost:9000/?properties={"annotators":"tokenize,ssplit,pos,lemma,ner,parse,dcoref","outputFormat":"xml"}' -O in.xml

and the server 

    java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000

from 

    /stanford-corenlp-full-2016-10-31

the resulting xml file does not contain a <coref></coref> entry, which i assume to be empty, but still the tags should be there (possibly even <coreference><coreference></coreference></coreference>. this anomaly makes parsing the xml file difficult, because it requires handling the case where no coreference tag is found.

**Comment by J38** [comment]
If you add `"output.printSingletonEntities": "true"` this should fix your specific case.

In the case where there are no coref mentions of any sort, I think there will still be an issue of there being no tags for coref in the xml output.

**Comment by andrewufrank** [comment]
thank you for the work around - no urgency with the fix.
andrew
