### ISSUE TITLE
NERCombinerAnnotator unused variable

### ISSUE THREAD

**Issue by ziorufus** [stanfordnlp/CoreNLP#371]
The NER annotator loads a lot of memory when the sentence is too long, therefore it should be useful to add a limit.

Indeed, the limit is already there, in `NERCombinerAnnotator.java`, and it is called `maxSentenceLength`. Unfortunately, it is never used (sic!).

On lines 111/112 you should add:

```
        // line 111 --- List<CoreLabel> tokens = sentence.get(CoreAnnotations.TokensAnnotation.class);
        if (maxSentenceLength > 0 && tokens.size() > maxSentenceLength) {

            // For compatibility with dcoref
            for (CoreLabel token : tokens) {
                token.set(CoreAnnotations.NamedEntityTagAnnotation.class, "O");
                token.set(CoreAnnotations.NormalizedNamedEntityTagAnnotation.class, "O");
            }
            return;
        }
        // line 112 --- List<CoreLabel> output; // only used if try assignment works.
```

This code skip a sentence (and load "O" as NER into its tokens, for compatibility) when the sentence is longer than `maxSentenceLength` tokens.

**Comment by J38** [comment]
Okay I added a check for the sentence length!
