### ISSUE TITLE
CoNLL file pattern problem

### ISSUE THREAD

**Issue by dragoon** [stanfordnlp/CoreNLP#372]
Hello,
I have a problem running stanford CoreNLP on my CoNLL generated files.
My files have a names like ``cctv_0005.v9_auto_mentions_conll``, while in ``DocumentMaker.getDocumentReader`` function there is a setting ``options.setFilter(".*_auto_conll$");``, which does not correspond to my pattern.
Is there a problem here?

The same problem appears to be in ``CoNLL2011DocumentReader``, but with gold files: ``this(".*_gold_conll$");``

**Comment by J38** [comment]
I've added a new property to let you set whatever pattern you want for files.

`coref.conllFileFilter = .*conll$" `

for instance will match files ending in `conll` such as `eng_0012.conll`
