### ISSUE TITLE
Is this word "cost" in this sentence not a noun ?

### ISSUE THREAD

**Issue by HarishAtGitHub** [stanfordnlp/CoreNLP#374]
I gave the sentence "list the chairs that have cost lesser than three hundred USD" to POS tagger

and got the following output

![1](https://cloud.githubusercontent.com/assets/5524260/23585286/5c0b35fe-012f-11e7-8484-68b5f1ca8c52.png)

Is this word "cost" in this sentence not a noun ?

**Comment by HarishAtGitHub** [comment]
Forgive if my english is grammatically wrong.

**Comment by J38** [comment]
You are right this is an error by the POS tagging system.  Our POS tagging system only has an accuracy of around ~97% and it does make errors some times.  You can learn more here: http://nlp.stanford.edu/software/tagger.shtml
