### ISSUE TITLE
Can CoreNLP server run without internet connection ?

### ISSUE THREAD

**Issue by xcapt** [stanfordnlp/CoreNLP#384]
When working offline (Windows version), CoreNLP server does not seem to work (API not responding), did anyone experience the same ?

CoreNLP server runs as:
java -Xmx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000

**Comment by xcapt** [comment]
hmm only web client is not working properly , API is ok when I use 127.0.0.1 instead of localhost :)

**Comment by manning** [comment]
Yes, should work. Web client should work too. Commonest cases of failure that I'm aware of relate to Chrome and things defaulting to https. See, e.g.: https://superuser.com/questions/961532/chrome-localhost-connection-refused
