### ISSUE TITLE
SUTime NIGHT constant range end time is before start time

### ISSUE THREAD

**Issue by rickystillwell** [stanfordnlp/CoreNLP#39]
The NIGHT constant in SUTime.java currently has the range between hour (19:00 - 5:00) giving it a duration of -14 hours

REPRODUCE:
http://nlp.stanford.edu:8080/sutime/process
Input: "tomorrow night"
Output: <TIMEX3 range="(2014-12-02T19:00:00.000,2014-12-02T05,PT-14H)" tid="t3" type="TIME" value="2014-12-02TNI">tomorrow night</TIMEX3>

![image](https://cloud.githubusercontent.com/assets/8366770/5254570/317870d2-7977-11e4-893e-5b5145f096ab.png)

BUG LOCATION:
edu.stanford.nlp.time.SUTime.java:724
  public static final Time NIGHT = createTemporal(StandardTemporalType.TIME_OF_DAY, "NI", new InexactTime(new Range(new InexactTime(new Partial(DateTimeFieldType.hourOfDay(), 19)), new InexactTime(new Partial(DateTimeFieldType
      .hourOfDay(), 5)))));

FIX SHOULD BE SOMETING LIKE:
  public static final Time NIGHT = createTemporal(StandardTemporalType.TIME_OF_DAY, "NI", new InexactTime(new Range(new InexactTime(new Partial(DateTimeFieldType.hourOfDay(), 19)), new InexactTime(new Partial(DateTimeFieldType
      .hourOfDay(), 24)))));

**Comment by manning** [comment]
A fix for this was made by @angelxuanchang  in commit 0e1478995eda17e344e8d4c746bf740b83d3894d on github and will be in the next release ... soon.
