### ISSUE TITLE
running multiple copies of corenlp - address already in use for liveness server

### ISSUE THREAD

**Issue by andrewufrank** [stanfordnlp/CoreNLP#391]
i try to run on a server multiple copies of corenlp for different languages, each with a different port. it works, but i get an error message when starting the second corenlp process:

ERROR Could not start liveness server. This will probably result in very bad things happening soon. - java.net.BindException: Address already in use

what is the liveness server doing? why is it always starting on port 9000, even when the process starting is on a different port (e.g. 9001 for a german corenlp process). 

the error message is ignored and the process seems to work ok.

**Comment by gangeli** [comment]
Yes, this actually happens to be ok for most uses; it's safe to ignore the error. These are there for managing the server's lifecycle in, e.g., Kubernetes -- though even for that I should merge the endpoints back into the main server rather than having them on a different port.

**Comment by andrewufrank** [comment]
the problem happens only because even when using a different port, the liveness server port remains the same. if you can change this with one of the next releases it will reduce an unnecessary warning for new users. 
thank you for your quick reply!

**Comment by J38** [comment]
Okay this should be fixed now.
