### ISSUE TITLE
lemmatization for german incorrect

### ISSUE THREAD

**Issue by andrewufrank** [stanfordnlp/CoreNLP#397]
i use a coreNLP server for german (version 2016-10-31) which works ok but the lemmas included in the output are off. for examle i see `ging`as a lemma (correct would be `gehen`) etc. 

`<token id="2"><word>ging</word><lemma>ging</lemma><CharacterOffsetBegin>23..27</CharacterOffsetEnd><POS>VVFIN< ....`

internally, the parser must have a better lemmatizatin to determine (correctly) for the parse `(VVFIN ging)`. i assume this is a bug somewhere which does not copy the correct lemmas into the output file. 

a bugfix/patch would be greatly appreciated!

other issue with the german parser: requires `latin1` encoding ...

**Comment by sebschu** [comment]
Unfortunately, we currently don't have a lemmatizer for German and no plans to implement one in the near future. Neither the English nor any other parser make use of the lemmatizer -- they just work off the surface forms.
