### ISSUE TITLE
Chinese CORENLP Parsing : Parse per line

### ISSUE THREAD

**Issue by rafael75012** [stanfordnlp/CoreNLP#398]
Hi, 

I use the parser of CoreNLP for Chinese, here is my commandline : 
`java -mx2100m -cp stanford-corenlp.jar:stanford-chinese-corenlp-2016-10-31-models.jar edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-chinese.properties -annotators tokenize,ssplit,pos,depparse -file /Users/xx/xx/xx/xx/xx/myfile.txt -outputFormat conll -ssplit.eolonly`

The option ssplit.eolonly should help to provide a parsing made line by line. But it gives one tree for all the file. If I don't add this option, it will parse sentence by sentence.

How can I fix that? I want that the parser splits at each "\n".

**Comment by J38** [comment]
There has been a long term problem with this option not working for Chinese.  We will work on fixing it but for the moment this is just a known bug.

**Comment by rafael75012** [comment]
Thank you

**Comment by J38** [comment]
Great news, this issue has been resolved now!  You should be able to process Chinese sentences one per line now!
