### ISSUE TITLE
Stanford Parser for Processing French Text in GATE Developer.

### ISSUE THREAD

**Issue by LearnOut** [stanfordnlp/CoreNLP#400]
Hi, 
I need to process French text in Gate Developer 8.2. I am giving frenchFactored.ser.gzas URL to parameter parseFile for the StanfordParser processing resource . Kindly suggest what shall be given for tlppClass String?
The pipeline has Stanford PTB Tokenizer , ANNIE Sentence Splitter and Stanford POS Tagger such the the tagger parameter modelFile URL is file:/home/stanford-french-corenlp-2016-10-31-models/edu/stanford/nlp/models/pos-tagger/french/french.tagger.

**Comment by J38** [comment]
I don't know anything about the GATE-Stanford CoreNLP integration.

But I would suggest this class: `edu.stanford.nlp.parser.lexparser.FrenchTreebankParserParams`
