### ISSUE TITLE
Is -ner.model ignored when starting the corenlp server?

### ISSUE THREAD

**Issue by dandelionred** [stanfordnlp/CoreNLP#404]
I want the default annotator to be `ner` and only `3class` model to be used for it. I start the server as
```bash
$ java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000 -ner.model edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz -annotators ner
```

When I curl a request 
```
$ curl 'http://localhost:9000/' --data 'President Obama is male.'
```

I see in the console all `ner` models are loaded:
```
[pool-1-thread-1] INFO CoreNLP - [/127.0.0.1:50632] API call w/annotators tokenize,ssplit,pos,lemma,ner
President Obama is male.
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[pool-1-thread-1] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.7 sec].
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[pool-1-thread-1] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.6 sec].
[pool-1-thread-1] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.2 sec].
[pool-1-thread-1] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.5 sec].
[pool-1-thread-1] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
```

How can I force unwanted `ner` models not to load?

**Comment by J38** [comment]
You need to provide a .properties file to the server with the `-serverProperties` option.  The `-ner.model` property is meaningless to the server.

**Comment by dandelionred** [comment]
> The -ner.model property is meaningless to the server.

Then there is inconsistency in options to the server because it accepts for example `-parse.model edu/stanford/nlp/models/srparser/englishSR.ser.gz`

**Comment by J38** [comment]
The server defaults to `englishSR.ser.gz` if it can find it in the CLASSPATH.

If you try starting the server with `parse.model` set to a specialized path you should see it still load the shift reduce model (or the standard English parsing model if the shift reduce model is not available).

**Comment by dandelionred** [comment]
So it was my misunderstanding.

I ran pure stanford-corenlp-full-2016-10-31 at first and it was loading `englishPCFG.ser.gz`:
```
[pool-1-thread-1] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.4 sec].
```

Next I added stanford-english-corenlp-2016-10-31-models.jar to the classpath and set `-parse.model edu/stanford/nlp/models/srparser/englishSR.ser.gz` and it started to load `englishSR.ser.gz`. So the reason is because `englishSR.ser.gz` has appeared on the classpath no matter the `-parse.model` value in the cmd line.

Thanks for your time )

**Comment by nadavb** [comment]
Do you know what tagger does the demo page use? http://nlp.stanford.edu:8080/parser/index.jsp
I can't reproduce the tagging results, even if I use the StanfordCoreNLPServer with passer englishPCFG.ser.gz and english-bidirectional-distsim.tagger
