### ISSUE TITLE
CoreNLP Dedicated Server

### ISSUE THREAD

**Issue by certifiedvirgo** [stanfordnlp/CoreNLP#410]
I am a part of a team participating in the development of an application that uses CoreNLP and I'm responsible for configuring a dedicated server but... I don't know how the software works. So, after following the instructions on their site (https://stanfordnlp.github.io/CoreNLP/corenlp-server.html#dedicated-server), I'm not confident I have completed the task with respect to what my project manager is looking for. He wants to bring the data from the Stanford CoreNLP server down to our local server to eliminate the need to leave our local network to analyze ingested data.

**Comment by J38** [comment]
Have you been able to successfully issue a request to the server running in your local network and get back a response?

**Comment by certifiedvirgo** [comment]
Before I answer any questions, I'd like to make sure you understand my situation. I have been tasked to configure a dedicated server for CoreNLP and my understanding was it should be a standalone instance of CoreNLP that runs the service continuously. I believed we would need to call to that server instead of the servers hosted by Stanford.


To do this, I created a Hyper V Ubuntu Server environment and attempted to initiate a request to my server. I don't know how to do that.


Yesterday, my Project Manager brought to my attention the concept of running our scripts on our dedicated server. I never considered that. I was trying to place the server ip in the code to direct the requests to the server which proved unsuccessful.


I am now installing all the necessary packages on my dedicated sever to run the requests and all other related Python code. Is this what I should be doing?


________________________________

**Comment by certifiedvirgo** [comment]
Are you able to provide any insight?

________________________________

**Comment by J38** [comment]
Here's a basic description:

1. Download Stanford CoreNLP here: https://stanfordnlp.github.io/CoreNLP/download.html

2. Start the server with this command: 

`java -Xmx4g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000`

3. On the same machine that you are running the server, you can issue requests to that server.

Here is some basic Python code:

```
import requests

url = 'http://localhost:9000/?'
request_params = {'outputFormat': 'json'}
# docs should be a list with the String contents of each document
docs = ["text of document 1", "text of document 2"]
# list to store json results
for doc in docs:
    r = requests.post(url,data=doc,params=request_params)
    results.append(r.json())

# results will now have the json response for each document
```

You could also install and use the stanza library to issue requests to StanfordCoreNLP

If you want to run the server on one machine and make requests from a different machine, you must alter the line `url = 'http://localhost:9000/?'` line accordingly.

**Comment by certifiedvirgo** [comment]
Thank you for your response.

If you start the server with 'java -Xmx4g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000' then what is 'start service corenlp start' for?

Regards,

Gregory Owens

**Comment by J38** [comment]
The java command I provided will start the server.  If you've successfully set up the dedicated server and run this command: `sudo service corenlp start` that would also start the server.

I've never set up a dedicated server and I just use the Java command to manually start it, but I don't run continuous services, so in your use case you might prefer the dedicated server setup.

If the server is running properly you should get back json with NLP annotations of documents when running the small Python code I supplied.  Note that in the dedicated server instructions it is setting it up to listen on port 80.

**Comment by certifiedvirgo** [comment]
I'm going to prepare a diagram to show you what I'm trying to acheive. I don't think we are able to achieve what we want.

Get Outlook for Android

**Comment by certifiedvirgo** [comment]
What we want to do is eliminate the need to travel outside of our network to process all document analysis and parsing in house using CoreNLP. Below is our intended network configuration:

[cid:image002.jpg@01D2BA8A.F192D230]
With this configuration, we will process all data in house with no requirement to contact the Stanford substantiation of CoreNLP.

Below is what I believe to be the requirement:

[cid:image001.jpg@01D2BA8B.6237F2E0]
Is it possible, with a dedicated server, to eliminate the requirement of communicating with the Stanford CoreNLP Server in CA? My understanding of a dedicated server so far is a server who's sole responsibility is to send and receive the requests to the Stanford server in CA. We want a server with all the necessary data to respond to it's own requests. Is that something that can be done?


Gregory Owens
IT Systems Engineer
ALEX - Alternative Experts
3600 Pointe Center Court, Suite 160
Dumfries, Virginia 22026
Direct 571.261.6458
Email gowens@alexinc.com<mailto:gowens@alexinc.com>

www.alexinc.com<http://www.alexinc.com/>
SBA 8(a), WOSB, and EDWOSB Certified
