### ISSUE TITLE
Subjectivity detection API?

### ISSUE THREAD

**Issue by EasonSun** [stanfordnlp/CoreNLP#412]
Does coreNLP comes with subjectivity detection / genre classification? It seems the sentiment analysis tool cannot do this?

Thank you for your work!

**Comment by J38** [comment]
No unfortunately at this time Stanford CoreNLP does not have any capability for this.

**Comment by J38** [comment]
The closest thing would be that you can train a classifier to do such a thing, or perhaps the sentiment pipeline.  You would have to come up with the training data on your own.  More info about the classifier here: https://nlp.stanford.edu/software/classifier.html
