### ISSUE TITLE
originalText is not reliable

### ISSUE THREAD

**Issue by dandelionred** [stanfordnlp/CoreNLP#413]
I  send "2 1/2" string to it (I explicitly write the space as \x20) and in output I get a no-break space (utf8=c2 a0)  between "2" and  "1/2" under `originalText`:

```bash
$ echo -e '2\x201/2' | java -cp '*' edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit -outputFormat json 2>/dev/null | grep originalText | xxd
0000000: 2020 2020 2020 2020 2020 226f 7269 6769            "origi
0000010: 6e61 6c54 6578 7422 3a20 2232 c2a0 312f  nalText": "2..1/
0000020: 3222 2c0a                                2",.
```

**Comment by manning** [comment]
Thanks, you're right. This has been a long-standing error in the originalText of mixed fractions. 

Correcting in HEAD. Unfortunately, it won't make the next release. (But will make the one after that.)
