### ISSUE TITLE
dependency parsing line by line

### ISSUE THREAD

**Issue by zhang-wen** [stanfordnlp/CoreNLP#415]
when i use following command to parse a text file which contains 10 sentences.

java -Xmx2g -cp "*" edu.stanford.nlp.parser.nndep.DependencyParser -model edu/stanford/nlp/models/parser/nndep/CTB_CoNLL_params.txt.gz -tagger.model edu/stanford/nlp/models/pos-tagger/chinese-distsim/chinese-distsim.tagger -textFile input.txt -outFile input.txt.out

but one sentence in the text file have no period punctuation, i found if one sentence do not end with period punctuation, the parser will not treat it as one sentence. i do not know why.

the old version of parser can specify the delimiter by using -sentences newline parameter, how do i specify the delimiter in the new version of parser ? 

thank you very much !

**Comment by muzny** [comment]
If you just want to dependency parse the sentences, you should try running through StanfordCoreNLP as follows:

`java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,depparse -file input.txt -props sampleprops.props`

Then in `sampleprops.props` put the line `ssplit.eolonly=true`

Read more about the command line tool and props files here: http://stanfordnlp.github.io/CoreNLP/api.html
and about sentence splitting: http://stanfordnlp.github.io/CoreNLP/ssplit.html

**Comment by J38** [comment]
Warning: `ssplit.eolonly` doesn't work right now for Chinese.  I am working on fixing this for Stanford CoreNLP 3.8.0.

**Comment by zhang-wen** [comment]
@muzny @J38 thank you for replying.

i have another question, if i do not use CoreNLP, no problem for parse line by line , even no period punctuation ends in one sentence.

my question is that is there some different between the POS taggers, dependency parsers in the two directories of **stanford-corenlp-full-2016-10-31/** and **stanford-parser-full-2016-10-31/**  ?

**Comment by J38** [comment]
The models should be the same.

**Comment by zhang-wen** [comment]
@J38  thank you very much, i works if i use stanford-parser-full-2016-10-31/    , corenlp still does not works for me..

**Comment by zhang-wen** [comment]
hello, everyone, i found a string thing, when i parsed chinese sentence by using standford denpendency parser, there are some (not very many) dependency labels which is chinese characters and there are duplicate dependency edges，i selected some examples from the parsing result as following:

关于(规划-28, 司法部-14)
关于(规划-62, 司法部-48)

is this normal ?
i do not know why ? can some one explain this for me ? any reply will be appreciated.
