### ISSUE TITLE
CoreNLP server no response

### ISSUE THREAD

**Issue by gravin** [stanfordnlp/CoreNLP#416]
i did as http://stanfordnlp.github.io/CoreNLP/corenlp-server.html
start the server
# Run the server using all jars in the current directory (e.g., the CoreNLP home directory)
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000

and write java api to call it

// creates a StanfordCoreNLP object with POS tagging, lemmatization, NER, parsing, and coreference resolution
Properties props = new Properties();
props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
StanfordCoreNLPClient pipeline = new StanfordCoreNLPClient(props, "localhost", 9000, 2);
// read some text in the text variable
String text = ... // Add your text here!
// create an empty Annotation just with the given text
Annotation document = new Annotation(text);
// run all Annotators on this text
pipeline.annotate(document);
.........................................
	              // display the token-level annotations
	              String[] tokenAnnotations = {
	                      "Text", "PartOfSpeech", "Lemma", "Answer", "NamedEntityTag",
	                      "CharacterOffsetBegin", "CharacterOffsetEnd", "NormalizedNamedEntityTag",
	                      "Timex", "TrueCase", "TrueCaseText", "SentimentClass", "WikipediaEntity" };
	              for (CoreLabel token: tokens) {
	            	  out.print(token.word()+","+token.tag()+","+token.ner());
	            	  out.println();
	            	  out.print(token.toShorterString(tokenAnnotations));
	            	  out.println();
	              }

but no response at all,  
but when i shutdown server, it will give some output at that time

**Comment by J38** [comment]
You need to change "localhost" to ""http://localhost"
