### ISSUE TITLE
RelationExtractorAnnotator.java

### ISSUE THREAD

**Issue by swapnilkumbhar1602** [stanfordnlp/CoreNLP#422]
please explain the output of the RelationExtractorAnnotator.java 

what are the entities and their relations

**Comment by J38** [comment]
Here is an example command for using the old relation extractor.  If you look at the output on an example sentence you will see info about EntityMention's and RelationMention's.  A RelationMention represents a relation such as "Live_In" between two EntityMention's.

`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,parse,ner,relation -file example.txt -outputFormat text`
