### ISSUE TITLE
there are chinese label when i parsed chinese sentence by using standford dependency parser

### ISSUE THREAD

**Issue by zhang-wen** [stanfordnlp/CoreNLP#425]
hello, everyone, i found a strange thing, when i parsed chinese sentence by using standford denpendency parser, there are some (not very many) dependency labels which is chinese characters and there are duplicate dependency edges，i selected some examples from the parsing result as following:

`
关于(规划-28, 司法部-14)
`
`
关于(规划-62, 司法部-48)
`

is this normal ?
i do not know why ? can some one explain this for me ? any reply will be appreciated.

**Comment by J38** [comment]
Could you provide the sentence that produced this result?

**Comment by zhang-wen** [comment]
@J38  sure , this it is

( 授权 发布 ) 中共 中央 国务院 关于 转发 " 中央 宣传部 , 司法部 关于 在 公民 中 开展 法制 宣传 教育 的 第四 个 五 年 规划 " 的 通知 新华社 北京 5月 27日 电 中共 中央 国务

please check it . thank you!

**Comment by J38** [comment]
I ran this command using Stanford CoreNLP 3.7.0 and the 3.7.0 Chinese models jar:

`java -Xmx4g edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-chinese.properties -annotators tokenize,ssplit,pos,lemma,ner,depparse -file example.txt -outputFormat text`

I didn't see any edges with Chinese text.  Sometimes edges are produced with `dep`
