### ISSUE TITLE
lexical parser grammar

### ISSUE THREAD

**Issue by siddharthBohra** [stanfordnlp/CoreNLP#426]
Hi,
I ran the parserDemo program from CoreNLP and i get the output in pennTree 
(ROOT
  (S
    (NP (DT This))
    (VP (VBZ is)
      (NP (DT an) (JJ easy) (NN sentence)))
    (. .)))
Is there a way to get in grammar format something like this 
S -> NP VP
  NP -> Det N
  PP -> P NP
  VP -> 'slept' | 'saw' NP | 'walked' PP
  Det -> 'the' | 'a'
  N -> 'man' | 'park' | 'dog'
  P -> 'in' | 'with'.

Thanks in Advance.

**Comment by J38** [comment]
At this time I don't believe we support that.
