### ISSUE TITLE
Do Stanford TokensRegex support other language like Chinese?

### ISSUE THREAD

**Issue by rickyngan** [stanfordnlp/CoreNLP#432]
As title, I can't find any docs on other language in 
https://nlp.stanford.edu/software/tokensregex.shtml

**Comment by J38** [comment]
Yes.  We have examples of Chinese TokensRegex rules in the Chinese models jar.  You should look at this file for instance: `edu/stanford/nlp/models/kbp/chinese/tokensregex/per:employee_of.rules`
