### ISSUE TITLE
Option to suppress logging

### ISSUE THREAD

**Issue by DavidNemeskey** [stanfordnlp/CoreNLP#433]
When run, the server prints a lot of logging messages to stderr; the most pesky is logging every single API call. It would be nice having an option that turned logging off. Even more useful would be an option to specify the logging level, so that if one is interested in startup and shutdown messages, but not in the individual API calls, could have their cake and eat it.

Of course, this latter use-case is not relevant until all log messages are on the INFO level...

**Comment by gangeli** [comment]
The `-quiet` flag to the server will suppress the log messages to stdout. If you have slf4j in your classpath, logs should be directed there, and you can suppress them in the usual way though slf4j.

**Comment by DavidNemeskey** [comment]
OK, 3 questions then:
1. What would that "usual way" be?
1. So if I don't have slf4j in the class path, then these logs will disappear?
1. This should be documented somewhere, because `corenlp.sh` includes all `jar`s in the directory, including slf4j, so by default users get the excessive logging.

**Comment by gangeli** [comment]
Responding to each:

1. I guess the combination of the `-quiet` flag and setting log levels through slf4j is the "usual way."

2. You have to have slf4j in your classpath to make the logs disappear, by setting the appropriate slf4j log level. For example: `-Dorg.slf4j.simpleLogger.defaultLogLevel=error` from, e.g., http://stackoverflow.com/questions/14544991/how-to-configure-slf4j-simple

3. I'll add a bit of documentation on the server page for the `-quiet` flag.

**Comment by DavidNemeskey** [comment]
@gangeli Thanks, great. :)

**Comment by nadavb** [comment]
I tried adding the `-quiet` to the Java command line when running the StanfordCoreNLPServer.
I suppressed the prints of the text input, but I still get:
`[/127.0.0.1:60508] API call w/annotators tokenize,ssplit,pos,parse`
printout.
Prints may slow down and reduce performance. Is there way to stop these prints?
