### ISSUE TITLE
"Transfer learning" on CFClassifier

### ISSUE THREAD

**Issue by afcruzs** [stanfordnlp/CoreNLP#434]
Is it possible to do 'transfer learning' on the pre trained CRFClassifier?. I want to show additional examples to the classifier and that it fit the parameters. There is a method called train on CRFClassifier.java, but it is not clear to me if it start again or if it uses the previous weights.

**Comment by J38** [comment]
CRFClassifier is not set up to do this, but with some small modifications you could alter it to do this.  You would need to load your original CRFClassifier, and then initialize the weights for the new about to be trained CRFClassifier from the original one.  Where the weights and feature indices are stored is around line 144.  The logic for training is around line 3001.
