### ISSUE TITLE
CRFClassifier classifySentence and classify difference

### ISSUE THREAD

**Issue by toliwa** [stanfordnlp/CoreNLP#437]
I noticed something similar as was [posted](https://mailman.stanford.edu/pipermail/java-nlp-user/2017-May/008098.html) recently on the `java-nlp-user` CoreNLP mailinglist.

Following the [Stanford NER CRF FAQ](https://nlp.stanford.edu/software/crf-faq.html) with the same sample properties, I annotated my corpus and created my own classifier.

Using only the CLI, I noticed that the output of the named entities differs, depending on if I use the textFile or testFile arguments:

1. `java -cp stanford-ner.jar:lib/* edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier my-crf-ser.gz -textFile myFile.txt`
or
2. `java -cp stanford-ner.jar:lib/* edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier my-crf-ser.gz -testFile myFile-tokenized.tsv`

Using the `ner-gui.sh` or using the API and `List<IN> classify(List<IN> document)` also gives the entities as in 1. (using -textFile). I noticed that the quality of recognized named entities is worse here.

However, as @manning mentioned [on the mailing list](https://mailman.stanford.edu/pipermail/java-nlp-user/2017-May/008098.html), there is the method `List<IN> classifySentence(List<? extends HasWord> tokenSequence)`. I created some code that just reads my text file, tokenizes it and passes it to the classifier to `classifySentence` (even though it is a full document and not only sentence):

```
        AbstractSequenceClassifier<CoreLabel> classifier = CRFClassifier.getClassifier("my-crf-ser.gz");
        final String inputFile = "myFile.txt"
        Properties props = new Properties();
        props.put("annotators", "tokenize");
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
        Annotation document = new Annotation(IOUtils.slurpFile(inputFile));
        pipeline.annotate(document);        
        List<CoreLabel> tokens = document.get(TokensAnnotation.class);
        List<CoreLabel> classifiedTokens = classifier.classifySentence(tokens);
        for (CoreLabel token : classifiedTokens) {
            System.out.println(token.word() + '/' + token.get(CoreAnnotations.AnswerAnnotation.class) + ' ');
        }
```

Here the named entities match the ones found with `-testFile myFile-tokenized.tsv`, and are, from the look of it, of better quality than when using `classify`.

Is my code above a proper way to use a trained classifier through the API to obtain named entities from a document?

**Comment by J38** [comment]
Sure there's nothing wrong with doing it that way if you are observing better performance.  So what you seem to be saying is you get better F1 performance by tagging the entire document as one large sentence instead of breaking it into sentences?

**Comment by toliwa** [comment]
@J38 I think there is more to that. Quoting from the CoreNLP mailing list [here](https://mailman.stanford.edu/pipermail/java-nlp-user/2011-August/001279.html) :  

``
Another thing I just learned about is that the basic classify() method
for a CRFClassifier doesn't add those extra annotations, which are
actually quite useful in terms of features.  Not having them costs
quite a bit of performance.  What you can do instead is call
classifySentence(), which does add those features.
``

Also see the @manning post to the CoreNLP mailing list from my first post.

It seems that these extra features are only being gathered when using `classifySentence` and the CRFClassifier with tokenized input, but not when using `classify` or the `ner-gui.sh`.
