### ISSUE TITLE
Stanford relation extraction program

### ISSUE THREAD

**Issue by souravidea** [stanfordnlp/CoreNLP#439]
for the program given in https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/RelationExtractorAnnotator.java

public Set<Class<? extends CoreAnnotation>> requires()  and
public Set<Class<? extends CoreAnnotation>> requirementsSatisfied() this 2 statements are giving same error when tried for execution
error is-
return type Set<Class<? extends CoreAnnotation>> is not compatible with Set <Requirement>

**Comment by J38** [comment]
When I run a pipeline with the `relation` annotator I am not seeing any issues.  If you provide more details I can attempt to reproduce this issue.
