### ISSUE TITLE
Can we construct Trees from input String?

### ISSUE THREAD

**Issue by windweller** [stanfordnlp/CoreNLP#44]
I know StanfordNLP produces parentheses based output through print() method, but does it provide any function to read back outputted string and construct a tree?

**Comment by gangeli** [comment]
You can try using edu.stanford.nlp.trees.PennTreeReader. Tree.valueOf(String) might work as well.

**Comment by windweller** [comment]
Yes thanks. What do you think about ` val r: TreeReader = new PennTreeReader(new StringReader(rawString), new LabeledScoredTreeFactory(new StringLabelFactory))`? I found it from the Tregex library!

**Comment by manning** [comment]
Most of our code now uses a CoreLabel for tokens/nodes, which gives you a Map which can have multiple attributes at a node, whereas with a StringLabel, you just get a String at each node. But what you show does work if it is all you need.  I would re-recommend:

    Tree t = Tree.valueOf("(S (NP (DT The) (NN man)) (VP (VBD slept)) (. .)))

If your needs aren't fancy, that is the easiest way.
