### ISSUE TITLE
IndexOutOfBoundsException while using stanford naturalli.OpenIE

### ISSUE THREAD

**Issue by iarroyof** [stanfordnlp/CoreNLP#443]
I'm using the `naturalli.OpenIE` module from coreNLP. I get an IndexOutOfBoundsException while using combined/simultaneous options `-triple.all_nominals true` and `-format reverb`. Please tell me how can I fix it. This is my line command:

    java -mx2g -cp "*" edu.stanford.nlp.naturalli.OpenIE -filelist list.txt -triple.all_nominals true -format reverb > triples.reverb

where the input is either a sentence-by-row file or a list of file names (a sentence by file). This does not occur if I use the mentioned options differently, e.g. `(-triple.all_nominals false, -format reverb)` or `(-triple.all_nominals true, -format ollie)`.

This is a sample input file (a sentence by row, the openIE module crashes with the 3rd row):

    The ability of IHF alone to activate fimB expression show IHF to repress ompC transcription
    Thus , NanR and NagC appear to activate fimB expression independently .
    Thus MarA is able to repress the rob promoter after the preformed open complex clears the promoter .
    However , in vitro experiments show IHF to repress ompC transcription from two of its three promoters .
    These results show that constitutive and inducible expression of the chromosomal MarA was able to upregulate nfnB expression in contrast with the lack of activation mediated by constitutive expression of the chromosomal SoxS and Rob proteins .
    The Rob homologs MarA and SoxS can activate transcription of a broad range of genes in vivo ( reviewed in references 2 and 14 ) , including sodA , fumC , micF , zwf , and inaA , suggesting broadly overlapping activities of these three regulators .
    It thus seems likely that the ability of IHF alone to activate fimB expression is enhanced in the D3 mutant background
    In conclusion , MelR and CRP bind to the melAB promoter co - operatively to adjacent sites in order to activate transcription in a co - dependent manner

This is the output, which I get multiple times in the log.

    [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
    [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
    [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
    Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.1 sec].
    [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
    [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator depparse
    Loading depparse model file: edu/stanford/nlp/models/parser/nndep/english_UD.gz ... 
    PreComputed 100000, Elapsed Time: 2.424 (s)
    Initializing dependency parser done [6.8 sec].
    [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator natlog
    [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator openie
    Loading clause searcher from edu/stanford/nlp/models/naturalli/clauseSearcherModel.ser.gz...done [0.210 seconds]
    Processing file: /almac/ignacio/rie_gce/karla_tests
    All files have been queued; awaiting termination...
    /almac/ignacio/rie_gce/karla_tests	0	ability	show	IHF	1	2	9	10	10	11	1.000	the ability of IHF alone to activate fimB expression show IHF to repress ompC transcription Thus , NanR and NagC appear to activate fimB expression independently .	DT NN IN NN RB TO VB NN NN VBP NN TO VB NN NN RB , NN CC NN VBP TO VB NN NN RB .	ability	show	ihf
    /almac/ignacio/rie_gce/karla_tests	0	NanR	activate	NagC	17	18	22	23	19	20	1.000	the ability of IHF alone to activate fimB expression show IHF to repress ompC transcription Thus , NanR and NagC appear to activate fimB expression independently .	DT NN IN NN RB TO VB NN NN VBP NN TO VB NN NN RB , NN CC NN VBP TO VB NN NN RB .	nanr	activate	nagc
    /almac/ignacio/rie_gce/karla_tests	0	IHF	repress	ompC transcription	10	11	12	13	13	15	0.620	the ability of IHF alone to activate fimB expression show IHF to repress ompC transcription Thus , NanR and NagC appear to activate fimB expression independently .	DT NN IN NN RB TO VB NN NN VBP NN TO VB NN NN RB , NN CC NN VBP TO VB NN NN RB .	ihf	repress	ompc transcription
    /almac/ignacio/rie_gce/karla_tests	0	NanR	activate independently	NagC	17	18	22	26	19	20	1.000	the ability of IHF alone to activate fimB expression show IHF to repress ompC transcription Thus , NanR and NagC appear to activate fimB expression independently .	DT NN IN NN RB TO VB NN NN VBP NN TO VB NN NN RB , NN CC NN VBP TO VB NN NN RB .	nanr	activate independently	nagc
    /almac/ignacio/rie_gce/karla_tests	0	NanR	activate	fimB expression	17	18	22	23	23	25	1.000	the ability of IHF alone to activate fimB expression show IHF to repress ompC transcription Thus , NanR and NagC appear to activate fimB expression independently .	DT NN IN NN RB TO VB NN NN VBP NN TO VB NN NN RB , NN CC NN VBP TO VB NN NN RB .	nanr	activate	fimb expression
    /almac/ignacio/rie_gce/karla_tests	0	NanR	activate independently	fimB expression	17	18	22	26	23	251.000	the ability of IHF alone to activate fimB expression show IHF to repress ompC transcription Thus , NanR and NagC appear to activate fimB expression independently .	DT NN IN NN RB TO VB NN NN VBP NN TO VB NN NN RB , NN CC NN VBP TO VB NN NN RB .	nanr	activate independently	fimb expression
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    	at java.util.ArrayList.get(ArrayList.java:429)
    	at edu.stanford.nlp.ie.util.RelationTriple.toReverbString(RelationTriple.java:373)
    	at edu.stanford.nlp.naturalli.OpenIE.tripleToString(OpenIE.java:604)
    	at edu.stanford.nlp.naturalli.OpenIE.processDocument(OpenIE.java:638)
    	at edu.stanford.nlp.naturalli.OpenIE.lambda$main$12(OpenIE.java:760)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    DONE processing files. 1 exceptions encountered.

I've used `stanford-corenlp-{3.6.0, 3.7}`

In the case that there is an option to generate marks for the output results that can be a surrogate of origin marks of the `reverb` format please tell me how to do it. That's why I need this format given an input `-filelist` or a `-file` containing a sentence by row. Also other configurations of the openIE (coreNLP) module that process sentences in parallel while keeping track between the input and the output would be useful alternatives.

Thank you very much.

**Comment by gangeli** [comment]
Thanks for the report! I could replicate the bug, and a fix should be inbound shortly.

**Comment by iarroyof** [comment]
Thank you very much @gangeli , that's now fixed.. right?
