### ISSUE TITLE
R coreNLP package error (foreign language)

### ISSUE THREAD

**Issue by LauEst** [stanfordnlp/CoreNLP#447]
Hello,

I have some issue using CoreNLP on R for french language. The following code gave me an error:

```
library(coreNLP)
downloadCoreNLP(type = "french")
initCoreNLP(type = "french")

[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: StanfordCoreNLP-french.properties
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
Error in rJava::.jnew("edu.stanford.nlp.pipeline.StanfordCoreNLP", basename(path)) : 
  java.lang.RuntimeException: edu.stanford.nlp.io.RuntimeIOException: Error while loading a tagger model (probably missing model file)
```

The _StanfordCoreNLP-french.properties_ file is in extdata folder and the file _stanford-french-corenlp-2016-01-14-models_ is in _stanford-corenlp-full-2015-12-09_ folder.

Moreover, there was no problem on adding tokenize and ssplit methods, the problem is for the part of speech model.

Any idea of what is the problem?

Thanks, Laurent.

**Comment by LauEst** [comment]
Okay I found the solution by looking in the source code. The init needs to be done in two times:

```
initCoreNLP()
initCoreNLP(type = "french")
```

**Comment by manning** [comment]
Okay, great! In general, for problems specific to something like the R corenlp package, you're more likely to be able to get help from its authors....
