### ISSUE TITLE
[help-wanted] coref: how to get all Mentions for a document

### ISSUE THREAD

**Issue by dan-zheng** [stanfordnlp/CoreNLP#449]
I'm wondering how to get all coreference `Mention`s for a document.

I'm using the following annotators: `tokenize, ssplit, pos, lemma, ner, parse, mention, coref`

Using `CorefChainAnnotation` to get `CorefChain.CorefMention`s for an entire document is simple enough, but I'd really like to access `Mention`s, which provide much more information.

Things I've tried:

- `CorefMentionsAnnotation` is great for getting `Mention`s, but only works for sentences, not entire documents. Each `Mention` has a `corefClusterID`, so maybe it's possible to easily get all coref clusters. I wasn't able to figure it out though.
- `CorefChainAnnotation` gets `CorefMention`s. However, I couldn't figure out a way to get `Mention`s from `CorefMentions`s.

Theoretical solutions (if they exist and work):

- `document.get(CorefMentionsAnnotation)`
- `document.get(CorefClusterAnnotation)`

Current solution:

- create a Map<Int, Mention> of Mention ids to Mentions: use `sentence.get(CorefMentionsAnnotation)` on all sentences and store `Mention`s in a map

Any advice would be greatly appreciated!

**Comment by J38** [comment]
Hi I've altered the `mention` annotator to also store a list of all coref mentions for the entire document in the annotation.

**Comment by dan-zheng** [comment]
Thanks!
