### ISSUE TITLE
Non-string property values don't get passed to annotators

### ISSUE THREAD

**Issue by cheald** [stanfordnlp/CoreNLP#45]
Ref: https://github.com/stanfordnlp/CoreNLP/commit/c01f31e190c322bffe508f2776c6d8af3c052392#diff-817eb462723073c02c8fc4fd34993d18R22

Edit: This doesn't seem to come up right - the file and line in question are AnnotatorFactory.java, line 22:

~~~diff
-    for(Object key: properties.keySet()) {
-      this.properties.setProperty((String) key, properties.getProperty((String) key));
+    for (String key : properties.stringPropertyNames()) {
+      this.properties.setProperty(key, properties.getProperty(key));
     }
   }
~~~

Using `stringPropertyNames()` causes properties with non-string values to be excluded from the copied properties set, since they are excluded from the iterator. For example:

~~~java
Properties props = new Properties();
props.put("ner.useSUTime", false);
props.put("customAnnotatorClass.stopword", "intoxicant.analytics.coreNlp.StopwordAnnotator");
~~~

from this props object, only `customAnnotatorClass.stopword` will be copied into the annotator, since the value of the "ner.useSUTime" prop is a non-string. The documentation for stringPropertyNames says:

> [This] method returns a set of keys in this property list where the key and its corresponding value are strings, including distinct keys in the default property list if a key of the same name has not already been found from the main properties list. *Properties whose key or value is not of type String are omitted.*

This results in CoreNLP silently creating annotators without the properties that have been set on the Properties object.

**Comment by AngledLuffa** [comment]
Properties objects should not be used like that.  Basically, they were an
attempt to make HashMap<String, String> before generics were added.  They
should be treated as if they can only store String keys and values.

http://docs.oracle.com/javase/8/docs/api/java/util/Properties.html

**Comment by cheald** [comment]
I'd like to suggest then that the documentation be updated to recommend `setProperty` rather than put, as that documentation says:

> Because Properties inherits from Hashtable, the put and putAll methods can be applied to a Properties object. Their use is strongly discouraged as they allow the caller to insert entries whose keys or values are not Strings. The setProperty method should be used instead.

The [CoreNLP documentation](http://nlp.stanford.edu/software/corenlp.shtml) gives the example:

~~~java
// creates a StanfordCoreNLP object, with POS tagging, lemmatization, NER, parsing, and coreference resolution 
    Properties props = new Properties();
    props.put("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
    StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
~~~

which makes it somewhat easy to fall into this trap!

**Comment by manning** [comment]
Good point. The example isn't best practices. I'll change this.  We might even want to add an example showing `"false"`.
