### ISSUE TITLE
CoreNLP online demo URL

### ISSUE THREAD

**Issue by MadhuKush** [stanfordnlp/CoreNLP#454]
Hi, 

We were using the below links to check the Named entities identified by Stanford NLP.
http://nlp.stanford.edu:8080/corenlp/process
http://www.corenlp.run/

But now both the links seems not working. Is the demo link changed ? If yes could you please provide us the link. 

Thank you in advance.

**Comment by gangeli** [comment]
Yes, those are the correct demo links. The corenlp.run demo should be back up. Just to make sure though, I should reiterate that you should not be making API calls against the site -- they're running on fairly small boxes intended for demo use only.

**Comment by MadhuKush** [comment]
Hi Angeli,

Thanks alot for your quick response and the confirmation on the links. Yes
we are not making any API calls against the site. We are making use of them
just and purely for demo purpose only.

Thank you again.

**Comment by gangeli** [comment]
Anytime! The demo does have a bad habit of going down now and again -- my running assumption is from people making API calls against it. It's still not as robust as it should be to too many different annotator configurations being called too many times...
