### ISSUE TITLE
ptb trees to UD conversion

### ISSUE THREAD

**Issue by mariaBio** [stanfordnlp/CoreNLP#455]
Hello,

Could you please help me with converting ptb trees into CONLL-U format.
I am trying to use the following command:
java -mx1g edu.stanford.nlp.trees.ud.UniversalDependenciesConverter -treeFile treebank > treebank.conllu
from https://nlp.stanford.edu/software/stanford-dependencies.shtml
Unfortunately I get the following error:

"Could not find or load main class edu.stanford.nlp.trees.ud.UniversalDependenciesConverter"

Indeed, UniversalDependenciesConverter.java is not in stanford-parser-3.7.0-sources.jar, the corresponding .class file is missing either.
I downloaded the parser from https://nlp.stanford.edu/software/lex-parser.shtml
The parser (even the new one, nndep) works fine. 
Thank you for your helo,
Maria

**Comment by manning** [comment]
The omission of this class from the last release was a mistake…. If you want things quickly you can download this class and any others you need from GitHub:

https://github.com/stanfordnlp/CoreNLP/blob/9ae8235e4175d992db0b3faf43768d4bc10833d3/src/edu/stanford/nlp/trees/ud/UniversalDependenciesConverter.java

But we're also going to do a new release soon, and then it'll be available in it.

**Comment by mariaBio** [comment]
Thank you very much, it works fine.

May I ask you please one more question.
The Readme file says that the English model for the parser was trained on a
variety of texts, including biomedical ones.
Could you please tell, which biomedical corpus was used and what part of it
went for training/dev/test?

Thank you very much,
With kind regards,
Maria

**Comment by matanster** [comment]
Old thread, but I think you can find the answer as to your training data question here ― 
https://nlp.stanford.edu/software/parser-faq.shtml

> Genia (biomedical English). Originally we used the treebank beta version reformatted by Andrew Clegg, his training split, but more recently (1.6.5+?) we've used the official Treebank, and David McClosky's splits

But it later acknowledges this list may not be up to date. On the training data topic, I wonder if the license to the Stanford produced annotations which were infused into the training to augment for imperative and question sentences, are still licensed under the Creative Commons Attribution 4.0, as mentioned, or whether that's changed.

Admittedly I came here looking for UD conversion, this post shows up high in Google for that.
