### ISSUE TITLE
Splitting sentence: Difference in Results from online corenlp.run server from local server 

### ISSUE THREAD

**Issue by jchauhan** [stanfordnlp/CoreNLP#456]
I have a difference while splitting a a text in online version vs my local version of corenlp server. Is it a configuration issue, or model issue? Let me know

## corenlp.run server

**Text**
Added Rs. 5000 to your Paytm wallet. Transaction ID: 7214651302. Current Balance: 5703.05. Upto Rs 150 Cashback on Movie tickets! Use code MOVIE150. http://m.p-y.tm/oo. Book Now

**Result**
![image](https://cloud.githubusercontent.com/assets/74857/26830069/3d413696-4ae5-11e7-8bce-34c5f5ae8c3c.png)

## local server (ver 3.7.0)

**Text**
Added Rs. 5000 to your Paytm wallet. Transaction ID: 7214651302. Current Balance: 5703.05. Upto Rs 150 Cashback on Movie tickets! Use code MOVIE150. http://m.p-y.tm/oo. Book Now

**Result**
![image](https://cloud.githubusercontent.com/assets/74857/26830010/0f9c1b3e-4ae5-11e7-9140-eae4d62ac315.png)

**Comment by manning** [comment]
Hi jchauhan! This change is a result of how we're always improving CoreNLP! Previously, it didn't handle the Indian "Rs." abbreviation properly, and now it does! Our live demo is currently using a recent-ish (but probably not the most recent) code checkout. 

You've got a couple of choices here: Either you can download a commit from github and build your own jar, or wait until the next official release – which will be soon – which will incorporate this change.
