### ISSUE TITLE
in in /StanfordCoreNLP/src/edu/stanford/nlp/sentiment filelist option is not processed correctly 

### ISSUE THREAD

**Issue by alrahimi** [stanfordnlp/CoreNLP#46]
the fout and pout are created and closed per sentence instead of per file.
Resolution:
Change it to the following:
      for (Annotation annotation : annotations) {
          pipeline.annotate(annotation);

          //AR: bug move it to before the second for
          //FileOutputStream fout = new FileOutputStream(file + ".out");
          //PrintStream pout = new PrintStream(fout);

**Comment by manning** [comment]
Thanks!

**Comment by alrahimi** [comment]
thanks for fixing this.
