### ISSUE TITLE
POS tagger incorrectly returns NN instead of VB for this utterance

### ISSUE THREAD

**Issue by donasumu** [stanfordnlp/CoreNLP#463]
While comparing the Stanford NLP POS tagger against 2 others, I noticed that this sentence was being incorrectly parsed:
"unlock my debit card"
POS returns
unlock / NN  <<<< should be VB (or VBP)
my / PRP$
credit / NN
card / NN

**Comment by manning** [comment]
Thanks for the report. We have gradually tried to improve the system's performance on imperatives like this, which are not well-represented in traditional NLP training data. But it's all still a work in progress. We can't guarantee correct results for particular examples, but we'll see if we can fix this in a future release. Despite the POS error, the dependency parse seems to be correct.
