### ISSUE TITLE
How can I get the same result as CoreNlp.run?

### ISSUE THREAD

**Issue by Gii16** [stanfordnlp/CoreNLP#467]
sorry to bother you.
I use CoreNlp to get the parse tree ,and the maven dependency is like below:

    <dependency>
        <groupId>edu.stanford.nlp</groupId>
        <artifactId>stanford-corenlp</artifactId>
        <version>3.8.0</version>
    </dependency>

    <dependency>
        <groupId>edu.stanford.nlp</groupId>
        <artifactId>stanford-corenlp</artifactId>
        <version>3.8.0</version>
        <classifier>models</classifier>
    </dependency>
The result is different from CoreNlp.run(process the same sentence),and I want to get the same result like CoreNlp.run, what should i do?Thanks!

**Comment by gangeli** [comment]
Likely, this is from using a different parser model locally. corenlp.run uses the shift-reduce constituency parser for efficiency, whereas the default parser in the CoreNLP distribution is a PCFG. The tradeoff here is between a faster and more accurate model (shift reduce) versus faster loading time and smaller model disk size (the PCFG). For more details: https://nlp.stanford.edu/software/srparser.shtml (note that you'll need to include an additional model jar)

**Comment by Gii16** [comment]
Really thanks for your help！
