### ISSUE TITLE
how to build the CoreNLP Project?

### ISSUE THREAD

**Issue by tankle** [stanfordnlp/CoreNLP#47]
I want to change the SUTime to use heidelTime,  but I don't how to build this project ！

**Comment by alrahimi** [comment]
You can follow the instructions here:
http://nlp.stanford.edu/software/basic-compiling.txt

**Comment by manning** [comment]
Yes, it comes with both a build.xml for ant and a build.gradle for gradle. Either use one of those or adapt for your favorite build system. Open a new issue if there's a specific problem?

**Comment by melodyju** [comment]
My apologies if this isn't the right place to stick this question. I am using ant to build, but it seems that the command "jar -cfm ../stanford-corenlp-<version>.jar ../META-INF/MANIFEST.MF edu" cannot fine the manifest file. For some context, I am trying to use SUTime to annotate a file with timex3 tags.

**Comment by J38** [comment]
I would just do:
    jar -cf stanford-corenlp.jar edu

I don't think you need the MANIFEST.MF file for any practical purpose.

**Comment by J38** [comment]
I added a sample MANIFEST.MF file to doc/corenlp/META-INF

**Comment by makamkkumar** [comment]
I am getting this error when I cloned the source from github 
I did the cd CoreNLP and then ran the ant command
Got this output stating that the build failed
ant
Buildfile: /home/Tkx/CoreNLP/build.xml

classpath:
     [echo] core

compile:
     [echo] core
    [javac] Compiling 1987 source files to /home/Tkx/CoreNLP/classes

BUILD FAILED
/home/Tkx/CoreNLP/build.xml:103: Error running javac compiler

Total time: 0 seconds

Any suggestions or mistake I am doing
I have already done sudo apt-get update and then updgraded as well
