### ISSUE TITLE
Chinese coref model not work

### ISSUE THREAD

**Issue by jingtianming1** [stanfordnlp/CoreNLP#471]
I use coref model to deal with chinese，the properties is use default，but don't find result

**Comment by dan-zheng** [comment]
What version are you using? What annotators/properties are you using? What error do you get?

Chinese coref works for me on version 3.8.0 with the following annotators: `'tokenize', 'ssplit', 'pos', 'lemma', 'ner', 'parse', 'mention', 'coref'`.
