### ISSUE TITLE
NER and TokensRegex not working together in StanfordCoreNLPServer 3.8.0

### ISSUE THREAD

**Issue by nkrot** [stanfordnlp/CoreNLP#472]
(copying over my question from StackOverflow in the hope to get a quicker answer)

In brief: I have observed that `StanfordCoreNLP` and `StanfordCoreNLPServer` (v.3.8.0) work differently when annotators include both `ner` and `tokensregex`. More specifically, in the server mode results of `tokensregex` and `ner` are not combined and only results of `ner` are outputted.

Now description at length:

The server `StanfordCoreNLPServer` is started with `-serverProperties` option pointing to the file with the following content:

    annotators = tokenize,ssplit,pos,lemma,ner,tokensregex

    pos.model = edu/stanford/nlp/models/pos-tagger/german/german-hgc.tagger

    tokenize.language = de
    tokenize.options = normalizeCurrency=false

    ner.model = edu/stanford/nlp/models/ner/german.conll.hgc_175m_600.crf.ser.gz
    ner.applyNumericClassifiers = false
    ner.useSUTime = false

    customAnnotatorClass.tokensregex = edu.stanford.nlp.pipeline.TokensRegexAnnotator
    tokensregex.rules = deu/ner.money.tre.txt

The rule is deliberately made super simple and dumb. There is nothing else but these lines in the file `deu/ner.money.tre.txt`:

    ne = { type: "CLASS", value: "edu.stanford.nlp.ling.CoreAnnotations$NamedEntityTagAnnotation" }

    { ruleType: "tokens",
      pattern: ( /Millionen/ ),
      action: ( Annotate($0, ne, "HUGE") ) }

The text snippet to tag is as follows:

     mit einem Gesamtwert von mehr als € 5 Millionen in Frankfurt am Main .

Experiment 1. Console `StanfordCoreNLP` works as expected outputting both `ner` and `tokensregex` tags. The option `-props` points to the file with properties as described above.

    java -cp "*:/path/to/models-2017-06-09/*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -props ./deu/StanfordCoreNLP-deu.properties -file text.in -outputFormat json

grepped output contains all correct NEs

    ...
    { "word": "Millionen", "ner": "HUGE" },
    ...
    { "word": "Frankfurt", "ner": "I-LOC" },
    { "word": "am",        "ner": "I-LOC" },
    { "word": "Main",      "ner": "I-LOC" },
    ...

Experiment 2. The goal of this experiment is to determine whether `StanfordCoreNLPServer` is able of assigning tags by `tokensregex`. I can confirm it does.

The server is sent properties as below together in the request.

    {
      "pipelineLanguage" : "german",
      "annotators" : "tokenize,ssplit,pos,tokensregex",
      "outputFormat" : "json",
      "tokenize.whitespace" : "true",
      "ssplit.eolonly" : "true"
    }

As can be seen, the returned json contains tag `HUGE` assigned by `tokensregex`

    ...
    { "word": "Millionen", "ner": "HUGE" },
    ...
    { "word": "Frankfurt", "ner": null },
    { "word": "am",        "ner": null },
    { "word": "Main",      "ner": null },
    ...

Similarly, all three `I-LOC` are assigned when `ner` is used solely, without `tokensregex`.

Experiment 3. Looks like the *combination* of `ner` and `tokensregex` does not work in server mode. The server is sent the request that contains properties like this:

    {
      "pipelineLanguage" : "german",
      "annotators" : "tokenize,ssplit,pos,ner,tokensregex",
      "outputFormat" : "json",
      "tokenize.whitespace" : "true",
      "ssplit.eolonly" : "true"
    }

In the returned json the target word `Millionen` is tagged to as `O` to my great disappointment.

    ...
    { "word": "Millionen", "ner": "O" },
    ...
    { "word": "Frankfurt", "ner": "I-LOC" },
    { "word": "am",        "ner": "I-LOC" },
    { "word": "Main",      "ner": "I-LOC" },
    ...

Experiment 4 that blew my mind. Turns out that giving less annotators in the query does produce correct results that combine both `ner` and `tokensregex` tags. The query now looks like this:

    {
      "pipelineLanguage" : "german",
      "annotators" : "ner,tokensregex",
      "outputFormat" : "json",
      "tokenize.whitespace" : "true",
      "ssplit.eolonly" : "true"
    }

My server is started in preload mode with `-preload tokenize,ssplit,pos,lemma,ner,regexner,tokensregex` option. To my understanding this explains why specifying an incomplete list of annotators works. To be on the safe side I would prefer to always send the complete list of annotators in the request to the server.

I have played around with the list of annotators. Suffice it to add `pos` for `tokensregex` tags to be overriden with `O` tag. WTF?

    {
      "annotators" : "pos,ner,tokensregex",
    }

Is it an issue with `StanfordCoreNLPServer` or am I just doing something wrong?

**Comment by J38** [comment]
Does the server work properly if you start it without specifying `-preload`, with the `-serverProperties` as you described, and with a query where you don't specify a list of `annotators` ?

**Comment by nkrot** [comment]
No, without `-preload` and without explicit list of `annotators` in the request, only `ner` tags appear.

Another interesting fact: when i modify `properties` file to contain a shorted list of annotators like this:

    annotators = tokenize,ssplit,lemma,ner,tokensregex

I expect the server to fails due to absence of `pos`. However this does not happen. The logs show a *different* list of annotators:

    ... API call w/annotators tokenize,ssplit,pos,parse,lemma,ner

Why are `pos` and `parse` on the list and where is `tokensregex` gone?

By the way, I send the list of annotators in the request to avoid that unnecessary components are loaded, e.g. the parser.

**Comment by gangeli** [comment]
So, I haven't had a chance to look at this in detail yet, but my 5 second guess is that the bug here is the fact that the TokensRegex and Semgrex endpoints rerun the annotators when they're annotating. Likely, this second pipeline that they're running is different from the one you ran on the main annotation endpoint, yielding a discrepancy in the outputs.

The challenge here is that we have a JSON _outputter_, but not a deserializer. The challenge, then, is (1) the Tokensregex endpoint needs to be able to read an annotated proto blob and run tokensregex on that, and (2) we need a way to have the javascript frontend keep track of the proto blob that it should send back. 

The alternative is to write a JSON deserializer, but this encounters the twin challenges of (1) without including libraries parsing JSON is a bit of a pain, and (2) the JSON output is lossy and typeless, so it's not trivial to maintain the backwards mapping from JSON path to CoreNLP annotation key (this is a big enough pain with the proto annotator).

**Comment by nkrot** [comment]
Thanks @gangeli . can I do anything about this issue?

**Comment by J38** [comment]
Ok I used this properties file (note you no longer need to treat `tokensregex` as a custom annotator, you can just use `tokensregex` and it should work): 

```
annotators = tokenize,ssplit,pos,lemma,ner,tokensregex

pos.model = edu/stanford/nlp/models/pos-tagger/german/german-hgc.tagger

tokenize.language = de
tokenize.options = normalizeCurrency=false

ner.model = edu/stanford/nlp/models/ner/german.conll.hgc_175m_600.crf.ser.gz
ner.applyNumericClassifiers = false
ner.useSUTime = false

tokensregex.rules = deu/ner.money.tre.txt
```

And I used your rule.

I started the server with this command:

`java -Xmx4g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties example.properties -port 9000 -timeout 15000`

And I got back the result with both the `ner` and `tokensregex` labels.  So I am counting this issue as resolved for now.
