### ISSUE TITLE
Issues with NER in French

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#475]
I'm using `fr` and the following `"annotators": "tokenize,ssplit,pos,lemma,ner"`, where my configuration was like

```
"fr": {
    "parse.model": "edu/stanford/nlp/models/srparser/frenchSR.ser.gz",
     "tokenize.language" : "fr",
     "ssplit.newlineIsSentenceBreak": "always" 
}
 ```

while, by example in spanish `es` I have specified the `ner.model` along with the other models:

```
// spanish
 "es" : {
  "pos.model": "edu/stanford/nlp/models/pos-tagger/spanish/spanish.tagger",
  "parse.model": "edu/stanford/nlp/models/srparser/spanishSR.ser.gz",
   "ner.model":  "edu/stanford/nlp/models/ner/spanish.ancora.distsim.s512.crf.ser.gz",
    "tokenize.language" : "es",
     "ssplit.newlineIsSentenceBreak": "always"    
}
```

So in french NER results seems to be totally wrong. 

![screencapture-localhost-3000-track-63654076-1499186846303](https://user-images.githubusercontent.com/163333/27838264-b4f3c734-60e9-11e7-9afe-60709240c43b.png)

Looking at the default properties for french in this repo's `pipeline` folder, this seems to be confirmed:

```
annotators = tokenize, ssplit, pos, parse

tokenize.language = fr

pos.model = edu/stanford/nlp/models/pos-tagger/french/french.tagger

parse.model = edu/stanford/nlp/models/lexparser/frenchFactored.ser.gz

# dependency parser
depparse.model = edu/stanford/nlp/models/parser/nndep/UD_French.gz
depparse.language = french
```

Does this means that `NER` not supported in `fr`? Any other custom model for french?
```
-rw-r--r--@ 1 loretoparisi  staff      214038 28 Feb 18:47 /root/jollyday-0.5.1.jar
-rw-r--r--@ 1 loretoparisi  staff    14362014 13 Giu 10:50 /root/stanford-arabic-corenlp-2017-06-09-models.jar
-rw-r--r--@ 1 loretoparisi  staff   821613963 13 Giu 10:59 /root/stanford-chinese-corenlp-2017-06-09-models.jar
-rw-rw-r--@ 1 loretoparisi  staff   362527920 12 Giu 21:41 /root/stanford-corenlp-3.8.0-models.jar
-rw-rw-r--@ 1 loretoparisi  staff     8011820 12 Giu 21:40 /root/stanford-corenlp-3.8.0.jar
-rw-r--r--@ 1 loretoparisi  staff  1039009129 13 Giu 11:00 /root/stanford-english-corenlp-2017-06-09-models.jar
-rw-r--r--@ 1 loretoparisi  staff   474001837 13 Giu 10:59 /root/stanford-english-kbp-corenlp-2017-06-09-models.jar
-rw-r--r--@ 1 loretoparisi  staff   138392747 13 Giu 10:53 /root/stanford-french-corenlp-2017-06-09-models.jar
-rw-r--r--@ 1 loretoparisi  staff   128259316 13 Giu 10:52 /root/stanford-german-corenlp-2017-06-09-models.jar
-rw-r--r--@ 1 loretoparisi  staff   213169413 13 Giu 10:54 /root/stanford-spanish-corenlp-2017-06-09-models.jar
```

**Comment by mcavdar** [comment]
According to [this page](https://stanfordnlp.github.io/CoreNLP/human-languages.html), CoreNLP has not yet support for French NER.
If you want to train your own model, please see [this page](https://nlp.stanford.edu/software/crf-faq.shtml#a) and [that question](https://stackoverflow.com/questions/37852084/how-to-train-a-french-ner-based-on-stanford-nlp-conditional-random-fields-model).
Don't forget to add your trained model file(ser.gz) path to properties file like your Spanish example.
`"ner.model": "bla/bla/bla/french-model.ser.gz"`

**Comment by loretoparisi** [comment]
@mcavdar Thanks for the suggestion! I think I do not have labeled data to do the training in a new language right now. Yes, is that true, the parser will fallback on the default `en` model.

**Comment by mcavdar** [comment]
You can use [Europana](https://github.com/EuropeanaNewspapers/ner-corpora/tree/master/enp_FR.bnf.bio) and [Wikiner](http://downloads.schwa.org/wikiner/) dataset.

**Comment by loretoparisi** [comment]
@mcavdar Thanks a lot! The `EuropanaNews` has a pre-trained `fr` model for `ner`:

```shell
11:47:54.361 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
11:47:55.657 [main] INFO  e.s.n.ie.AbstractSequenceClassifier - Loading classifier from /root/eunews.fr.crf.gz ... done [1.3 sec].
```

The trained classifier `eunews.fr.crf.gz` is available here: http://lab.kbresearch.nl/static/html/eunews.html

My setup became:

```
"fr" : {
                "tokenize.language" : "fr",
                "pos.model" : "edu/stanford/nlp/models/pos-tagger/french/french.tagger",
                "parse.model" : "edu/stanford/nlp/models/lexparser/frenchFactored.ser.gz",
                // dependency parser
                "depparse.model" : "edu/stanford/nlp/models/parser/nndep/UD_French.gz",
                "depparse.language" : "french",
                "ner.model":  DATA_ROOT+"/eunews.fr.crf.gz",
                "ssplit.newlineIsSentenceBreak": "always" 
            },
```

**Comment by loretoparisi** [comment]
I'm closing this, since using the proposed solution for the `fr` NER it works.
