### ISSUE TITLE
Issue with Quote Attribution (English).

### ISSUE THREAD

**Issue by aparna-bansal** [stanfordnlp/CoreNLP#482]
Is the property: quoteattribution (`'annotators': 'quoteattribution'`  for English) \ annotator class name: QuoteAttributionAnnotator (https://stanfordnlp.github.io/CoreNLP/quoteattribution.html) not yet supported with the Version 3.8 available on the page? 

I also tried with the code from GitHub (built with Ant, downloaded the model jars to the CoreNLP folder), using `py-corenlp` but I get a `Null Pointer Exception`, details follow :

> Setting quotes.
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
> 	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:676)
> 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
> 	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
> 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
> 	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
> 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
> 	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
> 	at edu.stanford.nlp.quoteattribution.Sieves.Sieve.createNameMatcher(Sieve.java:128)
> 	at edu.stanford.nlp.quoteattribution.Sieves.Sieve.<init>(Sieve.java:40)
> 	at edu.stanford.nlp.quoteattribution.Sieves.QMSieves.QMSieve.<init>(QMSieve.java:32)
> 	at edu.stanford.nlp.quoteattribution.Sieves.QMSieves.TrigramSieve.<init>(TrigramSieve.java:23)
> 	at edu.stanford.nlp.pipeline.QuoteAttributionAnnotator.getQMMapping(QuoteAttributionAnnotator.java:220)
> 	at edu.stanford.nlp.pipeline.QuoteAttributionAnnotator.annotate(QuoteAttributionAnnotator.java:206)
> 	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
> 	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:648)
> 	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.lambda$handle$0(StanfordCoreNLPServer.java:658)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	... 3 more

**Comment by ryan-gilbert** [comment]
having the same issue as well

**Comment by J38** [comment]
This bug is caused by not having `ner,entitymentions` in your list of annotators.  Those are required for the QuoteAttributionAnnotator to work.

Example properties file for server:

`annotators = tokenize,ssplit,pos,lemma,ner,entitymentions,depparse,quote,quoteattribution`

I have also added the speaker to the JSON output for quotes, so it should work better with the server now.

**Comment by J38** [comment]
You'll need to build the latest version to use these changes.

Details here: https://stanfordnlp.github.io/CoreNLP/download.html
