### ISSUE TITLE
Adding custom annotators to CoreNLP Server

### ISSUE THREAD

**Issue by natewatson999** [stanfordnlp/CoreNLP#483]
I know that custom annotators can be added to CoreNLP, but I can't find a way to enable custom annotators within CoreNLP server. I need to be able to add features such as ClausIE to CoreNLP, and have them available in the same manner OpenIE or NER is usable via a network interface, but I haven't been able to find how. Is it possible to add custom annotators to CoreNLP Server?

**Comment by loretoparisi** [comment]
@natewatson999 to add custom annotators, see the proposed solution for the `ner` french annotator that it is missing in the `CoreNLP` distribution: https://github.com/stanfordnlp/CoreNLP/issues/475

**Comment by J38** [comment]
You need to launch the server with a properties file: `-serverProperties custom-annotators.properties`

Here is an example of launching the server with a properties file:

# Run a server using Chinese properties
java -Xmx4g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties StanfordCoreNLP-chinese.properties -port 9000 -timeout 15000

Your properties file should look like this:

```
customAnnotatorClass.custom.lemma = edu.stanford.nlp.examples.CustomLemmaAnnotator

annotators = tokenize,ssplit,pos,custom.lemma

custom.lemma.lemmaFile = custom-lemmas.txt
```

Don't include a list of annotators in your request, the list of annotators should be specified in the .properties file.

Also, you must make sure the new custom class is on the CLASSPATH when you run the server.

More extensive documentation:

https://stanfordnlp.github.io/CoreNLP/corenlp-server.html
https://stanfordnlp.github.io/CoreNLP/new_annotator.html
