### ISSUE TITLE
NLP not able to identify billion or million or Rupees given in short form 

### ISSUE THREAD

**Issue by MadhuKush** [stanfordnlp/CoreNLP#485]
Hi,
Considering the below sentences for example:
1) software company turn over is  **$ 1.8 bln** for the current year.
2) software company turn over is **Rs16,189-crore** ($ 2.5 billion) previous year.
3) software company turn over is expected to be **$ 728 mil** next year.
4) Over all profit seen in this year is **RM10 million**.

**NLP is not able to identify** 
- bln as Billion
- Rs16,189-crore as money itself
- mil as million
- RM10 million as money iteself.

NLP identifying Money entities just as $1.8, $728 without billion and million
Other two cases of RM10 million and Rs16,189-crore is not getting identified as Money at all
If full form like billion/million is given, it is able to identify. 

Could you please suggest a best solution that we can try out to make these cases success. 
Thank you in advance.

**Comment by keerath** [comment]
Easiest way is to write regex for all these various money units. Take a look at RegexNER.

**Comment by MadhuKush** [comment]
Thank you Keerath. We will check and if any issues hoping you will guide. Thanks again
