### ISSUE TITLE
Inconsistent NER execution

### ISSUE THREAD

**Issue by natewatson999** [stanfordnlp/CoreNLP#486]
I'm using the latest version of CoreNLP server in English, with 7 gigs of memory available. The following sentence has parsing issues: 

'In "Desperate Living"; a crazy woman and her maid accidentally kill the crazy woman's husband, and faced with jail or Mortville, opt to live in Mortville, which is populated by criminals, perverts, nudists, and the evil corrupt cops who serve the fascist evil ruler of Mortville, Queen Carlota.'

The word "Mortville" is not tagged consistently with NER. The first time it's tagged, it's tagged as a person; but the other two times, it's tagged as a location. It's a location. The NER results should be internally consistent.

**Comment by J38** [comment]
The NER system is a statistical model trained on thousands of sentences, so sometimes it will do strange things like this.  I think there would be value in trying to better leverage the fact that the same string appearing in the same sentence in most cases will probably be the same entity type, though there are exceptions like "Do you mean the city Paris or a person named Paris?"  There has been past research on looking at all of a string's appearances in a document when making the decision.
