### ISSUE TITLE
Sentiment dependency on tense

### ISSUE THREAD

**Issue by kamaldsingh** [stanfordnlp/CoreNLP#487]
The sentiment for sentence :-

> the movie itself is excellent but i expected more from the director

is positive 

whereas for sentence :-
> the movie itself was excellent but i expected more from the director

is negative, 
just because the tense is changed, whereas in the training data (tress/train.txt) we see the word "was" being tagged as neutral 

![screen shot](https://user-images.githubusercontent.com/15106140/28575966-c43111d8-7152-11e7-95e1-028a1ebe2941.png)

![screenshot](https://user-images.githubusercontent.com/15106140/28576083-1eea26c8-7153-11e7-8b41-bd27f65c733b.png)

Could this be related to fact that we have more negative and very negative reviews than positive reviews for the past tense in the training data  ?

y axis - count of reviews , x axis - sentiment from 0 to 4 (very -ve to very +ve)
![image](https://user-images.githubusercontent.com/15106140/28576002-dcf461e8-7152-11e7-80a1-a48fbed79bb3.png)

**Comment by kamaldsingh** [comment]
![screen shot](https://user-images.githubusercontent.com/15106140/28575178-76b7322c-7150-11e7-8c88-c06a74a03c66.png)

**Comment by J38** [comment]
That is an interesting observation.  At some point we may retrain the sentiment system with new data and a more advanced model.
