### ISSUE TITLE
Training relation extractor with custom data

### ISSUE THREAD

**Issue by ramonrod** [stanfordnlp/CoreNLP#489]
Hello All,
As a test I want to train my own model for extracting relations between entities in the financial domain. So far I have been able to trail a NER-model in order to recognize custom entities. The next step in my project is to recognize the relations. Theoretically, I know how the training process works, but I need some help with the relation data for training and how to integrate all this in stanfordCoreNLP.

**What I know until now:**
1. I need to train a ner-model for recognizing new entities (this step is already implemented and is working fine).
2. I need to create training data in the format IO similar to conll04.corp, e.g.:
1	O	0	O	IN	By	O	O	O
1	Peop	1	O	NNP/NNP	RONI/RABIN	O	O	O
2	Org	0	O	NNP/NNP	Associated/Press	O	O	O
2	O	1	O	NNP	Writer	O	O	O
3	O	0	O	DT	The	O	O	O
3	O	1	O	JJ	long	O	O	O
3	Other	2	O	JJ	Palestinian	O	O	O
3	O	3	O	NN	uprising	O	O	O
3	O	4	O	VBZ	has	O	O	O
3	O	5	O	VBN	brought	O	O	O
3	O	6	O	NN	bitterness	O	O	O
3	O	7	O	TO	to	O	O	O

3. Change use new "possibleEntities" attribute in the properties file
4. Re-compile library (?)
5. Train and test your model

**Where do I need help:**
a. Is there a script which could help me to generate the training data layout for the relation extractor. I hope I don't have to create this file manually. And do I run the script in order to get the desired output.

b.  Where do I have to do changes in the original code/classes?

c. After changes are done, do I have to recompile the library indeed?

Please advise.

Thanks

**Comment by J38** [comment]
There is documentation here for training a relation extraction model:

https://nlp.stanford.edu/software/relationExtractor.html

You don't need to recompile or change your code for this to work.  Of course you need to build the latest GitHub version the first or have one of our official distributions:

https://stanfordnlp.github.io/CoreNLP/download.html
