### ISSUE TITLE
How can I get train file of english tagger model?

### ISSUE THREAD

**Issue by vietkhoa** [stanfordnlp/CoreNLP#492]
I am using CoreNLP to tag word's part of speech in sentence. It's pretty awesome. But some word was tagged inappropriately.
I know how to train tagger model for CoreNLP. But my problem is that I couldn't find 3 files "train-wsj-0-18", "train-extra-english", "train-tech-english". 
How could I get 3 files to train CoreNLP tagger model to add some miss train rule and rebuild tagger model ? Also arch files "egw4-reut.512.clusters,-1,1"
Thank you very much

**Comment by J38** [comment]
We do not release those files.  

You can get the `wsj` files from LDC: https://catalog.ldc.upenn.edu/ldc99t42

They need to be of the format 1 sentence per line, tokens separated by space, so I think you need to process the original files from LDC.  Example:

`He_PRP drove_VBD from_IN California_NNP ._.`

The other two files are resources we created that we are not currently distributing.
