### ISSUE TITLE
How to over ride the original entities fetched with RegexNER

### ISSUE THREAD

**Issue by MadhuKush** [stanfordnlp/CoreNLP#495]
Hi Team,
 In the below sentence
Mega First Corp Bhd has A21 a major stake in a Perak mining company for **RM10 million**

RM10 million is identified as NUMBER by NLP default. However we wrote a regex using RegNER to fetch it as Money. The regex is as follows:

**RM[0-9]{2}\s*million	Money**

But still NLP is identifying it as NUMBER instead of MONEY. Could you please tell how to override this behavior and fetch the value as Money.

Thank you advance.

**Comment by J38** [comment]
You need to add an overwrite column.  Here is an example entry:

`london  CITY    LOCATION        1`

The third column means that LOCATION tags can be overwritten as CITY.  So you need to do the same and say MONEY can overwrite NUMBER.
