### ISSUE TITLE
Conditions and Guidelines to make changes to the Standford core NLP project

### ISSUE THREAD

**Issue by MadhuKush** [stanfordnlp/CoreNLP#498]
Hi Team,

We would like to know if there is any chance that we can do some enhancements or changes to the Standford core NLP project.  
If its allowed 
Will the changes be committed to your core project and released ? 
Any restrictions on the same ?
What are the things to be noted or minded in doing so ?

Could you please give more information.

Thank you in advance.

**Comment by J38** [comment]
We are always happy to review and accept pull requests.  If it is a small, limited change, the pull request will probably be approved.  If you do something with extensive changes I don't think we will approve it.  Ultimately this will depend on the specific pull request.  If you want to create a GitHub issue with a specific description of what you want to work on we will review it and let you know if that is something that we will merge.  Any pull requests we accept will end up in the next official release.
