### ISSUE TITLE
Tokenization emojis

### ISSUE THREAD

**Issue by jplu** [stanfordnlp/CoreNLP#501]
Hello,

As referenced in the issue #248, emojis are now handled in CoreNLP. But instead of being considered as "real UTF-8 token" they are considered as "2 tokens" in the offset all the time. For example:

```
📷
```
Has the offset [0:2] instead of [0:1].

But:

```
❤️
```

Has really the offset [0:2]. Basically considering the real unicode size like Python 3 does. How to make CoreNLP able to understand an emoji like this?

Thanks.

**Comment by manning** [comment]
I don't think that "real UTF-8 token" is an established term, but I'm pretty sure that what you're referring to is what the Unicode standard (or the Javadoc for the String class) calls a "code point".

I agree that this isn't what CoreNLP token offsets give you. Rather they give you offsets in the UTF-16 encoding that Java uses for Strings internally. That is, you can use the character begin/end offsets as indices into a String (with, e.g., the substring() method) or the corresponding char[] array.

I'm really not sure that this should be changed. To my mind the primary use case of these methods is that if you have the text of a document, then you can get the the portion of it corresponding to a token with these methods. That works well with them being the char offset that you pass to the String substring() method. In Java it is much easier to go from there to counting code points than to go the other direction from code point offsets to character offsets into a String.

So, operationally, to get the length in code points as you want, if you have a CoreLabel token `tok` and the original text in the variable `txt` the thing to ask for is:

```txt.substring(tok.beginPosition(), tok.endPosition()).codePointCount()```

Unicode is complex stuff, and only getting more complex with modern emoji developments. I think many people would question whether ❤️ or even more complex Unicode constructions like 👨‍👩‍👧 should count as multiple "things", as they do when counting in code points. For instance, Swift 4 has moved to principally working in terms of graphemes, so each of those also counts as 1 thing. I think that makes a fair bit of intuitive sense to a user!

**Comment by manning** [comment]
But I did improve the documentation. 🙂

**Comment by jplu** [comment]
Very clear answer and the proposed solution works perfectly well! Thanks a lot @manning and sorry for my "unclear" terms.

**Comment by manning** [comment]
Update (2021): To make it easier to work with code points, especially with other languages such as Python, we have now added support for `CodepointOffsetBeginAnnotation` and `CodepointOffsetEndAnnotation`, which count in code points. These annotations are requested by the `tokenize.codepoint` option, and then added by the `CodepointCoreLabelProcessor`.
