### ISSUE TITLE
How to get the universal dependency, NOT enhanced just like the demo online from command line? 

### ISSUE THREAD

**Issue by xieexiaotuzi** [stanfordnlp/CoreNLP#502]
In "stanford-parser-full-2016-10-31", I try the command line:

####
java -mx1000m -cp "$scriptdir/*:" edu.stanford.nlp.parser.lexparser.LexicalizedParser -sentences newline -outputFormat "typedDependencies" -originalDependencies edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz $*
#### 

and  get the universal dependency, enhanced;  but I don't know how to get the NOT enhanced universal dependency on command line.
Could anyone help me? Thanks a lot.

**Comment by J38** [comment]
There is answer for this here:

https://stackoverflow.com/questions/45629591/how-to-get-the-universal-dependency
