### ISSUE TITLE
Lemma for "seconds" is wrong

### ISSUE THREAD

**Issue by daywithoutrain** [stanfordnlp/CoreNLP#510]
The lemma from Corenlp for "seconds" is "seconds" instead of "second".

**Comment by AngledLuffa** [comment]
FWIW this is probably because of `he was hungry and asked for seconds` as opposed to `my fastest 400m ever was 56 seconds`

but the latter is much more common, and arguably the first one could be `second` anyway

**Comment by AngledLuffa** [comment]
fixed in 4.5.0
