### ISSUE TITLE
Can you please provide some examples of training a dependency parser?

### ISSUE THREAD

**Issue by harshchiki** [stanfordnlp/CoreNLP#512]
We need to parse e-mail messages in our project to extract information to generate orders (involving a code, description, quantity). We are using Named Entity Recognition to identify the key domain entities, and have been quite successful. Now we need to build dependency graphs, to establish relations and associations, for eg.
common information, say 1% rate of interest
first order information
second order information
third order information
In this example, the 1% rate of interest is applicable to all the orders. In case any order has a specific rate of interest, it overrides the value 1% (as is in this context)

I have not found any examples anywhere across the web, with searches done so far. Could you please advise?

Thanks!

**Comment by J38** [comment]
Please see this issue where a sample command and some advice can be found: https://github.com/stanfordnlp/CoreNLP/issues/683
