### ISSUE TITLE
StanfordCoreNLPServer 3.8 : Exception for some specific words

### ISSUE THREAD

**Issue by chandon** [stanfordnlp/CoreNLP#520]
Using StanfordCoreNLPServer and StanfordCoreNLPClient for French models and specific words (like **aujourd'hui** or **là-bas** ) is problematic and returns an exception on the server side:

    edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer$LossySerializationException: Keys are not being serialized: class edu.stanford.nlp.ling.CoreAnnotations$ParentAnnotation
        at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.toProto(ProtobufAnnotationSerializer.java:240)
        ...

Here is a client code example for a server running on localhost, port 8135:

    import java.util.Properties;

    import edu.stanford.nlp.pipeline.Annotation;
    import edu.stanford.nlp.pipeline.StanfordCoreNLPClient;

    public class test2 {
        public static void main(String[] args) {
            Properties props = new Properties();
            
            props.setProperty("annotators", "tokenize, ssplit, pos, depparse");             
            props.setProperty("tokenize.language","fr");
            props.setProperty("pos.model","edu/stanford/nlp/models/pos-tagger/french/french.tagger");
            props.setProperty("depparse.model","edu/stanford/nlp/models/parser/nndep/UD_French.gz");    
            props.setProperty("depparse.language","french");
            
            StanfordCoreNLPClient pipeline = new StanfordCoreNLPClient(props,"http://localhost",8135);
            Annotation annotation = pipeline.process("aujourd'hui");
        }
    }

Is there a way to fix it (seems it's not possible to change client/server serializer) ?

**Comment by J38** [comment]
I think this is a bug related to dependency parses of single word sentences.  I'll add it to the list of things we'll try to fix for version 3.9.0

**Comment by J38** [comment]
The issue here is actually related to French tokenization and our serialization.  I'm going to update the serializer to capture this field.

**Comment by J38** [comment]
Ok this should be fixed now in the current code.  I ran this command to verify:

`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-french.properties -annotators tokenize,ssplit,pos -file one-word-sentence.txt -outputFormat serialized -serializer edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer
`

**Comment by chandon** [comment]
@J38 thanks, i'll give a try as soon as possible
