### ISSUE TITLE
How to retrain an existing model

### ISSUE THREAD

**Issue by chandon** [stanfordnlp/CoreNLP#529]
We would like to train the existing POS tagger French models by removing accents from the training set.
Is it a way to remove accents directly without training the model again (from the .tagger file, or an option to the POS tagger annotator), or do i need to remove accents from the train File before training my own model ?

I cann't find the original trainfile (/u/nlp/data/lexparser/trees/FrenchCC/FTB-Train.utf8.txt), is it available somewhere?

**Comment by J38** [comment]
I would suggest you train a model with the Google Universal Dependencies data which I think is freely available.

Here is a link:

https://github.com/UniversalDependencies/UD_French

We did an experimental release in 3.8.0 of a French model with UD POS tags.  If you want to train on text without accents, you should preprocess that file to remove the accents.

Note the format of the training, dev, and test files should be two tab separated columns, the first is the token, the second is the POS tag.  Separate sentences with a blank line.
