### ISSUE TITLE
How to use WordToSentenceProcessor in Python?

### ISSUE THREAD

**Issue by carltonwang** [stanfordnlp/CoreNLP#532]
I want to split a list of words into a list of sentences, with each sentence being a list of words.
This can be done by your WordToSentenceProcessor, but how can I use it in Python?
Can you give me an example?

**Comment by J38** [comment]
There are a variety of ways to use Stanford CoreNLP via Python.  One such way is to use the `stanza` package in concert with the Stanford CoreNLP server:

Stanford CoreNLP server: https://stanfordnlp.github.io/CoreNLP/corenlp-server.html
stanza: https://github.com/stanfordnlp/stanza
