### ISSUE TITLE
[Part of speech] Inaccurate proper nouns tagging.

### ISSUE THREAD

**Issue by viebel** [stanfordnlp/CoreNLP#535]
Could you explain why sometimes the proper nouns tagging (NNP) is inaccurate.
For instance in this sentence: "Greater exposure to the market is required".
**Greater** is a `NNP` (inaccurate).
While in this sentence: "Better exposure to the market is required".
**Better** is a `RBR` (accurate)

Another example:
In this sentence:  "Automatic mail sending is an important feature."
**Automatic** is a `NNP` (inaccurate).
While in this sentence: "Instant mail sending is an important feature."
**Instant** is a `JJ` (accurate).

Here is a screenshot of the NLP Core online demo:
![image](https://user-images.githubusercontent.com/955710/31053853-be11a9de-a6ae-11e7-9a2c-e23db76d05b9.png)

**Comment by J38** [comment]
The part-of-speech model is a sequence tagging model trained on a large set of sentences.  These models are not quite perfect and make mistakes.  Their accuracy is in the 97% range.  Unfortunately that is the state of the art for this technology.  We are working on using more sophisticated sequence tagging models for future software we release, though even these methods will still make errors, and I cannot comment on whether or not it will make an error on your specific example.

**Comment by dekelcohen** [comment]
Does the POS Tagger has confidence scores ? Do you think it will help to use them (combined with other factors) to try to workaround cases like the ones mentioned above ? 
In [TestSentence.java](|https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/tagger/maxent/TestSentence.java) it mentions calculateProbs function. Do you think we can use that ?
