### ISSUE TITLE
I need VerbTense.java

### ISSUE THREAD

**Issue by nerzid** [stanfordnlp/CoreNLP#541]
I want to change verb's tense using this https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/naturalli/VerbTense.java

but it's currently not in 3.8.0 version. Why ? And when can it be avaliable ? If not, is there any workaround for this ?

thank you

**Comment by gangeli** [comment]
Ha! How did you even find this class?

It should be in the next version of CoreNLP -- I just wrote it a few months ago for a project I was doing, after 3.8 was released. Jason: do we have to add it explicitly as a root, since it's unused in the codebase?

**Comment by gangeli** [comment]
Oh, and as a workaround, you can always build the most recent version of the code with `ant jar`, and include the most recent models file in your classpath, and everything should work.

**Comment by nerzid** [comment]
Hello, thank you for fast respond! I'm using this toolkit for my thesis and don't want to use other nlp tools, that would be hideous, so I've searched through this repo for a possible solution and I'm glad I found it :smile:  .

I can build using `ant jar` you are correct but this class needs the file `conjugations_english.tab` and it's **not** in this repo or I wasn't able to find it.

**Comment by nerzid** [comment]
And also, is it possible to convert sentence into its passive form using corenlp?

**Comment by gangeli** [comment]
You'll need the most recent models, which can be downloaded from: http://nlp.stanford.edu/software/stanford-corenlp-models-current.jar

For converting sentences to their passive form: there's nothing built-in to do this, but I'd expect you can get fairly close with some dependency rewrite rules (see Semgrex) and conjugation.

**Comment by J38** [comment]
There is nice documentation for building the project from GitHub here:
https://stanfordnlp.github.io/CoreNLP/download.html

@gabor the script for generating dependencies sometimes misses things so we have a list of classes we manually add in

**Comment by J38** [comment]
I added this class to the release creation script for future editions.
