### ISSUE TITLE
British-style date only recognized as Number and not Date entity

### ISSUE THREAD

**Issue by leowmjw** [stanfordnlp/CoreNLP#550]
Testing online, it seems British-style date only recognized as Number and not Date entity:
```
I'll be away 20/10/2017 to 25/10/2017
```

If you can provide some guidance on the fix; I'll implement and do a pull request.  
From my quick inspection of the code, it is possibly an additional line of RegExp; is it correct?  
Also, it will be good to give the corenlp some hints to prioritize British-style date.

**Comment by J38** [comment]
This has been fixed for Stanford CoreNLP 3.9.0.  You need to set `sutime.language british` where I have added some rules to use British-style dates.  Keep in mind, this will recognize all dates with British format, so for instance `12/10/2017` will be recognized as `2017-10-12`.
