### ISSUE TITLE
Semgrex { } matches multiple nodes in child patterns

### ISSUE THREAD

**Issue by jayhill** [stanfordnlp/CoreNLP#552]
Semgrex documentation suggests that a pair of curly braces `{ }` represents a single token and that multiple assertions of the same token can be grouped with square brackets `[{ } | { }]`. It appears, however, that the components of an AND `CoordinationPattern` are applied independently, such that a single set of braces or brackets may end up matching multiple tokens.

Today, these patterns are functionally equivalent, but the documentation suggests that the third and fourth should behave differently, ensuring that the `pos` and `word` descriptions apply to the same node:
✅  `{$} > { pos:JJS } > { word:most }`
✅  `{$} [> { pos:JJS } & > { word:most }]`
❌  `{$} > { pos:JJS; word:most }`
❌  `{$} > [{ pos:JJS } & { word:most }]`

This example is verifiable at [http://corenlp.run](http://corenlp.run).
Input: `She said hello.`
Pattern: `{$} > { word:She; word:hello }`

Clearly, no node can have the `TextAnnotation` value of "She" and at the same time a value of "hello," yet this pattern matches because the root has dependents that match each child of the `CoordinationPattern`.

If this is expanded out, one can name the nodes and see that they both match:
Pattern: `{$} > [{ word:She }=sheNode & { word:hello }=helloNode]`

The issue appears to be particular to child patterns. If one inverts that pattern, it [correctly] no longer matches: `[{ word:She } & { word:hello }] < {$}`

### Why it matters:
Grouping node patterns is the only clear way to assert OR conditions, to assert positive and negative attributes of a node, or both "rootness" and any other attribute(s).
```
[{$} & { pos:/NN.*/ }=root] >amod [{ pos:JJS }=sup & !{ word:most }]
```
If the descriptions in `{ ; }` or `[{ } & !{ }]` or `[{$} & { }]` patterns don't reliably refer to the same node, then the power and accuracy of Semgrex is unnecessarily limited.

### A limited workaround:
The only way I've seen to describe the same node in a child pattern is to put each description in its own set of braces `{ }`, name every node, and assert their equality or inequality at the end using backreferences. Even then, I don't believe this fully achieves what a proper fix would do for all cases.
```
[{$} & { pos:/NN.*/ }=root] >amod [{ pos:JJS }=ref1 & !{ word:most }=ref2] : {}=ref1 == {}=ref2
```

**Comment by AngledLuffa** [comment]
Necro post!

I'm not convinced of what the semantics (pun intended) should be for 

 ```{$} > [{ pos:JJS } & { word:most }]```

It currently compiles to this:

 ```{$}  > {pos:JJS} > {word:most}```

This explains the behavior you are getting, even if it isn't the behavior you want.  Maybe it should just be an error.

This one is much more clear:

```{$} > { pos:JJS; word:most }```

I agree it should be matching one child node which is both a `JJS` and `most`.  I will investigate this one.

```[{ word:She } & { word:hello }] < {$}```

compiles to something which is output as the following:

```{word:She}  < {$}  {word:hello}  < {$}```

This statement doesn't compile, and I'm not sure what it is supposed to mean.  But I suspect that the & symbol between two nodes will simply be changed to be an error for both the < and the > cases.

**Comment by AngledLuffa** [comment]
I added this test to SemgrexTest.java.  Note that runTest with no labeled nodes as the third or later argument implies that it is supposed to match nothing.  The test passes, which to me suggests example #3 from above is behaving correctly.

```

  public void testConjunction() {
    // A possible user submitted error: https://github.com/stanfordnlp/CoreNLP/issues/552
    // A match with both POS and word labeled should have both attributes on the same node
    String pattern = "{$} > {pos:JJS;word:most}";
    // check that the compiled pattern is the same as the input pattern    
    comparePatternToString(pattern);
    SemgrexPattern semgrex = SemgrexPattern.compile(pattern);

    // root is "foo", has 3 children with various relations
    SemanticGraph graph = SemanticGraph.valueOf("[foo obj> most subj> bar dep> asdf]");
    // with no POS, should have no matches
    runTest(semgrex, graph);
    // index 1 is "most".  should match at the root
    graph.getNodeByIndex(1).setTag("JJS");
    runTest(semgrex, graph, "foo");
    // sanity check: should stop matching with the child set differently
    graph.getNodeByIndex(1).setTag("NN");
    runTest(semgrex, graph);
    // 1st word "most", 2nd word "_JJS".  Should not match
    graph.getNodeByIndex(2).setTag("JJS");
    runTest(semgrex, graph);
    // should now match at the root, as the second word is now "most_JJS"
    graph.getNodeByIndex(2).setWord("most");
    runTest(semgrex, graph, "foo");
  }
```

**Comment by AngledLuffa** [comment]
`[{ pos:JJS } & !{ word:most }]`

The straightforward understanding of this expression should be a word which is "_JJS" but is not "most".   I agree that such a thing should be possible.  

Technically it is already possible to negate a word attribute, for example, using a regex:

```
    SemanticGraph graph = SemanticGraph.valueOf("[ate subj>Bill obj>[muffins compound>blueberry]]");
    runTest("{word:/^(?!Bill).*$/}",
            graph,
            "ate", "muffins", "blueberry");
```

Using this you can negate any attributes as part of longer list of attributes:

```
  public void testNegatedAttribute() {
    SemanticGraph graph = SemanticGraph.valueOf("[ate subj>Bill obj>[muffins compound>blueberry]]");
    runTest("{word:/^(?!Bill).*$/}", graph,
            "ate", "muffins", "blueberry");
    graph.getNodeByIndex(0).setTag("NN");
    graph.getNodeByIndex(1).setTag("NN");
    graph.getNodeByIndex(2).setTag("JJS");
    graph.getNodeByIndex(3).setTag("NN");

    // find the JJS
    runTest("{pos:JJS}", graph,
            "muffins/JJS");
    // find any JJS with the text "muffins"
    runTest("{pos:JJS;word:muffins}", graph,
            "muffins/JJS");
    // find any JJS which is not "Bill"
    runTest("{pos:JJS;word:/^(?!Bill).*$/}", graph,
            "muffins/JJS");
    // find any JJS which is not "muffins": should be empty
    runTest("{pos:JJS;word:/^(?!muffins).*$/}", graph);      
    // find any not NN which is "muffins"
    runTest("{pos:/^(?!NN).*$/;word:muffins}", graph,
            "muffins/JJS");
    // find any not JJS which is not "Bill"
    runTest("{pos:/^(?!JJS).*$/;word:/^(?!Bill).*$/}", graph,
            "ate/NN", "blueberry/NN");
  }
```  

I'll add that as documentation to SemgrexPattern.  

I wonder if it would be cleaner to allow something like this:

```{pos:JJS;!word:most}```

**Comment by AngledLuffa** [comment]
Feel free to unsubscribe if you don't followups to this bug from years ago, btw.

```{$} > {word:She;word:hello}``` gets parsed to ```{$}  > {word:hello}```.  The conflicting constraint is dropped.  An exception would make it clear these shenanigans are not allowed.

Action items for this issue:

- Update javadoc to explain how to negate attributes (done)
- throw exception for repeated attributes such as a double `word`
- figure out what is happening with ```[{ word:She } & { word:hello }] < {$}```
- stretch goal: allow `!word:most` as an node description

**Comment by jayhill** [comment]
Thanks for looking at this old item!

FWIW, I am _pretty_ sure that negation of the form `!{ word:hello }` does work (we use this extensively); it is just that it doesn't work within grouping brackets (`[{ } & !{ }]` constructs).

What we ended up finding was that using `==` in grouping parentheses was more effective at asserting multiple conditions.
So, instead of
```[{$} & { pos:/VB.*/ }] > [{ pos:JJS } & !{ word:most }]```
which does not work as we expected, this does:
```({$} == { pos:/VB.*/ }) > ({ pos:JJS } == !{ word:most })```

**Comment by AngledLuffa** [comment]
The thing I'm struggling with here is, what should be the mechanics of 

[foo & bar] > zzz

I can think of three reasonable interpretations:

- one node has to be both foo and bar.  that node > zzz
- two nodes, foo > zzz and bar > zzz.  the zzz are the same
- two nodes, foo > zzz and bar > zzz.  the zzz are not required to be the same

Currently it is doing #3, which is possibly the least intuitive explanation.  Either of the others could be implemented without too much difficulty.  However, I don't like changing the semantics of semgrex without going through all the existing expressions to make sure none of them are affected.  That's not even possible in terms of checking semgrex expressions made in the wild.  Considering that problem, I think making this an illegal expression is the easiest.  At least that way people will be forced to rewrite the expression to get exactly what they are looking for.  Each of the three semantics can be achieved with some alternate writing of the semgrex, anyway.

> it is just that it doesn't work within grouping brackets ([{ } & !{ }] constructs).

This is the same issue, actually.  Currently, zzz < [foo & !bar] means zzz < foo, zzz < !bar, foo and !bar not necessarily the same node.  Probably this construction is more common even in our own internal usage, which means forbidding this would create a ton of extra work, so I won't bother.

In the next release of corenlp, the first half of your expression can be simplified to

{$;pos:/VB.*/}

I was considering also adding the ability to write

{pos:JJS;!word:most}

**Comment by jayhill** [comment]
All of this stems from the fact that the Semgrex PowerPoint deck linked from https://nlp.stanford.edu/software/tregex.shtml indicates that `[ ]` grouping works in the way I described.

This deck was the most clear and exhaustive source of documentation I could find when I started using Semgrex, and is the basis for much of my team's understanding of how it works.

![semgrex_node_grouping](https://user-images.githubusercontent.com/116148/70163036-bc621b00-168c-11ea-87ec-aaf15022773e.jpg)

**Comment by AngledLuffa** [comment]
Crazy.  I had completely forgotten that existed.  Discussing with my colleagues, it seems that disabling or altering semgrex functionality and looking for its use anywhere in corenlp isn't what we want to be doing while trying to get the next release out the door.  Maybe for now I'll just update that powerpoint to more clearly explain how these expressions work.

Glad your team had figured out the == trick.  & is essentially useless, as all patterns implicitly are conjunctions unless | is specified.  I can see how it would look like & means a node is both things at the same time, but internally that's not how it's implemented.

**Comment by AngledLuffa** [comment]
I updated the .ppt to include some of the various ways to get that effect instead of using &.  I also updated the parser to output a warning and a brief explanation when someone uses &.  The next release will involve that warning, and then the release after that will make it actually illegal to use such syntax.

Thanks for the report!  (Even if it took a while to handle.)

**Comment by jayhill** [comment]
Thank you! I appreciate you picking this up and working through it. 🙌 🏆

**Comment by AngledLuffa** [comment]
The new version is now live with these updates.  Also, I made it so the next version after this will throw an error instead of just warning people if they use this ambiguous construction.
