### ISSUE TITLE
Is sentiment treebank the training data? How to prepare my own train data?

### ISSUE THREAD

**Issue by ajige** [stanfordnlp/CoreNLP#553]
Hi, 
For the sentiment analysis model,  I want to train by myself, I saw this page for instruction, https://nlp.stanford.edu/sentiment/code.html
**Models can be retrained using the following command using the PTB format dataset:
java -mx8g edu.stanford.nlp.sentiment.SentimentTraining -numHid 25 -trainPath train.txt -devPath dev.txt -train -model model.ser.gz**

My question is,  what's the relationship between train data here and the sentiment treebank data mentioned in that paper for sentiment analysis model?
And If I make annotated data by myself, how to make that in the PTB format, is there any tools?

thanks.

**Comment by J38** [comment]
The training file is available at that link you provided.  We don't have any tools at this time for building sentiment training data.

**Comment by ajige** [comment]
what's the relationship between train data here and the sentiment treebank data mentioned in that paper for sentiment analysis model

**Comment by J38** [comment]
They are the same thing.

**Comment by ajige** [comment]
In the download page, there are 3 download link:
Dataset Downloads:
Main zip file with readme (6mb)
Dataset raw counts (5mb)
Train,Dev,Test Splits in PTB Tree Format

tree bank is this file:   Dataset raw counts (5mb)
but the train data is this: Train,Dev,Test Splits in PTB Tree Format

I think they are different, the Dataset raw is the tree bank, it includes phrases. But the PTB tree is the train,and dev test data. 

Can you explain about relationship of them more ?
Thanks.

**Comment by loretoparisi** [comment]
By the way the README.md has some useful info:

```
1. original_rt_snippets.txt contains 10,605 processed snippets from the original pool of Rotten Tomatoes HTML files. Please note that some snippet may contain multiple sentences.

2. dictionary.txt contains all phrases and their IDs, separated by a vertical line |

3. sentiment_labels.txt contains all phrase ids and the corresponding sentiment labels, separated by a vertical line.
Note that you can recover the 5 classes by mapping the positivity probability using the following cut-offs:
[0, 0.2], (0.2, 0.4], (0.4, 0.6], (0.6, 0.8], (0.8, 1.0]
for very negative, negative, neutral, positive, very positive, respectively.
Please note that phrase ids and sentence ids are not the same.

4. SOStr.txt and STree.txt encode the structure of the parse trees. 
STree encodes the trees in a parent pointer format. Each line corresponds to each sentence in the datasetSentences.txt file. The Matlab code of this paper will show you how to read this format if you are not familiar with it.

5. datasetSentences.txt contains the sentence index, followed by the sentence string separated by a tab. These are the sentences of the train/dev/test sets.

6. datasetSplit.txt contains the sentence index (corresponding to the index in datasetSentences.txt file) followed by the set label separated by a comma:
	1 = train
	2 = test
	3 = dev

Please note that the datasetSentences.txt file has more sentences/lines than the original_rt_snippet.txt. 
Each row in the latter represents a snippet as shown on RT, whereas the former is each sub sentence as determined by the Stanford parser.
```

**Comment by palfeng** [comment]
@loretoparisi Thanks. I read this file and at the point 4 it mentioned the Matlab code of this paper. Can you provide a source or link for it? The format of Stree.txt is a mystery.

**Comment by loretoparisi** [comment]
@palfeng unfortunately I do not have more info. Something helpful is here https://github.com/stanfordnlp/CoreNLP/issues/684 and here https://github.com/stanfordnlp/CoreNLP/issues/685

**Comment by cheungtitus** [comment]
@ajige maybe the following helps?
https://github.com/stanfordnlp/CoreNLP/issues/296
https://github.com/stanfordnlp/CoreNLP/issues/32#issuecomment-61037436
https://www.kaggle.com/c/sentiment-analysis-on-movie-reviews/discussion/12304

**Comment by bond-** [comment]
@J38 may I know the logic that was used to split a given sentence for the train data?

**Comment by lihaan** [comment]
For future readers wondering where to get the processed train / dev / test splits, this is the [repository](https://github.com/yoonkim/CNN_sentence/tree/master) by Yoon Kim, author of Convolutional Neural Networks for Sentence Classification who used it in his paper.

I found the preprocessed splits by following the pytorch links in the README to HarvardNLP repo which contains the files at this [folder](https://github.com/harvardnlp/sent-conv-torch/tree/master/data).
