### ISSUE TITLE
NER Classifier unable to classify time

### ISSUE THREAD

**Issue by ygsriram** [stanfordnlp/CoreNLP#558]
Hi, I am using the latest CoreNLP jar (stanford-corenlp-models-current.jar), but when I am using the 7 class NER classifier to get the tags, I am not able to get tags for time , eg. for 6 pm ,NER classifies it as 'O' rather than time. Can anyone please help me with the issue and tell me where I might have gone wrong. Thank you.

**Comment by J38** [comment]
When I run this command on an example sentence I get time annotations:

`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner -file time-example-1.txt -outputFormat text`
