### ISSUE TITLE
chinese_map_utils.jar 

### ISSUE THREAD

**Issue by s-matthew-english** [stanfordnlp/CoreNLP#56]
to execute the functionality described [here](https://github.com/stanfordnlp/CoreNLP/tree/master/src/edu/stanford/nlp/trees/international/pennchinese) do I have to make that chinese_map_utils.jar myself?

**Comment by J38** [comment]
This command will work with the current Stanford CoreNLP 3.7.0 release:

`java edu.stanford.nlp.trees.international.pennchinese.ChineseEnglishWordMap words-file.txt`

You need to have this file: `cedict_ts.u8` in the directory you run it from or set the "CEDICT" environment variable, which you have to get from here: https://www.mdbg.net/chinese/dictionary?page=cedict

This command will work as well:

`java edu.stanford.nlp.trees.international.pennchinese.RadicalMap -infile test.txt`

You can get Stanford CoreNLP 3.7.0 from here: http://stanfordnlp.github.io/CoreNLP/download.html
