### ISSUE TITLE
Parsing neural coref output (say xml) and resolving the references correspondingly in the original text.

### ISSUE THREAD

**Issue by vinaymundada27** [stanfordnlp/CoreNLP#560]
What is the best approach to resolve all the references in a text document (as given from the **neural coref** output) and modify the original document accordingly?

**Comment by J38** [comment]
So are you saying you want to turn:

`Barack Obama was born in Hawaii.  He was elected president in 2008.`

to:

`Barack Obama was born in Hawaii.  Barack Obama was elected president in 2008.`

**Comment by vinaymundada27** [comment]
@J38 Yes exactly. Want to do this for the entire document.

**Comment by vshan** [comment]
@J38 We are aware of the indices returned by the coref XML output, and have tried using it to resolve the references. 

However, we are having issues in tokenizing our text into sentences; as these sentences don't match the sentences returned by the CoreNLP sentence tokenizer used in the coref module. The tokenizer we use (   [java edu.stanford.nlp.process.DocumentPreprocessor](https://nlp.stanford.edu/software/tokenizer.html)) **does not** return the same number of sentences as returned by the tokenizer used in the coref module, hence the "Sentence IDs" don't match correctly and we lose the ability to resolve the references. 

Is there a command which would let us invoke the _sentence_ tokenizer used in the coref module directly?

**Comment by J38** [comment]
There is a very thorough example here: https://stanfordnlp.github.io/CoreNLP/coref.html

Look at the Java API section with the class CorefExample.
