### ISSUE TITLE
Change delimiter from '.' to '\n' for running coreference resolution (neural model)

### ISSUE THREAD

**Issue by vinaymundada27** [stanfordnlp/CoreNLP#561]

**Comment by J38** [comment]
Could you provide more details about your request?

**Comment by vinaymundada27** [comment]
Currently while running the coref (neural model), it tokenizes a given document **sentence-wise**. Is it possible to tokenize it **paragraph-wise** (since the paragraph information is lost after running coref)?
By paragraph I mean, text separated by **newline ("\n")**. Hence wanted to know if we can tokenize the text with the newline ("\n") delimiter.

**Comment by J38** [comment]
There is a thorough example of using a pipeline to generate coref info here:

https://stanfordnlp.github.io/CoreNLP/coref.html

If you add a ParagraphAnnotator, you can have some paragraph annotations as well.  

You will need these properties:

// always sentence split at newline
props.setProperty("ssplit.newlineIsSentenceBreak", "always");
// add ParagraphAnnotator to pipeline
props.setProperty("customAnnotatorClass.custom.paragraph", "edu.stanford.nlp.paragraphs.ParagraphAnnotator");
props.setProperty("annotators", "tokenize,ssplit,paragraph,pos,lemma,ner,parse,mention,coref");

Here is some example usage of the ParagraphAnnotator:

https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/paragraphs/RunParagraphAnnotator.java
