### ISSUE TITLE
Remove old TokensRegexNER file and references to it

### ISSUE THREAD

**Issue by manning** [stanfordnlp/CoreNLP#563]
Our code still refers to and has a DefaultPaths to `type_map_clean`, but it's really our tackbp2010 regexner. We should everywhere change to the two current files - currently in `kbp/regexner_* but they should maybe be moved out of the kbp dir.

**Comment by J38** [comment]
Should RegexNERAnnotator be deprecated ?  Currently `regexner` points to `TokensRegexNERAnnotator`.  This situation could cause some confusion.  I assume you would always want to use TokensRegexNERAnnotator over RegexNERAnnotator.  

Furthermore for 3.9.0 we should make sure include those in the main models jar.

**Comment by J38** [comment]
Wait, they already are in the default models jar, oops!

**Comment by J38** [comment]
I am going to remove RegexNERAnnotator since it is a duplicate of TokensRegexNERAnnotator

**Comment by J38** [comment]
Err, maybe I won't do that actually!
