### ISSUE TITLE
Contributions to Standford NLP Project

### ISSUE THREAD

**Issue by MadhuKush** [stanfordnlp/CoreNLP#564]
Hi Team,

We have been using the Standford NLP for textual extraction since 2 years. 
And It is an awesome software built which is helping us in lot many ways.

However we are facing some issues with the identification of NUMBERS and CURRENCIES from RegexNER rule file. 
Some of them we have reported in the GitHub for which we have received the responses. However it was not addressing all the issues.

So the reason why we are writing this mail is that we would like know more information on the below lists

1.	From where should we download the Standford NLP source project ?
2.	Which package can we modify in order to fix the issues with NUMBERS and CURRENCIES format given in RegexNER rule file ?
3.	Should we have to become a member of the group in order to contribute ? If yes how would we become ?
4.	How should we post the changes to the project ?
5.	How can we test the tool on the contributions/fixes made from our end ?
6.	What the conditions to contribute to the project ?
7.	What are the overall in and out procedure in steps to contribute to the project ?
8.	Who is the point of contact to work with for any further information or clarification needed throughout the contribution ? 

We hope you will kindly consider our request and respond positively ASAP.
Looking forward. 
Thank you in advance.

**Comment by J38** [comment]
1. The source project is available here on GitHub.  There are good instructions for building here: https://stanfordnlp.github.io/CoreNLP/download.html

2. The two major classes that handle numeric quantities are `edu.stanford.nlp.ie.QuantifiableEntityNormalizer` and `edu.stanford.nlp.ie.regexp.NumberSequenceClassifier` ; as I stated in a different issue, I can not reproduce your error

3-8. The general process for contributing to the project is to issue a pull request.  This is open to the public.  We will review pull requests and integrate them.  I would recommend corresponding with me via the GitHub page which I check fairly frequently.
