### ISSUE TITLE
Numbers represented in words are extracted only half of them

### ISSUE THREAD

**Issue by MadhuKush** [stanfordnlp/CoreNLP#565]
Hi Team,

Considering the below example sentence
There is an issue in number **seven hundred and seventeen**.

The NormalizedNamedEntityTagAnnotation of seven hundred and seventeen should be **717** but NLP is identifying it as only **100**

![image](https://user-images.githubusercontent.com/20786984/32429424-9c9ae9b0-c2f0-11e7-8d5b-6c07a5ce434e.png)

There are multiple examples with such issues. Please help us in overcoming these types.
Thank you in advance.

**Comment by J38** [comment]
I am not able to reproduce this error.  I ran this example:

    His age is seven hundred and seventeen.

```
I got this output result:

Document: ID=example-2.txt (1 sentences, 8 tokens)
Sentence #1 (8 tokens):
His age is seven hundred and seventeen.
[Text=His CharacterOffsetBegin=0 CharacterOffsetEnd=3 PartOfSpeech=PRP$ Lemma=he NamedEntityTag=O]
[Text=age CharacterOffsetBegin=4 CharacterOffsetEnd=7 PartOfSpeech=NN Lemma=age NamedEntityTag=O]
[Text=is CharacterOffsetBegin=8 CharacterOffsetEnd=10 PartOfSpeech=VBZ Lemma=be NamedEntityTag=O]
[Text=seven CharacterOffsetBegin=11 CharacterOffsetEnd=16 PartOfSpeech=CD Lemma=seven NamedEntityTag=NUMBER NormalizedNamedEntityTag=717.0]
[Text=hundred CharacterOffsetBegin=17 CharacterOffsetEnd=24 PartOfSpeech=CD Lemma=hundred NamedEntityTag=NUMBER NormalizedNamedEntityTag=717.0]
[Text=and CharacterOffsetBegin=25 CharacterOffsetEnd=28 PartOfSpeech=CC Lemma=and NamedEntityTag=NUMBER NormalizedNamedEntityTag=717.0]
[Text=seventeen CharacterOffsetBegin=29 CharacterOffsetEnd=38 PartOfSpeech=CD Lemma=seventeen NamedEntityTag=NUMBER NormalizedNamedEntityTag=717.0]
[Text=. CharacterOffsetBegin=38 CharacterOffsetEnd=39 PartOfSpeech=. Lemma=. NamedEntityTag=O]
root(ROOT-0, hundred-5)
nmod:poss(age-2, His-1)
nsubj(hundred-5, age-2)
cop(hundred-5, is-3)
nummod(hundred-5, seven-4)
cc(hundred-5, and-6)
conj:and(hundred-5, seventeen-7)
punct(hundred-5, .-8)
```

**Comment by MadhuKush** [comment]
Hi,
**Please find the below code which we are using and result generated from it. May be this will be of more clear where we are facing the issue**

Properties props = new Properties();
props.setProperty("annotators", "tokenize, ssplit, cleanxml, regexner, pos, lemma, ner, entitymentions"); props.setProperty("ner.useSUTime", "0"); 
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
String text = "His age is seven hundred and seventeen.";
Annotation document = new Annotation(text);
pipeline.annotate(document);

![image](https://user-images.githubusercontent.com/20786984/32490438-3945c472-c3d9-11e7-81f4-184ef60a4140.png)

**Even the mentions also giving as 100 and not as 717. Please find the below code for fetching mentions and its results**
List mentions = (List)sentence.get(java.lang.Class.forName("edu.stanford.nlp.ling.CoreAnnotations$MentionsAnnotation"));
![image](https://user-images.githubusercontent.com/20786984/32490549-8a458b32-c3d9-11e7-8390-835825e29073.png)

Not sure where we are wrong. Please help us.
Thank you in advance.

**Comment by J38** [comment]
Are you using the latest code from GitHub?

**Comment by J38** [comment]
This code with the latest code from GitHub produces the correct result:

```
package edu.stanford.nlp.examples;

import edu.stanford.nlp.ling.*;
import edu.stanford.nlp.pipeline.*;
import edu.stanford.nlp.util.*;

import java.util.*;

public class NumberEntityMentionExample {

  public static void main(String[] args) {
    // set up pipeline properties
    Properties props = new Properties();
    props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,regexner,entitymentions");
    // set up Stanford CoreNLP pipeline
    StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
    // build annotation for example
    Annotation annotation = new Annotation("The bike costs seven hundred and seventeen dollars.");
    // annotate example
    pipeline.annotate(annotation);
    for (CoreMap sentence : annotation.get(CoreAnnotations.SentencesAnnotation.class)) {
      for (CoreMap entityMention : sentence.get(CoreAnnotations.MentionsAnnotation.class)) {
        System.err.println("---");
        System.err.println(entityMention.get(CoreAnnotations.TextAnnotation.class));
        System.err.println(entityMention.get(CoreAnnotations.NormalizedNamedEntityTagAnnotation.class));
      }
    }
  }
}
```

**Comment by J38** [comment]
Output:

```
---
seven hundred and seventeen dollars
$717.0
```
