### ISSUE TITLE
How to map questions to questions in Stanford NLP

### ISSUE THREAD

**Issue by Kabilesh93** [stanfordnlp/CoreNLP#566]
I am new to NLP. I am working on a virtual avatar that communicates with the user. I want the system to answer the questions of the users. The Avatar and the entire system has been created with .NET. Therefore I had to choose Stanford NLP for .NET. The problem I have here is a question can be asked in many ways. I want to identify the questions that has similar meaning and map it to one question, therefore I can return the predefined answer. I know this can be done using NLTK or other NLP tools. Can this be done in Stanford NLP. If yes how can I achieve this?

**Comment by mcavdar** [comment]
[This report](https://nlp.stanford.edu/courses/cs224n/2006/fp/henggong-telarson-joshd-1-cs224n_project_report.pdf) can be useful in some way. From abstract:

> We use a combination of NLP and IR techniques to return the most relevant pre-answered question.

**Comment by J38** [comment]
I googled for this and found this project from CS 224N:

https://web.stanford.edu/class/cs224n/reports/2759336.pdf

There is nothing out of the box in Stanford CoreNLP that does this.  Off the top of my head I would recommend building a training data set of (q1,q2,yes/no) triples where q1 and q2 are different phrasings of a question.  

Then you train a neural network to identify questions that are the same or not.  That project report I mention claims there is a Quora dataset.  You'd probably be better off building something distinct to your domain, and you're going to want at least 10,000 - 100,000 examples, so you're going to have submit something to Mechanical Turk.

**Comment by J38** [comment]
I don't know if this would work or not, but you would imagine that question rephrasing is similar to textual entailment, in terms of determining a relationship between two sentences.

So you could try training one of the textual entailment models on a large (q1,q2,entails/contradicts) dataset and seeing if you get solid results.

AllenNLP has an out of the box system for training such models:

http://allennlp.org/models

I have no idea how well that would work
