### ISSUE TITLE
Misprediction on dep parse

### ISSUE THREAD

**Issue by jeffrschneider** [stanfordnlp/CoreNLP#569]
Dependency Parse has a misprediction: 
"How far did the sea level drop?" 
ADVMOD ROOT DEP	DET	COMPOUND COMPOUND DOB
(assuming you want mispredicitons here, as I found no other place).

**Comment by J38** [comment]
Thank you for mentioning this, we do want to know about algorithm errors.

**Comment by jeffrschneider** [comment]
There are MANY mispredictions. Not sure if you want me to open a new issue for each? 

// "night" should be a TMOD
The | night | before | last | , | Bob | ate | pizza
DT | NN | IN | JJ | , | NNP | VBD | NN
DET | NSUBJ | CASE | NMOD | PUNCT | NSUBJ | ROOT | DOBJ

**Comment by J38** [comment]
I'm starting a thread for dependency parse error collection here: https://github.com/stanfordnlp/CoreNLP/issues/694
