### ISSUE TITLE
what do maxLeft and maxRight means to NER

### ISSUE THREAD

**Issue by ajige** [stanfordnlp/CoreNLP#570]
Please help me.
java -cp ../../stanford-corenlp-3.7.0.jar edu.stanford.nlp.ie.crf.CRFClassifier -prop austen.prop

In the austen.prop file for crf ner module, When I set maxLeft and maxRight  both to 5, 
the Precision and Recall both rise to 0.99(from 0.9 when maxLeft = 3).
Why? is it reasonable?
Thanks!

**Comment by J38** [comment]
Please see this link for descriptions of these features: 

https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/ie/NERFeatureFactory.html
