### ISSUE TITLE
Modifying order of sentence array creates NPE

### ISSUE THREAD

**Issue by craigpfeifer** [stanfordnlp/CoreNLP#574]
When I process a text with the simple API (which is a really nice API btw), if I change the order of the sentences (via `Collections.reverse()` or `Collections.shuffle()`) and then make calls that require a model e.g. `parse()` those calls generate an NPE.

Workaround is to iterate through items via `get(int)` method on `List<Sentence>` instance from `Document.sentences()` method.

Code to recreate the error:
```
import edu.stanford.nlp.simple.*;
import java.util.*;

public class SimpleApiTest {

    public static void main(String[] whocares) {
        Document d = new Document("Hey everybody just wanted to say this is a new document. Wonder if this will work? This is another sentence. This is yet another sentence.");

        List<Sentence> sents = d.sentences();

        Collections.reverse(sents);

        for (Sentence aSent : sents)
        {
            System.out.println("aSent : "+aSent.text());
            System.out.println(aSent.parse().score());
        }
    }
}
```

stack trace:
```
Exception in thread "main" java.lang.NullPointerException
	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.fromProto(ProtobufAnnotationSerializer.java:1507)
	at edu.stanford.nlp.simple.Document.asAnnotation(Document.java:1091)
	at edu.stanford.nlp.simple.Document.runParse(Document.java:922)
	at edu.stanford.nlp.simple.Sentence.parse(Sentence.java:637)
	at edu.stanford.nlp.simple.Sentence.parse(Sentence.java:645)
	at SimpleApiTest.main(SimpleApiTest.java:15)
```

workaround:

```
import edu.stanford.nlp.simple.*;
import java.util.*;

public class SimpleApiTest {

    public static void main(String[] whocares) {
        Document d = new Document("Hey everybody just wanted to say this is a new document. Wonder if this will work? This is another sentence. This is yet another sentence.");

        List<Sentence> sents = d.sentences();

        for (int x=sents.size()-1; x>=0; x--)
        {
            System.out.println("x : "+x+" : "+sents.get(x).parse().score());
        }
    }
}
```

**Comment by J38** [comment]
Yes I would not advise tampering with the annotation in this manner, especially if you're using the simple API which is not designed to be very customizable.  I don't know the specific cause of this NPE, but if you start doing things like reversing the sentence list you're going to break the annotation data structure which expects things like the sentence list to be in the original order.  If you really want to have a list of the sentences in reverse order I would use your workaround or make a copy of the list and reverse the order.

**Comment by craigpfeifer** [comment]
Thanks for the response. If the intent is to not allow modification, I'd suggest making this explicit by returning an immutable list via ```Collections.unmodifiableList()```

This way, when they try to modify the list, it throws a ```java.lang.UnsupportedOperationException``` at the modification operation (in user code) and not deep in the bowels of your code.
