### ISSUE TITLE
"Shall" is parsed as a name rather than an auxiliary verb. 

### ISSUE THREAD

**Issue by natewatson999** [stanfordnlp/CoreNLP#575]
The POS tagging of "Shall Bob eat pizza?" is flawed. "Shall" is tagged as "NNP" when it should be "MD":

"Shall Bob eat pizza?":

This is tokenized as "Shall", "Bob", "eat", "pizza", "?"; with POS values of "NNP", "NNP", "VB", "NN", ".", when it should be "MD", "NNP", "VB", "NN", ".".

This can be reproduced on corenlp.run.

**Comment by AngledLuffa** [comment]
Honestly, that doesn't even look correct to me.  I've only ever seen it
used in the first person ("Shall I eat pizza" or "Shall we eat pizza"), or
as something akin to a command ("Bob shall eat pizza").

I would not be surprised to hear the tools get each of those wrong as well,
though, as it's not exactly a common word, even in the WSJ.

**Comment by natewatson999** [comment]
The exact same issue occurs with "May Bob eat pizza?". "may" gets tagged as "NNP" instead of "MD".

To be fair, both of these are cases of odd sentence structure.

**Comment by natewatson999** [comment]
This may be related to issue 576.

**Comment by J38** [comment]
Thank you for identifying an error case.  Unfortunately the statistical model will make mistakes at times, it only has 97% accuracy and is tuned towards Wall Street Journal text.

**Comment by J38** [comment]
Please see: https://github.com/stanfordnlp/CoreNLP/issues/680
