### ISSUE TITLE
In  /StanfordCoreNLP/src/edu/stanford/nlp/sentiment/SentimentPipeline.java Remove "-file" option the "-fileList" option can handle a list of 1.

### ISSUE THREAD

**Issue by alrahimi** [stanfordnlp/CoreNLP#58]
In  /StanfordCoreNLP/src/edu/stanford/nlp/sentiment/SentimentPipeline.java
Remove "-file" option the "-fileList" option can handle a list of 1.

both -file and fileList options are provided which is redundant and error prone. 
Right now file handling in the code for file and filelist are not in sync. 

  } else if (args[argIndex].equalsIgnoreCase("-file")) {
        filename = args[argIndex + 1];
        argIndex += 2;
      } else if (args[argIndex].equalsIgnoreCase("-fileList")) {

**Comment by AngledLuffa** [comment]
The difference is intentional.  -file goes to stdout, -filelist writes to
disk.  I suppose if we added an option to determine where the output goes,
that would allow unification of the processing code.

John

**Comment by alrahimi** [comment]
Hi John,
Thank you for clarifying.Probably can use filielist just for input and use
an output option  for output (with default  inputFile.out).
May be in that case can even allow -stdin as a filename.
But  I am sure you guys have more pressing things to do
thanks
Al
