### ISSUE TITLE
Improper Lemma Parsing

### ISSUE THREAD

**Issue by natewatson999** [stanfordnlp/CoreNLP#583]
There's a flaw in the Stanford Lemma algorithm:

"What is the English translation of tawhid?"

It yields "translation" for the lemma of "translation".  The parser should yield "translate" for the lemma of "translation".

**Comment by manning** [comment]
Hi Nate, this really isn't a flaw; it's just not giving you what you'd like....

What you are looking for is the "root" (or perhaps "stem" – people's terminology isn't completely consistent) of a word. Unfortunately, we don't currently provide anything for that. 

The "lemma" of a word is its dictionary form, which is commonly but not always the form without inflectional morphology (or in the canonical inflected form used in dictionaries, such as 1st person present singular for Latin verbs).  You would look up "translations" or "translation" in a dictionary under "translation" and would find it there....

See perhaps:
https://en.wikipedia.org/wiki/Root_(linguistics)
https://en.wikipedia.org/wiki/Word_stem
https://en.wikipedia.org/wiki/Lemma_(morphology)
