### ISSUE TITLE
Quality regression git vs. 3.7.0 and 3.8.0

### ISSUE THREAD

**Issue by kno10** [stanfordnlp/CoreNLP#584]
With CoreNLP 3.8.0 `edu.stanford.nlp.ie.crf.CRFClassifier -prop german.hgc_175m_600.prop`:
```
CRFClassifier tagged 51645 words in 3068 documents at 18664,62 words per second.
         Entity	P	R	F1	TP	FP	FN
            LOC	0,7869	0,6190	0,6929	731	198	450
           MISC	0,7486	0,4069	0,5273	411	138	599
            ORG	0,8260	0,5624	0,6692	698	147	543
            PER	0,7514	0,4768	0,5834	668	221	733
         Totals	0,7808	0,5189	0,6235	2508	704	2325
```
With CoreNLP 3.7.0
```
CRFClassifier tagged 51645 words in 3068 documents at 20477,80 words per second.
         Entity	P	R	F1	TP	FP	FN
            LOC	0,7869	0,6190	0,6929	731	198	450
           MISC	0,7486	0,4069	0,5273	411	138	599
            ORG	0,8260	0,5624	0,6692	698	147	543
            PER	0,7514	0,4768	0,5834	668	221	733
         Totals	0,7808	0,5189	0,6235	2508	704	2325
```

With current git (7fc91e35582e00de2c8b012cfb70138679534943), same properties file again, using :
```
commit 7fc91e35582e00de2c8b012cfb70138679534943 (HEAD -> master, upstream/master)
Author: Christopher Manning <manning@cs.stanford.edu>
Date:   Thu Nov 30 22:05:49 2017 -0800

    4 less javadoc warnings.

CRFClassifier tagged 51645 words in 3068 documents at 20951,32 words per second.
         Entity	P	R	F1	TP	FP	FN
            LOC	0,4514	0,7426	0,5615	877	1066	304
           MISC	0,2324	0,6426	0,3414	649	2143	361
            ORG	0,3447	0,5479	0,4231	680	1293	561
            PER	0,5490	0,5517	0,5504	773	635	628
         Totals	0,3671	0,6164	0,4601	2979	5137	1854
```

So the F1 dropped from 0,6235 to 0,4601. There is a regression in CRFClassifier in current git. Training time also increased substantially, by taking 380 instead of 299 iterations (in both 3.7.0 and 3.8.0).

**Comment by J38** [comment]
If it is any encouragement the stored model doesn't appear to work incorrectly.  I will attempt to train a German model and see what results I get.

**Comment by J38** [comment]
Also I should note even 3.7.0 has degraded performance according to your numbers.  We should see this result:

```
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - CRFClassifier tagged 51645 words in 3068 documents at 10324.87 words per second.
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -          Entity	P	R	F1	TP	FP	FN
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -             LOC	0.7977	0.7782	0.7878	919	233	262
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -            MISC	0.7934	0.5515	0.6507	557	145	453
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -             ORG	0.8456	0.6398	0.7284	794	145	447
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -             PER	0.9155	0.7116	0.8008	997	92	404
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -          Totals	0.8416	0.6760	0.7497	3267	615	1566
```

**Comment by J38** [comment]
Ok I am going to try to pinpoint when in the recent history this went wrong.  I see the current trained model is not performing as well as it should.

**Comment by kno10** [comment]
It is expected that my models are a bit worse than the released models, because they were run with `QNsize` reduced to 7 instead of 10 (to run with 4 GB), and had to use `useDistSim=false`, because I do not have `/u/nlp/data/german/ner/hgc_175m_600`. How do I obtain this file? It would be nice to be able to completely reproduce model training, and be able to also use this for domain specific model training.

**Comment by J38** [comment]
I reverted changes in July that seem to have caused this issue.  Please let me know if you can use the current code in GitHub and train a model comparable to the 3.8.0 release.

Here is info about the German models:

```
GERMAN NER CLASSIFIERS
======================

(1) Huge German Corpus-generalized classifier : This classifier has
    been trained on the CoNLL 2003 German data and has been
    generalized with the distributional similarity lexicon formed
    using the 175 million tokens of the HGC which have been clustered
    in 600 clusters. HGC is a collection of news-wire text, thus we
    suggest to use it for tagging the same.

(2) deWac-generalized classifier : This classifier has been trained on
    the CoNLL 2003 German data and has been generalized with the
    distributional similarity lexicon formed using the 175 million
    tokens of the deWac which have been clustered in 400
    clusters. deWac corpus has been created by scraping off content
    from the web, hence it is unclean and contains data from all
    genres, thus we suggest to use it for tagging all other kinds of
    documents.

--------------------------------------------------------
               |      HGC       |           deWac      |
--------------------------------------------------------
Type of Corpus |  Newswire-Text |  Data from Web (Raw) |
--------------------------------------------------------
Amount of Data |   175M tokens  |       175M tokens    |
--------------------------------------------------------
#Clusters      |      600       |            400       |
--------------------------------------------------------
```

**Comment by J38** [comment]
So I am not sure how `and has been generalized with the distributional similarity lexicon formed using the 175 million tokens of the HGC which have been clustered in 600 clusters.` was done to produce `hgc_175m_600`...I will investigate

**Comment by J38** [comment]
It is possible I can just send you this file, I am not sure there are any license issues...

**Comment by kno10** [comment]
With todays git, 4798589e72c873edd83e72af84d1039bd1150c66,  I get
```
         Totals	0,7808	0,5189	0,6235	2508	704	2325
```
but I do not understand how the commit 3c51ef22ea72ac3871f745bc853a22c566f9ba45 is causing this difference. To me, the code looks equivalent and _should_ not make a difference?!?

From what I can tell, the actual bug is likely in ObjectBankWrapper, which wraps `iterator()`, but forwards `toArray()` without wrapping. As this may resurface any time, I suggest to properly fix this there.

I would appreciate if you can share the HGC distsim file with me, but I understand if there may be licensing issues, although this is only a summary of that corpus.
Some information on this approach can apparently be found here:
http://www.manaalfaruqui.com/papers/konvens10_faruqui.pdf
http://www.aclweb.org/anthology/E03-1009
where they report ~7% increase in precision and ~13% increase in recall by using this approach.

As I want to apply this to other corpora and domains anyway, I am most interested in understanding how this could be used with other data. Am I correct in assuming the file is simply storing tokens (surface forms) and some cluster id each?

**Comment by manning** [comment]
Hi @kno10 , many thanks for the sleuthing -- I think you are definitely right. The problem was with the buggy definitions of `toArray()` in ObjectBankWrapper. I guess that bug had been there for a decade but just no one had used them. And hence what looked like harmless refactoring failed. I'll submit a fix for that and add a test.

**Comment by manning** [comment]
The previously used `german.hgc_175m_600.prop` also doesn't seem to have been as good as it could be; in particular, there were easy gains by just using less regularization. So, I'm making new a new version of that, which gives a model that breaks 0.65 F1, training on just the CoNLL 2003 data.

**Comment by manning** [comment]
On the `hgc_175m_600` file: Yes, it's distributional similarity clusters made from the Huge German Corpus, which are used as features in the NER to improve performance.

I imagine they're okay to share, but they were made originally by Faruqui/Padó. And in fact much more recently (in 2016), Sebastian Padó remade them to fix character encoding errors in the original. So we'd need to get permission from him. We'll ask.

**Comment by manning** [comment]
At any rate: The Stanford NER software supports word clusters in either the format output by Alex Clark's distributional similarity clustering (http://www.cs.rhul.ac.uk/home/alexc/) or Brown clustering (https://github.com/percyliang/brown-cluster). The former just produces a big long list of words with an integer class number for each:

Norden 492 0.0344469
entstehen 243 0.017008
Paul 75 0.00795746
Suche 76 0.118893

(well, also a probability in the cluster, which we ignore).
