### ISSUE TITLE
Improper Lemma Parsing in units of measurement

### ISSUE THREAD

**Issue by natewatson999** [stanfordnlp/CoreNLP#585]
When one runs "It alternates between 20 and 25 centimeters." through the lemma parser, alongside the dependencies; the lemma result for "centimeters" is "centimeter". The proper lemma should be "meter", since "centi" is a well known prefix meaning "1/100th of". 

I've confirmed the same issue with the following words:

- picometers -> picometer
- milligrams -> milligram
- gigahertz -> gigahertz
- kiloliters -> kiloliter

I suspect this isn't just a matter of limited dataset, because Stanford uses the WSJ dataset, and that has most of the main measurement words.

**Comment by manning** [comment]
You have a little too much faith in the occasional usage of metric by people in the USA. FWIW, there are no uses of "milligrams" or "kiloliters" in the PTB WSJ, and just one of "centimeters"....

But, substantively, I do agree that it would be useful to do more here, but I don't really agree on lemmas. Or, at any rate, our lemmatization only removes inflectional morphology like "undid" --> "undo", and not derivational morphology as well which might  take you back to "un" + "do".

What would be useful to add at some point would be parsing such quantity expressions as parsed numeric expressions, in the same way that we do parse something like "twenty five dollars", as you can see on http://corenlp.run/ .

In the meantime, it might possibly be useful for you to look at Marve:
https://memex.jpl.nasa.gov/KDD17.pdf
https://github.com/khundman/marve
