### ISSUE TITLE
 edu.stanford.nlp.process.PTBTokenizer failed to input/output files path pairs passed in file with ioFileList parameter

### ISSUE THREAD

**Issue by juhuahuang** [stanfordnlp/CoreNLP#586]
when I have input/ouput file path pairs in a file like:
input1  output1
input2 output2

only the first pair can be processor. and the program starts to fail from the second pair

**Comment by manning** [comment]
I believe this is a duplicate of #460.

This was a bug in version 3.8, but it is already fixed in head and not a problem in either 3.7 or the forthcoming 3.9.
