### ISSUE TITLE
Improper POS verb detection

### ISSUE THREAD

**Issue by natewatson999** [stanfordnlp/CoreNLP#587]
With the sentence "How far did the sea level drop in the ice ages?", CoreNLP 3.8.0 classifies the word part of speech of the word "drop" as "NN". It should be VB*.

**Comment by manning** [comment]
I agree that this is misparsed.

Parsing is done by machine learning models and although we do our best, we don't get the right parse in all cases, and this can't be immediately fixed.

I have added the example as one we'd like to get right, though, with "drop" as "VB".
