### ISSUE TITLE
Truecaser not running because of missing Java class

### ISSUE THREAD

**Issue by ghpaetzold** [stanfordnlp/CoreNLP#59]
Hello,

I am trying to use Stanford Core NLP for an EAMT funded project which is being implemented in Java, and we would love to use the tool's truecasing functionality. However, It seems that the whenever we try to run the truecasing annotator, we get the following error:

Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.sequences.TrueCasingForNISTDocumentReaderAndWriter

It seems like this is a very old problem which had been solved in the past but is now back in the newest versions. Is there any way it can be fixed?

Thanks in advance.

**Comment by AngledLuffa** [comment]
Good question.  It was moved to a different subdirectory in our system
which isn't picked up for release.  I'm not sure why, and this breaks the
truecase annotator.

**Comment by bradserbu** [comment]
Agreed.  I'm having the same issue on 3.5.1

**Comment by hans** [comment]
I've moved [`TrueCasingForNISTDocumentReaderAndWriter`](https://github.com/stanfordnlp/CoreNLP/blob/92ca767b6d498b1346ea44fb827de83fb60a4c4a/src/edu/stanford/nlp/sequences/TrueCasingForNISTDocumentReaderAndWriter.java) back into the code repository (92ca767b).

This will be included in the next release.

**Comment by erip** [comment]
@ghpaetzold Is this resolved?

**Comment by ghpaetzold** [comment]
@erip It seems to be :)
Thanks!

**Comment by manning** [comment]
Yes, this was fixed in v.3.5.2 ... but not closed.
