### ISSUE TITLE
misprediction: like as a verb

### ISSUE THREAD

**Issue by jeffrschneider** [stanfordnlp/CoreNLP#590]
Case: "Politicians like regulations more than farmers."

It's being tagged as a preposition.

**Comment by manning** [comment]
I agree that this is misparsed.

Parsing is done by machine learning models and although we do our best, we don't get the right parse in all cases, and this can't be immediately fixed.

I have added the example as one we'd like to get right, though.

**Comment by manning** [comment]
p.s. the difficulties of choosing the right PoS for "like" features in one of the long time most used examples of an ambiguous sentence: _Time flies like an arrow._
