### ISSUE TITLE
German lemmatization and sentiment tagging

### ISSUE THREAD

**Issue by n1try** [stanfordnlp/CoreNLP#596]
Will the German models support lemmatization and sentiment analysis in the near future? That'd be really great!

**Comment by J38** [comment]
Hi, so I don't think we will be adding German lemmatization any time soon.  The lemma code was manually created, and you can look it over in edu/stanford/nlp/process/Morpha.flex.  Unfortunately I don't think anyone on staff is going to recreate that in German any time soon.

With regards to sentiment, you could train a German sentiment model if you'd like fairly easily. Ultimately if you have a specific purpose though, you will probably want to collect training data that is specific to your use case.  For instance if you want to analyze movie reviews, you really need a corpus that is movie-review oriented.  There doesn't appear to be a single corpus that will handle various cases.

Here are two links to start you off with if you want to try training a German sentiment model.

Training data (I just found this on Google as an example):

http://aclweb.org/anthology/W17-1106
https://www.spinningbytes.com/resources/germansentiment/

Info on training a sentiment model:

https://nlp.stanford.edu/sentiment/code.html

Let me know if you have any questions and I can give advice.  If you'd like to contribute the model you build we could definitely be interested in distributing the German sentiment model in future releases.
