### ISSUE TITLE
Is there anyone who can give us a clear document about how to train Truecaser model ?

### ISSUE THREAD

**Issue by gladuo** [stanfordnlp/CoreNLP#601]
I'm using Truecaser model, and I am gonna using wikipedia data for training Truecaser model.
I searched on Google about this and it seems no one ever showed a successful experience of training a new Truecaser model.
So here, is there anyone who can give us a clear document about how to train Truecaser model ?
It should not be too much complicated, just some successful experience plz.

**Comment by J38** [comment]
please see: https://github.com/stanfordnlp/CoreNLP/issues/336

**Comment by J38** [comment]
I think this command should work:

`java -Xmx110g edu.stanford.nlp.ie.crf.CRFClassifier -prop your-prop-file.props -multiThreadGrad 8 `

Also, you can see an example prop file by looking at this file in the models jar: `edu/stanford/nlp/models/truecase/truecasing.fast.caseless.prop`

**Comment by J38** [comment]
The data format is one sentence per line, text tokenized by white space.
