### ISSUE TITLE
Manning: a touch of irony

### ISSUE THREAD

**Issue by jeffrschneider** [stanfordnlp/CoreNLP#602]
failed syntax parse on: "Manning is a top NLP expert."
(it's tagging Manning as VBG). 

=-=-=- 
Most syntax parsers are able to get this one right. I've noticed that CoreNLP has issues with proper names.  Not sure if you'd consider using one of the many 'names lists' available with a friendly license as new training tokens:
https://github.com/FinNLP/humannames/blob/master/list.txt

**Comment by jeffrschneider** [comment]
Here's a filtered list of names (first and last) that end in "-ing"

First Names Ending in -ing

Irving
Sterling
Ying
Ling
Changning
Szuting
King
Jing
Boxing
Chengqing
Ekaling
Spring


Last Names ending in -ing

Breining
Ahsing
Borgerding
Dowding
Bisping
Fearing
Mesenbring
Esterling
Pauling
Fitting
Manring
Hickling
Fremming
Reing
Fanning
Ding
Tregoning
Ashing
Wendling
Juengling
Joerling
Busing
Fleming
Rolling
Reidling
Kitching
Schaming
Sterling
Beadling
Froemming
Tysseling
Myking
Erpelding
Corning
Hotelling
Goulding
Hessling
Meinerding
Gramling
Sinning
Garing
Yearling
Tijing
Demulling
Fling
Weispfenning
Poling
Banning
Smiling
Ensing
Mehling
Stradling
Werring
Ming
Zaring
Huling
Cutting
Hoving
Mulling
Halling
Emerling
Flauding
Kipling
Schmeling
Wehking
Nowling
Buening
Moehring
Kassing
Codling
Luening
Leaming
Zehring
Wissing
Farthing
Running
Gerling
Darring
Harting
Woodring
Bitting
Fehling
Bleything
Harmening
Borcherding
Kersting
Branting
Alberding
Schuring
Jopling
Hetling
Hamling
Edling
Haering
Helmsing
Pfenning
Railing
Rossing
Maulding
Kroening
Dering
Strickling
Mcfarling
Goering
Dorning
Hopping
Hosking
Mooring
Setting
Venning
Spiering
Dettling
Wirsing
Easterling
Warling
Swilling
Wilging
Loegering
Salling
Leeming
Swing
Stoeltzing
Leming
Delling
Kaeding
Bicking
Kesselring
Nutting
Bohling
Thessing
Hommerding
Kiesling
Wenning
Blasing
Moring
Buehring
Yielding
Holling
Walding
Milling
Voelkerding
Zwilling
Kraling
Bowring
Theiling
Laning
Chowning
Engelking
Hollering
Neiling
Boeding
Gunning
Scherping
Mensing
Dusing
Belling
Geeting
Rotering
Broering
Wonderling
Aring
Taing
Willenbring
Breitling
Luecking
Fahlsing
Syring
Kettenring
Burling
Nearing
Hartling
Anding
Demling
Deering
Marling
Hachting
Wolfing
Hemming
Spearing
Ring
Sering
Spierling
Meyering
Greising
Helbling
Ebling
Stinespring
Rohling
Walkling
Feeling
Raveling
Herling
Flewelling
Levering
Erving
Buesing
Groening
Kisling
Lawing
Flaming
Johanning
Reusing
Glendenning
Gohring
Golding
Bring
Reinking
Gahring
Imming
Apling
Duesing
Hassing
Merkling
Derting
Lanning
Martling
Depping
Modgling
Boulding
Yuengling
Canning
Gerding
Medling
Johnting
Durling
Fielding
Pickering
Olberding
Merring
Kamerling
Klasing
Rising
Standring
Houghtelling
Foecking
Wakeling
Dearring
Stelling
Luehring
Garling
Serfling
Drewing
Bowering
Reising
Kettering
Schmaling
Fuelling
Kinsolving
Hunking
Helsing
Boeving
Tsing
Reichling
Fahning
Glassing
Cushing
Tielking
Cring
Riding
Ringering
Kreinbring
Aeling
Hamming
Handing
Stoneking
Elfering
Soderling
Harling
Frerking
Derring
Kling
Swadling
Hawking
Shilling
Forsting
Witting
Friemering
Frewing
Trilling
Munding
Tarring
Adling
Brading
Heling
Fickling
Tremelling
Moling
Grussing
Kelling
Brenning
Kissling
Leuhring
Wilding
Leiding
Jansing
Henning
Colling
Vining
Pershing
Browing
Hildring
Whitling
Alsing
Penning
Dowling
Channing
Ayling
Twining
Johansing
Wing
Seling
Knowling
Sebring
Strimling
Dilling
Sansing
Wearing
Houghtling
Herring
Heying
Lightning
Henfling
Glendening
Lansing
Gering
Merckling
Dimling
Boling
Melling
Behring
Belding
Hocking
Morning
Koenning
Snetting
Frohling
Spalding
Gosling
Gladding
Gooding
Wedding
Schuering
Luing
Wehling
Lowing
Oesterling
Volking
Jing
Gulling
Schmiesing
Norling
Hasting
Melching
Daking
Herzing
Weaving
Gieseking
Knipping
Hoesing
Ruffing
Wooding
Creveling
Ameling
Berling
Abling
Benzing
Earing
String
Donning
Anning
Messing
Reining
Bending
Luhring
Behning
Senderling
Bening
Leisenring
Heising
Fulling
Manning
Everding
Bertling
Elting
Gatling
Chewning
Perring
Schlichting
Dettmering
Ridling
Tipping
Bunning
Sing
Goodling
Rahming
Snelling
Lossing
Sandling
Kinning
Rushing
Haffling
Roling
Seiberling
Griebling
Stalling
Kolling
Huiting
Geving
Morring
Lambing
Binning
Pilling
Ruehling
Gathing
Vleming
Bering
Garding
Peeling
Lepping
Lenling
Laming
Werning
Holding
Sparling
Catching
Mourning
Stripling
Watling
Kirkling
Bolling
Cowing
Appeling
Mearing
Ording
Seering
Schleining
Cumming
Willing
Jungling
Curling
Washing
Roering
Blessing
Schelling
Kiening
Scotting
Sieverding
Gilling
Schimming
Shearing
Lofing
Doeberling
Dearing
Codding
Ewing
Mettling
Dewing
Balling
Schwering
Winterling
Drenning
Irving
Schanding
Schabbing
Lamping
Rowling
Lemming
Hutching
Assing
Maring
Merling
Ostling
Munning
Zarling
Lehning
Geeding
Sitterding
Spradling
Reineking
Hedding
Smalling
Dunsing
Haning
Wadding
Toting
Dohring
Pulling
Brunsting
Gearing
Boring
Hilding
Darting
Botting
Yingling
Engleking
Rilling
Bruening
Koening
Emberling
Sperling
Jarding
Siering
Massing
Schuiling
Kimberling
Findling
Gitting
Epling
Redepenning
Vissering
Foersterling
Houghtaling
Keisling
Ing
Bing
Gutting
Prinzing
Gihring
Gilding
Glessing
Whitting
Scantling
Heming
Herrling
Thilking
Vinning
Tussing
Corpening
Sieving
Goding
Stelting
Kiessling
Boening
Malling
Lanting
Tusing
Freiling
Broking
Lolling
Ketring
Riling
Scherbring
Hanning
Sichting
Reading
Bolding
Kabigting
Reding
Zerring
Terpening
Shelling
Raring
Gehling
King
Werking
Rensing
Sensing
Repenning
Haring
Piening
Corping
Colding
Willging
Minning
Bruning
Walking
Falling
Hearing
Gesing
Kolding
Steiling
Holsing
Doing
Kring
Seidling
Wilkening
Lueking
Cunning
Keeling
Loving
Verling
Appling
Persing
Drilling
Osting
Poeling
Worthing
Wareing
Grambling
Saling
Madding
Fleeting
Ting
Fuesting
Ramming
Wedeking
Lewelling
Giesing
Girling
Lapping
Wansing
Epping
Dudding
Copping
Koelling
Thesing
Starling
Standing
Mehring
Balding
Heiting
Otting
Kuning
Keding
Searing
Olding
Heading
Jording
Metting
Doring
Mossing
Watring
Hacking
Warning
Emmerling
Mering
Duensing
Suing
Nuding
Simmering
Hoefling
Welling
Roehling
Denning
Doelling
Oetting
Durning
Warring
Borling
Ging
Specking
Manwaring
Harding
Woodling
Tabeling
Spring
Rohlfing
Scheuring
Failing
Selking
Heuring
Emling
Doffing
Janning
Beeching
Gruening
Reckling
Snerling
Branning
Arning
Darling
Bidding
Reisling
Fryling
Schilling
Froning
Waring
Tarling
Hilling
Ratering
Mainwaring
Loring
Dekoning
Nading
Spaulding
Hsing
Whiting
Lunning
Wulfing
Stirling
Duling
Ping
Breiling
Helbing
Ebeling
Breuning
Pongkhamsing
Breeding
Shadding
Renning
Epting
Roesing
Frilling
Hunting
Benning
Elling
Goehring
Gehrking
Kenning
Gowing
Dahling
Goetting
Herting
Nolting
Hotaling
Paulding
Schoening
Schooling
Gossling
Billing
Jongeling
Deming
Menning
Reihing
Cabading
Going
Ising
Wentling
Eberting
Kaing
Greening
Quiring
Ying
Copening
Wotring
Bussing
Sweeting
Moulding
Roessing
Westerling
Daring
Erding
Rawding
Beerling
Bartling
Dailing
Klitzing
Mechling
Liming
Starring
Lenning
Wessling
Cowling
Brooking
Shiring
Fruhling
Conkling
Bunting
Gharing
Perking
Heppding
Clausing
Meling
Brening
Stocking
Laing
Ducking
Ling
Dreiling
Walling
Quilling
Bluming
Leising
Gerking
Vanhyning
Picking
Evering
Ruhling
Clendening
Lening
Latting
Schwing
Spratling
Gemberling
Dinning
Living
Siverling
Goeing
Koeing
Bensing
Kasting
Yeilding
Huesing
Gierling
Nordling
Browning
Mealing
Stribling
Ketterling
Luebbering
Blanding
Blazing
Gaulding
Downing
Etling
Cashing
Eastling
Pring
Soechting
Struebing
Neering
Harring
Poepping
Hoying
Hempfling
Werling
Sherling
During
Ponting
Detering
Deterding
Heinzerling
Panning
Brauning
Dunning
Arking
Grumbling
Demming
Dierking
Felling
Shierling
Rehling
Goring
Jerding
Revering
Redding
Shuping
Koning
Griffing
Kroesing
Ulwelling
Marking
Kemerling
Alling
Stremming
Chickering
Hemmerling
Reiling
Lensing
Freehling
Gillming
Fruehling
Hing
Cocking
Kaemmerling
Lovering
Sundling
Kemmerling
Winning
Doering
Hessing
Hering
Frieling
Kowing
Siemering
Berning
Kastning
Brining
Paling
Mohring
Boning
Hulzing
Skilling
Moening
Landing
Tuning
Spurling
Dooling
Khilling
Krenning
Erling
Schwarting
Rosing
Bowling
Keesling
Vestering
Eberling
Warsing
Wheeling
Charping
Koetting
Fasching
Vollmering
Wehring
Behling
Kading
Ronning
Doehring
Scharping
Welding
Kipping
Westling
Wieting
Firsching
Koehring
Friling
Getting
Helling
Gehring
Nehring
Ebbing
Bonning

**Comment by manning** [comment]
Ouch! A serious failure! 😆

We'll provide a fix for at least that case. Thanks.

You're right that what is going wrong is that if a word is unknown and it ends in -ing then the unknown word guesser is likely to make it a VBG. (Though this is just a feature, not an absolute choice.)

We're not in principle against using word lists, but at present we only use them for NER not POS. The NER (and dependency parse) is correct! Of course, like all these things, the balance is subtle. A number of the items on your list are not only used as names: Boxing, Spring, Fling, Welding, .... Of course, so can be "Manning", though it would be unusual for it to be capitalized when used as a verb.
