### ISSUE TITLE
case sensitive lemma failure

### ISSUE THREAD

**Issue by jeffrschneider** [stanfordnlp/CoreNLP#603]
in some cases, the lemma function is failing based on upper case characters. Here's some examples:
Farms, Places, Saints, Aborted, Teachers

Note that the lower case version works fine.

**Comment by manning** [comment]
Hi Jeff, thanks for the note. Strictly, we'd internally regard this as a failure of POS tagging: If the POS tag is right, then lemmatization will work, but if the POS tag comes out as NNP(S), then it won't be lemmatized. 

Many of these errors do again reflect limitations of our current training data: None of the first three words occur as common nouns in the training data....  We'll see what can be done.
