### ISSUE TITLE
Quote.Attribution Speakers Unknown 

### ISSUE THREAD

**Issue by ryan-gilbert** [stanfordnlp/CoreNLP#604]
In the commit [21c9c0630e7d2e4d796aa40f5001ed97c30e2b3d](https://github.com/stanfordnlp/CoreNLP/commit/21c9c0630e7d2e4d796aa40f5001ed97c30e2b3d) , people, corefs and quotes are being correctly identified, but not being included in the quote annotation. What could be some of the potential causes? 

Edit:

My apologies @J38 , I should've given more context. I went through your commits and made sure to comply with the changes, so my first notion was to check if you had to break something intermediately. 

By the way, thanks for those updates and the issue response!

I ran the sentence and annotators that worked for you and received the response below. Tried on both my dev server and corenlp.run and got the same response. From what I understand, corenlp.run is using the standard documented setup and integrates passing builds, right?

Could it be an issue in the http request encoding?

 Response:

```javascript
"corefs": {
    "2": [
      {
        "id": 0,
        "text": "Joe Smith",
        "type": "PROPER",
        "number": "SINGULAR",
        "gender": "MALE",
        "animacy": "ANIMATE",
        "startIndex": 1,
        "endIndex": 3,
        "headIndex": 2,
        "sentNum": 1,
        "position": [
          1,
          1
        ],
        "isRepresentativeMention": true
      },
      {
        "id": 4,
        "text": "He",
        "type": "PRONOMINAL",
        "number": "SINGULAR",
        "gender": "MALE",
        "animacy": "ANIMATE",
        "startIndex": 1,
        "endIndex": 2,
        "headIndex": 1,
        "sentNum": 2,
        "position": [
          2,
          3
        ],
        "isRepresentativeMention": false
      },
      {
        "id": 2,
        "text": "I",
        "type": "PRONOMINAL",
        "number": "SINGULAR",
        "gender": "UNKNOWN",
        "animacy": "ANIMATE",
        "startIndex": 4,
        "endIndex": 5,
        "headIndex": 4,
        "sentNum": 2,
        "position": [
          2,
          1
        ],
        "isRepresentativeMention": false
      }
    ]
  },
  "quotes": [
    {
      "id": 0,
      "text": "\"I want pizza.\"",
      "beginIndex": 40,
      "endIndex": 55,
      "beginToken": 9,
      "endToken": 14,
      "beginSentence": 1,
      "endSentence": 1,
      "speaker": "Unknown"
    }
  ]
```

Request:

```javascript
REQUEST { url: 'http://corenlp.run',
  method: 'POST',
  form: 'Joe Smith decided to get lunch. He said "I want pizza."',
  qs: { properties: '{"annotators":"tokenize,ssplit,pos,lemma,ner,depparse,coref,quote","pipelineLanguage":"en"}' },
  json: true,
  agent: false,
  pool: { maxSockets: 5 },
  forever: true,
  timeout: 120000,
  callback: [Function: RP$callback],
  transform: undefined,
  simple: true,
  resolveWithFullResponse: false,
  transform2xxOnly: false }

REQUEST onRequestResponse http://corenlp.run/?properties=%7B%22annotators%22%3A%22tokenize%2Cssplit%2Cpos%2Clemma%2Cner%2Cdepparse%2Ccoref%2Cquote%22%2C%22pipelineLanguage%22%3A%22en%22%7D 200 { 'access-control-allow-credentials-header': '*',
  'access-control-allow-headers': '*',
  date: 'Fri, 19 Jan 2018 16:15:03 GMT',
  'access-control-allow-methods': 'GET,POST,PUT,DELETE,OPTIONS',
  'content-type': 'application/json;charset=UTF-8',
  'access-control-allow-origin': '*',
  'access-control-allow-credentials': 'true',
  'content-length': '7811' }

REQUEST response end http://corenlp.run/?properties=%7B%22annotators%22%3A%22tokenize%2Cssplit%2Cpos%2Clemma%2Cner%2Cdepparse%2Ccoref%2Cquote%22%2C%22pipelineLanguage%22%3A%22en%22%7D 200 { 'access-control-allow-credentials-header': '*',
  'access-control-allow-headers': '*',
  date: 'Fri, 19 Jan 2018 16:15:03 GMT',
  'access-control-allow-methods': 'GET,POST,PUT,DELETE,OPTIONS',
  'content-type': 'application/json;charset=UTF-8',
  'access-control-allow-origin': '*',
  'access-control-allow-credentials': 'true',
  'content-length': '7811' }
```

**Comment by J38** [comment]
Could you give me an example.  Also I recently set up the `quote` annotator to just build a `quote.attribution` annotator and run it because I just assumed people would always want the attribution with the quotes.  This is a general pattern I have been introducing in several places.  For instance now the `ner` annotator handles the work of the `tokensregexner,entitymentions` annotators and now `coref` annotator also will run `coref.mention` as before.  My main goal was to shorten the annotators list.

Any rate, if you provide me some failure examples I will make any small fixes necessary to get it working properly.

**Comment by J38** [comment]
Also I changed the name from `quoteattribution` to `quote.attribution`

**Comment by J38** [comment]
Ok so I ran this command (with the latest checkout from git)

`java -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,depparse,coref,quote -file quote-example.txt -outputFormat text`

On this file (quote-example.txt):

`Joe Smith decided to get lunch.  He said "I want pizza."`

And I identified Joe Smith as the speaker of the quote.

**Comment by ryan-gilbert** [comment]
Just tried it again on my dev server and it's now correctly working. Not exactly sure why though. It may be because my instance on Google Compute engine rebuilt the container and it pulled down your latest commits. Thanks again for your help!
