### ISSUE TITLE
OutOfMemEx on seemingly innocuous data

### ISSUE THREAD

**Issue by rgwood1234567890** [stanfordnlp/CoreNLP#608]
I've noticed that a fairly standard pipeline will throw a OOME on common "Internet" data. I've used 22+GB heaps and it still errors out on input less that 4k chars. Typical scenarios is which this occurs are repeated phrases (sentence fragments) or many braces. I have gone into the code and removed a lot of places where OOME are caught (catching these in a library is rarely a good idea, IMO).

The offending code is the large allocs in ExhaustivePCFGParser.createArrays():

...
iScore = new float[length][length + 1][];
...
	for (int start = 0; start < length; start++) {
		for (int end = start + 1; end <= length; end++) {
			try {
				iScore[start][end] = null;
				iScore[start][end] = new float[numStates]; // oome here
...

numStates=12977 seems to be a model dependent constant - in this case the stock model.
length=1007 in one case
The allocs for this 3-d array are only ~1.1GB and yet are causing a 22GB JVM to OOME.

Looking through the code I don't see any way to limit the allocs here. The regular mode of operation should probably handle most all text within 4GB. If it can't , it should throw maybe a validation exception of some sort.

The props I used are: "tokenize, ssplit, pos, lemma, parse"
props.put("parse.maxlen", 512); // len in tokens; doesn't seem to work

Simple input enclosed in dquotes follows:
"I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg      I am a bad egg"

**Comment by J38** [comment]
Have you tried `parse.maxlen = 100`.  512 is probably too high.

**Comment by manning** [comment]
It's just the nature of type dynamic programming algorithms used in the default parser used by `parse` that it takes a lot of memory when the sentences are very long!

But we have alternatives! If you only need dependency parses, try the `depparse` annotator instead. Using it ("tokenize,ssplit,pos,lemma,depparse"), I could parse this sentence in 1GB of RAM!

If you need constituency parsing, try using the SR parser model. You need the extra English models jar for it to be available. Using it (`-annotators tokenize,ssplit,pos,lemma,parse -parse.model edu/stanford/nlp/models/srparser/englishSR.ser.gz`, I could parse this sentence in 2GB of RAM.

In general, see: https://stanfordnlp.github.io/CoreNLP/memory-time.html
