### ISSUE TITLE
Invalid JSON output format

### ISSUE THREAD

**Issue by ntaoo** [stanfordnlp/CoreNLP#61]
Hello,

When I try POS tagging with stanford-corenlp-3.5.1, I got following part of the output by StanfordCoreNLP's jsonPrint method.

{
    "index": "5",
    "word": "\'s",
    "lemma": "\'s",
    "characterOffsetBegin": "17",
    "characterOffsetEnd": "19",
    "pos": "POS"
}

Sample sentence: "I was the teacher's student."

It looks like the "word" and "lemma" contain invalid JSON format and json validations fail. Single quote characters do not need to be escaped according to http://json.org/.
You can check it in http://jsonlint.com/

I glanced at the code, and maybe this part is relevant to it. https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/JSONOutputter.java#L178

I hope it is not my misunderstanding and I can commit for it.
Regards,

**Comment by gangeli** [comment]
Yes, this is a bug -- thanks for pointing it out! We'll commit the fix within the next day or so. Is crediting it to the username + address on your github ok?

**Comment by ntaoo** [comment]
Thank you for the answer. Yes, I'm happy to be credited!
