### ISSUE TITLE
Stanford CoreNLP Truecase Annotator giving null TrueCaseTextAnnotation

### ISSUE THREAD

**Issue by mahdiman** [stanfordnlp/CoreNLP#611]
I am trying to case correct an all lowercase text using Stanford's trueCaseAnnotator so, if I have a statement like this: "jack went to russia", I want it to be "**J**ack went to **R**ussia"I've tried to make a pipeline as follows:
```
var props = new Properties();
// set pipeline annotators.
props.setProperty("annotators", "tokenize, ssplit, truecase, ner");
props.setProperty("ner.useSUTime", "0");
props.setProperty("truecase.overwriteText", "true");

Directory.SetCurrentDirectory(modelsPath);
pipeline = new StanfordCoreNLP(props);

// annotate text
var annotation = new Annotation(text);
pipeline.annotate(annotation);
```

and whenever I annotate a text using this pipeline configuration, I only get three annotations

1. TextAnnotation
2. TokenAnnotation
3. SentenceAnnotation

and there is no record for TrueCaseTextAnnotation which is what I need, instead it changes values of the tokens to be truecase only.

I used Stanford CoreNLP 3.8.0 and 3.7.0 (English models) with the [C# wrapper ](https://www.nuget.org/packages/Stanford.NLP.CoreNLP/)for the Stanford library and the problem still existing.

**Comment by J38** [comment]
I can't speak to whether or not the C# wrapper is causing a problem, but the `TrueTextCaseAnnotation` is a key that the `CoreLabel token` has.  So each token has a key representing the text of the true case version.  If you run this in Java using the `truecase` annotator it will print out the proper version for each token in the output.
