### ISSUE TITLE
Quote Attribution Speaker Data

### ISSUE THREAD

**Issue by ryan-gilbert** [stanfordnlp/CoreNLP#616]
It seems like the name of quote.speaker doesn't resolve to the representative mention for it's corefs, at least for JSON output. It would also be really useful to populate entitylink data in quote as well. 

If these features haven't been implemented, would a custom annotator be the best way to accomplish this?

**Comment by J38** [comment]
This'll get fixed soon.  I've changed it some so there is the speaker and the "canonical speaker", which would be the representative speaker.  So in the example of 'Joe Smith went to get lunch.  He said "I want pizza."  Joe ended up getting a hamburger.', "He" would be the speaker, but "Joe Smith" would be the "canonical" speaker.  So I probably need to update output fields to access the canonical speaker.  Also, you might want to look at the `CoreQuote` class that was recently added, which is a new wrapper for handling quotes, this of course works with the new "CoreDocument", "CoreEntityMention", and "CoreSentence" wrappers.  The aim of these new classes is so users no longer have to write something like `quote.get(QuoteAttributionAnnotator.MentionAnnotation.class)` and can instead write something like `quote.getCanonicalSpeaker()`.

**Comment by J38** [comment]
Also I suppose I'll add a link to an entity mention for the quotes so you can access the entity link.

**Comment by ryan-gilbert** [comment]
Awesome, thank you. I did notice the additions with canonical speakers, but couldn't confirm it was the same as representative speakers with my very limited experience in Java. Also, I had one less important but useful feature suggestion for the future: it would be nice if the JSON output for entity mentions included an array of all the speakers instead of just being listed by sentence. But that's just a small matter of convenience. Thanks for everything else.

**Comment by J38** [comment]
If you run this command:

`java -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,depparse,coref,quote -file quote-w-coref-example.txt -outputFormat json`

You should see a `canonicalSpeaker` field now in the JSON.

I ran this on a test document with this text:

`In the summer Joe Smith decided to go on vacation.  He said, "I'm going to Hawaii."  That July, vacationer Joe went to Hawaii.`

**Comment by J38** [comment]
Also see this test for an example of how to use the new `CoreQuote` wrapper.  This will allow you to access that actual `entity mention` data object for the speaker rather than just the String.

**Comment by J38** [comment]
itest/src/edu/stanford/nlp/pipeline/CoreQuoteSanityITest.java

**Comment by J38** [comment]
So for example:

```
CoreDocument testDoc = new CoreDocument("...");
pipeline.annotate(testDoc);
List<CoreSentence> allSentences = testDoc.sentences();
List<CoreEntityMention> allEntityMentions = testDoc.entityMentions();
List<CoreQuote> allQuotes = testDoc.quotes();
```

**Comment by J38** [comment]
`CoreEntityMention canonicalSpeaker = testDoc.quotes().get(0).getCanonicalSpeakerEntityMention().get();`

**Comment by J38** [comment]
String wikipediaLink = canonicalSpeaker.entity();

**Comment by J38** [comment]
Note that someQuote.getCanonicalSpeakerEntityMention() returns an Optional<CoreEntityMention>.
Optional's are a new feature in Java that allow cleaner handling of null's.  So if you have an Optional<CoreEntityMention> myCoreEntityMention, you get the actual CoreEntityMention with the `get()` method.  So `myCoreEntityMention.get()` returns the `CoreEntityMention` stored in the Optional.  If the Optional stores a null, you will get an exception.  You can check if an Optional stores a real object or a null with the `isPresent()` method, which is true if there is non-null value in the container.

**Comment by ryan-gilbert** [comment]
Awesome, thanks for all the info. Just confirmed canonical speakers are showing up correctly in noisy text from online articles. Very useful. Although single quotes (') are still generating quotes, despite the default properties and my own properties disabling both singleQuotes and smartQuotes.
