### ISSUE TITLE
CoNLLMentionExtractor always uses ``auto_conll`` files.

### ISSUE THREAD

**Issue by dragoon** [stanfordnlp/CoreNLP#62]
Hello,

it seems that ``CoNLLMentionExtractor`` always uses ``auto_conll`` to extract entity mentions, even for gold mentions. However, gold mentions are contained in ``gold_conll`` files. This results in the metric scores always being equal to zero.
In particular, on line 75:

    if (Constants.USE_CONLL_AUTO) options.setFilter(".*_auto_conll$");

Is this the correct behavior or am I missing something?

**Comment by xzephyr** [comment]
Hi Roman,

auto_conll uses parser's parse tree and gold_conll uses human annotated
parse tree. Both have the same gold mentions ( thus auto_conll might have
some gold mention not being a NP due to parser error )

Both the official evaluation and most system reports on auto_conll, which
is why it is the default.

Zero score might indicate some configuration problems, how are you running
the system?


Xiao

**Comment by dragoon** [comment]
Hello Xiao,
Thanks for the reply!

I'm running the ``SieveCoreferenceSystem`` using the following ``coref.properties`` file (mostly copied from the website of Stanford coref.):

    annotators = pos, lemma, ner, parse
    dcoref.score = true
    dcoref.postprocessing = true
    dcoref.maxdist = -1
    dcoref.use.big.gender.number = false
    dcoref.replicate.conll = true
    dcoref.conll.scorer = /Users/.../reference-coreference-scorers/v8.01/scorer.pl
    dcoref.logFile = logs
    dcoref.conll2011 = /Users/.../conll-2012/v4/data/test/data/english/annotations

As regarding the different between _auto and _gold, I have manually checked and I can confirm that _auto_conll files do not contain any gold coreferences (last column), while _gold_conll indeed has coreferences properly marked.

**Comment by xzephyr** [comment]
Hi Roman,

That sounds weird. I checked all training/dev *._auto_conll files from
conll-2011 and conll-2012 contains gold mentions. Can you check your data
source, making sure it is not overwritten by something else?

e.g.:
xiao~$ diff
v0/data/train/data/english/annotations/bc/cnn/00/cnn_0004.v0_auto_conll
v0/data/train/data/english/annotations/bc/cnn/00/cnn_0004.v0_gold_conll |
head -n 14
2,7c2,7
< bc/cnn/00/cnn_0004   0   0      Tonight    RB  (S1(FRAG*   -   -   -   -
     (TIME)    -
< bc/cnn/00/cnn_0004   0   1          the    DT       (NP*   -   -   -   -
         *   (30
< bc/cnn/00/cnn_0004   0   2    legendary    JJ          *   -   -   -   -
         *     -
< bc/cnn/00/cnn_0004   0   3         Mike   NNP          *   -   -   -   -
  (PERSON*     -
< bc/cnn/00/cnn_0004   0   4      Wallace   NNP          *)  -   -   -   -
         *)   30)
< bc/cnn/00/cnn_0004   0   5           /.     .         *))  -   -   -   -
         *     -
---
> bc/cnn/00/cnn_0004   0   0      Tonight    NN   (TOP(FRAG(NP*)  -   -   -
  -      (TIME)    -
> bc/cnn/00/cnn_0004   0   1          the    DT            (NP*   -   -   -
  -          *   (30
> bc/cnn/00/cnn_0004   0   2    legendary    JJ               *   -   -   -
  -          *     -
> bc/cnn/00/cnn_0004   0   3         Mike   NNP               *   -   -   -
  -   (PERSON*     -
> bc/cnn/00/cnn_0004   0   4      Wallace   NNP               *)  -   -   -
  -          *)   30)
> bc/cnn/00/cnn_0004   0   5           /.     .              *))  -   -   -
  -          *     -


Thanks,

Xiao

**Comment by dragoon** [comment]
Hello Xiao,

Indeed, my train/dev files also contain coreferences, but I was actually running the system on **test data** as you can see from the config. And the test data does not contain them. Is that a problem?

**Comment by xzephyr** [comment]
Hi Roman,

Please refer to http://conll.cemantix.org/2012/data.html

Generally test set is intended for end to end evaluation and thus at the
time did not include gold mentions or coreference.
The auto evaluation provided in CoreNLP is also intended for train/dev
only, as test evaluation was done by task organizer.

If you wish to leverage the test set for development, maybe generate the
auto_conll with corresponding mentions?

Xiao

**Comment by dragoon** [comment]
Ok, thanks!

I thought since you had the results on ``conllst2011 test `` on http://nlp.stanford.edu/software/dcoref.shtml, then I could also run it.
