### ISSUE TITLE
Difference b/w Model Jar Language English and English(KBP)

### ISSUE THREAD

**Issue by MadhuKush** [stanfordnlp/CoreNLP#621]
Hi Team,

We are trying to download the Stanford NLP Model jar from the below link for English language.
https://stanfordnlp.github.io/CoreNLP/download.html

But we found two jars of type English and English(KBP)
![image](https://user-images.githubusercontent.com/20786984/35845631-4a244118-0b39-11e8-9ecc-9ad75fa616ef.png)

What is the difference between these two and which one is the best. Please provide your suggestions and explanations.

Thank you in advance

**Comment by gangeli** [comment]
For most things, the regular English models should be sufficient. The KBP models are only for the new relation extractor (the `kbp` annotator), and are somewhat large, which is why they're broken out as a separate jar.

**Comment by MadhuKush** [comment]
Hi,
Thanks for the explanation. 
A similar question if you dont mind could you please tell whats the 
difference between models jar file that come along when we download CoreNLP 3.9.0
(**this models jar file size is 426MB**)

![image](https://user-images.githubusercontent.com/20786984/35899157-da423d9c-0bf0-11e8-8895-08163f944d4f.png)

 and only models jar file that the we download from the below (**this models jar file size is 1.26GB**)

![image](https://user-images.githubusercontent.com/20786984/35899180-f74d20be-0bf0-11e8-9c85-b14c50d21241.png)
 
Please suggest which is good for extracting most of the entities without any issues.
Thank you in advance

**Comment by gangeli** [comment]
The `English` models have more variants of each of the models than the official distribution. For example, I believe the English models include the shift-reduce constituency parser, in addition to the PCFG models. Again, for most cases, you should be ok just using the official distribution.

**Comment by MadhuKush** [comment]
Okay thanks alot

**Comment by LifeIsStrange** [comment]
@gangeli it is unclear to me whether kbp is a strict superset of the default english, it is unclear if it has on average better performance (orthogonally to being more expressive).
Also I am coming from Spacy and I am surprised your english model doesn't has a large version a la BERT-large.
btw I wonder what model you're using and whether it's still state of the art (XLnet)
