### ISSUE TITLE
Pure c# port

### ISSUE THREAD

**Issue by knuppe** [stanfordnlp/CoreNLP#63]
I recently had finished a port/reimplementation of OpenNLP library in C#, and would like to do the same with StanfordNLP! :yum: 

There is any impediment (regarding the dual license) to make this port?

**Comment by manning** [comment]
You're totally allowed to take the Stanford CoreNLP code and to port/reimplement it in C# !

The legal technicalities would simply be:
 - If the code is in part or in whole a port or translation of Stanford CoreNLP code, then it would also need to be under a GPL license.
 - If the code is in part or in whole a port or translation of Stanford CoreNLP code, then those parts would remain copyright Stanford University.
 - You're not allowed to imply endorsement by Stanford University. 

I think the dual licensing part is irrelevant. It would only be relevant if someone wished to be able to purchase the result under a commercial license.

If you're also interested in producing Portuguese models, which are compatible with our Java models, and which we could also distribute, then we'd also be pleased to do that. :)

I presume you're aware of Sergey Tihon's work but are wanting to do more of a true translation?

**Comment by knuppe** [comment]
Thanks for the reply!
I would like to make a true/real port... For a few reasons:

1. It is fun to re-implement ;-)
2. The IKVM is very interesting, but it uses a LOT of memory!
3. In the past when I was using the parser of OpenNLP through IKVM, I noticed that in the some cases the results/tags ware different from the parsed sentence using Java. I am afraid the same will happen with the StanfordNLP.

The idea is to re-implement using the .net technology, otherwise there is no reason to make a ctrl+c and ctrl+v of the StanfordNLP.

Well, it will not be easy! It has some peculiarities that will be complicated to implement, such as the Java serializer that writes the models... It does not exist in C# :'(

Let’s see what can be accomplished.

**Comment by AngledLuffa** [comment]
Just as long as you realize you will be chasing a moving target

**Comment by Jetski5822** [comment]
@knuppe have you tried to do the port? im thinking of giving it a go myself.
