### ISSUE TITLE
Call edu.stanford.nlp.pipeline.Annotation with new Properties

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#633]
I'm running several annotations at once like `tokenize,ssplit,pos,parse,sentiment,ner,regexner,entitymentions`, that I setup when initializing a new `edu.stanford.nlp.pipeline.StanfordCoreNLP` instance and passing the `Properties` object.

I would like to run a different set of Properties in my process without reloading the `StanfordCoreNLP`, passing a different configuration for the tokenizer/ssplit like `"ssplit.newlineIsSentenceBreak": "two"` instead of `"ssplit.newlineIsSentenceBreak": "never"`, etc.

So that I could call the `StanfordCoreNLP.annotate` after setting up the new `Properties` without reload everything. Is that possibile or shall I have to clone this different pipeline (same annotators), but initializing with a different set of Properties?

**Comment by gangeli** [comment]
Perhaps only a half-satisfying answer, but: creating a new `StanfordCoreNLP` object doesn't necessarily reload all of the annotators. We do keep a cache of already loaded annotators, and only ones whose property signature changed are reloaded.

**Comment by loretoparisi** [comment]
@gangeli thank you, so this means that if I create new instances of the `StanfordCoreNLP` class, and I see logs like

```
10:36:41.399 [main] INFO  e.s.nlp.pipeline.AnnotatorPool - Replacing old annotator "tokenize" with signature [tokenize.keepeol:false;ssplit.isOneSentence:false;ssplit.newlineIsSentenceBreak:two;tokenize.language:en;tokenize.whitespace:false;] with new annotator with signature [tokenize.language:de;ssplit.newlineIsSentenceBreak:two;tokenize.keepeol:false;tokenize.whitespace:false;ssplit.isOneSentence:false;]
10:36:41.401 [main] INFO  e.s.nlp.pipeline.AnnotatorPool - Replacing old annotator "pos" with signature [] with new annotator with signature [pos.model:edu/stanford/nlp/models/pos-tagger/german/german-hgc.tagger;]
10:36:41.401 [main] INFO  e.s.nlp.pipeline.AnnotatorPool - Replacing old annotator "ner" with signature [] with new annotator with signature [ner.applyNumericClassifiers:false;ner.useSUTime:false;ner.model:edu/stanford/nlp/models/ner/german.conll.hgc_175m_600.crf.ser.gz;]
10:36:32.598 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator regexner
```

the pipeline is *replacing* only the annotators (like `tokenize`, `pos`, `ner`) I can see in the logs like above and keeping the others (like `regexner`)?

**Comment by J38** [comment]
Yes it should only be updating the ones you are changing.

Also, make sure to see the migration guide for Stanford CoreNLP 3.9.1:

https://stanfordnlp.github.io/CoreNLP/migration.html

**Comment by ziorufus** [comment]
I'm migrating [Tint](http://tint.fbk.eu/) to CoreNLP 3.9.1 but I'm stuck on a new annotator called `IsNewlineAnnotator`. See [here](https://stackoverflow.com/questions/49252826/isnewline-new-feature-in-stanford-corenlp).

**Comment by J38** [comment]
After you run the `tokenize` annotator, there are two reasons newline tokens will be generated.  The first is if `tokenize.options="tokenizeNLs=true"` is set.  Another reason is if you are using newline related sentence splitting options.  In either of these cases the `tokenize` annotator will generate newline tokens.  That annotation is merely a boolean flag to mark the token as a newline token (to avoid relying on matching the text "*NL*".

Currently the code removes these tokens at the end of `ssplit`.  If you just tokenize, you should still see newline tokens.  But if you add `ssplit`, at the end of that annotator is a loop to remove all newline tokens.

It might make sense to modify that to check if the user selected `tokenize.options="tokenizeNLs=true"`, that may be an oversight in this change.  Please let me know if you need any other assistance with the migration!
