### ISSUE TITLE
HTTP 400 Errors on CoreNLP server

### ISSUE THREAD

**Issue by davidabarrett** [stanfordnlp/CoreNLP#634]
I've been seeing http status 400 errors when providing certain
input files to the CoreNLP server:

  https://stanfordnlp.github.io/CoreNLP/corenlp-server.html

Is this a known issue?  

Is there a way to configure the server to generate diagnostics
for the failure?

**Comment by J38** [comment]
If you run it on the command line and have the Terminal open with the Java process, what is being printed out when you submit these problematic files ?
