### ISSUE TITLE
Cannot load English models properly (v3.9.1)

### ISSUE THREAD

**Issue by borice** [stanfordnlp/CoreNLP#635]
Two issues I noticed:

1. It's not possible to use `stanford-english-corenlp-2018-02-27-models.jar` by itself (without the KBP "add-on") since by default the properties file seems to reference files from the KBP jar. This is using default configuration (no special properties set), and the annotator pipeline `tokenize,ssplit,pos,lemma,ner`
2. Even when adding both English model JAR files ("regular" and KBP) to the classpath, it seems the annotator pipeline fails to be built. Error is 

> Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Couldn't read TokensRegexNER from edu/stanford/nlp/models/kbp/regexner_caseless.tab
> Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/kbp/regexner_caseless.tab" as class path, filename or URL

Looking inside `stanford-english-kbp-corenlp-2018-02-27-models.jar` I see that indeed there is no file at `edu/stanford/nlp/models/kbp/regexner_caseless.tab`. Instead, they're all at `edu/stanford/nlp/models/kbp/english/regexner_caseless.tab`  (note the additional **english** path segment)

I tried setting the property (in Scala)
```
val props = new Properties()
props.put("regexner.mapping", "ignorecase=true,validpospattern=^(NN|JJ).*,edu/stanford/nlp/models/kbp/english/regexner_caseless.tab;edu/stanford/nlp/models/kbp/english/regexner_cased.tab")
props.put("annotators", "tokenize,ssplit,pos,lemma,ner")
props.put("threads", "8")
val nlp = new StanfordCoreNLP(props)
```
but that also didn't work (same error).

Am I missing something, or is this a bug?

Thank you.

**Comment by borice** [comment]
OK, so it looks like I was missing `stanford-corenlp-3.9.1-models.jar` from the class path. I wonder what's different between what's inside this jar file and the other two English jar files, with respect to NER configuration/models.

Anyway - false alarm. Closing.

**Comment by chronos-cosine** [comment]
Hi, I saw if not initialised, the engine sets the fine grained Ner to true.  So if you do not want to use it set this property to false:
```
val props = new Properties();
props.put("ner.applyFineGrained", "0");
```

If you want to use it remember to set the mapping property to the location where your models are located.  By default I use the models on a server location.
```
val props = new Properties()
props.put("ner.applyFineGrained", "0");
props.put("ner.fine.regexner.mapping, "~/home/.../location");
```

**Comment by Emil333** [comment]
> Hi, I saw if not initialised, the engine sets the fine grained Ner to true. So if you do not want to use it set this property to false:
> 
> ```
> val props = new Properties();
> props.put("ner.applyFineGrained", "0");
> ```
> If you want to use it remember to set the mapping property to the location where your models are located. By default I use the models on a server location.
> 
> ```
> val props = new Properties()
> props.put("ner.applyFineGrained", "0");
> props.put("ner.fine.regexner.mapping, "~/home/.../location");
> ```

This worked for me
