### ISSUE TITLE
Unknown property: |sutime.language|

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#638]
I get this INFO, that seems to be more a warning, not sure if this causes anything, but I didn't had it in CoreNLP 3.8.0, reporting then:

```
11:51:23.863 [main] INFO  e.s.nlp.sequences.SeqClassifierFlags - sutime.language=spanish
11:51:23.863 [main] INFO  e.s.nlp.sequences.SeqClassifierFlags - Unknown property: |sutime.language|
11:51:24.184 [main] INFO  e.s.nlp.sequences.SeqClassifierFlags - Unknown property: |sutime.language|
11:51:24.371 [main] INFO  e.s.n.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/spanish.ancora.distsim.s512.crf.ser.gz ... done [0.5 sec].
11:51:24.371 [main] INFO  e.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
11:51:24.372 [main] INFO  e.s.n.t.TimeExpressionExtractorImpl - Using following SUTime rules: edu/stanford/nlp/models/sutime/defs.sutime.txt,edu/stanford/nlp/models/sutime/spanish.sutime.txt
```

my configuration for spanish is the default one where is used:

```
# sutime
sutime.language = spanish
```

i.e. the default configuration for spanish [here](https://github.com/stanfordnlp/CoreNLP/blob/d8bccdd2724f06dafea03f561299833c67244688/src/edu/stanford/nlp/pipeline/StanfordCoreNLP-spanish.properties).

**Comment by J38** [comment]
The warning doesn't have any significance.  I pushed a change so in future versions it won't print out.  That is the setting for telling the system what SUTime language files to use.

**Comment by loretoparisi** [comment]
Thanks a lot!
