### ISSUE TITLE
EnglishFactored model is gone

### ISSUE THREAD

**Issue by windweller** [stanfordnlp/CoreNLP#64]
Hi! I have been using English Factored model for a long time (it's slower but seems to be more accurate than PCFG one). I have upgrade my StanfordNLP library to 3.5.1, and it seems like `edu/stanford/nlp/models/lexparser/englishFactored.ser.gz` has gone missing and the only two models there are `RNN` and `PCFG`. Can I still find it somewhere?

**Comment by AngledLuffa** [comment]
Although I don't know anything about decisions to remove the Factored
model, I can tell you the RNN is both faster and more accurate

**Comment by windweller** [comment]
If it's not being removed, can I still find it somewhere in the model.jar?

**Comment by reckart** [comment]
If you have trouble finding it in the CoreNLP package, maybe check in the Stanford Parser package.

**Comment by windweller** [comment]
I did check. I couldn't find the model .ser.gz file

**Comment by reckart** [comment]
As I suspected, the factored model is still present in the stanford-parser-3.5.1-models.jar file that comes with the Stanford Parser (http://nlp.stanford.edu/software/lex-parser.shtml).

**Comment by windweller** [comment]
yes, but would you please provide the actual location of that .ser.gz file or a link to it?

**Comment by reckart** [comment]
Download this file:

http://nlp.stanford.edu/software/stanford-parser-full-2015-01-29.zip

Extract it to a folder.

In the folder, locate the file "stanford-parser-3.5.1-models.jar" and rename it to "stanford-parser-3.5.1-models.zip".

Extract stanford-parser-3.5.1-models.zip to a folder.

Find the model in the subfolder "edu/stanford/nlp/models/lexparser"

**Comment by windweller** [comment]
Thank you!
