### ISSUE TITLE
outdated libraries. any plans to patch them?

### ISSUE THREAD

**Issue by krinkere** [stanfordnlp/CoreNLP#640]
Looking over lib folder I see very old libraries. for example

log4j-1.2.16.jar	Put CoreNLP on GitHub	5 years ago
lucene-analyzers-common-4.10.3.jar	Compile with new requirements system	2 years ago

any plans to update them to take advantage of bug fixes, security patches and new capabilities?

**Comment by manning** [comment]
Yes, we should. Of course the issues with updating things varies:
- log4j should be trivial
- lucene might take a little work
- we'd like to update ejml sometime, but that requires retraining a bunch of models whose serialized form depends on the current version....

**Comment by krinkere** [comment]
Thank you @manning
