### ISSUE TITLE
Can train based on last result ?

### ISSUE THREAD

**Issue by jackieju** [stanfordnlp/CoreNLP#642]
Hi,

We have a very big corpus and our customer may add new corpus very frequently, but everytime the train will take long time. So I have a question: Can we do incremental training or say only train new added corpus  then merge with last result ? or any other way to enhance the training performance is appreciated.

Thanks a lot !

**Comment by J38** [comment]
Hi, to the best of my knowledge we don't have any offerings that easily allow for continuing training of a model with new data.
