### ISSUE TITLE
Indicate model version & corenlp version in online demo corenlp.run

### ISSUE THREAD

**Issue by kno10** [stanfordnlp/CoreNLP#643]
Thank you very much for http://corenlp.run/ - I frequently use it to check how Stanford processes some particular sentence during development and debugging.

However, the web site does not indicate which CoreNLP version, and even more important, which model it uses. For example, I cannot tell if it is already updated to 3.9.x.

Please include the version number and model in the web site output. Thank you.

**Comment by gangeli** [comment]
In general, corenlp.run tracks some semblance of the HEAD of the repo, rather than any particular version. Currently, it's updated to something around 3.9.0.

**Comment by kno10** [comment]
The _model_ versions are more important for me. I noticed because the 3.9.1 models for German use "PERSON", but the corenlp.run website seems to use "I-PER".

**Comment by J38** [comment]
Hi I added the date of the last time the code and models were updated.  I updated them just now to use the latest code and the latest models.  You should see the `ner` model now using `PERSON` for instance in German....
