### ISSUE TITLE
Custom Pipeline

### ISSUE THREAD

**Issue by bgshin** [stanfordnlp/CoreNLP#647]
Hello,

I really like CoreNLP, thanks for the good tool.

I'm wondering if customizing the pipeline is possible.
For example, I want to call only the CoreNLP's POS tagger component with a tokenized string list, 
or I want to call only the dependency parser component using my own POS tags.

FYI, Spacy supports a customized pipeline as described in [here](https://spacy.io/usage/processing-pipelines).

Hope I could find a clue of this feature.
Thank you very much!

**Comment by manning** [comment]
Sure, absolutely you can customize the pipeline!

In essence, CoreNLP has exactly the same sort of pipeline architecture that SpaCy has. You could say that they copied it off of us. 😉 Though, really, it's a pretty basic, universal sort of pipeline architecture that is widely used in NLP systems. The only difference is that theirs is better documented than ours. 😛 

You will need to set up your own `Annotation` object, and if using the `StanfordCoreNLP` `AnnotationPipeline`, make sure to give it the property `enforceRequirements = false`.

I've started a new documentation page, just for you: https://stanfordnlp.github.io/CoreNLP/pipelines.html
