### ISSUE TITLE
Question: Can the CoreNLP Classifier do multi-label classification?

### ISSUE THREAD

**Issue by allisterb** [stanfordnlp/CoreNLP#650]
I've been reading the classifier docs and source code trying to figure out how to do it from the command line but I've had no luck. I see there is a KNNClassifierFactory class but I don't know how to call it or how to specify what the columns for classes are. Is there any way to do multi-label classification currently?

**Comment by bhi5hmaraj** [comment]
If you have only a few classes you could create a classifier for each one

**Comment by J38** [comment]
The `main()` method of `edu.stanford.nlp.classify.KNNClassifier` shows a thorough example of usage.  You might also want to look at `edu.stanford.nlp.classify.OneVsAllClassifier`.
