### ISSUE TITLE
quote.attribution annotation protobuf serialization (CoreNLPServer). 

### ISSUE THREAD

**Issue by sina-al** [stanfordnlp/CoreNLP#653]
Currently, I can only get quote attribution annotations through the CoreNLPServer in json output format.
Are there any plans to add protobuf support? 

Thanks

**Comment by J38** [comment]
The current code should be doing that.  For instance this test: 

`edu.stanford.nlp.pipeline.ProtobufSerializationSanityITest` runs the quote attribution code as part of the process when it serializes the annotation.  Note that `quote` now runs the attribution process as well, so you just need the `quote` annotator.
