### ISSUE TITLE
The stanford-english-corenlp-2018-02-27-models.jar file from Stanford domain has invalid property file

### ISSUE THREAD

**Issue by nadavb** [stanfordnlp/CoreNLP#655]
It has  a file called: StanfordCoreNLP.properties
Which contains keys with parser.model instead of parse.model

**Comment by J38** [comment]
Hi, sorry it does appear that the commented out properties in this file are out of date.  This file isn't used for anything other than setting the default annotators list.  Anything starting with a "#" is commented out, so has no effect.  But I will work to improve this file for future releases!

**Comment by nadavb** [comment]
Thanks.
It is important, since people (like myself) uncomment the "#" to config things...

In addition, I can't replicate the results from the demo page: http://nlp.stanford.edu:8080/parser/index.jsp on my localhost. I get differences between running the non server StanfordCoreNLP, and the server StanfordCoreNLPServer + sending commands using curl. When parsing the text "The boy drive well" (mistake on purpose), in the non server I get "drive" to be VBP and with the server I get NN (noun). Don't know why.

In addition, when I send a curl request:

curl --data 'The boy drive well.' 'http://localhost:9000/?properties={%22annotators%22%3A%22tokenize%2Cssplit%2Cparse%22%2C%22outputFormat%22%3A%22json%22}' -o -

The server prints: API call w/annotators tokenize,ssplit,pos,parse - but I didn't specify a POS annotator...

I would appreciate a short example how to run the server and curl commands to replicate the demo page.

**Comment by nadavb** [comment]
I think I found the thing. If I add` enforceRequirements = false `in the properties file, the CoreNLP server behave like the CoreNLP, and doesn't add the pos. Maybe this should be in the supplied properties file as well.

**Comment by J38** [comment]
The demo page is using the parser to generate part-of-speech tags I believe, so that is the difference.

The best way to start a server with certain properties is to use the `-serverProperties` option and supply a properties file.  In that file you could specify `annotators = tokenize,ssplit,parse` and you will get the parser generated tags.

**Comment by nadavb** [comment]
You need to also put the `enforceRequirements = false` in the properties file, otherwise the server automatically adds the `pos` annotator before the parse, and you get a different results.

**Comment by J38** [comment]
That's if you use `parse.model = edu/stanford/nlp/models/srparser/englishSR.ser.gz` which requires tags.  `parse.model = edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz` does not.  The server uses the former by default for speed purposes.

**Comment by J38** [comment]
I have updated this file so in future editions it will not have out of date info.
