### ISSUE TITLE
RegexNERAnnotator | ValidPosPattern issue

### ISSUE THREAD

**Issue by alsora** [stanfordnlp/CoreNLP#658]
Hi,
I am using the corenlp pipeline for entities recognition.

Could you explain me a little bit what is the proper use of the ValidPosPattern option?

I noticed that using the default parameters ValidPosPattern is set to null.
By the way the mapping files are loaded in the following way:

`"ignorecase=true,validpospattern=^(NN|JJ).*, edu/stanford/nlp/models/kbp/regexner_caseless.tab;"
 
   "edu/stanford/nlp/models/kbp/regexner_cased.tab;"`

At first glance I thought that the pattern "^(NN|JJ).*" would have applied only for the entities contained in the first file.
However, when the POS tags are checked [here](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/TokensRegexNERAnnotator.java#L419), it seems like the pattern is applied to all the entries without any distinction.

Thank you for your help

**Comment by J38** [comment]
It should work as you would expect, each rules file has it's own set of properties.  Commas separate the different properties (with the file path of the rules file being the last entry).  Semicolons separate different rules files.  There is a caveat though.

There are two rule types.  One rule type is a list of regexes that match each token for the entry.  The other rule type is a full TokensRegex rule.  

**type one example:** vice president 
**type two example:** ( /University/ /of/ [ {ner:LOCATION} ] )

Full details here: https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/pipeline/TokensRegexNERAnnotator.html

The caveat is that the valid pos pattern setting is only attached to the pattern for a rule if it is the first type.  Note that with TokensRegex rules, you can add requirements about the POS tags in your TokensRegex rule.

**for instance:** ( [ {pos:NN} ] /of/ [ {ner:LOCATION} ] )

**Comment by alsora** [comment]
Thank you a lot for the information.

By the way consider the case of annotating the following sentence:

>  This is Miami. This is NY.

The entity "Miami" is contained in the "edu/stanford/nlp/models/kbp/regexner_caseless.tab" file while the entity "NY" is contained in the "edu/stanford/nlp/models/kbp/regexner_cased.tab" file.
By default a validPosPattern is specified only for the first file, while it's null for the second.

The "processPerFileOptions" method correctly fills the "validPosPatternList" object.
However, the method [annotateMatched](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/TokensRegexNERAnnotator.java#L375) performs a check on the POS in order to decide if a token NER can be overwritten or not.

Considering the default parameters the [checkPosTags](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/TokensRegexNERAnnotator.java#L419) method works in the following way:

- validPosPattern is set to null for the whole annotator but "atLeastOneValidPosPattern(validPosPatternList)" returns true
- posMatchType by default is MATCH_AT_LEAST_ONE_TOKEN
- the tokens have a POS assigned, but validPosPattern is set to null
- the program executes the for loop in line [433](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/TokensRegexNERAnnotator.java#L433). This loop checks wether the current POS tag matches ANY of the Pattern inside validPosPatternList

This happens for both the entities that I want to overwrite  in my example (Miami and NY).
By the way it should only apply to Miami, since, for NY, which is contained in the second file, validPosPattern was set to null and so I would like to overwrite it regardless of its POS.

Moreover, assume for example that I have 2 different validPosPattern specified for the files:

`"validpospattern=^(NN).*, edu/stanford/nlp/models/kbp/regexner_caseless.tab;" "validpospattern=^(JJ).*, edu/stanford/nlp/models/kbp/regexner_cased.tab;"`

An entity contained in the second file would be accepted for the overwrite even if its POS is NNP, because "checkPosTag" will iterate over all patterns

Sorry for the very long reply, I hope that it's clear.
