### ISSUE TITLE
How to know Tree library's end of sentence

### ISSUE THREAD

**Issue by windweller** [stanfordnlp/CoreNLP#66]
I'm using the Tree class, and doing DFS traversal to collect different parts of the sentence. Since it is a collection process, I need to be able to add the last part and one of the common condition would be "If you are at the end of a sentence, add the collected parts to the collection". And normally, `treeNode == null` would suffice, but Stanford tree does not return null value. So how do I know if I have already reached the end of sentence, in a DFS??

**Comment by reckart** [comment]
Please consider posting questions to the users mailing list. This is an issue tracker, not a forum ;)

**Comment by windweller** [comment]
Sorry! I didn't know such mailing list exist.

**Comment by reckart** [comment]
No offense meant :) I just wanted to point that out and opened issue #67 now about adding a link to the main README file.

http://nlp.stanford.edu/software/corenlp.shtml#Mail
