### ISSUE TITLE
CTB9.0 to UD

### ISSUE THREAD

**Issue by fouzhe** [stanfordnlp/CoreNLP#661]
Is there anyway to tansfer ctb9.0 to Universal Dependencies?

**Comment by J38** [comment]
I think this should be possible.  You can read in the CTB 9.0 trees with a tree reader derived from: `edu.stanford.nlp.trees.international.pennchinese.CTBTreeReaderFactory`.  Then you can use `edu.stanford.nlp.trees.international.pennchinese.ChineseGrammaticalStructureFactory` and this line of code to produce a `SemanticGraph`:

`SemanticGraph enhancedPlusPlusDeps = SemanticGraphFactory.generateEnhancedPlusPlusDependencies(gsf.newGrammaticalStructure(tree));`
If I have a chance I'll try to write a more detailed explantation.
