### ISSUE TITLE
Can CoreNLP Server receive already tokenized inputs?

### ISSUE THREAD

**Issue by sevenights** [stanfordnlp/CoreNLP#668]
Because I want to use my own trained tokenizer, I want to know whether there is a way to inputs tokenized sentence to the CoreNLP Server Annotators, such as NER, POS, dependency parser...

I have searched the issues and googled it, but I can't get a solution.

Thank you

**Comment by J38** [comment]
If you start the server with a properties file, and put the property `tokenize.whitespace = true` it will tokenize on white space exclusively.  So you can submit your string tokenized the way you want with whitespace splitting the tokens.
