### ISSUE TITLE
Default NER models and code keep state, resulting in ordering effects

### ISSUE THREAD

**Issue by kwalcock** [stanfordnlp/CoreNLP#669]
We run NER across a directory of files and observe that the results are different across runs.  This happens most often when files are processed in parallel, but it can happen in serial cases as well if the data is reordered.

According to english.all.3class.distsim.prop and two other files packaged with the models, wordShape=chris2useLC or dan2useLC.  This means they use algorithms for word shaping that consult knownLCWords, a record of known lowercase words.  The problem is that the record is updated as text is processed by code in ObjectBankWrapper, namely knownLCWords.add(word);, and there doesn't appear to be a way to reset it other than to reconstruct the processor.

What happens is that we see a capitalized word like Belt in a sentence.  It is not in the initial knownLCWords and gets a shape something like Xxxx which for our sentence eventually translates to a category O.  Some later text then has belt, which gets added to knownLCWords.  If the sentence with Belt is run again (or it is run for the first time after seeing belt), the shape is something like Xxxxk which eventually results in LOCATION.  So, if our files or sentences come in "Belt belt" order, we get one answer and if they are "belt Belt" we get a different answer for the same sentence.

I have not found code that will allow me to reset knownLCWords between runs, despite there being various reinit() methods.  knownLCWords is designed to be thread-safe (see below), so reserving it for one text and resetting it for the next is not desirable anyway.  flags.useShapeStrings might be useful, but I think that's set in the serialized models.  It seems like the best way to achieve repeatable results is to change the wordShape settings to chris2 and dan2 without the useLC.  This may imply a rebuild of the models.

This issue is also described at https://github.com/clulab/eidos/issues/261.

Although it may be a feature to have the WordShapeClassifier learn new lowercase words, for our application it's closer to a bug.  I hope someone can comment on any plans related to the issue.  Thanks.

  /** Different threads can add or query knownLCWords at the same time,
   *  so we need a concurrent data structure.  Created in reinit().
   */
  protected MaxSizeConcurrentHashSet<String> knownLCWords; // = null;

**Comment by J38** [comment]
Have you tried setting `maxAdditionalKnownLCWords` to 0.  Looking over the code, this appears to me that it will set the size of the hash set to 0 when you set it up and effectively deactivate this.

**Comment by J38** [comment]
So I investigated this more and I think if you just add `-maxAdditionalKnownLCWords 0` when you run it it will cap the size of that hash at it's default value so that should get rid of the ordering effect.

**Comment by J38** [comment]
Just to clarify, it won't allow new words to be added to that hash so you won't have this ordering issue you are speaking of.

**Comment by kwalcock** [comment]
It looks very much like you are correct.  How the variable is ever anything other than 0 with the code

  public int maxAdditionalKnownLCWords = 0; // was 10_000;

is still a mystery to me, but adding

    props.put("maxAdditionalKnownLCWords", "0");

does the trick.  I see only now that others have noted similar confusion.  Thanks for taking the time to set me straight.

**Comment by J38** [comment]
Just a note, it appears to me that each of the 3 CRF classifiers loaded by default have different settings for `maxAdditionalKnownLCWords`.  So when these serialized models are loaded I think perhaps a value for that is stored with them and then being used to set the size limit for the known lc words set.  This value is overridden when you set it 0.  I am not sure if the default should be 0 or what it was when these models were trained.  I guess for now I am not going to change it, but maybe I should make it default to 0.
