### ISSUE TITLE
Add prominent link to mailing list in README.md

### ISSUE THREAD

**Issue by reckart** [stanfordnlp/CoreNLP#67]
It might be good to add a prominent link to the users mailing list to the README.md file to avoid questions being posted to the issue tracker.

**Comment by windweller** [comment]
Also, the mailing list right now needs registration. Moving to Google Group mailing list might be a nicer strategy. I instead posted my question on StackOverflow.

**Comment by gangeli** [comment]
(We also browse the "stanford-nlp" tag on stackoverflow: http://stackoverflow.com/questions/tagged/stanford-nlp)
