### ISSUE TITLE
German parsing without dependency relations

### ISSUE THREAD

**Issue by Mileyjun** [stanfordnlp/CoreNLP#670]
When I use stanford parser to analyse German, the only two labeled dependency relations are root and punct, so how can i get further analysis of dependency relations?

**Comment by J38** [comment]
This command will run the German dependency parser model.  You should see all the expected dependency relations.

`java -Xmx15g edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-german.properties -annotators tokenize,ssplit,pos,depparse -file german-sentence.txt -outputFormat text`
