### ISSUE TITLE
Interrogative "may"

### ISSUE THREAD

**Issue by jeffrschneider** [stanfordnlp/CoreNLP#675]
Sample:
"May Susan go to lunch?"

When "may" is used as an interrogative, it is consistently tagged incorrectly from a part of speech perspective.

**Comment by J38** [comment]
Thank you for raising this issue.  I think in the future we are aiming to release a new combination of part-of-speech tagging and dependency parsing in Python, so hopefully these more modern deep learning based systems will not make as many errors like this.

**Comment by J38** [comment]
Please see https://github.com/stanfordnlp/CoreNLP/issues/680

**Comment by manning** [comment]
I added a couple of examples of "May" questions and imperatives to the training data. They may help, or "May" as a month may just so dominate numerically that there'll be no difference. We'll see....
