### ISSUE TITLE
coref without pronoun

### ISSUE THREAD

**Issue by liuzqt** [stanfordnlp/CoreNLP#676]
I want to use coref annotator to find out entities in a cluster. But it seems that the coref annotator will skip those entity which isn't referred by a pronoun.

For example, 
sentence1 "David is a student and he study in Pittsburgh", 
the annotator will give coref chain of ["David", 'he"]

sentence2 "David is a student"
the annotator will give no coref chain.

I suppose this should be a necessary features, and what might be the best way to do this?

(Actually my task is to find out all entities, and count their frequency in a document. Therefore I need to group entities name into some cluster, and resolve the pronoun as well)

**Comment by J38** [comment]
Make sure you set `coref.removeSingletonClusters = false` ...that is why it is not creating a chain in your second example.
