### ISSUE TITLE
Can anyone suggest the austen.prop documentation page

### ISSUE THREAD

**Issue by anshumanvarshney** [stanfordnlp/CoreNLP#679]
Hi! I am using NER for finding out Education Entities(College, Score, Year, Department, Degree), with default Austen.prop property I am not getting good accuracy. So I want to know about property in details

**Comment by J38** [comment]
Please see this link: 

https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/ie/NERFeatureFactory.html
