### ISSUE TITLE
Problem with splitHyphenated

### ISSUE THREAD

**Issue by catcduet** [stanfordnlp/CoreNLP#681]
In the document, I found the splitHyphenated for tokenizer options with the description: Whether or not to tokenize segments of hyphenated words separately ("school" "-" "aged", "frog" "-" "lipped")...Default is currently false, which maintains old treebank tokenizer behavior. (This default will likely change in a future release.)

I've tried setting this options to True but I completly get the wrong tree. For example, with the noun phrase "Chemical-induced disease", I expect the disease being the main Noun.
Something like this
![image](https://user-images.githubusercontent.com/10630842/39092166-4b8767f0-4631-11e8-9edb-91024e1e9297.png)
Actually, I got a tree with the Chemical is subject and disease is object of a sentence. The whole meaning was changed.

Is there any way to solve this problem?
Thanks!

**Comment by J38** [comment]
Unfortunately the statistical based parser will make errors.  I do see examples of hyphenated nouns such as this in the training data, and they are tokenized in the manner you want, but unfortunately it appears the parser is continuing to make mistakes.  We are actively working on a new parser and will hopefully release this new parser sometime this year.
