### ISSUE TITLE
CoreNLP server cannot handle french unicode characters

### ISSUE THREAD

**Issue by zolikacsepel** [stanfordnlp/CoreNLP#682]
CoreNLP Server won't recognise unicode characters.
I start the server like this:
`java -mx2g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties StanfordCoreNLP-french.properties -port 9000 -timeout 15000`

Then I send a request to it from python like this:

`params = (('properties', '{"annotators":"tokenize,ssplit,pos,lemma,depparse","outputFormat":"conllu"}'),)`

`data = "Il a été créé quand?"`

`response = requests.post('http://localhost:9000/', params=params, data=data)`

`print(response.text)`

The output is then:

1	Il	il	_	PRON	_	4	nsubj	_	_
2	a	a	_	AUX	_	4	aux	_	_
3	t	t	_	X	_	4	compound	_	_
4	cr	cr	_	X	_	0	root	_	_
5	quand	quand	_	ADV	_	4	advmod	_	_
6	?	?	_	PUNCT	_	4	punct	_	_

So the 'é's are missing. How can I fix it? It should be able to do it, because if I just run stanford CoreNLP  (from python) on a text file, then it works correctly. I use for this:

`["java", "-classpath", stanford_main_path, "-Xmx2g", "edu.stanford.nlp.pipeline.StanfordCoreNLP", "-ssplit.eolonly", "-annotators", "tokenize,ssplit,pos,lemma,depparse", "-file", input_path + input_name, "-props", "StanfordCoreNLP-french.properties", "-outputDirectory", output_directory, "-outputFormat", "conllu"]`

**Comment by J38** [comment]
See this Python client:

https://github.com/stanfordnlp/python-stanford-corenlp

Some sample code:

```
import corenlp
client = corenlp.CoreNLPClient(start_server=False)
ann = client.annotate(u"Il a été créé quand?")
sentence = ann.sentence[0]
print(sentence.token[2].word)
```

Should print out `été`

One warning: I've found a bit of a bug with French and German...you should add `ner.applyFineGrained = false` to your properties, or it will load the English `regexner` mapping files and possibly erroneously tag some of your entities!

**Comment by gangeli** [comment]
Perhaps check your `content-type` encoding on the request, and make sure it's (1) sending the request in Unicode, and (2) requesting the response to be in unicode?

See, e.g, the Javascript request the demo site makes against the server: https://github.com/stanfordnlp/CoreNLP/blob/db4a03c5f6b84cbbf2609e8b3d0e0e0e8d460a03/src/edu/stanford/nlp/pipeline/demo/corenlp-brat.js#L994

**Comment by zolikacsepel** [comment]
Szevasz Gábor,

thanks for the hint, I found the solution, im in python3 and I assumed that utf-8 is the default.

If I change the line in the above code to:

`data = u"l'été était bref".encode("utf-8")`

, then it works fine.
Cheers
