### ISSUE TITLE
Sentiment Tree as JSON Object

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#684]
Recently in the **Sentiment** module output a _SentimentTree_ output has been added:

```javascript
{
                "index": 4,
                "sentimentValue": "2",
                "sentiment": "Neutral",
                "sentimentDistribution": [
                  0.02319716964425,
                  0.24382036048496,
                  0.67127763735208,
                  0.05488071716532,
                  0.0068241153534
                ],
                "sentimentTree": "(ROOT|sentiment=2|prob=0.671 (NP|sentiment=2|prob=0.998 this)\n  (@S|sentiment=2|prob=0.743 (ADVP|sentiment=2|prob=0.997 here)\n    (VP|sentiment=2|prob=0.749 (VBZ|sentiment=2|prob=0.994 's)\n      (SBAR|sentiment=2|prob=0.583 (WHNP|sentiment=2|prob=0.994 what)\n        (S|sentiment=2|prob=0.569 (NP|sentiment=2|prob=0.995 you)\n          (VP|sentiment=2|prob=0.648 (VBP|sentiment=2|prob=0.992 call)\n            (NP|sentiment=2|prob=0.432 (DT|sentiment=2|prob=0.990 a) (JJ|sentiment=1|prob=0.336 flip))))))))",
                "tokens":[]
```

This output has been widely discussed here https://github.com/stanfordnlp/CoreNLP/issues/465 by @J38 and others. The output is it ok to be used _within_ Java CoreNLP through a `TreeFactory` module impl like the `LabeledScoredTreeFactory`, by the way it cannot be used by a visual representation like the D3 dataviz in the demo:

<img width="963" alt="schermata 2018-04-24 alle 12 05 57" src="https://user-images.githubusercontent.com/163333/39180701-e15f4c0c-47b7-11e8-8e24-3a1edce7e7b2.png">

This data visualization is build using the good D3.js and a JSON structure of the tree:

```javascript
drawTrees( d3.select( "div.trees" ), data.trees, params );
```

where the `data.trees` have a struct like

```javascript
{
	"version": 2,
	"build": "2018-04-24 02:35:39.775761",
	"trees": [{
		"child0": {
			"child0": {
				"index": 3,
				"leaf": true,
				"rating": 13.0,
				"text": "This",
				"scoreDistr": [0.0001, 0.0007, 0.9985, 0.0006, 0.0001],
				"tokens": 1,
				"depth": 1,
				"numChildren": 0,
				"pixels": 26
			},
			"index": 2,
			"leaf": false,
			"rating": 13.0,
			"text": "This movie",
			"scoreDistr": [0.0002, 0.0032, 0.9908, 0.0056, 0.0002],
			"tokens": 3,
			"depth": 2,
			"numChildren": 2,
			"pixels": 63
		},
		"index": 1,
		"leaf": false,
		"rating": 8.0,
		"text": "This movie does n't care about cleverness , wit or any other kind of intelligent humor .",
		"scoreDistr": [0.1685, 0.7187, 0.0903, 0.0157, 0.0068],
		"tokens": 33,
		"depth": 10,
		"numChildren": 2,
		"pixels": 493
	}]
}
```

(this is a simplified version with just one root node and one child - see the whole version [here](https://pastebin.com/yvvmikLZ)

How to translate the current string tree representation in the `sentimentTree` to JSON struct represented in the Sentiment live demo?

**Comment by J38** [comment]
Hi a lot of this is done with the sentiment demo page code which was a class project from a few years ago, and has both C and Python code handling the creation of this json.  The authors have moved on.  It is highly unlikely we will ever have the time to integrate that code into Stanford CoreNLP.

I will ask if it is okay to send you some of that code if you would like to sift through it and figure it out.  I personally think it might be faster to write your own code that processes the PTB tree representation and maps it to that format, but it might help to look at the Python code that is doing that for the demo page.

Alternatively, you could also try working with our Python client for the server.  It has a somewhat similar structure.  If you ask for sentiment parses from the server, you'll get a tree structure back that is kind of similar, though it is lacking a lot of the detailed info.  But if you just want to visualize the trees, I think it should be sufficient to just have sentiment scores for each subtree, and the Python code should provide that.

Package info here: 

https://github.com/stanfordnlp/python-stanford-corenlp/blob/master/doc/CoreNLP.proto

Some sample usage code:

```
import corenlp
client = corenlp.CoreNLPClient(start_server=False, annotators=["tokenize", "ssplit", "pos", "lemma", "ner", "parse", "sentiment"])
ann = client.annotate(u"The pizza was great!")
print(ann.sentence[0].annotatedParseTree)
```

Each tree will have a sentiment score from ["STRONG_NEGATIVE", "WEAK_NEGATIVE", "NEUTRAL", "WEAK_POSITIVE", "STRONG_POSITIVE"]

You can iterate through the tree like structure like this:

```
sentimentTree = ann.sentence[0].annotatedParseTree
for child in sentimentTree.child:
    print(child)
```

**Comment by loretoparisi** [comment]
@J38 thanks lot. I was aware of the `annotatedParseTree` structure, my aim was to create the json from the annotated string output, by the way I understand that is clearly difficult to put the piece together if this code is out-of-date. If you can share it it's ok we will try to refactor it in some way in our pipeline (CoreNLP Java), otherwise, we will wait a new model for the sentiment part, that at this point seems to be the most interesting option, but also the more reasonable one, considering the last findings here, if you have any news about it, we would be glad to try/test it thanks.

**Comment by MartinoMensio** [comment]
If anyone is still interested in parsing the sentimentTree attribute, I wrote a parser here https://github.com/MartinoMensio/corenlp-sentiment-tree-parser together with some d3.js code to display the tree.
