### ISSUE TITLE
Sentiment Treebank Annotation Tool

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#685]
The live demo has a annotation tool of the Sentiment Tree. I have tried to annotate from this nifty UI that let to annotate the sentiment classes by each tree node:

<img width="982" alt="schermata 2018-04-24 alle 12 26 50" src="https://user-images.githubusercontent.com/163333/39181721-d2f0a352-47ba-11e8-85f8-0eb6eb27817a.png">

Is this tool still working i.e. the submitted annotation are used to re-train the model?
Also, currently in the CoreNLP pipeline demo there is a live demo, but the RNTN demo plus annotator it is missing. Why not provide this demo as well in the CoreNLP demo web app? This would help to improve the annotator as well as the annotated dataset for the Treebank Sentiment.

**Comment by J38** [comment]
Hi at this time I don't think we're doing anything with annotation submissions from the demo page.  We definitely are not training a new model with the new data being collected.

When I go to `corenlp.run` I am able to get a demo of sentiment analysis on a sentence, (though not a representation of the full sentiment tree).  Unfortunately I think we don't have the bandwidth at this time to substantially modify the pipeline demo page to include this.

Recently we've been discussing contributions we'd like to make to the Python NLP community (in concert with other offerings such as AllenNLP and spaCy).  One thing I suggested was putting more work into an open source sentiment annotator, paying particular attention to having domain specific sentiment models (product reviews, newswire, etc...).  One of the issues is the sentiment model we release is based on movie reviews, and thus probably won't perform that well on say newswire text.  Ultimately if you want to get good results from the sentiment code we've released, you're going to have to tag data specific to your use case and then retrain a new model.  I'll keep you posted as we have further discussions about releasing new sentiment stuff.

**Comment by loretoparisi** [comment]
@J38 thanks a lot for the details. In fact I'm using this model for sentiment analysis of song lyrics by line, phrase or paragraphs and we can see very different (and sometimes opposite) results. Despite of this, other tools (more recent architecture based on LSTM and online apis like Google Cloud) are based anyways on the same datasets (IMDB Movie Reviews, etc.) so the pre-trained models perform ok only for these kind of text/sentences (short text / review writing style / etc.). It's clear that here more than the model itself, it is the sentiment annotated dataset that matters, and there is no generalist NN to handle a  general sentiment (that was proven by https://github.com/openai/generating-reviews-discovering-sentiment) model for all kind of domains. The idea was training from scratch the sentiment annotator but it's not clear to me how to build from a annotated sentiment dataset of sentences the tree, i.e. the contents of the files `dev, test and train` that are provided in this annotatore page, that's why I though that having the whole stuff it would have helped to understand how this pipeline works for training with new data.
Thanks again, it would be glad to have more info about the status of the sentiment pipeline.

**Comment by loretoparisi** [comment]
I'm not sure but this could be the one
https://github.com/HaebinShin/stanford-sentiment-dataset

**Comment by AngledLuffa** [comment]
Do you know if that is different in any way from the original treebank?

**Comment by loretoparisi** [comment]
@AngledLuffa Nope, more info here https://www.aclweb.org/anthology/D14-1181/
