### ISSUE TITLE
[sutime] no value extracted for input with token 'first'

### ISSUE THREAD

**Issue by lithces** [stanfordnlp/CoreNLP#686]
I gave a try to sutime via online demo
[http://nlp.stanford.edu:8080/sutime/process](http://nlp.stanford.edu:8080/sutime/process)

seems that the demo has problem with input containing token '**first**', 

- output for 'first week in jan':

| text        | value           | timex tag  |
| ------------- |:-------------:| -----:|
| first week in jan|  |\<TIMEX3 alt_value="XXXX-01 INTERSECT P1W-#1" anchorTimeID="t2" temporalFunction="true" tid="t1" type="DATE" valueFromFunction="tf0"\>first week in jan\</TIMEX3\>|

replacing '**first**' with  '**second**' leads to correct result,

- output for 'second week in jan':

| text        | value           | timex tag  |
| ------------- |:-------------:| -----:|
| second week in jan| 2018-W02 | \<TIMEX3 tid="t1" type="DATE" value="2018-W02"\>second week in jan\</TIMEX3\> |

is there any way to fix this?

**Comment by J38** [comment]
This just appears to be an issue with out of date demos.  At some point I can try to update these.  This example seems to work fine using the latest code.  Please see `http://corenlp.run` for a demo with up to date code.  You will see your example work on this demo page.

**Comment by lithces** [comment]
Sorry to reopen the issue.

I checked the  [new demo url](http://corenlp.run) seems that the 'Named Entity Recognition' result is exactly the same as the out of date demos. 
- 'first week of jan' gives 'XXXX-01 INTERSECT P1W-#1'
- 'second week of jan' gives '2018-W02'

I am quite new to TimeX and the output format like '2018-W02' is appreciated. If it is difficult to fix, is there any api which could convert ‘XXXX-01 INTERSECT P1W-#1’ to '2018-W01'
