### ISSUE TITLE
About parsing adv. to its original word

### ISSUE THREAD

**Issue by tecRicky** [stanfordnlp/CoreNLP#688]
What if we want to parse words like "sadly", "desperately" or "deleting" into their original verbs/nouns/adj word? Like "sadly" -> "sad", "deleting" -> "delete", "desperately" -> "desperate"..
Concurrently adv words were marked as RB or RBR after the PoS and lemma;
What should we do? ISorry maybe its my carelessness, but I can not find the option to solve this question;

**Comment by J38** [comment]
I don't think the lemma annotator can produce that result.  

`Morphology computes the base form of English words, by removing just inflections (not derivational morphology).  That is, it only does noun plurals, pronoun case, and verb endings, and not things like comparative adjectives or derived nominals.`

It would be pretty straight forward to just check each of the tokens, see if they are adverbs or not, and then consult a mapping (e.g. see that "sadly" is marked as an adverb, then map it to "sad" from a list you provide).
