### ISSUE TITLE
ArrayIndexOutOfBoundsException in SpanishVerbStripper

### ISSUE THREAD

**Issue by emmeljay** [stanfordnlp/CoreNLP#69]
This line is still reached if words.length < 3
https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/international/spanish/SpanishVerbStripper.java#L86

**Comment by hans** [comment]
Thanks for reporting. Are you using a custom dictionary with `SpanishVerbStripper`? Just curious — the dictionary we ship shouldn't trigger this bug if everything is formatted correctly.
