### ISSUE TITLE
Meaning of '?' in annotator dependencies

### ISSUE THREAD

**Issue by ladiesman6969** [stanfordnlp/CoreNLP#696]
What is the meaning of '?' beside `regexner` and `sentiment` in annotator dependency list

![screenshot from 2018-05-06 10-51-53](https://user-images.githubusercontent.com/25760501/39674579-f0804c3c-511b-11e8-86ed-32ef50a6c01a.png)

Taken from the following website : 
https://stanfordnlp.github.io/CoreNLP/dependencies.html

**Comment by J38** [comment]
This has been fixed.
