### ISSUE TITLE
How to get train data 

### ISSUE THREAD

**Issue by francescoyang** [stanfordnlp/CoreNLP#697]
Like  /u/nlp/data/chinese-dictionaries/plain/ne_wikipedia-utf8.txt
where I can get nlp data

**Comment by J38** [comment]
Could you list the full set of files you'd like.  I am not sure about what we can give out and what we can't.  ne_wikipedia-utf8.txt is a fairly old file, I'm not sure if we can give it out or not but I'll ask around.  If you let me know what else you're into I can ask about that as well.

**Comment by luosmart** [comment]
HI @J38 , I am very interesting about NER in Chinese and I would like to retrain some model.May I get the data about Chinese NER model, which locate 
```
trainFileList = \ 
/u/nlp/data/chinese/ner/extra-chinese-ner-6class.train,\
/u/nlp/data/chinese/ner/ace05.6class.train,\
/u/nlp/data/chinese/ner/ace04.nwire.5class,\
/u/nlp/data/chinese/ner/ace04.treebank.5class,\
/u/nlp/data/chinese/ner/edl15.df.train.5class,\
/u/nlp/data/chinese/ner/edl15.nw.train.5class,\
/u/nlp/data/chinese/ner/ere14.4class,\
/u/nlp/data/chinese/ner/ere14.df.4class,\
/u/nlp/data/chinese/ner/ere15.5class,\
/u/nlp/data/chinese/ner/ere15.para.5class,\
/u/nlp/data/chinese/ner/ere15.r2.5class
```
Thank you a lot.

**Comment by manning** [comment]
All but the first of these come from data from the Linguistic Data Consortium, which we are not at liberty to redistribute. And `extra-chinese-ner-6class.train` is only 80 lines (words) and so not very useful on its own….
