### ISSUE TITLE
error: Program type already present

### ISSUE THREAD

**Issue by rubyakerman** [stanfordnlp/CoreNLP#699]
i tried to use the library, and i got this error:

"Program type already present: edu.stanford.nlp.fsm.FastExactAutomatonMinimizer
Message{kind=ERROR, text=Program type already present: edu.stanford.nlp.fsm.FastExactAutomatonMinimizer, sources=[Unknown source file], tool name=Optional.of(D8)}"

![dd](https://user-images.githubusercontent.com/815634/39832060-e1c8f896-53ce-11e8-9528-28e7b0dacc9e.jpg)

please help me, i spent the whole day trying of making things work 🥇 but it didnt worked out :)

this is the code from android studio:

package il.co.cafa.nlp;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import java.util.List;
import java.util.Properties;

import edu.stanford.nlp.ling.CoreAnnotations;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.pipeline.Annotation;
import edu.stanford.nlp.pipeline.StanfordCoreNLP;
import edu.stanford.nlp.util.CoreMap;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // creates a StanfordCoreNLP object, with POS tagging, lemmatization, NER, parsing, and coreference resolution
        Properties props = new Properties();
        props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

        // read some text in the text variable
        String text = "What is the Weather in Bangalore right now?";

        // create an empty Annotation just with the given text
        Annotation document = new Annotation(text);

        // run all Annotators on this text
        pipeline.annotate(document);

        List<CoreMap> sentences = document.get(CoreAnnotations.SentencesAnnotation.class);

        for (CoreMap sentence : sentences) {
            // traversing the words in the current sentence
            // a CoreLabel is a CoreMap with additional token-specific methods
            for (CoreLabel token : sentence.get(CoreAnnotations.TokensAnnotation.class)) {
                // this is the text of the token
                String word = token.get(CoreAnnotations.TextAnnotation.class);
                // this is the POS tag of the token
                String pos = token.get(CoreAnnotations.PartOfSpeechAnnotation.class);
                // this is the NER label of the token
                String ne = token.get(CoreAnnotations.NamedEntityTagAnnotation.class);

                System.out.println(String.format("Print: word: [%s] pos: [%s] ne: [%s]", word, pos, ne));
            }
        }

    }
}

this is my gradle:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "il.co.cafa.nlp"
        minSdkVersion 26
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'edu.stanford.nlp:stanford-parser:3.9.1'
    implementation 'edu.stanford.nlp:stanford-corenlp:3.9.1'
    implementation files('C:/Users/user/AndroidStudioProjects/NLP2/lib/slf4j-api.jar')
}

**Comment by aamirmirza2999** [comment]
i also found same error when i run app after build gradel 
error :Program type already present: org.json.Cookie
Message{kind=ERROR, text=Program type already present: org.json.Cookie, sources=[Unknown source file], tool name=Optional.of(D8)}



here is my app.gradel file 

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation files('libs/json-org.jar')
    implementation files('libs/WebSocket.jar')
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation "com.github.nkzawa:socket.io-client:0.5.0"


     implementation 'com.android.support:multidex:1.0.1'
}

**Comment by aamirmirza2999** [comment]
Please   help me out to solve this error

**Comment by luckynarang** [comment]
Use something like this -
implementation ('edu.stanford.nlp:stanford-parser:3.9.1') {
exclude group: 'edu.stanford.nlp.fsm.FastExactAutomatonMinimizer'
}
