### ISSUE TITLE
3.5.2 released, but not on Maven?

### ISSUE THREAD

**Issue by goldibex** [stanfordnlp/CoreNLP#70]
Is there an ETA for when I can get 3.5.2 off of Maven?

**Comment by TGVarik** [comment]
+1

Really looking forward to being able to use `Sentence.listToOriginalTextString()`.

**Comment by manning** [comment]
Thanks for the interest. We're fixing a couple of bugs with Universal Dependencies before putting it on Maven. But it should be there in a few days.

**Comment by manning** [comment]
Slow follow up, but it's been on Maven for a couple of weeks now....
