### ISSUE TITLE
Correlating between parser input string and output tokens and their character positions.

### ISSUE THREAD

**Issue by ndvbd** [stanfordnlp/CoreNLP#700]
I tried 2 input strings. The only difference is in the leading space.

When I parse 'The boy' - I get for "the" the positions (0,3) as it supposed to do.
When I parse ' The boy' - I get for "the" the positions (0,3), which is wrong (I added a leading space).

It feels like the whitespaces are trimmed at the beginning of the text? Is this a bug, or intended? What's the right scheme to fully correlate between input string and output tokens?

**Comment by J38** [comment]
Can you provide more details about how you processed the text and how you did this matching?

**Comment by nadavb** [comment]
Sure.
Simply do:

`curl --data 'The boy.' 'http://localhost:9001/?properties={%22annotators%22%3A%22tokenize%2Cssplit%2Cparse%22%2C%22outputFormat%22%3A%22json%22}' -o -`

and

`curl --data ' The boy.' 'http://localhost:9001/?properties={%22annotators%22%3A%22tokenize%2Cssplit%2Cparse%22%2C%22outputFormat%22%3A%22json%22}' -o -`

**Comment by J38** [comment]
I can see there are some issues with how the server handles input strings, it for instance seems to lose leading space, newlines.  I'm looking more into this now.

**Comment by J38** [comment]
line 316 of StanfordCoreNLPServer is causing the problem:

`text = URLDecoder.decode(text, encoding).trim();`

I will probably change this, but I am not sure why it was set up this way originally, so it may break a different case.

**Comment by nadavb** [comment]
Fantastic J38. If you managed to fix it, kindly tell us so we can pull the new version. Thanks!

**Comment by nadavb** [comment]
Hi @J38, any news on this one?

**Comment by AngledLuffa** [comment]
FWIW this was fixed a long time ago
