### ISSUE TITLE
Coreference and Dependency Parsing with JAR files w/o running a server

### ISSUE THREAD

**Issue by The-Gupta** [stanfordnlp/CoreNLP#701]
Can I use 'corefs'and 'depparse' without starting a server but using JAR files like "from nltk.tag.stanford import StanfordPOSTagger" for POS tagging?

**Comment by The-Gupta** [comment]
Found [here ](https://stackoverflow.com/questions/13883277/stanford-parser-and-nltk) for dependency parser with NLTK.

>>> from nltk.parse.stanford import StanfordDependencyParser
>>> dep_parser=StanfordDependencyParser(model_path="edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz")
>>> print [parse.tree() for parse in dep_parser.raw_parse("The quick brown fox jumps over the lazy dog.")]
[Tree('jumps', [Tree('fox', ['The', 'quick', 'brown']), Tree('dog', ['over', 'the', 'lazy'])])]

**Comment by J38** [comment]
We don't have any support for accessing coreference in Python without using the server.  The best you could do is make java calls with `subprocess`.  We are working on a standalone Python codebase for some of our algorithms, but it is unclear if or when we would integrate coref into that.
