### ISSUE TITLE
Illegal char <:> at index 44: \edu\stanford\nlp\models\kbp\tokensregex\per:siblings.rules

### ISSUE THREAD

**Issue by rubyakerman** [stanfordnlp/CoreNLP#702]
i got this error in android studio while trying to run the CoreNLP, i imported the jars (maybe not?)

someone has a clue? i spent almost 2 days trying to import this library for using it :)
any kind of help is blessing 

[this is a screenshot of android studio](https://i.stack.imgur.com/jsNxH.jpg)

**Comment by J38** [comment]
Hi I've changed the file names for all of the KBP models so they no longer have a ":".  This is with the latest code and latest models jars.  We will work on a new release fairly soon that includes these fixes.
