### ISSUE TITLE
dependency parser assigned a governor to the root of a sentence

### ISSUE THREAD

**Issue by yyzhuang1991** [stanfordnlp/CoreNLP#705]
When I tested the dependency parser for the sentence: Anyone else 's mom and dad do that thing where they call each other mom and dad , with the following command: 
 
      `wget --post-data "Anyone else 's mom and dad do that thing where they call each other mom and dad" 'localhost:9000/?properties={"annotators":"tokenize,ssplit,pos,depparse","outputFormat":"json"}' -O - `

it gave me a json like this: 
`{"sentences":[{"index":0,"basicDependencies":[{"dep":"ROOT","governor":0,"governorGloss":"ROOT","dependent":1,"dependentGloss":"Anyone"},{"dep":"nmod:poss","governor":4,"governorGloss":"mom","dependent":2,"dependentGloss":"else"},{"dep":"case","governor":2,"governorGloss":"else","dependent":3,"dependentGloss":"'s"},{"dep":"nsubj","governor":7,"governorGloss":"do","dependent":4,"dependentGloss":"mom"},{"dep":"cc","governor":4,"governorGloss":"mom","dependent":5,"dependentGloss":"and"},{"dep":"conj","governor":4,"governorGloss":"mom","dependent":6,"dependentGloss":"dad"},{"dep":"acl:relcl","governor":1,"governorGloss":"Anyone","dependent":7,"dependentGloss":"do"},{"dep":"det","governor":9,"governorGloss":"thing","dependent":8,"dependentGloss":"that"},{"dep":"dobj","governor":7,"governorGloss":"do","dependent":9,"dependentGloss":"thing"},{"dep":"advmod","governor":12,"governorGloss":"call","dependent":10,"dependentGloss":"where"},{"dep":"nsubj","governor":12,"governorGloss":"call","dependent":11,"dependentGloss":"they"},{"dep":"acl:relcl","governor":9,"governorGloss":"thing","dependent":12,"dependentGloss":"call"},{"dep":"det","governor":15,"governorGloss":"mom","dependent":13,"dependentGloss":"each"},{"dep":"amod","governor":15,"governorGloss":"mom","dependent":14,"dependentGloss":"other"},{"dep":"dobj","governor":12,"governorGloss":"call","dependent":15,"dependentGloss":"mom"},{"dep":"cc","governor":15,"governorGloss":"mom","dependent":16,"dependentGloss":"and"},{"dep":"conj","governor":15,"governorGloss":"mom","dependent":17,"dependentGloss":"dad"}],"enhancedDependencies":[{"dep":"ROOT","governor":0,"governorGloss":"ROOT","dependent":1,"dependentGloss":"Anyone"},{"dep":"det","governor":9,"governorGloss":"thing","dependent":1,"dependentGloss":"Anyone"},{"dep":"nmod:poss","governor":4,"governorGloss":"mom","dependent":2,"dependentGloss":"else"},{"dep":"case","governor":2,"governorGloss":"else","dependent":3,"dependentGloss":"'s"},{"dep":"nsubj","governor":7,"governorGloss":"do","dependent":4,"dependentGloss":"mom"},{"dep":"cc","governor":4,"governorGloss":"mom","dependent":5,"dependentGloss":"and"},{"dep":"conj:and","governor":4,"governorGloss":"mom","dependent":6,"dependentGloss":"dad"},{"dep":"nsubj","governor":7,"governorGloss":"do","dependent":6,"dependentGloss":"dad"},{"dep":"acl:relcl","governor":1,"governorGloss":"Anyone","dependent":7,"dependentGloss":"do"},{"dep":"ref","governor":1,"governorGloss":"Anyone","dependent":8,"dependentGloss":"that"},{"dep":"dobj","governor":7,"governorGloss":"do","dependent":9,"dependentGloss":"thing"},{"dep":"advmod","governor":12,"governorGloss":"call","dependent":10,"dependentGloss":"where"},{"dep":"nsubj","governor":12,"governorGloss":"call","dependent":11,"dependentGloss":"they"},{"dep":"acl:relcl","governor":9,"governorGloss":"thing","dependent":12,"dependentGloss":"call"},{"dep":"det","governor":15,"governorGloss":"mom","dependent":13,"dependentGloss":"each"},{"dep":"amod","governor":15,"governorGloss":"mom","dependent":14,"dependentGloss":"other"},{"dep":"dobj","governor":12,"governorGloss":"call","dependent":15,"dependentGloss":"mom"},{"dep":"cc","governor":15,"governorGloss":"mom","dependent":16,"dependentGloss":"and"},{"dep":"dobj","governor":12,"governorGloss":"call","dependent":17,"dependentGloss":"dad"},{"dep":"conj:and","governor":15,"governorGloss":"mom","dependent":17,"dependentGloss":"dad"}],"enhancedPlusPlusDependencies":[{"dep":"ROOT","governor":0,"governorGloss":"ROOT","dependent":1,"dependentGloss":"Anyone"},{"dep":"det","governor":9,"governorGloss":"thing","dependent":1,"dependentGloss":"Anyone"},{"dep":"nmod:poss","governor":4,"governorGloss":"mom","dependent":2,"dependentGloss":"else"},{"dep":"case","governor":2,"governorGloss":"else","dependent":3,"dependentGloss":"'s"},{"dep":"nsubj","governor":7,"governorGloss":"do","dependent":4,"dependentGloss":"mom"},{"dep":"cc","governor":4,"governorGloss":"mom","dependent":5,"dependentGloss":"and"},{"dep":"conj:and","governor":4,"governorGloss":"mom","dependent":6,"dependentGloss":"dad"},{"dep":"nsubj","governor":7,"governorGloss":"do","dependent":6,"dependentGloss":"dad"},{"dep":"acl:relcl","governor":1,"governorGloss":"Anyone","dependent":7,"dependentGloss":"do"},{"dep":"ref","governor":1,"governorGloss":"Anyone","dependent":8,"dependentGloss":"that"},{"dep":"dobj","governor":7,"governorGloss":"do","dependent":9,"dependentGloss":"thing"},{"dep":"advmod","governor":12,"governorGloss":"call","dependent":10,"dependentGloss":"where"},{"dep":"nsubj","governor":12,"governorGloss":"call","dependent":11,"dependentGloss":"they"},{"dep":"acl:relcl","governor":9,"governorGloss":"thing","dependent":12,"dependentGloss":"call"},{"dep":"det","governor":15,"governorGloss":"mom","dependent":13,"dependentGloss":"each"},{"dep":"amod","governor":15,"governorGloss":"mom","dependent":14,"dependentGloss":"other"},{"dep":"dobj","governor":12,"governorGloss":"call","dependent":15,"dependentGloss":"mom"},{"dep":"cc","governor":15,"governorGloss":"mom","dependent":16,"dependentGloss":"and"},{"dep":"dobj","governor":12,"governorGloss":"call","dependent":17,"dependentGloss":"dad"},{"dep":"conj:and","governor":15,"governorGloss":"mom","dependent":17,"dependentGloss":"dad"}],"tokens":[{"index":1,"word":"Anyone","originalText":"Anyone","characterOffsetBegin":0,"characterOffsetEnd":6,"pos":"NN","before":"","after":" "},{"index":2,"word":"else","originalText":"else","characterOffsetBegin":7,"characterOffsetEnd":11,"pos":"RB","before":" ","after":" "},{"index":3,"word":"'s","originalText":"'s","characterOffsetBegin":12,"characterOffsetEnd":14,"pos":"POS","before":" ","after":" "},{"index":4,"word":"mom","originalText":"mom","characterOffsetBegin":15,"characterOffsetEnd":18,"pos":"NN","before":" ","after":" "},{"index":5,"word":"and","originalText":"and","characterOffsetBegin":19,"characterOffsetEnd":22,"pos":"CC","before":" ","after":" "},{"index":6,"word":"dad","originalText":"dad","characterOffsetBegin":23,"characterOffsetEnd":26,"pos":"NN","before":" ","after":" "},{"index":7,"word":"do","originalText":"do","characterOffsetBegin":27,"characterOffsetEnd":29,"pos":"VBP","before":" ","after":" "},{"index":8,"word":"that","originalText":"that","characterOffsetBegin":30,"characterOffsetEnd":34,"pos":"DT","before":" ","after":" "},{"index":9,"word":"thing","originalText":"thing","characterOffsetBegin":35,"characterOffsetEnd":40,"pos":"NN","before":" ","after":" "},{"index":10,"word":"where","originalText":"where","characterOffsetBegin":41,"characterOffsetEnd":46,"pos":"WRB","before":" ","after":" "},{"index":11,"word":"they","originalText":"they","characterOffsetBegin":47,"characterOffsetEnd":51,"pos":"PRP","before":" ","after":" "},{"index":12,"word":"call","originalText":"call","characterOffsetBegin":52,"characterOffsetEnd":56,"pos":"VBP","before":" ","after":" "},{"index":13,"word":"each","originalText":"each","characterOffsetBegin":57,"characterOffsetEnd":61,"pos":"DT","before":" ","after":" "},{"index":14,"word":"other","originalText":"other","characterOffsetBegin":62,"characterOffsetEnd":67,"pos":"JJ","before":" ","after":" "},{"index":15,"word":"mom","originalText":"mom","characterOffsetBegin":68,"characterOffsetEnd":71,"pos":"NN","before":" ","after":" "},{"index":16,"word":"and","originalText":"and","characterOffsetBegin":72,"characterOffsetEnd":75,"pos":"CC","before":" ","after":" "},{"index":17,"word":"dad","originalText":"dad","characterOffsetBegin":76,"characterOffsetEnd":79,"pos":"NN","before":" ","after":""}]}]}`

The enhanced dependencies treated "anyone" as the root but also assigned it a governor "thing": 
`{"dep":"ROOT","governor":0,"governorGloss":"ROOT","dependent":1,"dependentGloss":"Anyone"},{"dep":"det","governor":9,"governorGloss":"thing","dependent":1,"dependentGloss":"Anyone"},`

The same happened to the enhanced plus-plus dependencies. I wonder if this is a valid output.

**Comment by AngledLuffa** [comment]
The particular dependencies here look quite messed up.  In general, though, the enhanced dependencies can add some backlinks from the children of a relative clause to the parent.  If the parent happens to be the root, then that means there are links going to the root.  Also, in version 4.0.0, the parse for this sentence is somewhat improved.  So for multiple reasons, this issue can be closed as of 4.0.0.
