### ISSUE TITLE
[URGENT] Parser Online Demo Not Working 

### ISSUE THREAD

**Issue by candicefan** [stanfordnlp/CoreNLP#706]
Hi, we are using the online demos (http://nlp.stanford.edu:8080/parser/index.jsp) to look at the parse trees of sentences for a final project that is due tomorrow. But the website is down from around noon yesterday. There were some downs before, but never for this long period of time. Would you mind bring the online demos back up? Thank you so much!

**Comment by J38** [comment]
Hi sorry, I've been playing with upgrading our tomcat.  It should be back up in a second.
You should also consider using `http://corenlp.run` which will also give you parse trees.

**Comment by hanryhu** [comment]
Hello, both http://nlp.stanford.edu:8080/parser/ and http://corenlp.run seem to be down.  Are there plans to bring them back up?

**Comment by AngledLuffa** [comment]
Should be reloading now

**Comment by Enterprais** [comment]
Hello, http://nlp.stanford.edu:8080/parser/ has been down for a while. Will it be up?

**Comment by nikhilvirmani4** [comment]
Hi,  https://nlp.stanford.edu:8080/parser/ is down
Can you please help with that?

**Comment by AngledLuffa** [comment]
Looks like it's working now, fwiw

**Comment by PPW6** [comment]
Hello, both http://nlp.stanford.edu:8080/parser/ and http://corenlp.run/ seem to be down. Are there plans to bring them back up?

**Comment by AngledLuffa** [comment]
I will need to confer with our sysdev team to figure out what happened to
corenlp.run  It's on my radar
