### ISSUE TITLE
CoreNLP potential bug

### ISSUE THREAD

**Issue by vyhuhol** [stanfordnlp/CoreNLP#71]
Hello,

I am running the following pipeline with Stanford CoreNLP 3.5.2
annotators = tokenize,ssplit,pos,lemma,ner,depparse

with output to json
-outputFormat json

The problem is CoreNLP doesn't split tokens to sentences, every sentence contains all tokens in the input text.

If text contains 100 tokens, then
length(sentence_1) = 100 tokens
....
length(sentence_n) = 100 tokens

Bug appears only in json format.

**Comment by manning** [comment]
I agree that the json output is buggy (@gangeli). It's not about depparse in particular, you get the same result with the default pipeline. The text is divided into sentences and parsed as such, but for each sentence, the "tokens" list is the whole text.

**Comment by vyhuhol** [comment]
@gangeli, how can I apply this fix to the current Stanford CoreNLP (3.5.2)? I tried to use stanford-corenlp-3.5.2.jar from MAVEN but it's still a buggy version.

**Comment by gangeli** [comment]
This will be fixed in the next release of CoreNLP. You can always clone this git repository and run `ant jar` to create the most recent version.
