### ISSUE TITLE
Make annotators to ignore some tokens

### ISSUE THREAD

**Issue by alsora** [stanfordnlp/CoreNLP#710]
Hi everyone,

I'm working with a CoreNLP pipeline and at a certain stage I'm selecting some tokens to be ignored by further components of the pipeline.
Consider this sentence:

> I have a big cat

I would like to mark the token "big" in order to be ignored by successive annotators.
Instead of completely removing the token I would prefer to simply mark it, since this would allow to reconstruct the original sentence in an easier way.

Do you have any idea about how to do that?

Thank you

**Comment by J38** [comment]
I think the best thing you could do is run one pipeline to tokenize the text, and then process each sentence and create a new annotation that doesn't have the tokens you want to remove if you want to process "I have a cat" instead.  If you start messing with the token values in the original annotation like this I think it's going to cause problems, the pipeline is not really set up to handle that.
