### ISSUE TITLE
corenlp ner prediction takes a long time

### ISSUE THREAD

**Issue by shikimoon** [stanfordnlp/CoreNLP#711]
sentence cost statistics
Total: 363630, min: 14ms, max: 60135ms, Average: 148.62655446470313ms, P90: 119ms, P95: 158ms, P99: 445ms, 0.1%above: 13807ms,0.01%above: 14364ms, 0.001%above: 14672ms

sentence length statistics
Total: 363630, min: 1, max: 605, Average: 15.197348953606689, P90: 46, P95: 48, P99: 94, 0.1%above: 205, 0.01%above: 253, 0.001%above: 510
when the sentence is long, prediction takes a long time,how to reduce it

**Comment by J38** [comment]
Unfortunately there isn't really any way around this other than setting a max limit if you don't want to tag long sentences.  You can use the `ner.maxSentenceLength` option to not have `ner` run on long examples.
