### ISSUE TITLE
how does the basic authentication with "username" and "password" params when starting up the server work?

### ISSUE THREAD

**Issue by Luke-Tan** [stanfordnlp/CoreNLP#712]
https://stanfordnlp.github.io/CoreNLP/corenlp-server.html
From the docs here, it is mentioned that you can flag username and password params when running the command to start the coreNLP server for basic authentication. However, there is not much else written on how to use it. Could someone guide me on how it works and how to provide the username and pw when making a request so that the authentication works?

**Comment by J38** [comment]
command to start the server:
`java -Xmx4g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties custom.properties -port 9000 -timeout 15000 -username myUsername -password myPassword`

example wget:

`wget --user myUsername --password myPassword --post-data 'The quick brown fox jumped over the lazy dog.' 'localhost:9000/?properties={"outputFormat":"json"}' -O -`
