### ISSUE TITLE
Tokens with empty text classified as NUMBERS

### ISSUE THREAD

**Issue by alsora** [stanfordnlp/CoreNLP#716]
Hi,

I am working with the NLP pipeline.
I noticed that if I set the text of a token to an empty string, then it is treated in a very strange way by successive annotators.

I'm working on English text.
I am basically doing the following:

```
token.setWord("");
token.setValue("");
```

Then the POS annotator sets the POS to CD and the NER annotator sets it as a NUMBER.

Do you have any idea why ?

Best regards

**Comment by J38** [comment]
I would strongly recommend against altering the text of a token in this manner.
