### ISSUE TITLE
How can I change the output of dependency parser of stanford corenlp into conllU format?

### ISSUE THREAD

**Issue by paktiger** [stanfordnlp/CoreNLP#717]
I want to train my Classifier with CONLLU format, however, Stanford corenlp dependency parser produces a tree structure. I need to have dependency parser out in the following format:
**The	DET	DT	det
Mayan	PROPN	NNP	compound
Empire	PROPN	NNP	nsubj
grew	VERB	VBD	ROOT
from	ADP	IN	prep
about	ADP	IN	prep
the	DET	DT	det
year	NOUN	NN	pobj
400	NUM	CD	nummod
to	ADP	IN	quantmod
900	NUM	CD	advcl
.	PUNCT	.	punct**
I need stanford corenlp api that changes the result of dependency parser.

**Comment by J38** [comment]
`java -Xmx5g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,depparse -file example.txt -outputFormat conllu`

**Comment by nirmalsurange** [comment]
How to get UD-POS tags along with fine-grained tags in output? I tried -outputFormat conllu, but the UPOS column remained empty. This is what I got:
1	Antonius	Antonius	_	NNP	_	2	compound	_	_
2	Romanus	Romanus	_	NNP	_	12	nsubj	_	_
3	(	(	_	-LRB-	_	4	punct	_	_
4	fl.	fl.	_	VBP	_	12	nsubj	_	_
5	1400	1400	_	CD	_	4	dep	_	_
6	--	--	_	:	_	7	punct	_	_
7	1432	1432	_	CD	_	5	dep	_	_
8	)	)	_	-RRB-	_	7	punct	_	_
9	was	be	_	VBD	_	12	cop	_	_
10	an	a	_	DT	_	12	det	_	_
11	Italian	italian	_	JJ	_	12	amod	_	_
12	composer	composer	_	NN	_	0	root	_	_
13	of	of	_	IN	_	17	case	_	_
14	the	the	_	DT	_	17	det	_	_
15	early	early	_	JJ	_	17	amod	_	_
16	15th	15th	_	JJ	_	17	amod	_	_
17	century	century	_	NN	_	12	nmod	_	_
18	.	.	_	.	_	12	punct	_	_

**Comment by AngledLuffa** [comment]
Please open a new issue
