### ISSUE TITLE
TreeGraph missing in version 3.5 ?

### ISSUE THREAD

**Issue by wangxiangtao** [stanfordnlp/CoreNLP#72]
Hi , I have used TreeGraph in version 3.4 
But it seems it disappear in the new version . 
so how can I implement below code ? 

TreeGraph treegraph =  new TreeGraph(tree) ;
TreeGraphNode  root = treegraph.root();

**Comment by AngledLuffa** [comment]
Getting rid of this was a big interface improvement.  I think you should
instead be able to construct a SemanticGraph or an
EnglishGrammaticalStructure / ChineseGrammaticalStructure to get any
information you were getting from the TreeGraphNode,

John

**Comment by wangxiangtao** [comment]
Thanks for your reply .  Could you explain how to convert Tree to TreeGraphNode ? 
I want to get the root(TreeGraphNode) of the tree.  then traversal the tree

**Comment by wangxiangtao** [comment]
I need parent() method which works without searching from the root. that'why i need TreeGraphNode instead Tree.  so how to get the root which is a TreeGraphNode ?

**Comment by AngledLuffa** [comment]
The `TreeGraphNode` still exists. Its primary uses are to store parent
pointers when creating the dependency objects and to give a huge middle
finger to Java inheritance conventions.  You can probably construct these
objects using the `factory()` method in the class.

Can you write your code to work from the top of the tree and remember what
the current parent is, though?

**Comment by manning** [comment]
So, basically, you should be good just doing what you were but with just TreeGraphNode and TreeGraphNodeFactory.
