### ISSUE TITLE
-filelist has inconsistent naming

### ISSUE THREAD

**Issue by gattilorenz** [stanfordnlp/CoreNLP#722]
From the command line, the parameters are outputFormat, outputDirectory, replaceExtension and so on, but fileList is not recognized (while filelist is).

This is inconsistent and mildly confusing, and it would be a minor improvement to accept both versions (so that you don't break existing scripts)

**Comment by J38** [comment]
Ok I set it up to handle `fileList` as well, but it will handle `filelist` for legacy purposes.
