### ISSUE TITLE
Head finder does not recognize head correctly

### ISSUE THREAD

**Issue by morvarid21** [stanfordnlp/CoreNLP#723]
With texts such as "Boys & Girls", CoreNLP detects Boys as head but not Girls. Shouldn't they be treated similarly?

**Comment by ladiesman6969** [comment]
I don't think so

**Comment by morvarid21** [comment]
Any comments?

**Comment by AngledLuffa** [comment]
It's a left to right rule.  boys & girls, girls & boys, dogs & cats, oil & vinegar
