### ISSUE TITLE
chinese segmenter doesn't tokenize newline

### ISSUE THREAD

**Issue by Rossonero** [stanfordnlp/CoreNLP#73]
I read that "A side-effect of setting ssplit.newlineIsSentenceBreak to "two" or "always" is that tokenizer will tokenize newlines." but when I set ssplit.newlineIsSentenceBreak to always,  chinese segmenter does not keep newline tokens, which lead to ssplit's failure to split sentences by newline.

**Comment by J38** [comment]
This has been fixed!
