### ISSUE TITLE
Training Format

### ISSUE THREAD

**Issue by sarankup** [stanfordnlp/CoreNLP#731]
Hi,

I want to create NER sample using my own data set. I could not see the `entitymentions` sample data format anywhere. Could you please advise the format of `entitymentions` to train?

So far, I could create data model for NER using the following details.
[https://stanfordnlp.github.io/CoreNLP/ner.html](url)

Thanks in advance.

**Comment by J38** [comment]
I'm unclear what you mean.  The entity mentions are formed by rules based off of the NER tags.  So 
(Joe PERSON) (Smith PERSON) becomes the entity (Joe Smith).  If you have a more advanced NER tag set such as BIO, then (Joe B-PERSON) (Smith I-PERSON) (Jane B-PERSON) (Smith I-PERSON) would become the two entities (Joe Smith) and (Jane Smith).  But the entity mentions are completely determined by the `ner` tags.  You can see the code in `edu.stanford.nlp.pipeline.EntityMentionsAnnotator` (which as of 3.9.1 is run as a sub-annotator of the `ner` annotator).  Please let me know if you need any more info.

**Comment by sarankup** [comment]
Hi, Thanks for your response. My model is as follows_
```
World ORG
Health ORG
Organization ORG
best O
Organization A
World A
```

And, my statement is `World Health Organization is one of the best organization in the World`
When I process the annotation, even the `ORG` elements are tagged as `A`

Please advise how to create my model as follows
`Word Health Organization ORG
Organization A
World A`

**Comment by Florian9M** [comment]
You can use the IOB format
