### ISSUE TITLE
What does it mean - "Updated for compatibility"

### ISSUE THREAD

**Issue by ArsenyClean** [stanfordnlp/CoreNLP#734]
Hi!

I am looking for explanation of the release notes of Stanford NLP

If i come to this page (https://github.com/stanfordnlp/CoreNLP/blob/master/doc/lexparser/README.txt) and read about chenges, so in version 3.8.0 i found - "Updated for compatibility".

But if i come here (https://stanfordnlp.github.io/CoreNLP/history.html), i see "Web service annotator, discussion forum handling, new French and Spanish UD POS models, emoji support", and i understand what does it mean. But i dont see dependency of this text with the "Updated for compatibility". 

Maybe, i am not good in English enoth, or you can add more information to explain the frase "Updated for compatibility".  

Please answer me as fast? as you can, this information is very important for me!

**Comment by J38** [comment]
The parser release is a subset of the full code release.  I don't believe there were any major changes in that subset from the previous release hence the generic message, but the code in the 3.8.0 parser release is from the same commit as the 3.8.0 full release.
