### ISSUE TITLE
About chinese CoreNLP modles 

### ISSUE THREAD

**Issue by mylenezhou** [stanfordnlp/CoreNLP#740]
I use chinese CoreNLP modles to make a NER of adress. But i can't understand what do GPE and facility mean????
When i test some Chinese adresses,i got the result below:
![image](https://user-images.githubusercontent.com/40876756/42356610-0d4c1ce6-8106-11e8-88e1-9dedfec0e98d.png)
Can someone help me with this issue? THANK YOU VERY MUCH!

je suis entrain de faire une reconnaissance de l'adress NER .je voulais savoir les sens des labels GPE et facility dans le module chinois CoreNlp. merci beaucoup!

同志们，有没有人用中文的CORENLP模型做NER？我发现它识别出来的地址很少打标是LOCATION的，大部分是GPE和FACILITY，有没有人知道这两个标识是什么？？？谢谢了！

**Comment by sea-boat** [comment]
"FACILITY" Buildings, airports, highways, bridges, etc

**Comment by sea-boat** [comment]
in addition,"GPE" for cities,countries,etc.

**Comment by mylenezhou** [comment]
@sea-boat 跪谢大佬救命之恩！衔草结环磨齿难忘！
