### ISSUE TITLE
Steps to generate a new sentiment model file

### ISSUE THREAD

**Issue by cheungtitus** [stanfordnlp/CoreNLP#742]
Can someone please confirm if the following is the correct sequence of steps to generate a new sentiment model (eg sentiment.ser.gz)?
Specifically questions on.

- How do you break each sentence into phrases in step 4?
- Why do we need SOStr.txt in step 6?  I know it's an input to ReadSentimentDataset.java for generating the three tree files train.txt, dev.txt, and test.txt.  But is that the only reason why this file is required?
- How do we generate STree.txt in step 7?  Seriously this is a mystery.
- Is it true that both methods 1 & 2 under step 8 can be used to generate the tree files?
- For step 8 method 1, how do we know we need to use 'good', 'good day', and 'a good day'?  What about 'is not'?  What do the numeric labels mean?

## Preparation

1. Find a bag of comments such as original_rt_snippets.txt which contains 10,605 comments.
2. For each comment in the original_rt_snippets.txt file that has multiple sentences, break up the comment to have each of its sentence on its own line.  Applying this process on the 10,605 comments in original_rt_snippets.txt creates datasetSentences.txt which has 11,855 sentences.
    This should be easy by using the ssplit annotator.  Here is an example of how to do this interactively.
    ```text
    C:\Users\cheun\.m2\repository\edu\stanford\nlp\stanford-corenlp\3.9.1>java -cp "*;C:\Users\cheun\.m2\repository\org\ejml\*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit
    Adding annotator tokenize
    No tokenizer type provided. Defaulting to PTBTokenizer.
    Adding annotator ssplit

    Entering interactive shell. Type q RETURN or EOF to quit.
    NLP> are you sure?  really?

    Sentence #1 (4 tokens):
    are you sure?

    Tokens:
    [Text=are CharacterOffsetBegin=0 CharacterOffsetEnd=3]
    [Text=you CharacterOffsetBegin=4 CharacterOffsetEnd=7]
    [Text=sure CharacterOffsetBegin=8 CharacterOffsetEnd=12]
    [Text=? CharacterOffsetBegin=12 CharacterOffsetEnd=13]

    Sentence #2 (2 tokens):
    really?

    Tokens:
    [Text=really CharacterOffsetBegin=15 CharacterOffsetEnd=21]
    [Text=? CharacterOffsetBegin=21 CharacterOffsetEnd=22]
    NLP>
    ```
3. Each line in datasetSentences.txt is assigned into one of three different lists, which are 1 - train, 2 - test, and 3 - dev. datasetSplit.txt is a map datasetSentences.txt to a number representing which of these three list it is assigned to.
4. Each sentence is then broken down into phrases.  Doing this on the 11,855 sentences in datasetSentences.txt we have 239,232 phrases, each represented by a line in dictionary.txt.
5. Have someone manually assign a sentiment to each of the 239,232 phrases to create sentiment_labels.txt.
6. Run the Stanford Tokenizer on datasetSentences.txt to generate SOStr.txt.  Not sure why we need this file as it appears to be simply delimiting the words in a sentence with the '|' character.
    We can see the example in step 2 above how the tokens are generated.
7. Create a STree.txt.  Not sure how this is done and what the numbers mean.
8. Create the train.txt, test.txt, and dev.txt tree files based on sentences categorized during step 3 above.  These are two ways of doing this.

    ##### Method 1 - BuildBinarizedDataset.java class

    Example of how to do this is as follow.

    - Create an input file containing the original sentences from datasetSentences.txt.
    - For each of these lines we will list out all its parts.
    - Assign all these with a numeric label.  Have absolutely no idea what the numeric label represents.

    So we have something like this as an input file.
    ```text
    1 Today is not a good day.
    3 good
    3 good day
    3 a good day
    ```

    Running the input file with BuildBinarizedDataset creates a tree for the sentence.  Example of how to do this is as follow.
    ```text
    C:\Users\cheun\.m2\repository\edu\stanford\nlp\stanford-corenlp\3.9.1>java -cp "stanford-corenlp-3.9.1.jar;stanford-corenlp-3.9.1-models.jar;C:\Users\cheun\.m2\repository\org\ejml\*" -Xmx5g edu.stanford.nlp.sentiment.BuildBinarizedDataset -input treebanksource.txt
    Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.7 sec].
    (3 (3 Today) (3 (3 (5 (3 is) (3 not)) (30 (3 a) (3 (1 good) (3 day)))) (3 .)))
    ```

    ##### Method 2 - ReadSentimentDataset.java

    Using dictionary.txt, sentiment_labels.txt, SOStr.txt, STree.txt, and datasetSplit.txt, ReadSentimentDataset.java can generate the three tree files train.txt, dev.txt, and test.txt.

    ```text
    java edu.stanford.nlp.sentiment.ReadSentimentDataset -dictionary stanfordSentimentTreebank/dictionary.txt -sentiment stanfordSentimentTreebank/sentiment_labels.txt -tokens stanfordSentimentTreebank/SOStr.txt -parse stanfordSentimentTreebank/STree.txt -split stanfordSentimentTreebank/datasetSplit.txt -train train.txt -dev dev.txt -test test.txt
    ```

## Generate Model
After having prepping all the data above we can now generate a model with the following, creating the new model.ser.gz file.

```text
java -mx8g edu.stanford.nlp.sentiment.SentimentTraining -numHid 25 -trainPath train.txt -devPath dev.txt -train -model model.ser.gz
```

**Comment by AngledLuffa** [comment]
Personally I would go directly to trees, although unfortunately there isn't
much support specifically to help with this.  They are parenthesized trees
in a similar format to PTB parse trees, but the labels of the nodes are the
sentiment value rather than the parse tag.  Examples of those data files
should also be present on the website.

**Comment by bond-** [comment]
We need this too, personally I feel the documentation is non-existent or not present in the right language.

**Comment by AngledLuffa** [comment]
I seem to recall there being more documentation, but I can't find it now.  Anyway, check out

edu.stanford.nlp.sentiment.BuildBinarizedDataset
https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/sentiment/BuildBinarizedDataset.html

You can also hand build a bunch of trees which look like

(0
  (2
    (2 Ian)
    (2 Laperrière))
  (0
    (0
      (0 sucks)
      (2
        (2 as)
        (3
          (3 a)
          (3 
            (2 PK)
            (3 coach)))))))

You can also run a bunch of sentences such as "Ian Laperrière sucks as a PK coach" through the parser, then replace the tags such as NP etc with the sentiment labels.  

Perhaps you could put together a better tool which labels trees.  I don't think we have such a thing.

Note that the trees need to be fully binarized for use in the sentiment tool.  Honestly it's been a while, so I can't remember which option in the parser forces it to output binarized trees.

**Comment by pa-cloud** [comment]
Hi, I tried to generate custom model..my approach is mentioned https://github.com/stanfordnlp/CoreNLP/issues/793 . Till now only tested with a toy dataset.
