### ISSUE TITLE
cant run file to parse scene graph from commanda line

### ISSUE THREAD

**Issue by galsk87** [stanfordnlp/CoreNLP#745]
I'm running the next command:
java wiki_00 -mx2g -cp "*" edu.stanford.nlp.scenegraph.RuleBasedParser
and getting the next error
Error: Could not find or load main class wiki_00

**Comment by AngledLuffa** [comment]
I don't see any documentation which suggests to put wiki_00 at that part of the command line.  Putting it first makes java think that's the class you want to run, not the file you want to process.
