### ISSUE TITLE
regexner.mapping locations.txt missing?

### ISSUE THREAD

**Issue by TrollWarlord** [stanfordnlp/CoreNLP#75]
I'm looking for locations.txt, I found your sample, but what about the sample used in the visualizer.

**Comment by manning** [comment]
Sorry you didn't get an answer, but I don't think anyone knows what you're referring to. Doing a google search, I found a `locations.txt` on [this web page](http://www.informit.com/articles/article.aspx?p=2265404), but I don't think we distribute one - where were you seeing a reference to this? - and I'm not sure what sample in what visualizer you are referring to.
