### ISSUE TITLE
In case you do not want the CoreNLP server to use all your computer's processors on Linux

### ISSUE THREAD

**Issue by neilnelson** [stanfordnlp/CoreNLP#750]
This is information only and should be closed.

The following causes the CoreNLP java server to use only processors 0 and 1. (0x03 is processors 1 and 2 by the way taskset counts.) The links below show how to select which and how many processors.

taskset 0x03 java ...

How to set CPU affinity to a process
https://askubuntu.com/questions/102258/how-to-set-cpu-affinity-to-a-process

Linux Setting processor affinity for a certain task or process
https://www.cyberciti.biz/tips/setting-processor-affinity-certain-task-or-process.html

**Comment by J38** [comment]
Thanks for the info!
