### ISSUE TITLE
Why CoreNLP server 3.9.1 is much slower than 3.8.0?

### ISSUE THREAD

**Issue by zhonghao0077** [stanfordnlp/CoreNLP#751]
Hi，

Recently I am trying to use the server mode of CoreNLP 3.9.1, The annotation contains ssplit, tokenize, pos, lemma and ner. The speed seems much slower than 3.8.0. 
Do you know why is that 
thanks，

Peter

**Comment by J38** [comment]
By default `ner` runs a lot of rule based stuff now.  You can deactivate that by setting `ner.applyFineGrained` to false and should speed up performance (though you'll lose the fine-grained tags such as CITY, STATE, and COUNTRY, etc...)
