### ISSUE TITLE
How to reload a custom entity model in CoreNLP Server?

### ISSUE THREAD

**Issue by RachelKrh** [stanfordnlp/CoreNLP#753]
I have trained a Custom Entity Model using Core NLP and I am able to load it into the CoreNLP Server and get entities using the model. However after retraining the model and replacing the old model file with the new file, I am not getting results as per the new training without restarting the server. Seems CoreNLP server is using the same model that was first loaded into it.  Restarting the server after each training is not possible in our business use case. Is there a way to reload a model into CoreNLP server without restarting the server?

**Comment by J38** [comment]
The short term answer would be to give every new version of the model a new name `ner_model_20180801.ser.gz` then `ner_model_20180802.ser.gz` etc...then when you make a server request set `"ner.model": "ner_model_20180802.ser.gz"`...you will always have to include the name of the latest model you want to use in the request.

Medium term I can investigate adding an option that would allow you to send a purge cache message then it will behave as you wish.  Though for one request it will be forced to reload ALL of the models and start from scratch (which I assume is not a big deal).  I suppose I could also see how difficult it would be to just specifically purge a specific resource from the cache.

**Comment by RachelKrh** [comment]
Thanks. We will go ahead with renaming the versions for now. It would be great if you could add the option to purge a specific model alone from the cache without affecting the other models.
