### ISSUE TITLE
CleanXmlAnnotator.process throws NullPointerException

### ISSUE THREAD

**Issue by mengxr** [stanfordnlp/CoreNLP#754]
`CleanXmlAnnotator.process(tokens)` invokes `process(null /* annotation */, tokens)` at https://github.com/stanfordnlp/CoreNLP/blob/bfc7f66/src/edu/stanford/nlp/pipeline/CleanXmlAnnotator.java#L382. However, `process(null, tokens)` calls `annotation.set` without null checking 
 at https://github.com/stanfordnlp/CoreNLP/blob/bfc7f66/src/edu/stanford/nlp/pipeline/CleanXmlAnnotator.java#L535. This triggers an NPE.

**Comment by J38** [comment]
Ok this should be fixed now!  Thanks for bringing it our attention!
