### ISSUE TITLE
invertible=true not working with XML output

### ISSUE THREAD

**Issue by ZhaofengWu** [stanfordnlp/CoreNLP#759]
When `invertible=true` is used with JSON output, the three additional fields `originalText`, `before`, and `after` do show up. However, when the output format is changed to XML, these three fields are lost.

Using 2018-02-27 version of CoreNLP, with official [python-stanford-corenlp](https://github.com/stanfordnlp/python-stanford-corenlp) wrapper.

**Comment by AngledLuffa** [comment]
Part of the problem here could be that whitespace is pretty hard to encode in a satisfactory manner.  What do you do with either blank spaces or \n?

**Comment by AngledLuffa** [comment]
I set it so that the `includeText` option adds the Before, After, and OriginalText annotations needed to recreate the original text.  They are in between xml tags so presumably the whitespace is okay there.

**Comment by AngledLuffa** [comment]
https://github.com/stanfordnlp/CoreNLP/commit/592e12ed23898e402145dfa09b786a71d47f60c2
