### ISSUE TITLE
Would like to get all the labels for NER, thanks~

### ISSUE THREAD

**Issue by Alice1998** [stanfordnlp/CoreNLP#761]
I know there are 3 class:	Location, Person, Organization
4 class:	Location, Person, Organization, Misc
7 class:	Location, Person, Organization, Money, Percent, Date, Time

While I would like to know all the labels that will show up in the 3 class NER.
(PS. I got these in my test.)
PPS. I am dealing with Chinese text, thanks a lot.
facility
organization
person
title
number
ordinal
ideology
date
location
state or province
country
city
GPE
MISC
DEMONYM
cause of death

**Comment by J38** [comment]
Hi, are you using the Chinese NER model ?

The statistical model should apply these tags:

```
FACILITY
GPE
LOCATION
MISC
ORGANIZATION
PERSON
```

There are the tags that should be applied by the fine-grained component:

```
CAUSE_OF_DEATH
CITY
COUNTRY
CRIMINAL_CHARGE
IDEOLOGY
LOCATION
NATIONALITY
ORGANIZATION
PERSON
RELIGION
STATE_OR_PROVINCE
TITLE
```

**Comment by Alice1998** [comment]
thanks a lot~

**Comment by J38** [comment]
I don't think DEMONYM should be showing up, but maybe ?  I looked at the Chinese statistical model's training data, the Chinese fine-grained rules, and the numerical processing rules, and posted those tags.  It's possible I'm missing something though, but I think that list is pretty exhaustive!

**Comment by jianz94** [comment]
> I don't think DEMONYM should be showing up, but maybe ? I looked at the Chinese statistical model's training data, the Chinese fine-grained rules, and the numerical processing rules, and posted those tags. It's possible I'm missing something though, but I think that list is pretty exhaustive!

Could you please offer the link of the Chinese statistical model's training data? I can't find it anywhere. Thanks a lot.
