### ISSUE TITLE
nlp.stanford.edu/js/brat/style-vis.css timeout

### ISSUE THREAD

**Issue by qweer28** [stanfordnlp/CoreNLP#762]
Hi,

I want to use the web version of CoreNLP server. But when I access [localhost:9000](localhost:9000), I got [https://nlp.stanford.edu/js/brat/client/lib/head.load.min.js](https://nlp.stanford.edu/js/brat/client/lib/head.load.min.js) and [https://nlp.stanford.edu/js/brat/style-vis.css](https://nlp.stanford.edu/js/brat/style-vis.css) timeout from chrome console, which makes the web version cannot work.

I guess the main cause is that [https://nlp.stanford.edu](https://nlp.stanford.edu) cannot be connected now. Any idea when it will be fixed? Thanks!

**Comment by chankeypathak** [comment]
The website was down. It's accessible now.

**Comment by qweer28** [comment]
Thanks.
