### ISSUE TITLE
Download CoreNLP 3.9.1 not working

### ISSUE THREAD

**Issue by neilnelson** [stanfordnlp/CoreNLP#763]
The link on this page https://stanfordnlp.github.io/CoreNLP/#download does not complete connection. This is likely a minor issue.

**Comment by chankeypathak** [comment]
The website was down. It's accessible now.

**Comment by J38** [comment]
Sorry for any inconveniences, we had a planned cluster outage all Labor Day weekend, but things should be returning to normal soon!
