### ISSUE TITLE
Spark partition issue with Stanford NLP

### ISSUE THREAD

**Issue by mathewvino** [stanfordnlp/CoreNLP#77]
I am trying to process millions of data with spark/scala integrated with stanford NLP (3.4.1). Since I am using social media data I have to use NLP for the themes generation (pos tagging) and Sentiment calulation.

I have to deal with Twitter data and NON Twitter data separately.So I have two classes that deal with Twitter/Non Twitter

I am using lasy val initialization from each class for loading the stanfordNLP

features: Seq[String] = Seq("tokenize","ssplit","pos","parse","sentiment")
  val props = new Properties()
  props.put("annotators", features.mkString(", "))
  props.put("pos.model", "tagger/gate-EN-twitter.model")
  props.put("parse.model", "tagger/englishSR.ser.gz");
  val pipeline = new StanfordCoreNLP(props)
Note: For above Twitter I am using different pos model and shift reduce parse model for parsing. The reason I use shift reduce parser is for some of the junk data at rum time the default PCFG model takes lot of time for processing and getting some Exception.Shift reduce parser will take around 15 seconds at load time and its faster at run time while processing the data.

NonTwitter class

 features: Seq[String] = Seq("tokenize","ssplit","pos","parse","sentiment")
    val props = new Properties()
    props.put("annotators", features.mkString(", "))
    props.put("parse.model", "tagger/englishSR.ser.gz");
Here I am using the default pos model and shift reduce parser

Problem:

Currently we am running with 8 Nodes with 6 cores and I can run with 48 partition. For to process millions of data with the above configuratin with lesser partition it works fine for me.

8 Nodes and 6 cores we have almost 48 partition and if I ran with 42 Number of partition it takes around 1 hr to finish the processing.

with the current configuration I need to scale it to 200 partition

8 Nodes and 6 cores we have almost 48 partition and if we ran with 200 Number of partition it takes around 2 hr and finally throwing some exception saying the one node is lost or java.lang.IllegalArgumentException: annotator "sentiment" requires annotator "binarized_trees" etc etc.

The problem is only if we scale up the number of partition to 200 with 8 Nodes and 6 cores which we have only 48 cores.

I have the suspect that its cuz of loading the shift reduce parser loading at each partition.i thought of loading this class at one time and then do the Broadcast but standforndNLP class is not searializable so i cannot broadcast.any thought suggestion

The reason we need to scale to 200 partition is it will run quickly with lesser time to process this data. Any thoughts suggestion is relly helpful

**Comment by gangeli** [comment]
I suspect you're going to have a hard time finding anyone here that can help substantially with Spark. If you can isolate the bug in a way we can test it, we can certainly help debug it. But, I think most of us have very little expertise in Spark, and at least I don't have much of an idea of what might be going wrong (anyone reading this -- feel free to chime in if you can help!). 

Just general debugging advice: try to run with fewer annotators and see if that works. In particular, take out the sentiment annotator, and that should take care of the "binarized_tree" issue -- then, if other issues come up instead those might be the root cause of the problem. Another thing that might be useful: CoreNLP multithreads, so you can load the model only once per node and run it on <# cores> threads.

Lastly, if all you're doing is annotating a bunch of documents and serializing them somewhere, you might not need Spark at all. Chances are the time you spend using CPU on a node is far more than the time you spend moving data between nodes. The unix `split` utility in combination with looping through your nodes and starting CoreNLP may actually just be easier in the end (certainly much more debugging friendly).

**Comment by mathewvino** [comment]
Thanks Gabor for looking into it.
I am  trying to isolate one by one as you said. By the way I am interested to know about coreNLP multithreads. How do I load the model only once per node.is it something I can set in the scala/java programme. Could you please share some light on it.(some example to load the sentiment,pos,parse...in java/scala)
I am thinking  i am dividing 1 node to 8 partition and each partition is loading all the files.
ThanksVinoj
Date: Thu, 28 May 2015 01:03:51 -0700

**Comment by manning** [comment]
I don't understand the details of your message with apparently different results with different numbers of workers/partitions, but what you want to do is load the appropriate CoreNLP once on each worker. (And you can have two different CoreNLP pipelines loaded in one program, if you're using two different pipelines, as here.)

Have you tried the approach that Evan Sparks describes on this thread? I think it should work for you, providing you set up __two__ StanfordCoreNLP pipelines on each worker.  http://apache-spark-user-list.1001560.n3.nabble.com/Spark-and-Stanford-CoreNLP-td19654.html

**Comment by mathewvino** [comment]
Thank you Prof. Christopher Manning. I am glad that I receive and email from you sir :). Yes i am looking into it.
Will update if i get any break through.
thanksvinoj

Date: Sat, 30 May 2015 08:40:22 -0700

**Comment by mathewvino** [comment]
Thanks  Christopher Manning
http://stackoverflow.com/questions/30484321/spark-partition-issue-with-stanford-nlp/30548032#30548032

I am doing the same way as it mentioned.
 When i tried with tokenize","ssplit","pos", there is no issues 200 partition is getting the output less than 30 minutes for almost a 1 million data and  can see the output.
But when I tried with tokenize","ssplit","pos","parse" and then set the parse model props.put("parse.model", "tagger/englishSR.ser.gz"), I am getting this out of memory error. its running on 64 bit machine with XX:MaxPermSize=1024m and i tried with 2048 but no luck.thanks for looking into it.
i used the shift reduce parser instead of the default bcz some of the input text is very long
I think the parse and the shift model I am passing is getting this issue and its take a lot of time
Here is the memory i tried  -- THis one is throwing out of memory error
spark.executor.memory=32gnumPartitions=200spark.cores.max=42 spark.executor.instances=8spark.executor.cores=6spark.storage.memoryFraction=1XX:MaxPermSize=1024m

The below one works for me for the "PARSE" with 200 partition but it took 2 hours and 30 minutes. The memory i use is 80g.  I am expecting it should done with less that 30 minutes for  1 million data but it takes 2 hours and 30 minutes

spark.executor.memory=80gnumPartitions=200spark.cores.max=42 spark.executor.instances=8spark.executor.cores=6spark.storage.memoryFraction=0.6XX:MaxPermSize=2048m

Thanksvinoj


From: vinojmathew@hotmail.com
To: reply@reply.github.com; corenlp@noreply.github.com
Subject: RE: [CoreNLP] Spark partition issue with Stanford NLP (#77)
Date: Sun, 31 May 2015 00:09:15 -0700




Thank you Prof. Christopher Manning. I am glad that I receive and email from you sir :). Yes i am looking into it.
Will update if i get any break through.
thanksvinoj

Date: Sat, 30 May 2015 08:40:22 -0700

**Comment by sebschu** [comment]
I don't think there is anything wrong. Parsing requires a lot more time and memory than POS tagging so it is expected that it takes significantly longer and that you have to give your VM more memory. In case you are parsing noisy data consider using the `parse.maxlen` option which prevents the parser from trying to parse unreasonable long sentences (which are typically not well-formed anyways).

**Comment by gangeli** [comment]
(Also, setting memory in Java is -mx rather than -XX:MaxPermSize. Though, spark.executor.memory might handle this for you already. The shift reduce models take a lot of memory, so you should set this to a few GB. For example, -mx4g)

**Comment by mathewvino** [comment]
Thanks Sebastin. I have to do the parse for long sentence cuz i have to do the sentiment calculation,for that parse is required.if  I use with parse.maxlen then can i get the sentiment correctly for that text.
thanksvinoj
Date: Mon, 1 Jun 2015 23:06:37 -0700

**Comment by mathewvino** [comment]
Thanks Gabor
-XX:MaxPermSize=1024m-Xms32768m -Xmx32768m 
when I pas the executor memory as 32 g  and i check each node the xms and xmx is set as 32 gig on each  node.

nohup /usr/bin/spark-submit --class com.xxxxx.customer360.pipeline.jobs.SocialMediaPipeline --master yarn-client --driver-memory 16g --conf spark.executor.memory=32g --conf numPartitions=200 --conf spark.shuffle.consolidateFiles=true --conf spark.storage.memoryFraction=1  --conf spark.executor.extraJavaOptions="-Dsun.io.serialization.extendedDebugInfo=true -Djava.io.tmpdir=/dev/shm -XX:MaxPermSize=1024m" --conf spark.executorEnv.LD_LIBRARY_PATH="/usr/local/lib/lexalytics/salience-5.2.0.7724/salience/lib" --conf spark.cores.max=42 --conf spark.executor.instances=8 --conf spark.executor.cores=6 --conf spark.worker.cleanup.enabled=true --conf spark.home=/etc/spark --conf spark.akka.frameSize=100 --conf spark.akka.threads=6 --conf spark.worker.timeout=600 --conf spark.akka.timeout=200 --conf input.string=/user/vmatthew/socialpipeline/input/temp.csv --conf outputPath=/user/vmatthew/socialpipeline/output1 /home/vmatthew/socialpipleline/social-pipeline.jar > /home/vmatthew/social_pipeline.log 2>&1 &

When I increase the partition each job to finish the task is taking lot of time for the parse( which uses shift reduce parser)
thanks for the helpvinoj

Date: Mon, 1 Jun 2015 23:16:19 -0700

**Comment by mathewvino** [comment]
Hi there,
could you please help me with issue. I don't have nay clue when this error happen
Any explanation or possible scenarios when this error can happen.
Any help is really appreciated.

http://stackoverflow.com/questions/30468010/error-annotator-sentiment-requires-annotator-binarized-trees
  
    
    
  
  

thanksvinoj

**Comment by J38** [comment]
If you get an error related to the sentiment annotator needing binary trees, you should be able to fix this with:

props.setProperty("parse.binaryTrees", "true");

The `sentiment` annotator requires binary versions of the constituency tree.
