### ISSUE TITLE
download page has outdated link

### ISSUE THREAD

**Issue by AngledLuffa** [stanfordnlp/CoreNLP#773]
https://stanfordnlp.github.io/CoreNLP/download.html references

wget http://nlp.stanford.edu/software/stanford-corenlp-full-2018-01-31.zip

for example, instead of 

http://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip

**Comment by J38** [comment]
Ok you scared me really bad for a second, but you don't mean the big red buttons.  I'll fix those tutorial links, I guess anyone who has been downloading via wget has been getting an outdated version all these months...
