### ISSUE TITLE
Change directory for output file

### ISSUE THREAD

**Issue by humehta** [stanfordnlp/CoreNLP#774]
How can I specify a particular directory to create my output of Coref in ?
I am executing the following command:
java -Xmx5g -cp C:\Users\harsh\CoreNLP\stanford-corenlp-full-2018-02-27\stanford-corenlp-3.9.1.jar;C:\Users\harsh\CoreNLP\stanford-corenlp-full-2018-02-27\stanford-english-corenlp-models-current.jar;* edu.stanford.nlp.pipeline.StanfordCoreNLP -props C:\Users\harsh\CoreNLP\src\edu\stanford\nlp\coref\properties\deterministic-english.properties -file C:\Users\harsh\public_mm\public_mm\metamap\transformed_openie_output.txt

**Comment by manning** [comment]
With the flag `-outputDirectory`. 

See: https://stanfordnlp.github.io/CoreNLP/cmdline.html
