### ISSUE TITLE
Correct Version Number for POM (3.9.1-->3.9.2)

### ISSUE THREAD

**Issue by Aevyz** [stanfordnlp/CoreNLP#775]
Hey, it appears that the version number of the regular [pom.xml](https://github.com/stanfordnlp/CoreNLP/blob/master/pom.xml#L5) file is `3.9.1` rather than `3.9.2` as shown in the [Gradle](https://github.com/stanfordnlp/CoreNLP/blob/master/build.gradle#L14) and the [Pom Java 11](https://github.com/stanfordnlp/CoreNLP/blob/master/pom-java-11.xml). 

Furthermore [this](https://github.com/stanfordnlp/CoreNLP/blame/master/README.md#L41) line in the Readme needs updating to at least version `3.9.1` as `mvn package` lists version as of current `3.9.1` (or just add some insert version number here comment).

**Comment by J38** [comment]
We're still working on updating everything, including the Maven release.  Should be done before Monday.
