### ISSUE TITLE
Stanford nlp.ner() giving: No JSON object could be decoded

### ISSUE THREAD

**Issue by AnilJagtap036** [stanfordnlp/CoreNLP#779]
I downloaded stanford on local and trying to parse emails. But whenever i'm passing documents/text to **stanfordcorenlp.ner()** function then it's returning **No JSON object could be decoded** exception.

And sometimes it's work fine for same text/emails.

Getting Exception for following code:
   
 `
    try:

       classified_text = nlp.ner(text)

    except Exception, e:

       print "Exception is : ", e`

I didn't get why it's not working and returning **No JSON object could be decoded** most of the time and sometime it's giving result for same text.

**Comment by J38** [comment]
What Python library are you using?

**Comment by AnilJagtap036** [comment]
I'm using 3.9.2 version.
Above exception I was getting because of Memory issue. After I increased RAM memory upto 10GB then it's start working fine
