### ISSUE TITLE
Annotator “sentiment” requires annotator “binarized_trees”‏

### ISSUE THREAD

**Issue by mathewvino** [stanfordnlp/CoreNLP#78]
could you please help me with issue. I don't have any clue when this error happen

Any explanation or possible scenarios when this error can happen.

Any help is really appreciated.

i am getting this error.Any idea when this error can happen
props.setProperty("annotators",
                            "tokenize, ssplit, pos, parse,sentiment");

5/06/07 08:18:06 WARN TaskSetManager: Lost task 95.0 in stage 18.0 (TID 137, tlbd1d03.tms.xxxx.com): java.lang.IllegalArgumentException: annotator "sentiment" requires annotator "binarized_trees"
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:300)
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:129)
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:125)

http://stackoverflow.com/questions/30468010/error-annotator-sentiment-requires-annotator-binarized-trees

thanks
vinoj

**Comment by mathewvino** [comment]
For the Sentiment i need only the pos and parse annotator and thats my understanding.I am not sure if this is realted to something else. Any idea when this error can happen thanks

**Comment by AngledLuffa** [comment]
It is supposed to detect the sentiment annotator and automatically include
binarized trees if needed.  It could be the specific text you use triggers
some bug.  What text is triggering this error?

**Comment by mathewvino** [comment]
thanks. i need to figure this out cuz currently i am using around 1 million data(input text) to process.So you saying that this could be the input text that i am passing to the annotator. I am not seeing this issue all the time when running with spark and scala. The problem comes when i increase the partition.
Let me check
