### ISSUE TITLE
Tokenizer incorrectly assign single quote to apostrophe

### ISSUE THREAD

**Issue by rosun82** [stanfordnlp/CoreNLP#780]
When dealing with partial segment, such as [He'll], [She'll], the tokenizer treats ['] as opening single quote. Interestingly, if we write [He'll, She'll], then the first one is treated as [will], while the second one is treated as opening single quote.

![image](https://user-images.githubusercontent.com/6566533/47049576-8c874980-d152-11e8-85d5-714a7e075c33.png)

**Comment by rosun82** [comment]
And to add to this, it seems the tokenizer disregard the opening single quote.

E.g., 'farmers' market. first single quote marked as ``, second marked as POS.

**Comment by manning** [comment]
Thanks for the report. First case is definitely a bug. But it only happens at end of string. That is, tokenization is correct if you give it:

    She'll remember.
    He'll forget

which is probably why we never noticed.

The second one is complex. 

    farmers'

is the correct possessive plural of "farmer", so it's not too surprising that it would tend to POS tag it as a "POS" in "farmers' market"....

**Comment by manning** [comment]
I'm going to close this. First one is now fixed (in HEAD). Second one it isn't clear how to fix within the current architecture. NLP Isn't perfect.
