### ISSUE TITLE
stanford-corenlp-3.9.2.jar don't contain the class HybridCorefAnnotator

### ISSUE THREAD

**Issue by demeiyan** [stanfordnlp/CoreNLP#785]
I download stanford-corenlp-3.9.2.jar and try to to run Chinese Coreference . But I don't find the class HybridCorefAnnotator and the [git repos](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/HybridCorefAnnotator.java) contanins the class.

**Comment by J38** [comment]
Hi that class has been deprecated.  If you run the pipeline with the default Chinese properties file it will run the Chinese coreference.

`java -cp "*" -Xmx14g edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-chinese.properties -file example.txt -outputFormat text`
