### ISSUE TITLE
Issue with EntityMentionsAnnotator when using custom NER and Mention annotations

### ISSUE THREAD

**Issue by PhdStudent2015** [stanfordnlp/CoreNLP#786]
Hi,
I want to draw your attention to a little bug that I discovered in the EntityMentionsAnnotator  class.  I was trying to avoid any overlap with existing NER tags and entity mentions. So, I created custom NER annotations which I used with tokensregex annotator. Then, I tried to set up the EntityMentionsAnnotator to work with my new NER tags. This is the configuration I used :

```
//The full pipeline

Properties props = new Properties();
props.put("annotators", "tokenize, ssplit, pos, lemma, ner, entitymentions, tokensregex, parse, depparse, coref, kbp");
props.setProperty("customAnnotatorClass.tokensregex", "edu.stanford.nlp.pipeline.TokensRegexAnnotator");
props.setProperty("tokensregex.rules", "skills.rules,pattern.rules");
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
pipeline.annotate(document);
		
//the custom Entity Mentions annotator

Properties mprops = new Properties();
mprops.setProperty("mymention.nerCoreAnnotation", "com.nlptools.pipeline.ie.MyCoreAnnotations$MyNamedEntityTagAnnotation" ) ;
mprops.setProperty("mymention.nerNormalizedCoreAnnotation", "com.nlptools.pipeline.ie.MyCoreAnnotations$MyNamedEntityTagAnnotation" ) ;
mprops.setProperty("mymention.mentionsCoreAnnotation", "com.nlptools.pipeline.ie.MyCoreAnnotations$MyMentionsAnnotation") ;
EntityMentionsAnnotator mentionsAnnotator = new EntityMentionsAnnotator("mymention", mprops) ;
mentionsAnnotator.annotate(document);
```

I succeeded to get the list of the new customized entity mentions at the sentence level (by calling `sentence.get(MyCoreAnnotations.MyMentionsAnnotation.class)`), but the mentions did not appear at the document level (when calling `document.get(MyCoreAnnotations.MyMentionsAnnotation.class)`). 
I figured out that the problem came from line 319 at the EntityMentionsAnnotator.java (latest version at Github)
```
// build document wide entity mentions list
...
for (CoreMap entityMention : sentence.get(CoreAnnotations.MentionsAnnotation.class)) {
```
which I replaced by with 

`for (CoreMap entityMention : sentence.get(mentionsCoreAnnotationClass)) `

In fact, `mentionsCoreAnnotationClass` is  the class name of the entity mention annotation set up at the constructor level of the EntityMentionsAnnotator. Now, all works fine for me.  I’m not really very experienced with CoreNLP, but I hope  that my comment would somehow help improve the CoreNLP API.

**Comment by J38** [comment]
Ok this should be resolved now, thanks for pointing this out.
