### ISSUE TITLE
Set up CoreNLPServer on Multiple Languages

### ISSUE THREAD

**Issue by RachelKrh** [stanfordnlp/CoreNLP#787]
I have few questions on setting up CoreNLP server for multi-language support.

1. Can we load multiple language models on the same CoreNLPServer instance? 
     I am using the below command to start the server
     sudo su nlp -c "/usr/bin/authbind --deep java -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir=/home/ice-ner-dev/CoreNLP_NER/corenlp -cp "$CLASSPATH" -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:SoftRefLRUPolicyMSPerMB=100 -mx20g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -preload "tokenize,ssplit,pos,lemma,ner" -port 9001 -timeout 75000 -serverProperties StanfordCoreNLP-spanish.properties"

     Using the above command, only the Spanish model gets loaded. If serverProperties are not specified, 
    only the English model gets loaded. Is there a way we can load all the models into the same server 
     instance?

2. For custom NER training, I am using the command below.
      java -cp "$CLASSPATH"  edu.stanford.nlp.ie.crf.CRFClassifier -prop MedicalAssistant.prop
      How do we specify the language here? Don't we want the POS and other features to be used based 
      on the language?

3.  I loaded the spanish model during server startup and ran the train command above. Use the https://pypi.org/project/stanford-corenlp/ for getting the results from the CoreNLPServer. The entity was detected correctly but the POS seems incorrect for some words. eg: In the sentence "Hola mi nombre es Rachel", Hola was taken as a Proper Noun which is not correct. Please see the output below

Hola mi nombre es Rachel
{u'sentences': [{u'tokens': [{u'index': 1, u'word': u'Hola', u'lemma': u'hola', u'pos': u'PROPN', u'characterOffsetEnd': 4, u'characterOffsetBegin': 0, u'originalText': u'Hola', u'ner': u'O'}, {u'index': 2, u'word': u'mi', u'lemma': u'mi', u'pos': u'DET', u'characterOffsetEnd': 7, u'characterOffsetBegin': 5, u'originalText': u'mi', u'ner': u'O'}, {u'index': 3, u'word': u'nombre', u'lemma': u'nombre', u'pos': u'NOUN', u'characterOffsetEnd': 14, u'characterOffsetBegin': 8, u'originalText': u'nombre', u'ner': u'O'}, {u'index': 4, u'word': u'es', u'lemma': u'e', u'pos': u'VERB', u'characterOffsetEnd': 17, u'characterOffsetBegin': 15, u'originalText': u'es', u'ner': u'O'}, {u'index': 5, u'word': u'Rachel', u'lemma': u'rachel', u'pos': u'PROPN', u'characterOffsetEnd': 24, u'characterOffsetBegin': 18, u'originalText': u'Rachel', u'ner': u'O'}], u'index': 0, u'entitymentions': []}]}

**Comment by J38** [comment]
1.) If you want one server to handle multiple languages, you'll need to switch which models are being used with the request.  It will cache the different models, and switch between them as it handles each request.

2.) Here is some documentation about the NER training:

- https://stanfordnlp.github.io/CoreNLP/ner.html
- https://nlp.stanford.edu/software/crf-faq.shtml#a
- https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/ie/NERFeatureFactory.html

If you want POS tags as features, you will need to supply them in the training data, and specify which column in your training data is the POS tags.  So in your training data you would supply Spanish POS tags.  When running a pipeline with your trained model, you will need to use the same POS tagger you used for the training data.

3. Unfortunately this is just an error with the POS tagger, it is not perfect and makes mistakes.  We are actually about to release some new part-of-speech and dependency parsers in Python (though this will require a GPU to use).

Let me know if you have any more questions !

**Comment by J38** [comment]
For instance when training your NER model with Spanish POS tags, you'd want this line:

```
map = word=0,answer=1,tag=2
```

This would work if the third column of your training file has the POS tags.
