### ISSUE TITLE
The dcoref link points to a nonexistent page on the annotator dependencies page

### ISSUE THREAD

**Issue by CPerry26** [stanfordnlp/CoreNLP#788]
On the annotator dependencies page located [here](https://stanfordnlp.github.io/CoreNLP/dependencies.html), the dcoref link points to a page which doesn't exist (causing a 404 error). If the proper annotator is coref and not dcoref (which I believe it is), I think it should point to https://stanfordnlp.github.io/CoreNLP/coref.html and not https://stanfordnlp.github.io/CoreNLP/dcoref.html. 

I couldn't find a repo for the website itself so I apologize if this is in the wrong spot!

**Comment by J38** [comment]
Thanks for pointing this out, I updated the page.  You can still use the legacy `dcoref` annotator but in general I would recommend using the `coref` annotator.
