### ISSUE TITLE
Coreference resolution: does not extract chains on some sentences

### ISSUE THREAD

**Issue by fhamborg** [stanfordnlp/CoreNLP#791]
Using the latest CoreNLP server and the neural models in the coreference resolution module, the following two sentences do not return any chain, besides I think they the coref resolution should ideally find one chain with two mentions:
```
Taxes on bill not revised after new financial year. Taxes applicable for last month to be recalculated.
```

**Comment by J38** [comment]
Unfortunately coref is nowhere near a solved problem, keep in mind even the best systems only score a 70 out of 100 on the standard conference metric.  I believe our system also has struggles with mentions like "taxes".  It is better for "Joe Smith" --> "Smith" style coref connections.
