### ISSUE TITLE
Sentiment model training for different domain

### ISSUE THREAD

**Issue by pa-cloud** [stanfordnlp/CoreNLP#793]
Hi
I tried following for generating model for my domain (product reviews) and it seems to be working (with a toy dataset). 

1. Generate sentiment-tree for train and dev data (using "-output PENNTREES" as mentioned at https://stackoverflow.com/a/42917906 )

2. The resulting tree needed some manual modifications because the "unseen" words were treated as neutral(2)
For example I had to modify below sentence: 
(2 (2 (2 Vendor) (2 (2 selling) (2 (2 defective) (2 products)))) (2 .))
By changing sentiment score for word "defective" (and its parents)
(1 (1 (2 Vendor) (1 (2 selling) (1 (1 defective) (2 products)))) (2 .))

3. Then I trained my model using the pruned train/dev files
java -mx8g edu.stanford.nlp.sentiment.SentimentTraining -numHid 25 -trainPath train.txt -devPath dev.txt -train -model my.model.ser.gz

4. Used my model for sentiment analysis
java -cp "*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -stdin -output PENNTREES -sentimentModel my.model.ser.gz

I have some questions regarding training data:
1. Yeah, it does require some careful manual score replacement, but the standard approach is not understandable anyway  (https://github.com/stanfordnlp/CoreNLP/issues/742). So is this approach fine?
2. Should I train with just my domain specific input or will I be better off (will need to prepare smaller input) if I append my train/dev sentences to the supplied train/dev files
3. I notice there were some 'trivial' misses due to "unseen" words: like above example of "defective". If appending is fine, should I append a bunch of single-word 'sentences' (defective, sleek, classy etc) to get a easy improvement in accuracy. (just because it will be much easier/faster to prepare this training data) 

Kindly help

**Comment by J38** [comment]
Just to be clear, you have to completely human score your training and dev data.  You could do this by running the model we provide and fixing mistakes, but you there is no way to get around human review of every single sentence in your custom training and dev data.

It is unknown what will give you best results. You will need to experiment with training on just your custom product review data or you could add unrelated info.

It is plausible adding basic examples with unknown words will help out.  Once again you will have to experiment to see what results you get.

**Comment by pa-cloud** [comment]
Thanks for the response. Sure, I understand the human review part.
Will sure experiment as suggested...thanks.
