### ISSUE TITLE
Clique in Stanford NER

### ISSUE THREAD

**Issue by nvlong198** [stanfordnlp/CoreNLP#794]
I am reading through the code for NER in CoreNLP and am unable to understand what a "Clique" is and why there are multiple feature extractors inside the NERFeatureFactory.getCliqueFeatures(). Can someone help me understand: 

**1. What is a clique?** 
**2. Why are there multiple helper methods to calculate the features for different types of cliques (cliqueX, cliquecp2c, etc.) ?** 

Thanks!

**Comment by manning** [comment]
Our NER code draws terminology, etc. from the general approach to undirected probabilistic graphical models (whereas much other work, including the original CRF paper, give a matrix-based presentation that only supports 1st order CRFs. You can find a presentation from this perspective in Kevin Murphy's book here: https://www.cs.ubc.ca/~murphyk/MLbook/pml-print3-ch19.pdf

_However,_ that chapter doesn't define a clique…. Unfortunately, you're already meant to know. A clique is any all-pairs connected set of nodes (including just a single node). See here: https://en.wikipedia.org/wiki/Clique_(graph_theory).

The idea is that you can place potential functions (weights) on just the class of the current word, the pair of the current and previous word, the triple of the current and previous two words, etc.
