### ISSUE TITLE
Provide releases on GitHub?

### ISSUE THREAD

**Issue by aendrew** [stanfordnlp/CoreNLP#797]
Hi!

I'm working on some Docker images involving CoreNLP which has unfortunately involved me having to download the latest release and the srparser models several times, with each attempt taking upwards of 40 minutes due to the speed of the main nlp.stanford.edu mirror.

In the interests of enabling people to download it faster (as well as reducing load on your servers!), one idea might be to put published releases on GitHub, using it as a secondary mirror? Just a thought!

**Comment by J38** [comment]
This sounds like a reasonable idea, I'll talk it over with Chris.

**Comment by aadrian** [comment]
This shouldn't be that difficult, since there are many open source projects that user Travis to trigger on a new Version Tag the publishing of build artifacts.

**Comment by nimasTT** [comment]
Hi, 
Is it possible to provide also a sample Dockerfile to build a multilingual CoreNLP Server from GitHub? 
The Links and Documentations on https://stanfordnlp.github.io/CoreNLP/ are outdated.

**Comment by AngledLuffa** [comment]
FWIW there are now releases on huggingface:

https://huggingface.co/stanfordnlp/CoreNLP/tree/main

There are also repos for the various model packages.  Hopefully that addresses any future bulk download issues
