### ISSUE TITLE
Requesting model for Hindi language

### ISSUE THREAD

**Issue by knightcube** [stanfordnlp/CoreNLP#801]
How can I develop a model for Hindi language for CoreNLP?

**Comment by J38** [comment]
Which annotators do you want?  With the CoNLL 2018 data, you can train a tokenizer, part-of-speech tagger and dependency parser.  You will have to come up with rules for sentence splitting, and you will have to come up with your own data for things like named entity recognition, coreference, or relation extraction.

Here are some resources that could help:

**CoNLL 2018 data:** http://universaldependencies.org/conll18/data.html

**Train a segmenter:** https://nlp.stanford.edu/software/segmenter.shtml

**Train a part-of-speech model:** https://nlp.stanford.edu/software/pos-tagger-faq.html#train

**Train a dependency parsing model:** https://stanfordnlp.github.io/CoreNLP/depparse.html
