### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP

### ISSUE THREAD

**Issue by UTKGANDHI** [stanfordnlp/CoreNLP#802]
I'm using Stanford NLP for sentiment analysis in my sbt project. I am getting the error when I run the project jar file on AWS EMR cluster, while it perfectly runs in the IntelliJ IDE.

**Comment by J38** [comment]
This is an error with your CLASSPATH, you need to have all of the jars in the CLASSPATH from IntelliJ IDE in the CLASSPATH on your AWS setup as well.
