### ISSUE TITLE
Stanford POS French Model: confusion between Homonym NOUN and VERB

### ISSUE THREAD

**Issue by zsellami** [stanfordnlp/CoreNLP#806]
**The POS French Model not recognize Homonym verb noun**
Elle équipe la maison -> équipe is a verb but the POS tagger suggest NOUN
Elle danse tout le temps -> danse is a verb but the POS tagger suggest NOUN
elle est assemblée de cette façon -> assemblée is a verb but the POS tagger suggest NOUN

**Comment by J38** [comment]
The POS model is a trained statistical model that will make errors from time to time.  The accuracy of the best English tagging model is only 97.8%, and the English Java code base is using older algorithms that are more in the 97% range.  The accuracies are lower on French models I believe.  Also, out of curiosity, which POS model are you using?

**Comment by zsellami** [comment]
Thank's for the answer. I'am using the version 3.9.2 of the french model. The solution, is to increase the french corpus with more annotated sentences to obtain more accuracy, I think.
Is it possible to give me the link for the french corpus using for learning, and how to use CoreNLP to generate a POS Tag Model ?
