### ISSUE TITLE
Cannot get BinarizedTreeAnnotation

### ISSUE THREAD

**Issue by nooralahzadeh** [stanfordnlp/CoreNLP#807]
Hi,
I cannot get BinarizedTreeAnnotation even with setting parameter in Stanford CoreNLP API:
"parse.binaryTrees", "true"!
Version: stanford-corenlp-full-2017-06-09
Any advice
Thanks for your help

**Comment by slliao445** [comment]
> Hi,
> I cannot get BinarizedTreeAnnotation even with setting parameter in Stanford CoreNLP API:
> "parse.binaryTrees", "true"!
> Version: stanford-corenlp-full-2017-06-09
> Any advice
> Thanks for your help

I also have this question. Did you get the solution for get binary parse tree from the parser?

**Comment by J38** [comment]
I will make the annotation more accessible from the server.  Right now I think it's only accessible in Java code.

**Comment by nooralahzadeh** [comment]
I used NLTK to have binary parse tree from the result of the constituent tree of Stanford CoreNLP:
`def binarize(constituentTree):
    t=Tree.fromstring(constituentTree)
    # collapse
    Tree.collapse_unary(t,collapsePOS=True, collapseRoot=True)
    # chomsky normal form transformation
    Tree.chomsky_normal_form(t)
    str=t._pformat_flat(nodesep='', parens='()', quotes=False)
    return str
`

**Comment by slliao445** [comment]
> I used NLTK to have binary parse tree from the result of the constituent tree of Stanford CoreNLP:
> `def binarize(constituentTree): t=Tree.fromstring(constituentTree) # collapse Tree.collapse_unary(t,collapsePOS=True, collapseRoot=True) # chomsky normal form transformation Tree.chomsky_normal_form(t) str=t._pformat_flat(nodesep='', parens='()', quotes=False) return str `

It works! Thank you very much!

**Comment by J38** [comment]
I add the binary tree output to the .json output.

**Comment by J38** [comment]
I also added it to the text output.  And all along it has been available in the the protobuf output.
