### ISSUE TITLE
corefannotator "coref" requires annotation "CategoryAnnotation".

### ISSUE THREAD

**Issue by crapthings** [stanfordnlp/CoreNLP#811]
java.lang.IllegalArgumentException: annotator "coref" requires annotation "CategoryAnnotation". The usual requirements for this annotator are: tokenize,ssplit,pos,lemma,ner,depparse

when i try online chinese demo, it prints this error?

**Comment by aseaday** [comment]
I also meet this problem

**Comment by aseaday** [comment]
@crapthings Just use the command line mode, It works!

**Comment by leii13** [comment]
I use English version but I had the same error. Use annotationins in this order: "tokenize,ssplit,pos,lemma,ner,parse,depparse,coref" - for me it works.

**Comment by RumRaisins** [comment]
In 2021, this problem still exists！

**Comment by AngledLuffa** [comment]
Thanks for calling our attention to this.  The next version will know how
to tell you if it needs parse or depparse based on the annotations it
uses.  It should be noted that the default properties already correctly
handle the requirements.
