### ISSUE TITLE
Tokenization with UTF-8 literals and emoticons

### ISSUE THREAD

**Issue by devikasondhi** [stanfordnlp/CoreNLP#812]
Hello,

I realize that while the tokenizer in the CoreNLP lib. (version 3.9.2) does support tokenizing on the emojis, there is no support for tokenizing on emoticons, or also for UTF-8 literals. Sharing few examples below:
Input 1: `"@Insanomania They do... Their mentality doesn't :("` tokenizes as `["@Insanomania", "They", "do", "...", "Their", "mentality", "does", "n't", ":" ,"("]` while the expectation on the `:(` was to be treated as a single token.

Input 2: `"\xabNow that I can do.\xbb"` tokenizes as `["\", "xabNow", "that", "I", "can", "do", ".", "\", "xbb"]`

**Comment by devikasondhi** [comment]
I also came across another case of tokenization on escape characters that isn't handled well.
Input:` "Good muffins cost $3.88\nin New York."` tokenizes as `["Good", "muffins", "cost", "$", "3.88", "\", "nin", "New", "York", "." ]` with the newline character(`'\n'`) not handled well

**Comment by manning** [comment]
[Belatedly cleaning up some old issues]
The tokenizer should recognize simple emoticons, but there was an issue at end of string/file; now fixed.
Things like `\xab` are features of programming language escaping not Unicode. They are not recognized by the tokenizer. Normally a '\n' in text entry will already have been interpreted as a newline character.
