### ISSUE TITLE
Issue with sentiment analyzer

### ISSUE THREAD

**Issue by devikasondhi** [stanfordnlp/CoreNLP#813]
Hello,

I recently came across an interesting example where sentiment analysis on words containing negative words (like 'not', 'never') need not always indicate a negative sentiment. Example:
`"Sentiment analysis with VADER has never been this good."` or `"This is not at all bad."`
These should be tagged as a Positive sentiment. However, the default analyzer of the CoreNLP library marks them as Negative.

P.S. I've been using the web interface of CoreNLP (http://corenlp.run/), which is great for all the visualization that it provides :-)

**Comment by J38** [comment]
Thanks for providing this example!
