### ISSUE TITLE
PTBTokenizer normalizeOtherBrackets option is changin CoreLabel.after() and CoreLabel.before()

### ISSUE THREAD

**Issue by mahdiman** [stanfordnlp/CoreNLP#814]
As per the StanfordCoreNLP [documentation for CoreLabel](https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/ling/CoreLabel.html), The functions **after()** and **before()** should return white space strings between the token and the next/previous tokens respectively.
However, they return an empty string always even if there are some white spaces when the tokenizer option **normalizeOtherBrackets** is equal to **false**.

**Comment by manning** [comment]
I'm sure it isn't the normalizeOtherBrackets option determining behavior here.

Rather, I think it is the option **invertible**. Only an invertible tokenizer stores before() and after().
