### ISSUE TITLE
Difference between Stanford POS tagger and POS tagger from Stanford Parser

### ISSUE THREAD

**Issue by aafreenart** [stanfordnlp/CoreNLP#815]
What is the difference between Stanford POS tagger and POS tagger in Stanford Parser? I am getting different results from these two services for the same sentence. 

**Example:** 

**Fires** are the high-temperature phenomenon of relatively local extent.

Result from Pos tagger: 

The term **Fires** has captured as **VBZ**
![image](https://user-images.githubusercontent.com/39255595/50591258-a9f7c400-0eb4-11e9-80d6-3de0ae4233aa.png)

Result from Stanford parser POS tagger:

The term **Fires** has captured as **NNP**
![image](https://user-images.githubusercontent.com/39255595/50591365-44f09e00-0eb5-11e9-96d1-a8b133d933c2.png)

**Comment by mcavdar** [comment]
http://corenlp.run/ works on Corenlp 3.9.2 (updated 2018-11-29) but http://nlp.stanford.edu:8080/parser/ is based on model created before 2016-09-12. It seems that POS tagger models are not same because of different CoreNLP versions.

**Comment by J38** [comment]
The difference is that the parser demo uses the parsing model itself to predict the part-of-speech tags, whereas the full pipeline demo uses the part-of-speech tagger.
