### ISSUE TITLE
I want to modify NER 3 class tagger to recognize some specific words to be PERSON entity. 

### ISSUE THREAD

**Issue by sonsus** [stanfordnlp/CoreNLP#816]
I want to customize the CoreNLP NER functionality for my research experiment.   

What I want to add is some explcit NER rule to current NER module which will enable the module recognize several mentioning words like father, grandmother and etc. as <code>PERSON</code> entity. (I have a set of several word lists for this) 

Could you specify the part of the code I need to take a look at? Or is it impossible to do this because the NER taggers does not contain such a explicit rules checking for person names?

**Comment by J38** [comment]
There is a detailed description of the NER system here (including how to blend statistical and rule-based approaches):

https://stanfordnlp.github.io/CoreNLP/ner.html
