### ISSUE TITLE
Output encoding issue for the Stanford Parser

### ISSUE THREAD

**Issue by linhr** [stanfordnlp/CoreNLP#82]
It seems that the `-encoding` option in the Stanford Parser does not set output file encoding correctly. This causes problem on some Windows systems, where the parse tree are written using the system's default encoding Windows-1252, even if `-encoding UTF-8` is set.

On systems that the default file encoding is UTF-8, the problem can be reproduced in the following way. Suppose we want to parse a file (encoded in UTF-8) containing a single word "café".
```
$ cat sample-utf8.txt | hexdump -C
00000000  63 61 66 c3 a9 0a                                 |caf...|
00000006
```
We run the parser after setting the `file.encoding` property in Java to the Windows default.
```
$ java -mx150m -Dfile.encoding=Cp1252 -cp stanford-parser.jar edu.stanford.nlp.parser.lexparser.LexicalizedParser -encoding UTF-8 -outputFormat penn edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz sample-utf8.txt 2> /dev/null | hexdump -C
00000000  28 52 4f 4f 54 0a 20 20  28 4e 50 20 28 4e 4e 50  |(ROOT.  (NP (NNP|
00000010  20 63 61 66 e9 29 29 29  0a 0a                    | caf.)))..|
0000001a
```
The content of the output is the same regardless whether `-encoding UTF-8` is passed or not. Note that the byte representation for the character "é" is wrong, which should be `c3 a9` in UTF-8 rather than `e9`. The problem exists either when the result is written to stdout, or to files via `-writeOutputFiles`.

I guess the problem is related to [Line 83](https://github.com/stanfordnlp/CoreNLP/blob/c922558c890c08aaabf5ec29aa873b7fb0a1a59d/src/edu/stanford/nlp/parser/lexparser/ParseFiles.java#L83), [Line 151](https://github.com/stanfordnlp/CoreNLP/blob/c922558c890c08aaabf5ec29aa873b7fb0a1a59d/src/edu/stanford/nlp/parser/lexparser/ParseFiles.java#L151) and [Line 173](https://github.com/stanfordnlp/CoreNLP/blob/c922558c890c08aaabf5ec29aa873b7fb0a1a59d/src/edu/stanford/nlp/parser/lexparser/ParseFiles.java#L173) in  ParseFiles.java, where `op.tlpParams.getOutputEncoding()` is not used to determine the encoding for output streams.

**Comment by manning** [comment]
Thanks for the report. I agree that this is broken. Will fix for the next release.  This definitely worked right at one point, but I guess it got broken. Not enough tests.... 

It's not immediately obvious to me that the lines you point out are broken, though, since if you look at the implementation of pw() in `AbstractTreebankParserParams`, then it should be using the encoding. But clearly broken somewhere.

**Comment by manning** [comment]
Okay, solved. Other languages (where it had been tested) worked fine with character encodings, but, for English, EnglishTreebankParserParams had a useless overwride of pw(OutputStream) which ignored character encodings....

**Comment by linhr** [comment]
Thanks for fixing this!
