### ISSUE TITLE
Stop server prints to the console

### ISSUE THREAD

**Issue by nadavb** [stanfordnlp/CoreNLP#820]
I tried adding the `-quiet` to the Java command line when running the StanfordCoreNLPServer.
I suppressed the prints of the text input, but I still get:
`[/127.0.0.1:60508] API call w/annotators tokenize,ssplit,pos,parse`
printout.
Prints may slow down and reduce performance. Is there way to stop these prints?

**Comment by neilnelson** [comment]
On linux you can preface a command with 'nohup' that will send all output to a file called 'nohup.out'.

https://www.maketecheasier.com/nohup-and-uses/

Or you can also add ' &> /dev/null' to the end of the command to discard all output.

https://unix.stackexchange.com/questions/70963/difference-between-2-2-dev-null-dev-null-and-dev-null-21

**Comment by nadavb** [comment]
That's not a good solution, as it will hide errors as well.
I just want to remove all the 
[/127.0.0.1:60508] API call w/annotators tokenize,ssplit,pos,parse
prints.
I want to see only errors

**Comment by J38** [comment]
How are you starting up the server?  I am not seeing this issue when I run it with the `-quiet` option.  Also, how are you making calls to the server?

**Comment by nadavb** [comment]
I start the server this way:

> java -Xmx4000m -cp "/usr/Stanford_CoreNLP/stanford-corenlp-3.9.1.jar" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9001 -timeout 3000 -threads 12 -serverProperties /usr/stanford-english-corenlp-2018-02-27-models/StanfordCoreNLP.properties -quiet -Dorg.slf4j.simpleLogger.defaultLogLevel=error

I am making calls to port 9001.

**Comment by J38** [comment]
I think you need to upgrade to 3.9.2.  The quiet feature was added between 3.9.1 and 3.9.2
