### ISSUE TITLE
Poor performance with Spanish parser?

### ISSUE THREAD

**Issue by ianbstewart** [stanfordnlp/CoreNLP#821]
Not sure where to post this but I've found that the Spanish sentence parsers are struggling with basic sentences, usually involving recursion. I provide an example below. I'm using the default parser available [here](http://nlp.stanford.edu/software/stanford-spanish-corenlp-2018-10-05-models.jar).

```
# in java
java -Xmx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties StanfordCoreNLP-spanish.properties -preload tokenize,ssplit,pos,ner -status_port 9003  -port 9003 -timeout 45000

# in python
from nltk.parse.corenlp import CoreNLPParser
parser = CoreNLPParser(url='http://localhost:9003', tagtype='ner')
test_sent = 'El número telefónico de Centro de Ayuda es el 123-456-7890.'
test_parse = next(parser.parse(parser.tokenize(test_sent)))
test_parse.pprint()
```

Output:
```
(ROOT
  (sentence
    (sn
      (grup.nom
        (DET El)
        (NOUN número)
        (ADJ telefónico)
        (ADP de)
        (PROPN Centro)
        (ADP de)
        (PROPN Ayuda)
        (VERB es)
        (DET el)
        (NOUN 123-456-7890)))
    (PUNCT .)))
```

In the provided tree I'm not sure why the entire sentence is being tagged as `grup.nom`. A similar problem happens with other sentences that are parsed as `interjeccio`.

**Comment by AngledLuffa** [comment]
Without going into the history of whatever caused this bug at the time, recent versions of CoreNLP put a reasonable parse tree on this sentence.
