### ISSUE TITLE
Wrong depedency structure while running corenlp locally.

### ISSUE THREAD

**Issue by saurv** [stanfordnlp/CoreNLP#824]
While generating dependency tree for below sentence , I am getting different dependencies structure with enhanced dependencies in comparison to the visualization I am getting  from [corenlp demo] (http://nlp.stanford.edu:8080/corenlp/process).  Seems like later one is the correct .  May I know, which version of corenlp, this demo website is using. 

**The board of directors of Accord new Group Limited announced that Dr. Shang Li has been re-designated as an executive director of the company, Dr. Jesse Zhixi Fang has been appointed as an independent non-executive director of the company, and Dr. Shang has resigned as a member of the remuneration committee of the company and Dr. Fang has been appointed as a member of the remuneration committee of the company.**

Thanks,
Saurabh

**Comment by AngledLuffa** [comment]
The corenlp demo is now at corenlp.run, and recently we've been putting the version at the top of the page.  It's currently one version behind...
