### ISSUE TITLE
[tokensregex] how to define a regular expression for matching multiple tokens?

### ISSUE THREAD

**Issue by ducalpha** [stanfordnlp/CoreNLP#829]
How to write a regular expression for matching multiple tokens?
I tried `(?m){n,m} /abc/` as mentioned in the [document](https://nlp.stanford.edu/software/tokensregex.html#Usage), but it does not work.

```
{ ruleType: "tokens",
  pattern: ([word:(?2){2,2}/Our company/]),
  action: Annotate($0, ner, "COMPANY"),
  result: "COMPANY_RESULT" }
```

The above rule causes an exception `edu.stanford.nlp.ling.tokensregex.parser.ParseException`.

**Comment by J38** [comment]
Hi there is an extensive write up on how to use TokensRegex here, with multiple examples:

https://stanfordnlp.github.io/CoreNLP/tokensregex.html

**Comment by ducalpha** [comment]
The document does not provide any example for matching multiple tokens using the `(?m){n,m} /abc/` syntax.

**Comment by J38** [comment]
```
[{word:/[A-Z][A-Za-z]+/}]{n,m}
```

Above is an example, and I've added it to the token sequence example list on the documentation page.  You can put n=0 to cover the case of the entire sequence being option.
