### ISSUE TITLE
Running edu.stanford.nlp.pipeline.StanfordCoreNLPServer without depparse yields dependencies

### ISSUE THREAD

**Issue by nadavb** [stanfordnlp/CoreNLP#830]
Running edu.stanford.nlp.pipeline.StanfordCoreNLPServer with tokenize,ssplit,pos,parse yields basicDependencies, enhancedDependencies, enhancedPlusPlusDependencies when I did not specify depparse.

However, when I do specify depparse, I  also get: basicDependencies, enhancedDependencies, enhancedPlusPlusDependencies, but with different results (different dependencies).

Should it be like that? If we don't specify the depparse annotation, what is the default dep parser we get?

**Comment by J38** [comment]
By default if the `parse` annotator is run, the dependency converter will also be run to generate the dependency parses.  If the `depparse` annotator is used, the neural dependency parse model will be run as well.

**Comment by nadavb** [comment]
Thanks, where is the 'default' dependency parser model file located? or is it 'built in' into the Java code?

**Comment by J38** [comment]
It's in Java code.  Whatever constituency parser model you have specified runs first, then the universal dependencies converter creates a dependency parse in a rule based fashion from the constituency parse.  

See `edu.stanford.nlp.trees.ud.UniversalDependenciesConverter`.  Small warning, we have recently been updating this to convert things to UD 2.0, so the current GitHub state is sort of a mess.  I would advise continuing to use 3.9.2 for the next few weeks.
