### ISSUE TITLE
CoreAnnotations.NumerizedTokensAnnotation

### ISSUE THREAD

**Issue by aafreenart** [stanfordnlp/CoreNLP#833]
I tried to annotate numbers in a sentence in below way. But, it didn't work.

https://github.com/stanfordnlp/CoreNLP/issues/199#issuecomment-223178447

Please check the below code:
```
props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner");
props.setProperty("ner.useSUTime", "false");
props.setProperty("ner.applyFineGrained", "false");
props.setProperty("ner.buildEntityMentions", "true");
pipeline = new StanfordCoreNLP(props);
Annotation annotation = new Annotation("There have been 43 presidents.");
pipeline.annotate(annotation);
foreach (CoreMap sent in annotation.get(typeof(CoreAnnotations.SentencesAnnotation)) as ArrayList)
{
         foreach (CoreMap token in sent.get(typeof(CoreAnnotations.NumerizedTokensAnnotation)) as ArrayList)
             {
                   //Always sent.get(typeof(CoreAnnotations.NumerizedTokensAnnotation)) returning null
             }
}
```

sent.keySet()
[edu.stanford.nlp.util.ArrayCoreMap.1]: {[class edu.stanford.nlp.ling.CoreAnnotations$TextAnnotation, class edu.stanford.nlp.ling.CoreAnnotations$CharacterOffsetBeginAnnotation, class edu.stanford.nlp.ling.CoreAnnotations$CharacterOffsetEndAnnotation, class edu.stanford.nlp.ling.CoreAnnotations$TokensAnnotation, class edu.stanford.nlp.ling.CoreAnnotations$SentenceIndexAnnotation, class edu.stanford.nlp.ling.CoreAnnotations$TokenBeginAnnotation, class edu.stanford.nlp.ling.CoreAnnotations$TokenEndAnnotation, class edu.stanford.nlp.ling.CoreAnnotations$MentionsAnnotation]}

NumerizedTokensAnnotation is always returning null value.
Any changes required in my code to make it work.

**Comment by J38** [comment]
Here is an example.  The list stored with the `NumerizedTokensAnnotation` key will contain a list of tokens.  Numeric phrases will be condensed into one token.  So "forty three" will have one token representing both "forty" and "three".  Other words will remain unchanged.

```
package edu.stanford.nlp.examples;


import edu.stanford.nlp.ling.*;
import edu.stanford.nlp.pipeline.*;
import edu.stanford.nlp.util.*;

import java.util.*;

public class NumerizedTokensExample {

    public static void main(String[] args) {
        // text
        String inputText = "There were forty three presidents.";
        // set up pipeline properties
        Properties props = new Properties();
        // set the list of annotators to run
        props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner");
        // build pipeline
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
        // create a document object
        CoreDocument document = new CoreDocument(inputText);
        // annnotate the document
        pipeline.annotate(document);
        // iterate through sentences
        for (CoreSentence sent : document.sentences()) {
            for (CoreMap token : sent.coreMap().get(CoreAnnotations.NumerizedTokensAnnotation.class)) {
                System.out.println(token);
            }
        }
    }
}
```
