### ISSUE TITLE
How to use edu.stanford.nlp.parser.nndep.DependencyParser to parse raw text line by line 

### ISSUE THREAD

**Issue by Sisi0518** [stanfordnlp/CoreNLP#838]
I use the command "java -Xmx8g  edu.stanford.nlp.parser.nndep.DependencyParser     -model edu/stanford/nlp/models/parser/nndep/english_UD.gz     -textFile input.txt -outFile output.txt " to parse my input.txt one line for one sentence, but filed. There are 250000 sentences in my input.txt, but the result of command is "Parsed 24994 sentences in 136.33 seconds (183.34 sents/sec)."

How to use edu.stanford.nlp.parser.nndep.DependencyParser to parse raw text line by line ?
 I use the edu.stanford.nlp.parser.nndep.DependencyParser in the Stanford CoreNLP 3.9.2, the model is edu/stanford/nlp/models/parser/nndep/english_UD.gz 
Thanks.

**Comment by J38** [comment]
You should just use the full pipeline interface.

```
java -Xmx4g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,depparse -ssplit.eolonly -file example.txt
```
