### ISSUE TITLE
constituency parse

### ISSUE THREAD

**Issue by valeryweber** [stanfordnlp/CoreNLP#841]
Dear All
I would like to ask you how to get access to the constituency parse, the same as the one displayed by http://corenlp.run/ webpage. I am using stanford-corenlp-full-2018-10-05 and I dont get always the same.
Where can I find this constituency parse?
Many thanks
valery

**Comment by neilnelson** [comment]
Looks like the 'parse' annotator' is the one you want. The following page is shown when clicking 'Constituency Parsing' from the main menu.

https://stanfordnlp.github.io/CoreNLP/parse.html

The server JSON output has an array line beginning

["parse"]=>
      string(191) "(ROOT

**Comment by valeryweber** [comment]
Yes, I can get it via the python interface, but the tree is not the same as via http://corenlp.run/ webpage.

For example, I get via the python interface:

(ROOT (S (NP (NN Water)) (VP (VP (VBZ is) (VP (VBN composed) (PP (IN of) (NP (NP (NN hydrogen)) (SBAR (WHNP (WDT which)) (S (VP (VBZ is) (NP (DT a) (NN gas))))))))) (CC and) (VP (VBZ is) (ADJP (RB very) (JJ flammable)))) (. .)))


While the webpage gives this one:

(ROOT ((S (NP (NN Water)) (VP (VBZ is) (VP (VBN composed) (PP (IN of) (NP (NP (NN hydrogen)) (SBAR (WHNP (WDT which)) (S (VP (VP (VBZ is) (NP (DT a) (NN gas))) (CC and) (VP (VBZ is) (ADJP (RB very) (JJ flammable)))))))))) (. .)))

Is there another switch to get the same constituency parse as on the webpage or the new parse is coming in a newer CoreNLP version?

Many thanks

valery

**Comment by AngledLuffa** [comment]
For posterity, you get different results when using `parse` by itself, `pos` and `parse`, or `pos` and `parse` with the shift reduce model.  Generally the shift reduce model will be the fastest and most accurate.  Feel free to experiment to figure out which is giving you the most useful results.
