### ISSUE TITLE
Precise commit hash release mapping?

### ISSUE THREAD

**Issue by tc64** [stanfordnlp/CoreNLP#844]
Does version x.y.z correspond to a precise commit? I see there are commits that specifically update release notes, but is there anything more precise?

Also, are releases ever changed or do you always increment version as a rule?

Thanks.

**Comment by J38** [comment]
In some cases a specific commit matches a specific release.  I don't know that this has always been the case historically.  I think moving forward we will try to always have the release be a specific commit.  That should be the case for versions 3.9.1 and 3.9.2.

We have in the past put up a rough draft for download on our site, but the release is totally finalized when we submit the jars to Maven, and at that point there are no changes to the release.  I think in the future we may put up a beta jar on Maven and when we work out any final issues after initial release, we will put up the final version.

I have made more proper release tags for v3.9.2 and v3.9.1 here on GitHub and will continue to do so for future releases.  As I have time I'll try to go back in time and match up previous releases with commits.
