### ISSUE TITLE
simpleBase local class incompatible

### ISSUE THREAD

**Issue by godlockin** [stanfordnlp/CoreNLP#845]
When I load the sentiment annotation into my project and init the StanfordCoreNLP object, the following exception always happens

`Invocation of init method failed; nested exception is edu.stanford.nlp.io.RuntimeIOException: java.io.InvalidClassException: org.ejml.simple.SimpleBase; local class incompatible: stream classdesc serialVersionUID = 7560584869544985034, local class serialVersionUID = -4908174115141247692`

The coreNLP version I am using is 3.9.2, which need to involve the ejml at version 0.30 (the same with the coreNLP dependency of v3.9.2), but I tried several versions of ejml, the only version which doesn't trigger this exception is v0.23, while the issue "version conflict" will happens...

It's a little confuse me that which version of ejml I need to involve here? or, does the coreNLP 3.9.2 a stable version?

**Comment by AngledLuffa** [comment]
Our version of EJML was updated with the most recent 4.0.0 release.  The issue you were likely running into was that the models were serialized with the older version of EJML, and the serialization was changed in a non-backwards-compatible manner sometime around v30.
