### ISSUE TITLE
3.9.2 canonical commit

### ISSUE THREAD

**Issue by aimerlavie** [stanfordnlp/CoreNLP#849]
I want to create a fork off 3.9.2. The code should match the exact version 3.9.2 that went into the jar files on mavencentral. How can I get the correct commit-ID?

**Comment by J38** [comment]
Ok I've set up a release for 3.9.2, you can see the appropriate commit by looking at release v3.9.2

https://github.com/stanfordnlp/CoreNLP/releases/tag/v3.9.2
