### ISSUE TITLE
Spanish tokenizer much slower than English tokenizer

### ISSUE THREAD

**Issue by vadali** [stanfordnlp/CoreNLP#85]
Hey,
I am using the Spanish tokenizer to run large jobs on common crawl using hadoop. 
While the english tokenizer works really fast, the Spanish tokenizer is painfully slow.. 

I started profiling it, and i'd like to share with you some initial results, perhaps we could find the bottleneck and fix it.

The first image shows profiling made to a large document (433,321 bytes) using the english tokenizer, which takes about ~35msecs on my computer:
![tokenize-english](https://cloud.githubusercontent.com/assets/379063/8886273/6534d4fc-321c-11e5-838a-34d9b7a0b23f.png)

The second image shows profiling made to the same exact document, using the spanish tokenizer, which takes about ~300msecs on the same computer:
![tokenize-spanish](https://cloud.githubusercontent.com/assets/379063/8886295/b0b7d12c-321c-11e5-8eff-01780c15b3d4.png)

it seems that most of the time is spent in asciiQuotes.. any ideas of why it behaves this way?

Thanks,
Shlomi

**Comment by vadali** [comment]
Some updates,
Unlike the english lexer, the spanish lexer uses String.replaceAll almost exclusively, rather than use Pattern.compile statically and the matcher method. 

I fixed this in asciiQuotes, and it improved the runtime from about 300ms to about 190ms. One thing that I am seeing is that this method gets called many many times, especially comparing it to the regular PTBLexer, for the same exact text:
![english-spanish-calls](https://cloud.githubusercontent.com/assets/379063/8918898/0e085432-3470-11e5-9771-aa6feb071965.png)

Here is a profiling breakdown of the tokenization process,
English:
![english-breakdown](https://cloud.githubusercontent.com/assets/379063/8918869/dec50404-346f-11e5-9af0-447be42d926b.png)

Spanish:
![spanish-breakdown](https://cloud.githubusercontent.com/assets/379063/8918872/e529000c-346f-11e5-8525-88e4142b1d85.png)

I will try to compare both flex files, attempt to minimize normalization calls. I would really appreciate any help with this, to make sure that I am doing the right thing correctly.

Thanks!

**Comment by vadali** [comment]
Another update:
It seems that `{WORD3}` is the culprit, causing all the calls to asciiQuotes. 
If I change the following:
```java
{WORD2}|{WORD3}  {
 final String origTxt = yytext();
 return getNext (asciiQuotes(origTxt), origTxt);
}
{WORD}	{ return getNext(); }
```
to 
```java
{WORD2}  {
 final String origTxt = yytext();
 return getNext (asciiQuotes(origTxt), origTxt);
}
{WORD}|{WORD3}	{ return getNext(); }
```
I get comparable performance to the english version (similar amount of asciiQuotes calls, etc). The question is, is that the correct thing to do, considering that:
```
/* Includes words with numbers, eg. sp3 */
WORD2 = {WORD}(({NUM}|{APOSETCETERA}){WORD}?)+{WORD}

/* Includes words with apostrophes in the middle (french, english,  catalan loanwords) */
WORD3 = {NUM}?({WORD}|{WORD2}){NUM}?
```
?

WDYT?

**Comment by vadali** [comment]
Hey,
Here is the commit of all my Spanish optimizations (b2cf3a6bc46d03d9b3d8106500874b39430e66b2), it now runs about 2x the speed of the english tokenizer, which makes sense due to the three types of splitting. Let me know if you'd like a pull request.

**Comment by erip** [comment]
I recommend submitting a PR regardless. If they want it, they'll take it.

**Comment by AngledLuffa** [comment]
Yes, if there's a change that improves speed quite a lot without changing
functionality, we'll be very glad to see it,

John

**Comment by manning** [comment]
Thanks Shlomi! 

Slow to get to this, but I've just merged in your changes. Thanks, this all looks good and indeed makes Spanish tokenization much faster.
