### ISSUE TITLE
在google colaboratory启动NLPserver失败，address already in use

### ISSUE THREAD

**Issue by johnarchie1** [stanfordnlp/CoreNLP#850]
!java -mx4g -cp "code/DataProcessor/stanford-corenlp-full-2018-10-05/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer 
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
[main] INFO CoreNLP -     Threads: 2
[main] INFO CoreNLP - Starting server...
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:433)
	at java.base/sun.nio.ch.Net.bind(Net.java:425)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:225)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:101)
	at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
	at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
	at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(HttpServer.java:137)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.run(StanfordCoreNLPServer.java:1427)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1523)
[Thread-0] INFO CoreNLP - CoreNLP Server is shutting down.

**Comment by zhangruinan** [comment]
Please read your error message *carefully*
```
 java.net.BindException: Address already in use
```
In default, corenlp server start on port 9000 (I remember), the error msg means that port=9000 was already taken at the point you trying to start the server. 

You may start server on different port by passing the parameters: `-port 9001` or any other unoccupied port.

**Comment by johnarchie1** [comment]
> 请阅读错误消息，_仔细_
> 
> ```
>  java.net.BindException: Address already in use
> ```
> 默认情况下，corenlp服务器在端口9000上启动（我记得），错误消息msg表示在尝试启动服务器时已经使用了port = 9000。
> 
> 您可以通过传递参数：`-port 9001`或任何其他未占用的端口来启动不同端口上的服务器。

感谢！！！是这样的，我解决了

**Comment by zhangruinan** [comment]
感兴趣可以follow我的项目, 在CoreNLP基础上支持更多的NLP中文支持: https://github.com/zhangruinan/SmoothNLP

**Comment by bifeng** [comment]
the same error is [site](https://github.com/stanfordnlp/CoreNLP/issues/663)

[site](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html#stopping-the-server), first stopping the server, then start it again

but, where is the "corenlp.shutdown" file in windows?

**Comment by bifeng** [comment]
Before restart this server, how to close this port which be occupied?

**Comment by bifeng** [comment]
For  windows.
```
import requests
from commands import getoutput

url = "http://localhost:9000/shutdown?"
shutdown_key = getoutput("type C:/Users/登录用户~1/AppData/Local/Temp/corenlp.shutdown")
r = requests.post(url,data="",params={"key": shutdown_key})
```
Before start the server again, you should shutdown first!

**Comment by AngledLuffa** [comment]
For everyone who contributed suggestions on how to check if the port was already occupied, thank you for taking that time.
