### ISSUE TITLE
Sentence spliting doesn't work, if there is no whitespace after dot

### ISSUE THREAD

**Issue by zharenkov** [stanfordnlp/CoreNLP#854]
I have text like this

> Dog loves cat.Cat loves mouse. Mouse hates everybody.

When I'm trying to split it into sentences, I got 2 sentences instead of 3.

> Dog loves cat.Cat loves mouse.
> 
> Mouse hates everybody.

My code is
```
        Properties props = new Properties();
        props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,parse,coref");
        props.setProperty("ssplit.boundaryTokenRegex", "\\.|[!?]+");
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
       pipeline.annotate(doc);
        List<CoreMap> sentences = doc.get(CoreAnnotations.SentencesAnnotation.class);
```

Also I tried to use PTBTokenizer, to split text to tokens, but again, it thinks that **cat.Cat** is a single word.

```
        PTBTokenizer ptbTokenizer = new PTBTokenizer(
                new FileReader(classLoader.getResource("simplifiedParagraphs.txt").getFile())
                ,new WordTokenFactory()
                ,"untokenizable=allKeep,tokenizeNLs=true,ptb3Escaping=true,strictTreebank3=true,unicodeEllipsis=true");
        List<String> strings = ptbTokenizer.tokenize();
```

Which type of annotator should I use, to get 3 sentences as the output?

**Comment by wnm3** [comment]
Likely due to attempts to preserve URL's within sentences. I have a related problem where strings of dotted text parse correctly unless there is a hyphen in part of the text. For example:

"SystemConfiguration folder com.apple.airport.preferences.plist com.apple.network.eapolclient.configuration.plist com.apple.wifi.message-tracer.plist"

parses as:
SystemConfiguration folder com.apple.airport.preferences.plist com.apple.network.eapolclient.configuration.plist com.apple.wifi.message-tracer."
and
"plist"

**Comment by manning** [comment]
Yes. A long time ago (probably at least a decade ago), CoreNLP did try to separate sentences with patterns like [a-z]\.[A-Z]. But there are many cases when you get periods in the middle like this that shouldn't be split, including URLs, filenames, mutual fund codes, abbreviations like "Ph.D.", .... So we ended up going with not splitting to minimize surprise.

Underlyingly, the key observation here is that CoreNLP sentence splitting is rule-based, and there are no short term plans to change this. You could try using the sentence splitter in the Python stanfordnlp to see if it works any better. No guarantee that it will in general, but it is neural network based, so maybe miracles will occur. ;)
