### ISSUE TITLE
Custom model and entity creation through API

### ISSUE THREAD

**Issue by DeepakDonde** [stanfordnlp/CoreNLP#855]
Microsoft LUIS API allow us to: 
1)Create custom intent
2)Create custom entities
3)Train models using set of utterances
4)Group intent and entities inside single application
5)Train and publish application

Can we do same with Stanford NLP?

If yes,  please mention API or classes for this. Stanford NLP documents are mostly focused on using existing model and entities.

**Comment by DeepakDonde** [comment]
@J38 can you please help me with this?

**Comment by J38** [comment]
We have a generic text classifier, so you could theoretically use that for intent as well.  

There is some info here: 
https://nlp.stanford.edu/wiki/Software/Classifier
https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/classify/ColumnDataClassifier.html

You can definitely train a custom NER model: https://stanfordnlp.github.io/CoreNLP/ner.html

There is no specific code for dealing with intent.
