### ISSUE TITLE
Annotater too Slow

### ISSUE THREAD

**Issue by wbickelmann** [stanfordnlp/CoreNLP#857]
I have the following properties for my pipeline:

Properties props = new Properties();
        props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,parse,sentiment");
        props.setProperty("parse.model", "edu/stanford/nlp/models/srparser/englishSR.ser.gz");
        props.setProperty("ner.model", "edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz");
        props.setProperty("ner.applyNumericClassifiers", "false");
        props.setProperty("ner.includeRange", "false");
        props.setProperty("sutime.markTimeRanges", "false");
        props.setProperty("ner.combinationMode","NORMAL");
        props.setProperty("ner.applyFineGrained","false");
. 

As far as I can tell I followed most of the advice on https://stanfordnlp.github.io/CoreNLP/memory-time.html yet I am still at ~260 ms per sentence. Any tuning advice to make the annotation process faster?

**Comment by luckynarang** [comment]
> I have the following properties for my pipeline:
> 
> Properties props = new Properties();
> props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,parse,sentiment");
> props.setProperty("parse.model", "edu/stanford/nlp/models/srparser/englishSR.ser.gz");
> props.setProperty("ner.model", "edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz");
> props.setProperty("ner.applyNumericClassifiers", "false");
> props.setProperty("ner.includeRange", "false");
> props.setProperty("sutime.markTimeRanges", "false");
> props.setProperty("ner.combinationMode","NORMAL");
> props.setProperty("ner.applyFineGrained","false");
> .
> 
> As far as I can tell I followed most of the advice on https://stanfordnlp.github.io/CoreNLP/memory-time.html yet I am still at ~260 ms per sentence. Any tuning advice to make the annotation process faster?

whats your pipeline , have you found the solution ?

**Comment by AngledLuffa** [comment]
4.0.0 should also be somewhat faster, and git master is faster to load, although I have no idea if the improvements will be sufficient for your needs.
