### ISSUE TITLE
Server for file https://nlp.stanford.edu/js/brat/style-vis.css is down

### ISSUE THREAD

**Issue by nadavb** [stanfordnlp/CoreNLP#858]
I am running the CoreNLP (Java) locally, and when trying to access the visual parser at
http://localhost:9001
It stopped working, because the files
https://nlp.stanford.edu/js/brat/style-vis.css
https://nlp.stanford.edu/js/brat/client/lib/head.load.min.js
are not served anymore.

**Comment by J38** [comment]
Unfortunately our machines are inaccessible for the moment.  I was told this matter probably won't be resolved until tomorrow.  But hopefully things will be back to normal by tomorrow afternoon.

**Comment by J38** [comment]
I think this is fixed now, but let me know if there are still issues.

**Comment by nadavb** [comment]
Yes, it works now. I think it would be wise to incorporate these two static files together with the local files, so it will be independent of any remote servers' functionality and would be able to run without internet connection.

**Comment by J38** [comment]
Sure thing, I agree!

**Comment by stanuku** [comment]
We see this happen again today, please help.
