### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by Ravindrakumara** [stanfordnlp/CoreNLP#859]
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project stanford-corenlp: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:

**Comment by AngledLuffa** [comment]
This isn't enough information to diagnose.

**Comment by Ravindrakumara** [comment]
same error came


________________________________
