### ISSUE TITLE
edu.stanford.nlp.patterns.LuceneSentenceIndex not in v3.5.2 corenlp jar

### ISSUE THREAD

**Issue by craigpfeifer** [stanfordnlp/CoreNLP#86]
I downloaded the v3.5.2 corenlp package and tried to use the SPIED functionality w/lucene indexing. However the class edu.stanford.nlp.patterns.LuceneSentenceIndex is not in the jar.

**Comment by gravity1989** [comment]
Is this resolved?

**Comment by craigpfeifer** [comment]
Nope. According to the SPIED FAQ:
(https://docs.google.com/document/d/19m_venIHdA_qfICEQaRbLuyX-JEysm5eTMyIKPTrXmE/edit?usp=sharing)

"Right now Lucene related classes and jar are not distributed in the CoreNLP release. Email sonal@cs.stanford.edu to get them."

Sent mail about a month ago and never heard back.

**Comment by J38** [comment]
I think there are license issues which prevent us from packaging our stuff with the Lucene jars.

You should be able to use the Lucene related stuff if you just download the GitHub repo and include these jars:

lucene-analyzers-common-4.10.3.jar
lucene-core-4.10.3.jar
lucene-demo-4.10.3.jar
lucene-queries-4.10.3.jar
lucene-queryparser-4.10.3.jar

Which can be found here I assume: https://lucene.apache.org/core/

**Comment by J38** [comment]
Note those lucene jars can be found in the CoreNLP/lib folder.
