### ISSUE TITLE
Dependency Parse - Tree annotation always null

### ISSUE THREAD

**Issue by rkechols** [stanfordnlp/CoreNLP#864]
Using the Russian CoreNLP we're trying to get a dependency tree (from 'depparse') to analyze, but the call to CoreMap.get(TreeCoreAnnotation.TreeAnnotation.class) always returns a null tree. Here's a code snippet:
```
public boolean	apply(AbstractDocument docToParse){
		assert docToParse != null;
		int attempts = 0; 
		try
		{
			initializeState(docToParse);

			Annotation docAnnotation = new Annotation(workingDoc.getText());
			pipeline.annotate(docAnnotation);

			List<CoreMap> sentences = docAnnotation.get(CoreAnnotations.SentencesAnnotation.class);
			for (CoreMap itr : sentences)
			{
				if (itr.size() > 0)
				{
					Tree tree = itr.get(TreeCoreAnnotations.TreeAnnotation.class);
					//'tree' is always null here
```

We've been able to get a valid tree from English and German, which use the constituency parse, not dependency parse ('parse', not 'depparse'). How do we get the dependency tree?

**Comment by AngledLuffa** [comment]
TreeAnnotation is specifically for constituency trees.  Look for the SemanticGraph objects defined in src/edu/stanford/nlp/semgraph/SemanticGraphCoreAnnotations.java
