### ISSUE TITLE
Stanford NLP NER when executed on android runs out of heap memory

### ISSUE THREAD

**Issue by luckynarang** [stanfordnlp/CoreNLP#876]
I am using this pipeline

Tokenizer, splitter , pos, lemma , ner

I tried tweaking the pipeline by setting properties.

But eventually this pipeline runs out of heap memory on android.

What can be the solution for this , considering it has to be run offline.

Or what could be alternate approach for this.

**Comment by AngledLuffa** [comment]
Although this is not surprising, considering the process takes quite a bit of memory, we have lowered the memory footprint of these annotators quite a bit recently.  You might have more luck with 4.0.0 or with the current git master, which is still compatible with 4.0.0 models.

Currently running that set of annotators takes 836MB to load.

There may still be room for improvement, and you can also do things like turn off sutime, turn off fine grained NER, or use fewer NER models.
