### ISSUE TITLE
TokenSequenceParser ignoring tail of patterns mentioned in rules

### ISSUE THREAD

**Issue by ankitsingh2** [stanfordnlp/CoreNLP#877]
Following function in TokenSequenceParser class **ignores tail of patterns** defined in rules for **tokensregex**

private String getStringFromTokens(Token head, Token tail, boolean includeSpecial) {
      StringBuilder sb = new StringBuilder();
      for( Token p = head ; p != tail ; p = p.next ) {
        if (includeSpecial) {
          appendSpecialTokens( sb, p.specialToken );
        }
        sb.append( p.image );
      }
      return sb.toString();
 }

Eg:
**([{lemma:/([a-zA-Z]{2,}_)?[a-zA-Z]{2,}[0-9]{2,}/}])** 
gets converted to 
**([{lemma:/([a-zA-Z]{2,}_)?[a-zA-Z]{2,}[0-9]{2,}/}]** 
while reading and don't provide intended matches

**Comment by ankitsingh2** [comment]
Please update

**Comment by AngledLuffa** [comment]
The student who worked on TokensRegex the most has moved from Stanford, so
would you mind giving a little more context for this issue?  A small test
case which shows the problem would be perfect.

Thanks,

John

**Comment by ankitsingh2** [comment]
As we know that TokenRegex works on sequence of token. Consider following rule being applied on the user input:

**Rule:**
```
{
    ruleType: "tokens",
    pattern: ([{word:"hello"}]),
    action: Annotate($0, ner, "O"),
    priority: 1.0
}
```

**Input:** `"hello"`

Expected behaviour: Annotates "hello" word as entity "O".
Actual behaviour: Doesn't matches with hello text of the token and ner annotation corresponding to input "hello" remains null.

Cause: The pattern changes from
`([{word:"hello"}])`
to 
`([{word:"hello"}]`
ignoring the tail (i.e the last closing bracket) when the pattern is parsed through the above mentioned
function in TokenSequenceParser.java. The pattern is rendered invalid and don't match according to the rule defined. All the sample rules defined in CoreNLP models jar under tokensregex folder are too
not providing the intended functionality because of this.

**Comment by J38** [comment]
I don't fully know the TokensRegex code base so I'm not sure how the rule parsing is handled completely, but `tokensregex` (including the example rules) work fine as of the moment.

There is exhaustive documentation about using it here:

https://stanfordnlp.github.io/CoreNLP/tokensregex.html

I would strongly discourage altering the original author's code.

**Comment by J38** [comment]
For instance this example runs fine:

```
java -Xmx5g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,tokensregex -tokensregex.rules colors.rules.txt -file example.txt
```

**Comment by J38** [comment]
This example works fine as well:

```
package edu.stanford.nlp.examples;

import edu.stanford.nlp.ling.*;
import edu.stanford.nlp.pipeline.*;

import java.util.Properties;

public class TokensRegexExample {

    public static void main(String[] args) {
        Properties props = new Properties();
        props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,tokensregex");
        props.setProperty("tokensregex.rules", "colors.rules.txt");
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
        Annotation ann = new Annotation("My favorite color is green.");
        pipeline.annotate(ann);
        for (CoreLabel token : ann.get(CoreAnnotations.TokensAnnotation.class)) {
            System.out.println(token.word() + " " + token.ner());
        }
    }
}
```

**Comment by J38** [comment]
I am running Stanford CoreNLP 3.9.2 on a Unix environment.

**Comment by J38** [comment]
I have never tested this on a Windows environment for example, so maybe the issue has to do with Windows ?  In which case I guess we should alter that code!

**Comment by ankitsingh2** [comment]
I am using the same version you mentioned (3.9.2) and have even gone through the tokensregex documentation. Tried to run your sample code on my mac env (which is UNIX based) but its too breaking for me with original author's code in place. 

Also its clearly eminent from the function i mentioned that the tail has been left unprocessed. Can you please guide me regarding this?

**Comment by AngledLuffa** [comment]
I can confirm that the TokensRegexExample works on Windows 10

**Comment by ankitsingh2** [comment]
PFB the debugger screenshot. In it the **head** and **tail** are "**(**" and "**)**" respectively. But the **str** variable is missing "**)**" at the end after getting processed from **getStringFromTokens** function. And the **TokenSequencePattern** is getting created by the faulty **str** variable which is causing malfunctioning of tokensregex.

![image](https://user-images.githubusercontent.com/35058598/57978194-a27d2580-7a25-11e9-92cc-d9f935c770fc.png)

**Comment by AngledLuffa** [comment]
Can you give us example code & expressions where it doesn't work the way
you expect?  Since we just provided a couple examples where it works as we
expect

**Comment by ankitsingh2** [comment]
I simply followed the sample shared by **J38** (you can find the code in above comment) which is working according to him with rule as follows:

```
word = { type: "CLASS", value: "edu.stanford.nlp.ling.CoreAnnotations$TextAnnotation" }

{
    ruleType: "tokens",
    pattern: ([{word:"green"}]),
    action: Annotate($0, ner, "COLOR"),
    priority: 1.0
}
```
Expected behaviour: **Tokensregex tags "green" with entity "COLOR"**
Actual behaviour (in my env):   **"green" is tagged as entity "O"** as tokensregex failed to match pattern mentioned with word green as it was rendered invalid with missing closing bracket (the tail of the pattern)

**Comment by AngledLuffa** [comment]
I think literal expressions supposed to be written

/green/

I believe the text conversion you are concerned about is simply for
debugging / logging reasons.  I agree that it is missing the trailing ) but
it does not cause any problems with SUTime or with the examples we sent.

**Comment by J38** [comment]
Just to be clear, I was referring to a rules file in the demo.  Particularly this one:

https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/ling/tokensregex/demo/rules/colors.rules.txt

It doesn't appear your rules are formatted properly.

**Comment by J38** [comment]
I think the issue is you are missing this from your rules:

```
ner = { type: "CLASS", value: "edu.stanford.nlp.ling.CoreAnnotations$NamedEntityTagAnnotation" }
```

**Comment by ankitsingh2** [comment]
/green/ is written when we are supposed to match the token with regular expression. Incase we need to do exact match it is enclosed under double quotes i.e. "green". Even if i change "green" to /green/ in rule its still missing the closing the bracket.

Also i didn't miss the statement:
 ner = { type: "CLASS", value: "edu.stanford.nlp.ling.CoreAnnotations$NamedEntityTagAnnotation" }

Its defined under my base rule. I just didn't provide under my comment. If i would have missed it would have thrown parsing exception. Sorry again if i have caused some misunderstanding by this. PFB revised rule:

```word = { type: "CLASS", value: "edu.stanford.nlp.ling.CoreAnnotations$TextAnnotation" }
ner = { type: "CLASS", value: "edu.stanford.nlp.ling.CoreAnnotations$NamedEntityTagAnnotation" }

{
    ruleType: "tokens",
    pattern: ([{word:"green"}]),
    action: Annotate($0, ner, "COLOR"),
    priority: 1.0
}
```

**Comment by ankitsingh2** [comment]
Regrading formatting of my rule, the rule follows the convention mentioned by first point (i.e [{word:"pizza"}]) in the link : 

[https://stanfordnlp.github.io/CoreNLP/tokensregex.html#tokens-rules-patterns](https://stanfordnlp.github.io/CoreNLP/tokensregex.html#tokens-rules-patterns)

**Comment by AngledLuffa** [comment]
It's not hard to update getStringFromTokens and recompile.  I did this and
it didn't change any results.  Have you tried it yourself? As far as I can
tell, the bug you've uncovered is just a cosmetic change and doesn't have
anything to do with the issue you're having.

**Comment by ankitsingh2** [comment]
Well it did change the results for me. Doing changes (adding tail)  to getStringFromTokens as i mentioned in above comments lets tokensregex recognise patterns and it does what its expected to do, while with original code in place, it doesn't.
It's perfectly visible that tail has been missed in the function and how should i expect the pattern without tail to work?
The same is supported by debugger's screenshot i shared.
Let me know if i am missing something in the question asked.

**Comment by J38** [comment]
I ran the `TokensRegexExample` code above with `colors.rules.txt` as this rules file: 

https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/ling/tokensregex/demo/rules/colors.rules.txt

and got expected output.  Are you saying you don't get the expected output when you run that demo class?  I am using Stanford CoreNLP 3.9.2 on Unix at the command line.

**Comment by J38** [comment]
It also works in IntelliJ.

**Comment by ankitsingh2** [comment]
Yes its working. Might have did something wrong in writing the rules and assumed this cosmetic issue as mentioned by AngledLuffa to be the cause of mismatch. But do correct this as it provides wrong notion. Thanks guys for being patient with me :)

**Comment by AngledLuffa** [comment]
For future reference, I did reattach the missing ).  It caused no changes
in the output of corenlp on a fairly large corpus, so I still think it was
a cosmetic issue rather than a functional one.
