### ISSUE TITLE
French Tokenizer: set splitContraction to false

### ISSUE THREAD

**Issue by wbcf** [stanfordnlp/CoreNLP#879]
Hi!

I've switched my dependencies to the latest release that added the management of contractions  in French (which seems to be splitContractions=true by default)
```
public static final String FTB_OPTIONS = "ptb3Ellipsis=true,normalizeParentheses=true,ptb3Dashes=false," +
      "splitContractions=true,splitCompounds=true";
```
But I now get an error stating that:
`edu.stanford.nlp.international.french.process.FrenchLexer: Invalid options key in constructor: splitContractions`

I've then tried not to use the default FTB_OPTIONS settings and inputting `splitContractions=false` but I quite predictably got the same error.
When I look at the setOptions method, I can see how it works for either one of the existing options from FrenchLexer (ptb3Escaping, untokenizable, _etc_.) OR splitCompounds but I can't find how/where the splitContractions option is parsed? Did I miss something?

**Comment by AngledLuffa** [comment]
Thanks for letting us know!  I just submitted a patch which should fix this
for the next release.

**Comment by wbcf** [comment]
Thanks!
