### ISSUE TITLE
Make AnnotationUtils.get*Mentions Methods Static

### ISSUE THREAD

**Issue by ThomasMatlak** [stanfordnlp/CoreNLP#880]
Is there a good reason why the methods `getEntityMentions`, `getRelationMentions`, and `getEventMentions` in the class `edu.stanford.nlp.ie.machinereading.structure.AnnotationUtils` are non-static?

It would be nice to have access to these methods and avoid the `CoreMap.get(MachineReadingAnnotations.RelationMentionsAnnotation.class)` syntax.
They are currently non-static methods in a class with a private constructor, which makes them totally unaccessible.

**Comment by manning** [comment]
Not that I'm aware of....

In general this doesn't seem the best piece of code in CoreNLP....

I'll look at the PR.
