### ISSUE TITLE
Get positions of tokens in parsing tree

### ISSUE THREAD

**Issue by lcswillems** [stanfordnlp/CoreNLP#883]
Hi,
I use CoreNLP to get the parsing tree of a sentence. However, all the leaves are just plain text. I would like to also get the position of each leaf in the original sentence (by position, I mean, the position of the first and last character of the token in the original sentence).
How could I do it?

**Note:** I use the CoreNLP Python plugin.

**Comment by AngledLuffa** [comment]
How are you getting the leaves?  Because the bottom of the parse tree
should be some form of label with annotations on it, probably a CoreLabel

**Comment by lcswillems** [comment]
I use `tree.leaves()`.

**Comment by AngledLuffa** [comment]
That should return tree nodes which have a label attached.  leaf.label()
should work.

What are you trying?

**Comment by lcswillems** [comment]
Sorry, I didn't open the issue in the good repo. Is it possible to transfer it to this one : https://github.com/stanfordnlp/python-stanford-corenlp ?
