### ISSUE TITLE
Constituency parser's visualization does not work on https://corenlp.run

### ISSUE THREAD

**Issue by phosseini** [stanfordnlp/CoreNLP#884]
When applying constituency parser, there is no visualization shown in the output. I've already tried the parser from corenlp.run on multiple platforms and browsers, but it seems like there's a problem on the server side.

**Comment by J38** [comment]
I see the visualization when I try it right now.

**Comment by J38** [comment]
In both Chrome and Safari.

**Comment by phosseini** [comment]
Weird, this is what a couple of us see in our browsers both in Chrome and Safari.

<img width="1316" alt="Screen Shot 2019-05-21 at 7 30 43 PM" src="https://user-images.githubusercontent.com/25105263/58137201-54bc1500-7bff-11e9-94a6-a3199c0bd8ca.png">

**Comment by phosseini** [comment]
Checked it with a couple of other people too, they also have the same problem.

**Comment by AngledLuffa** [comment]
This is working fine for me as of now, so I'm going to close this issue
