### ISSUE TITLE
Is it normal to have multiple roots in depparse result ?

### ISSUE THREAD

**Issue by lengockyquang** [stanfordnlp/CoreNLP#887]
Hi CoreNLP team, I'm using stanford corenlp to depparse a sentence and get the output in conll format. The command i use is below:

> java -cp "*" -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,depparse -tokenize.whitespace -ssplit.eolonly -file tok_train.en -outputFormat conll

**Given sentence:** A school uniform down to the ankles , because it had to last for six years .
Output in Conll format:
![image](https://user-images.githubusercontent.com/45225905/58377542-9a852e80-7fad-11e9-900c-f4ed29ed33a8.png)

I have a question that is it normal to have multiple roots like this ?
The corenlp version is stanford-corenlp-full-2018-10-05

**Comment by kaushikacharya** [comment]
Don't know how to force single root in CoreNLP, but had used the solution provided in https://github.com/explosion/spaCy/issues/1850#issuecomment-359184838 for spaCy.

Probably something similar should be there for CoreNLP.

**Comment by AngledLuffa** [comment]
Shouldn't happen!  Seems the classifier has chosen the relationship as root
even though it shouldn't be able to.  The real root is the one with 0 as
the head.  The wrong root should be connecting to 3, not 8, but that's just
a misclassification.  The fact that it can choose to classify it as root is
something we can hopefully fix

**Comment by AngledLuffa** [comment]
This will now be fixed in the next release.
