### ISSUE TITLE
java.io.IOException: The process cannot access the file because another process has locked a portion of the file

### ISSUE THREAD

**Issue by 121eddie** [stanfordnlp/CoreNLP#890]
[This post](https://github.com/stanfordnlp/CoreNLP/issues/399) has been closed even though the problem persists:
When building with maven on windows, some files are 'locked', and no .jar is being produced

Tests in error:
  testPutLocal(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testCacheWritingToDisk(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testCollision(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testGetLocal(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testMerge(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testSize(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testContainsFile(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testPutFile(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testGetFile(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testContainsLocal(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testMapValueGoodPattern(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testContainsRemoveFromMemory(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testIterator(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file
  testComprehension(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The process cannot access the file because another process has locked a portion of the file

Tests run: 1166, Failures: 16, Errors: 14, Skipped: 1

**Comment by AngledLuffa** [comment]
In fact, this has nothing to do with maven, and seems to be an actual
problem on Windows.  I'll take a close look later.

**Comment by 121eddie** [comment]
In the meantime , I used ant  and encountered the ['unable to open' problem](https://github.com/stanfordnlp/CoreNLP/issues/101), even in the absence of a slash
