### ISSUE TITLE
Exporting trees for Tregex

### ISSUE THREAD

**Issue by 121eddie** [stanfordnlp/CoreNLP#891]
The Tregex CLI and GUI both require tree files. How can I produce these files from CLI or web interface?

**Comment by AngledLuffa** [comment]
Which tool?  What do you want to do?  This is not nearly enough information
to help you.

**Comment by 121eddie** [comment]
```
echo 'please parse this sentence'>input
java -Xmx4g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,parse -file input.txt -outputFormat xml
java edu.stanford.nlp.trees.tregex.TregexPattern '__<#VP' tree_input
> The system cannot find the file specified.
```

**Comment by AngledLuffa** [comment]
The name of the files are not consistent.  Did you get those exact commands
from our documentation?

**Comment by 121eddie** [comment]
line 1 successfully creates 'input', line 2 'input.xml'. Is there a documentation about command line usage of Tregex?

**Comment by AngledLuffa** [comment]
The second command in your post references "input.txt" after creating
"input" in the first line.  If you got this command from somewhere, it's
wrong and we should fix the documentation.

Frankly, we're not here to debug your entire process, especially when you
supply little drips of information in each question you post.

There's a ton of information on Tregex here:

https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/trees/tregex/TregexPattern.html

The LexicalizedParser or ShiftReduceParser is more suitable for outputting
trees than StanfordCoreNLP, although you can get trees from either one.

https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/parser/lexparser/package-summary.html
