### ISSUE TITLE
Websites not working.

### ISSUE THREAD

**Issue by bringoo** [stanfordnlp/CoreNLP#893]
Any of these mentioned links are not working in Pakistan. I had used stanford web api in my final thesis work these were working perfectly fine but from few days these sites are not working.
http://nlp.stanford.edu:8080/corenlp/process
http://corenlp.run/
https://nlp.stanford.edu/.

Please help what to do.
Thank you 
Regards 
Nageen Naeem

**Comment by manning** [comment]
Are things back now and this was a temporary outage?  If so, great news! If not, I'm afraid that we are not able to do anything about this. As a free demo service, it doesn't make sense to host it elsewhere. You can run corenlp locally or anyone else is free to host a corenlp server....
