### ISSUE TITLE
NullPointerException thrown when trying to getDate from Timex object with "this january" as entity. 

### ISSUE THREAD

**Issue by sysoutadi** [stanfordnlp/CoreNLP#896]
"this january" entity has Timex object 
`<TIMEX3 alt_value="THIS XXXX-01" anchorTimeID="t0" temporalFunction="true" tid="t1" type="DATE" valueFromFunction="tf0">this january</TIMEX3>`

on calling getDate on this object NullPointerException is thrown. 

However, when parsing the same entity on http://corenlp.run/, 
it parses the date correctly as "2019-01".

**Comment by AngledLuffa** [comment]
Please give us more context on how to replicate this bug

**Comment by sysoutadi** [comment]
I am trying to perform NER on the following sentence : 
"Kosgi Santosh sent an email to Stanford University this january"

Using the following code : 
 `public` `static String text = "Kosgi Santosh sent an email to Stanford University this january."`;

`Properties props = new Properties();`

`// set the list of annotators to run`

`props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref, sentiment");`

`// set a property for an annotator, in this case the coref annotator is being set to use the neural algorithm`

`props.setProperty("coref.algorithm", "neural");`

 `// build pipeline`

`StanfordCoreNLP pipeline = new StanfordCoreNLP(props);`

`// create a document object`

`CoreDocument document = new CoreDocument(text);`

`// annnotate the document`

`pipeline.annotate(document);`

`Calendar date = document.sentences().get(0).entityMentions().get(2).canonicalEntityMention().get().coreMap().get(TimeAnnotations.TimexAnnotation.class).getDate();`


This throws NullPointerException. 
Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.util.regex.Pattern.matches(Pattern.java:1134)
	at edu.stanford.nlp.time.Timex.getDate(Timex.java:354)
	at DateNER.main(DateNER.java:96)

Upon inspecting the coreMap object, I get the Timex  object as `<TIMEX3 alt_value="THIS XXXX-01" anchorTimeID="t0" temporalFunction="true" tid="t1" type="DATE" valueFromFunction="tf0">this january</TIMEX3>`

I need to resolve calendar the way it is being resolved on  http://corenlp.run/ i.e "2019-01"

**Comment by sysoutadi** [comment]
> I am trying to perform NER on the following sentence :
> "Kosgi Santosh sent an email to Stanford University this january"
> 
> Using the following code :
> `public` `static String text = "Kosgi Santosh sent an email to Stanford University this january."`;
> 
> `Properties props = new Properties();`
> 
> `// set the list of annotators to run`
> 
> `props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref, sentiment");`
> 
> `// set a property for an annotator, in this case the coref annotator is being set to use the neural algorithm`
> 
> `props.setProperty("coref.algorithm", "neural");`
> 
> `// build pipeline`
> 
> `StanfordCoreNLP pipeline = new StanfordCoreNLP(props);`
> 
> `// create a document object`
> 
> `CoreDocument document = new CoreDocument(text);`
> 
> `// annnotate the document`
> 
> `pipeline.annotate(document);`
> 
> `Calendar date = document.sentences().get(0).entityMentions().get(2).canonicalEntityMention().get().coreMap().get(TimeAnnotations.TimexAnnotation.class).getDate();`
> 
> This throws NullPointerException.
> Exception in thread "main" java.lang.NullPointerException
> at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
> at java.util.regex.Matcher.reset(Matcher.java:309)
> at java.util.regex.Matcher.(Matcher.java:229)
> at java.util.regex.Pattern.matcher(Pattern.java:1093)
> at java.util.regex.Pattern.matches(Pattern.java:1134)
> at edu.stanford.nlp.time.Timex.getDate(Timex.java:354)
> at DateNER.main(DateNER.java:96)
> 
> Upon inspecting the coreMap object, I get the Timex object as `<TIMEX3 alt_value="THIS XXXX-01" anchorTimeID="t0" temporalFunction="true" tid="t1" type="DATE" valueFromFunction="tf0">this january</TIMEX3>`
> 
> I need to resolve calendar the way it is being resolved on http://corenlp.run/ i.e "2019-01"

**Comment by sysoutadi** [comment]
Closed by mistake. Let's fix this.

**Comment by AngledLuffa** [comment]
I think there's a few things going on here:

- The output in this error case is not very clear.  It doesn't have enough
information to determine the full date, but instead of saying so, it just
barfs.  I can improve that

- Because the date in the text is just "this January", it doesn't by
default assume you mean 2019.  You can change that with

    props.setProperty("ner.docdate.useFixedDate", "2019-06-26");

Flipping through the docs, I couldn't find that anywhere either, so I'll
add a note about it.

- Even once you do that, it then thinks the date is "2019-01" instead of
"XXXX-01", but that's not enough to create a Calendar object.  What you
need is something like

"Kosgi Santosh sent an email to Stanford University on January 5th."
