### ISSUE TITLE
Question about Chinese sentences ssplit in the server mode

### ISSUE THREAD

**Issue by luyaojie** [stanfordnlp/CoreNLP#897]
Hi,

I run corenlp server using "StanfordCoreNLP-chinese.properties" as default -serverProperties. When I annotate Chinese text with stanfordcorenlp, the results of ssplit are different. 
run1.py with "'pipelineLanguage': 'zh',"
run2.py without "'pipelineLanguage': 'zh',".

In website visualisation version, I got the same result with run1.py. (only one sentence)
![image](https://user-images.githubusercontent.com/5457307/60080055-bffa8900-9761-11e9-85aa-9be39bd213f5.png)
How can get the right result (two sentences) of sentence split in website?

Corenlp: stanford-corenlp-full-2018-10-05
Model: stanford-*-corenlp-2018-10-05-models.jar

run1.py
```
from stanfordcorenlp import StanfordCoreNLP
corenlp = StanfordCoreNLP("http://127.0.0.1", port=9000)
sentence = "快速的棕色狐狸跳过了懒惰的狗。快速的棕色狐狸跳过了懒惰的狗。"
props = {'annotators': 'ssplit',
         'pipelineLanguage': 'zh',
         'outputFormat': 'conll'}
data = corenlp.annotate(sentence, properties=props)
print(data)
```
Got
```
1	快速	_	_	_	_	_
2	的	_	_	_	_	_
3	棕色	_	_	_	_	_
4	狐狸	_	_	_	_	_
5	跳过	_	_	_	_	_
6	了	_	_	_	_	_
7	懒惰	_	_	_	_	_
8	的	_	_	_	_	_
9	狗	_	_	_	_	_
10	。	_	_	_	_	_
11	快速	_	_	_	_	_
12	的	_	_	_	_	_
13	棕色	_	_	_	_	_
14	狐狸	_	_	_	_	_
15	跳过	_	_	_	_	_
16	了	_	_	_	_	_
17	懒惰	_	_	_	_	_
18	的	_	_	_	_	_
19	狗	_	_	_	_	_
20	。	_	_	_	_	_
```

run2.py
```
from stanfordcorenlp import StanfordCoreNLP
corenlp = StanfordCoreNLP("http://127.0.0.1", port=9000)
sentence = "快速的棕色狐狸跳过了懒惰的狗。快速的棕色狐狸跳过了懒惰的狗。"
props = {'annotators': 'ssplit',
         # 'pipelineLanguage': 'zh',
         'outputFormat': 'conll'}
data = corenlp.annotate(sentence, properties=props)
print(data)
```
Got
```
1	快速	_	_	_	_	_
2	的	_	_	_	_	_
3	棕色	_	_	_	_	_
4	狐狸	_	_	_	_	_
5	跳过	_	_	_	_	_
6	了	_	_	_	_	_
7	懒惰	_	_	_	_	_
8	的	_	_	_	_	_
9	狗	_	_	_	_	_
10	。	_	_	_	_	_

1	快速	_	_	_	_	_
2	的	_	_	_	_	_
3	棕色	_	_	_	_	_
4	狐狸	_	_	_	_	_
5	跳过	_	_	_	_	_
6	了	_	_	_	_	_
7	懒惰	_	_	_	_	_
8	的	_	_	_	_	_
9	狗	_	_	_	_	_
10	。	_	_	_	_	_
```

**Comment by J38** [comment]
Thanks for bringing up this issue.  I will investigate why the sentence splitting seems to not be working via the server.

**Comment by J38** [comment]
I am working on debugging this.  The issue seems to be when the `pipelineLanguage` option is used, when the code loads the sentence splitting regex from the properties, the wrong encoding is used.

**Comment by J38** [comment]
If you start the server this way

```
java -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000 -serverProperties StanfordCoreNLP-chinese.properties
```
And then issue a request with the smaller annotators list `tokenize,ssplit`, it should work properly.  But I will fix this character encoding issue in the current code as well.

Also, I recommend using the official Python client.  More here: https://stanfordnlp.github.io/stanfordnlp/corenlp_client.html

**Comment by J38** [comment]
Ok this issue should be fixed in the current version of the code on GitHub.

**Comment by luyaojie** [comment]
It works, Thank you!
