### ISSUE TITLE
localhost ipv6

### ISSUE THREAD

**Issue by zeeqy** [stanfordnlp/CoreNLP#899]
I'm running CoreNLP server on cluster node. Log tells me the following:

```
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9000
```

And I tried to use python3 requests to call the service but 

`http://127.0.0.1:9000/?properties={"annotators": "parse", "outputFormat": "json"}` 
and 
`http://localhost:9000/?properties={"annotators": "parse", "outputFormat": "json"}`
gave me `connection refused`

Any idea?

so [0:0:0:0:0:0:0:0] is an unspecified ipv6 address. Is there an option to specify the complete url (http://localhost:9000) instead of port only?

**Comment by manning** [comment]
I'm not greatly expert on IPv6, but, as I understand things, this IPv6 unspecified address, corresponding to IPv4 0.0.0.0, is just fine to use and you should be able to make calls to it. For example, assuming that you've started a StanfordCoreNLPServer on your local machine and that you have `wget`, then the following should work from the commandline:

```
wget --post-data 'The quick brown fox jumped over the lazy dog.' 'http://[::]:9000/?properties={"annotators":"tokenize,ssplit,pos","outputFormat":"json"}' -O -
```

and using the Python `requests` library, the following should work:

```
import requests
print(requests.post('http://[::]:9000/?properties={"annotators":"tokenize,ssplit,pos","outputFormat":"json"}', data = {'data':'The quick brown fox jumped over the lazy dog.'}).text)
```
Note: `[::]` is shorthand for `[0:0:0:0:0:0:0:0]`. The square brackets are used in the URL as per [RFC 2732](https://www.ietf.org/rfc/rfc2732.txt).

**Comment by zeeqy** [comment]
OMG, Are you THE Christopher Manning? Thanks for answering. We got it. It's the connection problem between master and worker nodes. Turn on internal IPv4 solve the problem and I believe using `[::]` also works.

Thanks again. Great tool.
