### ISSUE TITLE
distinguish types of adjectives

### ISSUE THREAD

**Issue by chaouiy** [stanfordnlp/CoreNLP#900]
It would be great if we can use coreNLP to distinguish which semantic type of adjective / adverb it is. Here is an example list I use to do this manually :
```
       "quantitative": ["half", "some", "several", "much", "all", "many", "whole", "no", "enough", "little", "any", "sufficient", "none", "most", "few"],
        "demonstrative": ["this", "that", "these", "those"],
        "possessive": ["my", "his", "their", "your", "our", "mine", "his", "hers", "theirs", "yours", "ours"],
        "interrogative": ["which", "what", "whose"],
        "distributive": ["each", "every", "either", "neither", "any"],
        "article": ["a", "an", "the"],
```

**Comment by manning** [comment]
This could be done with a set of tokensregex rules -- see, e.g., the example color.rules.txt in the tokensregex folder of the CoreNLP distribution. 

But we don't presently have any such lexicon. Someone would have to build it....
