### ISSUE TITLE
Less-than and greater-than signs in documentation wrongly escaped

### ISSUE THREAD

**Issue by JeroenvdV** [stanfordnlp/CoreNLP#906]
For instance noticeable here: 

https://github.com/stanfordnlp/CoreNLP/blob/0d4cfd4209feec7ddbda9eab3fa9c9791caa3e36/src/edu/stanford/nlp/semgraph/semgrex/SemgrexPattern.java#L103

Within the code snippets it seems the html entities are not parsed here: https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/semgrex/SemgrexPattern.html

**Comment by AngledLuffa** [comment]
You mean so that it results in

{} [&lt;subj {} | &lt;agent {}] &amp; @ {}

Thank you for calling our attention to this
