### ISSUE TITLE
命名实体识别标签对应的中文在哪里可以找到对应？

### ISSUE THREAD

**Issue by pangwh** [stanfordnlp/CoreNLP#908]
命名实体识别标签对应的中文在哪里可以找到对应？

**Comment by gamer01** [comment]
I am quite certain that you have no chance that your issue will be considered if you write in Chinese.

**Comment by AngledLuffa** [comment]
You can download corenlp from here:

https://stanfordnlp.github.io/CoreNLP/download.html

There is a link for Chinese models there as well.

There is a section here for running on Chinese text:

https://stanfordnlp.github.io/CoreNLP/human-languages.html

It seems you want ner?  Not 100% sure.

Unfortunately, all of the help information is in English, not Chinese.  Good luck...
