### ISSUE TITLE
Is the source code for the corenlp.run website available?

### ISSUE THREAD

**Issue by JeroenvdV** [stanfordnlp/CoreNLP#909]
I am interested in making some modifications to the demo site (than runs on corenlp.run) to test certain things more efficiently, using my local corenlp server (for my own use) and of course possibly submit improvements if they are useful in general. Is the website's source control repository published online anywhere?

**Comment by J38** [comment]
https://github.com/stanfordnlp/CoreNLP/tree/master/src/edu/stanford/nlp/pipeline/demo

All of the resources are located there.
