### ISSUE TITLE
[question] POS-tagger: why are the tag values constraint this way?

### ISSUE THREAD

**Issue by gamer01** [stanfordnlp/CoreNLP#911]
https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/sequences/ExactBestSequenceFinder.java#L55

I assume, this constraint has been introduced for the sake of efficiency of the viterbi algorithm, but how does this effect the precision and why are the values not pruned with respect to their log-probability instead? I could not find any explaination in eighter of the two papers (Toutanova 2000/2003)

**Comment by gamer01** [comment]
also i would add this source comment:

`// constraint to: only observed closed tags for the word IF word known ELSE all open tags`

**Comment by gamer01** [comment]
https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/tagger/maxent/TestSentence.java#L841 The expansion of the possible tags is only hard coded for english.

I wonder if it would make sense to ask the classifier when expanding the possible tags. Imagine the following: The corpus is small and the word did not appear in all its tags, but the classifier is certain that the word is a RBS, because the context it appears in is the same context, other adverbs appeared in during training. Because of the filtering mentioned above, it can never be classified that way, as the Viterbi has no possibility to do so.

Be `T` the set seen tags for a word `w` and `c` its context. Be `P` the MaxEnt model and `𝗧` the set of all tags.
```python
t_min = min([P(t|w+c) for t in T])
T.union([t for t in 𝗧 if t < t_min])
```
Meaning to add all all tags, that the classifier believes more probable than the most unlikely tag that is considered anyways. I assume this might reduce precision and increase recall, but by how much is the question. I wonder if this has been considered and any point in the implementation, as i cannot find anything related in the comments or the paper.

**Comment by AngledLuffa** [comment]
There's a threshold count for a word to show up in known tags, I believe.
Therefore, if you only have a couple examples of a word, the novel RBS tag
can be chosen.  If you have many such examples, but RBS was not in the
training data, then it is correct that RBS is forbidden.  Hopefully that
doesn't happen often for words which show up often in the training data,
though - the idea is that a sufficient number of examples means all
realistic possibilities show up at least once.

You are correct that this is an efficiency improvement.

I personally don't remember any results.  @manning tells me that this
change occasionally led to errors as the tagger could never boldly ignore
its training data to apply a novel tag, but the same restrictions also
prevent errors when the tagger goes a little haywire, so the overall effect
on accuracy was neither positive or negative.

If you notice a common word being forbidden from a reasonable tag by this,
feel free to tell us.  As you've just seen, we occasionally add examples to
the training data to fix errors.

**Comment by gamer01** [comment]
Because of this constraints the classifier is sometimes forced to make a classification error as the ground truth class is not contained in the set of allowed tags. This makes the accuracy of the CoreNLP Tagger upper bounded.

For my dataset the bounds where 97.68% (total) 97.16% (known words) 99.78% (unknown words)

Since in my dataset there are many open-class tags, the unknown words have a higher bound. The more interesting bound is the one for the known words. I assume this bound can vary a lot between datasets. If the corpus is sufficiently large, the known words are probably seen with all their correct tags during training and therefore there will only very little errors.

**Comment by AngledLuffa** [comment]
It's kind of an open question what situations this will actually help.
However, the next release will include a flag to only use the constraints
if a word appears at least X times.  It does make the tagger significantly
slower to even set it to 2 (20% or so).

Another thing you could look at is `deterministicallyExpandTags`, which
currently only expands some verbs for English.  For example, "he cooked
dinner" and "dinner is cooked" use the same spelling of cooked, but two
different tags, so seeing one tag allows the other.

**Comment by gamer01** [comment]
I also tried to run the code without constraints at all (i cloned the repo and made many simplifications), but this causes even my desktop machine with 32 gig ram to run out of memory, for sentences with more than 100 words (which is often the case in my corpus, because this historic language has no real sentence boundaries).

This is because first all scoring windows are generated and than the viterbi is run instead of deleting the old windows on the fly and only keeping the current wavefront of the dynamic program. (in my case i also have a insanely large tagset 80+)

**Comment by AngledLuffa** [comment]
You can try this to see if it helps:

https://github.com/stanfordnlp/CoreNLP/commit/8da1176c52d37eb2d3a4a3b2323e90ce6cf69db7


 I'd also like to remind you about deterministallyExpandTags

https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/tagger/maxent/TestSentence.java#L844


If you know a few tags are always possible substitutes for each other, you
might be able to keep the threshold low in other situations.

**Comment by gamer01** [comment]
i already know about this function. I will definetly implement substitutes, but unfortunately i am no domain expert for midle lower german :D but i will try to do it a little datadriven.

Thanks for the linked commit. i might try to implement it in my code as well (i am so far derailed from your master, that there is no possibility to merge anything from your codebase :D)
