### ISSUE TITLE
POS tagging Asian name "Ye" as pronoun

### ISSUE THREAD

**Issue by bnomis** [stanfordnlp/CoreNLP#914]
"Ye" is a common family name in Asia. In the context of a name should be tagged NNP not as PRP. 

I attached some example sentences which show the effect.

[unknown-pronoun-ye.txt](https://github.com/stanfordnlp/CoreNLP/files/3394857/unknown-pronoun-ye.txt)

**Comment by manning** [comment]
Thanks, I've made some additions that hopefully will improve the situation with the next model release. Of course, it's tricky, since "Ye" is also an (archaic) pronoun. "He" as a family name is even trickier. 😉
