### ISSUE TITLE
How should I train my own NER model in Chinese?

### ISSUE THREAD

**Issue by hshsilver** [stanfordnlp/CoreNLP#916]
I want to recognize some proper noun from a series of text, **especially the company and organization.**
I have found an article about how to train a NER model in English on the official site.
Is it the same way to handle Chinese text?
Thanks for your reply~

**Comment by manning** [comment]
Yes. You need Chinese text word-segmented roughly as our segmenter does, and with words labeled for NER class.

**Comment by hshsilver** [comment]
> Yes. You need Chinese text word-segmented roughly as our segmenter does, and with words labeled for NER class.

Wait a minute......Do you mean:
1.  I have to add my custom dictionary in the segmenter step first. For instance, if I wanna add a company name "北京市亦楚科技有限公司", I should divide it to get "北京市/ 亦楚/ 科技/ 有限/ 公司 "and make each Chinese word single in a line. Finally, use the methods mentioned in [https://nlp.stanford.edu/software/segmenter-faq.html](https://nlp.stanford.edu/software/segmenter-faq.html)(How can I retrain the Chinese Segmenter?)
2. Next, according to [https://nlp.stanford.edu/software/crf-faq.html#a](https://nlp.stanford.edu/software/crf-faq.html#a)(How can I train my own NER model?), follow the steps to train NER model. For example, label the whole Chinese word string "北京市亦楚科技有限公司" as a "COMPANY".

BTW, I still have some questions about the details.
Q1: Is the dictionary have a word/ length limit? For example, can I just put the whole Chinese string "北京市亦楚科技有限公司" (Length: 11 hanzi) in the segmenter step?
Q2: If I train my own Chinese Segment and NER model, should I totally **replace** the original segment and model or just **add** them as extra additions?

Thanks again~

**Comment by AngledLuffa** [comment]
Sorry to have dropped this on the floor.  

For the segmenter step, you can take one of two approaches:

- Match the segmentation with what the segmenter currently produces.  It was trained on ctb9 data.  For example, this tends to segment "you xian gong si" into two words, such as

大众 汽车 有限 公司

- Retrain the whole segmenter and add your own interpretation of the company names.  In practice this means starting from ctb 9 if you want something similar to what already exists, or possibly using the universal dependencies dataset, which is freely available.

Once this is done, you want to use those tokens to label text with the appropriate NER labels.  What we mean by follow the proper segmentation is that you label each segment:

大众 COMPANY
汽车 COMPANY
有限 COMPANY 
公司 COMPANY

BUT you cannot simply provide a list of companies like this.  They need to be in complete sentences for the model to have any benefit.  So for example, you could label this sentence from Wikipedia, one word per line:

上汽   COMPANY
大众  COMPANY
汽车  COMPANY
有限  COMPANY
公司  COMPANY
（   O
简称   O
etc etc for 上汽大众或上汽大众汽车），是中德合资的汽车生产企业，也是中国改革开放以后第一家轿车合资企业

It is a LOT of work to build a dataset like this, but it is possible.  Another option is to find an existing dataset and add your text to that, but in that case you would need your labels to conform to the labels in the dataset (or redo some of the existing labels).

The specific questions you asked:

Q1:  The default dictionary length limit is 6.  See src/edu/stanford/nlp/wordseg/ChineseDictionary.java

Q2:  Unfortunately there is no way to add just a few sentences to either the existing segmenter or NER models.  (They use the same model code underneath, so updating that would be a 2 for 1)  So your choices are, work with the existing models, extend an existing dataset and retrain from there, or rebuild an entirely new dataset.

Another alternative would be to postprocess: for example, if Volkswagon (unlikely, but for the purposes of this example) is being mislabeled, you could use the regex ner, tokensregex, or some other regex function to identify that name.  If you build up a list of such names which are being misidentified, perhaps you can simply correct those to be the desired label.  Again, though, you would have to conform to the existing labels; our models produce ORGANIZATION for company names, for example.
