### ISSUE TITLE
NullPointerException in EntityMentionsAnnotator

### ISSUE THREAD

**Issue by reza-ebrahimi** [stanfordnlp/CoreNLP#917]
https://github.com/stanfordnlp/CoreNLP/blob/089ff022c5cb3df39a00965b30ef2e90a29c594e/src/edu/stanford/nlp/pipeline/EntityMentionsAnnotator.java#L312

Caused by: java.lang.NullPointerException
	at edu.stanford.nlp.pipeline.EntityMentionsAnnotator.annotate(EntityMentionsAnnotator.java:312)

entityMentionsLanguage is null

**Comment by AngledLuffa** [comment]
This should only happen if you are specifying a language we don't support.  If you're trying to add a new language, I suggest changing LanguageInfo to include the new language.

However, it also shouldn't crash because of such an event, so I'll check in a change.

**Comment by AngledLuffa** [comment]
f169375f9c7d3653cd659c9caa8064ce8d5be733
