### ISSUE TITLE
Something happened during my NER train process

### ISSUE THREAD

**Issue by hshsilver** [stanfordnlp/CoreNLP#918]
According to the official instruction[https://nlp.stanford.edu/software/crf-faq.html#deterministic](https://nlp.stanford.edu/software/crf-faq.html#deterministic)(How can I train my own NER model?)
, I use the provided file **jane-austen-emma-ch1.tsv and jane-austen-emma-ch2.tsv** to train and test.
Things go well, however, after 

> `java -cp stanford-ner.jar edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier ner-model.ser.gz -testFile jane-austen-emma-ch2.tsv`

Here comes an exception:

> `testFile=jane-austen-emma-ch2.tsv
> loadClassifier=ner-model.ser.gz
> Loading classifier from ner-model.ser.gz ... done [0.1 sec].
> Error on line 1: CHAPTER		O
> Exception in thread "main" java.lang.UnsupportedOperationException: Argument array lengths differ: [class edu.stanford.nlp.ling.CoreAnnotations$TextAnnotation, class edu.stanford.nlp.ling.CoreAnnotations$AnswerAnnotation] vs. [CHAPTER, , O]
> 	at edu.stanford.nlp.ling.CoreLabel.initFromStrings(CoreLabel.java:263)
> 	at edu.stanford.nlp.ling.CoreLabel.<init>(CoreLabel.java:150)
> 	at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter$ColumnDocParser.apply(ColumnDocumentReaderAndWriter.java:91)
> 	at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter$ColumnDocParser.apply(ColumnDocumentReaderAndWriter.java:64)
> 	at edu.stanford.nlp.objectbank.DelimitRegExIterator.parseString(DelimitRegExIterator.java:71)
> 	at edu.stanford.nlp.objectbank.DelimitRegExIterator.setNext(DelimitRegExIterator.java:67)
> 	at edu.stanford.nlp.objectbank.DelimitRegExIterator.<init>(DelimitRegExIterator.java:63)
> 	at edu.stanford.nlp.objectbank.DelimitRegExIterator$DelimitRegExIteratorFactory.getIterator(DelimitRegExIterator.java:128)
> 	at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter.getIterator(ColumnDocumentReaderAndWriter.java:58)
> 	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.setNextObjectHelper(ObjectBank.java:435)
> 	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.setNextObject(ObjectBank.java:419)
> 	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.<init>(ObjectBank.java:412)
> 	at edu.stanford.nlp.objectbank.ObjectBank.iterator(ObjectBank.java:250)
> 	at edu.stanford.nlp.sequences.ObjectBankWrapper.iterator(ObjectBankWrapper.java:45)
> 	at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyAndWriteAnswers(AbstractSequenceClassifier.java:1189)
> 	at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyAndWriteAnswers(AbstractSequenceClassifier.java:1133)
> 	at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyAndWriteAnswers(AbstractSequenceClassifier.java:1087)
> 	at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3053)
> `

Indeed, the provided file **jane-austen-emma-ch2.tsv** has three colomn. If there is something wrong with it, how can I use it correctly?

**Comment by hshsilver** [comment]
BTW, I am not familiar with "perl", so even when I try to add tab by 

> `perl -ne 'chomp; print "$_\tO\n"' jane-austen-emma-ch2.tok > jane-austen-emma-ch2.tsv`

There is still some error:
![image](https://user-images.githubusercontent.com/25773429/61844620-a40a1480-aed2-11e9-9de2-ea18c7378a83.png)

```
>  > perl -ne 'chomp; print "$_\tO\
> n"' jane-austen-emma-ch2.tok > jane-austen-emma-ch2.tsv
> Backslash found where operator expected at -e line 1, near "$_\"
>         (Missing operator before \?)
> Backslash found where operator expected at -e line 1, near "tO\"
> syntax error at -e line 1, near "tO\"
> Execution of -e aborted due to compilation errors.
```

**Comment by hshsilver** [comment]
I know what's wrong with my process.
The file provided contains three columns (divided by tab)
Just delete the middle column.

**Comment by hshsilver** [comment]
As for the 2nd error, I turn to CMD but not PowerShell, and change the code to:
[perl -ne "chomp; print qq{$_\tO\n}" jane-austen-emma-ch2.tok > jane-austen-emma-ch2.tsv](url)
Sometimes, **""** will bring trouble in certain environment......

**Comment by Greg-the-bunny** [comment]
As hshsilver mentioned, the middle column adds improper spacing.  There should only be one tab between the word and its associated tag.  As for how quickly the process for fixing that can be done, other than lengthy & time-consuming manual editing, I am not sure.
