### ISSUE TITLE
Sentiment Pipeline Score

### ISSUE THREAD

**Issue by darav37** [stanfordnlp/CoreNLP#920]
I read on the Stanford NLP website that the sentiment scores ran from 1-25 (most negative to most positive), does anyone know how I can access these scores and print them along with the sentiment itself for a given dataset?

**Comment by J38** [comment]
To the best of my knowledge the training data has the 5 point scale, so our software won't generate scores in the 1-25 range.  Where did you read scores ran from 1-25 ?

**Comment by darav37** [comment]
@J38  https://nlp.stanford.edu/sentiment/treebank.html

**Comment by darav37** [comment]
@J38 https://nlp.stanford.edu/sentiment/treebank.html      either way do you know how I could print out the 1-5 scores?

**Comment by J38** [comment]
The scores are in the `text` and `json` output formats.  

`java -Xmx5g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,sentiment -file example.txt`
