### ISSUE TITLE
Regexner is invalid?

### ISSUE THREAD

**Issue by hshsilver** [stanfordnlp/CoreNLP#922]
I try to follow the steps given by 
[https://nlp.stanford.edu/software/regexner.html](https://nlp.stanford.edu/software/regexner.html)
However, I cannot successfully get the named entity  "Bachelor of Arts" tagged as "DEGREE".

![image](https://user-images.githubusercontent.com/25773429/61941770-b5364c80-afca-11e9-9847-f1336254e7c3.png)

How to deal with it?
Thanks for your reply~

**Comment by AngledLuffa** [comment]
This isn't enough information to diagnose the problem.

**Comment by hshsilver** [comment]
I follow every step in the instruction.

 - 

`java -mx1g -cp '*' edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators 'tokenize,ssplit,pos,lemma,ner' -file JuliaGillard.txt`
I change "-mx1g" to "-mx8g".

 - Create "jg-regexner.txt" ,the content is 
```
Bachelor of Arts	DEGREE
Bachelor of Laws	DEGREE
```
Before every DEGREE there is a tab.

 - 
`java -mx8g -cp '*' edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators 'tokenize,ssplit,pos,lemma,ner,regexner' -file JuliaGillard.txt -regexner.mapping jg-regexner.txt`

 - Finally, I get the result in XML format. As you can see above. "Bachelor of Arts"'s NER is TITLE, O, O but not "DEGREE".

**Comment by J38** [comment]
Don't use the `regexner` annotator and try using `-ner.addditional.regexner.mapping`.

There is an example here under "Additional TokensRegexNER Rules":

https://stanfordnlp.github.io/CoreNLP/ner.html

**Comment by hshsilver** [comment]
@J38 Thanks to your information, I have tried this module to fit my requirements. However, I find something confusing. 
For instance, I have to add some whitespace in the string defined in *.rules in order to make my rules valid. In other words, if I just put the whole string without any whitespace, it does not work.
`上海易初莲花有限公司✘→上海 易 初 莲花 有限 公司✔️
`
How can I just use the constant string without any whitespace to recognize the named entities?

btw, I guess the additional ner process is related to the segmenter process. If it is true, how to improve it? Make them cut the string finer?

**Comment by J38** [comment]
The `TokensRegexNERAnnotator` expects rules over tokens, not characters.  So you need whitespace to divide the tokens.  

There is more info here about `RegexNER`:
https://stanfordnlp.github.io/CoreNLP/ner.html
