### ISSUE TITLE
StanfordCoreNLP 3.9.1 and StanfordCoreNLP 3.9.2

### ISSUE THREAD

**Issue by FengXuas** [stanfordnlp/CoreNLP#923]
Why is the server we set up Stanford CoreNLP 3.9.1, and the latest API is Stanford CoreNLP 3.9.2?

**Comment by J38** [comment]
Unfortunately the date on the demo html page included in the jar was not updated with the release.  I'll make a note to make sure that gets updated before future releases.  If you're using the 3.9.2 jar it's the 3.9.2 code.

**Comment by FengXuas** [comment]
A new question. 
For example, I get via the python interface:

(ROOT (S (NP (NN Water)) (VP (VP (VBZ is) (VP (VBN composed) (PP (IN of) (NP (NP (NN hydrogen)) (SBAR (WHNP (WDT which)) (S (VP (VBZ is) (NP (DT a) (NN gas))))))))) (CC and) (VP (VBZ is) (ADJP (RB very) (JJ flammable)))) (. .)))

While the webpage gives this one:

(ROOT ((S (NP (NN Water)) (VP (VBZ is) (VP (VBN composed) (PP (IN of) (NP (NP (NN hydrogen)) (SBAR (WHNP (WDT which)) (S (VP (VP (VBZ is) (NP (DT a) (NN gas))) (CC and) (VP (VBZ is) (ADJP (RB very) (JJ flammable)))))))))) (. .)))
Is there another switch to get the same constituency parse as on the webpage or the new parse is coming in a newer CoreNLP version?

Many thanks
