### ISSUE TITLE
Lemmatization doesn't work on corenlp.run

### ISSUE THREAD

**Issue by lengockyquang** [stanfordnlp/CoreNLP#926]
As i know, lemmatization will return the base form with different word forms. When i used corenlp.run to pos tag, lemmtize and ner, lemmatization seem doesn't work.
![image](https://user-images.githubusercontent.com/45225905/62355313-eff33400-b538-11e9-8898-c6a98d30fb2d.png)

I think it should return "Thank , Tom" instead of "thanks ....."

**Comment by J38** [comment]
This is just a failure of the lemmatizer in general to handle the word "thanks."
