### ISSUE TITLE
Commit hashes for older versions

### ISSUE THREAD

**Issue by matanster** [stanfordnlp/CoreNLP#927]
The latest two versions currently have a release page for them associated here on Github. Does anyone have the commit hashes for older versions? I could not find it on the version history page of the project. My current interest is actually version 3.5.0.

**Comment by J38** [comment]
I'm not sure every release perfectly matches a version of master.

You might start at `671b0bd652f16f9603355b3abcef9bc2dc642ec0` and look at versions around there.  I'm not entirely sure which one is the final one before the release jars were built.  But I would presume it's one of the commit on 2014-10-31.

**Comment by matanster** [comment]
Thanks a lot. I guess I can also compare to the [sources released for this version on maven](https://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/3.5.0/) to make sure!
