### ISSUE TITLE
‘document is too long’ in my service

### ISSUE THREAD

**Issue by FengXuas** [stanfordnlp/CoreNLP#929]
I use the default English model to build the service, the error message is ‘document is too long’, but there is no problem using the shift reduce parser model. How can I fix the default English model.

**Comment by J38** [comment]
Can you please provide more detailed error output.

**Comment by J38** [comment]
I can't tell from your message what the issue,  but the `-maxCharLength` determines max characters you can submit to the server in a request.  The `-timeout` specifies when the server gives up trying to annotate a document.
