### ISSUE TITLE
import edu.stanford.nlp.process.WordTokenFactory;

### ISSUE THREAD

**Issue by venusafroid** [stanfordnlp/CoreNLP#931]
hi,

I am using parser to get dependency parser.
lib_dir = os.path.join(params['base_path'], 'lib')
classpath = ':'.join([
        lib_dir,
        os.path.join(lib_dir, 'stanford_parser/stanford_parser.jar'),
        os.path.join(lib_dir, 'stanford_parser/stanford_parser-3.9.2-models.jar')])
command = 'javac -cp $%s lib/*.java' % classpath
os.system(command)

I have download http://nlp.stanford.edu/software/stanford_parser-full-2018-10-17.zip and http://nlp.stanford.edu/software/stanford-postagger-2018-10-16.zip. I can not find the package "edu.stanford.nlp.process".
How to fix it?

**Comment by AngledLuffa** [comment]
Surely it should be in the class jars in those zip files...

If not, you can always download java corenlp, which is mostly a superset of
those two packages.
