### ISSUE TITLE
How should I use KBP with Java API? 

### ISSUE THREAD

**Issue by hshsilver** [stanfordnlp/CoreNLP#932]
I found useful tools to get the relation underneath the texts on page [KBPAnnotator](https://stanfordnlp.github.io/CoreNLP/kbp.html#example-usage)
But there is no example of Java API, so I cannot directly get the result in the IDE console. 
Does this module support Java API?
Thanks for your reply~

**Comment by J38** [comment]
Please see: https://stanfordnlp.github.io/CoreNLP/api.html

**Comment by hshsilver** [comment]
In fact, I did not find how to use **Annotation** data structure to get the KBP result. 
I have tried to add "kbp" in the property file.
`# Pipeline options - lemma is no-op for Chinese but currently needed because coref demands it (bad old requirements system)
annotators = tokenize, ssplit, pos, lemma, ner, regexner, parse, coref,tokensregex, kbp

.........(omited)
# kbp
kbp.semgrex = edu/stanford/nlp/models/kbp/chinese/semgrex
kbp.tokensregex = edu/stanford/nlp/models/kbp/chinese/tokensregex
kbp.language = zh
kbp.model = none
`
However, there is no result of kbp.
What should I do to get the missing result?

**Comment by J38** [comment]
Make sure you are using Stanford CoreNLP 3.9.2 and the most recent Chinese properties file (which is included in the Chinese models jar).  Obviously add `kbp` to the annotators list.

It should work on this text: `巴拉克·奥巴马是美国总统。他在2008年当选`.

Note that failure on any given input text doesn't mean a wrong configuration, it is quite possibly algorithm failure which is common.

I'll post the correct properties for convenience:

```

# Pipeline options - lemma is no-op for Chinese but currently needed because coref demands it (bad old requirements system)
annotators = tokenize, ssplit, pos, lemma, ner, parse, coref,kbp

# segment
tokenize.language = zh
segment.model = edu/stanford/nlp/models/segmenter/chinese/ctb.gz
segment.sighanCorporaDict = edu/stanford/nlp/models/segmenter/chinese
segment.serDictionary = edu/stanford/nlp/models/segmenter/chinese/dict-chris6.ser.gz
segment.sighanPostProcessing = true

# sentence split
ssplit.boundaryTokenRegex = [.。]|[!?！？]+

# pos
pos.model = edu/stanford/nlp/models/pos-tagger/chinese-distsim/chinese-distsim.tagger

# ner
ner.language = chinese
ner.model = edu/stanford/nlp/models/ner/chinese.misc.distsim.crf.ser.gz
ner.applyNumericClassifiers = true
ner.useSUTime = false

# regexner
ner.fine.regexner.mapping = edu/stanford/nlp/models/kbp/chinese/gazetteers/cn_regexner_mapping.tab
ner.fine.regexner.noDefaultOverwriteLabels = CITY,COUNTRY,STATE_OR_PROVINCE

# parse
parse.model = edu/stanford/nlp/models/srparser/chineseSR.ser.gz

# depparse
depparse.model    = edu/stanford/nlp/models/parser/nndep/UD_Chinese.gz
depparse.language = chinese

# coref
coref.sieves = ChineseHeadMatch, ExactStringMatch, PreciseConstructs, StrictHeadMatch1, StrictHeadMatch2, StrictHeadMatch3, StrictHeadMatch4, PronounMatch
coref.input.type = raw
coref.postprocessing = true
coref.calculateFeatureImportance = false
coref.useConstituencyTree = true
coref.useSemantics = false
coref.algorithm = hybrid
coref.path.word2vec =
coref.language = zh
coref.defaultPronounAgreement = true
coref.zh.dict = edu/stanford/nlp/models/dcoref/zh-attributes.txt.gz
coref.print.md.log = false
coref.md.type = RULE
coref.md.liberalChineseMD = false

# kbp
kbp.semgrex = edu/stanford/nlp/models/kbp/chinese/semgrex
kbp.tokensregex = edu/stanford/nlp/models/kbp/chinese/tokensregex
kbp.language = zh
kbp.model = none

# entitylink
entitylink.wikidict = edu/stanford/nlp/models/kbp/chinese/wikidict_chinese.tsv.gz
```
