### ISSUE TITLE
Editing PTB Tree format data with editable tree

### ISSUE THREAD

**Issue by karimkhanvi** [stanfordnlp/CoreNLP#934]
I have my own data in PTB format like this. 

(1 (2 (2 German) (2 nurse)) (2 (2 (2 sentenced) (2 (2 to) (2 (3 life) (2 (2 in) (2 prison))))) (2 (2 for) (2 (2 murdering) (2 (2 85) (2 patients))))))

I created this data using Stanford sentiment tagger. But I want to improve the dataset accuracy by manual annotation.

I want this to display on a tree and edit the sentiment values. 

Is it possible to display the above sentences similar to http://nlp.stanford.edu:8080/sentiment/rntnDemo.html editable tree? Any reference for this is highly appreciated.

**Comment by AngledLuffa** [comment]
I'm sorry, but we don't have a publicly available tool.
