### ISSUE TITLE
Let's POS tagged as possessive when preceded by a quote

### ISSUE THREAD

**Issue by bnomis** [stanfordnlp/CoreNLP#935]
Probably a tagging issue in the POS training data. When `Let's` is preceded with a quote as in `"Let's`, the `'s` is tagged as possessive rather than a pronoun. See below.

```shell
Let's go fishing  
Let = VB  
's = PRP  
go = VB  
fishing = NN  
```

```shell
"Let's go fishing  
" = ``  
Let = VB  
's = POS  
go = VB  
fishing = NN  
```

**Comment by AngledLuffa** [comment]
Which tool?  Corenlp using the pos annotator?

**Comment by bnomis** [comment]
@AngledLuffa Yes CoreNLP POS annotator

**Comment by AngledLuffa** [comment]
Yes, this is definitely a training data issue.

There are a few instances with the correct tagging, but also a few with
incorrect tagging:

``_`` Let_VB 's_POS close_VB the_DT door_NN ,_, ''_'' said_VBD the_DT
judge_NN as_IN he_PRP climbed_VBD to_TO his_PRP$ bench_NN ._.

``_`` The_DT strategy_NN is_VBZ `_`` Let_VB 's_POS vote_VB ._. '_'' ''_''

At_IN 5:40_CD p.m._NN ,_, scheduled_VBN game_NN time_NN having_VBG
passed_VBN ,_, some_DT fans_NNS chanted_VBD ``_`` Let_VB 's_POS Play_NNP
Ball_NNP ._. ''_''

(For that matter, why is Play Ball labeled NNP?)

**Comment by AngledLuffa** [comment]
Anyway, as long as we are training from PTB, this is impossible to fix unless we fix the incorrect labels in PTB.  We have discussed doing that, though
