### ISSUE TITLE
Null Pointer Exception in CustomNER

### ISSUE THREAD

**Issue by NickSadler2018** [stanfordnlp/CoreNLP#937]
I'm working on upgrading from 3.7.0 to 3.9.2, but after upgrading, I've been receiving a Null Pointer Exception that's throwing an error. However, after debugging, I've identified this line https://github.com/stanfordnlp/CoreNLP/blob/eddd12c73a7d77ea723c44c3513dab350dc11175/src/edu/stanford/nlp/pipeline/EntityMentionsAnnotator.java#L330 as causing the null pointer. This is code decompiled from the CoreNLP jar files, but for some reason when I remove this line, the null pointer ceases to be an issue, although I'm not sure why the language check would cause a null pointer, but it's a blocker for now.

Any guidance on how to overcome this null pointer or why it could exist? Thanks!

**Comment by AngledLuffa** [comment]
FWIW this should already be fixed in the next version.

**Comment by AngledLuffa** [comment]
If you don't want to recompile and/or wait for the new version, you can specify the language you are working on and it will not crash there.

**Comment by ElliottYan** [comment]
Hi @AngledLuffa , can you tell a bit more about how to specify language in command line? 
I met the same error when using ner for chinese in v3.9.2

**Comment by AngledLuffa** [comment]
Did you try these steps?

https://stanfordnlp.github.io/CoreNLP/human-languages.html

A new version should be released in a few days which includes the bugfixes
I mentioned.
