### ISSUE TITLE
Nondeterminism in parse annotator results

### ISSUE THREAD

**Issue by alexey-tarasov-irl** [stanfordnlp/CoreNLP#938]
I'm running into a problem, where `parse` annotator (with `englishRNN.ser.gz` model) doesn't always produce the same dependency graph for the same input. For instance, if I annotate a sentence "X should not be 0." ten times in a loop, each iteration can end with one of the following parses (the difference is marked in **bold**):

-> be/VB (root)
  -> X/NNP (nsubj)
  -> should/MD (aux)
  -> not/RB (neg)
  **-> 0/CD (xcomp)**
  -> ./. (punct)

-> be/VB (root)
  -> X/NNP (nsubj)
  -> should/MD (aux)
  -> not/RB (neg)
  **-> 0/CD (nmod:tmod)**
  -> ./. (punct)

[Here is the code to reproduce the issue](https://github.com/stanfordnlp/CoreNLP/files/3529531/Determinism.txt).

I looked into it, and it seems like it might be caused by a rounding error. From what I see in debugger, `parse` method of `RerankingParserQuery` class first gets a list of parses and then reranks them. In `bestKParses` both annotations are present, but the one with 0-xcomp is always ranked above one with 0-nmod:tmod (parses in question are 0 and 15):

![image](https://user-images.githubusercontent.com/54396013/63502724-0d774600-c4c6-11e9-97dc-4b1c6f2d3faa.png) 

Then, these parses are getting re-ranked by the following line in `rerank` method of `RerankingParserQuery`:

`score = op.baseParserWeight * score + rerankerQuery.score(scoredTree.object());`

The first term is the score contained in `bestKParses`, but since `score` factor is equal to zero in `englishRNN.ser.gz` model, the new score is effectively the score given by `rerankerQuery`.  The two annotations I'm concerned about seem to be getting the same score, resulting in a tie. It's not a problem, because `Collections.sort()` is stable, so the correct annotation ends up at the top and is getting returned as the resulting annotation by `getBestParse` method (see 0 and 3):

![image](https://user-images.githubusercontent.com/54396013/63503385-449a2700-c4c7-11e9-96fc-d172683c6af3.png)

So far so good, but if I repeat the same in a loop, there comes an iteration where scores in `bestKParses` are the same as before, but scores in `rerank` seem to exhibit something that looks like a rounding/truncation error at some deeper level in the execution stack. For instance, I would expect the parse at position 0 to get a score of 2.1485035452860854, but it has 2.148503545286086 instead, which pushes it to the top of the list and makes it the annotation that is actually returned from the pipeline:

![image](https://user-images.githubusercontent.com/54396013/63504650-e4f14b00-c4c9-11e9-9570-3125dcc4be95.png)

I'm running JDK 1.8 and Stanford CoreNLP 3.9.2.

Let me know if I can help with anything else to help to chase it up.

**Comment by alexey-tarasov-irl** [comment]
@J38 I had a few spare minutes today to look into it, and it seems I know what's happening. 

Unless I'm misunderstanding something basic, the bug is to do with floating point precision, while summing doubles, changing their order in lines 92-96 of `DVParserCostAndGradient`:
```double score = 0.0;
for (Tree node : scores.keySet()) {
  score += scores.get(node);
  //log.info(Double.toString(score));
}
```
I confirmed with more detailed logging, that for both `score = 2.1485035452860854` and `score = 2.148503545286086` the `scores.get(node)` values were the same, but came in different order. Why exactly the order is different, is probably a separate issue, but it seems to me that having different sums depending on the order of terms is clearly a bug. Created a pull request #946.

**Comment by AngledLuffa** [comment]
Thanks for digging into this.  I left a brief comment on the pull request,
but I'll replicate it here for posterity:

Do you think these changes need to be pushed further down into the score
functions? There are lots of matrix operations using floating points in
this module. Was the only issue you found the different ordering as a
result of the Set?

**Comment by alexey-tarasov-irl** [comment]
Thanks for looking at my suggestion so quickly.

Non-deterministic ordering was the only issue I encountered. For this particular issue, it seems to me that there is no need for going deeper, as the scores themselves were deterministic (i.e. the same in both cases). But you're right, issues like this might be hiding somewhere else in the codebase as well.

**Comment by AngledLuffa** [comment]
Our public github repo is actually a mirror of part of our internal github.  I integrated this patch into our private repo.  Thanks!
