### ISSUE TITLE
Stemmer class missing from Maven Central

### ISSUE THREAD

**Issue by chairbender** [stanfordnlp/CoreNLP#943]
As per the instructions here for Maven: https://stanfordnlp.github.io/CoreNLP/download.html

I've added the 2 dependencies to my project for the core classes and the models. However, they do not appear to contain the Stemmer class (https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/process/Stemmer.java) so I can't perform stemming.

I've even downloaded these jars directly from Maven Central and validated that neither the core JAR nor the models JAR has this Stemmer class.

Why is this missing from the JAR? Should I be using a different class to perform stemming?

**Comment by AngledLuffa** [comment]
Look for Morphology instead

https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/process/Morphology.java

**Comment by chairbender** [comment]
thank you!
