### ISSUE TITLE
Running quote annotator directly

### ISSUE THREAD

**Issue by BvdM0** [stanfordnlp/CoreNLP#944]
Hi,

I'm planning on using a different software for coreference (HuggingFace's neuralcoref), but then CoreNLP for quote attribution. I'm trying to figure out what input the CoreNLP quote annotator needs (so that I can massage my HuggingFace output to meet those requirements).

Before, when I was using the CoreNLP coreference annotator, running this from Terminal would work well:

`java -cp "*" -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,custom.lemma,ner,depparse,coref,quote -file input.txt -outputFormat text`

To get an acceptable input file for to use on 'quote', I tried running the same code but without quote annotator, and exporting as xml:

`java -cp "*" -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,depparse,coref -file input.txt -outputFormat xml`

I then took the output file (input.txt.xml) and fed it into the quote annotator directly as follows:

`java -cp "*" -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators quote -file input.txt.xml -outputFormat text`

However, this gave me the following error:

`Exception in thread "main" java.lang.IllegalArgumentException: annotator "quote" requires annotation "EntityMentionIndexAnnotation". The usual requirements for this annotator are: tokenize,ssplit,pos,lemma,ner`

What is the correct kind of file to feed directly into the quote annotator?

Any help much appreciated - thanks!

**Comment by AngledLuffa** [comment]
I don't believe there's any existing file input format which will convert
all of the data needed to something usable by QuoteAnnotator.  AFAIK it
doesn't read XML in the way you are attempting.  You'd need to use the API
to use QuoteAnnotator with a different source of annotations.
Alternatively, you could write a custom annotator to call HuggingFace from
within CoreNLP and convert that back to the annotation types used in the
pipeline.  Either way, it's probably going to be a bit of an undertaking to
interface the two with each other.
