### ISSUE TITLE
Chinese POS Tagger Tags Text as URL

### ISSUE THREAD

**Issue by bnomis** [stanfordnlp/CoreNLP#947]
I guess this is an error in the training data. 

When using the Chinese tagger - on text which includes English. The English phrase below get tokens tagged as URL.

I'm also surprised to see a URL tag - I can't find that tag documented anywhere.

```
I learned a lot about chemisty. The terrible
I = PN
learned = VV
a = CD
lot = NN
about = URL
chemisty. = URL
The = DT
terrible = NN
```

**Comment by AngledLuffa** [comment]
It's not documented, but stuff like this is scattered throughout the
training data:

URL 51．com

There's not really any English, so it's not surprising that doesn't work
well.
