### ISSUE TITLE
Treebank Corpus

### ISSUE THREAD

**Issue by debadityamandal** [stanfordnlp/CoreNLP#948]
How to create tree corpus from a sentence?I have created a model using RNTN and the model trained by stanford sentiment treebank train dataset.I have to test with new sentence.Please help me.
Thank you

**Comment by AngledLuffa** [comment]
Depends on what you're using it for, I suppose.

Simplest thing to do is to put it through CoreNLP.  Specify your new parser
and sentiment model using the -parse.model and -sentiment.model flags
