### ISSUE TITLE
entitymentions  doesn't return entity built using Regexner

### ISSUE THREAD

**Issue by maljarbou** [stanfordnlp/CoreNLP#950]
Hello all, I loaded my custom tags in the pipeline, but I can't get the entities with the new tags.
here is my code:
```
Properties props = new Properties();
props.put("annotators", "tokenize, ssplit, pos, lemma, ner, regexner");
String rules = Test.class.getResource("/rules.txt").getPath();
props.put("regexner.mapping", rules);
StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
CoreDocument document = new CoreDocument(text);
pipeline.annotate(document);
List<CoreEntityMention> entityMentions = document.entityMentions();
for(CoreEntityMention em: entityMentions){
    System.out.printf("Entity: %s - Type: %s\n", em.text(), em.entityType());
}
```
however, when I iterate the token and see the tags each token got, I can see the regexner is working, But most if not all of my custom tags are 2 or more words. What I want is when i call the `document.entityMentions()` I get everything, default tags and custom tags.

I need help please!

**Comment by J38** [comment]
There is a write up here about the NER pipeline: https://stanfordnlp.github.io/CoreNLP/ner.html

You should set properties for the `ner.additional.regexner` sub-annotator.
