### ISSUE TITLE
PoS tagging: noun-verb confusion

### ISSUE THREAD

**Issue by lguillou** [stanfordnlp/CoreNLP#952]
Hi,

When I run PoS tagging for the sentence "Tom is an idiot.", "idiot" is tagged as VB, not NN.

Tom NNP
is VBZ
an DT
idiot VB
. .

If I replace "idiot" with another noun such as "extrovert/angel/etc.", the tagging is correct, so the issue is not systematic.

I'm using version 3.9.2, with the models from 2018-10-05, and am using the english-left3words-distsim.tagger model.

**Comment by AngledLuffa** [comment]
It looks like there was a mis-tagging of `idiot` in one of our training
files.  It is now fixed, so the next time the models are rebuilt, it will
hopefully not make this error.
