### ISSUE TITLE
Latest Spanish model detects Countries as Brands

### ISSUE THREAD

**Issue by sa-** [stanfordnlp/CoreNLP#953]
Hey team,

I'm getting some unexpected behavior while trying to recognize countries in Spanish - could you please have a look? Details below:

Model downloaded from: http://nlp.stanford.edu/software/stanford-spanish-corenlp-models-current.jar
Model Last Updated: 2019-08-27
Using these dependencies: 
* `edu.stanford.nlp:stanford-corenlp:3.9.2:models-spanish`
* `edu.stanford.nlp:stanford-corenlp:3.9.2:models`
* `edu.stanford.nlp:stanford-corenlp:3.9.2`

Reproduce this error by running this snippet:
```
    Properties props = new Properties();
    props.setProperty("annotators", "tokenize,ssplit,ner");
    props.setProperty("tokenize.language", "es");
    props.setProperty("ner.model", "edu/stanford/nlp/models/ner/spanish.ancora.distsim.s512.crf.ser.gz");
    props.setProperty("ner.applyNumericClassifiers", "false");
    props.setProperty("ner.useSUTime", "false");
    props.setProperty("ner.applyFineGrained", "false");
    props.setProperty("ner.language", "es");
    StanfordCoreNLP nlp = new StanfordCoreNLP(props);

    CoreDocument document = new CoreDocument("El texto contiene Alemania e Inglaterra");
    nlp.annotate(document);
    document.entityMentions().stream().forEach(e -> System.out.println(e.toString() + ", " + e.entityType()));
```

This will print out
```
Alemania, ORGANIZATION
Inglaterra, ORGANIZATION
```

Which is incorrect, because Germany and England should be COUNTRY, not ORGANIZATION

Warm regards.

**Comment by AngledLuffa** [comment]
The NER model relies heavily on context, and this isn't a typical context
for a sentence.  Do you have more examples?

**Comment by AngledLuffa** [comment]
Further investigating the training data, it looks like it has a lot of
sports talk, and generally Germany or England are tagged as ORG when
referring to the sports team.  There are a few cases of both of those words
being LUG (eg lugar -> place), but ORG is also quite common.  I guess if
you put the words in a context such as "I am going to Germany" it might get
them correct, and otherwise ORG looks pretty good to the model.

**Comment by sa-** [comment]
Thank you very much for looking into this.

Cheers.
