### ISSUE TITLE
ClassifierDemo.java : Cannot find the file examples/cheeseDisease.train

### ISSUE THREAD

**Issue by emmanuel-D** [stanfordnlp/CoreNLP#960]
Hello,

I am trying to implement a code to train my own Model like the code in `CoreNLP/src/edu/stanford/nlp/classify/demo/ClassifierDemo.java`, but I cannot find the file located in `examples/cheeseDisease.train` in order to prepare my own train file.

**Comment by AngledLuffa** [comment]
It's not included in corenlp.  It's in the expected directory in the
classifier distribution:

https://nlp.stanford.edu/software/classifier.shtml
