### ISSUE TITLE
CRAN/R CoreNLP fails to initialise quotes annotator

### ISSUE THREAD

**Issue by BvdM0** [stanfordnlp/CoreNLP#963]
Hi,

I've managed to get CoreNLP running in R using a custom properties file. The only problem is that when I initialise CoreNLP every annotator loads _except_ for quote, which is what I really need.

For reference, this is my properties file, saved in my working directory as StanfordCoreNLP.properties:
`annotators = tokenize,ssplit,pos,lemma,ner,depparse,coref,quote`

This is the code I've been using:
```
library(rJava)
library(coreNLP)
setwd("~/Desktop/University/Thesis/Misc/Stanford/R/R project")`
initCoreNLP("~/Desktop/University/Thesis/Misc/Stanford/stanford-corenlp-full-2018-10-05", type = "english", parameterFile = "StanfordCoreNLP.properties", mem = "15g")
```

What I get after running the last command is:
```
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: StanfordCoreNLP.properties ... found.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.7 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.2 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.6 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.6 sec].
[main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
[main] INFO edu.stanford.nlp.time.TimeExpressionExtractorImpl - Using following SUTime rules: edu/stanford/nlp/models/sutime/defs.sutime.txt,edu/stanford/nlp/models/sutime/english.sutime.txt,edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
[main] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 580704 unique entries out of 581863 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_caseless.tab, 0 TokensRegex patterns.
[main] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 4869 unique entries out of 4869 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_cased.tab, 0 TokensRegex patterns.
[main] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 585573 unique entries from 2 files
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator depparse
[main] INFO edu.stanford.nlp.parser.nndep.DependencyParser - Loading depparse model: edu/stanford/nlp/models/parser/nndep/english_UD.gz ... 
[main] INFO edu.stanford.nlp.parser.nndep.Classifier - PreComputed 99996, Elapsed Time: 8.79 (s)
[main] INFO edu.stanford.nlp.parser.nndep.DependencyParser - Initializing dependency parser ... done [10.5 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
[main] INFO edu.stanford.nlp.coref.statistical.SimpleLinearClassifier - Loading coref model edu/stanford/nlp/models/coref/statistical/ranking_model.ser.gz ... done [0.6 sec].
[main] INFO edu.stanford.nlp.pipeline.CorefMentionAnnotator - Using mention detector type: dependency
```

As you can see there's no error, it just stops. As a result the annotated file is returned without a section for quotes/speakers.

Any help would be much appreciated!

Thanks

**Comment by AngledLuffa** [comment]
Perhaps it's not reading the expected args file.  I guess printing out the
expected annotator list would be a useful feature, but it currently doesn't
do that.  Instead, you can test if it's loading the correct properties by
adding some deliberately incorrect argument like

pos.model asdf.ser.gz

You should see some line like this when it loads the quote annotator:

[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator
quote

**Comment by BvdM0** [comment]
You're right, I can even replace the whole thing with jibberish and it returns the same result. I tried changing working directory to my .jar file location, and putting the .properties file in there. Same problem.  

[This](https://github.com/statsmaths/coreNLP/issues/10) says it's an rJava issue - I'm using rJava 0.9-11 on a MacBook with Java 9.0.4:

```
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

I can't tell if my rJava is 64-  or 32-bit, or how I'd find the 64-bit version if it isn't. Do you think my rJava/Java versions is likely to be the source of the problem?

**Comment by AngledLuffa** [comment]
It seems very likely that it's finding a properties file elsewhere in your
classpath and loading that instead.  Try renaming your properties file to
something unique like "bvd.properties" or whatever and using that name
instead.

**Comment by BvdM0** [comment]
Thanks, that did help. It does now initialise quote annotator and when I export output to a .txt file I can see the extracted quotes. e.g.

```
Extracted quotes: 
[QuotationIndex=1, CharacterOffsetBegin=894, Text=“suspicionless stops”, Speaker=Unknown]
[QuotationIndex=2, CharacterOffsetBegin=925, Text=“the practice is a manifestation of structural Islamophobia, which is experienced as harassment”, Speaker=Unknown]
```

But when I made an R obj I couldn't find the quotes anywhere. I tried exporting to an .xml file and searching in a text editor - no quotes. 

I've run these three lines separately:

```
obj <- annotateFile(file("sample2.csv"),format = "obj") 
annotateFile(file("sample2.csv"),format = "xml",outputFile = "output2.xml") 
annotateFile(file("sample2.csv"),format = "text",outputFile = "output2.txt") 
```

I get the same error in all three cases:

```
[main] INFO edu.stanford.nlp.pipeline.QuoteAnnotator - Setting quotes.
[main] WARN edu.stanford.nlp.quoteattribution.Sieves.MSSieves.BaselineTopSpeakerSieve - Watch out, there's an empty top speakers list!
```

I'm confused because, despite this error, I do get the desired output for txt, just not in the other cases. It may be relevant that, in the text file, all speakers are returned as 'Unknown'.

**Comment by AngledLuffa** [comment]
We don't really know anything about the R interface.  If you find something
wrong with the Java usage of that annotator, we'll investigate that.
