### ISSUE TITLE
Annotating a .csv

### ISSUE THREAD

**Issue by CrunchyLettuce** [stanfordnlp/CoreNLP#967]
Hi there,

Is there an easy way to annotate a .csv file using CoreNLP in the command line?

My .csv is two columns: 'article_id' and 'text'. I want to annotate the content of 'text' line by line, producing a list of quotes in each article (with the quote annotator), each with an 'id' value corresponding to the article the quote was in (i.e. the original 'id' column in the csv). 

I can't find anything online about annotating csv - all the examples seem to use .txt files.

Thanks very much for your help!

**Comment by AngledLuffa** [comment]
That sounds like a job for some preprocessing

**Comment by BvdM0** [comment]
You didn't answer my question, though. 

Is it not possible then? Do I have to work with a list of text documents?

**Comment by AngledLuffa** [comment]
Sorry for any ambiguity.  The answer is that this is a job for *you* to do
some preprocessing.  As far as I know, there is no mechanism for corenlp to
read csv documents as individual sentences or documents.  However, you can
hopefully quickly do something like what you've described with the API if
you are using Java.  If not, you can also send documents one at a time to a
server, or you can probably find some way to structure one or more text
input files so it gives you the result you want.
