### ISSUE TITLE
How we batch to train own model?

### ISSUE THREAD

**Issue by yolearn** [stanfordnlp/CoreNLP#974]
I am trying to train a own ner, but I always got out of memory.
Therefore, I try use batch training. 
The following is my step and cmd.
- java -cp "stanford-ner.jar" -mx4g edu.stanford.nlp.ie.crf.CRFClassifier -prop train/prop.txt

But after my first batch training, I got the domain.gz. How I train second batch based on domain.gz.
Because my input of cmd is stanford-ner.jar.

**Comment by AngledLuffa** [comment]
Unfortunately, the NER does not support this kind of training followed by
training another batch.

One thing that might make a difference is if you run it with fewer
threads.  Apparently each thread consumes quite a bit of memory on its
own.

-multiThreadGrad=___
