### ISSUE TITLE
Stanford Classifier: What is the max value of the scores for each datum ?

### ISSUE THREAD

**Issue by emmanuel-D** [stanfordnlp/CoreNLP#976]
I am using the `ColumnDataClassifier.java  ` and for each of my test Datum and I get following scores like in the bellow screenshot:

<img width="896" alt="Screenshot 2019-12-07 at 10 04 11" src="https://user-images.githubusercontent.com/37305687/70420758-b0999e80-1a68-11ea-85b3-6f78f9e02a11.png">

**My issue** is: What is the **max value of the score** that can reach each test Datum ?
And it is possible to set this **max-score-value** to something like **10**. The purpose is to establish somme statistics on my **test Datum**.

**Comment by emmanuel-D** [comment]
@AngledLuffa any idea on a way to achieve that?

**Comment by AngledLuffa** [comment]
At a high level, those are just the scores produced by the underlying
classifier.  So if the classifier algorithm you use is limited in its
range, the scores will also be limited.  There's no way to specifically
guarantee <= 10.0 and I'm not sure why you would want to.  However, you
could always go into the code for the classifier used and adjust it to cap
scores at 10.0.  Or add your own classifier built on top of an existing
classifier which re-scales the scores the way you want.
