### ISSUE TITLE
Bad Sentence For English SR Parser

### ISSUE THREAD

**Issue by J38** [stanfordnlp/CoreNLP#978]
This sentence generates a crash when trying to train the English SR Parser:

```
( (S (NP-SBJ (DT the) (NNPS knights) (NNP inn)) (VP (VBD was) (ADJP-PRD (ADJP (JJ small)) (ADJP (RB very) (JJ small)))) (. .)) (FRAG (PRN (S (NP-SBJ (PRP i)) (VP (VBP mean)))) (NP (CD 1) (NN room)) (PP (IN in) (NP (DT every) (NN room))) (. !)) (UCP (S (NP-SBJ (PRP it)) (VP (VBD was) (ADJP-PRD (JJ cozy)) (NP-ADV (DT a) (JJ little)))) (CC and) (NP (DT a) (JJ small) (NN tv)) (. .)) )
```

**Comment by J38** [comment]
To be more specific, it produces an error about "expects binarized tree" when loading, so it won't even begin training...I guess binarizing this tree somehow causes a problem so might not even be the SR code that is the issue...

**Comment by AngledLuffa** [comment]
That is almost definitely the case.  Whatever is being used for binarization is not happily binarizing the tree.  It recursively checks that all of the trees are leaves, preterms, 1 child or 2 children at this point

**Comment by AngledLuffa** [comment]
so there's a bug or failed assumption in the treebinarizer

this is the result of binarizing that tree
```
  (S
    (NP (DT the)
      (@NP (NNPS knights) (NNP inn)))
    (@S
      (VP (VBD was)
        (ADJP
          (ADJP (JJ small))
          (ADJP (RB very) (JJ small))))
      (. .)))
  (FRAG
    (PRN
      (S
        (NP (PRP i))
        (VP (VBP mean))))
    (@FRAG
      (NP (CD 1) (NN room))
      (@FRAG
        (PP (IN in)
          (NP (DT every) (NN room)))
        (. !))))
  (UCP
    (@UCP
      (@UCP
        (S
          (NP (PRP it))
          (VP
            (@VP (VBD was)
              (ADJP (JJ cozy)))
            (NP (DT a) (JJ little))))
        (CC and))
      (NP (DT a)
        (@NP (JJ small) (NN tv))))
    (. .)))
```

**Comment by AngledLuffa** [comment]
seems that each of the three sentence pieces of this "sentence" are treated as a separate piece and all put at the root level.

**Comment by AngledLuffa** [comment]
for reference, here is the tree before it gets binarized
```
(ROOT
  (S
    (NP (DT the) (NNPS knights) (NNP inn))
    (VP (VBD was)
      (ADJP
        (ADJP (JJ small))
        (ADJP (RB very) (JJ small))))
    (. .))
  (FRAG
    (PRN
      (S
        (NP (PRP i))
        (VP (VBP mean))))
    (NP (CD 1) (NN room))
    (PP (IN in)
      (NP (DT every) (NN room)))
    (. !))
  (UCP
    (S
      (NP (PRP it))
      (VP (VBD was)
        (ADJP (JJ cozy))
        (NP (DT a) (JJ little))))
    (CC and)
    (NP (DT a) (JJ small) (NN tv))
    (. .)))
```

**Comment by AngledLuffa** [comment]
where is this tree from?

**Comment by AngledLuffa** [comment]
from @J38 : this is an ewt tree

**Comment by AngledLuffa** [comment]
There are several trees in EWT which have more than one subtree under root.  I removed those trees from the training data and adjusted the srparser training code to eliminate any trees which don't wind up binarized.  Still to do: we should figure out how to handle trees like this in the TreeBinarizer, and we should complain to whoever owns EWT about the issues with their data.
