### ISSUE TITLE
TimeAnnotator should have a 3-argument parameter

### ISSUE THREAD

**Issue by sinistersnare** [stanfordnlp/CoreNLP#98]
Hey, Im working on a project using CoreNLP, and SUTime, specifically. The TimeAnnotator class has three constructors, the Default, the constructor which initializes with properties, and a constructor to silence log output. There is currently no way to both initialize properties *and* silence log output. I propose there to be a 4th, 3-argument constructor `TimeAnnotator(String name, Properties props, boolean quiet)` which solves this issue.

I would send a PR, but wanted feedback first, and am quite busy, so if anyone else wants to do this, please go on ahead.

**Comment by manning** [comment]
Seems fair.  Added.

**Comment by sinistersnare** [comment]
Thanks!
