### ISSUE TITLE
What's the 'speaker' attribute in the token output?

### ISSUE THREAD

**Issue by lingvisa** [stanfordnlp/CoreNLP#982]
I am testing CoreNLPClient with the sentence "Apple is great" with the following output:

Starting server with command: java -Xmx8G -cp /Users/congminmin/nlp/stnlp/stanford-corenlp-full-2018-10-05/* edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 60000 -threads 5 -maxCharLength 100000 -quiet True -serverProperties StanfordCoreNLP.properties -preload [tokenize]
{'index': 1, 'word': 'apple', 'originalText': 'apple', 'lemma': 'apple', 'characterOffsetBegin': 0, 'characterOffsetEnd': 5, 'pos': 'NN', 'ner': 'O', 'speaker': 'PER0', 'before': '', 'after': ' '}
{'index': 2, 'word': 'is', 'originalText': 'is', 'lemma': 'be', 'characterOffsetBegin': 6, 'characterOffsetEnd': 8, 'pos': 'VBZ', 'ner': 'O', 'speaker': 'PER0', 'before': ' ', 'after': ' '}
{'index': 3, 'word': 'good', 'originalText': 'good', 'lemma': 'good', 'characterOffsetBegin': 9, 'characterOffsetEnd': 13, 'pos': 'JJ', 'ner': 'O', 'speaker': 'PER0', 'before': ' ', 'after': ''}

What are 'ner', 'speaker' in the output?

**Comment by mcavdar** [comment]
It seems that you put [quote](https://stanfordnlp.github.io/CoreNLP/quote.html) annotator in properties file. More information about quote annotator can be found: https://nlp.stanford.edu/pubs/muzny2017twostage.pdf
