### ISSUE TITLE
Are these latest Chines model significantly worse than the Stanford online parser?

### ISSUE THREAD

**Issue by lingvisa** [stanfordnlp/CoreNLP#985]
I tested the latest Chinese CoreNLP 3.92 version, and found the results are quite horrible. Here are few examples:

我的朋友：always tags "我的" as one NN token.
我的狗吃苹果： ‘我的狗’ tagged as one NN token.
他的狗吃苹果：'狗吃' tagged as one NN token.
高质量就业成时代: '就业' tagged as VV

When I compared them with the results from http://nlp.stanford.edu:8080/parser/index.jsp, surprisingly, the results of those examples are all right. Why is that? Are the models different? Is there a bug in the new 3.92 version model?

**Comment by AngledLuffa** [comment]
That doesn't sound right.  How are you running the tool?

**Comment by lingvisa** [comment]
I found the reason, because it is using CTB model. PKU model doesn't have this issue for those examples. Trying to switch the parameter to use PKU model. Really, by default it should PKU model. CTB horrible!

**Comment by AngledLuffa** [comment]
The online version is using an older model with fewer inaccuracies.  I'll
try to see if we can update it for the next release

**Comment by AngledLuffa** [comment]
I built a new model using ctb9 segmentation data (although the dictionary
has not been updated with the newer ctb).  It will be included in the next
release.  Also, until then it's here, in case you want to take a look:

https://nlp.stanford.edu/~horatio/ctb9.train.chris6.ser.gz

**Comment by lingvisa** [comment]
That's great! I just took a test, and it reports an error message for data format. Should i compressed myself?

 java -mx2g -cp ./*: edu.stanford.nlp.ie.crf.CRFClassifier -sighanCorporaDict ./data -textFile test.simp.utf8 -inputEncoding UTF-8 -sighanPostProcessing true -keepAllWhitespaces false -loadClassifier data/ctb9.train.chris6.ser.gz -serDictionary data/dict-chris6.ser.gz 0
Invoked on Fri Jan 17 00:16:49 PST 2020 with arguments: -sighanCorporaDict ./data -textFile test.simp.utf8 -inputEncoding UTF-8 -sighanPostProcessing true -keepAllWhitespaces false -loadClassifier data/ctb9.train.chris6.ser.gz -serDictionary data/dict-chris6.ser.gz 0
serDictionary=data/dict-chris6.ser.gz
loadClassifier=data/ctb9.train.chris6.ser.gz
sighanCorporaDict=./data
inputEncoding=UTF-8
textFile=test.simp.utf8
sighanPostProcessing=true
keepAllWhitespaces=false
=0
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Resource or file looks like a gzip file, but is not: data/ctb9.train.chris6.ser.gz
        at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:491)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1503)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifierNoExceptions(AbstractSequenceClassifier.java:1516)
        at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:2993)
Caused by: java.util.zip.ZipException: Not in GZIP format

**Comment by lingvisa** [comment]
Hi, John: Do you have a chance to see the error message. I'd love to use it and appreciate!

**Comment by AngledLuffa** [comment]
Your previous message was after midnight Stanford time.  A little patience
would be appreciated.

Serving files was doing something funky with the .gz file.  I put it inside
a .zip and it seems to work:

https://nlp.stanford.edu/~horatio/ctb9.zip

You'll have to extract it from the .zip, of course.

**Comment by lingvisa** [comment]
Hi, John: Seems there is a type casting issue, and simply unzip it and pass it the the command line:

 java -mx2g -cp ./*: edu.stanford.nlp.ie.crf.CRFClassifier -sighanCorporaDict ./data -textFile test.simp.utf8 -inputEncoding UTF-8 -sighanPostProcessing true -keepAllWhitespaces false -loadClassifier data/ctb.gz -serDictionary data/ctb9.train.chris6.ser.gz 0
Invoked on Fri Jan 17 11:02:45 PST 2020 with arguments: -sighanCorporaDict ./data -textFile test.simp.utf8 -inputEncoding UTF-8 -sighanPostProcessing true -keepAllWhitespaces false -loadClassifier data/ctb.gz -serDictionary data/ctb9.train.chris6.ser.gz 0
serDictionary=data/ctb9.train.chris6.ser.gz
loadClassifier=data/ctb.gz
sighanCorporaDict=./data
inputEncoding=UTF-8
textFile=test.simp.utf8
sighanPostProcessing=true
keepAllWhitespaces=false
=0
Loading classifier from data/ctb.gz ... done [5.8 sec].
Loading Chinese dictionaries from 1 file:
  data/ctb9.train.chris6.ser.gz
java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Ljava.util.Set;
  edu.stanford.nlp.wordseg.ChineseDictionary.loadDictionary(ChineseDictionary.java:69)
  edu.stanford.nlp.wordseg.ChineseDictionary.<init>(ChineseDictionary.java:118)
  edu.stanford.nlp.wordseg.ChineseDictionary.<init>(ChineseDictionary.java:98)
  edu.stanford.nlp.wordseg.Sighan2005DocumentReaderAndWriter.init(Sighan2005DocumentReaderAndWriter.java:104)
  edu.stanford.nlp.ie.AbstractSequenceClassifier.makeReaderAndWriter(AbstractSequenceClassifier.java:243)
  edu.stanford.nlp.ie.AbstractSequenceClassifier.defaultReaderAndWriter(AbstractSequenceClassifier.java:118)
  edu.stanford.nlp.ie.AbstractSequenceClassifier.plainTextReaderAndWriter(AbstractSequenceClassifier.java:142)
  edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3067)
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Ljava.util.Set;
	at edu.stanford.nlp.wordseg.ChineseDictionary.loadDictionary(ChineseDictionary.java:72)
	at edu.stanford.nlp.wordseg.ChineseDictionary.<init>(ChineseDictionary.java:118)
	at edu.stanford.nlp.wordseg.ChineseDictionary.<init>(ChineseDictionary.java:98)
	at edu.stanford.nlp.wordseg.Sighan2005DocumentReaderAndWriter.init(Sighan2005DocumentReaderAndWriter.java:104)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.makeReaderAndWriter(AbstractSequenceClassifier.java:243)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.defaultReaderAndWriter(AbstractSequenceClassifier.java:118)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.plainTextReaderAndWriter(AbstractSequenceClassifier.java:142)
	at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3067)
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Ljava.util.Set;
	at edu.stanford.nlp.wordseg.ChineseDictionary.loadDictionary(ChineseDictionary.java:69)
	... 7 more

**Comment by AngledLuffa** [comment]
Hmm, I am not finding the same result when running the previous code
release with the new model.  First, I downloaded the .zip file from the
link I gave and extracted the .gz file from that .zip.  (I heard you like
compressed files...)  Then I ran this command line on my windows machine:

java -cp *;../stanford-chinese-corenlp-2018-10-05-models.jar
edu.stanford.nlp.pipeline.StanfordCoreNLP -props
StanfordCoreNLP-chinese.properties -file ../../codebase/bar.txt
-segment.model ../../codebase/ctb9.train.chris6.ser.gz

Hopefully something similar will work for you.  If not, we will hopefully
be producing a new version of corenlp soon anyway, and the new models will
be available for public use then.

**Comment by lingvisa** [comment]
Sorry. it's my fault. I passed the new model to the segDictionary parameter, which is wrong. I corrected it and it works fine. Another question I am having is to add my new dictionary with the command: java -mx2g -cp ./*: edu.stanford.nlp.wordseg.ChineseDictionary -inputDicts data/dict-chris6.ser.gz,data/foo.txt -output data/dict-chris6.ser.2.gz. However, when I use the new dictionary name "dict-chris6.ser.2.gz" for the model, the running message says that there are only 4 entries in the dictionary, which is wrong. I checked the code of ChineseDictionary, and it seems my command above is the right way to add my dictionary into it. Where is wrong?  If I don't create new dictionary file but just add a new dict file with the parameter --serDictionary, it works fine. I want to create a new single dict file to make it easy for management.

**Comment by AngledLuffa** [comment]
What was the output of running ChineseDictionary?  Because I agree that
should have worked.

**Comment by lingvisa** [comment]
Output is below:

./segment.sh ctb test.simp.utf8 UTF-8 0
(CTB):
-n File: 
test.simp.utf8
-n Encoding: 
UTF-8
-------------------------------
Invoked on Sun Jan 19 20:29:56 PST 2020 with arguments: -sighanCorporaDict ./data -textFile test.simp.utf8 -inputEncoding UTF-8 -sighanPostProcessing true -keepAllWhitespaces false -loadClassifier ./data/ctb.gz -serDictionary ./data/dict-chris6.ser.2.gz
serDictionary=./data/dict-chris6.ser.2.gz
loadClassifier=./data/ctb.gz
sighanCorporaDict=./data
inputEncoding=UTF-8
textFile=test.simp.utf8
sighanPostProcessing=true
keepAllWhitespaces=false
Loading classifier from ./data/ctb.gz ... done [5.5 sec].
Loading Chinese dictionaries from 1 file:
  ./data/dict-chris6.ser.2.gz
  ./data/dict-chris6.ser.2.gz: 4 entries
Done. Unique words in ChineseDictionary is: 4.
Loading character dictionary file from ./data/dict/character_list [done].
Loading affix dictionary from ./data/dict/in.ctb [done].

As you can see,  "Done. Unique words in ChineseDictionary is: 4.", which is wrong, and the testing sentences are barely segmented.

**Comment by AngledLuffa** [comment]
Sorry for any misunderstanding - I meant, what is the result when you try
to build a new dictionary using ChineseDictionary.java

**Comment by lingvisa** [comment]
The log message looks normal:

$ java -mx2g -cp ./*: edu.stanford.nlp.wordseg.ChineseDictionary -inputDicts data/dict-chris6.ser.gz,data/foo.txt -output data/dict-chris6.ser.2.gz
Loading Chinese dictionaries from 2 files:
  data/dict-chris6.ser.gz
  data/foo.txt
  data/foo.txt: 6 entries
Done. Unique words in ChineseDictionary is: 423202.
Serializing dictionaries to data/dict-chris6.ser.2.gz ... 
done.

**Comment by AngledLuffa** [comment]
I am not seeing the same results as you.

c:\Users\horat\nlp\releases\stanford-corenlp-full-2018-10-05>java -cp
*;../stanford-chinese-corenlp-2018-10-05-models.jar
edu.stanford.nlp.wordseg.ChineseDictionary -output foo.ser.gz -inputDicts
../../codebase/foo.txt,edu/stanford/nlp/models/segmenter/chinese/dict-chris6.ser.gz
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary - Loading Chinese
dictionaries from 2 files:
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary -
../../codebase/foo.txt
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary -
edu/stanford/nlp/models/segmenter/chinese/dict-chris6.ser.gz
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary -
../../codebase/foo.txt: 1 entries
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary - Done. Unique words
in ChineseDictionary is: 423201.
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary - Serializing
dictionaries to foo.ser.gz ...
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary - done.


c:\Users\horat\nlp\releases\stanford-corenlp-full-2018-10-05>java -cp
*;../stanford-chinese-corenlp-2018-10-05-models.jar
edu.stanford.nlp.ie.crf.CRFClassifier -sighanCorporaDict
edu/stanford/nlp/models/segmenter/chinese -textFile ../../codebase/foo.txt
-sighanPostProcessing true -keepAllWhitespaces false -loadClassifier
edu/stanford/nlp/models/segmenter/chinese/ctb.gz -serDictionary foo.ser.gz
<snip>
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary - Loading Chinese
dictionaries from 1 file:
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary -   foo.ser.gz
[main] INFO edu.stanford.nlp.wordseg.ChineseDictionary - Done. Unique words
in ChineseDictionary is: 423201.
<snip>

**Comment by lingvisa** [comment]
Just tested and didn't find the issue when running in the full pipeline package, instead of the segmenter package. Thanks for the info.

**Comment by AngledLuffa** [comment]
Good to hear!

**Comment by lingvisa** [comment]
HI, John, a follow-up question regarding the segmenter dictionary: dict-chris6.ser.gz. Those 1-6 characters entries are meaningful words or n-grams? They look like n-grams, but a lot of them indeed are valid words. Could you confirm they are meaningful words extracted from the training data, or they are just ngrams extracted from the training data?  If they are words, just 2-character entries are as big as 125336.

**Comment by AngledLuffa** [comment]
They should all be words.  Do you see some which look like non-words to you?

**Comment by lingvisa** [comment]
I can easily notice some 2-character words which won't be great, normally, like:
归由
胜数
心来
开缺
老而
弄绉
缺顶
肤泛
应负
胡早

3-character:
嫁妆箱
杨岐黄
子模性
磁县都

Do you have a way to get the original sentences where those words occur? They look very unusual, though they lack context.

**Comment by AngledLuffa** [comment]
For the most part we are trying to get 4.0 out the door, so rebuilding the
dictionaries is on the long term list, not the short term list.

Just randomly picking one:

子模性

Is this a math term?

https://sighingnow.github.io/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/submodular.html


 嫁妆箱 seems like two words put together so idk about that one

杨岐黄 is a name, right?

 Seems like there might be some random crap sneaking in but at least some
of these look reasonable.  Anyway, we can look into starting a new
dictionary in a couple weeks
