### ISSUE TITLE
TimeoutException after running for a while

### ISSUE THREAD

**Issue by JohZant** [stanfordnlp/CoreNLP#987]
I have the following error coming up in the console and then it eventually just kills itself.

````[pool-1-thread-2] INFO CoreNLP - [/xxx.xxx.xxx.xx:54536] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:870)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:72)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[pool-1-thread-3] INFO CoreNLP - [/xxx.xxx.xxx.xx:54536] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner
Killed
````

The CoreNLP is running as a dedicated server on a CentOS 7 box and the timeout has been set to 2 minutes. 

The application that I have written sends 100000 characters each time, but if it gets a timed out response from the NLP server, it will half the amount of characters that it sends. It keeps doing this until it gets to below 1000 characters. If it is below 1000 characters and the server is still giving a timed out response, my application will assume that there is something wrong with the text, alert me to the document and move on to the next document.

After the NLP Server has been running for some amount of time, it seems that it can no longer process any text, no matter the size, and I have to manually restart the service.

I'm using 3.9.2

**Comment by AngledLuffa** [comment]
Some of the models don't honor being interrupted, so you may very well be making a backlog of queries which take a long time to get finished using this scheme.  My guess is it would eventually finish.

**Comment by JohZant** [comment]
@AngledLuffa, I am only sending one request at a time and I only send the next request once the NLP Server has responded with a result or an error.

The logs say that the service has been `Killed` so I do not imagine that it would eventually finish what ever it is that it is doing.

**Comment by AngledLuffa** [comment]
From your description, it sounds like the request is timing out, but there
may still be a thread on the server trying to process the request.  You
then send the next request while that thread is still running in the
background.  I'm not trying to suggest the request itself will eventually
succeed, but that the thread is still working and will eventually finish.

The server being killed is consistent with this theory.  It's probably
being killed because it runs out of memory or otherwise exhausts its
resources.

You can test this theory by giving it a query that times out and seeing if
the server is still eating memory and/or CPU

**Comment by JohZant** [comment]
This does make a bit of sense as I have tried to implement a solution where the service will be kicked off again once the NLP server has gone down but there is not enough memory left for the service to start again.

This issue has been closed so I am assuming that there is a solution to this problem?

**Comment by AngledLuffa** [comment]
Unfortunately I guess that wasn't a solution, just an explanation.  I'm not
sure how to best stop it from happening other than send smaller queries.
Making the server more robust to running out of resources would be a medium
term goal rather than a short term plan.

**Comment by JohZant** [comment]
This explains why the NLP server would have issues if I am constantly sending it text that errors out, but it doesn't explain why it has the issue in the first place.

After processing an unspecified amount of documents successfully, it can have troubles with one lot of 100000 characters and then spiral into dying. But after a reboot, the server can all of a sudden handle the exact same 100000 characters that it was having troubles with.

My thoughts would be that the NLP server should get the same result from the same text.

**Comment by AngledLuffa** [comment]
Now that is bizarre, and is not adequately explained by my theory.  I'll
see if I can do something to replicate that tomorrow, but I'm not hopefully
it will be fixed in time for the next release

**Comment by AngledLuffa** [comment]
Hmm, unfortunately I was able to reproduce this in the new version.  I'll
see what I can do to fix it for the next version after this.

**Comment by AngledLuffa** [comment]
I'm coming back around to the idea that this is just a memory problem.  I
implemented some changes which saved almost 1G of RAM, and now this doesn't
happen as much.  Furthermore, when run with the SR parser, which uses
significantly less RAM at runtime, it never seems to happen.  Also, when I
trigger it by running many threads at once, I literally get memory warnings
sometimes instead of more ambiguous errors:

[pool-2-thread-3] WARN edu.stanford.nlp.pipeline.ParserAnnotator - Parsing
of sentence failed, possibly because of out of memory.
I think the answer is just to run with a more restrictive sentence length
limit, add more memory, or switch to the SR parser, which as I said uses
less memory when parsing long sentences.

**Comment by JohZant** [comment]
Good day, @AngledLuffa.

Sorry for the lateness of this reply. Because of COVID, I was moved from the project that I was working on with the NLP server and I have only just been told to get back into it in the last week. I know that this issue was a year ago so it won't be fresh in your mind. I am happy to give any sort of extra information.

I have updated from 3.9.2 to 4.2, started using the SR parser and added a Swapfile and it hasn't fallen over yet but it is pretty close. It is using more than the 6gb of memory that I have told it to and it is contently rising. It has been running for 17 hours and is currently using almost all my RAM.

![image](https://user-images.githubusercontent.com/38639837/114634008-f7ef0980-9d04-11eb-84b1-9e6f83e1efbd.png)

The Centos Box that I am running it on has 8GB of RAM total. Upgrading the RAM would only seem to delay the issue. I also only send a maximum of 10000 characters, which will then get halved every time there is an error. I don't know how much more restrictive I can be. Could you give me ideas on how to restrict this more? I would think that the amount of RAM it is given should be more than enough to process 10000 characters.

Having no idea how the insides work, I would imagine that once it has processed the text it would release the memory and wait for the next lot of text to come through. Is that how it works? or does it hold onto information?

The big thing that I can't get my head around is that it can process 10k characters at a time for hours, and then it will have a memory issue on one lot of 10k characters, which will then be halved and halved again, until it is trying to process under 1000 characters and still fails. Then, when I reboot the server, it will be able to process the exact same set of 10k characters that it was having issues with.

Sorry again for the lateness. Thanks in advance for your help with this.

**Comment by AngledLuffa** [comment]
Any chance you could run jmap or some other heap profiling on your long
running process?

**Comment by JohZant** [comment]
I haven't used this before, so I hope that this is what you are after.

![image](https://user-images.githubusercontent.com/38639837/114641105-d0a03880-9d14-11eb-8315-1e20e1140197.png)


````
Heap Configuration:
   MinHeapFreeRatio         = 40
   MaxHeapFreeRatio         = 70
   MaxHeapSize              = 6442450944 (6144.0MB)
   NewSize                  = 1363144 (1.2999954223632812MB)
   MaxNewSize               = 3865051136 (3686.0MB)
   OldSize                  = 5452592 (5.1999969482421875MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 1048576 (1.0MB)

Heap Usage:
G1 Heap:
   regions  = 6144
   capacity = 6442450944 (6144.0MB)
   used     = 4718453928 (4499.868324279785MB)
   free     = 1723997016 (1644.1316757202148MB)
   73.2400443404913% used
G1 Young Generation:
Eden Space:
   regions  = 2727
   capacity = 4038066176 (3851.0MB)
   used     = 2859466752 (2727.0MB)
   free     = 1178599424 (1124.0MB)
   70.81277590236303% used
Survivor Space:
   regions  = 20
   capacity = 20971520 (20.0MB)
   used     = 20971520 (20.0MB)
   free     = 0 (0.0MB)
   100.0% used
G1 Old Generation:
   regions  = 1772
   capacity = 2383413248 (2273.0MB)
   used     = 1838015656 (1752.8683242797852MB)
   free     = 545397592 (520.1316757202148MB)
   77.11695223404246% used

16614 interned Strings occupying 5990368 bytes.
````

**Comment by JohZant** [comment]
Looking at that screenshot, it seems that the Memory usage has gone down a little and the swapfile is growing slowly. I am trying to read and understand that output from jmap, and from what I can tell, I seem to have a lot of spare space that the java process is not using.

I have always given it 6GB to run with. It has been recommended to me to account for at least 0.5GB of RAM just for the OS when running a Linux box, which leaves me with 1.5GB to play with.

The only things that I run on this box are:

- CoreNLP
- Webmin (Yes, I am very lazy like that)
- Fail2Ban
- FirewallD

None of these ever use even close to 1% of my memory.

**Comment by AngledLuffa** [comment]
Looking through some of these options, I would suggest

- get a histogram: `jmap -histo`

- running jmap (and also the histogram) again in a few hours, see what's
changed

- if it crashes, run jmap at the start, see how it progresses over time

- maybe `jmap -dump:format=b,file=filename` if we don't make any progress

https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr014.html
https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jmap.html

**Comment by JohZant** [comment]
The SR parser and adding the Swapfile seem to have fixed it. I'm pretty new to the world of linux, so I wasn't really sure about it at first. I thought it was some sort of equivalent to the dreaded "readyboost". The swapfile seems to stay between 600MB and 950MB.

I have changed the amount of characters sent to 200000 and so far no errors besides timeouts, which I am handling. It has been running for 1 day and 18 hours and it has processed almost 7k of my files. 

I still feel as though I am being cheated out of some RAM somewhere, but that probably has more to do with my ignorance than anything else.  

Thanks for all your help.

**Comment by AngledLuffa** [comment]
I'm happy to look at the heap profiles though, if you want to send one.
Also, I wonder if the reclamation strategy for the GC is part of the
problem with the chart parser.  It builds very large arrays which almost
definitely count as "humongous", and maybe that leaves the heap fragmented.
