### ISSUE TITLE
CleanXML in Python

### ISSUE THREAD

**Issue by CaptainCapitalizm** [stanfordnlp/CoreNLP#989]
Hello!

When using the CoreNLP Client, I am able to annotate text data using cleanxml. I can't seem to figure out, however,  how to use the cleanxml options (clean.xmltags, clean.docAnnotations, etc) in Python. I've scoured for any documentation on the matter but have not been fortunate in my search. Any help would be much appreciated.

Cheers,
Adrian

**Comment by mcavdar** [comment]
Did you try -p from https://github.com/stanfordnlp/python-stanford-corenlp/blob/master/README.rst#command-line-usage ? I think that it should support props from file like java example [here](https://stanfordnlp.github.io/CoreNLP/human-languages.html) for Chinese.
