### ISSUE TITLE
About sentence and paragraph split

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#990]
Hello, I'm using the annotator `"tokenize, ssplit, pos, lemma, ner"`.
In my simplest pipeline configuration I have

```javascript
{
"tokenize.whitespace": false,
"tokenize.keepeol": false,
"ner.applyFineGrained": false,
"ner.buildEntityMentions": false,
ssplit.isOneSentence": false,
"ssplit.newlineIsSentenceBreak": "always"
}
```

for a text that has bot `\n` and `\n\n` (multiple) new lines character as sentence separator. Using `ssplit.newlineIsSentenceBreak` works ok with both, but when I get the output structure of sentences list, I do not find the `\n\n` line break like in

```
We doin' this once (You yellin' at the mic, your beard's weird)
Why you yell at the mic? (Illa)

Rihanna just hit me on a text
``` 

the output will give me back the three sentences, without considering a empty sentence (matching the `\n\n`):

```javascript
...
{
    "index": 9,
    "text": "Why you yell at the mic? (Illa)",
    "tokens": [ ... ]
  },
  {
    "index": 10,
    "text": "Rihanna just hit me on a text",
    "tokens": [ ... ]
}
```

so when reconstructing the input text from the output I'm missing a blank line and I will get

```
We doin' this once (You yellin' at the mic, your beard's weird)
Why you yell at the mic? (Illa)
Rihanna just hit me on a text
``` 

Any way to handle this internally (without using the input as reference)?

**Comment by AngledLuffa** [comment]
Just to be clear, are you using the python interface that comes with
stanfordnlp, or are you using something else?  If you're using the
stanfordnlp client, the tokens should have "before" and "after" fields
which contain the whitespace you're looking for.

**Comment by loretoparisi** [comment]
@AngledLuffa this is the original Java interface

**Comment by AngledLuffa** [comment]
What interface is that?  I don't recognize that map format.

If you mean the java api, such as by calling StanfordCoreNLP directly,
there should be BeginAnnotation and AfterAnnotation there as well.

**Comment by loretoparisi** [comment]
@AngledLuffa ok thank you, that output is a customer json formatter from the java api. Let me find the `BeginAnnotation` and `AfterAnnotation`.

**Comment by AngledLuffa** [comment]
For posterity, you should be able to reconstruct the missing blank lines using the BeforeAnnotation or AfterAnnotation (sorry, "Begin" was a typo)
