### ISSUE TITLE
StanfordCoreNLPClient fails "silently"

### ISSUE THREAD

**Issue by drewkerrigan** [stanfordnlp/CoreNLP#991]
In `StanfordCoreNLPClient.annotate`, if the server is not running, or some other exception occurs in this catch block: https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/StanfordCoreNLPClient.java#L461-L467 - the exception is logged but the calling function never finds out about it. This is problematic because we end up with an annotation that wasn't annotated, but no way to test if it failed later on.

**Comment by AngledLuffa** [comment]
I merged your change.  Thank you
