### ISSUE TITLE
output.printSingletonEntities parameter doesn't work

### ISSUE THREAD

**Issue by verosol** [stanfordnlp/CoreNLP#996]
I'm using coreNLP for coreference resolution from command line. I need the system to annotate singletons (single mentions) to be able to evaluate the output on my data, which has them annotated. I know that the system was trained on Ontonotes, which doesn't have singletons, but I found this parameter output.printSingletonEntities.

However, adding it into the parameters file changed absolutely nothing, thought I know, I have singletons in my data. What am I doing wrong?

This is my parameter file:

annotators = tokenize,ssplit,pos,lemma,ner,parse,coref

tokenize.whitespace = true

tokenize.options = tokenizePerLine

ssplit.newlineIsSentenceBreak = always

coref.algorithm = neural

filelist = /Users/veronika/Dropbox/data/preprocessing/filelist.txt

output.printSingletonEntities = true

I also tried to call it from command line directly, but the annotation stays the same.

java -cp "" -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLP -props /Users/veronika/Dropbox/data/sampleProps.properties -output.printSingletonEntities true*

**Comment by AngledLuffa** [comment]
It looks like that parameter may only be respected by the xml output
format.    ¯\_(ツ)_/¯

Mind checking if the singletons you expect show up in xml output?  At least
that will help inform us how to proceed.

**Comment by AngledLuffa** [comment]
Following up on this a bit, if you are proficient with java compiling, you
can look here:

...pipeline.TextOutputter.java

look for

        for (CorefChain.CorefMention mention :
chain.getMentionsInTextualOrder()) {
          if (mention == representative)    <-- this is the problem
            continue;

It's currently at line 244 but that may not necessarily be the line number
in the source you have.

If any of this helps and you can send a sample file to make my life easier
debugging this, that would be very helpful.

**Comment by verosol** [comment]
Hi, so basically, for me the coreference annotations are always absent in the CONLL output, so I always do standard xml output and then transform it into CoNLL. There is no annotation of singletons in the xml and thus CoNLLs. You may find attached the txt file I give to the system and the xml output.
for the txt: https://www.dropbox.com/s/fidzb2z71zljz78/xx02.txt?dl=0
for the xml:  https://www.dropbox.com/s/g583sq8j3kp5r7o/xx02.txt.xml?dl=0

As far as I know I use the latest version available on the website 
stanford-corenlp-full-2018-10-05

I can't find this file pipeline.TextOutputter.java in this depository...

**Comment by AngledLuffa** [comment]
I think the issue you have encountered is that the statistical coref
annotators simply don't produce "chains" of length > 1.  The dcoref
annotator does, or you could find some alternate way of extracting the
entities you care about
