### ISSUE TITLE
json.decoder.JSONDecodeError pls help, text size is 355

### ISSUE THREAD

**Issue by yash04singh** [stanfordnlp/CoreNLP#997]
props = {'annotators': 'coref', 'pipelineLanguage': 'en'}
result = json.loads(nlp.annotate(text, properties=props))
[pool-1-thread-4] INFO CoreNLP - [/127.0.0.1:47894] API call w/annotators tokenize,ssplit,pos,lemma,ner,depparse,coref
Strong quarter For the period ending March 31, 2019, the company reported a good set of numbers on the back of better realizations. The companys net profits soared by a whopping 363 percent year-on-year to Rs 6,027 crore. Revenues increased more modestly by 7.5 percent to Rs 28,546 crores. Most brokerages had hiked their target price on the stock, following the companys good set of numbers. Going ahead for 2019-20, as well most brokerages are upbeat on the companys performance and hence the dividend yield. The stock at Rs 218, is not very far from its 52-week low of Rs 211. Decent dividend yield For FY 2018-19, Coal India declared dividend two times. The first was in December 2018, when the company declared a dividend of Rs 7.25 per share, while the second was in Feb 2019, when the company declared a dividend of Rs 5.85 per share. The total dividends declared by the company was Rs 13.1, during FY 2018-19. If you take the current stock price of Rs 218, the dividend yield works close to 6 per cent. What we believe is that the dividends being offered by the company, will be significantly higher than the dividends that were offered in the previous year, ensuring that the dividend yield remains high. Splitting of Coal India may remain an overhang According to reports the government was thinking off spinning off units of Coal India Ltd, into separate listed companies to boost competition and raise government funds. This was as per reports in the Bloomberg. Even if the spin-off does take place, it is likely that Coal India shareholders would get shares in the listed entities. That is only logical. However, as per the reports this is only in an initial stage and no concrete decision is taken in this regards. What makes Coal India attractive at this stage is also the price to earnings ratio, which for 2019-20, could be under 10. Buy the stock for decent dividend yields and gains. Disclaimer This article is strictly for informational purposes only. It is not a solicitation to buy, sell in securities or other financial instruments
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:870)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yashpal/Storage/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/yashpal/Storage/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/yashpal/Storage/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AngledLuffa** [comment]
It timed out.  Doesn't look like it has any particularly long sentences...
Is it running out of memory?  One thing you can do is run the same query
with the same properties directly in StanfordCoreNLP and see if it works or
what errors happen.

**Comment by yash04singh** [comment]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
I had 6gb free memory,
as you said above, I executed this command:
java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -props sampleProps.properties
still it is giving out of memory error I don't know why?
please help

**Comment by AngledLuffa** [comment]
The -Xmx2g is setting how much memory java uses.  It will only use 2g with
those parameters despite having another 6g free

**Comment by yash04singh** [comment]
after doing -Xmx4g I am not getting error, but I'm getting an error when I'm executing with python, 
is there a way i can set memory usage here.
props = {'annotators': 'coref', 'pipelineLanguage': 'en'}
result = json.loads(nlp.annotate(text, properties=props))
because this is giving same error.
please help

**Comment by AngledLuffa** [comment]
Which python interface?  The stanfordnlp interface?

**Comment by AngledLuffa** [comment]
If you are using CoreNLPClient from stanfordnlp, there should be a `memory='4G'` flag or whatever you can set when creating the client.  Hopefully that helps.

**Comment by yash04singh** [comment]
nlp = StanfordCoreNLP(r'stanford-corenlp-full-2018-10-05', quiet=False,memory="4g")
Thanks this is working...
