### ISSUE TITLE
NER tag 'HANDLE'

### ISSUE THREAD

**Issue by hanuellee** [stanfordnlp/CoreNLP#998]
Hi,
I'm using corenlp for NER and noticed the 'HANDLE' tag when tested some text like `hello world @helloworld` (it tags `@helloworld` as HANDLE). But I don't see the docs mentioning this tag. I also can't find it defined in the source. I'm using the TokenRegexNerAnnotator. Could you point me to which model was trained to recognize this tag or where it's defined? And if the 23 tags that are defined in the [docs](https://stanfordnlp.github.io/CoreNLP/ner.html) is not the full list, would it be possible to get the docs updated?
Thank you.

**Comment by AngledLuffa** [comment]
Sounds like the fine grained NER has had twitter handles added.  You could
possibly verify that by setting -ner.applyFineGrained=false

**Comment by hanuellee** [comment]
@AngledLuffa  Is there a full list of fine grained tags defined somewhere?

**Comment by AngledLuffa** [comment]
Glad you found it.  For everyone else's reference, I found a list by doing this:

cut -f 2 edu/stanford/nlp/models/kbp/english/gazetteers/regexner_cased.tab edu/stanford/nlp/models/kbp/english/gazetteers/regexner_caseless.tab | sort | uniq

CAUSE_OF_DEATH
CITY
COUNTRY
CRIMINAL_CHARGE
EMAIL
HANDLE
IDEOLOGY
NATIONALITY
RELIGION
STATE_OR_PROVINCE
TITLE
URL

**Comment by AngledLuffa** [comment]
It would seem HANDLE is the only one missing from the list.  I will update the docs.  Thanks for calling that to our attention
